### ISSUE TITLE
TrimOptions.InsideQuotes unexpected behavior

### ISSUE THREAD

**Issue by Hauptsatana** [JoshClose/CsvHelper#1000]
I have csv file generated by legacy software where some columns have values like **="Some Value&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"** (formula with right-padded value) and file itself is intended to be viewed by Microsoft Excel. Some other columns are left-padded with space and every string column value is quoted.

Example rows:
2358241,"HC04B","=""CRUA01733Z1 ""","=""&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"""
730857,"CNV-121","=""141141206011""","=""MMBJNK7406D058070&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"""
So quotes used in formula columns are escaped by extra quote

When I set `Configuration.TrimOptions = TrimOptions.InsideQuotes` it accidentally removes spaces inside double quotes in formula field, so "=""12345&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;""" becomes `=\"12345\"` Is this option is intended to behave such a way?

Another problem is that value "=""&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;""" returned to TypeConverter is `"=\""` while according to above it is expected be `"=\"\""`. Is it a bug?

**Comment by JoshClose** [comment]
Sorry, for the slow reply. I've had some personal issues that arose that I needed to deal with.

That could be a bug. There is nothing built in that will deal with the `=` prefix though. I removed all Excel specific stuff.

**Comment by JoshClose** [comment]
Thanks. I'll mark as a bug.

**Comment by JoshClose** [comment]
This ended up being quite the troublesome bug to fix. It's fixed an in version 9.2.3 on nuget.
