### ISSUE TITLE
Getting all the header errors

### ISSUE THREAD

**Issue by fleneillon** [JoshClose/CsvHelper#1001]
Hi,
I'm using the ValidationException to catch any errors in the headers. But it is only catching the first one it's finding.
For example: Header matching ['headerName'] names at index 0 was not found.
I would like to know if there's a way to get ALL the errors in headers before catching/throwing it?

**Comment by JoshClose** [comment]
I could change it to go through all the header values before it throws the exception. That would probably be more useful than seeing an error, fixing it, then seeing another. Especially if you're looking at logs from a production system of something.

**Comment by FarshanAhamed** [comment]
@JoshClose Is there any way to get all the missing headers in the `HeaderNames` array of `HeaderValidationException`?

**Comment by JoshClose** [comment]
Not at the moment. You'd have to do a manual check.

**Comment by FarshanAhamed** [comment]
By providing a custom action delegate to the `HeaderValidated` will do the job, correct? Or do you have any other better options?

**Comment by JoshClose** [comment]
This is done and in version 17.0.0 on NuGet. `HeaderValidated` now gets an array of invalid headers.
