### ISSUE TITLE
Validate Headers

### ISSUE THREAD

**Issue by Maquiavelo1408** [JoshClose/CsvHelper#1003]
Hi, I have a question, how can i validate if the headers comes in the file or dont.

**Comment by JoshClose** [comment]
You'll have to do it manually. You're the one that specifies if the file has a header or not, so you need to give the library that info. You could read the first row and check it, then continue.

```cs
csv.Read();
// todo: Check csv.Context.Record and see if it looks like a header to you.
csv.ReadHeader();
var records = csv.GetRecords<MyType>();
```

**Comment by Maquiavelo1408** [comment]
Ok, thanks.
Btw, excellent work, this library has helped me a lot.

**Comment by JoshClose** [comment]
Glad it's helping you!
