### ISSUE TITLE
Exceptions cannot be serialized, even though they are marked serializable

### ISSUE THREAD

**Issue by hurcane** [JoshClose/CsvHelper#1004]
Exceptions are marked with the Serializable attribute. However, they are not actuallly serializable. When an exception needs to be serialized, the following exception occurs:

`The constructor to deserialize an object of type 'CsvHelper.ValidationException' was not found.`

[This StackOverflow question](https://stackoverflow.com/questions/94488) addresses the requirements to have a custom exception class that is serializable.

**Comment by hurcane** [comment]
I took a crack at fixing this issue. However, things start to get really complicated because the exceptions are including the ReadingContext and WritingContext members, which themselves have a deep set of data. 

I was working on making the whole object graph serializable until I hit the MemberMapData class. That includes several Expression properties. Linq expressions are not serializable.

There are workarounds to serialize expressions. However, I wonder whether there is real value in being able to serialize the entire reading and writing context. In practice, serialization is going to occur when the CSVHelper is running in a separate AppDomain or out of process. At runtime, how likely is it the application is going to dig into the details of the context? In my limited experience, the typical usage is simply to log the error message and possibly the call stack.

The other use for the exception is for live debugging. In that case, the exception is usually going to be debugged in the original domain, prior to any serialization. In that scenario, the context properties are useful, and would be available.

If this makes sense, making the exception serializable, but without the ReadingContext and WritingContext properties in the serialized copy, is an easy fix.

**Comment by JoshClose** [comment]
That sounds good to me. Sorry for the slow reply. My house was destroyed in a fire and I've been dealing with that for the past week.

**Comment by JoshClose** [comment]
Fixed. d8de6bdc63d607715db520606af0062c40c30152

This will be in release 8.0.0.
