### ISSUE TITLE
How to get Error Messages while validating in ClassMap

### ISSUE THREAD

**Issue by rb693** [JoshClose/CsvHelper#1005]
I have a csv file with three fields namely Input Code, City, Country Code
```cs
public class Input
{
	public InputCode {get; set;}
	public City {get; set;}
	public CountryCode {get; set;}
	public string Errors { get; set; }
}

public sealed class InputMapper : ClassMap<Input>
{
	public InputMapper()
	{
		Map(m => m.InputCode).Name("Input Code");
		Map(m => m.City).Name("City");
		Map(m => m.CountryCode).Name("Country Code").Validate(code => 
		{
			if (string.IsNullOrEmpty(code))
			{
				errors.Append("CountryCode is null"); // errors can be stringBuilder
			}
			return true;
		});
		Map(m => m.Errors) // Not sure how to map the validation error information to it
	}
}
```
Please let me know if it is allowed...If yes, then how can  I validate each field from the csv file via ClassMapper and if we encounter any error, how to return that?

**Comment by JoshClose** [comment]
`Validate` just throws an exception. If you want a property with all the errors, put all the validation code in `ConvertUsing` on the `Errors` property instead.

**Comment by rb693** [comment]
Thanks Josh .....got it..

**Comment by CoderKooke** [comment]
Hi @rb693 @JoshClose I want to do exactly this but confess I am a little lost at the statement "put all the validation code in `ConvertUsing` statement" comment.  I can't seem to find it in the API documentation so would love a bit of guidance.

By the way.  First time using this library ... it's fantastic @JoshClose .

**Comment by JoshClose** [comment]
Using a similar example:

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	s.AppendLine(",two");
	s.AppendLine("3,three");
	using (var csv = new CsvReader(new StringReader(s.ToString())))
	{	
		csv.Configuration.RegisterClassMap<FooMap>();
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int? Id { get; set; }
	public string Name { get; set; }
	public string Errors { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.Errors).ConvertUsing((IReaderRow row) => 
		{
			var errors = new StringBuilder();
			if (string.IsNullOrEmpty(row.GetField(nameof(Foo.Id))))
			{				
				errors.Append("Id is null");
			}
			
			return errors.ToString();
		});
	}
}
```

![image](https://user-images.githubusercontent.com/114971/53752647-c1333d80-3e74-11e9-8658-6eac87499ad3.png)

**Comment by CoderKooke** [comment]
Thank you @JoshClose .

**Comment by chiranthaw** [comment]
Hi @JoshClose 

Is there a way to validate the duplicate IDs?

Thanks

**Comment by AltruCoder** [comment]
@chiranthaw You could probably take the example, have a running list of Id's and check against that in the ConvertUsing method.

**Comment by chiranthaw** [comment]
@AltruCoder Thanks. I will try :)

**Comment by abidkayanidefra** [comment]
> Hi @rb693 @JoshClose I want to do exactly this but confess I am a little lost at the statement "put all the validation code in `ConvertUsing` statement" comment. I can't seem to find it in the API documentation so would love a bit of guidance.
> 
> By the way. First time using this library ... it's fantastic @JoshClose .

same problem I am facing as new library version doesn't seem to be including ConvertUsing. It has convert thought but it is no where to see how a collection of errors or atleast an extra field (column) can be populated in each row.

**Comment by abidkayanidefra** [comment]
> ```cs
> Map(m => m.Errors).ConvertUsing((IReaderRow row) => 
> 		{
> 			var errors = new StringBuilder();
> 			if (string.IsNullOrEmpty(row.GetField(nameof(Foo.Id))))
> 			{				
> 				errors.Append("Id is null");
> 			}
> 			
> 			return errors.ToString();
> 		});
> ```

Map(m => m.Errors).ConvertUsing((IReaderRow row) => 
		{
			var errors = new StringBuilder();
			if (string.IsNullOrEmpty(row.GetField(nameof(Foo.Id))))
			{				
				errors.Append("Id is null");
			}
			
			return errors.ToString();
		});

this method is not recognized by the Nuget package I have downloaded for csvhelper. ver 33.0.1

also .Errors is not in the CSV file I am  trying to import, hence it is completely ignored by the Mapping logic. I cannot add this column in the CSV file.
