### ISSUE TITLE
NameIndex documentation does not match code.

### ISSUE THREAD

**Issue by mavxg** [JoshClose/CsvHelper#1007]
On http://joshclose.github.io/CsvHelper/mapping#options

```
// Example header
id,name,id

// Mapping
Map( m => m.Id ).Name( "id" ).Index( 1 );
```
That last line should probably say
```
Map( m => m.Id ).Name( "id" ).NameIndex( 1 );
```

If I use the version in the documentation then `IsIndexSet` is `true` and the conditional in ExpressionManager.cs with `!memberMap.Data.IsIndexSet ` stops it doing a name based lookup. In your example I would actually be getting the `name` column into the records `Id` property because `Index` overrides `Name`.

Thanks

**Comment by JoshClose** [comment]
Fixed.
