### ISSUE TITLE
Not able to access the property value from memberMap

### ISSUE THREAD

**Issue by rb693** [JoshClose/CsvHelper#1009]
Hi

I have written an extension method ValidateDataType(errorhandler)  in which I want to validate the Type of data and update the errorHandler in case of any errors.
But I am not able to access the value from MemberMap....How can I do that? 

For example: 
```cs
public class Input
{
	public string InputCode {get; set;}
	public string City {get; set;}
	public decimal CountryCode {get; set;}
}

public sealed class InputMapper : ClassMap<Input>
{
	public InputMapper(ErrorHandler errorHandler)
	{
		Map(m => m.InputCode).Name("Input Code");
		Map(m => m.City).Name("City");
		Map(m => m.CountryCode).Name("Country Code").ValidateDataType(errorHandler)
	}
}

public class ErrorHandler
{
	private List<string> errors = new List<string>();

	public void Log(string error)
	{
		errors.Add(error);
	}
}

public static MemberMap<Terminal, decimal> ValidateDataType(this MemberMap<Terminal, decimal> x, ErrorHandler err)
{
     // How to access the value of CountryCode here  from MemberMap
     // I want to validate the Type of country code and update the errorHandler in case of any error

	return x;
}
```
Please let me know , if there is any other way to do it as well....TIA

**Comment by JoshClose** [comment]
You can't do it that way. The mapping is just metadata that is used to generate expression trees that get compiled and ran as native code.

If you use `MemberMap<TClass, TMember> ConvertUsing( Func<IReaderRow, TMember> convertExpression )` instead, you can supply the `Func<IReaderRow, TMember> convertExpression` that is used like you are trying to do with your extension method. That will give you the current `IReaderRow` for the line it's reading.

```cs
public sealed class InputMapper : ClassMap<Input>
{
	public InputMapper()
	{
		Map(m => m.InputCode).Name("Input Code");
		Map(m => m.City).Name("City");
		Map(m => m.CountryCode).Name("Country Code");
		Map(m => m.Errors).ConvertUsing(row =>
		{
			var errors = new List<string>();
			if (string.IsNullOrEmpty(row.GetField("Country Code")))
			{
				errors.Add("CountryCode is null");
			}
			
			return errors;
		});
	}
}
```

**Comment by rb693** [comment]
you mean I need to add all validations in ConvertUsing and add them to errors?
