### ISSUE TITLE
Documentation does not work over HTTPS

### ISSUE THREAD

**Issue by BobVul** [JoshClose/CsvHelper#1011]
https://joshclose.github.io/CsvHelper/

Does not work in Firefox or Chrome over HTTPS. Looks like none of the JS is loading because they're all hardcoded to use `http://` URLs, which are blocked as mixed content.

Unless it's necessary to support *really* old clients (we're talking IE on XP here), it would probably be best to change all these URLs to `https://` and maybe also [enable enforced HTTPS](https://help.github.com/articles/securing-your-github-pages-site-with-https/)).

If HTTP support is still required for some reason (?), these URLs should at least be changed to be protocol-relative `//` (e.g. `"//joshclose.github.io"`) so they work for people visiting the site over HTTPS.

---

Yes, I know this kind of read-only doc site doesn't really need HTTPS for security, and it's not really a privacy-sensitive resource. In this particular case, it's an [HTTPS Everywhere](https://www.eff.org/https-everywhere) rule that enforces HTTPS on GitHub Pages sites. In other cases, it actually does speed up page loads, since it's a prerequisite for HTTP/2.

**Comment by JoshClose** [comment]
Done.
