### ISSUE TITLE
Create CsvWriter constructor overload taking (TextReader, Configuration, bool) like CsvReader has

### ISSUE THREAD

**Issue by jhorv-scs** [JoshClose/CsvHelper#1013]
Unless this is an intentional omission.

**Comment by JoshClose** [comment]
That is intentional. The writer doesn't need to use the `TextReader`. There is an overload for `CsvWriter( TextWriter, Configuration, bool )` already though.

**Comment by jhorv-scs** [comment]
Thanks Josh, not sure what I was thinking with this one.
