### ISSUE TITLE
csv.GetRecords<dynamic> yields incorrect ExpandoObject (when first field is an empty string)

### ISSUE THREAD

**Issue by TheRouze** [JoshClose/CsvHelper#1014]
I think I have found a bug with the following code when the first csv value is an empty string...

`var records = csv.GetRecords<dynamic>();`

This scenario seems to confuse the parser and you end up with one too few columns in the resulting ExpandoObject with the first column being an amalgamation of the first blank value and a comma and ending in an escaped quotation mark.

Example...
SiteID,DealID,Cap Code
"","B9488254610000OC","MEEC20LMA2BDTA42"

Becomes and ExpandoObject of the form...
SiteID = ,"B9488254610000OC\\"
DealID = "MEEC20LMA2BDTA42"
Cap Code = [MISSING ENTIRELY]

Here's my configuration...

```
internal static void ConfigureCsvReader(CsvReader csvReader)
        {
            csvReader.Configuration.AllowComments = false;
            csvReader.Configuration.CountBytes = false;
            csvReader.Configuration.CultureInfo = CultureInfo.CurrentCulture;
            csvReader.Configuration.Delimiter = ",";
            csvReader.Configuration.DetectColumnCountChanges = false;
            csvReader.Configuration.Encoding = Encoding.UTF8;
            csvReader.Configuration.HasHeaderRecord = true;
            csvReader.Configuration.IgnoreBlankLines = true;
            csvReader.Configuration.IgnoreQuotes = false;
            csvReader.Configuration.HeaderValidated = null;
            csvReader.Configuration.MissingFieldFound = null;
            csvReader.Configuration.TrimOptions = CsvHelper.Configuration.TrimOptions.None;
            csvReader.Configuration.BadDataFound = null;
            csvReader.Configuration.ShouldSkipRecord = (x) => { return !x.Any(y => y.Length > 0); };    // skip rows which have no values at all
        }
```

Could you please try and reproduce or suggest a work around?
I am not in control of the format / contents of these CSV files.

Many thanks!

**Comment by JoshClose** [comment]
It'll work if there is just at LF too. There is currently a bug where things don't work properly when only a CR is used. Follow #914 for a fix.
