### ISSUE TITLE
Required vs Optional headers

### ISSUE THREAD

**Issue by amikulich** [JoshClose/CsvHelper#1017]
Hi Josh,

I'd like to have a possibility (on reading a file) to tell which columns are required (ValidationException should be thrown if header is missing) and which are not. In my opinion the most ideal way would be to extend the `MemberMap` class, so on `ClassMap` we can specify this property:

```
Map(x => x.RequiredColumn).Name("Required Column").Optional(false); // by default Optional == false
Map(x => x.OptionalColumn).Name("Optional Column").Optional(true); 
```

Have you considered this feature might be useful? May be you left this out intentionally, but I would like to consult before making a workaround or forking your library

**Comment by JoshClose** [comment]
If you create a map for the property, then it's required. The validation is there just to know if you mapped something and it isn't in the file.

**Comment by amikulich** [comment]
Thanks for the response.
I faced the case when a file has both: obligatory and optional columns. Therefore I'd like to preserve  validation, but I really needed a way to say that absense of some columns is normal. 

I think this case is pretty common and it would be great to add it to your library. I've committed the code change [here](https://github.com/amikulich/CsvHelper/commit/3d3815c03b80de266081a30b276d4d93ae107b9a), Could you please take a look if you have some time?

**Comment by zolrath** [comment]
I would also love to be able to denote certain Headers/Columns as optional as I am processing spreadsheets that drop some columns depending on a slight context shift.

Sorry to hear about the fire, hope you're doing well!

**Comment by FarshanAhamed** [comment]
@JoshClose Is there any way to avoid throwing exceptions when it fails to parse an Optional field? 
In my case a `DateTime` property is optional, so when I leave the field empty, it is throwing this error `String '' was not recognized as a valid DateTime.`

**Comment by FarshanAhamed** [comment]
@JoshClose Is there any way to avoid throwing exceptions when it fails to parse an Optional field? 
In my case a `DateTime` property is optional, so when I leave the field empty, it is throwing this error `String '' was not recognized as a valid DateTime.`

**Comment by JoshClose** [comment]
@FarshanAhamed Optional means the field is missing completely; not that the value is empty. You can change `DateTime` to `DateTime?` and it will be null for the empty fields.
