### ISSUE TITLE
Use display name instead of the property name

### ISSUE THREAD

**Issue by JacobMathew** [JoshClose/CsvHelper#1018]
Hi Josh,

I am using the Display Name instead of the property name for the csv file header. How do i make the csvhelper use the display name?

Thanks
Jacob

**Comment by JoshClose** [comment]
Do you mean `System.ComponentModel.DisplayNameAttribute`?

**Comment by JacobMathew** [comment]
Yes

**Comment by JoshClose** [comment]
There are attributes in CsvHelper if you want to use them. https://github.com/JoshClose/CsvHelper/tree/master/src/CsvHelper/Configuration/Attributes

There is no built in way to have it use the display name attribute though. You could use reflection to pull them if you want.

**Comment by JacobMathew** [comment]
I am not sure how to use those attributes, because i cannot access attributes inside Configuration.

**Comment by JoshClose** [comment]
I'm a little confused. For the attributes, you'd put them on the class properties, just like you would with `DisplayName`.

**Comment by totht91** [comment]
Related: https://github.com/JoshClose/CsvHelper/issues/585
