### ISSUE TITLE
Encoding no longer an available option for configuration?

### ISSUE THREAD

**Issue by SeanKilleen** [JoshClose/CsvHelper#1019]
Awesome library -- thank you for putting together such a great tool.

I see [in the docs](http://joshclose.github.io/CsvHelper/configuration#encoding) the following example:

```csharp
// Change to whatever the CSV file was encoded in.
csv.Configuration.Encoding = Encoding.Unicode;
```

However, using the current CsvHelper (7.1.0), `Encoding` no longer appears to be available:

> ![image](https://user-images.githubusercontent.com/2148318/39666232-6d132930-506e-11e8-84fe-31e98d86ec50.png)

Is there a new, preferred way to adjust the encoding? Or is this no longer an option?

I'm willing to do a PR for the docs once this is clarified.

**Comment by JoshClose** [comment]
It's only used when reading and counting bytes. You set it to the same encoding you're using in your `TextReader`.

You need to set the encoding you want to use in your `TextWriter`. CsvHelper doesn't care what you have set, it just writes to the writer. When you create your `StreamWriter`, use one of the options that you can pass in the encoding. https://msdn.microsoft.com/en-us/library/system.io.streamwriter.streamwriter(v=vs.110).aspx

**Comment by SeanKilleen** [comment]
I see; that's very helpful, thanks! Closing.
