### ISSUE TITLE
Reading 20GB CSV file

### ISSUE THREAD

**Issue by nkalakon** [JoshClose/CsvHelper#1026]
Hi Josh,

I have to read extremely large CSV files into the memory and store it in list. When i am trying to do that using CSVHelper it is not waiting to complete action it is moving one to next method. 

Is there any size limitation on CSVHelper? For small files this code works perfectly. 
```cs
  using (StreamReader stream = new StreamReader(fileName))
                {
                    using (var reader = new CsvReader(stream))
                    {
                        data = new List<myClass>();
                        reader.Configuration.RegisterClassMap<MyClassMap>();
                        reader.Configuration.WillThrowOnMissingField = false;
                        reader.Configuration.HasHeaderRecord = false;
                        reader.Configuration.IgnoreBlankLines = true;
                        reader.Configuration.SkipEmptyRecords = true;
                        reader.Configuration.Delimiter = delimiter.ToString();
                        data = reader.GetRecords<myClass>().ToList();

                    }
                }
```
Thank you,
Nimmy

**Comment by JoshClose** [comment]
So after this line `data = reader.GetRecords<myClass>().ToList();`, `data` won't contain all the records?

**Comment by nkalakon** [comment]
For smaller files it is but for larger files like 11GB it is moving to next method.

**Comment by JoshClose** [comment]
How many records are in `data`?

**Comment by nkalakon** [comment]
291239552 records

**Comment by nkalakon** [comment]
Sorry I misunderstood your question earlier. There are 291239552  in the CSV file that I am processing.
When i added a line to check to check count of data it returned empty.

**Comment by JoshClose** [comment]
Try not doing a `ToList()` and put it in a loop instead. This will pull one record at a time. Set a break point in the loop and see if you're getting anything that way. If so, make a counter and see how many records it pulls.

**Comment by nkalakon** [comment]
Thank you Josh. 

That seemed to work but it giving different results.
 using (StreamReader stream = new StreamReader(fileName))
                {
                    using (var reader = new CsvReader(stream))
                    {
                        data = new List<MyClass>();
                        reader.Configuration.RegisterClassMap<MyClassMap>();
                        reader.Configuration.WillThrowOnMissingField = false;
                        reader.Configuration.HasHeaderRecord = false;
                        reader.Configuration.IgnoreBlankLines = true;
                        reader.Configuration.SkipEmptyRecords = true;
                        reader.Configuration.Delimiter = delimiter.ToString();
                        while (reader.Read())
                        {
                            data.Add(reader.GetRecord<MyClass>());

                            LogHandler.LogEvent(data.Count().ToString());   
                        }

                        }
                }
As you see below: 

ERCD1000,! 05/10/2018 02:41:13 PM,! NA,! INFO,! **52878**,! 
ERCD1000,! 05/10/2018 02:41:13 PM,! NA,! INFO,! **132123**,! 
ERCD1000,! 05/10/2018 02:41:13 PM,! NA,! INFO,! **85061**,! 
ERCD1000,! 05/10/2018 02:41:13 PM,! NA,! INFO,! **174971**,! 

Am i missing something?

Thank you,
Nirmala

**Comment by JoshClose** [comment]
What does `MyClass` look like? Is that sample data from the CSV file?

**Comment by nkalakon** [comment]
public class MyClass
    {
        public string Name { get; set; }
        public string Status { get; set; }

        public int LineNumber { get; set; }
    }

    public class MyClassMap : CsvClassMap<MyClass>
    {
        public MyClassMap()
        {
            AutoMap();
            Map(m => m.LineNumber).ConvertUsing(row => row.Row);
            Map(m => m.Name).Index(0);
            Map(m => m.Status).Index(1);
            
        }
    }

Yes, it the sample data from CSV. Here are following 2 lines from csv file.

NIMMYYTESt|Testing|
NIMMYYPLAY|Testing|

**Comment by nkalakon** [comment]
Please ignore my question. I made a mistake in the code where two processes are running paralleling and causing an issue. I fixed the issue in my code. 

Is there any size limitation on CSVReader ?

Thank you,
Nimmy

**Comment by JoshClose** [comment]
The only size limitation will be your physical memory. .NET itself may require you to do something to use that much memory at once. There is no limitation imposed by CsvHelper though.

Why do you need to pull the whole file into memory?
