### ISSUE TITLE
Mapping - Adding mapping config and validation dynamically (from JSON??)

### ISSUE THREAD

**Issue by rmddevops** [JoshClose/CsvHelper#1027]
I would like to implement a service that will take CSV file and validate based on file type. I gather that you can create a various classes and then apply. But in order to minimize compile &deployments, is there any way to read a config file, map and validate?  This config file should contain filed mapping including validation rules like - not empty, string, with ###-###-#### format.

Thanks for your help

**Comment by DavidDeSloovere** [comment]
What you can do (and what I've done) is create your .NET map and poco classes on the fly with Roslyn. It's awesome. Check the Pluralsight course by Bart De Smet or search on google on how to create those classes on the fly.

**Comment by JoshClose** [comment]
You can build mappings on the fly. There are many questions regarding this subject in the issues, just search there if you're having trouble. If you can't get it working, let me know.

**Comment by mrcarl79** [comment]
Gotta chip in and say I've been looking for exactly the same @JoshClose having a type of simple json schema file that could be read in would be awesome particularly for validation. Absolutely scoured the internet for something suitable for C#/DOTNET and not found anything decent. We have CSVs sent in from clients and would love some kind of easily readable schema/data contract we can share with clients and say these are the rules and that CsvHelper could also read in.

**Comment by JoshClose** [comment]
You'll have to build that yourself. I don't want to have a dependency on a JSON library. There is a contrib library if you want to commit some code. Maybe a CsvHelper.Json library that has a dependency on JSON.NET or something. https://github.com/CsvHelperContrib/CsvHelperContrib
