### ISSUE TITLE
Constant doesn't work when there is no field in the CSV

### ISSUE THREAD

**Issue by SuperSkippy** [JoshClose/CsvHelper#1030]
I'm trying to write a map that always fills in one field in my output class with a constant value. However I can't, it only works when there is a field in the incoming csv file.

Here's a test for what I want to do. (an additional test in ConstantTests.cs)
```cs
        [TestMethod]
        public void ConstantNoFieldTest()
        {
            var rows = new Queue<string[]>();
            rows.Enqueue(new[] { "Id"});
            rows.Enqueue(new[] { "1"});
            rows.Enqueue(new[] { "2"});
            rows.Enqueue(null);
            var parser = new ParserMock(rows);

            var csv = new CsvReader(parser);
            csv.Configuration.RegisterClassMap<TestStringMap>();
            var records = csv.GetRecords<Test>().ToList();

            csv.Configuration.MissingFieldFound = null;

            Assert.AreEqual(1, records[0].Id);
            Assert.AreEqual("constant", records[0].Name);
            Assert.AreEqual(2, records[1].Id);
            Assert.AreEqual("constant", records[1].Name);
        }
```
(for reference, TestStringMap looks like:

```cs
private sealed class TestStringMap : ClassMap<Test>
		{
			public TestStringMap()
			{
				Map( m => m.Id );
				Map( m => m.Name ).Constant( "constant" );
			}
		}
```

)

**Comment by SuperSkippy** [comment]
Why do I want to do this? I'm letting users define their own mappings in software then storing them in a database so they can use their own CSV file formats. Sometimes their file formats don't have all the fields. In that case the user wants to put in a constant, and that field won't be in the incoming CSV file.

**Comment by JoshClose** [comment]
I'll put this as a feature request. When writing you don't even have to specify a property and it works. I think this might have just been an oversight.

For now, you can do this.

```cs
Map(m => m.Name).ConvertUsing((IReaderRow row) => "the constant");
```

**Comment by marcrocny** [comment]
I haven't looked at the source or blame, but I can't repro this issue with either index or header mapping. I'll add tests to confirm...

**Comment by marcrocny** [comment]
Interestingly, `MemeberMap.Constant()` *does* work if the underlying mapping is index-based. That is, with `csv.Configuration.HasHeaderRecord = false`, and the mapping is performed implicitly or explicitly by index.

**Comment by gandhis1** [comment]
Came across this bug today as I tried to map a CSV to a POCO and add a hard-coded field. I could do it after the fact, but it just seemed cleaner to do it at the point of deserialization, where all of the other properties are set. Maybe I'll try to pick up where #1252 left off.

**Comment by Logopolis** [comment]
I needed this feature today in order to add a Guid FileId to each record as it was being imported, to identify which import file generated the record. Dealing with lots of data so enumerating the records fix them up is not desirable.

Used this workaround:
Map(m => m.FileId).ConvertUsing(row => myGuid);

**Comment by JoshClose** [comment]
Looks like this works in the current version.
