### ISSUE TITLE
Bad Data Found

### ISSUE THREAD

**Issue by AJHopper** [JoshClose/CsvHelper#1035]
Having updated from  fairly old version of CsvHelper (version 2. something) to the newest version, we are now hitting an issue in some of the CSV files it parses.

The files are tab delimited, and fields arent quoted by default so we end up with data like

	UK	607345435	KDU005	Kurio Tab 2 7" Tablet 8GB Android 5.0 Quadcore WiFi	1	58.5000	

the problem is that, in the old version 2.* .. this used to parse fine when reading in, however in the updated version this hits as BadData due to the ".

What im wondering is, since this opens fine into excel etc, and parsed fine on older version of CsvHelper, why is this now bad data?

Would like to resolve this though unsure about just turning BadDataFound to ignore because this is just one of many file formats we get through and Im not sure how that would impact the other file types.

**Comment by beckyconning** [comment]
@AJHopper what was the solution?

**Comment by goors** [comment]
Is there some way to replace the field in question?
