### ISSUE TITLE
Created ClassMap not being recognized by the CsvReader.

### ISSUE THREAD

**Issue by ben-zyne** [JoshClose/CsvHelper#1036]
I created a CustomClassMap that performs batch mapping operations for the declared set of properties. I created it because I don't want to manually set the index of the mapping whenever I updated it. I want its index depend on the order of the items as I declared it. There are no column headers so I cannot use it.

Here is the base class I created:

<?prettify?>
<pre class="prettyprint cpp-html linenums">
public abstract class CustomClassMap&lt;TClass&gt; : ClassMap&lt;TClass&gt; where TClass : class
    {
        protected BatchMappingAction ForPropertySet(Action&lt;PropertySet&gt; action)
        {
            var set = new PropertySet(this);
            action?.Invoke(set);
            return new BatchMappingAction(set);
        }

        protected class PropertySet
        {
            internal PropertySet(ClassMap&lt;TClass&gt; classMap)
            {
                this.classMap = classMap;
                Mappings = new List&lt;MemberMap&gt;();
            }
           
            public PropertySet Property&lt;TMember&gt;(
                Expression&lt;Func&lt;TClass, TMember&gt;&gt; propertyExpr, 
                Action&lt;MemberMap&lt;TClass, TMember&gt;&gt; configureMemberMap = null)
            {
                var propertyInfo = propertyExpr.GetPropertyInfo();
                //Find first from the list of membermaps, if not found, create a mapping.
                var mapping = 
                    classMap.MemberMaps.Find(propertyInfo) ??
                    classMap.Map(propertyExpr);

                //If there's an action delegate provided, invoke it.
                configureMemberMap?.Invoke((MemberMap&lt;TClass, TMember&gt;)mapping);

                Mappings.Add(mapping);
                return this;
            }
          
            public List&lt;MemberMap&gt; Mappings { get; }

            private readonly ClassMap&lt;TClass&gt; classMap;
        }

         protected class BatchMappingAction
        {
            internal BatchMappingAction(PropertySet set)
            {
                memberMaps = set.Mappings.ToList();
            }
            
            public BatchMappingAction MapAsOrdered(int offset = 0)
            {
                for (int i = 0; i &lt; memberMaps.Count; i++)
                    memberMaps[i].Index(i + offset);

                return this;
            }

           //....other code removed for brevity.

            private readonly List&lt;MemberMap&gt; memberMaps;
        }
    }
</pre>

And here is how I use it:
<?prettify?>
<pre class="prettyprint cpp-html linenums">
public sealed class EmployeeDetailsClassMap : CustomClassMap&lt;Employee&gt;
{
        public OperatorDetailsClassMap()
        {
            ForPropertySet(set =&gt; set
                .Property(m =&gt; m.EMPLOYEEID)
                .Property(m =&gt; m.LASTNAME)
                .Property(m =&gt; m.FIRSTNAME)
                .Property(m =&gt; m.USERID)
                .Property(m =&gt; m.ALIAS)
                .Property(m =&gt; m.SALUTATION)
                .Property(m =&gt; m.EMAILADDRESS)
                .Property(m =&gt; m.CONTACTNUMBER)
                .Property(m =&gt; m.JOINEDDATE)
                .Property(m =&gt; m.ENDDATE)
                .Property(m =&gt; m.MANAGEREMPLOYEEID)
                .Property(m =&gt; m.MANAGERUSERID)
                .Property(m =&gt; m.COMPANYCODE)
                .Property(m =&gt; m.DEPARTMENTCODE)
                .Property(m =&gt; m.GROUPCODE)
                .Property(m =&gt; m.SECTIONCODE)
                .Property(m =&gt; m.SHIFT)
                .Property(m =&gt; m.CATEGORY))
            .MapAsOrdered();

            //Map(m => m.EMPLOYEEID).Index(0);
            //Map(m => m.LASTNAME).Index(1);
            //Map(m => m.FIRSTNAME).Index(2);
            //Map(m => m.USERID).Index(3);
            //Map(m => m.ALIAS).Index(4);
            //Map(m => m.SALUTATION).Index(5);
            //Map(m => m.EMAILADDRESS).Index(6);
            //Map(m => m.CONTACTNUMBER).Index(7);
            //Map(m => m.JOINEDDATE).Index(8);
            //Map(m => m.ENDDATE).Index(9);
            //Map(m => m.MANAGEREMPLOYEEID).Index(10);
            //Map(m => m.MANAGERUSERID).Index(11);
            //Map(m => m.COMPANYCODE).Index(12);
            //Map(m => m.DEPARTMENTCODE).Index(13);
            //Map(m => m.GROUPCODE).Index(14);
            //Map(m => m.SECTIONCODE).Index(15);
            //Map(m => m.SHIFT).Index(16);
            //Map(m => m.CATEGORY).Index(17);
      }
}
</pre>

If I use the usual mapping (the commented lines), it's working correctly. 
What am I doing wrong in my base class? Thanks for the help!

**Comment by JoshClose** [comment]
How are you registering the map?

**Comment by ben-zyne** [comment]
Like this: 

<?prettify?>
<pre class="prettyprint cpp-html linenums">
 private void InitializeCsvReaderConfiguration()
        {
            configuration = new Configuration
            {
                Delimiter = ";",
                HasHeaderRecord = false,
                HeaderValidated = null,
                BadDataFound = context => Logger.Warn($"Bad data found on row '{context.RawRow}'", new BadDataException(context)),
                MissingFieldFound = (headerNames, index, context) =>
                {
                    Logger.Warn($"Field with names ['{string.Join("', '", headerNames ?? new[] { "" })}'] at index '{index}' was not found. ", new CsvHelper.MissingFieldException(context));
                },
                ReadingExceptionOccurred = exception => Logger.Error($"Reading exception: {exception.Message}", exception)
            };
            classMaps?.ForEach(configuration.RegisterClassMap);
        }
</pre>

The variable classMaps is being populated by MEF, and I can confirm that it is being populated correctly.

**Comment by JoshClose** [comment]
Ok, this is a lot of code... Can you give me a small contained code example showing this not working?
