### ISSUE TITLE
Change the class mapping for anonymous types

### ISSUE THREAD

**Issue by amoorthaemer** [JoshClose/CsvHelper#1038]
Hi,

When I try to customize the class mapping for an anonymous type I get the error

**CsvHelper.ReaderException: 'No members are mapped for type ..."**

I create a custom class map by creating a new class map type from DefaultClassMap<T> and performing Map() methods to map the required properties. 

NOTE: If I use AutoMap everything works as expected

Cheers
Bert

**Comment by JoshClose** [comment]
Can you give me an example?
