### ISSUE TITLE
CsvWriter throws NullReferenceException when Dispose is called more than once.

### ISSUE THREAD

**Issue by casperOne** [JoshClose/CsvHelper#1040]
NuGet Version: 7.1.0

When `Dispose` is called more than once on the `CsvWriter` class, it throws a `NullReferenceException`.

`Dispose` shouldn't throw, (this was laid out in #954 as well).

Here's a gist that contains a simple test that shows the failure.

https://gist.github.com/casperOne/ef98a0f9a224b6663d0408a595dfb5e5

**Comment by JoshClose** [comment]
Done. cba1e11c3e04c9b0946e578df2873daa45361ce0
