### ISSUE TITLE
Question Reading / Writing List<T>

### ISSUE THREAD

**Issue by tsage2012** [JoshClose/CsvHelper#1041]
I wrote a wrapper around the CsvHelper to read and write Csv data. 

Here is the write method:

```cs
        public void Write<T>(string fileName, List<T> entities) where T : class
        {
            using (var writer = new StreamWriter(_fileSystemAdapter.FileStreamForWritting(fileName)))
            using (var csvWriter = new CsvWriter(writer, _configuration))
            {
                csvWriter.WriteHeader<T>();
                csvWriter.NextRecord();
                csvWriter.WriteRecords(entities);
                csvWriter.Flush();
            }
        }
```

Here is the Read method:

```cs
        public List<T> Read<T>(string fileName) where T : class
        {
            using (var csvReader = new CsvReader(_fileSystemAdapter.OpenText(fileName), _configuration))
            {                
                return csvReader.GetRecords<T>().ToList();
            }
        }
```

Configuration Info for the wrapper class:

```cs
       _configuration =
                new Configuration {Delimiter = delimiter, HasHeaderRecord = true, MissingFieldFound = null};
      _configuration.RegisterClassMap<TMapper>();
```

The issue I am having is exposed during a unit test. After writing the content, when I read it back, I am getting all but the last record. So, if I write 3 records, I get the first 2. If I write 10 records, then I get back the first 9.

Does anything stand out in this code that highlights what I am missing to get all the data back from the read?

Thanks,
Tim

**Comment by KevinHoward** [comment]
I haven't done any testing with the provided code, but at first glance wouldn't the csvWriter.NextRecord() call in your write method push the iterator to the second record and then the following writer would start from there?

**Comment by tsage2012** [comment]
Are you referring to the call to nextrecord after writeheader? Should I
just call writerecords without the call to writeheader?

**Comment by JoshClose** [comment]
Write it to a `string` and see if all the data is there.

```cs
void Main()
{
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Id = 1, Name = "one" },
			new Test { Id = 2, Name = "two" },
		};
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);
		writer.Flush();
		
		writer.ToString().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```

You need to figure out if it's the writing or the reading that is causing the problem.
