### ISSUE TITLE
CsvHelper.MissingFieldException: Field with names ['Name'] at index '0' does not exist.

### ISSUE THREAD

**Issue by Morph12345** [JoshClose/CsvHelper#1045]
Hi, 
I have an issue while reading my csv using the header name. I saw some people with the same error but none of the solution works for me on my very simple example.

My CSV (one column) :
```
Name  
My name value1  
My name value2
```
My code :
```cs
using (var sr = new StreamReader(source))
            using (var csv = new CsvReader(sr))
            {
                while (csv.Read())
                {
                    var name = csv.GetField<string>("Name");
                }
            }
```
I get the "Field with names ['Name'] at index '0' does not exist." on the line "var name=..."

The reading is working with GetField(int index) but not with the header name.
I tried to change the separator (even if i'm working with only one column for now) but it didn't change anything.

Strange thing, the HasHeaderRecord is set to true (I tried to set it directly even if default is true), but while i'm reading the file with getField(int index), the first line is "Name". Is it normal ? The HasHeaderRecord=true doesn't mean the data start at line 2 ? Maybe this is a lead to the problem.

Thanks for your help :)

**Comment by NickStrupat** [comment]
I'm having the same issue.

**Comment by JoshClose** [comment]
If you're looping the rows yourself and there is a header, you'll need to call `ReadHeader`.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Name");
		writer.WriteLine("one");
		writer.WriteLine("two");
		writer.Flush();
		stream.Position = 0;

		csv.Read();
		csv.ReadHeader();
		while (csv.Read())
		{
			csv.GetField("Name").Dump();
		}
	}
}
```

**Comment by MMOSimca** [comment]
I created a new issue to help clarify this kind of misunderstanding somewhat. The exception wording for this problem really doesn't tell the user what is wrong or how to fix it.

https://github.com/JoshClose/CsvHelper/issues/1070

**Comment by JoshClose** [comment]
More clear messages have been added. Details in #1070.
