### ISSUE TITLE
Pipelines, Span, and Memory

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#1048]
Look into using these.

https://github.com/indy-singh/StringsAreEvil/pull/1

**Comment by meghuizen** [comment]
Let me nerdsnipe you a bit more, though your headers says something about pipelines as well: https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html  and  https://blog.marcgravell.com/2018/07/pipe-dreams-part-2.html

**Comment by JoshClose** [comment]
The parser was redone with massive speed improvements. It turns out that using `Span` and `Memory` wasn't faster, so they ended up not being used. https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers

**Comment by NickLarsen** [comment]
How did the use of pipelines affect allocations and peak memory usage?

**Comment by JoshClose** [comment]
I honestly don't remember. :(
