### ISSUE TITLE
CSVHelper find if any column is empty

### ISSUE THREAD

**Issue by nkalakon** [JoshClose/CsvHelper#1050]
Hi Josh,

Is there any way to check if any fields value are empty, instead of going through each and every row to find that particular row has empty values for some fields? 

ID Name
1  Nimmy
2   
3 Josh

In the above example, is there any way to find out that particular column has empty strings? 

Thank you,
Nirmala

**Comment by JoshClose** [comment]
No. The only way that would be possible is if the data was indexed liked a database.
