### ISSUE TITLE
CsvHelper V 2.16.3 error on Writing

### ISSUE THREAD

**Issue by sergiOO7** [JoshClose/CsvHelper#1051]
Hi All, I want to write errors into a log file using csvWriter, but I get an error : **"CsvHelper.Configuration.CsvConfigurationException: 'Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?'"**

I'm trying to read from a text file and write the row that errors into a different file.

Thank you
The code:
.NET CORE 1.0.1

```cs
private readonly TextWriter writer;

...
writer = File.CreateText(@"C:\errors\logs");
StreamReader file = File.OpenText(<Directory of the File i'm reading>);
var csvP = new CsvReader(file)

csvP.Read;
string[] row = new string[] { };
try{
var row = csvP.Parser.Read();
}catch(Exception e){
using (var csv = new CsvWriter(writer))
{ 
  csv.WriteRecords(row)
}
```

**Comment by JoshClose** [comment]
`WriteRecords` is meant for writing objects. If all you want to do is write an array of strings, use `CsvSerializer` instead.

**Comment by sergiOO7** [comment]
Thank you @JoshClose
