### ISSUE TITLE
Setting NumberDecimalDigits not working?

### ISSUE THREAD

**Issue by amyblank** [JoshClose/CsvHelper#1052]
I'm trying to limit the number of digits after the decimal place. I don't much care about trailing zeroes, but I do want to clip or round the extra decimal digits. Here's an example.

```
// Create a new invariant culture
CultureInfo culture = new CultureInfo ("");
// Limit the number of decimal digits
culture.NumberFormat.NumberDecimalDigits = 3;
culture.NumberFormat.PercentDecimalDigits = 3;
CsvConfiguration conf = new CsvConfiguration ();
conf.CultureInfo = culture;

// Open up the test.csv file
using (TextWriter writer = File.CreateText(@"my_test.csv")) {
    var csv = new CsvWriter (writer, conf);
    var records = new List<double> ();
    records.Add (1);
    records.Add (1.00002);
    records.Add (1.523468);
    csv.WriteRecords (records);
}
```

What I want from this is one of the following results:
```
1
1
1.523
```
OR
```
1.000
1.000
1.523
```

But what I'm getting is this:
```
1
1.00002
1.523468
```

Can you give me any advice? Thanks!

**Comment by amyblank** [comment]
Forgot to add, I'm using CsvHelper 2.0 and .Net 3.5 on Ubuntu 16.04

**Comment by JoshClose** [comment]
Which version of 2? 2.0.0? Or the later 2.16.3?

**Comment by amyblank** [comment]
Sorry, it's version 2.0.0

**Comment by JoshClose** [comment]
You just want to write a list of doubles? You don't want to write a custom class object?

**Comment by amyblank** [comment]
We're doing a custom class object, I just simplified to see if I could narrow in on the problem. We're using floats typically, but I get the same behavior for doubles. This is our custom class:

```
public class DataPoint
    {
        public float Timestamp { get; set; }
        public float MotorPos1 { get; set; }
        public float MotorPos2 { get; set; }
        public float MotorPos3 { get; set; }
        public float MotorTrq1 { get; set; }
        public float MotorTrq2 { get; set; }
        public float MotorTrq3 { get; set; }
        public int MotorEnc1 { get; set; }
        public int MotorEnc2 { get; set; }
        public int MotorEnc3 { get; set; }
        public int JointEnc1 { get; set; }
        public int JointEnc2 { get; set; }
        public int JointEnc3 { get; set; }
        public float JointEncAng1 { get; set; }
        public float JointEncAng2 { get; set; }
        public float JointEncAng3 { get; set; }
        public float MotorAngFromJoint1 { get; set; }
        public float MotorAngFromJoint2 { get; set; }
        public float MotorAngFromJoint3 { get; set; }

        // Default Constructor
        public DataPoint () {}

        // Registers the tool and joint data
        public DataPoint (float Timestamp_, Vector3 MotorPos_, Vector3 MotorTrq_, List<int> MotorEnc_,
            List<int> JointEnc_, Vector3 JointEncAng_, Vector3 MotorAngFromJoint_)
        {
            Timestamp = Timestamp_;
            MotorPos1 = MotorPos_ [0];
            MotorPos2 = MotorPos_ [1];
            MotorPos3 = MotorPos_ [2];
            MotorTrq1 = MotorTrq_ [0];
            MotorTrq2 = MotorTrq_ [1];
            MotorTrq3 = MotorTrq_ [2];
            if (MotorEnc_.Count >= 3) {
                MotorEnc1 = MotorEnc_ [0];
                MotorEnc2 = MotorEnc_ [1];
                MotorEnc3 = MotorEnc_ [2];
            }
            if (JointEnc_.Count >= 3) {
                JointEnc1 = JointEnc_ [0];
                JointEnc2 = JointEnc_ [1];
                JointEnc3 = JointEnc_ [2];
            }
            JointEncAng1 = JointEncAng_ [0];
            JointEncAng2 = JointEncAng_ [1];
            JointEncAng3 = JointEncAng_ [2];
            MotorAngFromJoint1 = MotorAngFromJoint_ [0];
            MotorAngFromJoint2 = MotorAngFromJoint_ [1];
            MotorAngFromJoint3 = MotorAngFromJoint_ [2];
        }
    }
```

**Comment by JoshClose** [comment]
```cs
void Main()
{
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Number = 1F },
			new Test { Number = 1.00002F },
			new Test { Number = 1.523468F },
		};
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);
		
		writer.Flush();		
		writer.ToString().Dump();
	}
}

public class Test
{
	public float Number { get; set; }
}

public class TestMap : CsvClassMap<Test>
{
	public override void CreateMap()
	{
		Map(m => m.Number).TypeConverterOption("0.00");
	}
}
```
Here are links for the formatting that you can use.
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings
https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings

**Comment by amyblank** [comment]
Awesome, thank you! This works perfectly.

**Comment by bjaeken** [comment]
Hi, 

In my csv file I have a decimal: 12.8570
But I get some errors.

**My model:** 
`public decimal SAMPLE_POSITIVE_PERCENT { get; set; }`
**Mapping:**
`Map(m => m.SAMPLE_POSITIVE_PERCENT).Default("0.0000");`

**Controller:**
` List<QPCatDetViewModel> QPCatDetView = new List<QPCatDetViewModel>();
            TextReader readQP = new StreamReader(@"CSV/QPCategoryDetails.csv");
            var csvQP = new CsvReader(readQP);
            csvQP.Configuration.HasHeaderRecord = false;
            csvQP.Configuration.TypeConverterOptionsCache.GetOptions(typeof(decimal)).NumberStyle = NumberStyles.AllowThousands | NumberStyles.AllowDecimalPoint | NumberStyles.AllowTrailingSign;
            QPCatDetView = csvQP.GetRecords<QPCatDetViewModel>().ToList();
            csvQP.Configuration.RegisterClassMap<QPCatDetViewModelMap>();
            csvQP.Configuration.Delimiter = ",";`

When I use the following, NO dot will show. And when I try to add the 
`.TypeConverterOption("0.00");` @JoshClose recommended **doesn't** work.

When I remove the the following out of my controller:
`            csvQP.Configuration.TypeConverterOptionsCache.GetOptions(typeof(decimal)).NumberStyle = NumberStyles.AllowThousands | NumberStyles.AllowDecimalPoint | NumberStyles.AllowTrailingSign;
`
 I recieve this error:
CsvHelper.TypeConversion.TypeConverterException: 'The conversion cannot be performed.
    Text: '12.8570'
    MemberType: System.Decimal
    TypeConverter: 'CsvHelper.TypeConversion.DecimalConverter''

**Comment by JoshClose** [comment]
I'll reply to your other thread. #1125
