### ISSUE TITLE
NullableConverter how to provide TypeConverterCache?

### ISSUE THREAD

**Issue by NecroFilja** [JoshClose/CsvHelper#1053]
Hello,

I am trying to migrate from version 2.XX to latest.
We have a lot of map derived classes with code like:

```
public sealed class MyClassMap : ClassMap<MyClass>
{
    public MyClassMap()
    {
        var intNullableConverter = new CsvHelper.TypeConversion.NullableConverter(typeof(double?));
		Map(m => m.Field).Index(2).TypeConverter(intNullableConverter);
    }
}
```

from latest versions NullableConverter requires TypeConverterCache which could be retrieved from CsvReader through configuration. Does it means that I need to update constructors of all ClassMaps to include dependency on Configuration? Are there any better ways?

**Comment by JoshClose** [comment]
Do you have a custom converter? If you just need to convert the field to a `double?`, you don't need to specify a converter. It'll do it for you automatically.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name");
		writer.WriteLine(",one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int? Id { get; set; }
	public string Name { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```
![image](https://user-images.githubusercontent.com/114971/41549413-6620beae-72eb-11e8-9fa6-1d4e73195547.png)

**Comment by NecroFilja** [comment]
Hello,

No I haven't custom converter.
Was something changed from v2.XX? Because I do remember in 2.X I have a lot of problems without NullableConverter. For which case now it is supposed to use NullableConverter?

**Comment by JoshClose** [comment]
If your type is `Nullable<T>`, so `int?` or `decimal?`, etc, everything should just work. You shouldn't have to specify or create a converter for that.

**Comment by ryanwilliams83** [comment]
public class NullableBooleanAsUpperConverter : NullableConverter
{
    private static readonly TypeConverterCache TypeConverterCache;

    static NullableBooleanAsUpperConverter()
    {
        TypeConverterCache = new TypeConverterCache();
        TypeConverterCache.AddConverter<bool>(new BooleanAsUpperConverter());
    }

    public NullableBooleanAsUpperConverter()
        : base(typeof(bool?), TypeConverterCache)
    {
    }
}
