### ISSUE TITLE
Simple DateTime Conversion? 

### ISSUE THREAD

**Issue by chadbruels** [JoshClose/CsvHelper#1054]
The last version I used was 2.16.3 and at that time I was able to achieve a date conversion when reading via: 

`Map(m => m.BatchDate).Index(2).TypeConverterOption("yyyy-MM-dd");`

Having reviewed the documentation I still don't understand how I can implement a simple type conversion.

**Comment by JoshClose** [comment]
It would look like this now.
```cs
Map(m => m.BatchDate).Index(2).TypeConverterOption.Format("yyyy-MM-dd");
```

**Comment by chadbruels** [comment]
Thank you. Would you also answer a follow-up. I'm still getting an inner exception of "String was not recognized as a valid DateTime." There are rows where date columns have no value. Would these likely be the culprit or something else?

**Comment by chadbruels** [comment]
I believe I have this working now. I did switch to a `DateTime?` property and then set all my date field mappings to: 

`Map(m => m.AllocationFromDate).Index(59).Default(new DateTime(1900, 1, 1));`

Thank you for your time and brain power.
