### ISSUE TITLE
How to handle bad escaping of double quotes - \"

### ISSUE THREAD

**Issue by magnusakselvoll** [JoshClose/CsvHelper#1055]
Hi,

I am trying to parse the following file: https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat

The following line is causing issues for me:
`332,"Magdeburg \"City\" Airport","Magdeburg","Germany",\N,"EDBM",52.073612,11.626389,259,1,"E","Europe/Berlin","airport","OurAirports"
`

As you can see, the authors use \\" instead of "" for inserting a double quote inside a quoted string. Do you have any suggestions on how to fix this, except asking the author to adhere to CSV standards?

Cheers,
Magnus Akselvoll

**Comment by JoshClose** [comment]
You could replace all the `\"` with `""` before running it through CsvHelper.

**Comment by JoshClose** [comment]
The issue here is it's mixed. `"` is used to escape a field, but `'` is used to escape the quote in the field.

**Comment by magnusakselvoll** [comment]
Hi Josh (and thanks for the quick replies),

The problem with replacing the characters is that I am reading this in a stream and found no simple way of doing just that.

Any other suggestions except talking to the author?
