### ISSUE TITLE
Custom `BuildRequiredQuoteChars` is only used if you change the delimiter

### ISSUE THREAD

**Issue by CodingGorilla** [JoshClose/CsvHelper#1057]
Maybe I'm misunderstanding the purpose of this configuration function, but I wanted to use it to force certain strings to be quoted.  Simply setting this property on the `Configuration` has no effect at all.  I had to do the following to force it to be evaluated:

```
var config = new Configuration
			 {
				 BuildRequiredQuoteChars = () => new[] { ' ', ',', '\r', '\n' },
				 Delimiter = ","
			 };
```

Is this by design, or is there something else that I'm missing?

**Comment by ili101** [comment]
Thank you @CodingGorilla, I tried to use it too and would never have figured out why it's not working without your post.
Very confusing behavior.
``` PowerShell
$StreamWriter = [System.IO.StreamWriter]::new('test.csv', $false, [System.Text.Encoding]::UTF8)
$CsvWriter = [CsvHelper.CsvWriter]::new($StreamWriter)

$CsvWriter.Configuration.BuildRequiredQuoteChars = [System.Func[Char[]]] {'X'}
'Before setting Delimiter:' + ($CsvWriter.Configuration.QuoteRequiredChars | Out-String)
$CsvWriter.Configuration.Delimiter = ','
'After setting Delimiter:' + ($CsvWriter.Configuration.QuoteRequiredChars | Out-String)
```
Output:
```
Before setting Delimiter:


,

After setting Delimiter:X

```

**Comment by JoshClose** [comment]
This should be called if the `BuildRequiredQuoteChars` function changes, or if the `Delimiter` changes.

**Comment by JoshClose** [comment]
I removed config options `QuoteAllFields`, `QuoteNoFields`, `QuoteRequiredChars`, and `BuildREquiredQuoteChars` in favor of `ShouldQuote` function. This makes things a lot less confusing.

This is in version 11.0.0 on nuget.
