### ISSUE TITLE
CSVHelper to skip record before header

### ISSUE THREAD

**Issue by meghma** [JoshClose/CsvHelper#1059]
Hi Josh,
This is a how to question - not an issue really but something I would really appreciate some help with.
I have  a record before he header record that I need to skip and a record at the end like and end of file record. 
I posted at stackoverflow also

https://stackoverflow.com/questions/51044949/csvhelper-to-skip-record-before-header

Thanks so much!
Anand

**Comment by JoshClose** [comment]
Answered.
