### ISSUE TITLE
 Attempt by method 'DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Reflection.RuntimePropertyInfo)' to access type 'System.Reflection.RuntimePropertyInfo' failed.

### ISSUE THREAD

**Issue by ChrisSorel** [JoshClose/CsvHelper#1068]
When I try to run CSV Helper in a partial-trust sandboxed environment, (Dynamics CRM Online) it gives me this error. 
 Attempt by method 'DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, System.Reflection.RuntimePropertyInfo)' to access type 'System.Reflection.RuntimePropertyInfo' failed.

at CsvHelper.ReflectionHelper.CreateInstanceWithoutContractResolver(Type type, Object[] args)   at CsvHelper.ObjectResolver.Resolve(Type type, Object[] constructorArgs)   at CsvHelper.ReflectionHelper.CreateInstance(Type type, Object[] args)   at CsvHelper.ReflectionHelper.CreateInstance[T](Object[] args)   at CsvHelper.Configuration.Configuration.RegisterClassMap[TMap]()

Running the same code locally works flawlessly.

Edit using v7.1.1 against .Net Framework 4.6.1

**Comment by ChrisSorel** [comment]
Thanks for the suggestions. Made both of the changes and got a new error:

Request for the permission of type 'System.Security.Permissions.ReflectionPermission, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' failed.
at System.Delegate.DelegateConstruct(Object target, IntPtr slot) 
at [redacted].<getBulkDataResult>d__7.MoveNext()

My Code is:

```
StringReader reader = new StringReader(responseString);
Configuration config = new Configuration();
config.Delimiter = "|";
config.HasHeaderRecord = true;
config.MissingFieldFound = null;
var csv = new CsvReader(reader, config);
...
ObjectResolver.Current = new ObjectResolver(type => true, Activator.CreateInstance);
csv.Configuration.RegisterClassMap(new CustomerInsightClassMap());
List<CustomerInsight> cirecords = csv.GetRecords<CustomerInsight>().ToList<CustomerInsight>();
```
I ended up creating the objects manually and populating with TryGetField

**Comment by JoshClose** [comment]
If you don't have access to reflection, I think that's your only option. 

You're still able to do things like `GetField<DateTimeOffset>("name")` and take advantage of the type conversion.
