### ISSUE TITLE
Improve Exception Message when Reading Fields by Field Name Fails Because Header is Unread

### ISSUE THREAD

**Issue by MMOSimca** [JoshClose/CsvHelper#1070]
```
                using (MemoryStream ms = new MemoryStream(File.ReadAllBytes(filePath)))
                using (TextReader sr = new StreamReader(ms, true))
                using (CsvReader cr = new CsvReader(sr, new CsvHelper.Configuration.Configuration() { HasHeaderRecord = true, Delimiter = "," }))
                {
                    while (cr.Read())
                    {
                        UserPaymentCsvRow r = new UserPaymentCsvRow();

                        r.Name = cr.GetField("Name");
                        r.Company = cr.GetField("Company");
                        r.AddressLine1 = cr.GetField("Address Line 1");
                        r.AddressLine2 = cr.GetField("Address Line 2");
                        r.City = cr.GetField("City");
                        r.State = cr.GetField("State");
                        r.ZipCode = cr.GetField("Zip Code");
                        r.Country = cr.GetField("Country");
                    }
                }
```

Code like the above (mainly pre-3.0 legacy code in need of fixing) throws a fairly unhelpful error message:
>CsvHelper.MissingFieldException: 'Field with names ['Name'] at index '0' does not exist. You can ignore missing fields by setting MissingFieldFound to null.'

It should just say something like this (either with the same exception class, a new one, or a different one): 
>"Cannot read fields by name if the header of the file has not been read yet. You should call Read() and ReadHeader() first."

**Comment by JoshClose** [comment]
Changes in version 9.2.0 on nuget.

If you try to get a field by name and the header hasn't been read yet, you'll get a `ReaderException` with message
> The header has not been read. You must call ReadHeader() before any fields can be retrieved by name.

The rest of the exceptions are `MissingFieldException`.

If you try to get a field by a index that doesn't exist
> Field at index '4' does not exist. You can ignore missing fields by setting MissingFieldFound to null.

If you try to get a field by a single name that doesn't exist
> Field with name 'missing' does not exist. You can ignore missing fields by setting MissingFieldFound to null.

If you try to get a field by a single duplicate name that doesn't exist
> Field with name 'missing' at field index '2' does not exist. You can ignore missing fields by setting MissingFieldFound to null.

If you try to get a field by multiple names that doesn't exist
> Field containing names 'first' or 'second' does not exist. You can ignore missing fields by setting MissingFieldFound to null.

If you try to get a field by multiple duplicate names that doesn't exist
> Field containing names 'first' or 'second' at field index '2' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
