### ISSUE TITLE
Not displaying quotes on dynamic objects

### ISSUE THREAD

**Issue by OriginLive** [JoshClose/CsvHelper#1072]
I'm trying to output the same format as i got it in:
"skale";200130.190080;10189.550121;170.000000;0.000000;0.000000;0.720000;0.000000;

However, the output format escapes quotes on string, if it was loaded in dynamically 
skale,200130.190080,10189.550121,170.000000,0.000000,0.000000,0.720000,0.000000

If csv_values.Configuration.IgnoreQuotes = true; then the output is:

"""skale""",200130.190080,10189.550121,170.000000,0.000000,0.000000,0.720000,0.000000

**Comment by JoshClose** [comment]
It won't write quotes unless they're needed. You can turn on `Configuration.QuoteAllFields` to have them all quoted. There is currently no way to specify on a field level to always quote.
