### ISSUE TITLE
Confusing interaction of ConvertUsing and Ignore properties?

### ISSUE THREAD

**Issue by FireEater64** [JoshClose/CsvHelper#1074]
If I have a `MemberMap`, which maps a property, providing both the `Ignore` flag and a `ConvertUsing` expression - I seem to get some interesting behaviour:

```csharp
private sealed class TestRecordMap : ClassMap<TestRecord>
{
    public TestRecordMap(bool shouldIgnoreColumn)
    {
        Map( m => m.IntColumn ).Name( "Int Column" );
        Map( m => m.IgnoredColumn ).Ignore(shouldIgnoreColumn).ConvertUsing(x => x.AnotherProperty ? x.IgnoredColumn : "Nothing");
    }
}
```

In this scenario, I'd expect to only see the first column in the csv

```csv
Int Column
1
2
3
```

But instead - whilst no header is written for the ignored property, the value *is* written:

```csv
Int Column
1, ignore me
2, ignore me
3, ignore me
```

This seem to be due to the fact that custom conversion expressions are invoked before the `Ignore` flag for a member is checked

https://github.com/JoshClose/CsvHelper/blob/d8de6bdc63d607715db520606af0062c40c30152/src/CsvHelper/Expressions/ObjectRecordWriter.cs#L58-L72

However, when writing the headers, there are no custom expressions, so the `Ignore` flag is honoured

https://github.com/JoshClose/CsvHelper/blob/d8de6bdc63d607715db520606af0062c40c30152/src/CsvHelper/CsvWriter.cs#L333-L336

I might be totally off-base here, but it feels like either the `Ignore` flag should be checked before invoking custom expressions when writing members, or headers should be written for members that have both `ConvertUsing` and `Ignore` properties defined. I'd be interested to hear peoples thoughts though - happy to be told I'm "doing it wrong" 😄

**Comment by JoshClose** [comment]
Yeah, the header and fields should at least be consistent. 

If you're ignoring a property, why do you also have a `ConvertUsing` in place? I guess I never even thought of testing this scenario.

**Comment by JoshClose** [comment]
After looking through the code and thinking about this, I think it's doing it the correct way right now. The reason is, supplying a `ConvertUsing` expression will override **everything**. You're supplying the code that is ran and none of the other configuration is used. `Ingore` is just a configuration value.

**Comment by Tirraon** [comment]
@JoshClose 
If ConvertUsing().Ignore() works as expected, so how we can ignore specified field by condition and convert it, if it should be visible?
For example:
```csharp
Map(m => m.StartTime).Ignore(!requiredfields.Contains("StartTime")).ConvertUsing(/*convert timezone or other operation with StartTime */).Name("Start Time");
Map(m => m.FirstName).Ignore(!requiredFields.Contains("FirstName")).Name("First Name");
```

I know, that we can use TypeConverter, but with it we need to create new converters for every case instead of simple lambda.

**Comment by Tirraon** [comment]
Also from @FireEater64 example:
When we ignore 'IgnoredColumn' with 'ConvertUsing()' CsvHelper will write only values, it will miss headers. If ConvertUsing() should 'override everything', than maybe it should also keep header?
