### ISSUE TITLE
Write Variable Parent Name before all Child properties

### ISSUE THREAD

**Issue by stlows** [JoshClose/CsvHelper#1076]
Hi,

I have a `Garage` object that I want to write to a csv file.

Ex:
```
public class Garage{
    public Car Car1 {get; set;}
    public Car Car2 {get; set;}
}
public class Car{
    public string Model {get; set;}
    public string Manufacturer {get; set;}
    public int Year {get; set;}
}
```

I would like that the csv column of a `Garage` would look like this:
`Car1_Model, Car1_Manufacturer, Car1_Year, Car2_Model, Car2_Manufacturer, Car2_Year`

In general: [NameOfParentProperty]_[NameOfChildProperty]

With or without underscores is fine...

At the time I have to make another object called `GarageResult`:

```
public class GarageResult{
    public string Car1_Model {get; set;}
    public string Car1_Manufacturer {get; set;}
    public string Car1_Year {get; set;}
    public string Car2_Model {get; set;}
    public string Car2_Manufacturer {get; set;}
    public string Car2_Year {get; set;}

    public GarageResult(Car car1, Car car2){
        this.Car1_Model = car1.Model;
        this.Car1_Manufacturer = car1.Manufacturer;
        this.Car1_Year = car1.Year;
        this.Car2_Model = car2.Model;
        this.Car2_Manufacturer = car2.Manufacturer;
        this.Car2_Year = car2.Year;
}
```

But each time I want to add a `Car` to `Garage`, I need to adjust the class `GarageResult` accordingly and the constructor...

Do you have any solutions for me to avoid the class `GarageResult` and be able to just WriteRecords an Enumerable of `Garage` ?

**Comment by FireEater64** [comment]
You should be able to do this by setting `ReferenceHeaderPrefix`:

```csharp
var testData = new List<Garage>
{
    new Garage {Car1 = new Car { Model = "Escort", Manufacturer = "Ford", Year = 2017 }, Car2 = new Car { Model = "Yaris", Manufacturer = "Toyota", Year = 2018 } }
};

using (var writer = new StreamWriter("test.csv"))
{
    var csv = new CsvWriter(writer);
    csv.Configuration.ReferenceHeaderPrefix = (memberType, memberName) => $"{memberName}_";
    csv.WriteRecords<Garage>(testData);
}
```

**Comment by stlows** [comment]
@FireEater64 Thank you so much ! Exactly what I was looking for ! Making the code so much cleaner ! :)
