### ISSUE TITLE
Ability to skip record / Invalidate based on multiple conditions using ClassMap

### ISSUE THREAD

**Issue by FutureTD** [JoshClose/CsvHelper#1083]
Is there a way to invalidate/skip a record  if the conditions do not match for example:

```
public class Person
{
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public DateTime Birthdate { get; set; }
}

public class PersonClassMap : CsvClassMap<Person>
{
    public PersonClassMap()
    {
        Map( m => m.FirstName ).Index( 0 );
        Map( m = > m.LastName ).Index( 1 );
        Map( m = > m.Birthdate ).Index( 2 );
    }
}
```

Is there a way within the ClassMap to say if FirstName AND LastName is NullOrWhitespace skip this record?

I see we can use validate but it only seems to work with the property you are trying to validate, not multiple conditions.

**Comment by JoshClose** [comment]
https://joshclose.github.io/CsvHelper/configuration#shouldskiprecord

**Comment by FutureTD** [comment]
Thanks, totally missed that.

**Comment by JoshClose** [comment]
No worries!
