### ISSUE TITLE
Not able to get Custom Headers in Asian Languages

### ISSUE THREAD

**Issue by xcasillas** [JoshClose/CsvHelper#1086]
Hi i am trying to create a file with custom headers, not sure if this is the right way to try that....

Since the Headers are going to be Localize on Asian Countries (Japanese for this example but also Chinese) is just display weird characters on the final export file.

        private byte[] WriteCsvToMemory(IEnumerable records)
        {
            using (var ms = new MemoryStream())
            using (var sw = new StreamWriter(ms ))
            using (var csv = new CsvWriter(sw ))
            {
                csv .WriteField(LocalizationUtilities.GetResourceFileValue("ja-jp", "KEY"));
                csv .NextRecord();
                csv .Configuration.HasHeaderRecord = false;
                csv .WriteRecords(records);
                sw.Flush();
                return ms.ToArray();
            }
  }

I think i Map Header class wont work since the class properties has to be on the specific language.

**Comment by FireEater64** [comment]
This feels like a general encoding problem rather than a specific issue with CsvHelper. When you write the `byte[]` to a file, what encoding do you use? If your file has non-ASCII characters - make sure you're using UTF-8 encoding when interpreting the byte array.

```cs
var results = WriteCsvToMemory(new List<Foo> { test });
Encoding.UTF8.GetString(results);
```

Also - becasue you mention that you can't use MapHeader - would the following not work?

```cs
sealed class FileMap : ClassMap<Foo>
{
    public FileMap(string culture)
    {
        Map(x => x.Bar).Name(LocalizationUtilities.GetResourceFileValue(culture, "KEY"));
    }
}

private byte[] WriteCsvToMemory(IEnumerable records, string culture)
{
    using (var ms = new MemoryStream())
    using (var sw = new StreamWriter(ms))
    {
        using (var csv = new CsvWriter(sw))
        {
            var classMap = new FileMap(culture);
            csv.Configuration.RegisterClassMap(classMap);
            csv.WriteRecords(records);
            sw.Flush();
            return ms.ToArray();
        }
    }
}
```

**Comment by xcasillas** [comment]
Thank you for your response. And sorry for my late response.

That works great.

**Comment by tankvn** [comment]
1. Step 1: Install Encoding.CodePages packages
`dotnet add package System.Text.Encoding.CodePages --version 9.0.0`

2. Step 2: Use Encoding 932 `Shift_JIS` for Japanese

```csharp
using System.Text;

// Register the CodePages encoding provider at application startup to enable using single and double byte encodings.
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

// Now can create single and double byte encodings for code pages that are not available in .NET Core.
using (var reader = new StreamReader(filePath, Encoding.GetEncoding(932)))
using (var csv = new CsvReader(reader, config))
{
   ....
}
```
