### ISSUE TITLE
Problems reading file w/Mac line endings (CR); Windows line endings (CRLF) works just fine!

### ISSUE THREAD

**Issue by rameshsrinivas** [JoshClose/CsvHelper#1087]
I just upgraded from a 2.x version of CsvHelper to the 7.1.1 version. And now I can't seem to read files with Mac (CR) line endings in them properly (I used to be able to do so in the old version), but the file is read fine if I simply save it on a PC, changing the line endings to CRLF. I've attached the two files here.

When reading the line with Mac (CR) endings, the header is read correctly. However, the first column (in this case, 'Institution' in the first line is read as "," (where it's supposed to read as an empty string) which throws the rest of the fields off - the index appears to be off by 1.

[trades-windows.txt](https://github.com/JoshClose/CsvHelper/files/2238934/trades-windows.txt)
[trades-mac.txt](https://github.com/JoshClose/CsvHelper/files/2238935/trades-mac.txt)
```cs
List<Dictionary<string, string>> listOfRows = new List<Dictionary<string, string>>();
while (csvReader.Read())
{
    Dictionary<string, string> currentRow = new Dictionary<string, string>();
    // fieldHeaders contain all the headers
    foreach (var field in fieldHeaders)
    {
        if (field != null)
        {
            // Insititution reads as ","
            currentRow.Add(field, csvReader[field]);
        }
    }
    if (!currentRow.All(x => string.IsNullOrWhiteSpace(x.Value)))
    {
        listOfRows.Add(currentRow);
    }
}
```

I've gone over similar issues that people have raised and have resolved, but nothing outside of converting the line endings to CR+LF works. You mention this being resolved in the 8.x version, but is this version out yet?

**Comment by JoshClose** [comment]
Yes, it was released recently. Let me know if you're still having the issue.
