### ISSUE TITLE
Provide a way to apply transformation to every raw data field processed.

### ISSUE THREAD

**Issue by liguori** [JoshClose/CsvHelper#1089]
It would be a nice feature provide as new member of the Configuration object a function that is able to process the raw content of a field for a content transformation and avoi BadData Exception.

I will explain how it can be useful. Consider that you have a raw CSV content like this:
"Name","Address"
"Pizzeria degli angeli","Via "Medina", 22 - Napoli"
"Bar "Super" Mario","Via Del Corso, 44 - Napoli"

I know that double quote between the double quote in the second record is not a RFC standard.

But having a feature like this:

`csv.Configuration.TransformRawDataField = rawData => rawData.Replace("\"","\"\"")`

I expect that the 'TransformRawData' function is called for every field and it will set the 'rawData' string parameter in this way (without the start and the end quote):

- Pizzeria degli angeli
- Via "Medina", 22 - Napoli
- Bar "Super" Mario
- Via Del Corso, 44 - Napoli

In this way It will be possible to the wrong raw data in a standard compliant. 

Maybe there is some possible way to perform this with the "Type confersion" but not that immediate as i just showed.

Waiting for you comment.

Regards

**Comment by JoshClose** [comment]
The issue with that is, when you have bad data, you really don't know what good data is, or when the field ends. It's possible that you have bad data in the first field of the file, then the rest of the entire file is the second field.

**Comment by liguori** [comment]
I agree with you: it sound like "Which came first: the chicken or the egg" :D
This is the limit of any kind of text file format not correctly escaped.
It happens when there are software that exports CSV without to do it.
A nice feature could be a sort of boolean option "Guess field by comma and double quote combination" or simply "Guess fields" that recognize some pattern giving a priority to the combination "," instead of ", like in the example i made.

**Comment by JoshClose** [comment]
Some will export with quotes around all fields, but doesn't escape quotes inside it. Makes it impossible to read properly. CsvHelper will handle improper files the same way excel does. If you open a bad file in excel, it should look the same as CsvHelper.
