### ISSUE TITLE
Mapping by index with unknown column name

### ISSUE THREAD

**Issue by renklus** [JoshClose/CsvHelper#1093]
I cannot find a way to map a column without specifying it's name.

I have a few csv files with headers. One column name is different in every file, so I tried to map this column by index.

    Map(m => m.MyProperty).Index(4);

The CSV looks like this:

    HeaderColumn1,HeaderColumn2,HeaderColumn3,HeaderColumn4,ThisHeaderChanges
    ,,,,"I need this Value"

Here I try to map the column 'ThisHeaderChanges' to 'MyProperty'.
But when only mapping by index the mapper still seems to use the property name instead of the index.
    `CsvHelper.ValidationException: 'Header matching ['MyProperty'] names at index 0 was not found.`

How can I map to a column without specifying it's name in the mapping file?

**Comment by InfamousPixel** [comment]
Did you ever find a solution to this? I'm having the same problem too

**Comment by JoshClose** [comment]
Turn off header validation.
```cs
csv.Configuration.HeaderValidated = null;
```
If you have an index specified it probably shouldn't validate. I'll mark this as a bug for now.

**Comment by JoshClose** [comment]
Fixed and is in 9.0.1 on nuget.
