### ISSUE TITLE
Thrown ValidationException with field name

### ISSUE THREAD

**Issue by mtissington** [JoshClose/CsvHelper#1095]
This is a great - thanks for doing this!

In my ClassMap I return false when validation fails. As stated this throws a ValidationException however the Message is not very helpful for the user. How can I get the field name that failed?

Thanks.

**Comment by novikov-alexander** [comment]
As I understand the problem still exists, isn't it?
Also I can't find any way to get proper header to show it to user.

**Comment by mtissington** [comment]
yes

**Comment by JoshClose** [comment]
You can't. That's the error. It can't find the field that it's looking for. If you have a property of `Id` mapped to a name of `"Id"`, `Map(m => m.Id).Name("Id")`, and there is no header of `"Id"` that exists, you'll get a `ValidationException`. Same with indexes. If you have a property mapped to index `5` and only have 3 columns in your CSV, it'll give you that exception.

Would adding properties of `string[] HeaderNames` and `int HeaderNameIndex` to `ValidationException` be helpful?

**Comment by JoshClose** [comment]
This will be in version 10.0.0 when it is released.
