### ISSUE TITLE
Updating Documentation

### ISSUE THREAD

**Issue by BKSpurgeon** [JoshClose/CsvHelper#1098]
Hi folks

I"m wanting to do a pull request to improve the documentation a little bit - very minor. But I was confronted with this - see image below (source file: https://github.com/JoshClose/CsvHelper/blob/master/docs/writing/index.html)

![image](https://user-images.githubusercontent.com/15097447/44249848-6e16d780-a20f-11e8-8539-41787b8d094c.png)

My suggestion was to add a text writer surrounding it - like this:

```c#
            using (StreamWriter textWriter = new StreamWriter(drawingType.LayoutsDirectory.FullName))
            {
                var records = new List<MyClass> { ... };
                var csv = new CsvWriter(textWriter);
                csv.WriteRecords(records);
            }
```

Not sure how to proceed exactly to update the docs. Advice much appreciated.

**Comment by mbergkvist** [comment]
[CsvHelper/docs](https://github.com/JoshClose/CsvHelper/tree/master/docs) are generated. The source is in [CsvHelper/docs-src/](https://github.com/JoshClose/CsvHelper/blob/master/docs-src/src/pages/writing.md).

**Comment by BKSpurgeon** [comment]
@mbergkvist thank you sir!
