### ISSUE TITLE
Support for an optional header collection in a CSV or TSV file.

### ISSUE THREAD

**Issue by rambotech** [JoshClose/CsvHelper#1112]
There are a few cases for CSV/TSV data files, which use "key: value" lines at the beginning of the file, with a blank line after the last pair to act as a separator between the headers and the regular CSV/TSV portion of the data.  Credit Unions and some retailers (e.g. Target) use these headers as metadata for the file.

E.g.

---TOF---
Account: 12356032-1
Updated: 6/23/2018

TRANS_DATE    AMOUNT  PAYEE CHECK_NUMBER POSTED_DATE
<--- the data rows begin here --->
--- EOF ---

I would be interested in this project supporting that, and if it doesn't already, I would be interested in adding that support for this project.  Is it there already, or are there any plans yet for it?

**Comment by JoshClose** [comment]
It's not something I want to support because it's not a part of the CSV standard. It's really easy to do yourself though.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Account: 12356032-1");
	s.AppendLine("Updated: 6/23/2018");
	s.AppendLine();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		// We want to know when we've hit a blank line, so don't ignore them.
		csv.Configuration.IgnoreBlankLines = false;
		csv.Configuration.RegisterClassMap<TestMap>();

		// Skip all records until a blank line is found.
		while (csv.Read() && csv.Context.Record.Length > 0) { }

		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```

**Comment by rambotech** [comment]
Thanks, that was helpful.

**Comment by JoshClose** [comment]
No problem. Sorry it took so long.
