### ISSUE TITLE
Easy conversion of CSV files to Excel 

### ISSUE THREAD

**Issue by Tealons** [JoshClose/CsvHelper#1120]
I'm looking for a way to easily convert csv files to excel without creating object of all the different CSV files that will be uploaded. Is this possible with CsvHelper? Or do I need to create some dynamic object logic to accomplish this? Or is there an easier way to do this?

**Edit:** I just realized that importing the CSV file is only one side of the story. But maybe you have seen this scenario more often with CsvHelper :)

**Comment by WilliamsKobie** [comment]
Try to use Excel Interop.


 string fileName = Path.GetFileName(fileWithPath);

                string fullDestinationPathWithFile = Path.Combine(destinationPath, fileName);
                string excelFile = Path.ChangeExtension(fullDestinationPathWithFile, "xlsx");

                var _excelApp = new Excel.Application();

                var workBook = _excelApp.Workbooks.Open(fileWithPath,
                Type.Missing, Type.Missing, Type.Missing, Type.Missing,
                Type.Missing, Type.Missing, Type.Missing, Type.Missing,
                Type.Missing, Type.Missing, Type.Missing, Type.Missing,
                Type.Missing, Type.Missing);

                workBook.SaveAs(excelFile, Excel.XlFileFormat.xlWorkbookDefault);
                workBook.Close();

**Comment by Tealons** [comment]
Thanks! I will try that!
