### ISSUE TITLE
Row with multiple columns shows as single column, data corrupt

### ISSUE THREAD

**Issue by taga-maga-at** [JoshClose/CsvHelper#1128]
I am attempting to read a CSV file and am not getting the correct data returned. The file reads without errors however the data rows are not reading correctly:

1. The data row is returned as a single column even though the data has multiple columns
2. The data appears in unreadable format or 

I have 2 other separate files that are reading correctly but on this one it fails. I have created multiple other files of this one but it still results with the same output.

```
try
{
	var csvConfig = new CsvHelper.Configuration.Configuration
	{
		HeaderValidated = null,
		MissingFieldFound = null,
		IgnoreBlankLines = false,
		BadDataFound = null
	};
	using (var csv = new CsvReader(Stringreader, csvConfig))
	{
		try
		{
			var records = csv.GetRecords<dynamic>();
			int rowNo = 0;
			foreach (var record in records)
			{
				rowNo++;
				//csv.Read();
				if (rowNo >= 3)
				{
					try
					{
						string RECTYPE = csv[0];
						...
					}
					catch (Exception ex)
					{
						...
					}
				}
			}
		}
	}
}
```

When I execute `string RECTYPE = csv[0];` I get the following ‰öx´6_ŽP„ñÏí}¨m¨” as the row content

Below is a sample of the CSV content (I am reading the data from row 3 onwards):

> 

RECTYPE,BATCHID,BTCHENTRY,SRCELEDGER,SRCETYPE,JRNLDESC
RECTYPE,BATCHNBR,JOURNALID,TRANSNBR,ACCTID,TRANSAMT,HCURNCODE,TRANSDESC,TRANSREF,TRANSDATE,COMMENT
"1","117","1","GL","JE","TEST JOURNALS BATCH"
"2","99","1","20","3013",150.00,"CAD","123","1808JSI0001 SECFEE","20180906",""
"2","99","1","40","4009",-150.00,"CAD","123","1808JSI0001 SECFEE","20180906",""

> 

FYI, RECTYPE 1 is the header, and RECTYPE 2 is the detail

**Comment by JoshClose** [comment]
Look like you might need to set the culture on the stream.
