### ISSUE TITLE
ReferenceMaps with no MemberMaps throws MissingFieldFound

### ISSUE THREAD

**Issue by jrigsby** [JoshClose/CsvHelper#1129]
CsvHelper v7.1.1

I have a project where I am defining my mappings in a generic way.  Everything works when I map to a class with simple types but if I chose to map to something with only complex objects using reference maps that map fields in the file to properties of these child objects and I do not have a property in the parent that I am mapping to (MemberMaps count is 0) it fails to read each row due to MissingFieldFound. I can get around it if I have an empty MissingFieldFound handler or if I put a property on my parent object and map to it. 

I can see a case where I might want my code to error if a specific mapping I have identified isn't found.

Is there a way to handle this scenario that doesn't ignore missing fields? Not saying there is a bug, just wondering if there is or if there is a right way. I installed prerelease v8 and that didnt help.

Just to illustrate the class I am mapping to at the root is HierarchyFile. 

```c#
   public class HierarchyFile {
      public Plan Plan { get; set; }
      public Payroll Payroll { get; set; }
      public Contribution Contribution { get; set; }
      public Loan Loan { get; set; }
   }

   public class Plan {
      public string Client { get; set; }
   }

   public class Payroll {
      public string TaxId { get; set; }

      public decimal? GrossPay { get; set; }
   }

   public class Contribution {
      public decimal? RothCatchupContribution { get; set; }
   }
   public class Loan {
      public decimal? TotalLoans { get; set; }
   }
```

When I say Im mapping in a generic manner I am using

```c#

   public class DynamicCsvClassMap<T> {
      public static DefaultClassMap<T> Build(List<IMapDefinition> mapping, bool indexBased = false) {
         DefaultClassMap<T> map = new DefaultClassMap<T>();
         // mapping holds the Property - csv column mapping 
         foreach (var column in mapping) {
            if (!string.IsNullOrEmpty(column.Field)) {
               if (!column.Index.HasValue && indexBased) throw new Exception("Index required for index based mapping");
               var parent = column.Field;
               var propertyInfo = typeof(T).GetProperty(parent, BindingFlags.FlattenHierarchy | BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);

               var memberMap = MemberMap.CreateGeneric(typeof(T), propertyInfo);
               if(!indexBased) memberMap.Name(column.Heading);//If not defined the index position will be used for mapping
               if(column.Index.HasValue) memberMap.Index(column.Index.Value);
               if (column.TypeConverter != null) memberMap.TypeConverter(column.TypeConverter);
               
               map.MemberMaps.Add(memberMap);
            }
         }
         return map;
      }

      public static void AddReferenceMap(ClassMap parentMapping, string propertyName, ClassMap csvMapping) {
         var propertyInfo = typeof(T).GetProperty(propertyName, BindingFlags.FlattenHierarchy | BindingFlags.IgnoreCase | BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);

         var referenceMap = new MemberReferenceMap(propertyInfo, csvMapping);

         parentMapping.ReferenceMaps.Add(referenceMap);
      }
   }

   //sample mapping
         List<IMapDefinition> myMap = new List<IMapDefinition> {
            new MapDefinition("Client", "Plan.Client"),
            new MapDefinition("Tax ID (SSN)", "Payroll.TaxId"),
            new MapDefinition("Gross Pay", "Payroll.GrossPay"),
            new MapDefinition("KC - ROTH 401K CUP", "Contribution.RothCatchupContribution"),
            new MapDefinition("401k Total Loans", "Loan.TotalLoans")
         };
```

**Comment by JoshClose** [comment]
Have you tried looking at what the auto mapper generates?

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Client,TaxId,GrossPay,RothCatchupContribution,TotalLoans");
	s.AppendLine("abc,123,456,789,2");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.GetRecords<HeirarchyFile>().ToList().Dump();
	}
}

public class HeirarchyFile
{
	public Plan Plan { get; set; }
	public Payroll Payroll { get; set; }
	public Contribution Contribution { get; set; }
	public Loan Loan { get; set; }
}

public class Plan
{
	public string Client { get; set; }
}

public class Payroll
{
	public string TaxId { get; set; }

	public decimal? GrossPay { get; set; }
}

public class Contribution
{
	public decimal? RothCatchupContribution { get; set; }
}
public class Loan
{
	public decimal? TotalLoans { get; set; }
}
```

**Comment by jrigsby** [comment]
While my description doesn't show it, two of my columns in a different file have the same heading and need to be mapped to different properties. My code has to account for that possibility. I know I'll also have classes with duplicate property names from time to time. So I don't think I'll get away with that. But it's good to know.

On Oct 1, 2018 9:29 PM, Josh Close <notifications@github.com> wrote:

Have you tried looking at what the auto mapper generates?

void Main()
{
        var s = new StringBuilder();
        s.AppendLine("Client,TaxId,GrossPay,RothCatchupContribution,TotalLoans");
        s.AppendLine("abc,123,456,789,2");
        using (var reader = new StringReader(s.ToString()))
        using (var csv = new CsvReader(reader))
        {
                csv.GetRecords<HeirarchyFile>().ToList().Dump();
        }
}

public class HeirarchyFile
{
        public Plan Plan { get; set; }
        public Payroll Payroll { get; set; }
        public Contribution Contribution { get; set; }
        public Loan Loan { get; set; }
}

public class Plan
{
        public string Client { get; set; }
}

public class Payroll
{
        public string TaxId { get; set; }

        public decimal? GrossPay { get; set; }
}

public class Contribution
{
        public decimal? RothCatchupContribution { get; set; }
}
public class Loan
{
        public decimal? TotalLoans { get; set; }
}

**Comment by jrigsby** [comment]
Sorry, the code actually wasn’t working completely with the MissingFieldFound handler coded. Its apparently automapping in this case and the only field with a column header that matches the field name was being populated at various levels (headers are not under my control and will rarely match the name). I guess I didn’t check other fields. The only way I can get it to do it is if at least one mapping results in there being a MemberMap.

**Comment by JoshClose** [comment]
I mean, if you debug the code, you can look at what the auto mapper generates, and use that as an example. You can also look at the auto mapper source code that generates everything dynamically on the fly.

**Comment by jrigsby** [comment]
Ok thanks. Ill give it a look.

**Comment by JoshClose** [comment]
If you want to give a failing example where I can hit F5 and see it fail, I'll take a look. There are too many assumptions that need to be made to create an example from the code you've shown.

**Comment by jrigsby** [comment]
Okay thank you. The issue was my error. I was attempting to register the root ClassMap that had no MemberMaps prior to configuring its corresponding ReferenceMaps and thus the registration failed with an error.  Somewhere along the line I chose to just not add it and went on to handle reference maps, forgetting that in the end I didnt add the root map that they would be attached to.  So yeah, there was no mapping defined. Fixing that I have my code taking in a generic definition that maps header names or index positions to the property in a class as deep or shallow as I like.

Sorry for the wasted time. Its usually something stupid. I appreciate the quick response.

**Comment by JoshClose** [comment]
You're welcome, and no worries.
