### ISSUE TITLE
.NET 4.0

### ISSUE THREAD

**Issue by sunthree74** [JoshClose/CsvHelper#1130]
i have some errors when i want to install this package

Install-Package : Could not install package 'CsvHelper 7.1.1'. You are trying to install this 
package into a project that targets '.NETFramework,Version=v4.0,Profile=Client', but the package 
does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author.
At line:1 char:1
+ Install-Package CsvHelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdle 
   ts.InstallPackageCommand

**Comment by JoshClose** [comment]
You'll need to be on .NET 4.5 for it to work. https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

You can use version 2.x if you want to run on 4.0.
