### ISSUE TITLE
Error handling question

### ISSUE THREAD

**Issue by scooter12** [JoshClose/CsvHelper#1132]
According to the documentation, "When some errors occur, you can change the behavior to do something besides throw an exception; such as ignoring the error and logging it." 

Since the BadDataFound, MissingFieldFound and ReadingExceptionOccurred function's don't have a return value how do you tell the reader to ignore the error? I've looked through the context that's passed in and nothing's jumping out at me.

Thanks in advance!
Scott

**Comment by JoshClose** [comment]
The default implementation of those functions throw an exception. When you set the value of the function to your custom code, don't throw an exception.

In one of the given examples, setting it to `null` or to your own function that doesn't `throw` will do it.
```cs
// Ignore bad data.
csv.Configuration.BadDataFound = null;

// Log bad data.
csv.Configuration.BadDataFound = context =>
{
    logger.WriteLine( $"Bad data found on row '{context.RawRow}'" );
};
```

**Comment by JoshClose** [comment]
Here are the default implementations. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/ConfigurationFunctions.cs

**Comment by iflp** [comment]
^ Thanks for that. I've been trying to throw an exception in `.validate()` but my inner exception is always null, couldn't figure out what was wrong. This breaks a few answers that assume the exception thrown in validate will get wrapped.

E.g. https://github.com/JoshClose/CsvHelper/issues/941

**Comment by JoshClose** [comment]
I see the issue with `ReadingExceptionOccurred`.

What if I changed it to
```cs
bool ReadingExceptionOccurred(CsvHelperException exception)
{
    return true;
}
```

Since it's already a `CsvHelperException`, I don't want to wrap it. I could have the caller of the method `throw` in the case of a caught exception, or throw the `new` exception in other cases if the result is `true`.

**Comment by JoshClose** [comment]
This is what the changes would be. https://github.com/JoshClose/CsvHelper/commit/90fe88e73a2d7f549d5e9deb0f0429eaa48b77df

**Comment by JoshClose** [comment]
This will be in release 10.0.0.

**Comment by scooter12** [comment]
> This will be in release 10.0.0.

Thanks Josh!!!
