### ISSUE TITLE
how can i able to read lines and reposition column names using CSVhelper..

### ISSUE THREAD

**Issue by ppaulerrol** [JoshClose/CsvHelper#1136]
-in CSV file-
Latitude Name Longitude 

-this is i need to read in system-
Name Latitude Longtitude

thanks..

**Comment by JoshClose** [comment]
You would have to read from a file and write the new format to a new file. You can then delete the old file and rename the new one to the original.

**Comment by ppaulerrol** [comment]
this is my code for reading csv file from my system.. i dont know what to do next?.

private void csv(string path)
        {
            try
            {
                int count = 0;
                //string targetFile = Application.StartupPath.ToString();
                //var jsonWrtr = new StreamWriter(targetFile + @"\DATAX0H.json");

                var csv = new List<string[]>(); // or, List<YourClass>
                var lines = System.IO.File.ReadAllLines(path);

                foreach (string line in lines)
                {
                    csv.Add(line.Split(','));
                    count++;
                }


                string json = new JavaScriptSerializer().Serialize(csv);

                string newJsonString = json.Substring(441); // delete all colums (First Row)

                string newJsonString2 = newJsonString.Replace("\"\"", "N/A"); //replace all ("") to ("N/A")
                newJsonString2 = newJsonString2.Replace("\"", ""); //replace 

                Regex regX = new Regex(@"(?<Station_Name>[A-Za-z0-9/]+),(?<Station_Short_Name>[A-Za-z0-9/]+),(?<Generated_Timestamp>[A-Za-z0-9:./-]+),(?<Arrival_Timestamp>[A-Za-z0-9:./-]+),(?<Data_Validity>[A-Za-z/]+),(?<Datum>[A-Za-z0-9/]+),(?<Latitude>[A-Za-z0-9.+/]+),(?<Longitude>[A-Za-z0-9.+/]+),(?<Ground_Speed>[A-Za-z0-9./]+),(?<Tracking_Angle>[A-Za-z0-9./]+),(?<Magnetic_Variation>[A-Za-z0-9.+/-]+),(?<Remote_Address>[\d\.\s+abc()A-Za-z0-9./]+),(?<Position_Accuracy_Minimum>[A-Za-z0-9./+-]+),(?<Position_Accuracy_Maximum>[A-Za-z0-9./+]+),(?<Data_Age_Minimum>[A-Za-z0-9./+]+),(?<Data_Age_Maximum>[A-Za-z0-9./+]+),(?<Altitude>[A-Za-z0-9./]+),(?<Northing>[A-Za-z0-9./]+),(?<Easting>[A-Za-z0-9./]+),(?<Grid_Square_Row>[A-Za-z0-9./]+),(?<Grid_Square_Column>[A-Za-z0-9./]+),(?<Grid_Row>[A-Za-z0-9./]+),(?<Grid_Zone>[A-Za-z0-9./]+),(?<Radio_Designator>[A-Za-z0-9./]+),(?<Combat_ID>[A-Za-z0-9./]+),(?<MIL_2525_Code>[A-Za-z0-9./]+),(?<Flag>[A-Za-z0-9./]+)");

                Match match = regX.Match(newJsonString2.ToString());
                if (match.Success)
                {
                    //SET DATA STRING
                    Station_Name = match.Groups["Station_Name"].Value.ToString();
                    Station_Short_Name = match.Groups["Station_Short_Name"].Value.ToString();
                    Generated_Timestamp = match.Groups["Generated_Timestamp"].Value.ToString();
                    Arrival_Timestamp = match.Groups["Arrival_Timestamp"].Value.ToString();
                    Data_Validity = match.Groups["Data_Validity"].Value.ToString();
                    Datum = match.Groups["Datum"].Value.ToString();
                    Latitude = match.Groups["Latitude"].Value.ToString();
                    Longitude = match.Groups["Longitude"].Value.ToString();
                    Ground_Speed = match.Groups["Ground_Speed"].Value.ToString();
                    Tracking_Angle = match.Groups["Tracking_Angle"].Value.ToString();
                    Magnetic_Variation = match.Groups["Magnetic_Variation"].Value.ToString();
                    Remote_Address = match.Groups["Remote_Address"].Value.ToString();
                    Position_Accuracy_Minimum = match.Groups["Position_Accuracy_Minimum"].Value.ToString();
                    Position_Accuracy_Maximum = match.Groups["Position_Accuracy_Maximum"].Value.ToString();
                    Data_Age_Minimum = match.Groups["Data_Age_Minimum"].Value.ToString();
                    Data_Age_Maximum = match.Groups["Data_Age_Maximum"].Value.ToString();
                    Altitude = match.Groups["Altitude"].Value.ToString();
                    Northing = match.Groups["Northing"].Value.ToString();
                    Easting = match.Groups["Easting"].Value.ToString();
                    Grid_Square_Row = match.Groups["Grid_Square_Row"].Value.ToString();
                    Grid_Square_Column = match.Groups["Grid_Square_Column"].Value.ToString();
                    Grid_Row = match.Groups["Grid_Row"].Value.ToString();
                    Grid_Zone = match.Groups["Grid_Zone"].Value.ToString();
                    Radio_Designator = match.Groups["Radio_Designator"].Value.ToString();
                    Combat_ID = match.Groups["Combat_ID"].Value.ToString();
                    MIL_2525_Code = match.Groups["MIL_2525_Code"].Value.ToString();
                    Flag = match.Groups["Flag"].Value.ToString();

                    //checkDatagridview(true, Station_Name);  //call checktable and set true to execute
                    checkOnDatabase();
                    user_zoom += 1;
                    gmap.Zoom = user_zoom;
                    gmap.Zoom = user_zoom - 1;
                    MyDatabase();   //updates the database
                }

                JsonFileName = Path.GetFileName(jsonPath);
                WriteJSONFile();

            }
            catch
            {

                listBox1.Items.Add("----------------------------------------------------------------------------------------------------------------");
                listBox1.Items.Add(" ");
                listBox1.Items.Add("ERROR 3058, CSV File contain NULL value");
                listBox1.Items.Add(" ");
                listBox1.Items.Add("----------------------------------------------------------------------------------------------------------------");
            }

        }

**Comment by ppaulerrol** [comment]
using Mapping? or i just rewrite the old file?

**Comment by ppaulerrol** [comment]
can u give an example? i dont know what to do?

**Comment by JoshClose** [comment]
Here is an example that takes a file and will reverse the order of the columns.

```cs
void Main()
{
	var filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.csv");
	var tempFilePath = Path.GetTempFileName();
	
	using (var reader = new StreamReader(filePath))
	using (var csvReader = new CsvReader(reader))
	using (var writer = new StreamWriter(tempFilePath))
	using (var csvWriter = new CsvWriter(writer))
	{
		csvReader.Configuration.RegisterClassMap<TestMapOld>();
		csvWriter.Configuration.RegisterClassMap<TestMapNew>();
		
		var records = csvReader.GetRecords<Test>();
		csvWriter.WriteRecords(records);
	}
	
	File.Delete(filePath);
	File.Move(tempFilePath, filePath);
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class TestMapOld : ClassMap<Test>
{
	public TestMapOld()
	{
		Map(m => m.Id).Index(0);		
		Map(m => m.Name).Index(1);
	}
}

public class TestMapNew : ClassMap<Test>
{
	public TestMapNew()
	{
		Map(m => m.Id).Index(1);
		Map(m => m.Name).Index(0);
	}
}
```

**Comment by ppaulerrol** [comment]
thanks a lot buddy.
i will try the codes you gave to me. 

by the way? 

public class TestMapOld : ClassMap<Test>
{
	public TestMapOld()
	{
		Map(m => m.Id).Index(0);		
		Map(m => m.Name).Index(1);
	}
}

public class TestMapNew : ClassMap<Test>
{
	public TestMapNew()
	{
		Map(m => m.Id).Index(1);
		Map(m => m.Name).Index(0);
	}
}

in this code the Columns "Name" and "Id" are moving in 0 to 1. 
what if i have a new CSVfile with Name and Id are in rumble column position? can i read it and reposition it back from original position for my system? 

-Example of New CSV files
1.Longitude Latitude Name
2.Latitude Longitude  Name
3. Name Longitude Latitude

-This is i what need to read in system-
Name Latitude Longitude

**Comment by ppaulerrol** [comment]
thanks a lot buddy.
I've got another question.
in this code below
```
// Multiple possible names
Map( m => m.Id ).Name( "id", "the_id", "Id" );
```
on the top you input the possible names inside the "Id" 
Is there any code that i can use to find a field name with the same name or/with any additional characters?.
like this. 
"Id_with_extend_name" or "name_with_Id"

**Comment by ppaulerrol** [comment]
Thanks for the reply buddy.

```
// Multiple possible names
Map( m => m.Id ).Name( "id", "the_id", "Id" );
```

I have another one question? You use multiple possible names in the header of field name.
What if a have an field name with an any additional characters like this to the bottom?

"Id_with_Additional_char" or "Additional_char_Id"

**Comment by ppaulerrol** [comment]
sdasd
