### ISSUE TITLE
Dealing with Double Quote

### ISSUE THREAD

**Issue by filjan** [JoshClose/CsvHelper#1137]
I have been searching and searching for a solution, but have found nothing that works. It is very simple, there is a record with a double quote (I have no control over the generation of this file) and I get a bad record exception. Is there a way to intercept this record before the exception occurs or after and fit the double quote? I haven't found anybody with a solution.

Here is the offending record trying to be read. Notice someone has the inches " after 70.
"PART ABC","827","70"H Unit Testing","721.85"
`
                using (TextReader fileReader = System.IO.File.OpenText(fileName))
                {
                    var csv = new CsvReader(fileReader);

                    csv.Configuration.HasHeaderRecord = true;
                    csv.Configuration.BadDataFound = context =>
                    {
                        Console.WriteLine($"Bad data found on row '{context.RawRow}'");
                        Console.Out.Flush();
                        System.Diagnostics.Debugger.Break();
                    };
                    csv.Read();
                    csv.ReadHeader();
                    altVendorRecords = csv.GetRecords<VendorModel>();

                    List<InventoryItem> invList = new List<InventoryItem>();
                    List<ItemVendor> itemVendList = new List<ItemVendor>();
                    foreach (var record in vendorRecords)
                    {
// doing some stuff
                    }
`
I just don't see any configuration that solves this, or a way to intercept the record before it becomes a problem. 

My pasted code has problems.

**Comment by JoshClose** [comment]
There isn't a good way to do this. The file is bad. It's not a valid CSV format. 

The best you can do is read it with the bad data but you'll get `70 H Unit Testing"` for that field.

You could try writing something to fix your file first. If the `"` doesn't have a `,` or a `"` before or after it, it needs another quote to escape it. This is assuming that every field always has quotes around it. If not, you'll find issues where a comma might show up in the field after the quote and you won't know if it's a part of the field, or there is a missing quote, or etc...

CsvHelper will parse malformed CSV files the same way Excel does.

**Comment by filjan** [comment]
Since I am not in control of the input file, is there a way before the BadDataFound to intercept the double quote and deal with it?

**Comment by Grauenwolf** [comment]
You would have to write a custom pre-processor that looks for even numbered double-quotes that are not followed by a [comma | line-break] and inject a second quote.

Since a TextReader is an abstract class, you could in theory create your own TextReader that does the pre-processing. But I think it would be cleaner if you just built it as a separate function.

In any event, this isn't the kind of thing the library should handle. It will be very brittle and won't work in all cases.
