### ISSUE TITLE
Writing only dynamically selected columns to a CSV file using CSVHelper

### ISSUE THREAD

**Issue by pango89** [JoshClose/CsvHelper#1139]
I have a collection of some objects say customers. Customer contains say 10 properties. I am also getting a list of properties which is a subset of Customer properties as string array. ONLY these columns need to be present in the written CSV. I followed the CSVHelper documentation (https://joshclose.github.io/CsvHelper/2.x/#mapping-runtime-mapping) but it seems to be outdated.

My method looks like this:

```
public void WriteToOutputFile(string filePath, IEnumerable<Customer> records, IEnumerable<string> columnsToBeSelected)
{
    using (var writer = new StreamWriter(File.Create(filePath)))
    {
        var csvWriter = new CsvWriter(writer, new Configuration
            {
                Encoding = Encoding.UTF8,
                HasHeaderRecord = true
            });
        csvWriter.WriteRecords(records);
    }
}
```
Right now, this method will write all the columns to the CSV file. I want only those columns which are supplied in the columnsToBeSelected array.

**Comment by JoshClose** [comment]
It changed slightly.

```cs
void Main()
{
	var records = new List<Test>
	{
		new Test { Id = 1, Name = "one" },
		new Test { Id = 2, Name = "two" },
	};

	var columnsToBeSelected = new List<string> { "Name" };
	
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		var map = new CsvHelper.Configuration.DefaultClassMap<Test>();
		foreach (var column in columnsToBeSelected)
		{
			var property = typeof(Test).GetProperty(column);
			map.Map(typeof(Test), property);
		}
		
		csv.Configuration.RegisterClassMap(map);
		
		csv.WriteRecords(records);
		
		writer.ToString().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by riscie** [comment]
Is it possible to still honour Field Attributes like "Format" or "Name" using this dynamic method? (Attributes would be defined on type `Test` in your example above)
