### ISSUE TITLE
GetRecord<ExpandoObject>() results in exception "Types that inherit IEnumerable cannot be auto mapped"

### ISSUE THREAD

**Issue by CrispyDrone** [JoshClose/CsvHelper#1141]
```
static void main(string[] args)        
{
            using (var streamReader = new StreamReader(@"myfile.csv"))
            using (var csv = new CsvReader(streamReader))
            {
                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var record = csv.GetRecord<ExpandoObject>();
                    foreach (var kvp in record)
                    {
                        Console.WriteLine($"{kvp.Key}: {kvp.Value}");
                    }
                }
            }
        }
    }
```
I'm trying to read and process CSV files with content that is unknown until execution time, for some I will receive a description of their headers (and types), but also at execution time.

The previous code results in the following exception: `CsvConfigurationException: Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?`

However, if I change the problematic statement to either `var record = csv.GetRecord<object>();` or `var record = csv.GetRecord<dynamic>()` everything works fine.

Is this expected behavior? If so, why? And why does this check for type IEnumerable need to occur inside the AutoMap function? Thanks!

**Comment by JoshClose** [comment]
If you use `GetRecord<dynamic>()` it will give you an `ExpandoObject`. If you use `ExpandoObject` directly, it's looking at it's properties and trying to map them. `Keys` and `Values` are both collections.

**Comment by CrispyDrone** [comment]
I see, thanks for your quick and helpful reply.
