### ISSUE TITLE
create DataTable with column from header of CSV and populate rows

### ISSUE THREAD

**Issue by antonlynnik** [JoshClose/CsvHelper#1142]
please give example how to create datatable with columns from csv header
and populate with rows

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/issues?utf8=%E2%9C%93&q=is%3Aissue+datatable

**Comment by antonlynnik** [comment]
i cant understand how to create datatable with column from csv
please give example

**Comment by JoshClose** [comment]
This has been asked many times before.

It's also on the old docs. I haven't added it to the new ones yet. https://joshclose.github.io/CsvHelper/2.x/#misc-faq

**Comment by antonlynnik** [comment]
Yes, I re-read your documentation completely ...
went through all the solutions, but those solutions have already been resolved and not actualy.
and in the new edition I can not understand ...
Please ask again, please give an example.

**Comment by antonlynnik** [comment]
there is information in the documentation how to fill in datatable, but there is no information how to generate a table (create by columns from the csv)

**Comment by JoshClose** [comment]
```cs
void Main()
{
	var s = new StringBuilder();
	s.Append("Id,Name\r\n");
	s.Append("1,one\r\n");
	s.Append("2,two\r\n");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		var dataTable = new DataTable();
		dataTable.Columns.Add("Id", typeof(int));
		dataTable.Columns.Add("Name", typeof(string));

		csv.Read();
		csv.ReadHeader();		
		while( csv.Read() )
		{
			var row = dataTable.NewRow();
			foreach (DataColumn column in dataTable.Columns)
			{
				row[column.ColumnName] = csv.GetField(column.DataType, column.ColumnName);
			}
			
			dataTable.Rows.Add(row);
		}
		
		dataTable.Dump();
	}
}
```

![image](https://user-images.githubusercontent.com/114971/47393107-32532f00-d6e4-11e8-8c9d-1b89480519e5.png)

**Comment by antonlynnik** [comment]
many thanks
but i wont create DataTable dynamically
I would like the table to be created on the basis of columns from tsv, do not prescribe the table in advance
it is possible?

**Comment by JoshClose** [comment]
`CsvDataReader` was added. You can now do this.
```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	using (var dataReader = new CsvDataReader(csv))
	using (var dt = new DataTable())
	{		
		dt.Load(dataReader);
	}
}
```

**Comment by antonlynnik** [comment]
many thanks
