### ISSUE TITLE
Mapping nested array items

### ISSUE THREAD

**Issue by georgiosd** [JoshClose/CsvHelper#1149]
Just in case I'm missing something, is this expected to work? Getting an exception.

`Map(x => x.Foo[0].Bar)`

Thanks!

**Comment by JoshClose** [comment]
Nope. `Map(x => x.A.B.C)` will work, but not indexing into an array.

**Comment by georgiosd** [comment]
Gotcha. If you're ever bored, it would be great to add some ways of mapping arrays, this way or another.

**Comment by JoshClose** [comment]
It's possible. I still recommend doing it by hand. Take a look at the unit tests here for the enumerable types. https://github.com/JoshClose/CsvHelper/tree/master/src/CsvHelper.Tests/TypeConversion

**Comment by georgiosd** [comment]
That's a cool feature! I'm a special case because I'm actually fetching a property of the array item...
