### ISSUE TITLE
Reposition the data of csv file

### ISSUE THREAD

**Issue by jhaype** [JoshClose/CsvHelper#1150]
I have a csv file that contains (but some csv that i have to read has also different position of data)
Name, Location, Latitude, Longitude
89.4343,174.2324,HugS27,North

How can I put them into their right position? 
Name,Location,Latitude,Longitude
HugS27,North,89.4343,174.2324

**Comment by JoshClose** [comment]
You mean you want to change the file itself? Or you just want to read it?

**Comment by jhaype** [comment]
I just want to read it sir.

**Comment by jhaype** [comment]
And also the data can be interchange.

**Comment by JoshClose** [comment]
You could specify the index in the mapping.
```cs
Map(m => m.Name).Index(2);
Map(m => m.Location).Index(3);
Map(m => m.Latitude).Index(0);
Map(m => m.Longitude).Index(1);
```
You could also change the names it's pulling from, though this might get confusing.
```cs
Map(m => m.Name).Name("Latitude");
Map(m => m.Location).Name("Longitude");
Map(m => m.Latitude).Name("Name");
Map(m => m.Longitude).Name("Location");
```

**Comment by jhaype** [comment]
But what if sir i have a lot of csv files and they also have different position like:

Name,Location,Latitude,Longitude
HugS27,North,89.4343,174.2324

Name,Location,Latitude,Longitude
North,HugS27,89.4343,174.2324

Name,Location,Latitude,Longitude
North,89.4343,174.2324,HugS27

Name,Location,Latitude,Longitude
North,89.4343,HugS27,174.2324,

**Comment by JoshClose** [comment]
If the header is never in the right order, you'll need to find a way to figure out what column maps to what class property. You should probably read the rows by hand also. https://joshclose.github.io/CsvHelper/reading#getting-fields

**Comment by JoshClose** [comment]
Closing this. Let me know if you have any more questions.
