### ISSUE TITLE
Mapping Random Header name to the Valid Header

### ISSUE THREAD

**Issue by duskbeforedawn** [JoshClose/CsvHelper#1153]
Can you help me solve my problem.
Suppose I have a csv file that contains the following:

Place,Lat,Long
Philippines,14.97322,121.2837813

However I want to staticly define valid column headers such as:

Country,Latitude,Longitude

I would like to allow the user to map the headers in the csv to the static valid headers like so:

Country = Place
Latitude = Lat
Longitude = Long

I have the following mapping:
```cs
public MyDataClassMap()
    {
        Map(x => x.Country).Name("Country", "Place", "Location");
        Map(x => x.Latitude).Name("Latitude", "Lat", "Lati");
        Map(x => x.Longitude).Name("Longitude", "Long", "Longi");
    }
```
And this works for me but the problem is that I manually input what would be the possible header name of the csv file. Here it looks like "Country" and the rest of them are being mapped manually not dynamically. I don't know what the columns is going to be named so how would that work? If the columns were always named Country, Place, Location etc. etc. this would work but sometimes its CountryA sometimes its Place1 sometimes its LocationB it is really random.

What is a possible solution to this?

**Comment by duskbeforedawn** [comment]
I'm thinking of using regex to solve this problem. I will validate the csv data with a regex pattern then if the pattern match I will map that data to its specific header. The problem is I don't know how to skip reading the csv header in csvhelper and using regex as a condition in mapping the csv file.

**Comment by JoshClose** [comment]
You can create a map dynamically. Search the existing issues. There should be a few of them that explain how to do that.

**Comment by duskbeforedawn** [comment]
Can you give me an example how to do that? Or referred me to some issues that related to my problem. I've been searching and asking about this problem for more than a week already but I couldn't find an answer that can help me solve my problem.

**Comment by JoshClose** [comment]
The `AutoMap` method will dynamically build a `ClassMap` at runtime. Take a look at how it does it.

https://github.com/JoshClose/CsvHelper/blob/47a8e85bc49ccf18ab3c351a0e60d6a4fc58fde7/src/CsvHelper/Configuration/ClassMap.cs#L136

**Comment by JoshClose** [comment]
Also, why use a mapping at all? Why don't you just read row by row? You have a lot of flexibility if you do that.

**Comment by duskbeforedawn** [comment]
I need the mapping because there are instances that the data of the upcoming csv are in different position. This is the code I'am working with right now.

using System;
using System.IO;
using CsvHelper;
using CsvHelper.Configuration;
using System.Text.RegularExpressions;


namespace Csv
{
    class Program
    {
        static void Main()
        {
           
            var filePath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "tests.csv");
            var tempFilePath = Path.GetTempFileName();

            using (var reader = new StreamReader(filePath))
            using (var csvReader = new CsvHelper.CsvReader(reader))
            using (var writer = new StreamWriter(tempFilePath))
            using (var csvWriter = new CsvHelper.CsvWriter(writer))
            {
                csvReader.Configuration.RegisterClassMap<TestMapOld>();
                csvWriter.Configuration.RegisterClassMap<TestMapNew>();
                csvReader.Configuration.Delimiter = ",";
                csvReader.Configuration.PrepareHeaderForMatch = header =>
                {
                    var newHeader = Regex.Replace(header, @"[\s\d*%!]", string.Empty);
                    newHeader = newHeader.Trim();
                    newHeader = newHeader.ToLower();

                    return newHeader;
                };
                
                var records = csvReader.GetRecords<Test>();
                csvReader.Configuration.MissingFieldFound = null;
                csvReader.Configuration.HeaderValidated = null;

                csvWriter.WriteRecords(records);
            }

            File.Delete(filePath);
            File.Move(tempFilePath, filePath);
        }
                                                                                                                                       
        public class Test
        {
            public string Country { get; set; } 
            public string Latitude { get; set; }
            public string Longitude { get; set; }
            
        }

        public class TestMapOld : ClassMap<Test>
        {
            public TestMapOld()
            {
                        Map(m => m.Country).Name("Country", "CountryA", "CountryB");
                        Map(m => m.Latitude).Name("Latitude", "Lat", "LatA");
                        Map(m => m.Longitude).Name("Longitude", "Long", "LongA");
        
                 }
        }

        public class TestMapNew : ClassMap<Test>
        {
            public TestMapNew()
            {
                      Map(m => m.Country).Index(0);
                      Map(m => m.Latitude).Index(1);
                      Map(m => m.Longitude).Index(2);
            }
        }
    }
}

**Comment by JoshClose** [comment]
You can create the map and set the names after creation.
```cs
void Main()
{
	var map = new TestMap();
	map.Map(m => m.Country, true).Name("Country", "CountryA");
	map.Map(m => m.Latitude, true).Name("Latitude", "LatA");
	map.Map(m => m.Longitude, true).Name("Longitude", "LongA");

	var s = new StringBuilder();
	s.AppendLine("Country,Latitude,Longitude");
	s.AppendLine("USA,37.6,-95.665");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{		
		csv.Configuration.RegisterClassMap(map);		
		csv.GetRecords<Test>().ToList().Dump();
	}
	
	s = new StringBuilder();
	s.AppendLine("CountryA,LatA,LongA");
	s.AppendLine("Canada,56.0,-96.0");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.RegisterClassMap(map);
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public string Country { get; set; }
	public string Latitude { get; set; }
	public string Longitude { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Country);
		Map(m => m.Latitude);
		Map(m => m.Longitude);
	}
}
```

**Comment by JoshClose** [comment]
Closing this. If you have any more questions, let me know.
