### ISSUE TITLE
V8 changelog?

### ISSUE THREAD

**Issue by krohnm1** [JoshClose/CsvHelper#1156]
I have a project presently using 7.1.1 and according to nuget the current release is V8.3 but the changelogs I'm finding don't have anything about V8 releases. Am I missing something or is there not anything presently posted on V8?

**Comment by JoshClose** [comment]
Updated the change log. I found a breaking change while at it, so 8.2.0 and 8.3.0 have been unlisted and in release 9.0.0 now. All this is reflected in the updated change log. https://joshclose.github.io/CsvHelper/change-log/

**Comment by JoshClose** [comment]
You weren't missing anything. I just hadn't got around to updating the change log. I should really do it immediately upon any commit. ;)
