### ISSUE TITLE
How to map a collection using CSV Helper

### ISSUE THREAD

**Issue by robertovaldesperez** [JoshClose/CsvHelper#1165]
Hello @JoshClose , I have this code:

`
using (var writer = new StreamWriter(@"C:\Temp\test_export_cadastral_references_to.csv", false, Encoding.UTF8))
            using (var csvWriter = new CsvWriter(writer))
            {
                csvWriter.Configuration.Delimiter = ValidationUtils.CSV_SEPERATOR;
                csvWriter.Configuration.RegisterClassMap<WritingCadastralPropertyCsvMap>();
                csvWriter.Configuration.RegisterClassMap<WritingCadastralConstructiveElementCsvMap>();
                csvWriter.Configuration.RegisterClassMap<WritingCadastralCropElementCsvMap>();
                var hasNext = true;
                var query = CadastralPropertyPredicates.ValueOf(filter, CadastralPropertyRepository.GetAllQueryable());
                while (hasNext)
                {
                    var page = CadastralPropertyRepository.Paginated(query, pageRequest);
                    csvWriter.WriteRecords(page.Content);
                    hasNext = page.Number + 1 < page.TotalPages;
                    pageRequest.Page++;
                }
            }
public sealed class WritingCadastralPropertyCsvMap : ClassMap<CadastralProperty>
    {
        public WritingCadastralPropertyCsvMap()
        {
            Map(m => m.Street.Locality.Province.Name).Index(1).Name(Messages.Province);
            Map(m => m.Street.Locality.Name).Index(2).Name(Messages.Locality);
            Map(m => m.ConstructiveElements).TypeConverter<WritingCadastralConstructiveElementConverter>();
            Map(m => m.CropElements).TypeConverter<WritingCadastralCropElementConverter>();
        }
    }

    public sealed class WritingCadastralConstructiveElementCsvMap : ClassMap<CadastralConstructiveElement>
    {
        public WritingCadastralConstructiveElementCsvMap()
        {
            Map(m => m.UseType).Name(Messages.UseType);
            Map(m => m.Stair).Name(Messages.Stair);
            Map(m => m.Floor).Name(Messages.AddressFloor);
            Map(m => m.Door).Name(Messages.AddressDoor);
            Map(m => m.TotalArea).Name(Messages.Area);
        }
    }

        public sealed class WritingCadastralConstructiveElementConverter : DefaultTypeConverter
        {
            public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
            {
                foreach (var cce in (ISet<CadastralConstructiveElement>)value)
                {
                    row.WriteRecord(cce);
                    /*row.WriteField(cce.UseType);
                    row.WriteField(cce.Stair);
                    row.WriteField(cce.Floor);
                    row.WriteField(cce.Door);
                    row.WriteField(cce.TotalArea);*/
                }

                return null;
            }
        }

        public sealed class WritingCadastralCropElementConverter : DefaultTypeConverter
        {
            public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
            {
                foreach (var cce in (ISet<CadastralCropElement>)value)
                {
                    row.WriteRecord(cce);
                    /*row.WriteField(cce.SubPlotCode);
                    row.WriteField(cce.Clazz);
                    row.WriteField(cce.Qualification);
                    row.WriteField(cce.ProductiveIntensity);
                    row.WriteField(cce.Area);*/
                }

                return null;
            }
        }
    public sealed class WritingCadastralCropElementCsvMap : ClassMap<CadastralCropElement>
    {
        public WritingCadastralCropElementCsvMap()
        {
            Map(m => m.SubPlotCode).Name(Messages.SubPlotCode);
            Map(m => m.Clazz).Name(Messages.Clazz);
            Map(m => m.Qualification).Name(Messages.Qualification);
            Map(m => m.ProductiveIntensity).Name(Messages.ProductiveIntensity);
            Map(m => m.Area).Name(Messages.Area);
        }
    }`
and I would like to map the names of the headers I have in WritingCadastralConstructiveElementCsvMap and WritingCadastralCropElementCsvMap as many times as ConstructiveElements and CropElements I have mapped in WritingCadastralPropertyCsvMap.

something like this:

![image](https://user-images.githubusercontent.com/15571467/48700375-2461d280-ebec-11e8-8a08-8b32759fadf2.png)

Thank you.

**Comment by robertovaldesperez** [comment]
something like this:

![image](https://user-images.githubusercontent.com/15571467/48700324-0e541200-ebec-11e8-9bdf-074a0276754f.png)

**Comment by JoshClose** [comment]
Will the list always have the same amount in them? I would suggest looping the rows yourself and doing a little bit of manual work.

```cs
void Main()
{
	var records = new List<A>
	{
		new A 
		{ 
			Id = 1,
			Name = "one",
			BList = new List<B> 
			{ 
				new B { One = "101", Two = "102", } 
			},
		},
		new A 
		{ 
			Id = 2,
			Name = "two",
			BList = new List<B> 
			{
				new B { One = "201", Two = "202", },
				new B { One = "203", Two = "204", },
		},
		},
		new A
		{
			Id = 3,
			Name = "three",
			BList = new List<B>
			{
				new B { One = "301", Two = "302", },
				new B { One = "303", Two = "304", },
				new B { One = "305", Two = "306", },
			},
		},
	};

	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		csv.Configuration.RegisterClassMap<AMap>();
		csv.Configuration.RegisterClassMap<BMap>();
		
		// Write headers.
		csv.WriteHeader<A>();
		var max = records.Max(r => r.BList.Count());
		for (var i = 0; i < max; i++)
		{
			csv.WriteHeader<B>();
		}
		
		csv.NextRecord();
		
		// Write records.
		foreach (var record in records)
		{
			csv.WriteRecord(record);
			foreach (var b in record.BList)
			{
				csv.WriteRecord(b);
			}
			csv.NextRecord();
		}

		writer.ToString().Dump();
	}
}

public class A
{
	public int Id { get; set; }
	public string Name { get; set; }
	public List<B> BList { get; set; }
}

public class B
{
	public string One { get; set; }
	public string Two { get; set; }
}

public class AMap : ClassMap<A>
{
	public AMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}

public class BMap : ClassMap<B>
{
	public BMap()
	{
		
		Map(m => m.One);
		Map(m => m.Two);
	}
}
```
Output:
```
Id,Name,One,Two,One,Two,One,Two
1,one,101,102
2,two,201,202,203,204
3,three,301,302,303,304,305,306
```

**Comment by robertovaldesperez** [comment]
It is the perfect example because the lists have different sizes, thank you
very much for your help.

**Comment by JoshClose** [comment]
You're welcome.
