### ISSUE TITLE
Map().Ignore() not incrementing Context.CurrentIndex

### ISSUE THREAD

**Issue by Linkbolt** [JoshClose/CsvHelper#1168]
Hi Josh,

Right now I'm processing a CSV file without a header (requirement!), and I have mapped all my class attributes just fine. Since I don't have a header I was mapping my class by the order written on the CSV, so I rely on the Context.CurrentIndex when I need to use ConvertUsing. Thing is, if I have a Map().Ignore() the Context.CurrentIndex doesn't increment.

Example:

            (...)
            Map(o => o.TestTargetId); // row.Context.CurrentIndex is 30
            Map(o => o.TestSourceId).Ignore(); // row.Context.CurrentIndex should be 31

            Map(o => o.TimePerTest).ConvertUsing(row =>
            {
                // row.Context.CurrentIndex is still 30!
                return Serialize<List<TimePerTest>>(row.GetField(row.Context.CurrentIndex + 2));
            });

**Comment by JoshClose** [comment]
`CurrentIndex` is set on a `GetField` call. It's mainly used for debugging after an exception.

Do you not know the indexes ahead of time?

**Comment by Linkbolt** [comment]
Was trying not to worrying about mapping the indexes, since I have around 100 fields. After reading the code a bit I understood that it doesn't quite work that way.

You can Close this issue, thanks Josh.
