### ISSUE TITLE
Commas inside double comma CSV issue

### ISSUE THREAD

**Issue by pacojones** [JoshClose/CsvHelper#1171]
Hi,
I have a CSV file with double comma delimited fields.
If I supply a CSV with the delimiter it works like a charm, but if some of the fields contains a comma, when reading the CSV it reads all data on the first column, leaving all other columns as NULL.

 Sample working:

Header: ID;Name;Address
Data: 1;Joseph;Street 1st;

Sample NOT working:
header: ID;name;Address
Data: 1;Joseph;Street 1st, near the pharmacy;

Code sample:

```
var csv = new CsvReader(reader);

                    csv.Configuration.Delimiter = ";";
                    csv.Configuration.HasHeaderRecord = true;
                    csv.Configuration.IsHeaderCaseSensitive = false;

                    while (csv.Read())
                    {
...
}
```

Is there something missing on my code, or should I really avoid using any commas?

**Comment by Linkbolt** [comment]
This might be a bug.
I use a tab (\t) to delimit and never had any problem so far.

**Comment by JoshClose** [comment]
What version are you using? This doesn't seem to be an issue in the latest version.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id;Name");
	s.AppendLine("1;one,blah");
	s.AppendLine("2;two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.Delimiter = ";";
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```
![image](https://user-images.githubusercontent.com/114971/48952131-bcbac880-ef06-11e8-8887-635e7643bb19.png)
