### ISSUE TITLE
Convert geographic coordinates - mapping file

### ISSUE THREAD

**Issue by sylvaincaillot** [JoshClose/CsvHelper#1175]
Hi, 

I have the following class used to map my CSV with latitude and longitude as decimal degrees (eg.: 165.32, -2.45):

```
public class Position
    {      
        public int ID { get; set; }
        public DateTime DateUTC { get; set; }
        public decimal Longitude { get; set; }
        public decimal Latitude { get; set; }      
    }
```
However, the coordinates in my CSV are provided in degrees, and decimal minutes (3º53.633'S, 164º27.100'E) and would need to be converted.

I have already a function named CoordinatesConverter which would make the conversion but don't know how to use it in the mapping file:

```
public sealed class PositionMap : ClassMap<Position>
    {
        public PositionMap()
        {
            Map(m => m.DateUTC).Name("StoredTime");
            Map(m => m.Latitude).Name("Latitude").TypeConverter(new CoordinatesConverter ()); ??
            Map(m => m.Longitude).Name("Longitude")..... ;          
        }
}
```

 Which syntax should I be using : ConvertUsing, TypeConverter to use this function?
I didn't find a clear example.

Your feedback would be very welcome.

Cheers

S.

**Comment by JoshClose** [comment]
If you want to use a converter, you would implement `ITypeConverter`, or probably just inherit `DefaultConverter`. You can then register the converter for the property.

`ConvertUsing` is an inline function to set the value of the property. If you have a function that already does this, you could just do
```cs
Map(m => m.Latitude).ConvertUsing(row => CoordinateToDecimal(row.GetField("Latitude")));
```
