### ISSUE TITLE
Object Column Order Not Preserved

### ISSUE THREAD

**Issue by fsmirne** [JoshClose/CsvHelper#1179]
I've just upgraded from v7.1.1 to v11.0.0 and `WriteRecords()` doesn't seem to be preserving the object column order anymore.

Example:

```
var array = new object[2];

dynamic test1 = new ExpandoObject();
var dict1 = test1 as IDictionary<string, object>;

dict1.Add("C - First Column", "1-CCC");
dict1.Add("B - Second Column", "1-BBB");
dict1.Add("A - Third Column", "1-AAA");

array[0] = test1;
			
dynamic test2 = new ExpandoObject();
var dict2 = test2 as IDictionary<string, object>;

dict2.Add("C - First Column", "2-CCC");
dict2.Add("B - Second Column", "2-BBB");
dict2.Add("A - Third Column", "2-AAA");

array[1] = test2 as object;

// Write CSV
var stream = new MemoryStream();
var writter = new StreamWriter(stream);
var csv = new CsvWriter(writter);
csv.Configuration.TypeConverterOptionsCache.AddOptions<DateTime>(new TypeConverterOptions { Formats = new string[] { "yyyy/MM/dd" } });
csv.WriteRecords(array);
```

V7.1.1 Produces:
```
C - First Column,B - Second Column,A - Third Column
1-CCC,1-BBB,1-AAA
2-CCC,2-BBB,2-AAA
```

V11.0.0 Produces
```
A - Third Column,B - Second Column,C - First Column
1-AAA,1-BBB,1-CCC
2-AAA,2-BBB,2-CCC
```

It seems that V11.0.0 is sorting the column names before writing while V7.1.1 is not. I don't believe sorting is correct here. The columns should be written in the order they are in the ExpandoObject.

I hope this helps explain the incorrect behavior. Let me know if you need any more examples.
Thanks!

**Comment by JoshClose** [comment]
This was intentional. The problem is the objects get written in the order that the `ExpandoObject` properties are set.
```cs
void Main()
{
	var records = new List<dynamic>();
	
	dynamic o = new ExpandoObject();
	o.Id = "1";
	o.Name = "one";
	
	records.Add(o);
	
	o = new ExpandoObject();
	o.Name = "two";
	o.Id = "2";
	
	records.Add(o);
	
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		csv.WriteRecords(records);
		
		writer.ToString().Dump();
	}
}
```
Output:
```
Id,Name
1,one
two,2
```
So to ensure that they are in the same order, it sorts them ascending.

**Comment by fsmirne** [comment]
Hi Josh,

Thanks for responding.
I'm not sure I understand the logic here. If I have a list of columns in a specific order, I would expect the library to respect that, or at least give me an option to tell it I know how the list was created and it's the way I'd like it to be. What I'm saying is I want the responsibility of setting the properties in the right order to be on me and not the library...

I'm sure you have other reasons I'm not considering but there should be a way for me to preserve my table during a write. Sorry if the design is not clear to me, but I wanted to give you my 2 cents.

Thanks!

**Comment by JoshClose** [comment]
I agree. Essentially each dynamic object is it's own type.

Maybe the ordering should be opt in. I'll look into being able to configure the order, and by default it will be the order given.

**Comment by JoshClose** [comment]
This is complete and in version 12.0.0 on nuget.

**Comment by JoshClose** [comment]
A config option `IComparer<string> IWriterConfiguration.DynamicPropertySort` was added. This is null by default, which means the order of the dynamic object properties will be what you set them as. You can specify the comparer if you want them to sort.

**Comment by JoshClose** [comment]
Sort ascending:
```cs
csv.Configuration.DynamicPropertySort = Comparer<string>.Create((x, y) => x.CompareTo(y));
```

**Comment by fsmirne** [comment]
Hey Josh, thanks for working on this!
I just updated to v12.0.0 on nuget and ran my example but I'm still getting the same result as v11.0.0. Am I missing anything?
Thanks!

**Comment by JoshClose** [comment]
I'm seeing that the header is the same, but the results are correct. I need to do the same thing with writing the header.

**Comment by fsmirne** [comment]
Yeah, sorry I wasn't very clear on the problem. If the header uses the same writing logic, everything will work.
Thanks!

**Comment by JoshClose** [comment]
Just pushed 12.0.1 to nuget which has this fixed.
