### ISSUE TITLE
How to ignore case in latest version?

### ISSUE THREAD

**Issue by TommoDotCommo** [JoshClose/CsvHelper#1183]
This no longer works for me:

    // Ignore case
    csv.Configuration.PrepareHeaderForMatch = header => header.ToLower();

It appears that PrepareHeaderForMatch used to be:

    Func<string, string> PrepareHeaderForMatch { get; set; }

but it's now:

    Func<string, int, string> PrepareHeaderForMatch { get; set; }

I wish I knew more, but it just tells me this delegate does not accept one argument.

**Comment by RichardMau5** [comment]
Can't this be implemented in a way that both the new and the old way work? This way by updating, not everyone's code breaks

**Comment by JoshClose** [comment]
That's why there was a major version number change. There were some other breaking changes in that release also.

Not sure if there was a non-breaking way to do it since it's a property. If it was a method, an overload could have been created, or a default parameter, but not with a property.

**Comment by Lroca88** [comment]
@JoshClose could you update your [Getting Started section](https://joshclose.github.io/CsvHelper/getting-started). 
Still has this:
`csv.Configuration.PrepareHeaderForMatch = (string header) => header.ToLower();`

**Comment by caioproiete** [comment]
@JoshClose Docs have been updated and this issue can be closed.
