### ISSUE TITLE
Working with unstructured data

### ISSUE THREAD

**Issue by sparticus1701** [JoshClose/CsvHelper#1185]
Most of the .csv files my code deals with are unstructured -- that is, they don't have a predefined layout that can be matched to a class.  The presence of a header is also not usually known (although we can usually infer a header because the files we work with typically have mostly numeric values).

What are the best practices for reading headers & records in this case?  Am I stuck with dynamic and ExpandoObject (which have poor performance)?

**Comment by JoshClose** [comment]
Read everything by hand.

Here is an example to give you an idea. I'm using LINQPad, which is where the `.Dump()` comes from.
```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.Delimiter = ",";
		csv.Read();
		if (IsHeader(csv.Context.Record))
		{			
			// This will populate csv.Context.HeaderRecord for you to use later.			
			csv.ReadHeader();
			csv.Context.HeaderRecord.Dump();
			csv.Read();
		}
		do
		{			
			for (var i = 0; i < csv.Context.Record.Length; i++)
			{
				csv.GetField(i).Dump();
			}
		}
		while (csv.Read());
	}
}

public bool IsHeader(string[] record)
{
	// Determine if the row is a header row.
	return true;
}
```

**Comment by sparticus1701** [comment]
Thanks for the reply!  I appreciate your time.
