### ISSUE TITLE
How to map to dynamic list

### ISSUE THREAD

**Issue by hostr** [JoshClose/CsvHelper#1190]
I'm working with a database table that has a Source, Target, Data Type, and Format. Some examples of data are:
```
Source, Target, DataType, Format
CustomerFirstName, FIRSTNAME, string, NULL
VisitDate, MEMBER_SINCE, date, mm/dd/yyyy
NULL, MEMBER_GOAL, blank, NULL
```

I'm able to pull back data from another query that includes the **Source** column in the above table as headers. Now I need to do mapping into the new **Target** column in the above table.

An example of that data looks something like this:
```
[
    {
        "CustomerFirstName": "John",
        "CustomerLastName": "Smith",
        "Points": 100,
        "VisitDate": "2018-10-10"
    },
    {
        "CustomerFirstName": "Bob",
        "CustomerLastName": "Anderson",
        "Points": 30,
        "VisitDate": "2018-11-20"
    }
]
```

The final output of this example in CSV format would be:
```
FIRSTNAME, MEMBER_SINCE, MEMBER_GOAL
John, 10/10/2018, 
Bob, 11/10/2018, 
```

What is the recommended approach for this? I've looked into setting up a MemberMap, but that seems to be only when I know the object I'm mapping to ahead of time. This will need to map at runtime. 

I've also tried using an ExpandoObject and populating the object with the Target values as properties and trying to map from there, but it wouldn't map from Source name to Target name still.

**Comment by JoshClose** [comment]
I'm a little confused. Do you need to read a CSV in one format, and write a CSV in another format?

**Comment by hostr** [comment]
Hey @JoshClose, sorry I ended up figuring this out! Instead of messing with dynamic objects, I mapped the fields to an array of strings and then used WriteField and NextRecord to write the records out.
