### ISSUE TITLE
Date time format doesn't accept ':'

### ISSUE THREAD

**Issue by AngeloStatescu** [JoshClose/CsvHelper#1197]
This is the code:

    public class Cycle
    {
        public int Number { get; set; }
        public DateTime Time{ get; set; }
        public double Duration { get; set; }
    }

    public sealed class CycleMap : ClassMap<Cycle>
    {
        public CycleMap()
        {
            Map(m => m.Number);
            Map(m => m.Time).TypeConverterOption.Format("yyyy-MM-dd HH:mm:ss");
            Map(m => m.Duration);
        }
    }

For some reason ':' doesn't work and it defaults to another format (one output example: 12/6/2018  6:08:14 PM -> clearly isn't the right format). If I replace ':' with something else like '-' it works. How do I make it work with ':'?

**Comment by AngeloStatescu** [comment]
Weird, I tried it on my machine and it does work. I probably overlooked something, maybe it's the culture thing you mentioned. Sorry for the bother.

**Comment by JoshClose** [comment]
Different cultures might use something else for the time separator when parsing. 

Check these settings to see what yours says.

![image](https://user-images.githubusercontent.com/114971/50184711-76754100-02db-11e9-90b5-349a13febb16.png)

I changed my list separator to something other than `,` so unit tests will fail for me if I don't specify it explicitly. If I just use `,` in tests, the tests fail in other cultures. ;)
