### ISSUE TITLE
Header with name 'fieldname' was not found.

### ISSUE THREAD

**Issue by Mattias85** [JoshClose/CsvHelper#1201]
I'm trying to use the CsvHelper with the code below:

```cs
var reader = new CsvReader(sr);
IEnumerable<DataRecord> records = reader.GetRecords<DataRecord>();
foreach (DataRecord record in records) 
{
   //Do stuff with the record
}
```

When I'm using version 2.0.0.0 it's working like a charm. I used this version by downloading an example online. But when I use the latest version 12.0.0.0 I'm getting the error below on the foreach line:

> Header with name 'CommonName' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.

 I tried following the documentation but I'm always getting a similar error. The CSV file and class file all fields have an identical name.
Can someone explain to me why this isn't working anymore in the latest version?

**Comment by JoshClose** [comment]
Do you have a property named `CommonName` that doesn't have a corresponding field in the CSV file?

**Comment by Mattias85** [comment]
The CSV file contains the following data:
```
CommonName,FormalName,TelephoneCode,CountryCode
Argentina,Argentine Republic,54,ARG
Armenia,Republic of Armenia,374,ARM
Australia,Commonwealth of Australia,61,AUS
```
The DataRecord class:

```
public class DataRecord
{
        public String CommonName { get; set; }
        public String FormalName { get; set; }
        public String TelephoneCode { get; set; }
        public String CountryCode { get; set; }
}
```
As far as I can see all requirements and fields are present.

**Comment by JoshClose** [comment]
This seems to work fine for me.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("CommonName,FormalName,TelephoneCode,CountryCode");
	s.AppendLine("Argentina,Argentine Republic,54,ARG");
	s.AppendLine("Armenia,Republic of Armenia,374,ARM");
	s.AppendLine("Australia,Commonwealth of Australia,61,AUS");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.GetRecords<DataRecord>().ToList().Dump();
	}
}

public class DataRecord
{
	public String CommonName { get; set; }
	public String FormalName { get; set; }
	public String TelephoneCode { get; set; }
	public String CountryCode { get; set; }
}
```

![image](https://user-images.githubusercontent.com/114971/50454700-efdde680-090e-11e9-9ecf-c080c784648a.png)


This also seems to work fine.
```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("CommonName,FormalName,TelephoneCode,CountryCode");
	s.AppendLine("Argentina,Argentine Republic,54,ARG");
	s.AppendLine("Armenia,Republic of Armenia,374,ARM");
	s.AppendLine("Australia,Commonwealth of Australia,61,AUS");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		IEnumerable<DataRecord> records = csv.GetRecords<DataRecord>();
		foreach (var record in records)
		{
			record.Dump();
		}
	}
}

public class DataRecord
{
	public String CommonName { get; set; }
	public String FormalName { get; set; }
	public String TelephoneCode { get; set; }
	public String CountryCode { get; set; }
}
```

![image](https://user-images.githubusercontent.com/114971/50454683-d9d02600-090e-11e9-8575-b5fa96bf16d9.png)

There must be something else that isn't represented in these examples.

**Comment by ssavkovic** [comment]
Not sure if it is the same issue, but I got exactly the same error for the header column 'fieldname' that was not at all in the file I was reading.
It turned out that the problem was that my class being read was missing the default constructor (I only had a constructor with parameters). Perhaps it would be a good idea to add a _where T : new()_ constraint for the _GetRecords<T>_ to avoid this? I've added the constraint in my code wrapping the call. Alternatively, we could make the error more clear (check for default constructor or similar). 
Anyway, thanks for the great library!

**Comment by dupuis2387** [comment]
So i had this exact same issue, and it turned out that the problem was the seperating character registered on my system. 

I'd been using the pipe character so much, for other csv work on other things, that it got annoying dealing with excel and telling it to use | everytime i wanted to process a pipe delimmited CSV. So i went to my PCs language settings, and set the list seperator to be the pipe character, by default. 

Since this library reads that setting from the PC's system settings, by default, it was trying to parse my file, thinking the field seperator to use was pipe. For this particular csv, it was comma. So, i just had to do

`csv.Configuration.Delimiter = ",";`

before calling 

`csv.GetRecords.`

Might be what's wrecking you.

**Comment by andrewpajda** [comment]
Hey, I just wanted to ask a question related to this problem .

I have my header in CSV file looking like this `Client_Id,Request_id,Name,Quantity,Price`
and as long as all CSV headers will look like that - everything is fine. 

But, I want to handle the situation in which the user uploads csv with wrong headers like `client_Id,request_id,name,quantity,price`. 
What exception should I try to catch when this happens?

**Comment by AltruCoder** [comment]
@andrewpajda, you just need to use `csv.Configuration.PrepareHeaderForMatch = (header, index) => header.ToLower();` to be able to ignore the case of the headers.

**Comment by andrewpajda** [comment]
This I understand. But what if for some reason, headers dont match entirely. For example user uploaded different csv by mistake.  So there are more columns and they represent completely different data.

**Comment by AltruCoder** [comment]
@andrewpajda I think that specific issue might be related to #1032. It doesn't look like there is a good way to tell if there are extra columns that you weren't expecting.

**Comment by efsandino** [comment]
Hi all... 
Believe it or not... I could read a CSV well on linux with dotnet core 2.2.105 but running the same code on Windows 10 with 2.2.202 is not working and I get the following error !

``2019-04-25 18:39:28,860 [5] ERROR Standard [(null)] - Header with name 'idCentro' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
CsvHelper.HeaderValidationException: Header with name 'idCentro' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
   at CsvHelper.Configuration.ConfigurationFunctions.HeaderValidated(Boolean isValid, String[] headerNames, Int32 headerNameIndex, ReadingContext context)
   at CsvHelper.CsvReader.ValidateHeader(ClassMap map)
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext()
   at coreproxy.Controllers.WebServiceTesterController.CargarPosicionesCSV() in E:\artexacta\proyectos\WMS\codigo\coreproxy\Controllers\WebServiceTesterController.cs:line 90

**Comment by JoshClose** [comment]
Probably your delimiter. Explicitly set it and see if that works.
```cs
csv.Configuration.Delimeter = ",";
```

**Comment by julioagp** [comment]
Hello, I have the EXACT same problems.
My properties are well named, I had de Delimiter options and anyway it does not work.
@Mattias85 did you solved it ? 

Thanks.

**Comment by JoshClose** [comment]
@julioagp Can you provide a failing example?

**Comment by RoyPullins** [comment]
I battled this exact error for two days. Mapped the file nothing changed. At one point I had the CSVReader working without error but all the fields were blank when they should not be.
The answer in the end was that I was missing a default parameterless constructor. Hope this comment helps someone else save time :)

**Comment by AntSwift** [comment]
Try using ReadHeader as below:

```csharp
using (var stringReader = new StringReader(str.Trim()))
using (var csvReader = new CsvReader(stringReader))
{
    csvReader.Read();
    csvReader.ReadHeader();

    var compoents = csvReader.GetRecords<Type>();
}

**Comment by roddharris** [comment]
I'm having the same issue as originally described.  I have the following

```
//Data
B S U,Episode Row,Street Address,City,State,Zip, ...
12345678,1,123 My Street,SomeCity,WI,53186, ...
98765432,1,321 Street 2,Anothercity,WI,53186,...
98765432,2,321 Street 2,Anothercity,WI,53816,...

//Simplified version of what I'm doing
byte[] fileBytes = File.ReadAllBytes(@"c:\temp\myepisodefile.csv");
string fileText = Encoding.Default.GetString(fileBytes);
using(var reader = new StringReader(fileText))
{
    using(var csv = new CsvReader(reader))
    {
        csv.Configuration.RegisterClassMap<EpisodeMap>();
        csv.Configuration.MissingFieldFound = null;
        
        var episodes = csv.GetRecords<Episode>().ToList();
    }
}

public class EpisodeMap : ClassMap<Episode>
{
    public EpisodeMap()
    { 
        Map(e => e.ReferenceNumber).Name("B S U");
        Map(e => e.ReferenceId).Name("Episode Row");
        Map(e => e.AddressLine1).Name("Street Address");
    }
}

public class Episode
{
    public string ReferenceNumber {get; set;}
    public string ReferenceId {get; set;}
    public string AddressLine1 {get; set;}
    public string AddressLIne2 {get; set;}
    ...
}

```

Whenever I hit the line `var episodes = csv.GetRecords<Episode>().ToList();` I get the error

>Header with name 'B S U' was not found.

If I comment out the line `Map(e => e.ReferenceNumber).Name("B S U");`, I get no error and everything works.  However, if I set a breakpoint on the `GetRecords<Episode>()` line (and catch it before it happens) and inspect `fileText`, I can see `B S U,` as the first characters in the text.  

If I then go to my Immediate Window and perform `csv.Read();` followed by `csv.ReadHeader();` and then inspect `csv.Context.HeaderRecord[0]`, I can see "B S U".

However, when I try "B S U" == csv.Context.HeaderRecord[0], I get False.  I just did an ASCII dumb of csv.Context.HeaderRecord[0] and the first ASCII character is 65279 -- which I found is a Byte Order Mark.  It would appear that this is what is causing my problem.  Now I just need to figure out how to get rid of this.

Hope this helps someone else as well!

**Comment by JoshClose** [comment]
@davideveloper You can also use `csv.Configuration.TrimOptions = TrimOptions.Trim;` to automatically trim your fields. I would only suggest this if you don't have control over your data and it has a lot of extra whitespaces.

**Comment by NiekGr** [comment]
I have got the same problem. On our development machines the code works fine and uses the default "," as delimiter. But on our build machine it uses ";" as a delimiter. How can de default change?
Both the default configuration for CsvReader and CsvWriter are changed.

**Comment by dzambrano-idmdev** [comment]
Hi @NiekGr 

I don't know if will this solved your problem but, i solved this way.

` 
     public static void ReadCsvTable()
        {
            string pathLocal = ConfigurationManager.AppSettings["PATH_LOCAL_CSV_TABLE"];

            try
            {
                GlobalVar._listModelTable = new List<CSVModel>();

                using (var reader = new StreamReader(pathLocal))
                using (var csv = new CsvReader(reader))
                {
                    csv.Configuration.Delimiter = ",";
                    csv.Configuration.PrepareHeaderForMatch = (header, index) => header.ToLower();
                    var records = csv.GetRecords<CSVModel>();

                    foreach (var item in records)
                    {
                        GlobalVar._listModelTable.Add(item);
                    }

                    // Closing.
                    reader.Dispose();
                    reader.Close();
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
`

**Comment by shumkis** [comment]
Hello all,
I've been struggling with the same error message and I've finally found a solution. 
If you are converting TextWriter to bytes and then bytes to File, Unicode encoding will give you a file that looks something like this: 

I d , N a m e

 1 , V a

 2 , K e p a l a s

If you open this file in Excel or Notepad it seems fine. I was only able to see this when I checked it with a stream reader. 

That's why reader can't find "Id" header, because it's encoded like "I d ". Switching to UTF-8 encoding solved my problem. Check your .csv file with this console app if you are having same problem.

    public class Program
    {
        static void Main(string[] args)
        {
            var textFile = @"C:\Identical\Test.csv";

            // Read file using StreamReader. Reads file line by line    
            using (StreamReader file = new StreamReader(textFile))
            {
                int counter = 0;
                string ln;

                while ((ln = file.ReadLine()) != null)
                {
                    Console.WriteLine(ln);
                    counter++;
                }
                file.Close();
                Console.WriteLine($"File has {counter} lines.");
            }

            Console.ReadLine();
        }
    }

**Comment by senkadir** [comment]
Giving order number to the properties worked for me.

```
public class DataRecord
{
        [Index(0)] public String CommonName { get; set; }
        [Index(1)] public String FormalName { get; set; }
        [Index(2)] public String TelephoneCode { get; set; }
        [Index(3)] public String CountryCode { get; set; }
}
```

**Comment by Yoonwoo** [comment]
order number worked for me too. Damn this is a lot more complex than I thought it could be.

**Comment by BuddhaBuddy1** [comment]
Our files contain things like trademark symbols, so I believe we need to use Unicode encoding. However, that doesn't seem to work with CsvHelper. As soon as we switch to Unicode, we start getting the header errors.
` using var streamReader = new StreamReader(bulkUpload.OpenReadStream(), Encoding.Unicode);
 var config = new CsvConfiguration(CultureInfo.InvariantCulture) { Encoding = Encoding.Unicode };
`

**Comment by BuddhaBuddy1** [comment]
Our data has trademark characters and such, so I believe we need to use Unicode encoding, but as soon as we switch to that, we start getting this header error.

> using var streamReader = new StreamReader(bulkUpload.OpenReadStream(), Encoding.Unicode);
var config = new CsvConfiguration(CultureInfo.InvariantCulture) { Encoding = Encoding.Unicode };

Am I doing something wrong? If I use Utf8, our special characters get turned into question marks. It seems to me like the header reading code doesn't honor the passed in Encoding configuration.

**Comment by BuddhaBuddy1** [comment]
Ok, so yes, I was doing something wrong. :-)

My source wasn't unicode, it just had extended ascii. To convert it properly I just had to use this:

> using var streamReader = new StreamReader(bulkUpload.OpenReadStream(), Encoding.GetEncoding("iso-8859-1"));

**Comment by rehmanab** [comment]
For me, I had whitespaces after comma's in my csv. e.g. Header1, Header2
After removing whitespace, it works... not sure if there is a config setting to enable trim.
But im sure programs like excel DONT add whitespace when saving as CSV.

**Comment by AltruCoder** [comment]
@rehmanab Yes, you can use `TrimOptions = TrimOptions.Trim`

**Comment by sajithdilhan** [comment]
In my case, I had an extra space at the end of Header column name. Ex: "Columnname "
