### ISSUE TITLE
some documents are inaccessiable

### ISSUE THREAD

**Issue by liesauer** [JoshClose/CsvHelper#1202]
the following links are just some samples:
```
https://joshclose.github.io/examples/writing
```
```
https://joshclose.github.io/CsvHelper/api/csvhelper/csvwriter
```

**Comment by JoshClose** [comment]
What page are those links on?

**Comment by JoshClose** [comment]
Thanks. I tested it locally and it's behaving differently on github pages. Looks like I can't test links locally.

**Comment by JoshClose** [comment]
I think it's fixed.

**Comment by JoshClose** [comment]
If you see any other broken links, let me know. Things work differently on the live site than I can reproduce locally.

**Comment by liesauer** [comment]
thanks!
