### ISSUE TITLE
Get a CsvReader from a string collection

### ISSUE THREAD

**Issue by tmenier** [JoshClose/CsvHelper#1206]
I'm dealing with a situation very similar to this question:

https://stackoverflow.com/questions/15727113/how-do-i-pass-a-collection-of-strings-as-a-textreader

That is, I'm reading/filtering/cleaning raw rows of CSV before parsing them. So at the point that I need a `CsvReader`, I have a list of strings, including the header row. What I'm doing is very similar to the accepted answer - Joining the strings and using a `StringReader`. But this just feels...wrong. It doesn't seem very efficient to concat a big list of strings together, only to have them broken apart again. But a `CsvReader` requires a `TextReader`, and I can't come up with a better way.

So I guess I would say this a feature request, unless there's already a better way to do this that I'm not seeing?

Thanks!

**Comment by JoshClose** [comment]
Can you create your own `IParser` implementation and pass that into `CsvReader` instead of the `TextReader`?

**Comment by JoshClose** [comment]
You'd actually probably want to implement your own `TextReader`, not `IParser`. Not sure what I was thinking last night. Maybe you could pass in the class that does the cleanup of the file and every time data is read, you can read and clean more from your file. You'd need to keep an internal buffer of cleaned data. The only `TextReader` methods that are used are `Read`, `ReadAsync`, and `Dispose`.

Looking outside of this whole thing, my suggestion would be to write a whole new temp file where the data is clean, read that file using CsvHelper, then delete the temp file.

**Comment by tmenier** [comment]
Doh, I sell I let this sit in my inbox for a while. Thanks for the suggestions, much appreciated. I went with the one-big-string and moved on. If that gets too big I think your temp file idea is my next best bet. 

Feel free to close this, unless it's something you'd consider someday (either a pre-filtering mechanism of raw rows, or a `CsvReader` that can process an `IEnumerable<string>` directly). To your point, it could get a little involved since there's no out-of-the-box way to get a `TextReader` from an `IEnumerable<string>`. Understandable if that's not something you want on your roadmap. Thanks again for a great library!
