### ISSUE TITLE
BadDataException issue with double quotes in header

### ISSUE THREAD

**Issue by rmoergeli** [JoshClose/CsvHelper#1209]
My CSV did not change, but CsvHelper version. Installing newest version 12.1.1 I have BadDataException reading first line of CSV file.
Going back to older versions using same CSV file, it is working up to version 9.2.3.

CSV file is:
"computer_name","computer_serial_number","model","chassis_type"

Higher 9.2.3 when BadDataException happens executing first Read():
Context.CurrentIndex = -1
Context.Field => "computer_name,\"computer_serial_number\",\"model\",\"chassis_type\""
Context.FieldBuilder => {computer_name,"computer_serial_number","model","chassis_type"}

First double quote is missing?

**Comment by JoshClose** [comment]
I'm not getting an exception. What is different about my example here?

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("\"computer_name\",\"computer_serial_number\",\"model\",\"chassis_type\"");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Read();
	}
}
```

**Comment by rmoergeli** [comment]
Thanks for the tip! Configuration.Delimiter = "," solved my problem too. Add the beginning I had no clue where the problem lies because using ClassMap and Parallel.ForEach. I thought it must be something wrong with the data. But to understand that it is not the data I had to disassemble the code.
