### ISSUE TITLE
Documentation on case-insensitive header outdated

### ISSUE THREAD

**Issue by VictorBonjour** [JoshClose/CsvHelper#1211]
Hi Josh,

I spotted a small issue on this page https://joshclose.github.io/CsvHelper/getting-started
Regarding the snippet that describes how to make header match in a case-insensitive way:
using (var reader = new StreamReader("path\\to\\file.csv"))
```
using (var csv = new CsvReader(reader))
{    
    csv.Configuration.PrepareHeaderForMatch = (string header) => header.ToLower();
    var records = csv.GetRecords<Foo>();
}
```

The PrepareHeaderForMatch delegate now takes 2 input arguments (string, int), as specified in the changelog. So this should read:
`csv.Configuration.PrepareHeaderForMatch = (string header, int unknown) => header.ToLower();`

Not sure what this integer is though.
Anyway, thanks for the great library!
Wishing you a happy new year.
Victor

**Comment by JoshClose** [comment]
It's the index (position) of the header. I should put what the arguments are in the xml doc.

**Comment by marcrocny** [comment]
This is just #1183. Nominate to close.

**Comment by JoshClose** [comment]
Thanks.
