### ISSUE TITLE
Is it possible to inject a column into the CsvDataReader?

### ISSUE THREAD

**Issue by recurs10n** [JoshClose/CsvHelper#1215]
I'm trying to read a large number (multiple 100's) of different CSV files and stream them into a database using SqlBulkCopy, without creating classes to represent each of them. The CSV files have no header, and the fields in the CSV exactly match the order of the database tables with one important exception: there is a LoadID field as the first field of the tables which is not present in the CSV files. For a given run, the same LoadID would be used for all tables and rows that were loaded. Is there a way to inject a constant field or a Func at index 0 when using the CsvDataReader class? Without the LoadID field on the SQL tables, the files load just fine using the default ordinal matching that SqlBulkCopy does. Below is an example of what doesn't work. 

If the only way to do this it two write my own extension, I'm OK with that, but I'm not sure the best class to extend. 

    static void Main( string[] args )
    {
        string sqlConnectionString = "[ConnectionString]";
        string createTable = 
            @"DROP TABLE IF EXISTS dbo.Names; 
            GO 
            CREATE TABLE dbo.Names( 
                LoadID INT NOT NULL, 
                ID INT NOT NULL, 
                Name VARCHAR(255) NOT NULL 
            )";

        // create SQL table
        using( SqlConnection conn = new SqlConnection( sqlConnectionString ) )
        using( SqlCommand cmd = new SqlCommand( createTable, conn ) )
            cmd.ExecuteNonQuery();

        var s = new StringBuilder();
        s.AppendLine( "1,John" );
        s.AppendLine( "2,George" );
        s.AppendLine( "3,Amy" );

        using( var reader = new StringReader( s.ToString() ) )
        using( var csv = new CsvReader( reader ) )
        {
            using( var dataReader = new CsvDataReader( csv ) )
            {
                SqlBulkCopy bcp = new SqlBulkCopy( sqlConnectionString );

                bcp.DestinationTableName = "dbo.Names";
                bcp.WriteToServer( dataReader );
            }
        }
    }

**Comment by recurs10n** [comment]
Hmmm. I was hoping to avoid that because the number of files involved would make keying each table like that very time consuming. However, if I grab all the metadata from the SQL sys.tables and sys.columns tables, I could generate the data table definitions at runtime, use index matching instead of name matching since they already match, and then only have to add the LoadID manually.

**Comment by JoshClose** [comment]
Yes, if you have the table column names, you could generate it instead of writing it by hand. That should work.

**Comment by beckyconning** [comment]
@recurs10n would you be up for sharing the solution you came to? I am trying to do this in a streaming manner as well.

**Comment by recurs10n** [comment]
Sure. I created a class called StaticDataCollection that looks like this. It's job is to contain the collection of data that's not in the CSV file. 

```
    public class StaticDataCollection
    {
        private readonly Dictionary<string, Func<string>> data = new Dictionary<string, Func<string>>();
        private readonly List<string> columnOrdinal = new List<string>();

        #region Properties
        /// <summary>
        ///     Gets the value of the column at the specified ordinal
        /// </summary>
        /// <param name="i">
        ///     The ordinal of the column to retrieve
        /// </param>
        /// <returns>
        ///     The value of the column at the specified position
        /// </returns>
        public string this[int i]
        {
            get
            {
                return this[columnOrdinal[i]];
            }
        }

        /// <summary>
        ///     Gets the valud of the column with the specified name
        /// </summary>
        /// <param name="columnName">
        ///     The name of the column
        /// </param>
        /// <returns>
        ///     The value of the column with the specified name
        /// </returns>
        public string this[string columnName]
        {
            get
            {
                return data[columnName].Invoke();
            }
        }

        /// <summary>
        ///     Gets the column count
        /// </summary>
        public int Count
        {
            get
            {
                return columnOrdinal.Count;
            }
        }
        #endregion Properties

        #region Public Methods
        /// <summary>
        ///     Gets the name of the column at the specified ordinal
        /// </summary>
        /// <param name="i">
        ///     The column ordrinal
        /// </param>
        /// <returns>
        ///     The name of the column
        /// </returns>
        public string GetName( int i )
        {
            return columnOrdinal[i];
        }

        /// <summary>
        ///     Adds a static column to the collection
        /// </summary>
        /// <param name="columnName">
        ///     The name of the column
        /// </param>
        /// <param name="columnValue">
        ///     The function that will return the value of the column
        /// </param>
        public void Add( string columnName, Func<string> columnValue )
        {
            if( data.ContainsKey( columnName ) )
                throw new InvalidOperationException( string.Format( "The specified column {0}, already has a static data definition.", columnName ) );

            data.Add( columnName, columnValue );
            columnOrdinal.Add( columnName );

        }

        /// <summary>
        ///     Gets the ordinal of the column with the specified name
        /// </summary>
        /// <param name="columnName">
        ///     The name of the column
        /// </param>
        /// <returns>
        ///     The column ordinal -or- -1 if the column was not found
        /// </returns>
        public int GetOrdinal( string columnName )
        {
            for( int i = 0; i < columnOrdinal.Count; i++ )
            {
                if( columnOrdinal[i].Equals( columnName, StringComparison.CurrentCultureIgnoreCase ) )
                    return i;
            }
            return -1;
        }
        #endregion Public Methods
    }
```

Then I copied the CsvDataReader class and added this:

```
        private readonly StaticDataCollection staticData = new StaticDataCollection();

        /// <summary>
        ///     Adds a static data point to the reader
        /// </summary>
        /// <param name="columnName">
        ///     The name of the column
        /// </param>
        /// <param name="data">
        ///     The function that returns the column value.
        /// </param>
        public void AddStaticData( string columnName, Func<CsvReader, string> data )
        {
            staticData.Add( columnName, () => data(csv) );
        }

```

After that, you just have to go through and update all the methods to account for the fact that you may have data outside your CSV. An example would be:

```
        public short GetInt16( int i )
        {
            if( ( csvFieldCount - 1 - i ) >= 0 )
                return csv.GetField<short>( i );

            return short.Parse( staticData[i - csvFieldCount] );
        }
```

Hope that helps.

**Comment by recurs10n** [comment]
If you want to add a static column called "Foo" with a value of "Bar", you'd do:

`reader.AddStaticData( "Foo", ( csv ) => "Bar" );`

If you wanted to do something like concat two CSV columns together, you'd do :

`reader.AddStaticData( "Foo", ( csv ) => csv[0] + csv[1] );`

**Comment by bakes82** [comment]
@recurs10n do you happen to have a helper/wrapper published that does this?
