### ISSUE TITLE
Bugs in CsvDataReader

### ISSUE THREAD

**Issue by recurs10n** [JoshClose/CsvHelper#1220]
I believe that I've found a couple bugs in CsvDataReader. 

The first relates to CSV files with no headers. In order to initialize properly, CSVDataReader needs to call csv.Read() in the constructor. However, when the file has no header row, this has the effect of skipping the first row of data. Without the call to Read() in the constructor, the SqlBulkCopy class throws an exception because it can't get the column count. 

The second is in the GetValue( int i ) method. It doesn't call IsDBNull( i ) before returning and the effect is that you can't ever return a null when you have an empty value, even if you've added string.Empty or other appropriate values to the csv.Configuration.TypeConverterOptionsCache.GetOptions<string>().NullValues collection. 

A third is related to the second one and is in the the GetValues( object[] values ) method where again it's not checking IsDBNull before returning the values array.

If you agree that these are all bugs, I think they should be pretty easy to fix and I wouldn't mind taking a crack at them.

**Comment by JoshClose** [comment]
I committed fixes. Can you take a look and see if they solve the issues?
d70d8c8eab9f92086675484040d183a5eabd8fec
02978221d2ae631281d1024189ccdbc90535eca5

**Comment by recurs10n** [comment]
Yes, they did.  I retested this morning and both are still issues on the current nuget package but are fixed by the commits above with a local build.

**Comment by JoshClose** [comment]
Version 12.1.2 contains these changes and is now on nuget.
