### ISSUE TITLE
Missing change logs

### ISSUE THREAD

**Issue by SIkebe** [JoshClose/CsvHelper#1222]
Hi! `change-log.md` doesn't seem to have changes in 12.1.0 and 12.1.1.
@JoshClose Could you update?
https://github.com/JoshClose/CsvHelper/blob/master/docs-src/src/content/change-log.md

Or are there any other way to see the changes easily?

**Comment by JoshClose** [comment]
Sorry. Updated. https://joshclose.github.io/CsvHelper/change-log/

**Comment by JoshClose** [comment]
The only other way would be to look at the commit history. https://github.com/JoshClose/CsvHelper/commits/master

**Comment by SIkebe** [comment]
Thank you for your quick response!
