### ISSUE TITLE
Is it possible to support column maybe exist?

### ISSUE THREAD

**Issue by bobdog1986** [JoshClose/CsvHelper#1223]
For example, a column "SomeColumn" exist in file1.csv but not file2.csv, could this repo support both of them? If not exsit , set it's value to default?

**Comment by JoshClose** [comment]
There is an `Optional` and `Default` mapping option.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.RegisterClassMap<FooMap>();
		csv.GetRecords<Foo>().ToList().Dump();
	}

	s = new StringBuilder();
	s.AppendLine("Id");
	s.AppendLine("2");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.RegisterClassMap<FooMap>();
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name).Optional().Default("default");
	}
}
```
![image](https://user-images.githubusercontent.com/114971/51789917-f94bb000-2153-11e9-9927-61339d5f9ce4.png)

**Comment by bobdog1986** [comment]
Hi Josh, thanks for your help. There is another question, if the cell content is illegal like "-", it cannot get the double or int value. In my understand, if I mark the property with [Default(0)], it should return 0 once fail to parse correct value.

**Comment by JoshClose** [comment]
No. Default will be used if there is no value.

**Comment by RonnieLawson** [comment]
> Though... I just noticed that when the column doesn't exist, the default isn't used. `Default` will only work when the field doesn't have a value.

Will this be changed? I'm looking for this behaviour: setting default if the value isn't supplied. Or should I just use the workaround of using ConvertUsing with GetField to work out if it's populated and set it accordingly?

**Comment by JoshClose** [comment]
So you want this?
```cs
Map(m => m.Property).Optional().Default("some value");
```

**Comment by JoshClose** [comment]
Maybe it would be more appropriate to do
```cs
Map(m => m.Property).Optional("default value");
```

**Comment by JoshClose** [comment]
I created a feature request for this. It seems like a reasonable thing to do. https://github.com/JoshClose/CsvHelper/issues/1407

**Comment by JoshClose** [comment]
This is complete an will be in release 12.2.0.

**Comment by RonnieLawson** [comment]
> This is complete an will be in release 12.2.0.

Great, thank you! 
Any idea when 12.2.0 is likely to be released?

**Comment by JoshClose** [comment]
Just pushed it. It should show up in nuget in a couple minutes.

**Comment by RonnieLawson** [comment]
> Just pushed it. It should show up in nuget in a couple minutes.

I've updated but it doesn't seem to see to think there are any arguments allowed for the Optional() method?

**Comment by JoshClose** [comment]
You need to use the combination of `.Optional().Default(value)`

**Comment by RonnieLawson** [comment]
> You need to use the combination of `.Optional().Default(value)`

Perfect!
