### ISSUE TITLE
Error reading blank column as DateTime?

### ISSUE THREAD

**Issue by kendallb** [JoshClose/CsvHelper#1226]
I just updated to the latest version of CsvHelper and it would appear the default handling for DateTime conversion has changed? I have a field that is blank in our unit tests, and it used to parse as DateTime.MinValue. Now it throws and exception saying it is an invalid format. I can use a custom type converter to fix this, but I would like to know how to enable the prior behavior as I don't know what other parts of the code might rely on this old behavior.

From Issue #191 I believe there must have been a breaking change related to this?

**Comment by kendallb** [comment]
I suspect this change is what broke it:

https://github.com/JoshClose/CsvHelper/commit/941fac99439842d9a029ba871c0a5bc5f94e8047#diff-4237752eff284771568f9374c8fdeb97

What was the reason this was changed, and how can I get that behavior back again?

**Comment by JoshClose** [comment]
It changed because none of the other converters use `default` when the field is empty.

The recommendation is to use to use `DateTime?` instead. You'll get a `null` in that case. If you really want the former behavior, you can create a customer converter like this.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,DateTime");
	s.AppendLine("1,");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.TypeConverterCache.AddConverter<DateTime>(new MinValueDateTimeConverter());
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public DateTime DateTime { get; set; }
}

public class MinValueDateTimeConverter : DateTimeConverter
{
	public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
	{
		if (string.IsNullOrWhiteSpace(text))
		{
			return DateTime.MinValue;
		}
		
		return base.ConvertFromString(text, row, memberMapData);
	}
}
```

**Comment by kendallb** [comment]
Thanks, I ended up making a custom converter and audited the rest of the code to make sure no other DateTime conversion would be affected.

**Comment by lawrencekoh88** [comment]
Hi, I am using the latest version of CsvHelper. However, when I define `DateTime?` for a field that may contain empty strings, I get the following error:
CsvHelper.TypeConversion.TypeConverterException
  Message=The conversion cannot be performed.
    Text: ''
    MemberType: System.Double
    TypeConverter: 'CsvHelper.TypeConversion.DoubleConverter'

I am currently using CsvHelper in a custom template class in the following manner:

`public class CsvHandler<T>
    {
        public string mCsvFilePath { get; set; }
        public bool mCsvFileHasHeader { get; set; }
        public ClassMap classMap { get; set; }

        public CsvHandler(bool csvFileHasHeader, string csvFilePath)
        {
            mCsvFilePath = csvFilePath;
            mCsvFileHasHeader = csvFileHasHeader;
        }

        public List<T> ReadCsv()
        {
            List<T> recordList = new List<T>();
            using (var reader = new StreamReader(mCsvFilePath))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                csv.Configuration.HeaderValidated = null;
                csv.Configuration.MissingFieldFound = null;
                csv.Configuration.TrimOptions = TrimOptions.Trim;
                var options = new TypeConverterOptions { Formats = new[] { "yyyyMMdd", "dd/M/yyyy", "dd/MM/yyyy" } };
                csv.Configuration.TypeConverterOptionsCache.AddOptions<DateTime>(options);
                classMap = csv.Configuration.AutoMap<T>();

                return recordList = csv.GetRecords<T>().ToList();
            }
        }
    }`
