### ISSUE TITLE
Refer to the same object

### ISSUE THREAD

**Issue by robertovaldesperez** [JoshClose/CsvHelper#1228]
Hello,

I have this mapping:

```cs
public sealed class LoadPropertyCsvMap : ClassMap<Property>
{
	public LoadPropertyCsvMap()
	{
		...
		Map(m => m.Development).ConvertUsing(x => !string.IsNullOrWhiteSpace(x.GetField<string>(10)) ? new Development()
		{
			Reference = x.GetField<string>(10)
		} : null); // Optional
	}
}
```

A "Development" can have many "Property". I would like to create only one "Development" for all the "Property". Is it possible to refer to the same "Development" instead of creating a new object for each csv line?

**Comment by JoshClose** [comment]
Can you give me your class structures?

**Comment by JoshClose** [comment]
So you only want a single `Development` object used for all `Property` records? You're setting a `Reference` property on it though.

**Comment by robertovaldesperez** [comment]
Hello @JoshClose 

This is my class structures:

`using System;
....
namespace Project.Model
{
    public class Property : Entity<long?>
    {
        .....
        public virtual Development Development { get; set; }
        .....
    }
}`

`namespace Project.Model
{
    public class Development : Entity<long?>
    {
        ....
        public virtual ISet<Property> Properties { get; set; }
    }
}`

**Comment by JoshClose** [comment]
Btw, you can just put three ticks at the beginning of the code block, followed by the language, and 3 ticks at the end.

    ```cs
    // Code goes here
    ```

Here is how you can build up what I think you're looking for. You can change it to build a list of `Property` records instead too.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Property,Development");
	s.AppendLine("Property1,Development1");
	s.AppendLine("Property2,Development1");
	s.AppendLine("Property3,Development1");
	s.AppendLine("Property4,Development1");
	s.AppendLine("Property5,Development1");
	s.AppendLine("Property6,Development2");
	s.AppendLine("Property7,Development2");
	s.AppendLine("Property8,Development2");
	s.AppendLine("Property9,Development2");
	s.AppendLine("Property10,Development3");
	s.AppendLine("Property11,Development3");
	s.AppendLine("Property12,Development3");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Read();
		csv.ReadHeader();
		
		var records = new List<Development>();
		var previousDevelopmentValue = string.Empty;
		Development currentDevelopment = null;
		while (csv.Read())
		{			
			var currentDevelopmentValue = csv.GetField("Development");
			if (currentDevelopmentValue != previousDevelopmentValue)
			{				
				currentDevelopment = new Development
				{
					Name = currentDevelopmentValue,
					Properties = new HashSet<Property>()
				};
				records.Add(currentDevelopment);
			}
			
			var property = new Property
			{
				Name = csv.GetField("Property"),
				Development = currentDevelopment
			};
			currentDevelopment.Properties.Add(property);
			
			previousDevelopmentValue = currentDevelopmentValue;
		}
		
		records.Dump();
	}
}

public class Property
{
	public string Name { get; set; }
	
	public Development Development { get; set; }
}

public class Development
{
	public string Name { get; set; }
	
	public ISet<Property> Properties { get; set; }
}
```

![image](https://user-images.githubusercontent.com/114971/52865906-3aa3ff80-3103-11e9-8818-8aac47f34801.png)

**Comment by robertovaldesperez** [comment]
Sorry I forgot to mention that the Development can be null, so, the
Property may not have Development
