### ISSUE TITLE
Write list of objects with custom column names

### ISSUE THREAD

**Issue by mibe94** [JoshClose/CsvHelper#1229]
I am trying to write a field which is a list of strings into multiple columns with custom column names. The expected result is:

ID, NumberOfItems, Item1, Item2, Item3
0,3,first,second,third

While reading can be done with usage of ConvertUsing on the map, I cannot figure out how to write custom headers.

```c#
public class RecordExample
{
    public int ID { get; set; }

    public IList<string> Items { get; set; }

}

public class RecordExampleMap : ClassMap<RecordExample>
{
    public RecordExampleMap()
    {
        this.Map(r => r.ID).Name("ID");
        this.Map(r => r.Items).Name("NumberOfItems").ConvertUsing(record => record.Items.Count.ToString());
        // TODO: dynamically map each item to a column with name $"Item{index}"
    }
}
```

How can I achieve this?

**Comment by losmac** [comment]
@mibe94, assuming that `re` is a `List<RecordExample>()`, you can project your data as anonymous data type:

```
var records = re
	.Select(r=> new
		{
			ID = r.ID,
			NumberOfItems = r.Items.Count(),
			Item1 = r.Items[0],
			Item2 = r.Items[1],
			Item3 = r.Items[2]
		})
	.ToList();
			
InstanceOfCsvWriter.WriteRecords(records);

```
See the documentation for further details: [Write Anonymous Type Objects](https://joshclose.github.io/CsvHelper/examples/writing/write-anonymous-type-objects)

Cheers
Maciej
