### ISSUE TITLE
Exclude column header names in output of CSV file

### ISSUE THREAD

**Issue by scionwest** [JoshClose/CsvHelper#1236]
I need to write out a CSV file from some data models I've been given, however the consumer of this CSV file can't have the column headers in the file.

Instead of an output like this:

```
Id,Make,Model
0,Toyota,4Runner
1,Lexus,LFA
```

I need the CSV output to look like
```
0,Toyota,4Runner
1,Lexus,LFA
```

Is there a means to configure the API to do this?

**Comment by scionwest** [comment]
Figured it out - I was looking through the docs and couldn't find what I was looking for. Found it mentioned though on a blog post somewhere.

```
    using (var csvWriter = new CsvWriter(streamWriter))
    {
        csvWriter.Configuration.HasHeaderRecord = false;
        csvWriter.WriteRecords(transferObjects);
    }
```

**Comment by stevenmcneese** [comment]
using (var csv = new CsvWriter(writer,CultureInfo.InvariantCulture))
                                        {
                                            csv.Configuration.HasHeaderRecord = false;
                                        }

I cannot get the above to work. It says HasHeaderRecord is read only

**Comment by AltruCoder** [comment]
You now have to pass the configuration to the `CsvWriter` constructor.  The `Configuration` is readonly inside `CsvWriter`.
```csharp
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	HasHeaderRecord = false
};
using (var csv = new CsvWriter(writer, config))
{
}
```
