### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by recepogras** [JoshClose/CsvHelper#1237]
Hello,

thank you for the great library. It works like a charm in my VS and while debugging. When i compile an run it on production, i get an error all the time. 

"Die Datei oder Assembly "CsvHelper, Version=12.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden. "

Looks like, that in productions some dependencies are missing. I have installed a .net framework version greater 4.5.

What i can see in nuget is, that the following packages are needed

**.NetFramework 4.5**  
System.ValueTuple (<=4.4.0)

**.NetStandard 4,2** 
System.Reflection.TypeExtension (>4.4.0)
Microsoft.CSharp (>=4.4.0)

What i tried is to add these packages via nuget.  For System.Reflection i had some issue, so i had to change my project target framwork to .net 4.6.1. After this i was able to add system.reflection (but just in 4.3). Might be this the issue?

Other dependencies installed via nuget:
System.ValueTuple = Version 4.5.0
System.Reflection.TypeExtensions = Version 4.5.0
Microsoft.CSharp= Version 4.5.0

The problem does still exist. Does anyone had similar issues? In other threads, i was not able to find the solution.

Thanks in advance

Addition:

Windows Log
Anwendung: SAM_Workers.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: **System.Reflection.ReflectionTypeLoadException
   bei System.Reflection.RuntimeModule.GetTypes(System.Reflection.RuntimeModule)
   bei System.Configuration.Install.AssemblyInstaller.GetInstallerTypes(System.Reflection.Assembly)
   bei System.Configuration.Install.AssemblyInstaller.InitializeFromAssembly()**

Ausnahmeinformationen: System.InvalidOperationException
   bei System.Configuration.Install.AssemblyInstaller.InitializeFromAssembly()
   bei System.Configuration.Install.AssemblyInstaller.Install(System.Collections.IDictionary)
   bei SAM_Workers.Program.InstallService()
   bei SAM_Workers.Program.Main(System.String[])

**Comment by GeertvanHorrik** [comment]
Looks like you installed System.ValueTuple = Version 4.5.0, but the dependency is 4.4.0. Did you add the binding redirect in your app.config?

**Comment by JoshClose** [comment]
I just released version `12.1.3` that has a separate `net47` build that doesn't use `System.ValueTuple`. Let me know if it's still a problem.
