### ISSUE TITLE
The conversion cannot be performed.\r\n Text: "\r\n MemberType: System.Double\r\n

### ISSUE THREAD

**Issue by esspijep** [JoshClose/CsvHelper#1238]
Hi,

I am reading from an AWS S3 CSV file and got it to be read as a Stream but I am having this error:

![image](https://user-images.githubusercontent.com/41111784/52982596-ea3de200-3421-11e9-9ae5-4ea87282df5f.png)

This is how I used the code:

```cs
using (var responseStream = response.ResponseStream)
{
	using (var sr = new StreamReader(responseStream))
	{
		var config = new CsvHelper.Configuration.Configuration
		{
			HasHeaderRecord = false
		};

		using (var csv = new CsvReader(sr, config))
		{
			var records = csv.GetRecords<Model>();
			return records;
		}
	}
}
```

I think the issue is the \r\n but if the issue is something else please let me know. Please advise.

**Comment by JoshClose** [comment]
Click on the magnifying glass icon of `Message` and paste the full text in here.

**Comment by Norrch2** [comment]
@esspijep You will probably want to massage the value by getting rid of any non character digits. From this example, double.TryParse will not be able to conver the values "\r\n" that is in your string.
