### ISSUE TITLE
Is .Net 4 Framework compatibility thinkable

### ISSUE THREAD

**Issue by M1k50** [JoshClose/CsvHelper#1242]
Hi Josh,
I am working on a small tool that enables me to write data into a table by column and row values and then exports the result to a csv, which is where CsvHelper came into play.
Unfortunately I had to switch to .Net 4 because of issues referencing a higher Framework .dll an now cannot use CsvHelper anymore because it requires .Net 4.5.
Is there any chance to introduce compatibility?

cheers
Mirko

**Comment by GeertvanHorrik** [comment]
.NET 4.0 is not even supported by MS anymore. I think you should fix the other libs instead of downgrading all the others.

**Comment by M1k50** [comment]
So true! I wish I hat that in my hands. The issue is Spotwares cTrader, which is still using the outdated .Net 4. It really is a hassle trying to work with that kind of an old base dll.

**Comment by GeertvanHorrik** [comment]
Technically, you should be able to reference even .net 2.0 assemblies in higher assemblies. I recommend contacting them for an updated version (but that could require a paid subscription).

**Comment by addisonvex** [comment]
I would also like support for .NET 4.0. We have a number of wealthy but stubborn customers still running Windows XP!

**Comment by GeertvanHorrik** [comment]
> We have a number of wealthy but stubborn customers still running Windows XP!

Great, if these wealthy customers can fully support (as in pay for) the whole development, it can be considered a serious option.

**Comment by addisonvex** [comment]
> Great, if these wealthy customers can fully support (as in pay for) the whole development, it can be considered a serious option.

Sadly this is not how this works for us. Had CsvHelper been compatible with our platforms then we would have donated. However we'd prefer to look for a quicker solution than await a third-party development cycle. Thanks for the response though!

**Comment by JoshClose** [comment]
You can download an older version of CsvHelper that is 4.0 compatible. CsvHelper is using `Microsoft.CSharp` which doesn't work with anything less than 4.5. CsvHelper version 2.16.3 is the last version that is net40 compatible. https://www.nuget.org/packages/CsvHelper/2.16.3
