### ISSUE TITLE
Writing nested properties

### ISSUE THREAD

**Issue by nazar554** [JoshClose/CsvHelper#1243]
How do I write nested properties (opt-in)? I set `IgnoreReferences` to skip automapping them,
but adding a `Map` explicitly produces no values:

```
PropertyA;B.PropertyB
1
```

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CsvHelper;
using CsvHelper.Configuration;
using System.IO;

namespace ConsoleApp1
{
    public class A
    {
        public string PropertyA { get; set; } = "1";

        public B B { get; set; }
    }

    public class B
    {
        public string PropertyB { get; set; } = "2";
    }

    class Program
    {
        static void Main(string[] args)
        {
            var stream = new StringWriter();
            var config = new Configuration
            {
                IgnoreReferences = true
            };
            var map  =config.AutoMap<A>();
            var writer = new CsvWriter(stream, config);
            map.Map(x => x.B.PropertyB).Name("B.PropertyB");

            writer.WriteRecords(new[] { new A { B = new B() } });
            writer.Dispose();

            var s = stream.ToString();
        }
    }
}

```

**Comment by JoshClose** [comment]
This looks like a bug. It's writing the header when it shouldn't be.

Is your goal to have `IgnoreReferences = true` and then just add in the references you want? If so, use a `ClassMap`. It's all opt-in. If you want to auto map and just ignore things, you can use attributes.

Attributes:
```cs
void Main()
{
	var stream = new StringWriter();
	var writer = new CsvWriter(stream);

	writer.WriteRecords(new[] { new A { B = new B() } });
	writer.Dispose();

	var s = stream.ToString();	
	s.Dump();
}

public class A
{
	public string PropertyA { get; set; } = "1";

	public B B { get; set; }
}

public class B
{
	[Ignore]
	public string PropertyB { get; set; } = "2";
}
```

ClassMap:
```cs
void Main()
{
	var stream = new StringWriter();
	var writer = new CsvWriter(stream);
	writer.Configuration.RegisterClassMap<AMap>();

	writer.WriteRecords(new[] { new A { B = new B() } });
	writer.Dispose();

	var s = stream.ToString();	
	s.Dump();
}

public class A
{
	public string PropertyA { get; set; } = "1";

	public B B { get; set; }
}

public class B
{
	public string PropertyB { get; set; } = "2";
}

public class AMap : ClassMap<A>
{
	public AMap()
	{
		Map(m => m.PropertyA);
	}
}
```

**Comment by nazar554** [comment]
I have a lot of different objects (with a lot of properties), so writing a `ClassMap` for each one is not an option.
My actual problem that the objects are from `EntityFramework` and `CsvHelper` follows all virtual properties even when I don't need it.

So I need to do `AutoMap` to save typing for each entity, but I don't need to follow nested objects until I explicitly map them

**Comment by JoshClose** [comment]
Nested, meaning the parent class? If you have `A : B` and you don't want to include all the properties on B, then there isn't a built in way to do that. I think I could easily do this by exposing the `BindingFlags` used when finding the properties. You could just set `BindingFlags.DeclaredOnly` then.

Currently, you can auto map and just ignore the references that you don't want like this.

```cs
void Main()
{
	var stream = new StringWriter();
	var writer = new CsvWriter(stream);	
	writer.Configuration.RegisterClassMap<AMap>();

	writer.WriteRecords(new[] { new A() });
	writer.Dispose();

	var s = stream.ToString();
	s.Dump();
}

public class A : B
{
	public string PropertyA { get; set; } = "1";
}

public class B
{
	public string PropertyB { get; set; } = "2";
}

public class AMap : ClassMap<A>
{
	public AMap()
	{
		AutoMap();
		Map(m => m.PropertyB).Ignore();
	}
}
```

**Comment by nazar554** [comment]
Sorry, I think you misunderstood my problem.
It's not about inheritance, it's actually about reference properties (the `public B B { get; set; }`)
If I do `AutoMap()` then `B.PropertyB ` gets included as a column, which I don't like so I set `IgnoreReferences = true`.
But if I want to opt-in to mapping it I get the weird result above.

**Comment by JoshClose** [comment]
Your issue is that you're not registering the map that you create. You need to do this:

```cs
config.RegisterClassMap(map);
```
