### ISSUE TITLE
Type checks in MemberMap.Constant and MemberMap.Default are too strict

### ISSUE THREAD

**Issue by marcrocny** [JoshClose/CsvHelper#1249]
Each allows only an exact type match, which presents an issue when trying to assign constant/default values to `Nullable<T>` properties, where this is built from a configuration read at run-time. 

In my case, potential constant or default values have to be read from strings. No method for conversion that I've found allows (for example) an integer string to be converted to `int?`. Even the `TypeConverter` for an `int?` property yields an `int` after conversion. This should work since `int` is assignable to `int?`.

Is there any reason this type-check couldn't be relaxed? E.g., change [this line](https://github.com/JoshClose/CsvHelper/blob/89edc486b51086453bc91e043f0f82789374b829/src/CsvHelper/Configuration/MemberMap.cs#L177)
```
if( constantValue != null && constantValue.GetType() != Data.Member.MemberType() )
```
to
```
if( constantValue != null && Data.Member.MemberType().IsAssignableFrom(constantValue.GetType()))
```

**Comment by marcrocny** [comment]
After a little more research (reminder of things I forgot about C#): this feature is broken for `Nullable<>` properties, and there's no workaround. `GetType()` will never return a `Nullable<>` type definition. See https://stackoverflow.com/q/6931783/85269. As composed the type-check will always fail.

**Comment by JoshClose** [comment]
In next release
