### ISSUE TITLE
TryGetField throws 'Index outside the bounds of the array' exception for DateTime converters

### ISSUE THREAD

**Issue by paulcurren** [JoshClose/CsvHelper#1250]
Issue is here:
line 707: if (string.IsNullOrWhiteSpace(context.Record[index]))

This extra bit of code does not range change the index in the same way that GetField(type, index, converter) does. Hence it is possible to get an exception if you don't have enough columns in your data and the converter type is DateTime.

E.g.:
Field1, Field2, Field3, Field4
1, 2, 3

TryGetField(typeof(DateTime), "Field4", out object value);

**Comment by JoshClose** [comment]
Fixed. This will be in release >= 12.2.1.
