### ISSUE TITLE
Issue while retrieving records dynamically

### ISSUE THREAD

**Issue by J523** [JoshClose/CsvHelper#1259]
Hi,
I am trying to read a csv file with headers through GetRecords<dynamic>. The intention is to loop through the list retrieved. In every iteration the record would be cast to a dictionary object since I have to work with key value pairs later. But the record which is retrieved is not coming as a json object format. I logged it through json serializer and the object is of form - {"Property1;Property2;Property3;Value1;Value2;Value3"} and not {"Property1":"Value1" , "Property2":"Value2" , "Property3":"Value3"}

**Comment by AltruCoder** [comment]
Not sure if this is what you are trying to do, but this works for me.

```csharp
using (var stream = new MemoryStream())
using (var writer = new StreamWriter(stream))
using (var reader = new StreamReader(stream))
using (var csv = new CsvReader(reader))
{
    csv.Configuration.Delimiter = ",";
    writer.WriteLine("Property1,Property2,Property3");
    writer.WriteLine("Value1,Value2,Value3");
    writer.WriteLine("Value4,Value5,Value6");
    writer.Flush();
    stream.Position = 0;

    var records = csv.GetRecords<dynamic>().ToList();

    var json = JsonConvert.SerializeObject(records);
    var dictionary = JsonConvert.DeserializeObject<List<Dictionary<string, string>>>(json);
}
```

**Comment by J523** [comment]
Hi David,
Thank you for your reply. I am actually trying to read a SQL (DB) export of a view which outputs the results as a file with csv extension. It has got headers as the table columns but it is not really a comma separated file.
So I read the file like this

        using (var reader = new StreamReader("filepath", FileEncoding))
                        using (var csv = new CsvReader(reader))
                        {
                            var records = csv.GetRecords<dynamic>();
                            
                           //post this I iterate over the records 

                        foreach (dynamic record in records.ToList() )
                            {
                                     //issue here. when I serialized record I don't get it in json object format  and hence cant work with any key / values as intended    
                             }

                           }

One thing to note it works completely fine when I run it through IDE but not when I deploy it to a different environment. I have checked for all the framework dependencies and have their run-times installed on this environment but still it doesn't work.

Best Regards,
VP

**Comment by J523** [comment]
Hi again ! 

It was my bad. I realized the delimiter was in fact a semicolon and it worked explicitly with your configuration setting (with ";" of course) in the other environment.  It was treating it by default till now in the IDE. Anyway glad it works and couldn't thank you enough for your help ! Have a nice weekend ahead !

//VP
