### ISSUE TITLE
Custom Headers  - CsvHelper.ReaderException: 'There is no header record to determine the index by name.'

### ISSUE THREAD

**Issue by sppc42** [JoshClose/CsvHelper#1262]
Hi,

I have a source file with no headers, so whilst reading, am reading it with `HasHeaderRecord = false`. But whilst writing it back, I need to put in my own custom headers. I tried using the `NameAttribute` but that fails with error : 

`CsvHelper.ReaderException: 'There is no header record to determine the index by name.'`

My class is:

   ```
 public sealed class MaxTimes
    {
        [Index(0)]
        [Name("Agent Name")]
        public string Agent { get; set; }

        [Name("Demand Any")]
        [Index(1)]
        public string Demand { get; set; }
        ....
     }
```

Reading:

   ```
var inputCsvReader = new CsvReader(sourceFileReader, new CsvHelper.Configuration.Configuration
            {
                HasHeaderRecord = false,
                MissingFieldFound = null
            });

            foreach (var row in inputCsvReader.GetRecords<MaxTimes>())
            {
              ....
            }
```
The exception is seen in the foreach loop above.

Looks like a bug wherein even if `HasHeaderRecord = false`, it detects `NameAttribute `and bails out. 

It should not use the `NameAttribute `when reading records if `HasHeaderRecord = false` is given in configuration.

Let me know if you need any more info.

Thanks
sandy

**Comment by kelvix** [comment]
I think the issue lies specifically on the [ExpressionManager L171-L186](https://github.com/JoshClose/CsvHelper/blob/2914f6856febbf7488c53ed65948a00a39f95a22/src/CsvHelper/Expressions/ExpressionManager.cs#L171-L186).

I'm using CsvHelper as a .NET core dependency on macOS and I'm having trouble running the test suite on my device to confirm my theory. As a work around I created a NameSet class map and a Index class map. If time permits I'll try to reproduce on my work provided Windows device.

If a pull request is welcome I can also aim for a pull request.

**Comment by c0shea** [comment]
I'm having this same exact problem. I would expect that the `Name` attribute would be ignored when reading when I have `Configuration.HasHeaderRecord = false` but used when writing headers.

**Comment by JoshClose** [comment]
I think that makes sense. When reading, it will ignore, but it needs to be there for writing purposes.

**Comment by HipDragon** [comment]
It appears that the pull request corrects this issue. There are at least a few people looking forward to this being added into CsvHelper. Any status update on this feature?

**Comment by leoerlandsson** [comment]
Is there any update on this? We're having the same problem.

**Comment by JoshClose** [comment]
Fixed.

**Comment by HipDragon** [comment]
When is the next release expected?

**Comment by JoshClose** [comment]
Just pushed version 28.0.0.
