### ISSUE TITLE
Crazy extra columns showing up for some reason (12.1.2)

### ISSUE THREAD

**Issue by EricZimmerman** [JoshClose/CsvHelper#1264]
all of a sudden i am seeing this:

BagPath,NodeId,Slot,NodeSlot,MRUPosition,AbsolutePath,ShellType,Value,ChildBags,IsEmpty,CreatedOn,ModifiedOn,Width,Height,AccessedOn,LastWriteTime,IsEmpty,MFTEntry,Width,MFTSequenceNumber,Height,ExtensionBlockCount,Width,FirstInteracted,Height,LastInteracted,HorizontalResolution,VerticalResolution,Miscellaneous,Flags,Guid,PixelFormat,Flags

vs what is actually in my class, 

where are these extra columns coming from, like PixelFormat, Flags, Resolution and all that? they are clearly not in my class, but all of a sudden are showing up in the output.

when i step thru the data the data is good going into WriteRecords, but then this shows up.

Any ideas?

**Comment by EricZimmerman** [comment]
OK so it turns out i have a BitMap property in the class in question. I did not mark that column as Ignore, so it looks like csvhelper pulled in all available properties and auto added them? i wouldnt have guessed it would do that, but here we are. 

the icon property is set to null in my code, but even when i ignore the field:

 foo.Map(m => m.Icon).Ignore();

it still shows up =(

Here you can see the properties for bitmap:

https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap?view=netframework-4.7.2

how do i stop this?

**Comment by EricZimmerman** [comment]
i just saw 

csv.Configuration.IgnoreReferences = true

when looking thru issues. will try it and see what happens

**Comment by EricZimmerman** [comment]
That fixed it! yay

**Comment by JoshClose** [comment]
Glad you figured it out!
