### ISSUE TITLE
MissingMethodException while using Csvhelper UseExcelLeadingZerosFormatForNumerics =true configuration in c#

### ISSUE THREAD

**Issue by SABARISHV06** [JoshClose/CsvHelper#1268]
Hi @JoshClose & team,

I'm trying to add zeros before the zipcode since US zipcode follows leading zeros. Henceforth, I reused the method available in CsvHelper UseExcelLeadingZerosFormatForNumerics method but it is not popping up, I using CsvHelper version v12.1.1. Could you help me how to fix it? 

![image](https://user-images.githubusercontent.com/16812919/54523403-75fd4c80-4995-11e9-91d6-cd775927ea6c.png)

**Comment by AltruCoder** [comment]
It looks like that method hasn't been available since version 3.0.0. This stackoverflow answer might help you. [https://stackoverflow.com/questions/54555534/what-is-the-equivalent-of-iwriterconfiguration-useexcelleadingzerosformatfornume](url)

**Comment by JoshClose** [comment]
All of the Excel specific stuff was removed. It should be a part of a contrib library instead, as it doesn't have anything to do with CSV itself. @AltruCoder's answer should work.
