### ISSUE TITLE
Escaping double quotes with GetRecords

### ISSUE THREAD

**Issue by hgmamaci** [JoshClose/CsvHelper#1269]
Hi
I have a problem while reading with GetRecords: If the text field has quotes inside it throws BadDataException.
... ,**"*CODE REPLACED BY "NC"//BY ME"**, ...
![2019-03-18_17-02-50](https://user-images.githubusercontent.com/3295186/54535572-d8f3e100-499f-11e9-88f1-e37299fe13d3.png)

**Comment by AltruCoder** [comment]
You could set the configuration to ignore quotes. `csv.Configuration.IgnoreQuotes = true;`

**Comment by hgmamaci** [comment]
> You could set the configuration to ignore quotes. `csv.Configuration.IgnoreQuotes = true;`

But then the string will not sbe starting and ending with double quotes?
I mean from the example
 ,"*CODE REPLACED BY "NC"//BY ME", 
I should get following
*CODE REPLACED BY "NC"//BY ME

**Comment by AltruCoder** [comment]
I tried the following and it appears to return what you are looking for.  I think the only issue would be you can't have a comma now in the middle of the text field.

```csharp
using (var stream = new MemoryStream())
using (var reader = new StreamReader(stream))
using (var writer = new StreamWriter(stream))
using (var csv = new CsvReader(reader))
{
    writer.WriteLine("Header1,Header2,Header3");
    writer.WriteLine("\"Record1\",\" * CODE REPLACED BY \"NC\"//BY ME\",\"Record3\"");
    writer.Flush();
    stream.Position = 0;

    csv.Configuration.Delimiter = ",";
    csv.Configuration.IgnoreQuotes = true;

    var records = csv.GetRecords<dynamic>().ToList();
}
```

**Comment by hgmamaci** [comment]
Hmm. That is not going to help than. As these are shared messages and can contain quotes, double quotes, comma etc.

Is there a way to ignore any double quotes except one right after and before field seperator?

**Comment by AltruCoder** [comment]
Not as far as I know, but my knowledge of CsvHelper is somewhat limited.

**Comment by AltruCoder** [comment]
I noticed in the other issue Josh referenced part of the rfc. https://tools.ietf.org/html/rfc4180#section-2

> 7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example: "aaa","b""bb","ccc"

Is there any way you can escape the double-quotes in the file? I tried it without `csv.Configuration.IgnoreQuotes = true;` and the internal quotes escaped and it worked correctly.

**Comment by hgmamaci** [comment]
> I noticed in the other issue Josh referenced part of the rfc. https://tools.ietf.org/html/rfc4180#section-2
> 
> > 1. If double-quotes are used to enclose fields, then a double-quote
> >    appearing inside a field must be escaped by preceding it with
> >    another double quote.  For example: "aaa","b""bb","ccc"
> 
> Is there any way you can escape the double-quotes going into the file? I tried it without `csv.Configuration.IgnoreQuotes = true;` and the internal quotes escaped and it worked correctly.

So; if the client delivers following
,"*CODE REPLACED BY "NC"//BY ME",
as 
,"*CODE REPLACED BY ""NC""//BY ME",
it will work. Is that right?

**Comment by AltruCoder** [comment]
Yes.

**Comment by hgmamaci** [comment]
> Yes.
> 
> ```cs
> using (var stream = new MemoryStream())
> using (var reader = new StreamReader(stream))
> using (var writer = new StreamWriter(stream))
> using (var csv = new CsvReader(reader))
> {
>     writer.WriteLine("Header1,Header2,Header3");
>     writer.WriteLine("\"Field 1\",\" * CODE REPLACED BY \"\"NC\"\"//BY ME\",\"Field, 3\"");
>     writer.Flush();
>     stream.Position = 0;
> 
>     csv.Configuration.Delimiter = ",";
> 
>     var records = csv.GetRecords<dynamic>().ToList();
> }
> ```

Thank you very much. This helps to understand

**Comment by JoshClose** [comment]
Read over [RFC 4180](https://tools.ietf.org/html/rfc4180) that @AltruCoder referenced. It's pretty short. The rules for CSV are pretty simple. Unfortunately a lot of systems will generate bad CSV data that is nearly impossible to parse correctly, unless you know the rules of that specific system.
