### ISSUE TITLE
Write csv file to string?

### ISSUE THREAD

**Issue by NeilMeredith** [JoshClose/CsvHelper#128]
I would like to use the csvhelper to export a list of objects to a csv file in the browser.  All I see in the documentation are ways to write directly to a file - can you return the csv file as a string for export?

I tried something like this, but the 'WriteRecords' method is closing the memory stream:

``` c#
 using (var memStream = new MemoryStream())
            {
                using (var csv = new CsvWriter(new StreamWriter(memStream)))
                {
                    csv.WriteRecords(events);
                    return File(memStream, "text/csv", "Report123.csv");
                }
            }
```

**Comment by amolstest** [comment]
Hi Josh your code is not working on 76224 rows collection 

it's brack execution 

can please suggest me any workaround for this

**Comment by JoshClose** [comment]
Can you start a new issue for this please?

**Comment by amolstest** [comment]
Thank....
sure

**Comment by JoeDM09** [comment]
Found this via google and the answer is a bit old so thought I'd give it an update for anyone else who finds this.

	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture, true))
	{
		csv.WriteRecord(csvRow);
		csv.Flush();
		var newRecord = writer.ToString();
    }
