### ISSUE TITLE
Trouble with Mapping a field that is not in the source file

### ISSUE THREAD

**Issue by Y2KCobra** [JoshClose/CsvHelper#1290]
Have Class Foo
{
public a
public b
public c
public d
}
CSV.File.Hearer.ROW = (a_name, b_name, c_name)
Have FooMap(Passed Value)
{
           Map(m => m.a).Name("a_name");
            Map(m => m.b).Name("b_name");
            Map(m => m.c).Name("c_name");
            Map(m => m.d).Constant(Passed Value);
}

I get missing column error and it fills the d field with 000-000-000 instead of 84e-f12...

I do not want to ignore an error but need to pass a foreign key to my record.

Have read what I can but am missing something.

Please help, this is a key effort in a project I am doing.

Thank you in advance,

Steve

**Comment by AltruCoder** [comment]
Looks like this is a known issue #1030.  The following is a temporary workaround.
```csharp
Map(m => m.d).ConvertUsing((IReaderRow row) => Value);
```

**Comment by AltruCoder** [comment]
It's also helpful if you can include a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
```csharp
public static void Main(string[] args)
{
    using (MemoryStream stream = new MemoryStream())
    using (StreamWriter writer = new StreamWriter(stream))
    using (StreamReader reader = new StreamReader(stream))
    using (CsvReader csv = new CsvReader(reader))
    {
        writer.WriteLine("a_name,b_name,c_name");
        writer.WriteLine("a value,b value,c value");
        writer.Flush();
        stream.Position = 0;

        csv.Configuration.RegisterClassMap(new FooMap(Guid.NewGuid()));

        var records = csv.GetRecords<Foo>().ToList();
    }            
}

public class Foo
{
    public string a { get; set; }
    public string b { get; set; }
    public string c { get; set; }
    public Guid d { get; set; }
}

public sealed class FooMap : ClassMap<Foo>
{
    public FooMap(Guid Value)
    {
        Map(m => m.a).Name("a_name");
        Map(m => m.b).Name("b_name");
        Map(m => m.c).Name("c_name");
        Map(m => m.d).Constant(Value);
    }
}
```
