### ISSUE TITLE
writing csv doubles properties for hidden base members

### ISSUE THREAD

**Issue by spooky** [JoshClose/CsvHelper#1295]
When a type has a property that hides a base class property, the writer uses both for output

quick spike to reproduce:
```c#
class Foo
{
    public int MyProperty { get; set; }
}

class Bar : Foo
{
    public new string MyProperty { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        var x = new Bar
        {
            MyProperty = "text"
        };

        using (var csv = new CsvWriter(Console.Out))
        {    
            csv.WriteRecords(new[] { x });
        }
    }
}

```

Current output:
```text
MyProperty,MyProperty
text,0
```

Expected output:
```text
MyProperty
text
```

Using CsvHelper version 12.1.2

**Comment by JoshClose** [comment]
This is fixed and will be in release >= 12.2.2.

I'm now walking up the inheritance tree and only adding properties with names that haven't already been added. This will ensure the child `new` property will be used instead of the parent property.
