### ISSUE TITLE
Does CsvHelper support carriage returns in string fields?

### ISSUE THREAD

**Issue by WallaceKelly** [JoshClose/CsvHelper#13]

**Comment by tonidef** [comment]
@JoshClose , I'm finding my csv is treating carriage returns as new rows of data. Any suggestions on how to address this?

![csv_carriage_return_issue](https://cloud.githubusercontent.com/assets/12530420/8828363/5df42a4c-3057-11e5-86dc-4e5e80f5d15e.PNG)

**Comment by JoshClose** [comment]
Are you saying CsvReader reading it improperly? Or CsvWriter is writing it improperly? Or something else?

**Comment by tonidef** [comment]
I'm using CsvWriter with a StringWriter.

**Comment by JoshClose** [comment]
If you're opening it up in a text editor, the formatting is going to be as you'd expect. Take a look over RFC 4180; it's a short read. https://tools.ietf.org/html/rfc4180

If a field has a carriage return in it `\r\n`, then the field must be escaped by putting quotes around it `"1\r\n2"`. The data you have is showing the field with the break has quotes around it. 

Opening up in a text editor is going to format it as text, so the breaks will break. Try opening it up in Excel and you'll probably see it more as you're expecting.

**Comment by tonidef** [comment]
I've found opening directly in Excel won't read special characters likes trademarks. I have to import the data and select a file origin for UTF-8. On import, it then reads the carriage returns as new lines. I can't determine a resolution to address both issues.

**Comment by JoshClose** [comment]
What is your goal? It looks like the data is being written correctly based on RFC 4180 (from what I can see). What needs to happen to the data after it's in CSV format?

**Comment by tonidef** [comment]
It needs to be accessed in Excel, then is merged with other data by my user who then imports all the data into cvent...for seminar registrations.

**Comment by JoshClose** [comment]
It should open in Excel fine. You may have to set some options in Excel when opening or importing. You may need to specify a specific encoding too for all I know. Obviously, use the encoding that you used to write the CSV. CsvHelper doesn't do anything with encodings; it just uses the TextWriter you give it.

**Comment by JoshClose** [comment]
I'm not on a computer that I'm able to test anything out unfortunately. If you need some help, you can email me a sample text file, and I can give it a try with Excel tonight some time.

**Comment by tonidef** [comment]
Thanks so much! Sending email now.
