### ISSUE TITLE
Mapping by Alternate Names and GetField

### ISSUE THREAD

**Issue by ChrisMarais** [JoshClose/CsvHelper#1300]
Thank you for a great product.

I have a question when using a class map with Mapping by Alternate Names, how do you determine which field name it matched on, so that you can use the GetField method to get the value?

Code snippet below from my ClassMap

Map(m => m.Address.PostalCode).Name("PostalCode", "AddressPostalCode").ConvertUsing(row =>
                {
                 // I dont know which field name to use here "PostalCode", "AddressPostalCode"
                    string postalCode = row.GetField("PostalCode");
                    if (row.GetField("Country").ToUpper() == "GBR")
                    {
                        UkPostcodeHelper.ReformatAndCorrect(postalCode, out string formattedPostcode);
                        return formattedPostcode;
                    }

                    return postalCode;
                });

Thanks
Chris

**Comment by AltruCoder** [comment]
It would be nice if there was an easier way to do it, but this should work.
```csharp
Map(m => m.Address.PostalCode).Name("PostalCode", "AddressPostalCode").ConvertUsing(row =>
{
    if (!row.TryGetField(typeof(string), "PostalCode", out object postalCode))
    {
        row.TryGetField(typeof(string), "AddressPostalCode", out postalCode);
    }

    if (row.GetField("Country").ToUpper() == "GBR")
    {
        UkPostcodeHelper.ReformatAndCorrect((string)postalCode, out string formattedPostcode);
        return formattedPostcode;
    }

    return (string)postalCode;
});
```

**Comment by ChrisMarais** [comment]
I had done something similar with a for loop and string array testing with the TryGetField.
It felt like I was doing something wrong hence the question.
Thank you for the fast response,
