### ISSUE TITLE
 Map using Index with columns are not fixed 

### ISSUE THREAD

**Issue by trungdang194** [JoshClose/CsvHelper#1302]
Hi all,
I'm struggling with the CSV format that have header name and number of columns is not fixed,
for example 
columnA, columnB, columnC, name_Your_name, name_His_name

also format can be
columnA, columnB, columnC, option1, option2, name_Your_name, name_His_name
The "Your_name" & "His_name" can be: John, Will...
The option1, option2 is optional.

I'm reading the header with Class Map and index compare but cannot solve this.

Map(m => m.option1).Name("option1").Optional();
Map(m => m.name_1).Index(4).Optional();
Because of the name_Your_name column name is not fixed, so I assign Index = 4 but if there are option1, option2 appear before, the index won't be correct.
I want to find the index of columns  name_Your_name, name_His_name, is there any solution about this?
Thank you

**Comment by AltruCoder** [comment]
What does your class look like that you are mapping the headers to?

**Comment by trungdang194** [comment]
I changed to use another way that is using dynamic object instead of using ClassMap, I saw the pattern columns have prefix name_ so I get all columns name_ and use the

foreach (KeyValuePair<string, object> kvp in row)
        {
            //this will get column name and index
        }

Now I can get these columns, thank you
