### ISSUE TITLE
Documentation need for ValidateHeader() with IsOptional field

### ISSUE THREAD

**Issue by SABARISHV06** [JoshClose/CsvHelper#1306]
@JoshClose / @amikulich I am developing with the help of the testcases added by you guys. I don't find ValidateHeader() test cases after adding IsOptional field. Because I'm facing StackoverFlow exception, after validateHeader method. Can you guys help on this?

Reference: https://github.com/JoshClose/CsvHelper/pull/1140

**Comment by JoshClose** [comment]
Can you post a full example that reproduces the stackoverflow exception?

**Comment by SABARISHV06** [comment]
@JoshClose I found the fix, thanks for the concern.
