### ISSUE TITLE
Last/Trailing row is empty, after file is saved

### ISSUE THREAD

**Issue by tad3j** [JoshClose/CsvHelper#132]
I've successfully implemented CsvHelper, thanks for the nice helper! Still I have a problem....its the empty line/row at the end of the file that bothers me. I guess its added because new line is added for each record.

Any suggestions how to save file without empty line at the end of the file?

Thanks!

**Comment by dougadriquei** [comment]
Hi brow,

After breaking my head, I noticed that the blank line really did not exist through this method.

What happened was the tool I was using (NotePad ++), it showed me a blank line wrongly.

Follows the method to check the lines of the files and remove the last line, can be useful for some specific situation.

Att,

private static void RemoveLastLine(string caminho, string nomePasta, string nomeArquivo)
        {
            string[] lines = System.IO.File.ReadAllLines(@caminho + nomePasta + nomeArquivo);
            System.IO.File.WriteAllLines(@caminho + nomePasta + nomeArquivo, lines.Take<string>(lines.Length - 1));
        }

**Comment by jusefb** [comment]
Just to let you know this is still a problem when using `WriteField` to write rows to a CSV file. We had a requirement from a client to construct a CSV from a dynamic list of string based columns (so I could not use `WriteRecords`) but explicitly their system can not accept blank lines. Using `WriteField` requires you to call `NextRecord`:
```csharp                
         for (var i = 0; i < records.Count; i++)
                {
                    var record = records[i];
                    foreach (var recordColumn in record)
                    {
                        csv.WriteField(recordColumn.Value);
                    }

                    csv.NextRecord();
                }
```
 this always adds a blank line at the end. Could not find a good way to prevent this from happening.

**Comment by JoshClose** [comment]
Don't call `NextRecord` if it's the last record.

**Comment by jusefb** [comment]
Thank you for a prompt response, I have tried that. Unfortunatly if I don't call `NextRecord` the row will not be written to the csv (this behaviour seems to match with CsvHelper documentation)

**Comment by JoshClose** [comment]
Oh yeah, sorry. When you detect the last record you should call `csvFlush()` instead of `csv.NextRecord()`. Flush will write it but not put the line ending. NextRecord both writes it and flushes.

**Comment by jhaws** [comment]
I was experiencing the empty rows. In my case I am bringing back 10s of thousands of rows of json and have to append lines to a file because of memory constraints. The empty lines were driving my crazy and fixed with code below. 

                        int rowCounter = 1;
                        foreach (DataRow row in dt.Rows)
                        {
                            for (var i = 0; i < dt.Columns.Count; i++)
                            {
                                csv.WriteField(row[i]);
                            }

                            if (rowCounter < dt.Rows.Count)
                                csv.NextRecord();
                            else
                                csv.Flush();

                            rowCounter++;
                        }

**Comment by rondougsflintfox** [comment]
Hello, I noticed that the issue above happens only when using StreamWriter(new MemoryStream()) with CsvWriter.

But when using actual physical file path (i.e. StreamWriter(filepath)), there is no issue on the last line with null columns.

Are you able to validate my findings?

Thank you.

**Comment by Krisje1973** [comment]
my workaround: memoryStream.GetBuffer().Where(b => b > 0).ToArray()
