### ISSUE TITLE
Last record is not written correctly

### ISSUE THREAD

**Issue by DominiqueFonteyn** [JoshClose/CsvHelper#1333]
Hi, I'm having an issue in which I create a CSV from an IEnumerable and the last record is correctly written. Here is the code. `MyCustomObject` is just a class with autoproperties.

 ```
private Stream WriteToStream(IEnumerable<MyCustomObject> data)
{
       var stream = new MemoryStream();
       var streamWriter = new StreamWriter(stream);
       var csvWriter = new CsvWriter(streamWriter);

       csvWriter.Configuration.Delimiter = ";";
       csvWriter.WriteRecords(data);

       stream.Seek(0, SeekOrigin.Begin);

       return stream;
}
```

When I opened the CSV in Excel I noticed that there was information missing on the last row.
![image](https://user-images.githubusercontent.com/9879997/59838237-e62dbc80-934e-11e9-9a66-120ff80ec6fa.png)

First I thought it was an Excel issue, but when consulting the CSV in notepad, the info just wasn't there. When debugging the IEnumerable the info is there though. So that is not the problem.

Perhaps it's a size issue: the original dataset had over 80.000 records. But then again, I have tested it with smaller sets (3000 records) too. Same problem...

Please help :-)

**Comment by AltruCoder** [comment]
I'm guessing the issue is your `StreamWriter` is not getting flushed.
```csharp
private Stream WriteToStream(IEnumerable<MyCustomObject> data)
{
      var stream = new MemoryStream();
      var streamWriter = new StreamWriter(stream);
      var csvWriter = new CsvWriter(streamWriter);

      csvWriter.Configuration.Delimiter = ";";
      csvWriter.WriteRecords(data);

      streamWriter.Flush();

      stream.Seek(0, SeekOrigin.Begin);

      return stream;
}
```

**Comment by DominiqueFonteyn** [comment]
Yes, that did the trick.

Thanks!
