### ISSUE TITLE
ClassMap InvalidOperationException Message should include message value

### ISSUE THREAD

**Issue by tomwarner13** [JoshClose/CsvHelper#1334]
**Describe the bug**
When giving an invalid expression in a class inheriting from ClassMap, the InvalidOperationException message includes the literal "{expression}" instead of the value of the expression which caused the exception.

**To Reproduce**
Steps to reproduce the behavior (included in new committed test):
1. Create and register a ClassMap with an invalid expression (eg. 'Map(m => m.Method())')
2. You'll see that instead of the invalid expression's value, the literal "{expression}" is printed in the message of the resulting expression

**Expected behavior**
To be able to quickly debug ClassMaps by getting details of failing calls to Map().

**Additional context**
I couldn't figure out how to trigger the second exception message I modified in a test; I believe it may be impossible to ever hit.

**Comment by mudnug** [comment]
While the PR is old, this issue is still present as of today.

**Comment by JoshClose** [comment]
Fixed.
