### ISSUE TITLE
How could I continue writing data to my existed csv

### ISSUE THREAD

**Issue by kevinding0218** [JoshClose/CsvHelper#1336]
Hello, I am using the csvHelper as a logger with my application that I can continue writing information to one of my existed file. However, I found out it would always only log the very last information, all my existed information were wiped out...Is that what CsvHeper supposed to work or is there any option that I need to set up? Here is my code
```
public static void LogIntoCsv(em)
{
            using (var writer = new StreamWriter(fileFullPath))
            {
                using (var csv = new CsvWriter(writer))
                {
                    csv.Configuration.RegisterClassMap<ExceptionModuleMap>();
                    csv.WriteRecord(em);
                }
                writer.Close();
            }
}
LogIntoCsv(em1)
LogIntoCsv(em2)
LogIntoCsv(em3)
// Always that em3 will overwrite em1 and em2 content data...
```

**Comment by AltruCoder** [comment]
You should be able to set up the `StreamWriter` to append text instead of overwriting.
```csharp
using (var writer = new StreamWriter(fileFullPath, append: true))
```

**Comment by kevinding0218** [comment]
That did work and thank you so much!  It'd be much appreciate if these info could be found in any documentation

**Comment by JoshClose** [comment]
That is general .NET I/O documentation, so it will not be added to the CsvHelper docs.
