### ISSUE TITLE
Exception: No parameterless constructor under Unity WebGL build (Bug 1073)

### ISSUE THREAD

**Issue by githubbar** [JoshClose/CsvHelper#1337]
**Describe the bug**
I'm building Unity3D  app. I'm still getting "InvalidOperationException: No public parameterless constructor found" when calling  GetRecords. 

I'm only getting this when compiling to WebGL. Works fine under Unity editor. Any solution for this?
```c#
public class ClassDescription
{
    public ClassDescription() { }

    public string Name { get; set; }
}
using (var csv = new CsvReader(reader))
{
        IEnumerable records = null;
        try
        {
            csv.Configuration.TrimOptions = CsvHelper.Configuration.TrimOptions.Trim;
            csv.Configuration.PrepareHeaderForMatch = (string header, int index) =>header.ToLower().Trim();
            records = csv.GetRecords<ClassDescription>();
        }
        catch (ValidationException e)
        {
                Debug.Log(e);
        }
}


```

**Comment by wiverson** [comment]
This may be related to the code stripping/reflection problems various Unity builds have.  Try turning off Unity code stripping for your build and see if that changes anything...?

https://docs.unity3d.com/Manual/webgl-building.html

Try setting code stripping to disabled to see if that changes anything...

**Comment by JoshClose** [comment]
CsvHelper uses expression trees and compiles code at runtime, which won't work for you. https://forum.unity.com/threads/are-c-expression-trees-or-ilgenerator-allowed-on-ios.489498/

You'll need to manually build your classes.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		var records = new List<Foo>();
		csv.Read();
		csv.ReadHeader();
		while (csv.Read())
		{			
			var record = new Foo
			{
				Id = csv.GetField<int>("Id"),
				Name = csv.GetField<string>("Name")
			};
			records.Add(record);
		}
		
		records.Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

This is what CsvHelper does for you under the hood. This will still use the build in type converters and you can use your own custom ones.

**Comment by JoshClose** [comment]
Follow this issue for a possible fix for this. https://github.com/JoshClose/CsvHelper/issues/1390

**Comment by zephyo** [comment]
Thanks @JoshClose manually building the classes seems to do the trick!
