### ISSUE TITLE
Initialize a map member

### ISSUE THREAD

**Issue by jquintard** [JoshClose/CsvHelper#1342]
Imagine a collection of EF dbSet like this :

```
public class Employee {
   ...
   public string FirstName { get; set; }
   public List<Badge> Badge { get; set; }
}

public class Badge {
   public long CSN { get; set; }
   public int EmployeeId { get; set; }
   public int Type { get; set; }
}
```

This models are used in my SGBB and I want to use it to import data from a CSV file. But this file has a small difference. It give only one badge like this : 

```
FIRSTNAME;CSN;TYPE
Jerome;12345;1
```

I have used a CollectionGenericConverter, to initialize the List<Badge> with a new record.

```
Map(m => m.Firstname).Name("Firstname");
Map(m => m.Badges).Name("CSN").TypeConverter<BadgeConverter>();

...

public class BadgeConverter : CollectionGenericConverter {
    public override object ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData) {
       return new List<Badge> {
           new Badge {
               CSN = Convert.ToInt16(text)
           }
       };
   }
}
```

I have just a problem with the second value, using a second converter reset the list of badges :

`Map(m => m.Badges).Name("Type").TypeConverter<AnotherOneBadgeConverter>();`

And set directly the first item not work :

`Map(m => m.Badges[0].Type).Name("Type");`

How to do that ?

**Comment by AltruCoder** [comment]
Check out my answer to this on [StackOverflow](https://stackoverflow.com/a/56792397/2355006)

**Comment by jquintard** [comment]
Perfect answer !
