### ISSUE TITLE
Index was outside the bounds of the array. When more than 100 K Data.

### ISSUE THREAD

**Issue by 7archers** [JoshClose/CsvHelper#1345]
I am using CsvHelper to convert datatable from csv file. When the csv data is less than 100 K than it is working fine. There is not any problem in to converting to DataTable. But if data is more than 105 K than it throw an error *Index was outside the bounds of the array*.  Is 100 K maximum limit for csv data to convert using CsvHelper or i am missing something. Please help me out in this matter. i have attached a screenshot of my error.

**To Reproduce**
1. Take a Csv file which contain more than 105 K data. 
2. try to convert this data in to data table as i have done. (You can check my screenshot.)
3. See error

**Expected behavior**
I want that if my Csv file contain either 1 Data or 1 million data. It should run perfectly. 

**Screenshots**
![Index was outside the bounds of the array error in csvhelper](https://user-images.githubusercontent.com/48427137/60431268-fe3def80-9c1c-11e9-847c-06b1cd5c6d42.png)

**Comment by JoshClose** [comment]
CsvHelper can use an unlimited size of data. This could be related to issue #1250 which I just fixed and is in release 12.2.1 on nuget. Please give that a try and let me know if you're still having the issue.
