### ISSUE TITLE
CsvHelper 12.1.2 throws an error when using .Net 4.8

### ISSUE THREAD

**Issue by vorien** [JoshClose/CsvHelper#1346]
I'm not sure that this is technically a bug, it may be a feature request...

CsvHelper 12.1.2
System.ValueTuple 4.4.0 and 4.5.0
Visual Studio 2017
.Net 2.8 (Developer)

When I updated a C# project to .Net 2.8, I received the error:

Some NuGet packages were installed using a target framework different from the current target framework and may need to be reinstalled. Visit http://docs.nuget.org/docs/workflows/reinstalling-packages for more information.  Packages affected: System.ValueTuple

From what I've read, .Net 2.7+ don't use System.ValueTuple.

My code compiles, but with a warning:

Found conflicts between different versions of "System.ValueTuple" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.

**Comment by remcoros** [comment]
Related to #1241

**Comment by JoshClose** [comment]
I just released version `12.1.3` that has a separate `net47` build that doesn't use `System.ValueTuple`. Let me know if it's still a problem.
