### ISSUE TITLE
Allow same key while parsing csv

### ISSUE THREAD

**Issue by puneetk207** [JoshClose/CsvHelper#1352]
Allow same key while parsing csv. Tried using `HasHeaderRecord=false`. It works but add header row with field1,field2,........so on. Need to remove this row or any other workaround to do it ?

**Comment by jamesbascle** [comment]
If I understand your question correctly, you can use the "NameIndex"
configuration method in your ClassMap.

**Comment by puneetk207** [comment]
Correct but i am not using any class.
I have dynamic values that's why i am using `var records = csv.GetRecords<dynamic>();`

**Comment by jamesbascle** [comment]
I don't think it's possible in the way you are saying.  The conflict has to
be resolved somehow.

**Comment by JoshClose** [comment]
This feature is in 16.0.0.
