### ISSUE TITLE
How to Retain Date Format after exporting the date value to CSV in CSV Helper

### ISSUE THREAD

**Issue by tharishk** [JoshClose/CsvHelper#1366]
Hello coders,

I have struck on an issue related to DateFormat on exporting to CSV cell.
Example - value in .NET object is **2019-01-25**
after writing the record, the value in CSV file changed to 1/25/2019, I require the value in CSV as 
**2019-01-25**. could you help me
 using (var streamWriter = new StreamWriter(filename))
                using (var csvWriter = new CsvWriter(streamWriter))
                {
                    streamWriter.WriteLine("sep=;"); // for populating each header and value to single //cell
   csvWriter.WriteHeader<Myclass>();
                    csvWriter.NextRecord();
                    csvWriter.WriteRecord(singleobject);
streamWriter.Flush();
}

**Comment by powerzone3000** [comment]
you can use the Format Attribute on your class property, e.g.:
public class MyClass
{
    [Format("yyyy-MM-dd")]
    public DateTime myDate { get; set; }
}
