### ISSUE TITLE
Calling Any() is

### ISSUE THREAD

**Issue by wis3guy** [JoshClose/CsvHelper#1368]
**Describe the bug**
Calling `.Any()` on the `IEnumerable<T>` returned by the `CsvReader.GetRecords<T>()` method, seems to progress the reader's internal row index/pointer. As a result, calling `.Any()` on the enumerable and subsequently calling `.ToArray()` will yield a data set, missing the first record. The behavior is consistent, in that calling `.Any()` *n* times, will remove exactly *n* records from the beginning of the data set.

**To Reproduce**

First run:

```c#
// obtain a stream ...

using (var reader = new StreamReader(stream))
{
    var options = new CsvDataReaderOptions
    {
        Delimiter = "|"
    };

    using (var csvReader = new CsvReader(reader,options))
    {
        Console.WriteLine(csvReader.GetRecords<Record>().ToArray().Length); // will yield n records ...
    }
}
```

... then try:

```c#
// obtain a stream ...

using (var reader = new StreamReader(stream))
{
    var options = new CsvDataReaderOptions
    {
        Delimiter = "|"
    };

    using (var csvReader = new CsvReader(reader,options))
    {
        var data = csvReader.GetRecords<Record>();

        if (data.Any())
            Console.WriteLine(data.ToArray().Length); // will yield n-1 records ...
    }
}
```

**Expected behavior**
A call to `.Any()` does not affect the resulting data.

**Screenshots**
n/a

**Additional context**
Not the same issue, but tighlty related to the implementation of the `CsvReader.ReadRecords<T>()` method is that i cannot call `.ToArray()` more than once on the returned enumerable. The second time it yields 0 records.

My impression is that the `CsvReader.ReadRecords<T>()` is not purely a query operation, but that it mutates (internal) state somehow/somewhere.

**Comment by marcrocny** [comment]
These are the same issue. The difference in outcome is because internally `Any()` just has to check that `MoveNext()` succeeds, whereas `ToArray()` enumerates the entire enumerable.

This would seem to be due to the nature of enumerating from a stream source. The enumeration that `GetRecords()` performs cannot itself reset the underlying stream. Suggestions:

1. If the record-set is empty, there is no loss in pulling the collection. For instance, in your use above:
``` csharp
var length = csvReader.GetRecords<Record>().Length;
if (length > 0)...
```
should suffice.
2. If you are pulling into a local collection, use `ToList()`. It is less expensive.

**Comment by wis3guy** [comment]
@marcrocny Thanks for your reply.

Imho option 1 is not a feasible work-around. I would be calling `GetRecords` twice, potentially doing all teh work twice as well. Perhaps that is not a problem for empty sets, but with full sets it might be expensive. As a consumer of the API i have no way to know, do i? I would even dare to say that, as a consumer, i would not _need_ to know the inner workings of the method. 

Pardon my ignorance, but why would `ToList()` be less expensive than `ToArray()`?

**Comment by JoshClose** [comment]
CsvHelper uses a forward only stream of data. It does not have a LINQ provider included, so when you're using any of the LINQ methods, it's doing it using LINQ to objects. If there isn't a LINQ provider, LINQ may iterate over the records multiple times, which will not work with a forward only stream. If you want to use LINQ on your CSV data, you'll need to pull everything into memory first, then operate on it. `ToList` and `ToArray` both will pull everything into memory.

**Comment by JoshClose** [comment]
Check out the documentation:

https://joshclose.github.io/CsvHelper/getting-started/

> The GetRecords<T> method will return an IEnumerable<T> that will yield records. What this means is that only a single record is returned at a time as you iterate the records. That also means that only a small portion of the file is read into memory. Be careful though. If you do anything that executes a LINQ projection, such as calling .ToList(), the entire file will be read into memory. CsvReader is forward only, so if you want to run any LINQ queries against your data, you'll have to pull the whole file into memory. Just know that is what you're doing.

**Comment by wis3guy** [comment]
@JoshClose Ok, thanks for the clarification
