### ISSUE TITLE
Skip lines that causes error

### ISSUE THREAD

**Issue by centiveo** [JoshClose/CsvHelper#137]
Is it possible to automatically skip rows that causes an error? And write it to a logfile?

For example; if I set the durationfield must be an integer and my csv-file contains a string instead of an integer. How can I handle this, skip that line, and continue with the rest of the csv-file?

**Comment by bborad** [comment]
Hi 

how do you skip the record that has raised BadDataFound exception?

Thanks

**Comment by JoshClose** [comment]
http://joshclose.github.io/CsvHelper/configuration#baddatafound

**Comment by bborad** [comment]
I have that configured but problem is CsvHelper has already read the line and converted it into object when calling GetRecords<Type>(). What I want to do is, because that row is incorrect data, I don't want to read/process that row.

Thanks

**Comment by JoshClose** [comment]
If there is an exception, the record doesn't get set. 

https://github.com/JoshClose/CsvHelper/blob/39736575e27b66ab6648027e3288e02ea1300613/src/CsvHelper/CsvReader.cs#L1041
