### ISSUE TITLE
[Feature Request] Add IAsyncDisposable to CsvWriter

### ISSUE THREAD

**Issue by AdamDotNet** [JoshClose/CsvHelper#1376]
In Asp.Net Core 3.0 ([to RTM on Sept 23, 2019](https://www.dotnetconf.net/)), calling synchronous IO APIs on the HttpResponse stream throws an exception to help warn users of potential performance issue. One area I recently hit is allowing CsvWriter to synchronously dispose the StreamWriter it is wrapping, which in turn wraps the Asp.Net Response stream. Specifically, this message occurs: `InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.` I'd prefer to be fully on async IO instead of allowing sync IO. I didn't even realize I was doing sync IO!

Demo code showing how the exception might occur can be found [here](https://github.com/AdamDotNet/AspNetCoreSyncWriteDemo/blob/528f9f611e7326437447fb19e1f713a926e8ca99/src/AspNetCoreSyncWriteDemo/Startup.cs#L39).

**Proposal**
In .Net Core 3.0, and .Net Standard 2.1, `TextWriter` now implements the new [IAsyncDisposable](https://github.com/dotnet/corefx/blob/7216dfaeeab82fc3c2fc65f62b3f28346f76b532/src/Common/src/CoreLib/System/IAsyncDisposable.cs) interface. I propose that CsvHelper add the `netstandard2.1` TFM to its csproj, and the following types add IAsyncDisposable conditionally to the `netstandard2.1` target:

 - CsvSerializer
 - CsvWriter
 - ISerializer
 - IWriter
 - WritingContext

It's necessary to `#if NETSTANDARD2_1` because even though there's a [NuGet package for the interface](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/1.0.0-preview8.19405.3), you need BCL support for TextWriter itself to implement IAsyncDisposable. Therefore, this feature can only benefit .Net Core 3.0 and any other framework in the future that implements .Net Standard 2.1. For every other TFM, nothing changes.

**Alternative**
A workaround includes instantiating CsvWriter with `leaveOpen: true` and calling `await using new StreamWriter ...` or `await streamWriter.DisposeAsync()` yourself, manually keeping track of disposing both the CsvWriter and the TextWriter passed to it. This solution isn't ideal, but it's doable.

**Branch with proposed changes**
I believe I've implemented this correctly at [/AdamDotNet/CsvHelper](https://github.com/AdamDotNet/CsvHelper/tree/feature/async-dispose). Perhaps there's more testing or more consideration you would be able to point out? Otherwise, I'm happy to submit a pull request. All unit tests passed on my machine.

**Addtional Details**
.Net Core 3.0, .Net Standard 2.1, and Visual Studio 2019 16.3 are not out yet, but will be in just a couple of weeks from opening this issue. The branch I made used previews of the SDK and Visual Studio. However, the SDK is in "go live" or "RC" mode and it could be nice to just be ready for the full release.

**Comment by daniel-wolf** [comment]
I've also hit this issue with .net core 3.0.  +1 for implementing IAsyncDisposable.  I was able to create a workaround for now that I thought worth sharing.

Implement a derived class like such:
` class AsyncCsvWriter : CsvWriter, IAsyncDisposable
        {
            private readonly TextWriter writer;

            public AsyncCsvWriter(TextWriter writer) : base(writer)
            {
                this.writer = writer;
            }

            public async ValueTask DisposeAsync()
            {
                await writer.FlushAsync();
                base.Dispose();
            }
        }`

Example usage:
`public async Task WriteToCsvAsync(
            IEnumerable<Record> records, Stream stream, CancellationToken cancellationToken)
        {
            await using (StreamWriter writer = new StreamWriter(stream))
            await using (AsyncCsvWriter csvWriter = new AsyncCsvWriter(writer))
            {
                csvWriter.WriteHeader<AmiRecord>();
                await csvWriter.NextRecordAsync();

                foreach (var record in records ?? Enumerable.Empty<Record>())
                {
                    if (cancellationToken.IsCancellationRequested)
                    {
                        return;
                    }

                    csvWriter.WriteRecord(record);
                    await csvWriter.NextRecordAsync();
                }
            }
        }`

**Comment by JoshClose** [comment]
In release 14.0.0 on NuGet.
