### ISSUE TITLE
Option to Ignore double quotes when a field does not start with quote

### ISSUE THREAD

**Issue by sameerkattel** [JoshClose/CsvHelper#1378]
> 4647101,TOYS "should ignore quotes","should not ignore, quotes"

I have this csv (not sure if this meets csv specification) where there are double quotes in certain field that needs to be ignored but elsewhere it is a quote value.
Thank you for the great library!

**Comment by JoshClose** [comment]
You want to do it only on specific fields? This isn't possible and something that I don't think should be in the library. It's really edge case for a non-compliant CSV file.
