### ISSUE TITLE
GetRecords (or retrieving info) jumping lines

### ISSUE THREAD

**Issue by donaldnp** [JoshClose/CsvHelper#1380]
**Describe the bug**
I'm using this for the first time. When I first used GetRecords, and did some spot checks, all the right information appeared to be in the right place (but that was just spot checks). I then wrote some extensive code to use the results, and was then finding incorrect information being returned after the first retrieval. basically it looked to be randomly skipping to the next row of information.

To explain further, the way I set up my ImportedCSV class, was to have F1 for field 1, F2 for field 2, etc., so if I do Records.ElementAt(0),F1, I should get the 1st field from the top row, and I do, but then it goes awry. Records.ElementAt(0),F2 gives me the 2nd field from the SECOND row, Records.ElementAt(0),F3 gives me the 3rd field from the third row, etc., it was traversing the data diagonally.

So, try it with row 2, and I got row 2 F1, row 2 F2, row 3 F3, row 3 F4, so not jumping a line every time, but still jumped.

Tried just getting F1 4 times in a row, so I should get the same result 4 times, but still jumps rows.

Thinking there might be a timing issue, I put 5 second delays between each one - still jumping.

I'm now out of ideas to try. I'm not sure if the issue is the records aren't being created properly in the first place, or if I'm just not getting the right ones retrieved,and I'm not sure if there's a way for me to check that? (GetRecords does the whole operation in one go, so there's no way for me to insert debugs between each line that I know of).

**To Reproduce**
1. Create a class like the following...
```
class ImportedCSV {
    [Index(0)]
    public string F1 {get;set;}
    [Index(1)]
    public string F2 {get;set;}
    [Index(2)]
    public string F3 {get;set;}
```
etc.
2. Write code like the following...
```
using (StreamReader reader=new StreamReader(myfile/stream))
using (CsvReader csv=new CsvReader(reader)) {
    csv.Configuration.HasHeaderRecord=false;
    Records=csv.GetRecords<ImportedCSV>();
    int row=0;
debug("Heading for F1 is ",Records.ElementAt(row).F1);
debug("Heading for F2 is ",Records.ElementAt(row).F2);
debug("Heading for F3 is ",Records.ElementAt(row).F3);
debug("Heading for F4 is ",Records.ElementAt(row).F4);
```

note: in writing this, I've realised that I'm streaming from a Dropbox file, so I'm not sure if maybe Dropbox is failing to deliver the file appropriately to begin with (first time retrieving a Dropbox file via a stream as well - I normally just retrieve the whole thing all at once).

**Expected behavior**
As per earlier description, should see the fields from the same row, but instead I'm getting fields from different rows.

**Screenshots**
N/A

**Additional context**
As mentioned, I'm getting the file as a Dropbox stream originally, which may be a confounding factor. The relevant code is...

```
public async Task<Stream> StreamFile(string file) {
   try {
        using (DropboxClient DxClient=new DropboxClient(AccessToken)) {
            var response=await DxClient.Files.DownloadAsync(file);
            var content=response?.GetContentAsStreamAsync();
            return content?.Result;
            }
        }
    }

```
Hope you have some ideas on this, as I'm out of them now.
thanks,
   Donald.

**Comment by donaldnp** [comment]
Actually, I just realised "Tried just getting F1 4 times in a row, so I should get the same result 4 times, but still jumps rows" proves that the issues is in the retrieval, not the creation (so I'm glad I tried that :-) ). Not sure how it's not giving me the same info back 4 times in a row...? :-/

**Comment by AltruCoder** [comment]
CsvHelper does a lazy load. Try getting the records to list first before iterating over them.
```csharp
Records=csv.GetRecords<ImportedCSV>().ToList();
```

**Comment by donaldnp** [comment]
Yes! That fixed it! Thank you so much @AltruCoder :-)
