### ISSUE TITLE
Computed Column when writing?

### ISSUE THREAD

**Issue by McPhale** [JoshClose/CsvHelper#1384]
Is it possible to conditionally use differing input column values for a single output column when writing?

Eg, if column X's value is null for the current row, fall back to column Y. If that's null as well, fall back to a default value. I figure this is doable with a TypeConverter but I'm having trouble figuring out how to get to the other fields in the current row.

**Comment by JoshClose** [comment]
The easiest way would be to create a property on your class that does the computing. If you can't (or don't want to) do that, you can map without a field, but you'll need to cast the type since it doesn't have one.

```cs
void Main()
{
	var records = new List<Foo>
	{
		new Foo { Id = 1, Name = "one" },
		new Foo { Id = 2, Name = "two" },
	};
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		csv.Configuration.RegisterClassMap<FooMap>();
		csv.WriteRecords(records);
		writer.ToString().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map().Name("Computed").ConvertUsing((object obj) => 
		{
			var foo = (Foo)obj;
			return $"{foo.Id} {foo.Name}";
		});
	}
}
```

If you'd rather do a full type converter, let me know.

**Comment by McPhale** [comment]
I ended up solving this a different way due to some changes in project requirements, but this looks like a good solution to me; next time I need to do this I'll give it a shot.

Thanks for your help! And apologies for letting the issue sit open for so long.

**Comment by JoshClose** [comment]
Glad you found something that works! And no worries.
