### ISSUE TITLE
Unescaped quote at end of quoted string

### ISSUE THREAD

**Issue by svickers** [JoshClose/CsvHelper#1385]
**Describe the bug**
I am trying to parse a csv file that has unescaped double quotes within some strings.  Normally this works fine but if the quote is right at the end of the column value it fails with a MissingFieldException.

**To Reproduce**
CSV:
```
Id,Name,Price
"123","Widget 1" ","34.56"
"456","Widget 5"","42.00"
"789","13" Widget","10.00"
```
```cs
        static void Main(string[] args)
        {
            using (var reader = new StreamReader("foo.csv"))
            using (var csv = new CsvReader(reader))
            {
                csv.Configuration.RegisterClassMap<ItemMap>();
                csv.Configuration.BadDataFound = null;
                var records = csv.GetRecords<Item>();
                foreach(var r in records)
                {
                    Console.WriteLine($"ID: {r.Id} Name: {r.Name} Price: {r.Price}");
                }
            }
        }
    public class Item
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Decimal Price { get; set; }
    }
    public class ItemMap : ClassMap<Item>
    {
        public ItemMap()
        {
            Map(m => m.Id).Name("Id");
            Map(m => m.Name).Name("Name");
            Map(m => m.Price).Name("Price");
        }
    }
```

Is there anything that can be done in these cases?

**Comment by W357** [comment]
Did you find a solution?

**Comment by JoshClose** [comment]
This is an invalid file. You could try ignoring the quotes, and then processing them yourself.

```cs
csv.Configuration.IgnoreQuotes = true;
```

If you have a `,` in any of your fields, you're going to run into issues.

You could also try ignoring the missing field in your current example.

```cs
csv.Configuration.MissingFieldFound = null;
```

**Comment by superrnovae** [comment]
Sorry for necrobumping this, but I’ve the same issue, and I haven’t found a solution. 

I have a quoted field that contains unescaped quotes inside of it. 

I’ve tried setting different escape modes, Escape and NoEscape result in headers not being found.

**Comment by JoshClose** [comment]
@superrnovae You have an invalid file. You'll need to find out what rules the system that created it are using so you can work around them.
