### ISSUE TITLE
Getting headers in a different row and colunm "trying read the header Position which is on row 8 and column 11"

### ISSUE THREAD

**Issue by therollingbird** [JoshClose/CsvHelper#1386]
![highlighted row i am trying to read](https://user-images.githubusercontent.com/35991749/65601897-513dfd80-dfe6-11e9-99c2-01763da1b88c.PNG)

[csvdata.zip](https://github.com/JoshClose/CsvHelper/files/3652449/csvdata.zip)

Hi i am trying to read a header in a different row and column i have tried a few things but nothing has worked see the code below and the data as well, i am trying to read the header Position which is on row 8 and column 11

```cs
 using (TextReader reader = new StreamReader(csvfile.csv))
            {
                using (var csvReader = new CsvReader(reader))
                {
                    csvReader.Configuration.HeaderValidated = null;
                    csvReader.Configuration.MissingFieldFound = null;

                    ////csv.Configuration.ShouldSkipRecord = row => row[0].StartsWith("Position") || row.All(string.IsNullOrWhiteSpace);
                    
                    while (csvReader.Read())
                    {
                        if (csvReader.Context.Record[0].StartsWith("Position"))
                        {
                            csvReader.Read();
                            csvReader.ReadHeader();

                            break;
                        }
                    }
                    // Remove whitespace
                    csvReader.Configuration.PrepareHeaderForMatch = (header, index) => header.Replace(" ", string.Empty);
                   // var records1 = csvReader.GetRecords<dynamic>();
                    var records = csvReader.GetRecords<players>();
                    playersToselect.AddRange(records.ToList());
                } 
                
            }
```

**Comment by JoshClose** [comment]
Does the entire file  always start that many spots in?

**Comment by therollingbird** [comment]
different sports start with different sports in, NFL is 9 spots in before position column, NBA is 8, MBL is 10. i think i have figured out the first half of the solution. so the solution goes through each row to see if there any rows that contain only 1 element and then the next row is the one with the second headings on element 11. but then if i put an extra row with empty space it breaks and i am thinking instead of  if (csvReader.Context.Record[0].ToLowerInvariant().StartsWith("")) i should do 
 if (csvReader.Context.Record[0].ToLowerInvariant().Contains("position")) but then the first record after the header is being skipped and gets the second record as the first. See current code that working below 
 csvReader.Configuration.HeaderValidated = null;
                    csvReader.Configuration.MissingFieldFound = null;
                    csvReader.Configuration.PrepareHeaderForMatch = (header, index) => header.Replace(" ", string.Empty);
                    csvReader.Configuration.IgnoreBlankLines = true;
                    // Skip until empty space with no rows is found.
while (csvReader.Read())
                    {
                        // get the space where record  = 1  
                        if (csvReader.Context.Record.Count() == 1)
                        {
                            // after getting the space, skip that record and then read and also get the mapped headers for players and salaries
                            if (csvReader.Context.Record[0].ToLowerInvariant().StartsWith(""))
                            {
                                csvReader.Read();
                                csvReader.ReadHeader();
                                var records = csvReader.GetRecords<dynamic>();
                                break;
                            }
                        }
}

**Comment by therollingbird** [comment]
I got it to work hopefully this might help someone else so i just needed to read the header first before calling read(). so this will find any header no matter which column and row the header starts 

 while (csvReader.Read())
                    {

                        // after ettingthe space, skip that record and then read and also get the mapped headers for players and salaries
                        if (csvReader.Context.Record.Where(x => x.ToLowerInvariant().Contains("position")).ToList().Count > 0)
                        {

                            csvReader.ReadHeader();
                            csvReader.Read();

                            var records = csvReader.GetRecords<players>();
                           
                            break;
                        }
                    }
