### ISSUE TITLE
RawRecord may have incomplete record on BadDataFound

### ISSUE THREAD

**Issue by MichaelMcKechnie** [JoshClose/CsvHelper#1387]
I expected that when a BadDataFound event occurs, the parser's RawRecord property would contain the raw csv record that failed. Instead, RawRecord appears to contain the text of the csv record up to the point where the parse error occurred. I'm using version 12.1.2.

Unit test:

        public class Test
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Status { get; set; }
        }

        [Test]
        public void CsvReaderBadRecordTest()
        {
            // arrange
            var testCsv = "Id,Name,Status\n" +
                          "1,\"Jon\"hn\"\",\"Doe\"\n" +
                          "2,\"Jane\",\"Doe\"";
            var expectedGood = new List<Test>()
            {
                new Test
                {
                    Id = 2, Name = "Jane", Status = "Doe"
                }
            };
            var expectedBad = new List<string>()
            {
                "1,\"Jon\"hn\"\",\"Doe\""
            };
            using (var stream = new MemoryStream())
            using (var writer = new StreamWriter(stream))
            using (var reader = new StreamReader(stream))
            using (var csv = new CsvReader(reader))
            {
                writer.Write(testCsv);
                writer.Flush();
                stream.Position = 0;

                var good = new List<Test>();
                var bad = new List<string>();
                var isRecordBad = false;
                csv.Configuration.BadDataFound = context =>
                {
                    isRecordBad = true;
                    bad.Add(context.RawRecord);
                };

                // act
                while (csv.Read())
                {
                    var record = csv.GetRecord<Test>();
                    if (!isRecordBad)
                    {
                        good.Add(record);
                    }

                    isRecordBad = false;
                }

                // assert
                good.Should().BeEquivalentTo(expectedGood);
                bad.Should().BeEquivalentTo(expectedBad);
            }
        }

**Comment by mudnug** [comment]
Currently, the behavior is by design; The context handed to BadDataFound contains the the text of the CSV row up to the point where the parse error occurred (as mentioned).

To get the behavior you're looking for you would want to read the RawRecord after the row has been entirely read. It would look like this, using your example:

```
                csv.Configuration.BadDataFound = context =>
                {
                    isRecordBad = true;
                    //bad.Add(context.RawRecord);
                };

                // act
                while (csv.Read())
                {
                    var record = csv.GetRecord<Test>();
                    if (!isRecordBad)
                    {
                        good.Add(record);
                    }
                    else
                    {
                        // NOTE: the RawRecord will contain the entire CSV row at this point, including /n
                        bad.Add(csv.Context.RawRecord);
                    }

                    isRecordBad = false;
                }
```

@JoshClose Should the XML documentation on BadDataFound be updated to explain `context` more or should this behavior be changed?

**Comment by MichaelMcKechnie** [comment]
Thanks, I can work with that. My expectation was based on the property name 'RawRecord' as I didn't understand that it gets filled in gradually rather than at the beginning of the row parse.

**Comment by JoshClose** [comment]
The raw data can't fill after bad data has been found because you really don't know where the end of that field is anymore.
