### ISSUE TITLE
How to write each row of a txt file in a single row of a csv file using python

### ISSUE THREAD

**Issue by SamiraSadat** [JoshClose/CsvHelper#1389]
Hi.
I have a text file in which each title has written in a separate row, like this:
**Actions
PullRequest
Issues**

I want to write each row of the TXT file to the first row of a CSV file, but it starts from B1 Cell. Like this:
![image](https://user-images.githubusercontent.com/45191491/66471017-84c56100-ea97-11e9-9ec6-2969e5182822.png)

Then, From the Second row, write a name, for example, Sara. Then writes some numbers which come from a numpy array.

like This:

![image](https://user-images.githubusercontent.com/45191491/66470819-32844000-ea97-11e9-826c-23660f14da03.png)

I've tried a lot to implement it but couldn't. Anyone can help me?
I'm using python.

**Comment by jamesbascle** [comment]
This is a C# library.  You should probably just use a CSV parser in your
language and process each line by itself using a custom dataset.  Past
that, this is not the appropriate forum for such a task, IMO.

**Comment by JoshClose** [comment]
If you're using something like IronPython running on top of .NET, I'll open this again.
