### ISSUE TITLE
How can I delete rows or edit rows with CSVHELPER ?

### ISSUE THREAD

**Issue by canbolat-oguzhan** [JoshClose/CsvHelper#1397]
Hello,

My question is said in the tittle. It's simply, i'm working with C# WPF, i'm putting all my csv data in a DataGrid, and the user can change/edit the DataGrid row and when he click on the Save button, I want to delete the row who he changed for remplace it by the new one or just edit the row.

Thanks.

**Comment by JoshClose** [comment]
CsvHelper is forward only, so you'll need to read through the existing file and write a new one.
