### ISSUE TITLE
Option to use default value when field can't be converted

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#1404]
Can this be done without using a `try/catch`? A `try/catch` on every field will slow things down a lot.

**Comment by JoshClose** [comment]
Can this be done without using a `try/catch`? A `try/catch` on every field will slow things down a lot.

**Comment by cap7ainjack** [comment]
Hope this will be resolved soon!

**Comment by JoshClose** [comment]
This is in 27.0.0 and will release soon.

**Comment by JoshClose** [comment]
This needs to be enabled when setting the default value.

```cs
Map(m => m.Property).Default(1, useOnConversionFailure: true);
```
