### ISSUE TITLE
Make line ending configurable

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#1408]
Make the line ending configurable but default it to `\r\n`. Only allow CRLF, CR, and LF, maybe by using an enum.

**Comment by StefanBertels** [comment]
Sounds great. I personally don't have a use case -- compare [my comment here](https://github.com/JoshClose/CsvHelper/commit/d0e1bf518bb022c0b310c87bc686a23ed2994edf#commitcomment-35813256). 

Just two cents:

Maybe this should be somewhat symmetric with reading (at least for custom newline options). Maybe just a bool switch to allow TextWriter.Newline to be used (default being false == fixed CRLF).

Probably the default should be (like now when using e.g. StreamReader, I guess): be tolerant when reading (allow CRLF and CR) and be strict when writing (CRLF). Not sure how whether the other mode should just use the TextReader/TextWriter logic.

**Comment by JoshClose** [comment]
I'm also thinking about possibly allowing any arbitrary string to be used, like the delimiter does. People have been wanting that for a while.

**Comment by jsytniak** [comment]
In cases where line feed can appear in the data values... I have to ingest files where the column & line endings are some chosen hex values char(1)/char(2) for instance. I cannot make use of CsvHelper in those cases.

**Comment by JoshClose** [comment]
Good to know. Any field that contains a quote, delimiter, or line ending should be wrapped in quotes so you don't run into an issue. I know data that your don't write yourself doesn't always come nice and neat like that though.

**Comment by elthombre** [comment]
I wish there was a line terminating method in the CsvWriter. I see it in the Serializer but not the Writer. When I try to add "\r\n", it's putting quotes around the field and onto the next line. For example:

writer.WriteField(SomeConstantValue + "\r\n");

then it shows up like:

"145678
"

if I leave the line feed out, the data just all runs together, as expected, but without any quotes.

**Comment by JoshClose** [comment]
`writer.NextRecord();` will write the line ending. If you're writing it as part of the field, it gets escaped as field content.

**Comment by JoshClose** [comment]
This will be in 13.0.0 on NuGet.
