### ISSUE TITLE
Double values written incorrectly

### ISSUE THREAD

**Issue by sid-6581** [JoshClose/CsvHelper#1409]
In version 12.2.0, doubles are written incorrectly. E.g. `52452.21` is written as `52452.209999999999`. In 12.1.3 it was written correctly as `52452.21`.

**Comment by JoshClose** [comment]
They are now written in a format that can be read back in properly. It's a round-trip format.

This parse fails:

```cs
double.Parse(double.MaxValue.ToString());
```

Using a round trip format will not fail.

```cs
double.Parse(double.MaxValue.ToString("G17"));
```

You can override this if you want to old behavior by specifying the format.

**Comment by JoshClose** [comment]
Also, it looks like .NET Core 3.0 uses this format by default, which should have always been the case.

**Comment by sid-6581** [comment]
I understand the reasoning, but in my case I don't care about round trip correctness, but I do care about readability and consistency, since my files will be read and used by humans and compared to other files. Is there an easy way to globally set the format back to what it was in the previous version?

**Comment by sid-6581** [comment]
I understand the reasoning, but in my case I don't care about round trip correctness, but I do care about readability and consistency, since my files will be read and used by humans and compared to other files. Is there an easy way to globally set the format back to what it was in the previous version?

**Comment by JoshClose** [comment]
You can set the options for all doubles. If you set  blank format, that will be used instead of `G17`.

```cs
csv.Configuration.TypeConverterOptionsCache.AddOptions<double>(new TypeConverterOptions { Formats = new string[] { "" } });
```
