### ISSUE TITLE
After calling IEnumerable.Count() on the records, the records data structure will be emptied

### ISSUE THREAD

**Issue by zephyrprime** [JoshClose/CsvHelper#1410]
```cs
static void Main(string[] args)
        {
            var fileStream = File.OpenText("ab.txt");
            using (var csv = new CsvReader(fileStream))
            {
                var records = csv.GetRecords<ab>();

                Console.WriteLine("Number of lines read: {0}", records.Count());
                Console.WriteLine("Number of lines read: {0}", records.Count());
}
}
```

The first time you call Count(), it will produce the correct value.  The second time you call it, it will produce 0.  The records data structure will be empty.  It seems like the records data structure is some sort of linked list that can only be read once?  Does it lack the ability to rewind?  Calling Count() should not produce side effects.  Maybe reading through the records will also cause the same problem but it shouldn't.  It should be possible to read through the records multiple times.  I will convert to a list to get around this problem but it shouldn't be necessary to do that.

**Comment by JoshClose** [comment]
This behavior is explained in the getting started documentation. https://joshclose.github.io/CsvHelper/getting-started

Running LINQ operations on an `IEnumerable` would cause the data to be scanned multiple times. For this not to happen, an LINQ provider for CsvHelper would need to be created and the files would need to be scanned so metadata could be built up so a query could be ran against it. That doesn't make sense in most CSV scenarios. If you want to do that and have enough memory, you can `ToList` the data and run queries against that. The entire file would be pulled into memory though.

You could read through the file multiple times though. In general,  CsvHelper should be fast enough to make multiple passes, especially if that data isn't being converted into an object on every pass.
