### ISSUE TITLE
not able to inject into mapper; InvalidOperationException: No public parameterless constructor found.

### ISSUE THREAD

**Issue by ElectNewt** [JoshClose/CsvHelper#1411]
I am trying to implement localization into my CSV, for that reason I wanted to inject into a mapper class a localization object:

```
public sealed class ValuesMap : ClassMap<ValuesResult>
{
    public ValuesMap(IStringLocalizer<values_localization> values)
    {
        AutoMap();
       Map(m => m.val1).Ignore();
    }
}

```
I also tried injecting only `values_localization` (just the class) and it didn't work. 

I'm getting the following error:
InvalidOperationException: No public parameterless constructor found
CsvHelper.ReflectionHelper.CreateInstanceDelegate(Type type, object[] args)
CsvHelper.ReflectionHelper.CreateInstanceWithoutContractResolver(Type type, object[] args)
CsvHelper.ReflectionHelper.CreateInstance&lt;T&gt;(object[] args)
CsvHelper.Configuration.Configuration.RegisterClassMap&lt;TMap&gt;()

I am using the version 12.1.2

**Comment by ElectNewt** [comment]
I did a workAround using: 

```
ValuesMap valuesMap = new ValuesMap(localizer);
csv.Configuration.RegisterClassMap(valuesMap);
```

instead of 
`csv.Configuration.RegisterClassMap<ValuesMap>();`


the only "issue" with this is that the DependencyInjection configuration looks a little bit longer (and uglier) but works perfectly.

**Comment by JoshClose** [comment]
That's the recommended way if you want to pass values into the constructor.
