### ISSUE TITLE
Unable to read CSV from byte array

### ISSUE THREAD

**Issue by kazo0** [JoshClose/CsvHelper#1412]
**Describe the bug**
Given a byte[] representing a .csv file, a null ref exception is thrown when attempting to read the file using `GetRecords`.

**To Reproduce**
```
List<ComponentRecord> componentRecords;
using (var ms = new MemoryStream(request.FileData))
{
	ms.Seek(0, SeekOrigin.Begin);
	using (var reader = new StreamReader(ms))
	{
		using (var csv = new CsvReader(reader))
		{
			componentRecords = csv.GetRecords<ComponentRecord>();
		}
	}
}
```

**Expected behavior**
Data is parsed properly

**Additional context**
`request.FileData` is a byte array that is confirmed to be populated

**Comment by kazo0** [comment]
Found this issue, I had to move the line `ms.Seek(0, SeekOrigin.Begin);` inside the using block: `using (var csv = new CsvReader(reader))` so it now looks like this:

```
using (var ms = new MemoryStream(request.FileData))
{
	using (var reader = new StreamReader(ms, true))
	{
		using (var csv = new CsvReader(reader))
		{
			ms.Seek(0, SeekOrigin.Begin);
			componentRecords = csv.GetRecords<ComponentRecord>().ToList();
		}
	}
}
```

**Comment by kazo0** [comment]
That's what I thought but for some reason I get a nullref from within CsvReader if I do that.

**Comment by JoshClose** [comment]
Strange. Whatever works I guess. :)
