### ISSUE TITLE
Ecnlosure gets set for string with traling/leading/surrounding whitespace

### ISSUE THREAD

**Issue by TheReal-BiffBoff** [JoshClose/CsvHelper#1413]
When using the TrimOptions.None with a string surrounded/trailing/leading by whitespace, the whitespace will not get trimmed as expected, but the string will be surrounded by enclosure when writing the csv file.

Is this an expected behaviour?

**Comment by JoshClose** [comment]
Yes. The default criteria for a field being quoted is:
1. Contains a quote
1. Starts with a space
1. Ends with a space
1. Contains any chars that require quotes (`\r` and `\n` by default)
1. Contains the delimiter

**Comment by TheReal-BiffBoff** [comment]
Thank you for the fast response!

**Comment by JoshClose** [comment]
You can change it to behave however you like though.

The default is
```cs
csv.Configuration.ShouldQuote = ConfigurationFunctions.ShouldQuote;
```

which is

```cs
public static bool ShouldQuote(string field, WritingContext context)
{
	var shouldQuote = !string.IsNullOrEmpty(field) &&
	(
		field.Contains(context.WriterConfiguration.QuoteString) // Contains quote
		|| field[0] == ' ' // Starts with a space
		|| field[field.Length - 1] == ' ' // Ends with a space
		|| field.IndexOfAny(quoteChars) > -1 // Contains chars that require quotes
		|| (context.WriterConfiguration.Delimiter.Length > 0 && field.Contains(context.WriterConfiguration.Delimiter)) // Contains delimiter
	);

	return shouldQuote;
}
```

You can copy that function and remove the spaces part.
