### ISSUE TITLE
NewLine now always uses Windows value instead of being based on OS

### ISSUE THREAD

**Issue by ajensen11** [JoshClose/CsvHelper#1415]
**Describe the bug**
After upgrading from `12.1.2` to `12.2.1` I noticed that the new line values were no longer based on the OS.
When the code is ran in VS on my local windows box the new line value is `\r\n`. And in the old version, when ran in a Linux docker image the new line value is `\n`.

But after upgrading, regardless of where the code is ran, Windows or Linux, the new line value is always the windows value: `\r\n`.

**Expected**
I expect the new line value to be based on the OS.

**Comment by JoshClose** [comment]
[RFC 4180](https://tools.ietf.org/html/rfc4180#page-2) states the format is `\r\n` so it was changed to always comply when writing. 

I'm possibly thinking of making the line ending configurable, but there is significant work that needs to be done to the parser for that to happen.

**Comment by JoshClose** [comment]
I just looked into it and having a configurable line ending would slow down parsing quite a bit. Right now it looks for `\r`, `\n`, or `\r\n`. Adding a configurable string on top of that is too much.

I think what I can do though, is make it configurable for writing, probably with an enum.

```cs
public enum LineEnding
{
	CRLF = 0,
	CR = 1,
	LF = 2,
	ListSeparator = 3
}
```

**Comment by ajensen11** [comment]
I briefly look at your code, and didn't test this, but could you add a `LineDelimiter` property to ISerializerConfiguration? The default might be able to be set to `Environment.NewLine`.
And then this value would be used within CsvSerializer's `WriteLine` and `WriteLineAsync` method?
e.g. 
from: 
`context.Writer.Write("\r\n");` 
to
`context.Writer.Write(Configuration.LineDelimiter);`

**Comment by JoshClose** [comment]
`ListSeparator` should read `NewLine`, as in `Environment.NewLine`

**Comment by JoshClose** [comment]
This is more appropriate.

```cs
public enum NewLine
{
	CRLF = 0,
	CR = 1,
	LF = 2,
	Environment= 3
}
```

**Comment by JoshClose** [comment]
This will be in 13.0.0 on NuGet.

**Comment by KN4CK3R** [comment]
Can't you just use the `WriteLine` method of the `TextWriter`? The `TextWriter` has a [`NewLine` property](https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter.newline?view=netframework-4.8) which allows to configure the line ending. CsvHelper should not care about the line ending but just use the configured `TextWriter` it got from the user.

**Comment by JoshClose** [comment]
Yes but people have been asking for it to be configurable.

**Comment by gabrieljoelc** [comment]
This might be a good candidate to add to the documentation for writing.

**Comment by JoshClose** [comment]
Done. https://joshclose.github.io/CsvHelper/getting-started/
