### ISSUE TITLE
Include license identifier in the NuGet package

### ISSUE THREAD

**Issue by reduckted** [JoshClose/CsvHelper#1423]
**Is your feature request related to a problem? Please describe.**
For automated tools that gather the license of NuGet packages, it's really handy for the license to be specified in the NuGet package (specifically in the `.nuspec` file).

**Describe the solution you'd like**
Include the [license identifier](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) in the NuGet package. I think it would require this in the project file (though I haven't tried this):

```xml
<PropertyGroup>
    <PackageLicenseExpression>Apache-2.0 OR MS-PL</PackageLicenseExpression>
</PropertyGroup>
```

**Describe alternatives you've considered**
N/A

**Additional context**
Some links to documentation:
* https://docs.microsoft.com/en-us/nuget/reference/nuspec#license
* https://github.com/NuGet/Home/issues/4628
* https://github.com/NuGet/Announcements/issues/32
* https://github.com/NuGet/Announcements/issues/32

**Comment by reduckted** [comment]
Heh, seems like this was added as a comment last year but at some point was removed. 

https://github.com/JoshClose/CsvHelper/blob/79211dc5031e331a2c9b8cda7665807f5c378363/src/CsvHelper/CsvHelper.csproj#L30-L32

**Comment by JoshClose** [comment]
Thanks. I'll add it back in. It got removed due to some build stuff, but it needs to go back in. I'm missing the logo and probably some other stuff in there too.

**Comment by JoshClose** [comment]
Fixed. https://www.nuget.org/packages/CsvHelper/12.2.2
