### ISSUE TITLE
Add XML documentation to NuGet package

### ISSUE THREAD

**Issue by julealgon** [JoshClose/CsvHelper#1424]
Just downloaded the latest version (`12.2.1`) and immediately noticed the lack of documentation in the library. This makes it incredibly difficult to understand some of the concepts directly via intellisense, and forces people to hunt for documentation elsewhere.

Has the team discussed adding proper XML documentation to the DLL?

I'm honestly a bit surprised such a widely popular library has zero XML documentation shipped with it.

**Comment by JoshClose** [comment]
If you look at the source code, every non-private method has xml documentation. I see when downloading the package that `CsvHelper.xml` is missing though. I'll figure out what's going on and make sure it's being generated in the publish again.

**Comment by JoshClose** [comment]
Fixed. https://www.nuget.org/packages/CsvHelper/12.2.2

**Comment by julealgon** [comment]
Thanks for the quick one @JoshClose , much appreciated. Updating package right now.
