### ISSUE TITLE
Link from NuGet gallery to documentation / github

### ISSUE THREAD

**Issue by DanLatimer** [JoshClose/CsvHelper#1425]
There doesn't appear to be any way to find the documentation from the official nuget page. From googling I did find your awesome webpage but you might want to update your nuget listing to include a link to that webpage as well as a link to this github page.

https://www.nuget.org/packages/CsvHelper/12.2.1

**Comment by JoshClose** [comment]
Fixed. https://www.nuget.org/packages/CsvHelper/12.2.2

**Comment by DanLatimer** [comment]
Thanks!
