### ISSUE TITLE
Documentation comments in nuget library

### ISSUE THREAD

**Issue by AlessandroDalMas** [JoshClose/CsvHelper#1428]
Is it possible to have the code documentation released together with the nuget package?
Currently when I need to read the documentation I always have to check the online source code or online documentation; while navigating the source code from Visual Studio I can't see any documentation.

Thank you

**Comment by julealgon** [comment]
This has already been fixed in the latest version of the NuGet package.

Check the following issue for more details: #1424

**Comment by AlessandroDalMas** [comment]
Thank you guys, I was stopped at 12.2.1. Updating solved it.
