### ISSUE TITLE
'Configuration' is both a namespace and a type

### ISSUE THREAD

**Issue by julealgon** [JoshClose/CsvHelper#1429]
**Describe the bug**
At some point, there were multiple classes in the project that were named `Csv{X}`, and the prefix was removed. This caused the old `CsvConfiguration` class to become just `Configuration`, and now we have multiple problems with this:
1. Naming a class the same as it's containing namespace is a bad practice. [CA1724: Type names should not match namespaces](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1724?view=vs-2019)
2. Naming a class with broadly generic terms causes conflicts with user code

**Expected behavior**
The `Configuration` class should be renamed to something else.

**Comment by JoshClose** [comment]
This is on the list somewhere along with some other classes. I'll try to get this in the next breaking change release.

**Comment by JoshClose** [comment]
This will be in 13.0.0 on NuGet.
