### ISSUE TITLE
error CS0726: ':' is not a valid format specifier

### ISSUE THREAD

**Issue by clockwiseq** [JoshClose/CsvHelper#1434]
**Describe the bug**
When data is simply comma-delimited and the value in one of the records has a colon (:), it attempts to parse this as a formatter.

**To Reproduce**
1. Create a class (`MyExpense`) with properties (`Id, ProcessDate, Name, Description`)
2. Add data to a CSV file with something like:

Id,ProcessDate,Name,Description  
1,2019-11-15,ABC Store,This was for liquor  
2,2019-11-16,Guest: The Store,This was for entertainment

3. Use standard code to get records (`csv.GetRecords<MyExpense>();`) and it will have the first record in the list (intellisense), but have the exception listed after that.

**Comment by AltruCoder** [comment]
This code works fine for me.  I believe that the [CS0726](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/xaastt59(v=vs.90)?redirectedfrom=MSDN) error has something to do with your visual studio debugger and not an error with the code.
>Compiler Error CS0726
This error occurs in the debugger. When you type a variable name into one of the debugger windows, you can follow it with a comma, and then a format specifier. Examples are: myInt, h or myString,nq. This error arises when the compiler does not recognize the Format Specifiers in C#.

**Comment by clockwiseq** [comment]
Apparently it's only when I'm attempting to iterate through the enumerable that's returned by the `GetRecords` call.  When I use the `.ToList()` method, I'm able to iterate just fine.

**Comment by C-Beams** [comment]
Also encountered this when enumerating through the result of a GetRecords call. Tried ToList and it worked fine, just like @clockwiseq .  ~1300 records were returned in my instance and this error appeared for every record beyond the 29th.

**Comment by JoshClose** [comment]
If you run without debugging, does the error still happen?

**Comment by C-Beams** [comment]
@JoshClose 
Yep. Here's the stacktrace:
`   at CsvHelper.CsvReader.<GetRecords>d__63`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
`

My code is very simple, calling GetRecords<MyType>() on a stream of a file and then calling ToArray after to display all of the records in a table on a site.

Just to test it outside of my personal environment and without any issues relating to debugging, I deployed the site to an Azure instance and it the page breaks there, too.

But again, calling ToList() actually works fine. Let me know if you need any more info or code snippets.

**Comment by JoshClose** [comment]
Can you create an example that reproduces it? Like a fully running example where I can hit F5 and see it. I won't be at a computer to test anything for a while

**Comment by C-Beams** [comment]
@JoshClose : Like a simple console app that runs GetRecords with and without ToList()? Or would you rather have me deploy my small site with one page running with ToList() and another without? Not sure what you'd like since you won't be able to test anything as of yet. Either way I can give you the source code to check it out, but like I said it's only a tiny block of code.

**Comment by C-Beams** [comment]
@JoshClose Here's a console app that demonstrates the issue:
https://github.com/C-Beams/CsvHelperIssueDemo

**Comment by AltruCoder** [comment]
@C-Beams The issue is that `csv.GetRecords<SampleModel>()` will lazy load the records.  In other words, it only reads the underlying file as you iterate over the `IEnemurable`.  When you return `IEnumerable<SampleModel>` outside of the `using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))` you have lost access to the `StreamReader` and the underlying data.  Calling `ToList()` iterates the records and pulls the whole file into memory.

**Comment by ghhv** [comment]
Adding an extra FYI gotcha to this, I've had some code working flawlessly for a long time using this `csv.GetRecords<model> ` but today I added a `.Count()` before processing the records in a `foreach` and that killed everything. After the `.Count()`, the `IEnumerable` was now empty. Note, prior to the `.Count()` there were 29 records listed with the CS2076 error for anything beyond. 

```
var records = csv.GetRecords<model>(); // has records (added ToList to resolve)
int recordCount = records.Count(); //empty now
```
Adding `.ToList()` as mentioned above fixes the issue as well.

**Comment by JoshClose** [comment]
Using any sort of LINQ projection will cause all records to be read. CsvReader/CsvParser are forward only readers. If you want to do multiple calls, you can do `.ToList()`, but that will pull all records into memory instead of a single row at a time.

**Comment by VictoriaRamirezCharles** [comment]
I have the same error when I try to get data from sql.

    SqlDataReader Data = null;
                    try
                    {
                        Data = Command.ExecuteReader();
                    }
                    catch (SqlException)
                    {
                        Data = Command.ExecuteReader();
                    }
