### ISSUE TITLE
DateTimeConverter with Timezone help

### ISSUE THREAD

**Issue by natebunton** [JoshClose/CsvHelper#1437]
I'm trying to create a mapping and I'm running into issues with some datetime formats.

Here is the CSV:
```
"Timestamp","Employee","Customer","Service","Buckets of Salt"
"2019/12/31 5:02:25 PM CST","Jeff","Builders Warehouse","Plow","1"
```

The following mapping works when I **remove** the "CST", but throws an exception when the timezone is present.

Can you provide some guidance?

```
 public class ServiceProvided
    {
        [Name("Timestamp")]
        public string Timestamp { get; set; }
        [Name("Employee")]
        public string Employee { get; set; }
        [Name("Customer")]
        public string CompanyName { get; set; }
        [Name("Service")]
        public string Services { get; set; }
        [Name("Buckets of Salt")]
        public int BucketsOfSalt { get; set; }
        [Ignore]
        public DateTime ServiceDate { get; set; }
    }

    public class ServiceProvidedMap : ClassMap<ServiceProvided>
    {
        public ServiceProvidedMap()
        {
            Map(m => m.Timestamp).Name("Timestamp");
            Map(m => m.Employee).Name("Employee");
            Map(m => m.CompanyName).Name("Customer");
            Map(m => m.Services).Name("Service");
            Map(m => m.BucketsOfSalt).Name("Buckets of Salt");
            Map(m => m.ServiceDate).Name("Timestamp").TypeConverter<CsvHelper.TypeConversion.DateTimeConverter>();
        }
    }
```

**Comment by JoshClose** [comment]
You don't need to do both attributes and a mapping. If you didn't register your class map, then it's only using the attributes and you have the `ServiceDate` property ignored.

This is how you would do a custom format.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("\"Timestamp\",\"Employee\",\"Customer\",\"Service\",\"Buckets of Salt\"");
	s.AppendLine("\"2019/12/31 5:02:25 PM CST\",\"Jeff\",\"Builders Warehouse\",\"Plow\",\"1\"");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.RegisterClassMap<ServiceProvidedMap>();
		csv.GetRecords<ServiceProvided>().ToList().Dump();
	}
}

public class ServiceProvided
{
	public string Timestamp { get; set; }
	public string Employee { get; set; }
	public string CompanyName { get; set; }
	public string Services { get; set; }
	public int BucketsOfSalt { get; set; }
	public DateTime ServiceDate { get; set; }
}

public class ServiceProvidedMap : ClassMap<ServiceProvided>
{
	public ServiceProvidedMap()
	{
		Map(m => m.Timestamp).Name("Timestamp");
		Map(m => m.Employee).Name("Employee");
		Map(m => m.CompanyName).Name("Customer");
		Map(m => m.Services).Name("Service");
		Map(m => m.BucketsOfSalt).Name("Buckets of Salt");
		Map(m => m.ServiceDate).Name("Timestamp").TypeConverterOption.Format("yyyy/MM/dd h:mm:ss tt");
	}
}
```

Though, I don't see a way to parse `CST` https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings

I think you'll have to create a custom type converter that strips the `CST` from the end and you can determine what time zone that is. You can then create a `DateTime` (though I would recommend `DateTimeOffset`) object specifying the correct timezone.

**Comment by AltruCoder** [comment]
The problem is `CST` could mean several different time zones.  There is no way to automatically convert it.  https://stackoverflow.com/questions/241789/parse-datetime-with-time-zone-of-form-pst-cest-utc-etc/22868721#22868721

* CST "China Standard Time"   Asia            UTC + 8 hours 
* CST "Central Standard Time" Central America UTC - 6 hours 
* CST "Cuba Standard Time"    Caribbean       UTC - 5 hours 
* CST "Central Standard Time" North America   UTC - 6 hours 

This [stackoverflow answer](https://stackoverflow.com/questions/55747050/how-to-parse-datetime-from-a-specific-timezone-into-utc/55763228#55763228) might give you some ideas for how you could strip the CST off the date and convert the time to the timezone you want using a custom DateTimeConverter.

**Comment by natebunton** [comment]
Thanks for the replies!  I can stop spinning my wheels and manage the timezone in a custom way.  I was able to get a custom type converted created and made a big hacky assumption of the text format.  I'll circle back and make it a little smarter and durable later.

`

    public class ServiceProvided
    {
        public string Employee { get; set; }
        public string CompanyName { get; set; }
        public string Services { get; set; }
        public int BucketsOfSalt { get; set; }
        public DateTime ServiceDate { get; set; }
    }

    public class ServiceProvidedMap : ClassMap<ServiceProvided>
    {
        public ServiceProvidedMap()
        {
            Map(m => m.Employee).Name("Employee");
            Map(m => m.CompanyName).Name("Customer");
            Map(m => m.Services).Name("Service");
            Map(m => m.BucketsOfSalt).Name("Buckets of Salt");
            Map(m => m.ServiceDate).Name("Timestamp").TypeConverter<CustomDateTimeConverter>();
        }
    }

    public class CustomDateTimeConverter : CsvHelper.TypeConversion.DefaultTypeConverter
    {
        /// <summary>
        /// Converts the string to an object.
        /// </summary>
        /// <param name="text">The string to convert to an object.</param>
        /// <param name="row">The <see cref="IReaderRow"/> for the current record.</param>
        /// <param name="memberMapData">The <see cref="MemberMapData"/> for the member being created.</param>
        /// <returns>The object created from the string.</returns>
        public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            if (text == null)
            {
                return base.ConvertFromString(null, row, memberMapData);
            }

            // Trim Last 4 chars from string to drop the timezone
            // 2019/12/31 5:02:25 PM CST
            text = text.Substring(0, text.Length - 4);

            var dateTimeConverter = new CsvHelper.TypeConversion.DateTimeConverter();
            return dateTimeConverter.ConvertFromString(text, row, memberMapData);
        }
    }
`

**Comment by AltruCoder** [comment]
You can make your `CustomDateTimeConverter` more succinct by inheriting from `DateTimeConverter`.
```csharp
public class CustomDateTimeConverter : CsvHelper.TypeConversion.DateTimeConverter
{
    /// <summary>
    /// Converts the string to an object.
    /// </summary>
    /// <param name="text">The string to convert to an object.</param>
    /// <param name="row">The <see cref="IReaderRow"/> for the current record.</param>
    /// <param name="memberMapData">The <see cref="MemberMapData"/> for the member being created.</param>
    /// <returns>The object created from the string.</returns>
    public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
    {
        if (!string.IsNullOrEmpty(text))
        {
            // Trim Last 4 chars from string to drop the timezone
            // 2019/12/31 5:02:25 PM CST
            text = text.Substring(0, text.Length - 4);
        }

        return base.ConvertFromString(text, row, memberMapData);
    }
}
```

**Comment by natebunton** [comment]
@AltruCoder thanks for the suggestion, that is much cleaner!
