### ISSUE TITLE
"Write Class Objects" Example not working, outdated?

### ISSUE THREAD

**Issue by Taschenbuch** [JoshClose/CsvHelper#1445]
This example gives an compile error:
https://joshclose.github.io/CsvHelper/examples/writing/write-class-objects/

when i change it to this, it works. (Is this the correct way of doing?)

```
using (var writer = new StreamWriter("path\\to\\file.csv"))
using (var csv = new CsvWriter(writer))
{
    csv.Configuration.CultureInfo = CultureInfo.InvariantCulture;
    csv.WriteRecords(records);    
}
```

**Comment by JoshClose** [comment]
Are you on the latest version?

**Comment by Taschenbuch** [comment]
okay, works fine now. didnt notice there was an update
