### ISSUE TITLE
Should change log for 13.0.0 include new required dll dependency?

### ISSUE THREAD

**Issue by DanFTRX** [JoshClose/CsvHelper#1446]
13.0.0 now requires Microsoft.Bcl.AsyncInterfaces as a dependency.  This threw me for a quick loop when updating from 12.X to 13.0, because until I ran (and crashed) my software from my bundled installer, I did not notice the new requirement.  Not a big deal, it was easy to resolve, although it would be nice to list new dependencies not included in the underlying runtime on the change log so it can be changed proactively when updating.

**Comment by JoshClose** [comment]
I guess I never thought of this because NuGet lists it and it's handled through there. Are you adding CsvHelper outside of NuGet?

**Comment by DanFTRX** [comment]
@JoshClose When I bundle installers for my software I specify DLLs by name so I know exactly what is being distributed and make sure we dont add anything we don't mean to.

**Comment by JoshClose** [comment]
Ah, ok. I'll update that in the docs and try to remember to do it in the future also.

**Comment by DanFTRX** [comment]
@JoshClose Thanks!

**Comment by JoshClose** [comment]
Updated.
