### ISSUE TITLE
Truncating last column record

### ISSUE THREAD

**Issue by RolandDan** [JoshClose/CsvHelper#1453]
I have the correct values in the Data Table, once it writes into a CSV file, last records last column has it's value truncated.

```
var csvData = string.Empty;
var ms = new MemoryStream();
var sw = new StreamWriter(ms);
var csvFile = new CsvWriter(sw, CultureInfo.InvariantCulture);
var dt = new DataTable();
csvFile.Configuration.SanitizeForInjection = false;

foreach (DataColumn column in dt.Columns)
{
     csvFile.WriteField(column.ColumnName);
}
csvFile.NextRecord();

foreach (DataRow row in dt.Rows)
{                               
     for (var i = 0; i < dt.Columns.Count; i++)
     {
           csvFile.WriteField(row[i]);
     }
     csvFile.NextRecord();
}
sw.Flush();
ms.Position = 0;

using (var sr = new StreamReader(ms))
{
      csvData = sr.ReadToEnd();
}
```
I'm sending that csvData to an ftp.

![Capture](https://user-images.githubusercontent.com/15847499/73775261-8ce69200-4753-11ea-83cb-072eab2d9b1d.JPG)

If I open it with Notepad++, the last row does not have a line end character.

**Comment by JoshClose** [comment]
Did you figure out what the issue is? I tried the example and everything wrote out fine for me. It seems like something wasn't being flushed if the data wasn't all written.

**Comment by RolandDan** [comment]
Hi, it was a type conversion between the 2 methods. I just changed my StreamReader to this 
```
using (var sr = new StreamReader(ms))
                                {
                                    ms.Position = 0;
                                    csvData = Encoding.UTF8.GetBytes(sr.ReadToEnd());
                                    sr.Close();
                                }
```
And sent csvData as a byte array to my ftp method.
