### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by mudnug** [JoshClose/CsvHelper#1455]
You've suggested we make a post before contributing bug fixes, so I wanted to introduce myself. I'm looking at contributing an hour or two of work to help clean out the bug backlog. After a few months I might answer stackoverflow questions or help with the documentation. Any place in particular you'd like me to focus? I do notice a number of open pull requests already.

So far I've got the project building locally and all 660 tests pass.

**Comment by JoshClose** [comment]
Documentation is the biggest place lacking at the moment. The only issue there is, there is a bug in react-static that is causing me to not be able to build the docs at the moment. I think I'm going to have to re-write it in gatsby or something. This is the second bug in a month that has completely halted building of the docs site. Once the site is converted over to gatsby (or whatever), the docs are just markdown files.

Pull requests are something I'll need to look at first. Some of the features in the pull requests have been implemented and some won't be accepted. I always seem to restructure things in them anyways.

Fixing bugs would definitely be a big help.

Answering questions here and on stackoverflow  would be a big help. David Specht has been doing an awesome job of this when he has time.

Hop on the gitter page to chat, ask questions, etc about these things. I try to respond promptly, assuming the phone app gives me the alert of a new message. https://gitter.im/CsvHelper/Lobby

**Comment by mudnug** [comment]
I'm aiming to work mostly on issues for a while until I feel like I have a good handle and can help out with SO questions/docs.

Closing as I've been able to reach you on gitter
