### ISSUE TITLE
How to validate a row

### ISSUE THREAD

**Issue by LeGrandKhan** [JoshClose/CsvHelper#1464]
Hello,

What is the new way to validate all columns?
I looked at https://github.com/JoshClose/CsvHelper/issues/1138 
and i think it doesn't work anymore.

thank you

**Comment by AltruCoder** [comment]
It just needs a couple of tweaks to work with the updates.
```csharp
void Main()
{
    var s = new StringBuilder();
    s.Append("Id,Name\r\n");
    s.Append("1,one\r\n");
    s.Append("2,two\r\n");
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
    {
        var exceptions = new List<HeaderValidationException>();
        csv.Configuration.HeaderValidated = (isValid, headerNames, headerNameIndex, context) =>
        {
            if (!isValid)
            {
                exceptions.Add(new HeaderValidationException(context, headerNames, headerNameIndex, "Your message here."));
            }
        };

        csv.Read();
        csv.ReadHeader();
        csv.ValidateHeader<Test>();

        if (exceptions.Count > 0)
        {
            throw new AggregateException(exceptions);
        }

        csv.GetRecords<Test>().ToList();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string One { get; set; }
    public string Two { get; set; }
    public string Three { get; set; }
}

public class TestMap : ClassMap<Test>
{
    public TestMap()
    {
        Map(m => m.Id);
	Map(m => m.Name);
    }
}
```

**Comment by LeGrandKhan** [comment]
Hello,
sorry I misspoke my need.

I need validation by raw.
ex:
Header: Date; int; string
Raw1: toto; toto; toto
Raw1: 10/10/2020; 1; toto
I need to have the 2 conversion errors for the date and int and to pass to the next raw.
thank you

**Comment by jzabroski** [comment]
@LeGrandKhan This should work but its clunky:

```c#
public class TestMap : ClassMap<Test>
{
    public TestMap()
    {
        Map(m => m.Id).Validate(string s => int.Parse(s));
	Map(m => m.Name).Validate(string s => DateTime.ParseExact(s, "MM/dd/yyyy", CultureInfo.InvariantCulture)) // for reading foreign data sources, use ParseExact + invariant culture as your CSV data source likely doesn't care what thread locale your principal is running as
    }
}
```

**Comment by jzabroski** [comment]
As a final remark, I stopped using `.Validate()` built-in by CsvHelper and instead use @JeremySkinner 's FluentValidation framework.  I find that I can process CsvReader wrotes in batches, and call a FluentValidation rule on my ClassMap'ed CsvRow object, and the validation can happen on a callback thread while CsvReader continues reading.  The added benefit is my validation logic is also more re-usable and easier to test independent of setting up streams to read/write to, so my tests are a lot simpler and just focus on the validation itself.
