### ISSUE TITLE
CSV writerecords appears to be failing when writing values containing "#"

### ISSUE THREAD

**Issue by BOMalley25** [JoshClose/CsvHelper#1470]
I have a .NET core webserver API endpoint which should return a csv built using csvhelper.
My values object is of type System.Collections.Generic.List<object> and contains objects of type System.Dynamic.ExpandoObject.

Code is:

           using var ms = new MemoryStream();
            
            using (var sw = new StreamWriter(ms))
            {
                var outputCsv = new CsvWriter(sw, CultureInfo.InvariantCulture);
                outputCsv.WriteRecords(values);
            }

            var response = ms.ToArray();
            return new FileContentResult(response, "text/csv");

This is working fine except for when one of the values I'm writing to CSV is a string containing a "#" character. When this is the case the csv writer appears to simply stop writing at that point, no exception is thrown but the csv is truncated.

I thought maybe it was interpreting the #  as a comment but I've tried explicitly setting AllowComments = false and overwriting the default comment character with another character, to no effect.

What's more confusing is that I tried to repro in a simple console app:

           var list = new List<object>();
            dynamic obj = new ExpandoObject();
            obj.Name = "words";
            obj.Value = "# string starting with a hash";
            obj.Value2 = "#string starting with a hash";
            obj.Value3 = "#1 SMP Wed Jul 16 12:08:17 BST 2014";
            list.Add(obj);
            dynamic obj2 = new ExpandoObject();
            obj2.Name = "words";
            obj2.Value = "# string starting with a hash";
            obj2.Value2 = "#string starting with a hash";
            obj2.Value3 = "#1 SMP Wed Jul 16 12:08:17 BST 2014";
            list.Add(obj2);

            

            using var ms = new MemoryStream();
            using (var writer = new StreamWriter(ms)) {
                var csv = new CsvWriter(writer, CultureInfo.InvariantCulture);
                
                csv.WriteRecords(list);
                
            }

            var output = ms.ToArray();
            File.WriteAllBytes("C:\\output.csv", output);

and this code works fine, despite the object type of values appearing to be exactly the same.

**Comment by JoshClose** [comment]
If you're writing 1,000 records and the first record has a `#`, does it stop at the first record?

**Comment by BOMalley25** [comment]
Yes, it will write records until it hits a record containing a #. That record will be empty, and it will not write any further records

**Comment by JoshClose** [comment]
You're not able to create an example that reproduces it though?

**Comment by BOMalley25** [comment]
No, in fact on looking further I'm fairly certain that the truncation is actually happening in my front end, and so is nothing to do with CsvHelper. Sorry to bother you!

**Comment by JoshClose** [comment]
No worries!

**Comment by JoaoDSSousa** [comment]
Hello,

I have also run into this issue, the file stops being written after the "#" character. Locally on my machine it works fine, but on the server it stops writing the file.

I do not think the character # is a special character that requires to be encoded and I haven't seen anything in this library that could be causing the problem.

I suspect the problem might be related with having the code running in a linux machine, since my local environment is windows.

server hosted on AWS using a linux image
project dotnet core 2.1
library version 15.0.1

**Comment by JoshClose** [comment]
@JoaoDSSousa Can you create a new issue and post example code that demonstrates the issue? If it works locally but not on the Linux server, that is fine, still post the code.
