### ISSUE TITLE
feature: GetRecords() output to implement IDataReader

### ISSUE THREAD

**Issue by mikeTWC1984** [JoshClose/CsvHelper#1471]
**Describe the solution you'd like**
Is is hard/possible to implement IDataReader for the output of CsvReader.GetRecords method? 
CsvDataReader implements it, but it includes all the columns (as string). This would be extremely useful for csv import to databases (several major RDBMS support bulk inserts from datareader)

**Additional context**
This potentially could be used to created some SQL-like DSL to query csv files

**Comment by JoshClose** [comment]
What do you mean by
> it includes all the columns (as string)

**Comment by mikeTWC1984** [comment]
I mean it acts like "Select *". Say my csv has 10 columns, and if I load CsvDataReder to datatable it will have all those 10 columns. But in some cases I'd need just a few columns (say 3 out of 10). In this case GetRecords method is useful, but to move it to database you still need manually convert it to  reader or datatable.

**Comment by JoshClose** [comment]
Does the second example here do what you need? https://joshclose.github.io/CsvHelper/examples/data-table

**Comment by mikeTWC1984** [comment]
What I'd like to have is some mix of that and GetRecords method. GetRecords returns specific columns/types based on mapping class (but as IEnumerable<T>), I guess it also let you create constant fields.   CsvDataReader implements IDataReader (my goal), but there is no way to filter columns (or there is?).

**Comment by JoshClose** [comment]
Looks like there currently isn't a way to limit the `CsvDataReader` columns. I thought specifying them in the `DataTable` would do it, but it doesn't. You could manually create your `DataTable` and only use the columns you want.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("Id,Name,Date");
	s.AppendLine($"1,one,{DateTimeOffset.Now.ToString("o")}");
	s.AppendLine($"2,two,{DateTimeOffset.Now.ToString("o")}");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
	{
		csv.Configuration.RegisterClassMap<FooMap>();
		var records = csv.GetRecords<Foo>();

		var dt = new DataTable();
		dt.Columns.Add("Id", typeof(int));
		dt.Columns.Add("Name", typeof(string));

		foreach (var record in records)
		{
			var row = dt.NewRow();
			row["Id"] = record.Id;
			row["Name"] = record.Name;
			dt.Rows.Add(row);
		}
		
		dt.Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```

**Comment by mikeTWC1984** [comment]
Thanks. After some research I found out that FastMember library do exactly what I need. It can convert IEnumerable<T> (product of GetRecords<T>) into IDataReader
