### ISSUE TITLE
write record if not empty file 

### ISSUE THREAD

**Issue by TavernierCedric** [JoshClose/CsvHelper#1472]
i want to be able to write data if the file is empty all the record in my list but if not only write data at the end of the file the new data but i don't find in you doc  how to do that

**Comment by AltruCoder** [comment]
You need to pass `true` as the append parameter of the `StreamWriter` constructor.
https://stackoverflow.com/questions/5516870/how-to-write-data-to-a-text-file-without-overwriting-the-current-data
```csharp
void Main()
{
    var records = new List<Foo>
    {
        new Foo { Id = 1, Name = "one" },
    };

    using (var writer = new StreamWriter("path\\to\\file.csv", true))
    using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
    {
        csv.WriteRecords(records);
    }
}

public class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

If there is already data in the file, you may not want to write the header again. 
```csharp
csv.Configuration.HasHeaderRecord = false;
```

**Comment by TavernierCedric** [comment]
How can I now that the file is not empty . My use case is that a yes begin of the day the file wil be empty but not at the long of the day is it a good way to now when I add a the end or not

**Comment by JoshClose** [comment]
https://stackoverflow.com/questions/3007711/is-file-empty-check

**Comment by TavernierCedric** [comment]
thanks
