### ISSUE TITLE
Changing row delimiter for reading: is supporting it viable?

### ISSUE THREAD

**Issue by PatrickHofman** [JoshClose/CsvHelper#1473]
In [a comment](https://github.com/JoshClose/CsvHelper/issues/768#issuecomment-333733750) on https://github.com/JoshClose/CsvHelper/issues/768 in 2017 Josh indicated that changing the row delimiter to any string value for reading has a so heavy impact on the performance, that it won't supported.

Has this changed in the meantime, or is it possible to support custom row delimiters now? We have some use cases when loading data from (generally) old systems, where it resembles CSV quite closely, just not the row delimiter.

If changing the row delimiter would be supported, this would be a great help. If any work needs to be done, please let me know.

**Comment by JoshClose** [comment]
This will be available in the next version of the parser. The next version uses `Memory<T>` and `Span<T>` and is more than 5 times faster. The issue is those things are only available in `netstandard2.1`. I haven't decided how I'm going to handle this yet.

**Comment by PatrickHofman** [comment]
That sounds wonderful. Need help anywhere?

**Comment by JoshClose** [comment]
I just added a discussion issue for this. Please add your thoughts. https://github.com/JoshClose/CsvHelper/issues/1474

**Comment by JoshClose** [comment]
You can still change the delimiter. This issue was about changing the **row** delimiter. i.e. line ending.

**Comment by JoshClose** [comment]
Changing the row delimiter has been available now since version 19. Use the `NewLine` configuration to set to any string you like. The works for both reading and writing.
