### ISSUE TITLE
Reading from string fails when reading from byte[] does not

### ISSUE THREAD

**Issue by pkoronawa** [JoshClose/CsvHelper#1481]
Equivalent operations reading CSV fail when stream is StringReader but succeed when stream is MemoryStream

**To Reproduce**
Run test in attached project

**Expected behavior**
Test succeeds

[CsvStringReader.zip](https://github.com/JoshClose/CsvHelper/files/4372820/CsvStringReader.zip)

**Additional context**

**Comment by JoshClose** [comment]
Your `Serialize` method is using `Encoding.Unicode` to write the data. You're then reading the data using `UTF8EncodingSealed` via `config.Encoding`. That's why it's not working.

**Comment by pkoronawa** [comment]
Setting config.Encoding = Unicode doesn't change behavior. Also, when using StringReader, the headers are read correctly, it's only when GetRecord<T> is called that it fails.

**Comment by JoshClose** [comment]
It has something to do with `memoryStream.ToArray()`. If I read the text from the stream and using the encoding to get the bytes, it works fine.

```cs
private byte[] Serialize<T>(IEnumerable<T> collection, CsvConfiguration config)
{
    using (MemoryStream memoryStream = new MemoryStream())
    {
        using (StreamWriter streamWriter = new StreamWriter(memoryStream, config.Encoding, leaveOpen: true))
        {
            using (CsvWriter csvWriter = new CsvWriter(streamWriter, config))
            {
                // Use this instead of csvWriter.WriteRecords to ensure
                // the header is on the output even if the collection is empty
                csvWriter.WriteHeader<T>();
                csvWriter.NextRecord();

                foreach (T item in collection)
                {
                    csvWriter.WriteRecord<T>(item);
                    csvWriter.NextRecord();
                }
            }
        }

        memoryStream.Position = 0;
        using (var streamReader = new StreamReader(memoryStream))
        {
            return config.Encoding.GetBytes(streamReader.ReadToEnd());
        }

        return memoryStream.ToArray();
    }
}
```

When using `ToArray()` there seem to be some hidden characters like a byte order mark in the fields.

**Comment by JoshClose** [comment]
Or if I change the method `ReadString` to convert the data back to a string the same way it was go out, it works too. Since `MemoryStream.ToArray()` is used, you need to do `new MemoryStream(byte[])` to go back in again.

```cs
private List<TestSerilizationClass> ReadString(CsvConfiguration config, byte[] data)
{
    List<TestSerilizationClass> deserializedList;
    string dataString = config.Encoding.GetString(data);

    //using (StringReader stringReader = new StringReader(dataString))
    using (var memoryStream = new MemoryStream(data))
    using (var streamReader = new StreamReader(memoryStream, config.Encoding))
    {
        using (CsvReader csv = new CsvReader(streamReader, config))
        {
            deserializedList = ReadCsv(csv);
        }
    }

    return deserializedList;
}
```

**Comment by pkoronawa** [comment]
Using MemoryStream has always worked; it's using StringReader that has failed. But you're correct, the first header includes the ByteOrderMark. Applying TrimStart((char)0xfeff) when getting the string solves the problem. 
Thanks
