### ISSUE TITLE
CsvWriter.WriteRecords method thrown NullReferenceException in Linqpad

### ISSUE THREAD

**Issue by pengzhisun** [JoshClose/CsvHelper#1486]
**Describe the bug**

In Linqpad or similar dynamic assembly loaded application, `CsvWriter.WriteRecords` method thrown following exception while re-run the Query code:

```log
[CsvHelper.WriterException]An unexpected error occurred.
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   at UserQuery.Main() in C:\Users\**\AppData\Local\Temp\LINQPad5\**\**\LINQPadQuery.cs:line 54
[System.NullReferenceException]Object reference not set to an instance of an object.
   at CsvHelper.Configuration.MemberMapCollection.AddMembers(ClassMap mapping)
   at CsvHelper.CsvWriter.WriteHeader(Type type)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
```

For the `CsvWriter.WriteHeader` code thrown this exception, it was trying to add a `ClassMap` instance to `Maps` Dictionary and retrived by the `System.Type` instance as `Key`.

```csharp
if (context.WriterConfiguration.Maps[type] == null)
{
    context.WriterConfiguration.Maps.Add(context.WriterConfiguration.AutoMap(type));
}

var members = new MemberMapCollection();
members.AddMembers(context.WriterConfiguration.Maps[type]);
```

The `CsvConfiguration.AutoMap` method will leverage `ReflectionHelper.CreateInstance` method to create a `DefaultClassMap<T>` instance, it maintains a static dictionary cache for resolved constructor functions: [code](https://github.com/JoshClose/CsvHelper/blob/24d8d5393d1c88f852fec32803419bf5a800f2b9/src/CsvHelper/ReflectionHelper.cs#L62), the cache dictionary key is generated as following code:

```csharp
var typeNames = new List<string>();
typeNames.Add(type.AssemblyQualifiedName);
typeNames.AddRange(args.Select(a => a.GetType().AssemblyQualifiedName));
var key = string.Join("|", typeNames).GetHashCode();
```

But for the two versions UserQuery assemblies dynamic loaded in Linqpad, the Defined Type have same `AssemblyQualifiedName` but are two different RunTime Types.

For Example:

* Assume we defined a `TestRecord` type in Linqpad
* The first version Runtime Type makred as `[A]TestRecord`
* After first time called the `CsvWriter.WriteRecords` successfuly, the `ReflectionHelper` had a cached constructor function for `[A]TestRecord`, the cache key is `UserQuery.TestRecord` (the assembly qualified type name for `TestRecord`
* We modified the Query code and re-run, which caused the Linqpad to dynamic load another version assembly, the new Runtime Type marked as `[B]TestRecord`
* While we trying to call the `CsvWriter.WriteRecords` again, the `ReflectionHelper` used `[B]TestRecord`'s assembly qualified type name `UserQuery.TestRecord` and resolved a constructor function cache for `[A]TestRecord`, then create a `DefaultClassMap<T>` instance for `[A]TestRecord`, then add the `ClassMap` instance for `[A]TestRecord` to `CsvConfiguration.Maps` dictionary.
* Eventually, the `CsvWriter.WriteHead` method tried to get the `ClassMap` instance with Runtime Type `[B]TestRecord` from `CsvConfiguration.Maps` dictionary, but got a null value, since the two RunTime Type instance are not equal.

**Workarounds**
Currently, I have found two workarounds for this issue:

1. Press `CTRL+SHIFT=F5` to Reset the UserQuery process before each execution.

2. Add the following code before calling `CsvWriter.WriteRecords` method:

```csharp
using (StreamWriter writer = new StreamWriter(filePath, false, Encoding.UTF8))
using (CsvWriter csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
{
    var map = (ClassMap)Activator.CreateInstance(typeof(DefaultClassMap<TestRecord>));
    map.AutoMap((CsvConfiguration)csv.Configuration);
    csv.Configuration.RegisterClassMap(map);

    csv.WriteRecords(records);
}
```

**To Reproduce**
1. Paste following code in a `New LinqPad Query Tab`:

```csharp
void Main()
{
    var records =
        Enumerable.Range(1, 10)
            .Select(i => new TestRecord
            {
                ID = i,
                Name = $"Item-{i}",
            });

    var filePath = @"E:\Temp\RunTimeTests.csv";
    using (StreamWriter writer = new StreamWriter(filePath, false, Encoding.UTF8))
    using (CsvWriter csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
    {
        try
        {
            /* Workaround Solution 1
            var map = (ClassMap)Activator.CreateInstance(typeof(DefaultClassMap<TestRecord>));
            map.AutoMap((CsvConfiguration)csv.Configuration);
            csv.Configuration.RegisterClassMap(map);
            */
            
            /* Workaround Solution 2
            CTRL + SHIFT + F5: Cancel All Threads and Reset
            */

            csv.WriteRecords(records);
            $"{records.Count()} records saved to {filePath}".Dump();
        }
        catch (Exception ex)
        {
            /* Catched Exception
[CsvHelper.WriterException]An unexpected error occurred.
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   at UserQuery.Main() in C:\Users\**\AppData\Local\Temp\LINQPad5\**\**\LINQPadQuery.cs:line 54
[System.NullReferenceException]Object reference not set to an instance of an object.
   at CsvHelper.Configuration.MemberMapCollection.AddMembers(ClassMap mapping)
   at CsvHelper.CsvWriter.WriteHeader(Type type)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
             */
            for (Exception e = ex; e != null; e = e.InnerException)
            {
                $"[{e.GetType().FullName}]{e.Message}\n{e.StackTrace}".Dump();
            }
        }
    }
}

public class TestRecord
{
    public int ID { get; set; }

    public string Name { get; set; }
}
```
2. Click on 'Execute' button
3. Change the code `Enumerable.Range(1, 10)` to `Enumerable.Range(1, 1`)`
4. See error in output panel

**Expected behavior**

The expected behavior should thrown no error and the `CsvWriter.WriteRecords` method should be worked well at every execution. 

**Screenshots**

**Additional context**

**Comment by JoshClose** [comment]
This isn't failing for me. I'm using LINQPad 6. I tried in 5 also and it still works.

**Comment by pengzhisun** [comment]
> 
> 
> This isn't failing for me. I'm using LINQPad 6. I tried in 5 also and it still works.

My Dev environment:
Microsoft Windows [Version 10.0.18363.720]
LinqPad V5.41.00
CsvHelper Nuget Package Version: v15.0.3

Snapshot:
![image](https://user-images.githubusercontent.com/764635/77826423-288bf180-714a-11ea-806e-0d659488eb56.png)

**Comment by JoshClose** [comment]
Weird. I have the same versions of everything that you do.

**Comment by pengzhisun** [comment]
> 
> 
> Weird. I have the same versions of everything that you do.

The first run should be worked,, but if you modified the query code to trigger the LinqPad reload a newer version LINQPadQuery.dll in the same LINQPad.UserQuery.exe process, the exception should be thrown.

**Comment by pengzhisun** [comment]
More Evidences:

The code to compare the cached type and the runtime type:

```csharp
            var cachedType = csv.Configuration.AutoMap(typeof(TestRecord)).ClassType;
            new
            {
                cachedType.AssemblyQualifiedName,
                HashCode = cachedType.UnderlyingSystemType.GetHashCode()
            }.Dump("Cached TestRecord");

            var currentType = typeof(TestRecord);
            new
            {
                currentType.AssemblyQualifiedName,
                HashCode = currentType.UnderlyingSystemType.GetHashCode()
            }.Dump("Current TestRecord");
```

You could see the hash code for cached type is same for each run, but the hash code of the runtime type are different.

![csv_20](https://user-images.githubusercontent.com/764635/77827573-60e2fe00-7151-11ea-80d0-43de0b27468f.PNG)
![csv_19](https://user-images.githubusercontent.com/764635/77827574-617b9480-7151-11ea-875d-faec53b09583.PNG)

**Comment by pengzhisun** [comment]
By the way, if you changed the previous code to the generic version `AutoMap<T>` method, you could got the following exception:

![image](https://user-images.githubusercontent.com/764635/77827839-eadf9680-7152-11ea-91e2-a6469c224021.png)

And from the `ReflectionHelper` source code:

```csharp
public static T CreateInstance<T>(params object[] args)
{
	return (T)CreateInstance(typeof(T), args);
}

public static object CreateInstance(Type type, params object[] args)
{
	return ObjectResolver.Current.Resolve(type, args);
}
```

You could see the cast exception was thrown just because the runtime type is different with the cached version.

**Comment by JoshClose** [comment]
In 15.0.4 on NuGet.
