### ISSUE TITLE
Header Record Skipped Then Fails Validation

### ISSUE THREAD

**Issue by andrewwilkin** [JoshClose/CsvHelper#1492]
Have a fairly simple file to read in with a header row and it is failing with an exception:
`CsvHelper.HeaderValidationException : Header with name 'VDIPractice' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.`

What appears to be happening is that is skipping the header row, as when I look I add a break point on the function to convert headers to lowercase it is the second row it is trying to match:

```csharp
        public List<ReferenceDataRecord> ReadInputFile(string filePath)
        {
            List<ReferenceDataRecord> data = new List<ReferenceDataRecord>();

            using (var reader = new StreamReader(filePath))
            {
                using var csv = new CsvReader(reader, CultureInfo.CurrentCulture);
                csv.Configuration.HasHeaderRecord = true;
                //csv.Configuration.MissingFieldFound = null;
                //csv.Configuration.BadDataFound = null;
                //csv.Configuration.Delimiter = ",";
                //csv.Configuration.TypeConverterCache.RemoveConverter<Double>();
                //csv.Configuration.TypeConverterCache.AddConverter<Double>(new CustomDoubleConverter());
                //csv.Configuration.TypeConverterCache.AddConverter<Guid>(new CustomGuidConverter());
                //csv.Configuration.TrimOptions = TrimOptions.Trim | TrimOptions.InsideQuotes;
                csv.Configuration.PrepareHeaderForMatch = (header, index) =>
                {
                    return header.ToLower();
                };
                //csv.Configuration.Encoding = Encoding.UTF32;
                //csv.Configuration.CountBytes = true;
                //csv.Configuration.HeaderValidated = null;

                while (csv.Read())
                {
                    var records = csv.GetRecords<ReferenceDataRecord>();
                    data = records.ToList();
                }
            }
            return data;
        }
```

The POCO is:
```csharp
 public class ReferenceDataRecord
    {
        public string VDIPractice { get; set; }
        public double MinutesPerConsult { get; set; }   
        public string CurrencyChoice { get; set; }
        public string CurrencyExchange { get; set; }
        public string BenchmarkingGroups { get; set; }
    }
```

If I set HasHeaderRecord = false it works yet here is a screenshot of the file:
![image](https://user-images.githubusercontent.com/31779817/78450002-5b1a7a80-7673-11ea-8d1d-d183a7fdb9b1.png)

Am using .Net Core 3.1 and the latest NuGet Package. What am I missing? Thanks :)

**Comment by AltruCoder** [comment]
You are mixing the reading of records line by line with the reading of the records all at once.  `csv.GetRecords<ReferenceDataRecord>()` calls the `Read()` method internally, so that first `Read()` method you are calling is skipping the first line.  To get all the records you just need to call
```csharp
var records = csv.GetRecords<ReferenceDataRecord>();
data = records.ToList();
```
To read them line by line you would need to do something like this.
```csharp
var records = new List<ReferenceDataRecord>();
csv.Read();
csv.ReadHeader();
while (csv.Read())
{
    var record = csv.GetRecord<ReferenceDataRecord>();
    records.add(record);
}
```

**Comment by andrewwilkin** [comment]
@AltruCoder thank you so much, what a banana I've been...
Hadn't noticed I added the "s" on the end, and was working when there was no header.

**Comment by Ward1984** [comment]
@AltruCoder 
In your last code-snippet 'Add' should be capitalized ;-)

**Comment by AltruCoder** [comment]
@Ward1984 Fixed it thanks.
