### ISSUE TITLE
CsvReader initialize once.

### ISSUE THREAD

**Issue by dberkouwer** [JoshClose/CsvHelper#1493]
Hi,

Right now im using the CsvWriter class to write CSV files. Works great. The best thing about it is that i can create all ClassMaps once and then use them a 1000 times. So i only have 1 CsvWriter object that configured once.
Like this:
StringWriter stringWriter = new StringWriter(ResultBuilder);
CsvWriter csvWriter = new CsvWriter(stringWriter, CultureInfo.InvariantCulture);
The Resultbuilder is a StringBuilder i clear everytime i finished a csvfile.

Question:
Is there a way to initialize the CsvReader with all classmaps and use the CsvReader like the CsvWriter? So just set the new string data and run the .GetRecords<T> again.
Setting up the classmap each time is slow.

Ive seen this on your site:
https://joshclose.github.io/CsvHelper/examples/reading/reading-multiple-record-types/
but that requires me to use a switch an put in all in one function. I have now like 15 maps so i dont want to do that.

Is this a possiblity?

David

**Comment by JoshClose** [comment]
You can create the configuration file and pass it into as many instances of `CsvWriter` or `CsvReader` as you like.

**Comment by dberkouwer** [comment]
Thanks for you're quick reply:-) And if there is not other option ill use it. But this still requires to make an new instance of the CsvReader every time. The best way( i think) would be to use dependency injection for the CsvReader as well.

**Comment by JoshClose** [comment]
I don't understand what you mean by this.

> Using the CsvConfiguration class gained ~15% of processing time.

Can you give an example of the setup before, and the setup after, that caused a 15% slowdown?

**Comment by dberkouwer** [comment]
After implementing the configuration class and pass it in the constructor it finished 15% faster. And that makes sense because it doesn't need to instantiate the configurationClass each time(3000 times in my case)

Thats because i really want to have a single instance of the CsvReader to speed it up even more.

**Before:**
 protected IEnumerable<T> FillSource<T, TMap>(string data) where TMap : ClassMap
        {
            using (StringReader reader = new StringReader(data))
            {
                using (CsvReader csv = new CsvReader(reader, CultureInfo.InvariantCulture))
                {
                    csv.Configuration.HeaderValidated = null;
                    csv.Configuration.MissingFieldFound = null;
                    csv.Configuration.RegisterClassMap<TMap>();

                    IEnumerable<T> records = csv.GetRecords<T>();
                    return records.ToList();
                }
            }
        }

**After:**
private void SetCsvConfiguration()
        {
            CsvConfiguration = new CsvConfiguration(System.Globalization.CultureInfo.InvariantCulture);
            CsvConfiguration.HeaderValidated = null;
            CsvConfiguration.MissingFieldFound = null;
            CsvConfiguration.RegisterClassMap<xxxx1Map>();
            CsvConfiguration.RegisterClassMap<15 more maps>();
}

        protected IEnumerable<T> FillSource<T>(string data)
        {
            using (StringReader reader = new StringReader(data))
            {
                using (CsvReader csv = new CsvReader(reader, CsvConfiguration))
                {
                    IEnumerable<T> records = csv.GetRecords<T>();
                    return records.ToList();
                }
            }
        }

**Comment by JoshClose** [comment]
The reader/parser has some state in it, so it would be hard to reuse a single instance.
