### ISSUE TITLE
Read is not skipping header

### ISSUE THREAD

**Issue by thdotnet** [JoshClose/CsvHelper#1494]
The following test is failing because it's using the header row rather than the following line. 

PS: I'm using the latest version 15.0.4

```
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Globalization;
using System.IO;
using System.Text;

namespace UnitTestProject1
{

    public class Message
    {
        [CsvHelper.Configuration.Attributes.Ignore]
        public int Id { get; set; }

        [Name("Timestamp")]
        public string TimeStamp { get; set; }

        [Name("Message ID")]
        public string MessageID { get; set; }

        [Name("Message")]
        public string Content { get; set; }

    }

    [TestClass]
    public class UnitTest1
    {
        public static string ContainerName { get; set; }
        public sealed class MessageMapper : ClassMap<Message>
        {
            public MessageMapper()
            {
                Map(m => m.TimeStamp).Name("Timestamp");
                Map(m => m.MessageID).Name("Message ID");
                Map(m => m.Content).Name("Message");

            }
        }

        [TestMethod]
        public void TestMethod1()
        {
            var file = new StringBuilder();

            foreach (var line in GetFakeLines())
            {
                file.AppendLine(line);
            }

            var fileContent = file.ToString();

            using (var stringReader = new StringReader(fileContent))
            using (var csvReader = new CsvReader(stringReader, CultureInfo.InvariantCulture))
            {
                csvReader.Configuration.HasHeaderRecord = true;
                csvReader.Configuration.MissingFieldFound = null;
                csvReader.Configuration.RegisterClassMap<MessageMapper>();                

                csvReader.Read();
                csvReader.ReadHeader();

                var headers = csvReader.Context.HeaderRecord;

                var record = csvReader.GetRecord<Message>();
                Assert.IsTrue(record.Content == "Foo");
            }
        }

        private static string[] GetFakeLines()
        {
            return new string[] {
                "Timestamp,Message ID,Message",
                "\"Sun Oct 14, 2018 00:53:15\",1,Foo"
            };
        }
    }
}

```

**Comment by JoshClose** [comment]
You need to call `Read` before `GetRecord`. `Read` will advance the row. `GetRecord` will turn the row contents into an object. These are separate so you can call `GetRecord` multiple times with different types or `GetField` or anything else you want to do. `GetRecords` (plural) will call `Read` for you because it needs to return all the records.

**Comment by thdotnet** [comment]
Hi @JoshClose , I'm doing it. If you check my code, I'm calling Read, ReadHeader and only then GetRecord.

**Comment by JoshClose** [comment]
Calling `Read` will advance to the first row. Calling `ReadHeader` will read the header information. It doesn't advance the row. You need to call `Read` again to advance to row 2. You can then call `GetRecord` on row 2. You'll then need to call `Read` again to advance to row 3.

This example illustrates this. https://joshclose.github.io/CsvHelper/examples/reading/reading-by-hand

**Comment by JoshClose** [comment]
`Read` will read a row. When on a row you can either read the headers, read a row, or read individual fields. Reading the headers will take the row and use it's fields as the headers in the system. That means you can do things like `GetField<int>("Id")` because you have read the headers into the system at some point.

**Comment by paulduran** [comment]
I'm in the process of upgrading from CSVHelper v2.16 to v15.0.8 and I'm having a lot of confusion with this too.

What's the point of setting `HasHeaderRecord` in the `CsvConfiguration` if you still have to call `Read()`, then `ReadHeader()` before you can start `Read()`ing the actual data? We now need to keep track of the header record twice when reading in a file.

This seems like a pretty significant behavioural change (although its a rather large upgrade gap for me so i can accept a lot of blame there!) and , reading through the release notes, I couldn't see when it was introduced?

**Comment by paulduran** [comment]
No worries @JoshClose , thanks for the explanation.

Really appreciate the work you've done in maintaining this awesome library over the long period of time.
