### ISSUE TITLE
Allow special `null` values to be written.

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#1497]
When writing, allow a `null` to be written as some sort of special value like `NULL`.

**Comment by gabbyhershey** [comment]
Can I try this for Hacktober fest? If not, is there anything else I should work on

**Comment by JoshClose** [comment]
Sorry @gabbyhershey I didn't see this.

**Comment by JoshClose** [comment]
This was done several months ago as a part of a different feature.

**Comment by Falco20019** [comment]
Is there documentation on how to use it?

**Comment by JoshClose** [comment]
No, not yet. There are type converter options you can set. The null values were only used for reading before, but works with writing now.

```cs
Map(m => m.Name).TypeConverterOption.NullValues("NULL");
```

**Comment by matthetherington** [comment]
@JoshClose is there a way to set this globally for all nullable types?
