### ISSUE TITLE
Using ShouldQuote(): how to get the class map information from the context parameter?

### ISSUE THREAD

**Issue by abrasat** [JoshClose/CsvHelper#1503]
I am struggling with the usage of ShouldQuote... Is it possible to extract from context parameter the information about the class map for the different columns from a record?
I would like to use ShouldQuote to quote only the columns mapped to a String type.

**Comment by TimSirmovics** [comment]
I have the exact same question.

**Comment by AltruCoder** [comment]
This appears to be related to this question. https://github.com/JoshClose/CsvHelper/issues/693

**Comment by AltruCoder** [comment]
I don't believe it is possible in `ShouldQuote` to determine the object type of the value to quote.  Here is a possible solution to the problem. https://stackoverflow.com/questions/56579848/csvhelper-configuration-shouldquote-return-true-for-only-fields-on-the-dto-whi

**Comment by abrasat** [comment]
> I don't believe it is possible in `ShouldQuote` to determine the object type of the value. Here is a possible solution to the problem. https://stackoverflow.com/questions/56579848/csvhelper-configuration-shouldquote-return-true-for-only-fields-on-the-dto-whi

Thats the workaround I am actually using.
But it should be possible to get the mapped property type from the name of the field, when handling the header (this can be identified from the context, when "HasHeaderBeenWritten" is true). This information should then be somehow cached when writing the subsequent records. Although I noticed another problem when writing a csv with several headers: the parameter "HasHeaderBeenWritten" is set on true only after writing the first header, and then it is set on false. When writing the second header, the "HasHeaderBeenWritten" remains false...

**Comment by JoshClose** [comment]
> the parameter "HasHeaderBeenWritten" is set on true only after writing the first header, and then it is set on false. When writing the second header, the "HasHeaderBeenWritten" remains false...

Submit a bug for this.

**Comment by JoshClose** [comment]
You can get the index using `context.Record` and find the map that way. You will need to change this code up if you're using field members or constructor parameters instead of properties. You could also do some checks if you're using a combination of them.

```cs
void Main()
{
	var records = new List<Foo>
	{
		new Foo { Id = 1, Name = "one" },
		new Foo { Id = 2, Name = "two" },
	};
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
	{
		csv.Configuration.ShouldQuote = (field, context) => 
		{
			var index = context.Record.Count;
			var type = ((PropertyInfo)context.WriterConfiguration.Maps.Find<Foo>().MemberMaps[index].Data.Member).PropertyType;
			if (type == typeof(string))
			{
				return true;
			}
			
			return ConfigurationFunctions.ShouldQuote(field, context);
		};
		csv.WriteRecords(records);
		writer.ToString().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by abrasat** [comment]
Thanks for the code sample

**Comment by JoshClose** [comment]
You're welcome.

**Comment by JoshClose** [comment]
@AltruCoder I updated your answer on SO and added the `ShouldQuote` example.

**Comment by TimSirmovics** [comment]
How would this work when there could be multiple record types being written?

**Comment by abrasat** [comment]
Is there actually any workaround to write only single quotes for a string column?

Right now only these 2 options are possible when writing a csv file:

```
"""Some string column""","""Some other string column""",1123,5.67,999,
```

or
```
Some string column,Some other string column,1123,5.67,999,
```

Would be possible to write a csv like this?
```
"Some string column","Some other string column",1123,5.67,999,
```

**Comment by AltruCoder** [comment]
@abrasat - I believe that is what Josh's [example](https://github.com/JoshClose/CsvHelper/issues/1503#issuecomment-617901689) does.

**Comment by abrasat** [comment]
With Josh's example I get the double (or better said triple) quotes (scenario 1)

**Comment by AltruCoder** [comment]
There has to be something else going on then.  I tried the example and I get scenario 3.

**Comment by AltruCoder** [comment]
If you output to the console, does it still do triple quotes?  I also didn't like how it quoted the two string headers so I added `&& context.HasHeaderBeenWritten` to the if statement.
```csharp
public class Program
{
    static void Main(string[] args)
    {
        var records = new List<Foo>
        {
            new Foo 
            { 
                SomeStringColumn = "Some string column", 
                SomeOtherStringColumn = "Some other string column",
                Id = 1123,
                DoubleProperty = 5.67D,
                IntProperty = 999
            }
        };
        using (var csv = new CsvWriter(Console.Out, CultureInfo.InvariantCulture))
        {
            csv.Configuration.ShouldQuote = (field, context) =>
            {
                var index = context.Record.Count;
                var type = ((PropertyInfo)context.WriterConfiguration.Maps.Find<Foo>().MemberMaps[index].Data.Member).PropertyType;
                if (type == typeof(string) && context.HasHeaderBeenWritten)
                {
                    return true;
                }

                return ConfigurationFunctions.ShouldQuote(field, context);
            };
            csv.WriteRecords(records);

            Console.ReadKey();
        }
    }
}

public class Foo
{
    public string SomeStringColumn { get; set; }
    public string SomeOtherStringColumn { get; set; }
    public int Id { get; set; }
    public double DoubleProperty { get; set; }
    public int IntProperty { get; set; }
}
```

**Comment by abrasat** [comment]
You are right, it works!
I was actually using the QuoteStringConverter from the [SO](https://stackoverflow.com/questions/56579848/csvhelper-configuration-shouldquote-return-true-for-only-fields-on-the-dto-whi) example

```
    csv.Configuration.TypeConverterCache.AddConverter<string>(new QuoteStringConverter());
```

but my mistake was that I forgot to add this line before setting the converter:
```
    csv.Configuration.ShouldQuote = (field, context) => false;
```

**Comment by abrasat** [comment]
It would be useful to have the option to decide for each column having the string type if or how to quote the values, not only globally for all string columns

**Comment by AltruCoder** [comment]
There was an example [here] (https://github.com/JoshClose/CsvHelper/issues/1221#issuecomment-457288093) for quoting specific columns.

**Comment by abrasat** [comment]
Thanks. How would this work when using the QuoteStringConverter instead of ShouldQuote ?
And also would be nice to get the column header names instead of the column index

**Comment by TimSirmovics** [comment]
> 
> 
> How would this work when there are multiple record types being written?

Still interested if this is possible.

**Comment by intraz** [comment]
@JoshClose the solution you gave [here](https://github.com/JoshClose/CsvHelper/issues/1503#issuecomment-617901689) for getting the current field's type only works when there is a type to be mapped.
This is not always the case (eg: I'm exporting a DataTable to CSV and using your code example from [here](https://github.com/JoshClose/CsvHelper/issues/1399#issuecomment-602758689)).
Would it be possible to add the original field type to the ShouldQuote delegate signature?

**Comment by JoshClose** [comment]
What are you doing that you need to know the type to know if the field needs to be quoted?

**Comment by intraz** [comment]
Thanks for the quick reply.
I have an integration requirement with an external system that all string values must be quoted.
I found a workaround for this (checking the type directly with the data table).
I still think it can be a helpful feature since CSV consumers (both humans and machines) can be very particular as to what they want (eg: a customer annoyed by Excel misinterpreting a decimal or a date is a regular occurrence that can be solved by quoting the values (with its own downside of losing the type inference by Excel)).

**Comment by JoshClose** [comment]
Is there a case where you couldn't quote all fields?

**Comment by TimSirmovics** [comment]
I have the same requirement, just string fields need to be quoted and no others.
I also have multiple record types.

**Comment by intraz** [comment]
Yes, I forgot to mention. I specifically should not quote any of the other
field types.

**Comment by JoshClose** [comment]
There is a feature request to add `ShouldQuote(bool)` to mappings (and attributes) to specify a field should always be quoted or not. This is probably a better idea than passing more information into the `ShouldQuote` callback. `ShouldQuote` is also called when doing `WriteField(string field)`, so there is no type in that case. This might be a good case to add that feature. https://github.com/JoshClose/CsvHelper/issues/1644

**Comment by intraz** [comment]
I saw that feature request and it's IMO only relevant for simple cases where the types are well defined and limited in size.
My code gets DataTables for reports from different sources representing different models and it has no knowledge about the contents so this solution will not help.
I do see your point regarding ```ShouldQuote``` (I dug through the code).

**Comment by JoshClose** [comment]
The type isn't known at the time that is called. https://github.com/JoshClose/CsvHelper/blob/8b555ec2cf5a918419f13f3f750e11956786209b/src/CsvHelper/CsvWriter.cs#L140

I'll have to think about this. Maybe I can add something to the map collection to easily get the info you're looking for.

**Comment by intraz** [comment]
I really appreciate that.
Would the map collection hold this info even if there is no concrete type used for records (like the DataTable based code I'm using)?
Again, for now, I have a workaround that seems to be working.

**Comment by JoshClose** [comment]
What do you think of this. Added `List<Type> IWriterRow.FieldTypes`. In `ShouldQuote` you can use `IWriterRow.Index` to get the current type.

```cs
ShouldQuote = (field, row) => row.FieldTypes[row.Index] == typeof(string);
```

You'll have access to the previous types then if needed also.

**Comment by JoshClose** [comment]
Maybe that's too confusing. Maybe it should just be `IWriterRow.FieldType` and it applies to the current field.

**Comment by TimSirmovics** [comment]
Could the field parameter be updated to an object which holds the `string` value and the `Type`?
In any case I'm really not too fussed, any solution that provides the type per field while working with multiple records is good.

**Comment by JoshClose** [comment]
`ShouldQuote` already has the `string field` as a parameter.

**Comment by TimSirmovics** [comment]
Yes.. I am suggesting if that could be replaced with an object, which still holds the string field, but also contains the Type.
Since you are debating on how best to include the field Type within an object that holds Row information I am suggesting maybe it is better located close to the field value that is already passed in.

**Comment by JoshClose** [comment]
Ah I see. I'll have to think about that.

**Comment by accessfreelancer** [comment]
Im getting ShouldQuote is read only on the latest version

![image](https://user-images.githubusercontent.com/51207026/105575770-f3d1d200-5d3b-11eb-8da5-743d8b9d4200.png)

**Comment by accessfreelancer** [comment]
Would this be the new way to set ShouldQuote to false?

![image](https://user-images.githubusercontent.com/51207026/105576115-a1de7b80-5d3e-11eb-98a7-c1ac22047eff.png)

**Comment by AltruCoder** [comment]
@accessfreelancer check out Josh's content here https://github.com/JoshClose/CsvHelper/issues/1664#issuecomment-764714249

**Comment by intraz** [comment]
> Ah I see. I'll have to think about that.

I like @TimSirmovics's suggestion for its clarity and future maintainability (if similar per-field requirements pop up), but like he said your suggestions are just fine and not at all confusing.

**Comment by JoshClose** [comment]
I'm opening this again so I don't lose this feature.

**Comment by JoshClose** [comment]
I changed `ShouldQuote` to `ShouldQuote(string field, Type fieldType, IWriterRow row)`.

This is in 22.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/22.0.0

**Comment by intraz** [comment]
Thank you Josh.

**Comment by ronenfe** [comment]
I don't understand how to convert  "(field, context) => true" after updating to latest nuget.

**Comment by JoshClose** [comment]
@ronenfe Do you mean changing from this
```cs
ShouldQuote = (_, _) => true
```
to this
```cs
ShouldQuote = (_, _, _) => true
```
?

**Comment by ronenfe** [comment]
yes, 
I had  :  
` using (var ms = new MemoryStream())
            {
                TextWriter tw = new StreamWriter(ms);
                var conf = new CsvConfiguration(CultureInfo.CurrentCulture)
                {
                    ShouldQuote = (field, context) => true
                };
                using (var csv = new CsvWriter(tw, conf))
                {
                    csv.WriteRecords(obj);
                }
                data = ms.ToArray();
            }`

**Comment by intraz** [comment]
change: `ShouldQuote = (field, context) => true`
to: `ShouldQuote = (field, fieldType, context) => true`

**Comment by recruz02** [comment]
Could use some help here @JoshClose . Every time I inspect the "fieldType" when iterating through my file, it's always returning as System.String. Am I accessing/checking it incorrectly?

![Uploading Screen Shot 2021-02-11 at 11.47.56 AM.png…]()

**Comment by JoshClose** [comment]
@recruz02 What method are you using to write?

**Comment by roman-ianchenko** [comment]
@JoshClose would be great to have in the "should quote" args the reference to current record and/or its type, f.e. when I have different record types processed by CsvWriter I want to check my custom attributes on current field.

**Comment by MYriad1993** [comment]
Is there a way to get access to PropertyInfo instead of FieldType?
I would like to use a custom attribute to mark field I want to get quoted. But I can't access it from the ShouldQuote lambda.
Or may be that would make sence to add a QuotedAttribute to the library to implement out-of-box solution.

**Comment by JoshClose** [comment]
No. You can get the field index though, which might help you. `args.Row.Index`

**Comment by MYriad1993** [comment]
Thanks, @JoshClose. I thought, this was a number of row. Your answer was helpful.

**Comment by abrasat** [comment]
@JoshClose : After a long time I am trying to update my application to the newest CsvHelper release. I used the [SO](https://stackoverflow.com/a/56581466/5027016) sample code with the custom QuoteStringConverter and adding it to the CsvWriter TypeConverterCache. How should that code be updated to get the same behavior with the newest 27.2.1 CsvHelper release?

**Comment by JoshClose** [comment]
Switch to using the `ShouldQuote` config.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    ShouldQuote = args => args.FieldType == typeof(string),
};
```

**Comment by abrasat** [comment]
@JoshClose Thanks, that solves the StringConverter in CsvWriter.
How can the DoubleConverter below be added to the TypeConverterCache? This does not compile anymore:
```
...
public class MyDoubleConverter : DefaultTypeConverter
{
...
        public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
        {
            ...
        }
        public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            ...
        }
}
...
using (var cw = new CsvWriter(...))
{
...
    // remove default double converter
    csvReader.Configuration.TypeConverterCache.RemoveConverter<double>();
    // override with custom double converter -> limit positions after decimal separator
    csvReader.Configuration.TypeConverterCache.AddConverter<double>(new MyDoubleConverter("0.##"));
...
}
```
How can the actual Record or HeaderRecord be now accessed in the CsvReader? This code does not compile anymore :
```
using (var csvReader = new CsvReader(...))
{
...
   string[] headerRow = csvReader.Context.HeaderRecord;
...
   string[] recordRowCols = csvReader.Context.Record;
...
}
```
How can be the AutoMap and RegisterClassMap methods from the IWriterConfiguration be called with the new release? I used to call them "on-the-fly", with a dynamically created type. I had something like this, does not compile anymore:
```
...
public sealed class EqDataRecInfoMap : ClassMap<EqDataRecInfo>
{
....
}
...
using (var cw = new CsvWriter(...))
{
   cw.Configuration.RegisterClassMap<EqDataRecInfoMap>();
...
   // create the new type
   Type dynamicType = CreateDynamicType(...);

   var classMap = cw.Configuration.AutoMap(dynamicType);
...
}
```

**Comment by JoshClose** [comment]
Mutable objects moved from configuration to the context. Things there were previously a pass-through to the parser are not accessed directly on the parser instead.

```cs
csvReader.Configuration.TypeConverterCache -> csvReader.Context.TypeConverterCache
csvReader.Context.HeaderRecord -> csvReader.HeaderRecord
csvReader.Context.Record -> csvReader.Parser.Record
cw.Configuration.RegisterClassMap -> cw.Context.RegisterClassMap
cw.Configuration.AutoMap -> cw.Context.AutoMap
```

There is a migration guide now also. https://joshclose.github.io/CsvHelper/migration/

**Comment by abrasat** [comment]
Great, thanks!
