### ISSUE TITLE
Error with delimiter !# with a field sinifhing by a !

### ISSUE THREAD

**Issue by li-stephanebeaud** [JoshClose/CsvHelper#1504]
**Describe the bug**
I have csv files with a !# delimiter.
Everything worked well until one of my field ends with a "!" character.

csvHelper don't recognize !!# as containing my delimiter.

I'm using CsvHelper 15.0.4 with .net framework 4.5

**To Reproduce**
Use a csv with !# delimiter and at least one field finishing by !

**Expected behavior**
each delimiter !# may be recognized as a delimiter.

**Screenshots**
![image](https://user-images.githubusercontent.com/59614824/79332003-592aa400-7f1c-11ea-8057-12abcb6ae4f1.png)

**Comment by JoshClose** [comment]
I'm able to reproduce this. I'll see if I can get a fix out soon.

**Comment by JoshClose** [comment]
This is fixed and in version 15.0.5 on NuGet.
