### ISSUE TITLE
Scientific Notation on decimals no longer works in 15.0.4

### ISSUE THREAD

**Issue by jtenos** [JoshClose/CsvHelper#1507]
**Describe the bug**
In version 15.0.0, a value like `1.2e-05` properly read into a decimal as 0.000012. In 15.0.4, this results in an error.

**To Reproduce**
Run the following code with NuGet package set at 15.0.0 and 15.0.4. I'm doing this with a .NET Core 3.1 Console application:

```
using CsvHelper.Configuration;
using System.Linq;
using System.Globalization;
using System.IO;

class Program {
    static void Main(string[] args) {
        var TEXT = @"a,b
1.2,3.4
1.2e-05,7.8";
        var reader = new CsvHelper.CsvReader(new StringReader(TEXT), new CsvConfiguration(CultureInfo.CurrentCulture));
        var foos = reader.GetRecords<Foo>().ToArray();
    }
}

public class Foo {
    public decimal a { get; set; }
    public decimal b { get; set; }
}
```

**Expected behavior**
The decimal value should be read.

**Additional context**
Here's the exception:

> CsvHelper.TypeConversion.TypeConverterException: 'The conversion cannot be performed.
>     Text: '1.2e-05'
>     MemberType: System.Decimal
>     TypeConverter: 'CsvHelper.TypeConversion.DecimalConverter''
> 
> This exception was originally thrown at this call stack:
> 	CsvHelper.TypeConversion.DefaultTypeConverter.ConvertFromString(string, CsvHelper.IReaderRow, CsvHelper.Configuration.MemberMapData)
> 	CsvHelper.TypeConversion.DecimalConverter.ConvertFromString(string, CsvHelper.IReaderRow, CsvHelper.Configuration.MemberMapData)
> 	CsvHelper.Expressions.RecordCreator.Create<T>()
> 	CsvHelper.Expressions.RecordManager.Create<T>()
> 	CsvHelper.CsvReader.GetRecords<T>()
> 	System.Collections.Generic.LargeArrayBuilder<T>.AddRange(System.Collections.Generic.IEnumerable<T>)
> 	System.Collections.Generic.EnumerableHelpers.ToArray<T>(System.Collections.Generic.IEnumerable<T>)
> 	System.Linq.Enumerable.ToArray<TSource>(System.Collections.Generic.IEnumerable<TSource>)
>     ConsoleApp18.Program.Main(string[]) in Program.cs

**Comment by JoshClose** [comment]
You'll need to update the `NumberStyles`. The default changed to what `decimal.TryParse` uses by default.

You can do this with attributes:

```cs
public class Foo
{
	[NumberStyles(NumberStyles.Number | NumberStyles.AllowExponent)]
	public decimal A { get; set; }
	[NumberStyles(NumberStyles.Number | NumberStyles.AllowExponent)]
	public decimal B { get; set; }
}
```

Or using a map:

```cs
public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.A).TypeConverterOption.NumberStyles(NumberStyles.Number | NumberStyles.AllowExponent);
		Map(m => m.B).TypeConverterOption.NumberStyles(NumberStyles.Number | NumberStyles.AllowExponent);
	}
}
```

Or you can change it globally for a `decimal` types:

```cs
csv.Configuration.TypeConverterOptionsCache.GetOptions<decimal>().NumberStyle = NumberStyles.Number | NumberStyles.AllowExponent;
```

**Comment by joefeser** [comment]
@jtenos @JoshClose Unless this did used to work and the default number style changed, I would say this issue can be closed.

**Comment by fredrikdev** [comment]
The above seem to have been moved to `.Context`. Anyway here's some code that works fine for me:

```c#
using (var file = new StreamReader(path)) {
	using (var reader = new CsvReader(file, CultureInfo.InvariantCulture)) {
		reader.Context.TypeConverterOptionsCache.GetOptions<decimal>().NumberStyles = NumberStyles.Number | NumberStyles.AllowExponent;
		
		if (!reader.Read() || !reader.ReadHeader())
			continue;
		
		while (reader.Read()) {
			var name = reader.GetField<string>("name");
			var numberwithexp = reader.GetField<decimal>("numberwithexp");
			...
		}
	}
}
```
