### ISSUE TITLE
When a different quote character is used in config, it invalidates the record with double quote (") character inside field 

### ISSUE THREAD

**Issue by rabiraj** [JoshClose/CsvHelper#1509]
Consider following example of csv

|field1|,|field2|
|val11|,|val12|
|val21|,|val"22"|

I have setup | character as quote character as following
CsvConfiguration config = new CsvConfiguration(CultureInfo.InvariantCulture);
config.Quote = '|';

I get BadDataFound for second row i.e. |val21|,|val"22"|
The " character in this case should have been ignored.

If I include the following code,
config.IgnoreQuotes = true;
then the values includes | characters even though config.Quote = '|';

**Comment by JoshClose** [comment]
There is also `Configuration.Escape` which is the character used to escape a quote inside a field. It defaults to `"`. The parser is seeing the `"` and thinking it's an escape char. Change your escape char to something else.

**Comment by rabiraj** [comment]
Thanks, that worked
