### ISSUE TITLE
PrepareHeaderForMatch in ClassMap doesn't work

### ISSUE THREAD

**Issue by Leon99** [JoshClose/CsvHelper#1511]
When I register a Func for PrepareHeaderForMatch via CsvReader.Configuration, it's all good. Once I move it to a class map and add via AutoMap, it doesn't work anymore. The ClassMap is initialized, it's just the Func is not called.
CsvHelper v15.0.5

**Comment by JoshClose** [comment]
Can you give me example code showing this failing?

**Comment by Leon99** [comment]
```

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		this.AutoMap(new CsvConfiguration(CultureInfo.InvariantCulture) {PrepareHeaderForMatch = (header, index) => header.ToLowerInvariant()});
	}
}

public class Foo
{
	public string Id { get; set; }
	public string Name { get; set; }
}

[TestClass]
public class CsvHelperBug
{
	[TestMethod]
	public void Reproduce()
	{
		using var reader = new StringReader(@"id,name
1,one
2,two");
		using var csv = new CsvReader(reader, CultureInfo.InvariantCulture);
		csv.Configuration.RegisterClassMap<FooMap>();
		var records = csv.GetRecords<Foo>();
	}
}
```

**Comment by JoshClose** [comment]
Do you need to use `AutoMap` in the mapping? If you're using `AutoMap` and aren't doing any explicit mapping, you don't need to map at all. 

The constructor overload of `AutoMap` that takes in configuration is really meant to only be used internally. I've tried to leave everything as open as possible so people can easily make changes to how things work.

The reason it's not working is because you're passing a new configuration into the `AutoMap`. This configuration isn't used by `CsvReader`. If you really wanted to do that, you'd have to pass the same configuration into the constructor of `ClassMap` and into the constructor of `CsvReader`.

Here is the intended way to use this.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("id,name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
	{
		csv.Configuration.PrepareHeaderForMatch = (header, index) => header.ToLowerInvariant();
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by Leon99** [comment]
Thanks for explanation @JoshClose. Does that mean that PrepareHeaderForMatch (or anything else that is set in the configuration class) can't be set via ClassMap?

**Comment by JoshClose** [comment]
It can be, but you should pass an existing instance into the map then.

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("id,name");
	s.AppendLine("1,one");
	s.AppendLine("2,two");
	// Create shared config.
	var config = new CsvConfiguration(CultureInfo.InvariantCulture);
	using (var reader = new StringReader(s.ToString()))
	// Pass config into CsvReader.
	using (var csv = new CsvReader(reader, config))
	{
		// Create map instance using config.
		var map = new FooMap(config);
		// Register map instance.
		csv.Configuration.RegisterClassMap(map);
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap(CsvConfiguration config)
	{
		config.PrepareHeaderForMatch = (header, index) => header.ToLowerInvariant();
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```
