### ISSUE TITLE
Escaped quotes aren't properly recognized

### ISSUE THREAD

**Issue by abihari** [JoshClose/CsvHelper#1518]
**Bug Description**
Using default settings for *Quote* and *Escape* values, I have the following line being parsed, but it throws a BadDataException and the ReadingContext has IsFieldBad set.

**"Fabrikam, Inc.",Account Number,000-1130-00,ApexDesk Elite 16"" Series 71,Active**

In the original string, the " was supposed to be after 71, but I figured being close to the comma delimiter might cause issues so moved it away with no change.

My reading of the RFC4180 spec indicates that this is the right way of escaping the double quote.

**Expected behavior**
The row should not throw an error

**Comment by AltruCoder** [comment]
That is the correct way to escape double quotes, but according to [RFC4180](https://tools.ietf.org/html/rfc4180)

> If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.

You need to also enclose the field that contains escaped double quotes with double quotes.

**Comment by abihari** [comment]
Yes, you are correct, totally misread that statement. Thanks for the quick response.
