### ISSUE TITLE
RegisterClassMap should be an option when creating an configuration object.

### ISSUE THREAD

**Issue by SuperDaveOsbourne** [JoshClose/CsvHelper#1520]
It would be nice to be able to have a configuration object where the RegisterClassMap call was available when creating it.

             var configuration = new 
                                   CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = true,
                Delimiter = "|",
                IgnoreBlankLines = true,
                HeaderValidated = null,
                MissingFieldFound = null
                RegisterClassMap<DataMap>() // This is not accessible currently.
            };

Am I missing a reason on why it shouldn't be included?

**Comment by ManuelRin** [comment]
Hi @SuperDaveOsbourne 

Unfortunately that's not possible because method calls are not allowed in C# object initializer syntax. That's a limitation of the C# language currently.

Please note that C# object initializer syntax is just syntactic sugar. This means that
```
var configuration = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
    {
        HasHeaderRecord = true,
    };
```
is compiled into exactly the same as

```
var configuration = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture);
configuration.HasHeaderRecord = true;
```
Therefore you need to call `RegisterClassMap` like that:
```
configuration.RegisterClassMap<DataMap>();
```
Is there any particular benefit you'd expect if your suggested syntax were allowed?

**Comment by SuperDaveOsbourne** [comment]
For me it would be cleaner code as all settings would be in one object I could inject later. I am working on kind of a universal decoder for old equity stock data there might be 50 permutations that I might have when done.

**Comment by JoshClose** [comment]
As @ManuelRin said, this is a C# language issue. You can make the call to register directly after though.

```cs
var configuration = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	HasHeaderRecord = true,
	Delimiter = "|",
	IgnoreBlankLines = true,
	HeaderValidated = null,
	MissingFieldFound = null
};
configuration.RegisterClassMap<DataMap>();
```

It would be possible to add another parameter to the constructor that takes in a map or multiple maps, but how is that any different that just calling the method directly after?

**Comment by SuperDaveOsbourne** [comment]
Mostly because of my OCD, I either want to have them all in the initializer or all inline. If its right to have an initializer then everything should be able to be in there.  Of course that is all on me and I recognize the limitations the C# has with the methods. I had forgot working on Python stuff for the last year.

**Comment by JoshClose** [comment]
C# is getting a lot of nice stuff though. I work mostly in JavaScript which is really flexible also, and a lot of that has been coming to C#.
