### ISSUE TITLE
How to write all DateTime fields as ISO 8601 strings?

### ISSUE THREAD

**Issue by eparizzi** [JoshClose/CsvHelper#1521]
I'm writing CSV out from `IEnumerable<dynamic>` objects. I do not know how many DateTime fields these objects can have, nor its names.

Is there a way to tell CsvWriter to write all DateTime objects as ISO 8601 strings?
https://dotnetfiddle.net/1ng5W9
I feel this should be obvious and easily achievable. But I couldn't find anything here or in StackOverflow.

**Comment by JoshClose** [comment]
You can globally configure the format for `DateTime`.

```cs
csv.Configuration.TypeConverterOptionsCache.GetOptions<DateTime>().Formats = new string[] { "o" };
```

**Comment by 0xced** [comment]
For the record, it must now be done through the `Context` object instead of the configuration:

```csharp
csv.Context.TypeConverterOptionsCache.GetOptions<DateTime>().Formats = new string[] { "o" };
```
