### ISSUE TITLE
Regression in 15.0.5- Unable to parse nullable decimal field with decimal scientific notation values like 1.0E+5

### ISSUE THREAD

**Issue by srigumm** [JoshClose/CsvHelper#1524]
**Describe the bug**
12.2.1 release used to support parsing decimal values with scientific notations.
I upgraded to latest version 15.0.5, now I am getting a read exception.

"{"The conversion cannot be performed.\r\n    Text: '1.00E+05'\r\n    MemberType: System.Nullable`1[[System.Decimal, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]\r\n    TypeConverter: 'CsvHelper.TypeConversion.NullableConverter'"}"

![image](https://user-images.githubusercontent.com/44202047/81019185-1b8eac00-8e34-11ea-820c-ec0d14a4f225.png)

**Comment by AltruCoder** [comment]
Check out Josh's answer here https://github.com/JoshClose/CsvHelper/issues/1507

**Comment by vodesoft** [comment]
A little update for Josh's answer. Use a separate line for nullable decimal (decimal?) as well:
`csv.Configuration.TypeConverterOptionsCache.GetOptions<decimal?>().NumberStyle = NumberStyles.Number | NumberStyles.AllowExponent;`

**Comment by joefeser** [comment]
@srigumm @JoshClose Unless this did used to work and the default number style changed, I would say this issue can be closed.
