### ISSUE TITLE
Use buffer pool to improve read performance

### ISSUE THREAD

**Issue by Yonisha** [JoshClose/CsvHelper#1530]
Any plans to use pooled buffers to reduce char array allocations in CsvFieldReader?
Microsoft provides [System.Buffers.ArrayPool<T>](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1?view=netcore-3.1) (supported also in .NET despite what the documentation states) with very simple API.

This can dramatically improve performance by reducing allocated buffers.

**Comment by Yonisha** [comment]
@JoshClose do you think it can improve performance?

**Comment by JoshClose** [comment]
I have a version of the parser that uses `MemoryPool<T>`, `Memory<T>` and `Span<T>` that drastically improves performance. I haven't found the time to integrate it in yet though.

**Comment by Yonisha** [comment]
Any plans/ETA? it will be very helpful for many consumers of this nuget.

**Comment by JanEggers** [comment]
can you push your branch? I would love to support you with spanification to speed things up

**Comment by JoshClose** [comment]
This performance improvement was added in version 20.0.0. It's not actually using `Memory` or `Span`. I found that you can use a single buffer and copy from it to itself in a single `Array.Copy`. The source and destination are the same buffer instance. This ended up being way faster than using `Memory` and `Span`.

**Comment by JanEggers** [comment]
thx for letting me know then i will do some experiments on my own. I still see many string allocations

**Comment by JoshClose** [comment]
Where at? Maybe I can explain what I've tried.

Also, check this out. https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers
