### ISSUE TITLE
Exception during run time ould not load file or assembly 'CsvHelper, Version=15.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by aaronavi** [JoshClose/CsvHelper#1533]
**Describe the bug**
Hello
During runtime i get the following error:
Could not load file or assembly 'CsvHelper, Version=15.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'. The system cannot find the file specified.
I am loading a class which uses the CsvHelper
And getting the exception above

Mu project is a .net core project and i am loading my projects dll dynamically

using 
the following code
IPluginModule plugin = (IPluginModule)Activator.CreateInstance(moduleClassType);
Activator is from Assembly System.Runtime, Version=4.2.2.0

i am using the latest version of CsvHelper version 15.0.5

Please help
Thanks

**Comment by luisrodge** [comment]
Hi, did you ever resolve this issue? I'm running into the same problem.

**Comment by aaronavi** [comment]
Hi
Yes i did, the only way i found to resolve it was to mark the project to publish all the dll's to the target folder.
use this property: <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
Regards

**Comment by rossthemusicteacher** [comment]
I aaronavi, I don't understand your solution. Can you please go into a little more depth? How did you fix this?
