### ISSUE TITLE
Extremely bad performance reading wide line

### ISSUE THREAD

**Issue by Xantrul** [JoshClose/CsvHelper#1535]
**Describe the bug**
When we get CSV with very wide lines, it takes CsvReader a very long time to `.Read()` them. For example for the sample repro csv file I created it took 1 hour and 37 minutes to complete reading of the single line in that file (120 MB).

**To Reproduce**
1. Open attached file in CsvReader and call `.Read()` method on it.
[wide_csv.zip](https://github.com/JoshClose/CsvHelper/files/4732943/wide_csv.zip)

**Expected behavior**
Given the size of the line, I would expect it to take a few minutes to complete the read, but not that long.

**Additional context**
* I looked though Issues history and google results, but found no similar reports.
* Would it be possible to improve performance by tweaking some settings? I played with all the settings that might be relevant, but no luck so far.
* Repro was verified with CsvHelper 15.0.5
* We deal with Postgres logs that include queries, and sometimes these queries can be very long. The line that triggered investigation was 146 MB. But even much shorter lines can take minutes to process once they are long enough
* Profiling shows that 99.6% of time is spent in `CsvFieldReader.FillBuffer` method
* [File with model matching repro csv file](https://github.com/tableau/Logshark/blob/master/LogShark/Plugins/Postgres/PostgresCsvMapping.cs)
* [The actual code that encountered the problem](https://github.com/tableau/Logshark/blob/master/LogShark/LogParser/LogReaders/CsvLogReader.cs)
* Simple repro code I used:
```
var csvConfig = new CsvConfiguration(CultureInfo.CurrentCulture)
{
    HasHeaderRecord = false
};
using var inputReader = new StreamReader(inputPath);
using var csv = new CsvReader(inputReader, csvConfig);
var elapsed = Stopwatch.StartNew();
while (csv.Read())
{
    var record = csv.GetRecord<PostgresCsvMapping>();

    if (elapsed.ElapsedMilliseconds > 1000)
    {
        Console.WriteLine($"Line {lineNumber} took {elapsed.Elapsed}");
    }
    elapsed.Restart();
}
```

P.S. I've been using CsvHelper for years in multiple projects and loving it! Thank you for keeping it going! 😃

**Comment by Xantrul** [comment]
Looks like cranking `BufferSize` in config does the trick. Setting it to 2097152 allows same line to be processed in under 10 seconds, and 20971520 results in less than 5 seconds read.

**Comment by JoshClose** [comment]
Glad you found a fix! There was some work done on having hundreds of fields in the past to make it fast.
