### ISSUE TITLE
v14 / v15 documentation

### ISSUE THREAD

**Issue by ellenhutchings** [JoshClose/CsvHelper#1544]
The documentation hasn't been updated since v13, which makes checking for breaking changes or resolving them difficult.

**Comment by michaelkhalsa** [comment]
I would like to make the same request. I update from version early 20 something to the latest (i think it is version 37), and there are quite a few breaking changes (and many that did not need to be breaking). Most of them i figured out, however some i cannot and there is not a clear mapping to the stripe api. Some real world examples would be nice.

**Comment by JoshClose** [comment]
There was an issue with the library I was using for the docs site. It's fixed now and docs are updated.
