### ISSUE TITLE
Removing bit confusing CSV parsing restrictions and issues

### ISSUE THREAD

**Issue by iatsdmy** [JoshClose/CsvHelper#1546]
Hello,

First of all, thank you for creating CsvHelper!
I just wanted to communicate some suggestions / ideas which can hopefully make it even better.
Thus, currently for the class to be parsed from csv it is required that this class:
1. Have all relevant members having set method (either private or public).
2. Have default constructor.

And while error message on default constructor absence is quite clear, the requirement for a set methods can be quite confusing and it takes time to figure out what is happening, because if property does not have a set method it seems to be just ignored... Furthermore, the function checking this is CsvReader.CanRead(), which name is slightly confusing given that it checks the existence of set method.

Overall, I am not sure why there are these restrictions (e.g. other products doing somewhat similar things like Dapper do not seem to have these). Thus, what I would expect is:
1. If there is no set method, assign such get-only property via GetBackingField().SetValue(...).
2. If there is no default constructor, use FormatterServices.GetSafeUninitializedObject(type). One can alternatively also use Json constructor if present and pass properties to it, but thats a bigger change probably.

Is there some specific reason (e.g. performance or backwards compatibility) that this is not done this way?

P.S. Also that would be handy to be able to specify general type converters for certain types of objects in csv configuration, not only all properties and exclusively for each one as currently.

Please let me know whether this makes sense to you.

Best regards,
Dima

**Comment by JoshClose** [comment]
Sorry, didn't see this issue until now.

All these features already exist. 

CsvHelper will choose the constructor with the most parameters. You can change this by `CsvConfiguration.GetConstructor` to choose whichever you like. In the latest versions you can set attributes on constructor parameters, or use a ClassMap to map constructor parameters.

You can set global settings for most things. Here is how you'd do that for a type converter.

```cs
Context.TypeConverterCache.AddConverter<int>(new MyIntConverter());
```

Let me know if I missed anything.
