### ISSUE TITLE
ConvertUsing IReaderRow overload does not ouput row number as expected when writing files

### ISSUE THREAD

**Issue by S1r-Lanzelot** [JoshClose/CsvHelper#1550]
**Describe the bug**
When using the IReaderRow ConvertUsing overload to retrieve the RawRow integer, the expression does not populate the field as expected, instead it will output the original source data without the expression applied.

**To Reproduce**
`Map(m => m.TestColumnTwo).Index(1).Name("Non Working Column 2").ConvertUsing(r => "Row Number: "+ r.Context.RawRow.ToString());`

**Expected behavior**
The row number would be populated in the "Non Working Column 2" field

Repo: 
https://github.com/S1r-Lanzelot/CsvHelperTest

Code to reproduce:
https://github.com/S1r-Lanzelot/CsvHelperTest/blob/master/CsvHelperTest/Program.cs

**Comment by JoshClose** [comment]
There are 2 overloads for `ConvertUsing`. One is for reading which gives you the row. The other is for writing which gives you the record, in this case `Test`. Your map on `TestColumnOne` is using the record and grabbing columns from it, so this is one that is used when writing. Your map on `TestColumnTwo` is passing the row in which means is used when reading. Intellisense doesn't do a good job an differentiating the two. I believe there is a feature request out there to change the naming since it's easy to mess up. One sure way of knowing which you're doing is to explicitly type the variable.

```cs
ConvertUsing((Test r) => r.TestColumnOne + " " + r.TestColumnTwo);
ConvertUsing((IReaderRow r) => "Row Number: " + r.Context.RawRow.ToString());
```

If you change the second map there for writing, you won't have the `Context` available to you.

**Comment by S1r-Lanzelot** [comment]
OK - thank you for explanation. For anyone else down the road who thinks they can do this... just use a local variable to track index while writing instead.

**Comment by ashokgovindaraj** [comment]
HI Josh Close,

I got this error.

Cannot convert type 'CsvHelper.ConvertToStringArgs<AccessUser>' to 'CsvHelper.IReaderRow' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion

"return (row as IReaderRow)?.Context.HeaderRecord" How I can convert this line?

This is my code
 Map(m => m.FacialImages).Convert(row =>
            {
                **return (row as IReaderRow)?.Context.HeaderRecord**
                    .Where(header => header.StartsWith("FacialImage"))
                    .Select(header =>
                    {
                        return new BioFacialImage()
                        {
                            FacialImage = row.Row.GetField<string>(header)
                        };
                    })
                    .ToList()
                    .Where(value => !string.IsNullOrWhiteSpace(value.FacialImage))
                    .ToList();
            });

Thanks in advance.

**Comment by JoshClose** [comment]
The `Convert` method now passes an args parameter of type `ConvertToStringArgs`. Change to `Convert(args =>` and then reference row `args.Row`.

**Comment by ashokgovindaraj** [comment]
Thanks for your reply,
I using convert method but issue is I need to convert to **CsvHelper.IReaderRow**. 

I don't know, how to convert to **IReaderRow**

This is my old code version is 15.0.9:

**return (row as IReaderRow)?.Context.HeaderRecord**

![image](https://user-images.githubusercontent.com/76514701/153967939-77e15390-101b-4073-ac20-75ea6ec9402a.png)

Thank you.

**Comment by ashokgovindaraj** [comment]
Got it. Thank you for your help.
