### ISSUE TITLE
IAsyncEnumerable 2 times slower to enumerate than a regular IEnumerable?

### ISSUE THREAD

**Issue by SpiritBob** [JoshClose/CsvHelper#1560]
What the hell?

I get it that you leverage the async-await flow, which means if done correctly, no thread is ever blocked, but I'd gladly block a thread to do the IO if it meant up to 2x performance increase in speed.

What is happening in the lower levels? You can easily test this.

Just call `CsvReader.GetRecordsAsync<YourObject>()` and enumerate, versus `CsvReader.GetRecords<YourObject>()` and enumerate.

I feel like there's some fake-async going on, because there's no way this gets slowed down this much from the over-heads of thread-switching/context switching.

Tested on a Console Application, by running the process on a Thread pool thread (Main Console thread Block-waiting for it to finish)

**Comment by JoshClose** [comment]
Does increasing the buffer size significantly make a difference? The only place async happens is reading from the `Stream` into the buffer. https://github.com/JoshClose/CsvHelper/blob/8185f5d1bf0cfe869fb9d9dab13a5dbdd1041956/src/CsvHelper/CsvFieldReader.cs#L117

**Comment by SpiritBob** [comment]
@JoshClose setting the buffer size to a higher value significantly increased the speed.

Reading 410,000 lines of csv took ~7 seconds synchronously, and now only ~9 seconds asynchronously. This seems about right. Thoughts?

**Comment by joefeser** [comment]
@SpiritBob even it being an IFormFile, it can be backed by any stream, network, file and so forth. Are you reading from the disk or are you taking this as an HTTP request. I am going to guess there is not a buffer that is backing it.

I would test this by using a BufferedStream and set the min to at least 64-128k. We drastically sped up our app that was performing a lot of reads from a network share.

**Comment by SpiritBob** [comment]
@joefeser it's a simple HTTP request in ASP NET Core 3.1. I believe if the file is less than a certain size, it's stored in the memory, otherwise it's stored in the hard disk? I forgot the exact numbers, feel free to enlighten me. 

Was your approach applied to that framework? If so, how?

**Comment by joefeser** [comment]
@SpiritBob Network streams should never be used for performance benchmarks. There is no telling how many packet analyzers are in the stream. Especially on a corporate network.

**Comment by SpiritBob** [comment]
@joefeser sorry, if you were referring to my actual testing environment, I believe I read the file from the disk, but my practical use case is ASP NET Core.
