### ISSUE TITLE
CsvReader.GetField wrong parsing

### ISSUE THREAD

**Issue by dario-hd** [JoshClose/CsvHelper#1565]
**Describe the bug**
We are currently using the 15.0.1 version which for a string like `100,50` is throwing a `FormatException` when using `CsvReader.GetField<decimal>(...)`. Later versions do not throw such exception but are parsing the string to the `10050` decimal. Is it intended behavior?

**Expected behavior**
Parsing the string `100,50` throws a `FormatException.`

**Comment by dario-hd** [comment]
@JoshClose do you have an idea?

**Comment by JoshClose** [comment]
In `15.0.3` there was a bug fix `Updated default number styles for DecimalConverter and DoubleConverter to match MS's recommendations.` https://joshclose.github.io/CsvHelper/change-log

Here are the changes. https://github.com/JoshClose/CsvHelper/commit/e1d3d06d34f3ce96bfe704222dcd538f5c03cec2?w=1

Basically, you just need to change your number styles.

You can set them globally like this.

```cs
csv.Configuration.TypeConverterOptionsCache.GetOptions<decimal>().NumberStyle = NumberStyles.Number;
```

**Comment by dario-hd** [comment]
Thanks! In my case I had to use:

```
csv.Configuration.TypeConverterOptionsCache.GetOptions<decimal>().NumberStyle = NumberStyles.AllowDecimalPoint;
```
