### ISSUE TITLE
CsvWriter does not respect class maps

### ISSUE THREAD

**Issue by alstrw** [JoshClose/CsvHelper#1569]
When writing to a CSV, CsvWriter will not respect class maps and maps properties even when they are ignored:

````
public async Task<byte[]> WriteSalesToMemoryAsync<T>(IEnumerable<Foo> bar) where T : Baz
{
    using (var ms = new MemoryStream())
    using (var sw = new StreamWriter(ms))
    using (var csv = new CsvWriter(sw, CultureInfo.GetCultureInfo("en-GB")))
    {
        csv.Configuration.RegisterClassMap(new FooBarMap());
        await csv.WriteRecordsAsync(bar);
        return ms.ToArray();
     }
}
````

FooBarMap:
````
public class FooBarMap: ClassMap<Foo>
    {
        public FooBarMap()
        {
            AutoMap(CultureInfo.GetCultureInfo("en-GB"));
            Map(m => m.Property1).Ignore();
            Map(m => m.Property2).Ignore();
            Map(m => m.Property3).Ignore();
            Map(m => m.Property4).Ignore();
            Map(m => m.Property5).Ignore();
            Map(m => m.Property6).Ignore();
            Map(m => m.Property7).Ignore();
        }
    }
````

All of the "ignored" properties are coming out in the byte array and end up in the CSV file.

**Comment by alstrw** [comment]
[This](https://github.com/JoshClose/CsvHelper/issues/722) issue from 2017 suggests mapping is ignored for writing and only is used when reading.

This is a large oversight and the docs do not mention anything about this.

Perhaps it would be worth clarifying that mapping only works for reading explicitly.

**Comment by derek-baker** [comment]
Wow. 1000% agree.

**Comment by JoshClose** [comment]
There may have been a bug before or something, as this is not the case now for sure.
