### ISSUE TITLE
Types that inherit IEnumerable cannot be auto mapped. 

### ISSUE THREAD

**Issue by chucklu** [JoshClose/CsvHelper#1570]
**Describe the bug**
Try to sanitize an existing csv file to avoid [CSV Injection (Formula Injection)](https://github.com/swisskyrepo/PayloadsAllTheThings/tree/master/CSV%20Injection)
Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single rec
I did not call GetRecord or WriteRecord, what I am using is WriteRecords method. And the WriteRecords method call WriteHeader method, and the automap method encounter the exception
```C#
if (context.WriterConfiguration.Maps[type] == null)
			{
				context.WriterConfiguration.Maps.Add(context.WriterConfiguration.AutoMap(type));
			}
```

**To Reproduce**
```C#
var path = @"C:\Users\clu\Downloads\test.csv";
			var path2 = @"C:\Users\clu\Downloads\test2.csv";
			var array = File.ReadAllLines(path);
			using (var writer = new StreamWriter(path2, append: false))
			{
				CsvWriter csvWriter = new CsvWriter(writer, CultureInfo.InvariantCulture);
				csvWriter.Configuration.SanitizeForInjection = true;
				csvWriter.WriteRecords(array);
				csvWriter.Flush();
				writer.Flush();
			}
```

**Expected behavior**
sanitize the csv file and output the result file

**Screenshots**
```none
CsvHelper.Configuration.ConfigurationException
  HResult=0x80131500
  Message=Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?
  Source=CsvHelper
  StackTrace:
   at CsvHelper.Configuration.ClassMap.AutoMap(CsvConfiguration configuration) in C:\workspace\GitHub\Others\CsvHelper\src\CsvHelper\Configuration\ClassMap.cs:line 152
   at CsvHelper.Configuration.CsvConfiguration.AutoMap(Type type) in C:\workspace\GitHub\Others\CsvHelper\src\CsvHelper\Configuration\CsvConfiguration.cs:line 511
   at CsvHelper.CsvWriter.WriteHeader(Type type) in C:\workspace\GitHub\Others\CsvHelper\src\CsvHelper\CsvWriter.cs:line 312
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records) in C:\workspace\GitHub\Others\CsvHelper\src\CsvHelper\CsvWriter.cs:line 521
   at CsvHelper.Tests.Serializing.SanitizationTests.QuoteTest() in C:\workspace\GitHub\Others\CsvHelper\tests\CsvHelper.Tests\Serializing\SanitizationTests.cs:line 40

  This exception was originally thrown at this call stack:
    CsvHelper.Configuration.ClassMap.AutoMap(CsvHelper.Configuration.CsvConfiguration) in ClassMap.cs
    CsvHelper.Configuration.CsvConfiguration.AutoMap(System.Type) in CsvConfiguration.cs
    CsvHelper.CsvWriter.WriteHeader(System.Type) in CsvWriter.cs
    CsvHelper.CsvWriter.WriteRecords<T>(System.Collections.Generic.IEnumerable<T>) in CsvWriter.cs
    CsvHelper.Tests.Serializing.SanitizationTests.QuoteTest() in SanitizationTests.cs
```

**Comment by chucklu** [comment]
The content of csv file is as following
```none
# pop a calc
DDE ("cmd";"/C calc";"!A0")A0
@SUM(1+1)*cmd|' /C calc'!A0
=2+5+cmd|' /C calc'!A0
```

**Comment by naeemgittham** [comment]
Were you able to solve your issue? I am having a similar issue while trying to WriteRecords to memory stream.

**Comment by brandonsmith86** [comment]
Same problem here.  Any solution?

**Comment by chucklu** [comment]
```C#
     public void Test20210831_001()
        {
            //https://github.com/JoshClose/CsvHelper/issues/1570
            var folder = @"C:\workspace\Company\Test\2021\0831";
            var path = Path.Combine(folder, "test.csv");
            var path2 = Path.Combine(folder, "test2.csv");
            var array = File.ReadAllLines(path);

            CsvConfiguration csvConfiguration = new CsvConfiguration(CultureInfo.InvariantCulture);
            csvConfiguration.SanitizeForInjection = true;
            csvConfiguration.HasHeaderRecord = false;

            using (var writer = new StreamWriter(path2, append: false))
            {
                CsvWriter csvWriter = new CsvWriter(writer, csvConfiguration);
                foreach (var field in array)
                {
                    csvWriter.WriteField(field);
                    csvWriter.NextRecord();
                }
                csvWriter.Flush();
                writer.Flush();
            }
        }
```

**Comment by chucklu** [comment]
@brandonsmith86  According the documentation https://joshclose.github.io/CsvHelper/getting-started/, you'd  better define a class object to do the mapping.
And make sure you did  not pass a IEnumerable variable to WriteRecords method.

Previously I am using [File.ReadAllLines](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readalllines?view=net-5.0) get a string array of file content. And [Array class](https://docs.microsoft.com/en-us/dotnet/api/system.array?view=net-5.0) inherit the IEnumerable interface. 

Maybe you can show me your code, how did you use CsvHelper to write data.

**Comment by brandonsmith86** [comment]
@chucklu My problem was passing IEnumerable.  I ended up enumerating myself and using WriteField instead.

**Comment by AltruCoder** [comment]
I have found that issue with `IEnumerable<string>`.  `IEnumerable<int>` or pretty much any other object works just fine.  I can think of a couple of workarounds.  

Convert your string array to an `IEnumerable` of anonymous type and then use that in `csvWriter.WriteRecords(records);`
```csharp
var array = File.ReadAllLines(path);
var records = array.Select(a => new {a});
```

The other way would be to read the file in with `CsvReader` as an dynamic object and then write that back out again.
```csharp
 void Main()
{
	var data = new StringBuilder();
	data.AppendLine("# pop a calc");
	data.AppendLine("DDE (\"cmd\";\"/C calc\";\"!A0\")A0");
	data.AppendLine("@SUM(1+1)*cmd|' /C calc'!A0");
	data.AppendLine("=2+5+cmd|' /C calc'!A0");

	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		HasHeaderRecord = false,
		SanitizeForInjection = true,
		Mode = CsvMode.NoEscape
	};

	using (var streamReader = new StringReader(data.ToString()))
	using (var reader = new CsvReader(streamReader, config))
	{
		var records = reader.GetRecords<dynamic>();
		
		using (var writer = new CsvWriter(Console.Out, config))
		{
			writer.WriteRecords(records);
		}
	}	
}
```

**Comment by 00zgit** [comment]
CsvHelper.Configuration.ConfigurationException
  Message=Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?


`internal static string CsvToString()
        {
            using var reader = new StreamReader(SharedApplicationPaths.CsvPath);
            using var csv = new CsvReader(reader, config);
            csv.Read();
            csv.ReadHeader();
            return csv.GetRecord<string>();
        }`
        
        Excuse me, folks. I would like to know where is the error here.

**Comment by 00zgit** [comment]
Folks, excuse me. I would like to know what I am doing wrong here. I am trying to use auto mapper and just wants to write a single record.

```
        internal static void FNRHToCsv(FNRH ficha)
        {
            using var writer = new StreamWriter(SharedApplicationPaths.CsvPath);
            using var csv = new CsvWriter(writer, config);
            csv.WriteRecord(ficha);
        }
```

When i try to read, 

```
internal static string CsvToString()
        {
            using var reader = new StreamReader(SharedApplicationPaths.CsvPath);
            using var csv = new CsvReader(reader, config);
            csv.Read();
            csv.ReadHeader();
            return csv.GetRecord<string>();
        }
```

it gives the exception "Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a...".
