### ISSUE TITLE
Exporting newly created CSV file to API Controller

### ISSUE THREAD

**Issue by zlavoie** [JoshClose/CsvHelper#1574]
Hi,

I am looking how to write a list of objects to a CSV file from within one of my services, then return this data to the API controller where I can return the CSV file to the frontend to be downloaded by the user. 

For Example if I had a service:

public class ExportService 
{

     public byte[] ExportData()
     {
            using (var writer = new StreamWriter("ExportData.csv"))
            using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
            {    
                csv.WriteRecords(records);
            }

           return ???
     }
}

What gets returned to the API so I can successfully send the newly created CSV to the frontend?

**Comment by AltruCoder** [comment]
Does this answer your question?
https://stackoverflow.com/questions/55085778/asp-net-web-api-csv-helper-writing-to-the-stream-doesnt-work/55185240#55185240

**Comment by zlavoie** [comment]
yes that does, thanks!
