### ISSUE TITLE
When DetectColumnCountChanges enabled, it uses the wrong number of columns to check

### ISSUE THREAD

**Issue by junalmeida** [JoshClose/CsvHelper#1579]
**Describe the bug**
When the file has headers and the option `DetectColumnCountChanges` is enabled, the library uses the first record's column count instead of the header's column count to do the check.

**To Reproduce**
1. Create a CSV file with a header and 10 records. 
2. Make only the first record (the data, not the header) have one extra column.
3. Read the header using `ReadHeader`, then read all the file collecting exceptions in a try-catch block.
4. It collects 9 exceptions, indicating all the remaining rows are incorrect except the first record.

**Expected behavior**
It should collect only one exception indicating the first record has invalid number of columns.

**Comment by JoshClose** [comment]
This bug seems to have been fixed from other changes.

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("Id,Name\r\n");
    s.Append("1,one,foo\r\n");
    s.Append("2,two\r\n");
    s.Append("3,three\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        DetectColumnCountChanges = true,
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, config))
    {
        csv.Read();
        csv.ReadHeader();
        try
        {
            while (csv.Read())
            {
            }
        }
        catch
        {
            csv.Parser.RawRecord.Dump();
        }
    }
}

private class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
Output:
```
1,one,foo\r\n
```
