### ISSUE TITLE
First data row in CSV ignored

### ISSUE THREAD

**Issue by mathewhiley** [JoshClose/CsvHelper#1582]
Hi There,

I have an issue using CsvHelper v15.0.5 that I would appreciate some feedback on:

**The data input file**

I have the following CSV input file with header row plus 4 rows of comma-delimited data:

OrganisationId,FirstName,FamilyName,Username,GroupName,IsDefaultOrg
38ad3542-a79f-4f43-bdd2-2eabf9ef5707,name1,surname1,name1@email.com,Managers,TRUE
38ad3542-a79f-4f43-bdd2-2eabf9ef5707,name2,surname2,name2@email.com,Managers,TRUE
38ad3542-a79f-4f43-bdd2-2eabf9ef5707,name3,surname3,name3@email.com,Managers,TRUE
38ad3542-a79f-4f43-bdd2-2eabf9ef5707,name4,surname4,name4@email.com,Managers,TRUE

**The c# code**

I have created the following class to serialise the data (properties exactly match the headers in csv):

    public class UserMembership
    {
        public string OrganisationId { get; set; }
        public string FirstName { get; set; }
        public string FamilyName { get; set; }
        public string Username { get; set; }
        public string GroupName { get; set; }
        public string IsDefaultOrg { get; set; }
    }

I have the following c#.Net code running in a console app to read in the csv and simply output the usernames found within it:

```
private static async Task InsertUsersFromCSV(string filename)
{
	using (var reader = new StreamReader("InputFiles\\" + filename))
	using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
	{
		var users = csv.GetRecords<UserMembership>();
		if (users != null && users.Any())
		{
  			foreach (var user in users)
			{
				if (!string.IsNullOrEmpty(user.Username)
					Console.WriteLine(user.Username);
				}					
			}
		}
	}
}
```
**The problem:**
When I run this code the output is always missing the first data row as follows:
name2@email.com
name3@email.com
name4@email.com

**The workaround**
If I add a blank row (using excel, meaning a row of commas) beneath the header row and run it then I do see all 4 data rows returned:
name1@email.com
name2@email.com
name3@email.com
name4@email.com

**The Question**
Please confirm if this is a bug or am I doing something wrong?

Kind regards,
Mat

**Comment by JoshClose** [comment]
CsvHelper is forward only. When you call `.Any()` it's reading in the header and the first row, and since there is a row, it stops. Then you read the records, which is the rest of the records.

You should be able to ignore the `if` statement. `GetRecords` return an `IEnumerable` that isn't null. If you loop an empty `IEnumerable`, it will just have zero iterations.

**Comment by mathewhiley** [comment]
Excellent thanks!

Sent from my iPhone

On 22 Sep 2020, at 16:55, Josh Close <notifications@github.com> wrote:

﻿

CsvHelper is forward only. When you call .Any() it's reading in the header and the first row, and since there is a row, it stops. Then you read the records, which is the rest of the records.

You should be able to ignore the if statement. GetRecords return an IEnumerable that isn't null. If you loop an empty IEnumerable, it will just have zero iterations.
