### ISSUE TITLE
NuGet package contains unnecessary dependencies for net45 and net47

### ISSUE THREAD

**Issue by ddreibrodt** [JoshClose/CsvHelper#1584]
The current NuGet package declares dependencies on System.Threading.Tasks.Extensions for all frameworks (net45, net47, netstandard2.0 and netstandard2.1). But for net45 this dependency is not required.

Because System.Threading.Tasks.Extensions depends on netstandard, using it in a project targetting .NET < 4.7 results in the build output to be cluttered with about 100 unnecessary DLLs related to .NET Standard.

**Comment by JoshClose** [comment]
Fixed in version 15.0.6 on NuGet. https://www.nuget.org/packages/CsvHelper/15.0.6
