### ISSUE TITLE
Null Reference error occurs when Accessing `GetEnumerator()` directly

### ISSUE THREAD

**Issue by gregberns** [JoshClose/CsvHelper#1596]
**Describe the bug**
If the `CsvReader.GetRecords()` Enumerator is accessed and used directly a null reference exception occurs. I'd submit a PR but cant get the project to build on macos.

**To Reproduce**

```csharp
CsvHelper.Configuration.CsvConfiguration config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture);
            
using (var file1 = new StreamReader(filepath1))
{
    using (var csv = new CsvReader(file1, config))
    {   
        var l = csv.GetRecords<dynamic>();
        return Iterate(l);
    }
}

public static IEnumerable<int> Iterate(IEnumerable<dynamic> csv)
{
    var e = csv.GetEnumerator();
    e.MoveNext();      // Faults here
    yield return e.Current;
}
```

Null Reference occurs when the `MoveNext()` method is called. The stack trace says the error is occurring here: https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvReader.cs#L1069

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext() in /Users/gb/github/project/deps/CsvHelper/src/CsvHelper/CsvReader.cs:line 1069
   at DbDataDiff.Diff.Iterate(IEnumerable`1 csv)+MoveNext() in /Users/gb/github/project/src/Diff.cs:line 174
```

**Expected behavior**
No null reference exception

**Screenshots**
N/A

**Additional context**
My guess is that this can be prevented by submitting some Configuration values, but I haven't been able to figure it out.

**Comment by gregberns** [comment]
Disregard, this is a C# issue with iterators and using blocks, not an issue with the library.

**Comment by AltruCoder** [comment]
@MaxwellDexter Do you have some sample code that fails.  The issue gregberns was having was `csv.GetRecords<dynamic>()` does a lazy load of the data, so when he tried to access the data outside of the `CsvReader` using statement, he no longer had access to the `CsvReader`.

**Comment by MaxwellDexter** [comment]
Sure thing @AltruCoder :) This is abstracted quite a bit but conveys the problem.
I have a generic function that wraps the reading of CSV, and any 
```
using System.Linq;

public IEnumerable<T> ReadCSV<T>(string path)
{
    using (var reader = new StreamReader(path))
    using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
    {
        return csv.GetRecords<T>();
    }
}

public void MyFunction()
{
    List<Foo> myList = ReadCSV<Foo>("foo.csv").ToList(); // throws error here
}
```
Trying iterate through it with a `foreach` loop also breaks.
It's the same error as above:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at CsvHelper.CsvReader.GetRecords[T]()+MoveNext() in ...
```
I've worked around this by creating a list in the function, and calling `ToList()` within the using block.
For reference, I'm using this package with Unity in a 4.x C# environment.

**Comment by AltruCoder** [comment]
Yes, that is the same issue gregberns was having.  From the CsvHelper [Getting Started](https://joshclose.github.io/CsvHelper/getting-started/) page.
>The GetRecords<T> method will return an IEnumerable<T> that will yield records. What this means is that only a single record is returned at a time as you iterate the records. That also means that only a small portion of the file is read into memory. Be careful though. If you do anything that executes a LINQ projection, such as calling .ToList(), the entire file will be read into memory. CsvReader is forward only, so if you want to run any LINQ queries against your data, you'll have to pull the whole file into memory. Just know that is what you're doing.

That is why putting `ToList()` inside the using block works, because you have pulled the whole file into memory and no longer need the `StreamReader` or `CsvReader`.  Nothing is read from the file until you start to iterate over the `IEnumerable` that is returned from `GetRecords<T>()`, but it can't do that if you have already destroyed the `StreamReader` by trying to call it from outside the using statement.

**Comment by MaxwellDexter** [comment]
Oh right, that makes a lot of sense, thanks for your help @AltruCoder !!

**Comment by JoshClose** [comment]
The latest version of CsvHelper will throw a `ObjectDisposedException` if you try and use `GetRecords` or `EnumerateRecords` outside the using block.
