### ISSUE TITLE
Problem with reading special characters, getting �

### ISSUE THREAD

**Issue by devanshudravid** [JoshClose/CsvHelper#1599]
With reference to issue: https://github.com/JoshClose/CsvHelper/issues/462

@JoshClose  I am facing this issue while reading a Csv.

Configuration I have:
var csvConfig = new CsvConfiguration
{
Encoding = Encoding.UTF8,
HasHeaderRecord = true,
IgnoreHeaderWhiteSpace = true,
IsHeaderCaseSensitive = false,
IgnoreBlankLines = true,
CultureInfo = new CultureInfo("es")
};

And the Output is

Cargando anomal�as...
No se encontraron anomal�as
Descripci�n
Abrir panel del cl�ster

For
Cargando anomalías...
No se encontraron anomalías
Descripción
Abrir panel del clúster

It works when I use Encoding.GetEncoding("ISO-8859-1"), but it should work with UTF-8 too.

**Comment by AltruCoder** [comment]
UTF-8 and ISO-8859-1 are only encoded the same for the first 128 characters.  After that UTF-8 uses 2 bytes and ISO-8859-1 uses 1 byte.  
https://stackoverflow.com/a/7048780/2355006

**Comment by devanshudravid** [comment]
@AltruCoder I tried the same using a .txt file with same string. It worked for Stream Reader with UTF-8.

**Comment by devanshudravid** [comment]
Also my file is .csv. I can see in MS Excel there is one more file csv UTF-8

**Comment by AltruCoder** [comment]
I have run into encoding issue numerous times.  It's generally not a bug with CsvHelper. 

What encoding did your .txt file use?  Most likely it used UTF-8.  

Yes MS Excel can save the csv file as either ISO-8859-1 or UTF-8.  If you save it in Excel with UTF-8 then it should work just fine with your code.

**Comment by AltruCoder** [comment]
I really wish MS Excel didn't give you the option to save as ISO-8859-1. Worse than that, saving as ISO-8859-1 looks like the default way to save a csv file.

**Comment by devanshudravid** [comment]
Yes @AltruCoder. Thanks for all the information.

**Comment by Hoai-Phong** [comment]
How to read data text in Japanese cvs file?

**Comment by tankvn** [comment]
@Hoai-Phong 

1. Step 1: Install Encoding.CodePages packages
`dotnet add package System.Text.Encoding.CodePages --version 9.0.0`

2. Step 2: Use Encoding 932 `Shift_JIS`

```csharp
using System.Text;

// Register the CodePages encoding provider at application startup to enable using single and double byte encodings.
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

// Now can create single and double byte encodings for code pages that are not available in .NET Core.
using (var reader = new StreamReader(filePath, Encoding.GetEncoding(932)))
using (var csv = new CsvReader(reader, config))
{
   ....
}
```
