### ISSUE TITLE
IgnoreBlankLines not working properly

### ISSUE THREAD

**Issue by tarockx** [JoshClose/CsvHelper#1604]
**Describe the bug**
The `IgnoreBlankLines ` configuration option seems not to be working for me. In particular, the example below shows how a blank line at the end of the input generates an empty record instead of being ignored.

**To Reproduce**
This code reproduces the issue. As you can see, there is a blank line at the end of the input (just two tabs, no othe non-whitespace characters), which should be skipped, instead a record is generated for it:
```
static void Main(string[] args)
{
    string input = "name,\t\tmail\n" +
        "Mr. Foobar,\t\tfoo@bar.com\n" +
        "\t\t";

    using (var reader = new StringReader(input))
    {
        using (var csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true,
            IgnoreBlankLines = true,
            TrimOptions = TrimOptions.Trim,
            Delimiter = ",",
            PrepareHeaderForMatch = (header, index) => header.Trim()
        }))
        {
            var records = csv.GetRecords<dynamic>();
            foreach (IDictionary<string, object> record in records)
            {
                Console.WriteLine($"Name: {record["name"]}, address: {record["mail"]}");
            }
        }
    }
}
```

**Expected behavior**
The list of records from the code above should only contain one record (name = Mr. Foobar, mail = foo@bar.com), instead there is a second one with null values (I'm assuming from the last row, that just contains 2 tabs).

**Additional context**
I'm using version 15.0.8

**Comment by AltruCoder** [comment]
`IgnoreBlankLines` , does exactly that.  It ignores _completely_ blank lines. (I believe it is set to true by default)  A tab is a valid piece of data.  The two tabs without a comma will fail with a `MissingFieldFound` exception when using `GetRecords` with a class.  `GetRecords<dynamic>()` allows it to go through.  If you want it to skip that line you could use `ShouldSkipRecord`.
```csharp
ShouldSkipRecord = (record) => record.All(field => string.IsNullOrWhiteSpace(field))
```

**Comment by tarockx** [comment]
Thanks, this works, I had misinterpreted what the api meant by "blank", I assumed it included whitespace.
Thank you.
