### ISSUE TITLE
I need help - my code states empty array

### ISSUE THREAD

**Issue by jake918** [JoshClose/CsvHelper#1610]
I am trying to read a csv file and add the items to a list, but when I run the debugger, it states my array is empty:

    ` public class Elements
            {
            public string streetaddress1 { get; set; }
            public string streetaddress2 { get; set; }
            public string city { get; set; }
            public string state { get; set; }
            public string zip { get; set; }
            public string country { get; set; }
        }

        private void btnMultiple_Click(object sender, EventArgs e)
        {
            
            using (var reader = new StreamReader(@"C:\dev\Jake API\Area Lookup\JakesAreaLookup\data.csv"))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                var records = csv.GetRecords<Elements>().ToList();
            }
        }`
![image](https://user-images.githubusercontent.com/74018393/98283423-497cb680-1f65-11eb-86fb-c4631bb56725.png)

![image](https://user-images.githubusercontent.com/74018393/98283695-a24c4f00-1f65-11eb-95bb-a68a1db47ac4.png)

**Comment by JoshClose** [comment]
Is your breakpoint on that line? If so, you'll need to advance to the next line for it to execute.
