### ISSUE TITLE
Q: What is new in CsvHelper 15.0.10 

### ISSUE THREAD

**Issue by mikkelbu** [JoshClose/CsvHelper#1611]
I cannot see any commits on master (or the other branches on GitHub). I've compared the IL from the dlls - for .NetStandard2.0 - and the only difference besides the version number is that `AutoMapMembers` now also breaks after a check of `GetCustomAttribute<class CsvHelper.Configuration.Attributes.IgnoreAttribute>`. Is this correct?

**Comment by JoshClose** [comment]
I just pushed the code so you can see. What do you mean by `breaks`? Is there a bug?

**Comment by mikkelbu** [comment]
Thanks for the quick response and for a very helpful library. The "break" should have been "branch" as the my diff showed that the following code was added in the release (in IL)
```il
      IL_0141:  call       !!0 [netstandard]System.Reflection.CustomAttributeExtensions::GetCustomAttribute<class CsvHelper.Configuration.Attributes.IgnoreAttribute>(class [netstandard]System.Reflection.MemberInfo)
      IL_0146:  brtrue     IL_0323
```

I'll close the issue now, as the question has been answered.
