### ISSUE TITLE
Missing content in csv generation

### ISSUE THREAD

**Issue by cristianocps** [JoshClose/CsvHelper#1612]
I'm trying to write some csv in one project and a unexpected behavior is happening, some of the expected content is missing in the generated file (image below).
![image](https://user-images.githubusercontent.com/11409684/98870771-90c9e200-2452-11eb-847c-830f2e16cece.png)

Below is the code i'm using to generate the csv.

```csharp 
var records = new List<NPSImportModel>()
            {
            };

            foreach (int value in Enumerable.Range(0, 1000))
            {
                records.Add(new NPSImportModel { Email = $"lorem@ipsum{value}.com.br", Name = $"{value}1 - Lorem ipsum dolor sit amet", PhoneNumber = $"{value}55199836622288" });
            }

            MemoryStream writeStream = new MemoryStream();
            using StreamWriter writer = new StreamWriter(writeStream);
            using (CsvWriter csvWriter = new CsvWriter(writer, new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                BufferSize = 4096 * 2,
                Encoding = Encoding.UTF8,
                ShouldQuote = (row, context) => true,
                ShouldSkipRecord = (data) => false
            }))
            {
                writeStream.Position = 0;
                csvWriter.WriteRecords(records);

                writeStream.Position = 0;
                var csvText = Encoding.UTF8.GetString(writeStream.ToArray());

                File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "../../../", "results.csv"), csvText, Encoding.UTF8);
            }
```

To reproduce clone the repo https://github.com/cristianocps/csvhelper-bug, run the ConsoleApp2 project and check the results.csv file in project directory.

I'm running CsvHelper 15.0.10 with dotnet core 3.1 on Windows 10 Professional.

Some advices of what i'm doing wrong?

**Comment by JoshClose** [comment]
After `csvWriter.WriteRecords(records);` call `writer.Flush();`. `StreamWriter`s have a buffer that needs to be flushed. It will automatically be flushed at the end of the using block, but you're accessing it before that.

**Comment by cristianocps** [comment]
@JoshClose you're right, after your tips worked.
Thanks for the amazing work with CsvHelper.

**Comment by JoshClose** [comment]
You're welcome!
