### ISSUE TITLE
reads line with escaped quotes and escaped newline incorrectly

### ISSUE THREAD

**Issue by vrnmthr** [JoshClose/CsvHelper#1614]
**Describe the bug**
CsvReader reads line that has escaped quotes and escaped newline incorrectly. `row[4` is "\\Direktiva o kvaliteti površinskih voda" whereas it should in reality be a much longer string.

**To Reproduce**
Using CsvHelper 15.0.5

Add the following line to a CSV:
`"čiščenje pitne vode","","slv","993","\"Direktiva o kvaliteti površinskih voda, namenjenih za pitno vodo\" opredeljuje tri kategorije ravnanja z vodo (A1, A2, A3), od preprostega fizikalnega čiščenja in dezinfekcije do intenzivnega fizikalnega in kemičnega čiščenja. Vrsta čiščenja, ki naj bi se uporabila, je odvisna od kakovosti dovedene vode. Direktiva uporablja imperativne vrednosti za parametre, ki imajo neugodne učinke na zdravje in je tudi nakazala smernice za tiste, ki nimajo tako neugodnih učinkov. Obstaja tudi direktiva, ki dopolnjuje \"Direktivo o zajetju površinskih voda\" tako, da podaja metode merjenj in pogostost zajemanja vzorcev in ustrezno analizo.\`

Read with the following code:
```
var readerOptions = new CsvReaderOptions() { HasHeaderRecord = false };
using (var reader = new StreamReader(dataSourcePath))
using (var parser = new CsvParser(reader))
using (var csv = new CsvReader(parser, readerOptions))
{
    while(csv.Read() { }
}
```

**Comment by philjones** [comment]
According to the [RFC 4180 spec](https://tools.ietf.org/html/rfc4180), a CSV cannot contain a double-quote inside of a field unless it is preceded by another double-quote e.g. `""`.

You could try replacing the `\"` with `\""` before it gets to CSVHelper.

Actually, it looks like there may be an option to specify the escape character as of 10.0

In the [API docs](https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration/Configuration):
`Configuration.Escape - Gets or sets the escape character used to escape a quote inside a field. Default is '"'.`

**Comment by JoshClose** [comment]
Yes, you can change `Escape = '\\'` and it should work.
