### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by haidepzai** [JoshClose/CsvHelper#1616]
Hi,

I'm trying to read a CSV file from upload with `IFormFile` for that I am using this

```
public async Task<string> ReadCsvAsync(IFormFile file)
        {
            IEnumerable<AddressBook> records;
            using (var reader = new StreamReader(file.OpenReadStream()))
            using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
            {
                records = csv.GetRecords<AddressBook>();
            }

            var recordsAsArray = records.ToArray();

            string output1 = JsonConvert.SerializeObject(recordsAsArray, Formatting.Indented);
            return output1;
          }
```
I don't know what I am doing wrong here but whenever I tried to test it with Postman, I get an error on line `var recordsAsArray = records.ToArray();` as this is empty.

My model looks like this 

```
public class AddressBook
    {
        public int Id; { get; set; }
        public string firstName; { get; set; }
        public string lastName; { get; set; }
        public string address_street; { get; set; }
        public string address_streetNo; { get; set; }
        public string address_postalCode; { get; set; }
        public int phoneNumber; { get; set; }
    }
```

The CSV looks like this

```
Id,firstName,lastName,address_street,address_streetNo,address_postalCode,phoneNumber
1,jon,doe,somewhere road,123,5000,12346789
```

Is there something I am missing?
Do I have to map or something?

**Comment by AltruCoder** [comment]
You need to add the `ToArray()` inside the using statement.  `csv.GetRecords<AddressBook>()` does not attempt to get the records until you start to enumerate over them.  That way if you end up only needing 5 records out of millions from a file,  you don't have to bring the whole file into memory.  It does, however, mean that `GetRecords` can't work if you have already left the using statement and removed the `CsvReader`.  

From the [Getting Started](https://joshclose.github.io/CsvHelper/getting-started/) page.
> The GetRecords<T> method will return an IEnumerable<T> that will yield records. What this means is that only a single record is returned at a time as you iterate the records. That also means that only a small portion of the file is read into memory. Be careful though. If you do anything that executes a LINQ projection, such as calling .ToList(), the entire file will be read into memory. CsvReader is forward only, so if you want to run any LINQ queries against your data, you'll have to pull the whole file into memory. Just know that is what you're doing.

**Comment by JoshClose** [comment]
I just pushed a change that will throw an `ObjectDisposedException` with a message explaining what is going on so when this happens people will know.

**Comment by JoshClose** [comment]
It's in 16.1.0 on NuGet.
