### ISSUE TITLE
Populate change log for recent releases

### ISSUE THREAD

**Issue by madelson** [JoshClose/CsvHelper#1618]
Thanks for maintaining this useful library!

I've found https://joshclose.github.io/CsvHelper/change-log/ super helpful in migrating from an older version of CsvHelper to the latest, particularly the documentation of breaking changes. However, the last several releases don't have entries in the change log (even though that page continues to be linked from nuget.org).

Any chance those could be populated? Is there a new place to get this info?

**Comment by JoshClose** [comment]
Updated!
