### ISSUE TITLE
Type Converter for All Enums

### ISSUE THREAD

**Issue by sbcarp** [JoshClose/CsvHelper#1619]
Is it possible to add a type converter for all enum properties?
My example code below doesn't work because CsvHelper get type converter by derived type **AnimalEnum** not base type **System.Enum** so that `AddConverter<Enum>(new EnumConverter());` wasn't applied. 

    public enum AnimalEnum
	{
		Fox,
		Dog
	}
	public class TestClass
    {
		public AnimalEnum Animal { get; set; } = AnimalEnum.Fox;
	}
	public class EnumConverter : TypeConverter
	{
		public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
		{
			return "Overrided";
		}
	}
	class Program
	{
		static void Main(string[] args)
		{
			var data = new List<TestClass>() { new TestClass() };

			using (var stream = new MemoryStream())
			using (var reader = new StreamReader(stream))
			using (var writer = new StreamWriter(stream))
            using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
            {
                csv.Configuration.TypeConverterCache.AddConverter<Enum>(new EnumConverter());
                csv.WriteRecords(data);
				writer.Flush();
				stream.Position = 0;
				Console.WriteLine(reader.ReadToEnd());
			}
			Console.ReadLine();
		}
	}

**Comment by sbcarp** [comment]
The reason I want this is that in my project I have lots of different enums with shared custom attribute, I want to use stored value of the custom attribute as output string, for example

    public enum AnimalEnum
    {
    	[DisplayText("Foxxxx")]
    	Fox,
    	[DisplayText("Dogggg")]
    	Dog
    }
    public enum TableEnum
    {
    	[DisplayText("...")]
    	...
    }
    public static string GetDisplayText(this Enum value)
    {
         ...
    }

**Comment by sbcarp** [comment]
In CvsHelper project, TypeConverterCache.cs, I edited the GetConverter method and it supports base type now, but I don't know if it's an appropriate way

			...
			if (typeConverters.TryGetValue(type, out ITypeConverter typeConverter))
			{
				return typeConverter;
			}
			
			// Newly Added Code Below
			if (typeConverters.TryGetValue(type.BaseType, out typeConverter))
			{
				return typeConverter;
			}
			// Newly Added Code Above
			...

**Comment by JoshClose** [comment]
What if I make it so the `CsvHelper.Configuration.Attributes.NameAttribute` attribute can be used on `enum` values?

I believe doing what you're doing still wouldn't accomplish your goal because the `DisplayText` isn't being used.

I could also make it so that if you register a converter with the type `Enum` that it'll use that for any `enum`. That way you could write a customer converter that would look at the `DisplayText` attribute.

**Comment by sbcarp** [comment]
> What if I make it so the `CsvHelper.Configuration.Attributes.NameAttribute` attribute can be used on `enum` values?
> 
> I believe doing what you're doing still wouldn't accomplish your goal because the `DisplayText` isn't being used.
> 
> I could also make it so that if you register a converter with the type `Enum` that it'll use that for any `enum`. That way you could write a customer converter that would look at the `DisplayText` attribute.

The latter option sounds better to me as it gives me more control of the enum values, adding CsvHelper NameAttribute support to enum values is also a great add-on tho. 

Thank you!

**Comment by JoshClose** [comment]
I did both. They are in 16.2.0 on NuGet.
