### ISSUE TITLE
WriteRecords sometimes fails with ArgumentNullException in Expression.Convert

### ISSUE THREAD

**Issue by madelson** [JoshClose/CsvHelper#1622]
We have a large test suite that uses CsvHelper in various places. Infrequently (not every run), **one test will fail with the following exception**:

```
CsvHelper.WriterException : An unexpected error occurred.
  ----> System.ArgumentNullException : Value cannot be null.
Parameter name: expression
   at System.Linq.Expressions.Expression.RequiresCanRead(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at CsvHelper.Expressions.ObjectRecordWriter.CreateWriteDelegate[T](T record)
   at CsvHelper.Expressions.RecordWriter.GetWriteDelegate[T](T record)
   at CsvHelper.Expressions.RecordWriter.Write[T](T record)
   at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
   at <our code>
```

Test test suite runs multi-threaded using NUnit, but individual CsvWriter instances are always used in a single-threaded way. I suspect that there is some sort of multi-threading bug in the object mapping code.

We do use a cached singleton `CsvConfiguration` instance created as follows:

```
var configuration = new CsvConfiguration(CultureInfo.InvariantCulture);
// add a converter for our custom type which encodes string or null
configuration.TypeConverterCache.AddConverter(typeof(NullableString), new NullableString.TypeConverter());
```

**Perhaps this type is not thread-safe and we should not re-use it?**

Looking at the CsvHelper code, I believe that the problematic `Expression.Convert` call appears here: https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Expressions/ObjectRecordWriter.cs#L102, since other calls to that function in CreateWriteDelegate should never be passed a null expression. The expression coming out of `ExpressionManager` can be null (https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Expressions/ExpressionManager.cs#L290).

**Comment by JoshClose** [comment]
`CsvConfiguration` isn't thread safe. I tried to start a discussion on this on a pull request, but no reply yet. https://github.com/JoshClose/CsvHelper/pull/1593 

I don't know if I want to make the configuration thread safe due to it slowing things down. If the user is using a single config in multiple instances, there could be issues. Maybe I'll create an issue about this for people to discuss.

**Comment by JoshClose** [comment]
Please join the discussion here. https://github.com/JoshClose/CsvHelper/issues/1623

**Comment by JoshClose** [comment]
Configuration is now read only and should be thread safe. Open this back up if it's still a problem in the latest version.
