### ISSUE TITLE
MemberMap<TClass, TMember>.TypeConverter<TConverter> VERY SLOW

### ISSUE THREAD

**Issue by jzabroski** [JoshClose/CsvHelper#1629]
**Describe the bug**
Using CsvHelper 16.0.0, ReflectionHelper.CreateInstance is called many times, resulting in extremely slow parsing of rows.

In researching this further, in 3.x release, TypeConverterFactory was replaced with TypeConverterCache, which is hung off `csv.Configuration` object.  This cache does not seem to work if you use the MemberMap fluent helper.

**To Reproduce**
See this code:
```c#
    /// <summary>
    /// Specifies the <see cref="M:CsvHelper.Configuration.MemberMap`2.TypeConverter(CsvHelper.TypeConversion.ITypeConverter)" /> to use
    /// when converting the member to and from a CSV field.
    /// </summary>
    /// <typeparam name="TConverter">The <see cref="T:System.Type" /> of the
    /// <see cref="M:CsvHelper.Configuration.MemberMap`2.TypeConverter(CsvHelper.TypeConversion.ITypeConverter)" /> to use.</typeparam>
    public virtual MemberMap<TClass, TMember> TypeConverter<TConverter>() where TConverter : ITypeConverter
    {
      this.TypeConverter((ITypeConverter) ReflectionHelper.CreateInstance<TConverter>());
      return this;
    }
```

**Expected behavior**
Caching of the type, or some option to enable caching the type.

For example, [System.Diagnostics.Contracts.PureAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.contracts.pureattribute?view=net-5.0) could be used to indicate it is safe to cache the type and share it across reader and writer instances.   While the C# compiler does not verify purity, it could be a convenient way to auto-detect the developer intent.

**Screenshots**

**Additional context**
I _also_ probably wouldn't need to create all so many type converters if:

- There was an easier way to create custom converters for `decimal` and `decimal?`
- Null handling was orthogonal to type conversion
- I don't use ConvertUsing because the way it handles errors isn't ideal / has bitten me in horrifying ways (can't remember off the top of my head)

**Comment by jzabroski** [comment]
I rewrote my logic to use ConvertUsing and it is not much faster.  I found I was better off using a DTO with all strings and doing the manipulate in C# than use CsvHelper to perform the transforms, which is rather surprising / indicative of how slow this area of the code is.

**Comment by JoshClose** [comment]
I'm confused. `MemberMap.TypeConverter` sets `MemberMapData.TypeConverter` where it should be used for reading/writing.

Can you give some example code, like a unit test or program that demonstrates this?

> There was an easier way to create custom converters for decimal and decimal?

Easier than a class? What is a better way in your opinion?

> Null handling was orthogonal to type conversion

How is it not? You only need a `decimal` converter. If the property is nullable, it should be handled for you.

> I don't use ConvertUsing because the way it handles errors isn't ideal / has bitten me in horrifying ways (can't remember off the top of my head)

Maybe this can be changed to register a `CustomConverter` type converter or something, so it behaves the same way as the other converters.

**Comment by jzabroski** [comment]
> > Null handling was orthogonal to type conversion
> How is it not? You only need a `decimal` converter. If the property is nullable, it should be handled for you.

I figured this out last night after staying up all night debugging it.  Basically, my core confusion (which I am sorry got passed on to you) is that when a type converter throws, it only populates the Index property on CsvHelperException, and not the Field property.  Despite the fact that the type converter is called from a MemberMap context, where it should, in theory, know the Field name.  For CSV files with many columns, its extremely mentally taxing trying to decode Index=[102] to "NewSharesOutstanding" or whatever field I am parsing that's failing.  (Of course, CsvHelper still beats using SSIS or some expensive cloud ETL tool.)

> > There was an easier way to create custom converters for decimal and decimal?
> 
> Easier than a class? What is a better way in your opinion?

In the past, I feel like needing to write an actual converter for this is overkill.  I can look back at specific examples of where I've actually needed to do this, because I just feel like if we exposed one more TypeConverterOption, most converters I write would just go away.  The ONLY scenario I can think of where using a TypeConverter is truly handy is when people want a cell with a nested csv value like:

```
Name,Address
"John Zabroski","1 Bob Maloogaloogalooogalooga Way, Paris, France"
```

or similarly, I had one client who wanted to enter data in Excel cells with a pipe delimiter to denote a list of values.  So, I loaded the document with Aspose.Cells, converted it to a CSV, and used CsvHelper and a TypeConverter to map that pipe delimited value to an array object.

> Maybe this can be changed to register a CustomConverter type converter or something, so it behaves the same way as the other converters.

This is a good idea.  So:

```c#
    public sealed class DelegateConverter : ITypeConverter
    {
        private Func<object, IWriterRow, MemberMapData, string> _convertToString;
        private Func<string, IReaderRow, MemberMapData, object> _convertFromString;
        DelegateConverter(
            Func<object, IWriterRow, MemberMapData, string> convertToString,
            Func<string, IReaderRow, MemberMapData, object> convertFromString)
        {
            _convertToString = convertToString;
            _convertFromString = convertFromString;
        }

        public string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
        {
            return _convertToString(value, row, memberMapData);
        }

        public object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            return _convertFromString(text, row, memberMapData);
        }
    }
```
I can create a ticket and a PR, if you're interested.  I know you have a new version of the code in your local that does memory pooling so I don't want to interfere with that stuff.  However, I think we also need to optimize how these objects are allocated.  On a 303,000 line file, GC pressure also adds performance overhang.  I'd need to look at this more carefully to see exactly why it was so slow.  I used Github and saw the ReflectionHelper and the Object Resolver doing locking and just immediately assume refleciton + lock = performance death.  With extremely fast DI frameworks, like DryIoC, that are mostly lock-free, it might even be possible to use Microsoft.Extensions.DependencyInjection and let people define services via IServiceProvider.

**Comment by JoshClose** [comment]
You can set your own resolver that could be DryIoc or Microsoft.Extensions.DependencyInjection. The default is `ReflectionHelper.CreateInstanceWithoutContractResolver` which has the locking.. I'd be interested to see how much faster it gets from just doing that. 

I could move all the object creation methods out into their own class so it could be an instance to avoid the locking.

**Comment by JoshClose** [comment]
I guess the static `Current` instance of `ObjectResolver` would need to be removed too.

**Comment by jzabroski** [comment]
Doubt you need it. Abioc container for example can handle your resolve needs. Plus, the TTypeConverter _could_ just have a new() constraint and you can just `new TTypeConverter`. Wasn't sure why there was the indirection but didn't study the tests

**Comment by jzabroski** [comment]
@JoshClose  To elaborate on my last reply, which I sent using the FastHub mobile app and didn't have access to a desktop:

abioc is a simple container that just delegates all logic to Roslyn.  Similar to how first generation .NET Framework IoC containers worked which called CodeDOM, except that it's much cleaner/faster since it's using an optimized compiler written in C# (Roslyn) to generate the scope binding and object allocation logic.  For the use cases you have, abioc would probably be the best since it has a very tiny package footprint.

Below is a screenshot that shows you that abioc is actually faster at allocations than calling `new T`.  Not all containers in Daniel Palme's [IoCPerformance](https://github.com/danielpalme/IocPerformance) benchmark suite can claim that.  In part because some containers use second or third generation container tech.  Fourth generation containers are generally blazing fast for the common scenarios.

![image](https://user-images.githubusercontent.com/447485/102379707-23e7c180-3f95-11eb-948e-03fba3eec6cf.png)

**Comment by JoshClose** [comment]
Since you're familiar with this, how can I set up abioc to create any object with given parameters without registering anything ahead of time?

**Comment by JoshClose** [comment]
This is only netstandard2.0 compatible, so I'll need to include something to generate on those platforms anyways.

**Comment by JoshClose** [comment]
I'm running some tests creating instances using the `ObjectResolver` with:
1. `ObjectResolver` instance with abioc.
2. `ObjectResolver` instance with `ReflectionHelper` instance with some re-work of the caching.
3. `ObjectResovler` static with `ReflectionHelper` static.

50,000,000 loops:
```
00:00:02.1913252
00:00:21.1325215
00:00:50.4524480
```
abioc is insanely fast. I'd adopt this by default is there is a way to register types on the fly and create instances with a variable number of constructor args. I could use my own backup for older versions of .NET versions.

**Comment by jzabroski** [comment]
Haha.  I am not sure how to do that but we can research it.

**Comment by jzabroski** [comment]
@JoshClose Can you give me an example of where you create instances with a variable number of constructor args?  Can probably take a this weekend.

**Comment by JoshClose** [comment]
```cs
class Foo
{
    public int Id { get; private set; }
    public string Name { get; private set; }

    public Foo(int id, string name)
    {
        Id = id;
        Name = name;
    }
}
```

**Comment by JoshClose** [comment]
So there could be any number of constructor args, just like properties.

**Comment by jzabroski** [comment]
I meant, where in CsvHelper does it need this.  TypeConverter<TConverter> doesnt have any args?  Unless I am misreading the code.

https://github.com/JoshClose/CsvHelper/blob/173e4011e93d7af9c00072f208c7ac9ead071cff/src/CsvHelper/Configuration/MemberMap.cs#L206-L211

and this doesn't test it either:

https://github.com/JoshClose/CsvHelper/blob/30b13339eb6adad447426bb6b48ed66cc4b7f679/tests/CsvHelper.Tests/Reflection/CreateInstanceTests.cs

I figure you know the code base better than me, so just wanted to see where the requirement was coming from.

**Comment by JoshClose** [comment]
I don't think it's used when creating the TypeConverters. I just looked and it looks like ArrayConverter might be the only place that currently passes args in.

**Comment by jzabroski** [comment]
Got it.  I never used or knew about ArrayConverter before.  Cool!  A bit hidden API wise, but cool! I don't think that's in the examples? https://joshclose.github.io/CsvHelper/examples/reading

So, basically, you can share a name across multiple csv columns, and if the target type is an IEnumerable, it will convert it to an array? Is there some sample code I can read to test it?

https://github.com/JoshClose/CsvHelper/blob/813346f2704b4238f8710cb44a3484b5220dda97/src/CsvHelper/TypeConversion/ArrayConverter.cs#L15

**Comment by JoshClose** [comment]
There are a bunch of collection type converters actually. Check out the unit tests for them here. https://github.com/JoshClose/CsvHelper/tree/master/tests/CsvHelper.Tests/TypeConversion

**Comment by JoshClose** [comment]
So, I don't think I need abioc. I just changed how `CreateInstance` works with caching and removed the `DynamicInvoke` in favor of `Func<object[], object>` and here are the results.

1. abioc.
1. DynamicInvoke removed.
1. Current static ReflectionHelper.

```
00:00:02.6041470
00:00:04.6746028
00:01:00.8696805
```

**Comment by jzabroski** [comment]
Yeah, probably not worth the dependency now that it is within one order of magnitude difference.  Not worth the dependency.

**Comment by JoshClose** [comment]
I'm using a class `HashCode` which isn't in older versions of .NET though. Maybe I'll just include the source code locally for older versions.

**Comment by JoshClose** [comment]
I did some more optimizations and it's down to `00:00:03.1587472` now.

**Comment by jzabroski** [comment]
Do you use BenchmarkDotNet?

**Comment by JoshClose** [comment]
This was using Stopwatch in LINQPad and doing 50,000,000 calls. I always forget about that library. It's really good. I'll hook it up to this.

**Comment by JoshClose** [comment]
I apparently don't know how to use BenchmarkDotNet. When I run tests there, it's showing `Activator.CreateInstance` to be faster. When running a looping test, `Activator` is slow. I'm not setting things up correctly apparently.

**Comment by JoshClose** [comment]
What do you think of this? 

I removed the static `ReflectionHelper` methods and made a class `ObjectCreator`. This class is really fast and just an order a magnitude slower than abioc, like you mentioned. This is not thread safe.

`ObjectResolver`'s default constructor will create a new `ObjectCreator` to use. There is an instance method that does the creation using the `ObjectCreator`. This is not thread safe.

`ObjectResolver` is now an instance on `ReadingContext` and `WritingContext`. This should avoid any threading issues unless someone decides to set their own and use it across multiple instances of the reader/writer. They will need to handle thread safety in that case.

`ObjectResolver.Current` has the locks removed. I don't think it matters if the instance changes during a get call. I don't think people will be setting this a bunch of times with different resolvers either.

`ObjectResolver` now has a static constructor that creates the `Current` instance. The resolve function will use locking on object creation.

Here is the `ObjectResolver` class.

```cs
// Copyright 2009-2020 Josh Close and Contributors
// This file is a part of CsvHelper and is dual licensed under MS-PL and Apache 2.0.
// See LICENSE.txt for details or visit http://www.opensource.org/licenses/ms-pl.html for MS-PL and http://opensource.org/licenses/Apache-2.0 for Apache 2.0.
// https://github.com/JoshClose/CsvHelper
using System;

namespace CsvHelper
{
	/// <summary>
	/// Creates objects from a given type.
	/// </summary>
	public class ObjectResolver : IObjectResolver
	{
		private static IObjectResolver current = new ObjectResolver();
		private readonly ObjectCreator objectCreator = new ObjectCreator();

		/// <summary>
		/// Gets or sets the current resolver.
		/// Use an instance of this instead if at all possible.
		/// </summary>
		public static IObjectResolver Current
		{
			get
			{
				return current;
			}
			set
			{
				if (value == null)
				{
					throw new InvalidOperationException($"{nameof(IObjectResolver)} cannot be null.");
				}

				current = value;
			}
		}

		/// <summary>
		/// A value indicating if the resolver's <see cref="CanResolve"/>
		/// returns false that an object will still be created using
		/// CsvHelper's object creation. True to fallback, otherwise false.
		/// Default value is true.
		/// </summary>
		public bool UseFallback { get; private set; }

		/// <summary>
		/// A function that returns a value indicating if the resolver 
		/// is able to resolve the given type. True if the type can be 
		/// resolved, otherwise false.
		/// </summary>
		public Func<Type, bool> CanResolve { get; private set; }

		/// <summary>
		/// The function that creates an object from a given type.
		/// </summary>
		public Func<Type, object[], object> ResolveFunction { get; private set; }

		static ObjectResolver()
		{
			var objectCreator = new ObjectCreator();
			var locker = new object();
			current = new ObjectResolver(type => true, (type, args) =>
			{
				lock (locker)
				{
					return objectCreator.CreateInstance(type, args);
				}
			});
		}

		/// <summary>
		/// Creates an instance of the object resolver using default values.
		/// </summary>
		public ObjectResolver()
		{
			CanResolve = type => true;
			ResolveFunction = ResolveWithObjectCreator;
			UseFallback = true;
		}

		/// <summary>
		/// Creates an instance of the object resolver using the given can create function
		/// and create function.
		/// </summary>
		/// <param name="canResolve">A function that returns a value indicating if the resolver
		/// is able to resolve the given type. True if the type can be
		/// resolved, otherwise false.</param>
		/// <param name="resolveFunction">The function that creates an object from a given type.</param>
		/// <param name="useFallback">A value indicating if the resolver's <see cref="CanResolve"/>
		/// returns false that an object will still be created using
		/// CsvHelper's object creation. True to fallback, otherwise false.
		/// Default value is true.</param>
		public ObjectResolver(Func<Type, bool> canResolve, Func<Type, object[], object> resolveFunction, bool useFallback = true)
		{
			CanResolve = canResolve ?? throw new ArgumentNullException(nameof(canResolve));
			ResolveFunction = resolveFunction ?? throw new ArgumentNullException(nameof(resolveFunction));
			UseFallback = useFallback;
		}

		/// <summary>
		/// Creates an object from the given type using the <see cref="ResolveFunction"/>
		/// function. If <see cref="CanResolve"/> is false, the object will be
		/// created using CsvHelper's default object creation. If <see cref="UseFallback"/>
		/// is false, an exception is thrown.
		/// </summary>
		/// <param name="type">The type to create an instance from. The created object
		/// may not be the same type as the given type.</param>
		/// <param name="constructorArgs">Constructor arguments used to create the type.</param>
		public object Resolve(Type type, params object[] constructorArgs)
		{
			if (CanResolve(type))
			{
				return ResolveFunction(type, constructorArgs);
			}

			if (UseFallback)
			{
				return objectCreator.CreateInstance(type, constructorArgs);
			}

			throw new CsvHelperException($"Type '{type.FullName}' can't be resolved and fallback is turned off.");
		}

		/// <summary>
		/// Creates an object from the given type using the <see cref="ResolveFunction"/>
		/// function. If <see cref="CanResolve"/> is false, the object will be
		/// created using CsvHelper's default object creation. If <see cref="UseFallback"/>
		/// is false, an exception is thrown.
		/// </summary>
		/// <typeparam name="T">The type to create an instance from. The created object
		/// may not be the same type as the given type.</typeparam>
		/// <param name="constructorArgs">Constructor arguments used to create the type.</param>
		public T Resolve<T>(params object[] constructorArgs)
		{
			return (T)Resolve(typeof(T), constructorArgs);
		}

		private object ResolveWithObjectCreator(Type type, params object[] args)
		{
			return objectCreator.CreateInstance(type, args);
		}
	}
}
```

**Comment by jzabroski** [comment]
It makes sense to me.  Was going to show you how to benchmark with benchmark dot net this weekend.  (I work through the holidays).  I can copy the above and throw it into a small example outside CsvHelper.

Sometimes, code that appears it should be faster can also be slower due to branch mispredictions and cache misses.  I've seen it happen where randomized test data inputs outperform serial inputs despite an algorithm that is designed to short-circuit on serial input when a monotonically increasing sub-sequence resets.  I meant to write a blog post about it and explain what is happening.  But Adam Sitnik has written similar posts.

**Comment by JoshClose** [comment]
Just did a test with the updated code. On a 100,000,000 record file, the current version took `3:04` to parser. The beta with the change I talked about took `1:18`.

Version `19.0.0-beta0001` is on NuGet if you want to try it out.

**Comment by jzabroski** [comment]
> Version `19.0.0-beta0001` is on NuGet if you want to try it out.

Change your naming convention to be `19.0.0-beta.1`.  It is technically more correct and Nuget will sort it correctly.  I know; I got bit by this when I was maintaining RazorLight and had to stop using `-beta` and use some suffix alphabetically higher so I chose `-rc` and started doing `-rc.1`, `-rc.2`.  You can see what I mean here by looking for `2.0.0-beta10` and seeing it sorts funny: https://www.nuget.org/packages/RazorLight

![image](https://user-images.githubusercontent.com/447485/102941239-31fb7d80-4480-11eb-804e-8d7c0187b9ba.png)

**Comment by JoshClose** [comment]
I'll see what I can get GitVersion to do.

**Comment by JoshClose** [comment]
I'm guessing that's why GitVersion put 3 0's in front of it.

**Comment by jzabroski** [comment]
hahahahahhahaha,  Does it really?  TBH I only use GitVersion suffixes for AzureDevOps package feeds for the FluentMigrator package , so I never even paid attention to that aspect.  I can look at how we set it up there, but we're technically using an old version of GitVersion and so I am sure what we are doing is janky.

**Comment by JoshClose** [comment]
I'm not seeing a way... If you know of something, let me know.

It looks like this right now.
```yml
next-version: 19.0.0
assembly-versioning-scheme: Major
assembly-file-versioning-format: '{Major}.{Minor}.{Patch}.{env:BUILD_NUMBER ?? 0}'
mode: Mainline
branches:
  fast-object-creator:
    tag: beta
    regex: fast-object-creator
    mode: ContinuousDelivery
    source-branches: ['master']
ignore:
  sha: []
merge-message-formats: {}
```

**Comment by jzabroski** [comment]
Found why. See:

> `legacy-semver-padding`
> The number of characters to pad LegacySemVer to in the LegacySemVerPadded [variable](https://gitversion.readthedocs.io/en/latest/input/docs/configuration/more-info/variables). Is default set to 4, which will pad the LegacySemVer value of 3.0.0-beta1 to 3.0.0-beta0001.

So, strange, GitVersion pushes the padding thing.  Maybe it's for backward compatibility with some awful artifact repositories that don't properly handle SemVer?

Note: the link I quote above is broken in that page.  I think the correct link is : https://gitversion.net/docs/more-info/variables

**Comment by jzabroski** [comment]
It looks like the variable PreReleaseTagWithDash is the right SemVer suffix format.

**Comment by JoshClose** [comment]
> So, strange, GitVersion pushes the padding thing. Maybe it's for backward compatibility with some awful artifact repositories that don't properly handle SemVer?

They output a `NuGetVersion`, `NuGetVersionV2`, `NuGetPreReleaseTag`, and `NuGetPreReleaseTagV2`, so you think it would be whatever works well with NuGet.

**Comment by JoshClose** [comment]
`SemVer` is correct, but the NuGet ones aren't. Maybe I'll use `SemVer` for the NuGet package names instead.

**Comment by jzabroski** [comment]
Josh, Where's the yak shaving emoji? :) GitVersion has come a long way since 2017 when I first heard of it, so my guess is it's not far off from fixing that issue.

I will resurrect my version of the code from my branch where I ran into perf issues.

**Comment by JoshClose** [comment]
I pushed a new beta using the new `ObjectCreator` but using the static `ObjectResolver.Current` and no instance on the context. It's just slightly slower coming in at `1:21` instead of `1:18`. I think that's fast enough to use so people don't get confused by having to set a resolver in 3 places in the system instead of 1. That lock didn't actually slow things down much. It was the `DynamicInvoke` that was slow.

**Comment by JoshClose** [comment]
The speed improvements are in 19.0.0 on NuGet.

**Comment by JoshClose** [comment]
Thanks for the info and discussion.
