### ISSUE TITLE
TypeConverterOption.Format for CsvReader

### ISSUE THREAD

**Issue by jzabroski** [JoshClose/CsvHelper#1630]
**Is your feature request related to a problem? Please describe.**
Observe the following program inspired from:

```c#
void Main()
{
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
	{
		var records = new List<Test>
		{
			new Test { Number = 1F },
			new Test { Number = 1.00002F },
			new Test { Number = 1.523468F },
		};
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);

		writer.Flush();
		writer.ToString().Dump();
	}

	var s = new StringBuilder();
	s.AppendLine("Number");
	s.AppendLine("1");
	s.AppendLine("1.00002");
	s.AppendLine("1.523468");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
	{
		csv.Configuration.TrimOptions = TrimOptions.Trim;
		csv.Configuration.Delimiter = "\t";
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public float Number { get; set; }
}

public class TestMap : ClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Number).TypeConverterOption.Format("0.00");
	}
}
````

**Describe the solution you'd like**
TypeConverterOption.Format should work both ways.  For Reader, it should read the field as a string, then apply the Format specification, then convert it to the BCL type.

**Describe alternatives you've considered**
#1629 is related to what I am trying to solve, which is working around how slow custom type converters are.

**Additional context**
n/a

**Comment by JoshClose** [comment]
Is this still an issue?

I don't see a way to specify a format when parsing a float. https://docs.microsoft.com/en-us/dotnet/api/system.single.tryparse?view=net-5.0#System_Single_TryParse_System_String_System_Globalization_NumberStyles_System_IFormatProvider_System_Single__

**Comment by jzabroski** [comment]
That's a good point. I guess I was thinking of a format specifier that only allows N decimal places.
