### ISSUE TITLE
EnumConverter should not use a case invariant comparison for names

### ISSUE THREAD

**Issue by thibault-reigner** [JoshClose/CsvHelper#1638]
While migrating from version 15.0 to 19.0 of CsvHelper, I encountered an issue resulting in a "key already existing in the dictionary" exception" in my code base.

After investigation, it is due to the following line : 
https://github.com/JoshClose/CsvHelper/blob/255fdb9ccfc0b98419eb0d3a00ab9af94a8eb643/src/CsvHelper/TypeConversion/EnumConverter.cs#L21

As it is perfectly legal in C# (but a very bad practice I confess), to have two distinct values in an enum, whose names only differ based on case (in my case it was `Alpha` and `ALPHA`), the string comparer used for this dictionary should be `StringComparison.Ordinal`.

However the following test forbid such change : 
https://github.com/JoshClose/CsvHelper/blob/db5baebe545ab2e989ad06e66ac608b98b947763/tests/CsvHelper.Tests/TypeConversion/EnumConverterTests.cs#L59-L61

So I think these behaviour should be configurable (i.e : are enum values in CSV expected to be case sensitive or not).

I had a look at the code and the change does not seem easy, as the converter cache does not receive the configuration during its instantiation but through `MemberMapData.TypeConverterOptions`, a parameter of `ConvertFromString`.

**Comment by JoshClose** [comment]
An option would be a good idea. `Enum.TryParse` has an `ignoreCase` setting so I could use that in the fallback also.

If you parse ignoring case and more than one are the same, it uses the one with the lowest value.

You can also use the same value for multiple names. That complicates things too.

**Comment by JoshClose** [comment]
I added `TypeConverterOptions.EnumIgnoreCase`.

I'm following the same rules that .NET uses when parsing. I'm only storing data for attributes and falling back to `Enum.TryParse`/`Enum.ToString`, since parse has the `ignoreCase` parameter. This makes it a lot easier.

**Comment by JoshClose** [comment]
Fixed in 22.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/22.0.0

**Comment by thibault-reigner** [comment]
Nice, thank you. I will give it a try soon.
