### ISSUE TITLE
CsvFieldAttribute could not be found

### ISSUE THREAD

**Issue by ghost** [JoshClose/CsvHelper#164]
Using Visual Studio 2012 .Net 4.5  Nuget version 2.5.40416.9020.  Any ideas why this isn't working?    

Manually referenced CsvHelper.dll in net40-client folder

[CsvField ( Name = "Missing reference")]

**Comment by pallu** [comment]
Will the Index auto map to the order in which the properties appear in the class code?

**Comment by JoshClose** [comment]
Maybe...

> The GetProperties method does not return properties in a particular order, such as alphabetical or declaration order. Your code must not depend on the order in which properties are returned, because that order varies.

https://msdn.microsoft.com/en-us/library/kyaxdd3x(v=vs.110).aspx

So basically you can't count on that.
