### ISSUE TITLE
ShouldQuote() while creating a ClassMap<Foo>

### ISSUE THREAD

**Issue by VasuInukollu** [JoshClose/CsvHelper#1644]
Should it be possible to set ShouldQuote when preparing a ClassMap? My CSV output columns order is to be changed based user input but I know specific column which needs to be quoted.

                    var prop = type.GetProperty(orderedSetting.Name);
                    var memberMap = Map(typeof(Call), prop);
                    memberMap.TypeConverterOption.Format("HH:mm:ss");
                    memberMap.ShouldQuote(); /// something like this

I have data column which has values like this 1610696963.16106**96963** which are not being selected for quotes by the default implementation. When this file is opened in Excel, it picks up this as a number field and silently drops the precision to 5 digits which is almost like a data loss.

**Comment by JoshClose** [comment]
`ShouldQuote` is based on looking at the content of a field. If you want always quote a given field, just quote them all. There shouldn't be any harm in that.

```cs
csv.Configuration.ShouldQuote = (field, context) => true;
```

If you know the index of the field, you can do this.

```cs
csv.Configuration.ShouldQuote = (field, context) => context.Record.Count() == 1;
```

I'll add the current index and the headers in the next version to make that easier.

I'm a little torn on the idea of putting it on a field level. I think it's kind of a special case.

**Comment by VasuInukollu** [comment]
I have following your suggestion and decided to get the column numbers from the class map after building it. The class map itself is built using code from the database as you can see.


      var streamWriter = new StreamWriter(memoryStream);
      var csvWriter = new CsvWriter(streamWriter, CultureInfo.InvariantCulture);

      var classMap = new CdrCsvColumnHeaderMap(xemaDb);
      var alwaysQuoteColumns = classMap.AlwaysQuoteColumns.ToArray();
      csvWriter.Configuration.ShouldQuote = (field, context) => alwaysQuoteColumns.Contains(context.Record.Count);

      csvWriter.Configuration.RegisterClassMap(classMap);
      csvWriter.WriteRecords<Call>(list);

If there is a way to mark the column inside the class map construction code, it would look clean.

Thanks for the quick comment and effort.

**Comment by JoshClose** [comment]
Version 21.0.0 is published and `ShouldQuote` now takes in `IWriterRow`. That will contain `Index` and `HeaderRecord` which should make it easier for you.

**Comment by apjones6** [comment]
From my testing while trying to something with this, both on version 20.0.0 and now 21.0.0, it seems the Row and Index properties always have a value of 1. Briefly looking at the code there doesn't appear to be anything to update the private field, does CsvWriter need to be subclassed?

https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvWriter.cs#L72

If it's my error I don't want to sidetrack this issue; just commenting as it seems relevant.

For unnecessary extra info I was attempting to use CsvHelper to modify an existing CSV, adding/removing quotes based on the 'column' index.

**Comment by JoshClose** [comment]
It's a bug that I apparently don't have a unit test for yet. I'll fix that.

**Comment by JoshClose** [comment]
A fix for this is in 21.0.1 on NuGet. Might take a few minutes to show up. https://www.nuget.org/packages/CsvHelper/21.0.1

**Comment by JoshClose** [comment]
I changed `ShouldQuote` to `ShouldQuote(string field, Type fieldType, IWriterRow)`. I believe everything is available here to quote based on index, name, or field type.

Added in 22.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/22.0.0

**Comment by JoshClose** [comment]
I changed `ShouldQuote` to `ShouldQuote(string field, Type fieldType, IWriterRow)`. I believe everything is available here to quote based on index, name, or field type.

Added in 22.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/22.0.0
