### ISSUE TITLE
Regression: impossible to use \r\n newlines on non-Windows platforms

### ISSUE THREAD

**Issue by jas88** [JoshClose/CsvHelper#1649]
**Describe the bug**
The new Configuration.NewLine mechanism (a single nullable char, where null uses the platform default line-ending but is wrongly documented as meaning \r\n) makes it impossible to configure \r\n on any platform where this is not the system default.

**To Reproduce**
Try to write a CSV on any system where Environment.NewLine!="\r\n" (e.g. Linux, Mac) with NewLine=null

**Expected behavior**
CSV written using \r\n line endings

**Screenshots**
Note failing unit test from run on Linux host.
<img width="655" alt="Screenshot 2021-01-18 at 13 22 29" src="https://user-images.githubusercontent.com/9466/104920814-4c961900-5990-11eb-81b0-74a93d8b753a.png">

**Additional context**
Proposed fix PR in #1648

**Comment by JoshClose** [comment]
I missed that scenario. What do you think is a good way to solve this? I could change `char? NewLine` to `string NewLine`. I'll have to update the parser, but that shouldn't be a big deal.

**Comment by jas88** [comment]
A "string?" would be most flexible and allow null to use the platform default as now, so that's probably best IMO - certainly fixes our issue.

**Comment by JoshClose** [comment]
It's been changed to a string in 21.0.0. https://www.nuget.org/packages/CsvHelper/21.0.0
