### ISSUE TITLE
How to replace csv.Configuration.RegisterClassMap<>()

### ISSUE THREAD

**Issue by Netclick19** [JoshClose/CsvHelper#1650]
Hi,

thank you for your library, very helpful!

I've a question about how to replace the method csv.Configuration.RegisterClassMap<>().
I don't find anything in the doc.

Thank you for your support.

**Comment by JoshClose** [comment]
I need to update the docs, but it's in the change log.

```cs
csv.Context.RegisterClassMap
```

The config is now read only and any mutable data went to the context.

**Comment by JoshClose** [comment]
https://joshclose.github.io/CsvHelper/change-log
