### ISSUE TITLE
IReaderConfiguration is readonly

### ISSUE THREAD

**Issue by mtissington** [JoshClose/CsvHelper#1651]
What am I missing? Upgraded to the latest version and I can no longer assign value to properties of IReaderConfiguration.

You example no longer works either....

using (var reader = new StreamReader("path\\to\\file.csv"))
using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
{
   /// reports error with the following line because it's readonly
    csv.Configuration.PrepareHeaderForMatch = (string header, int index) => header.ToLower();
    var records = csv.GetRecords<Foo>();
}

**Comment by JoshClose** [comment]
The config is read only now. You need to pass it into the constructor. I haven't updated the docs yet, but the change log shows all the breaking changes. https://joshclose.github.io/CsvHelper/change-log

**Comment by mtissington** [comment]
Hmm, I did check the change log and noticed it was set to readonly - however an example of when and how would be very helpful please becasue I'm still scratching my head here. Just attempting to create a  CsvConfiguration = new CsvConfiguration(?) is obviously not the way to do it.

**Comment by mtissington** [comment]
Hmm, am I missing something? You appear to have started using records which is c# 9.0 dependent which is .Net 5.0 dependent ...

**Comment by JoshClose** [comment]
I updated the examples in the docs so you can look at that now.

Most language features you can use because they're just syntactic sugar and don't require a new framework. A lot of times MS will provide a backwards compatible library from NuGet too. System.Memory and System.Buffers net50 libraries, but MS has a backwards compatible library.

**Comment by mtissington** [comment]
Thanks - helped a lot

**Comment by greg-stein** [comment]
I'm sorry for bringing this up again,

Our code was based on serialization and deserialization of CsvConfiguration class. For storing CsvConfiguration and retrieving it we use Json. It was really convenient way of controlling parsing behavior outside of application. By making all these properties readonly, this doesn't work anymore.

Why would you make CsvConfiguration's properties readonly? Also, what would be best way of fixing it in our code to make it work with latest version? For now we rolled-back CsvHelper version to 19.

Thank you!
