### ISSUE TITLE
ValidationException

### ISSUE THREAD

**Issue by mtissington** [JoshClose/CsvHelper#1652]
I have looked thru the change log but can't find any reference to the ValidationException.

What has happened to ex.ReadingContext.Row (ex = a thrown ValidationException)?

Thanks.

**Comment by mtissington** [comment]
I think I found it ...

ex.Context.Reader.Parser.Row ...

**Comment by JoshClose** [comment]
You can do ex.Context.Parser.Row. The parser is available directly on the context

**Comment by JoshClose** [comment]
Also, the exception should spit out a lot of information now.
