### ISSUE TITLE
Significant performance degradation when update from v19 -> v20

### ISSUE THREAD

**Issue by iccfish** [JoshClose/CsvHelper#1655]
**Describe the bug**
Running on .NET 5.0, when upgrade `CsvHelper` from v19 to v20, a significant performance degradation was issued.

**To Reproduce**
1. Start a new .NET 5.0 console application
2. Install `CsvHelper` v19, and wrote test code
3. Run project, log performance
4. Upgrade lib to v20, and speed downgrade.

> upgrade to v21 doesn't resolve this issue.

**Expected behavior**
Speed of CsvHelper v20+ should be faster than v19

**Screenshots**
Here's my test result:
![image](https://user-images.githubusercontent.com/1091653/105010521-c9032780-5a76-11eb-810d-41d264a7b113.png)

Test shows v19 only needs 99ms but v20 needs 15880ms (almost 158 times slower).

**Additional context**
I've done some performance capture on v19 using dotTrace:

![image](https://user-images.githubusercontent.com/1091653/105011127-8857de00-5a77-11eb-98ae-7ba310fa0d4a.png)

It shows that almost time was spent on 'System.Reflection.Emit.DynamicMethod.CreateDelegate(Type, Object)'.

Test project & sample data file was attached.

[CsvHelperTest.zip](https://github.com/JoshClose/CsvHelper/files/5834765/CsvHelperTest.zip)

**Comment by JoshClose** [comment]
Thanks. There must be a cache miss because that should be called once per Type/ClassMap.

**Comment by JoshClose** [comment]
Found the cache miss. It was in the write also.

**Comment by JoshClose** [comment]
Fixed in 21.0.4 on NuGet. https://www.nuget.org/packages/CsvHelper/21.0.4
