### ISSUE TITLE
Malformed field fallback behavior changed from v19 to v20

### ISSUE THREAD

**Issue by airbreather** [JoshClose/CsvHelper#1657]
**Describe the bug**
CsvHelper's malformed field fallback seems to have changed from v19 to v20.

**To Reproduce**
1. Run the given program (see the bottom of this report) as-is, and note the output.
1. Change the `CsvHelperVersion` property in the .csproj from 19.0.0 to 20.0.0 (or higher).
1. Re-run the program, and note the output.

Note that you can bring `CsvHelperVersion` all the way down to 13.0.0 to see what happens on older versions.  I haven't bothered figuring out how to look at it on versions any older than that.

**Expected behavior**
I expected the output to be exactly the same across versions.

Instead, it changes.  For example, version 19 lists the first field in the first record with double-quotes around "friend", but version 20 does not.

**Additional context**
This is a test file that I use to ensure that my CSV library's malformed field fallback logic is the same as CsvHelper's.  I was going through and updating CsvHelper to v21 to update my own benchmarks, and I encountered test failures due to this.

## dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

## Program.cs
```csharp
using System;
using System.Globalization;
using System.IO;

using CsvHelper;
using CsvHelper.Configuration;

const string Nonstandard = @"""hello"" my ""friend""
""hello"" ,
good""bye"" to you,";

using var textReader = new StringReader(Nonstandard);
using var csvReader = new CsvReader(textReader, new CsvConfiguration(CultureInfo.InvariantCulture) { BadDataFound = null });
int i = 0;

while (csvReader.Read())
{
    Console.WriteLine($"Record #{++i}");
    int j = 0;
    foreach (string field in GetRecord(csvReader))
    {
        Console.WriteLine($"\tField #{++j}: {field}");
    }
}

static string[] GetRecord(CsvReader csvReader)
{
#if CSVHELPER_19_OR_LOWER
    return csvReader.Context.Record;
#elif CSVHELPER_20_OR_HIGHER
    return csvReader.Context.Parser.Record;
#else
#error I don't know what this version is.
#endif
}
```

## ConsoleApp0.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>

    <CsvHelperVersion>19.0.0</CsvHelperVersion>

    <DefineConstants Condition=" $(CsvHelperVersion.StartsWith('1')) ">$(DefineConstants);CSVHELPER_19_OR_LOWER</DefineConstants>
    <DefineConstants Condition=" $(CsvHelperVersion.StartsWith('2')) ">$(DefineConstants);CSVHELPER_20_OR_HIGHER</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="$(CsvHelperVersion)" />
  </ItemGroup>

</Project>
```

**Comment by JoshClose** [comment]
There is definitely an issue with parsing, but what is malformed about it?

**Comment by JoshClose** [comment]
It looks like that should be one big line, correct?

**Comment by JoshClose** [comment]
No ending quote to the field?

**Comment by airbreather** [comment]
> There is definitely an issue with parsing, but what is malformed about it?

The text used here is the first 3 lines of this file: https://github.com/airbreather/Cursively/blob/edc03786c892a42ba61a3e2dc26eee376061e0a4/test/Cursively.Tests/TestCsvFiles/nonstandard.csv

(I omitted the rest of that file because it's not relevant to this)

Each line has an error:
1. In line 1, the field continues on with more data after the closing-quote from "hello"
1. Line 2 is invalid the same way as line 1, just that the field ends with a field terminator instead of a line terminator
1. Line 3 has quotes that start in the middle of the field

**Comment by JoshClose** [comment]
Thanks. That's much easier to read. :)

So there are no quotes around fields at all?

**Comment by airbreather** [comment]
> So there are no quotes around fields at all?

The exact test case here is a synthetic one that's designed to verify that all of my own parser's code paths that handle fallback for non-RFC 4180 will yield the same result as CsvHelper.

In a real-world use case, you get essentially the same error in a file like this:
```
ID,NAME,OTHERNAME
1,"TEST 1","TEST 1"
2,"TEST 2";"TEST 2"
3,"TEST 3","TEST 3"
```
(note the semicolon instead of comma on the line with "TEST 2")

**Comment by JoshClose** [comment]
Nice job on Cursively btw. Very fast. I had my implementation faster than Sylvan until I started adding in all the compatibility and settings. I'm pretty happy where it is right now though.

I used to have Excel compatible fallback, meaning if you opened the file in Excel, CsvHelper would parse the same way.  I noticed at one point that Excel actually is different between versions on how it renders non standard CSV files, so when doing the latest parser I omitted the Excel compatibility. I'd rather have a more controllable way of parsing than some undocumented features for bad files.

The latest version has 3 modes now.
1. RFC4180 - This will parse using double quotes around fields that need escaping, and escaping double quotes.
2. Escape - This will only use an escape character to escape things.
3. NoEscape - This ignore quotes and escape characters.

Between those and trimming inside and outside of fields, you should be to handle most things.

I think what was happening with the example you posted there is, if it detected a malformed field it would continue reading until the next delimiter or newline and then that would finish the field. I can't imagine that actually being useful though.

**Comment by airbreather** [comment]
> Nice job on Cursively btw. Very fast. I had my implementation faster than Sylvan until I started adding in all the compatibility and settings. I'm pretty happy where it is right now though.

Thanks -- I'm also really impressed with CsvHelper's speed these days.  It's a lot better than where it was when I last evaluated it, that's for sure :grin:.

> I used to have Excel compatible fallback, meaning if you opened the file in Excel, CsvHelper would parse the same way. I noticed at one point that Excel actually is different between versions on how it renders non standard CSV files, so when doing the latest parser I omitted the Excel compatibility. I'd rather have a more controllable way of parsing than some undocumented features for bad files.

I brought it up because https://joshclose.github.io/CsvHelper still advertises:
![image](https://user-images.githubusercontent.com/3792815/105752941-ec662080-5f15-11eb-8fdb-fd8b228b2dd5.png)

And also because https://joshclose.github.io/CsvHelper/change-log doesn't identify this as an intentional breaking change between v19 and v20, so it was presumably unintended.  If the fix is to just update the documentation to reflect the change in behavior, then that's a perfectly fine fix, as far as I'm concerned.  I can deal with updating my test cases to use something other than CsvHelper to determine how a malformed file "should" be parsed.

**Comment by JoshClose** [comment]
I think I should change that one to something about escape parsing; since that's what a lot of Unix/SerDe parsers do.

I'm open to adding it back in, but I'd like some sort of logical reasoning on why it's doing what it's doing. People would open invalid files in Excel and say "see, Excel can do it", so that's why I did that a long time ago. They were usually hand written files for their testing purposes too which was causing most of the issues. 

Maybe coming up with a set of fallback behavior that can be documented would be a good idea. Doesn't necessarily have to follow Excel.

**Comment by JoshClose** [comment]
Here are the documented cases I had:
1. `one,"two" ,three`
2. `one, "two",three`
3. `1,"two" "2,3`
4. `a,b,"c\r\nd,e,f`  

Rules:
1. If you're in a quoted field and encounter a double quoted that isn't preceded by an escape, read until a delimiter or newline is hit. Anything else including escapes are ignored.
2. If a field starts with a space and the first non space is a double quote, start from there reading as a quoted field.
3. Same as 1
4. Same as 1

There are only 2 rules there I guess.

**Comment by airbreather** [comment]
One more case:

`one"two"three`

The rule could be, "If a field starts with something other than a double quote, read until a delimiter or newline is hit.  Anything else including escapes are ignored."

**Comment by JoshClose** [comment]
1 and 2 can also be solved by just setting `TrimOptions.Trim`.

**Comment by JoshClose** [comment]
It would still call the `BadDataFound` function though.

**Comment by JoshClose** [comment]
I'll add these back in and remove the "Excel" part from the docs. Lots of people use Google docs and I have no clue how that behaves. 

I'll also create a documentation page on how fallback works.

**Comment by JoshClose** [comment]
Check this out.
```
a, " b " ,c
a, "b",c
a,"b" ,c
a,b " c,d
a,b "" c,d
a,"b c" "d,e
a,b "c d" e "f g",h
```
![image](https://user-images.githubusercontent.com/114971/105910492-a16c0c00-5fee-11eb-9db3-b83c10ec96a3.png)

So Excel (version 2012 at least) does exactly what you suggested. If it doesn't start with a quote, just read everything until a delimiter or newline. That actually makes things a lot easier.

**Comment by JoshClose** [comment]
I got this working and can leave the "excel" stuff since there really is only one rule. That makes it simple. I'm allowing trimming which will affect that. If trim is enabled, the first 2 would parse as normal.

**Comment by airbreather** [comment]
> there really is only one rule

2 rules?  Ignoring trimming, since the logic should only kick in after trimming has been done:

1. If you're in a quoted field and encounter a double quoted that isn't preceded by an escape, read until a delimiter or newline is hit. Anything else including escapes are ignored.
1. If a field starts with something other than a double quote, read until a delimiter or newline is hit. Anything else including escapes are ignored.

**Comment by JoshClose** [comment]
That sounds right.

**Comment by JoshClose** [comment]
Can you check the unit tests here and see if there is anything missing? https://github.com/JoshClose/CsvHelper/blob/master/tests/CsvHelper.Tests/Parsing/ExcelCompatibilityTests.cs

**Comment by airbreather** [comment]
Unit tests look correct to me.  I'm not sure what `private class Simple` is doing in there.

**Comment by JoshClose** [comment]
lol... oops. I'll delete that.

**Comment by JoshClose** [comment]
This is in version 21.3.0 on NuGet. https://www.nuget.org/packages/CsvHelper/21.3.0

**Comment by JoshClose** [comment]
Thanks for all the help.
