### ISSUE TITLE
Only the build for .NET Standard 2.1 has a library version of v1.0.0

### ISSUE THREAD

**Issue by shibayan** [JoshClose/CsvHelper#1658]
**Describe the bug**

For .NET Standard 2.1 dll was built as version `1.0.0`, which causes problems when resolving assembly version.

**Screenshots**

![image](https://user-images.githubusercontent.com/1356444/105064101-d7296600-5abf-11eb-9a84-7a7a67c7e8f1.png)

**Comment by JoshClose** [comment]
Thanks. That is really weird.

**Comment by JoshClose** [comment]
I did another build and they all have the correct version. That's something I should never have to check. I have no clue why it happened either. Version 21.0.3 on NuGet has the correct version.
