### ISSUE TITLE
IgnoreQuotes property disappeared in the latest version

### ISSUE THREAD

**Issue by slim16165** [JoshClose/CsvHelper#1659]
Upgraded to the latest version and I can no longer assign value to properties of IReaderConfiguration and I had the same issue of [him](https://github.com/JoshClose/CsvHelper/issues/1651). I moved the property initialization to the constructor but IgnoreQuotes is missing. Tried to ask on SO [here](https://stackoverflow.com/questions/65793127/upgrading-from-csvhelper-fix-breaking-changes) but couldn't find any hint.

**Comment by JoshClose** [comment]
There is a `Mode` setting now. I should document what that is. The XML docs should explain it, but the site needs to have it also.

For your purposes, you need to set `Mode = ParserMode.Escape` instead. `RFC4180` mode will parse using quoted fields, then escapes inside that. `Escape` mode will not use quotes and will just escape the `CsvConfiguration.Escape` character.

**Comment by slim16165** [comment]
Thanks a lot for the answer,
I've tried both methods but I'm still missing something

HasHeaderRecord = true,
                    BadDataFound = null,
                    Delimiter = ",",
                    Quote = '"',
                    Mode=ParserMode.RFC4180,
                    Escape = '"',
                    //IgnoreQuotes = true

gives this exception

CsvHelper.TypeConversion.TypeConverterException: 'The conversion cannot be performed.
    Text: '.PON.'
    MemberType: System.Nullable`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
    TypeConverter: 'CsvHelper.TypeConversion.NullableConverter'
IReader state:
   ColumnCount: 0
   CurrentIndex: 2
   HeaderRecord:
[""]
IParser state:
   ByteCount: 0
   CharCount: 3074
   Row: 31
   RawRow: 31
   Count: 7
   RawRecord:
30,""",505369,17740,PON,"",505369,.".,.PON.,.505369.,.PON-.,.505369.,215894

the other configuration 
//PrepareHeaderForMatch = (string header, int index) => header.ToLower(),
                    HasHeaderRecord = true,
                    BadDataFound = null,
                    Delimiter = ",",
                    Quote = '"',
                    Mode=ParserMode.Escape,
                    Escape = '"',
                    //IgnoreQuotes = true


gives another error
CsvHelper.MissingFieldException: 'Field at index '12' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
IReader state:
   ColumnCount: 0
   CurrentIndex: 12
   HeaderRecord:
[""]
IParser state:
   ByteCount: 0
   CharCount: 3073
   Row: 61
   RawRow: 61
   Count: 12
   RawRecord:
30,""",505369,17740,PON,"",505369,.".,.PON.,.505369.,.PON-.,.505369.,215894

'

Any idea on where to start the investigation?

**Comment by JoshClose** [comment]
Do you have a couple lines of CSV that shows this failure that I can test with?

**Comment by slim16165** [comment]
Thank you very much

you can find the whole file here:
https://www.dropbox.com/s/xnm6q48bmylgupk/subtlex-it.csv?dl=0

Or those are the first lines

Progressivo,spelling,FREQcount,CDcount,dom_pos,dom_lemma,dom_lemma_freq,all_pos,all_pos_freq,all_lemma,all_pos_lemma,all_pos_lemma_freq,id
1,.,21040084,19439,SENT,.,21040084,...,.SENT.,.21040084.,.SENT-..,.21040084.,129227
2,,,5756133,19420,PON,,,5756133,.,.,.PON.,.5756133.,.PON-,.,.5756133.,56434
3,?,3166496,19388,SENT,?,3166496,.?.,.SENT.,.3166496.,.SENT-?.,.3166496.,369827
4,non,2340479,19387,ADV,non,2340479,.non.,.ADV.,.2340479.,.ADV-non.,.2340479.,69610
5,che,2293840,19391,PRO,che,1828391,.che.che.che.,.PRO.CON.ADJ.,.1828391.379865.85584.,.PRO-che.CON-che.ADJ-che.,.1828391.379865.85584.,204595
6,è,2288908,19352,VER,essere,3507888,.essere.,.VER.,.2288908.,.VER-essere.,.3507888.,205052
7,di,2202526,19418,PRE,di,2202523,.di.di.,.PRE.CON.,.2202523.3.,.PRE-di.CON-di.,.2202523.3.,343263
8,',1861188,19401,PON,',1861188,.'.,.PON.,.1861188.,.PON-'.,.1861188.,390319
9,!,1641909,19249,SENT,!,1641909,.!.,.SENT.,.1641909.,.SENT-!.,.1641909.,171282
10,un,1499479,19415,DET,un,1457920,.un.un.,.DET.PRO
.,.1457920.41559.,.DET-un.PRO-un.,.1457920.41559.,293435
11,e,1484558,19406,CON,e,1484558,.e.,.CON.,.1484558.,.CON-e.,.1484558.,229763
12,la,1463653,19409,DET,il,3975550,.il.la.,.DET.PRO
.,.1335246.128407.,.DET-il.PRO-la.,.3975550.128407.,349976
13,il,1411456,19393,DET,il,3975550,.il.,.DET.,.1411456.,.DET-il.,.3975550.,24802
14,a,1301494,19402,PRE,a,1300846,.a.a.,.PRE.CON.,.1300846.648.,.PRE-a.CON-a.,.1300846.648.,442017
15,per,1053276,19376,PRE,per,1043921,.per.per.,.PRE.CON.,.1043921.9355.,.PRE-per.CON-per.,.1043921.9355.,161925
16,una,816439,19383,DET,una,816439,.una.,.DET.,.816439.,.DET-una.,.816439.,363362
17,in,807943,19383,PRE,in,807943,.in.,.PRE.,.807943.,.PRE-in.,.807943.,24804
18,mi,758068,19315,PRO,mi,758068,.mi.,.PRO.,.758068.,.PRO-mi.,.758068.,286609
19,sono,755503,19341,VER,essere|sonare,752297,.essere|sonare.sono.,.VER.NOM.,.752297.3206.,.VER-essere|sonare.NOM-sono.,.752297.3216.,191145
20,ho,676657,19278,VER,avere,2620540,.avere.,.VER.,.676657.,.VER-avere.,.2620540.,88390
21,ha,622479,19299,VER,avere,2620540,.avere.,.VER.,.622479.,.VER-avere.,.2620540.,88395
22,ma,591714,19314,CON,ma,591346,.ma.ma
.,.CON.NOM.,.591346.368.,.CON-ma.NOM-ma.,.591346.368.,286601
23,lo,583474,19313,PRO,lo,457066,.lo.il
.,.PRO.DET.,.457066.126408.,.PRO-lo.DET-il.,.457066.3975550.,349978
24,l,562618,19171,VER,<unknown>,1069550,.<unknown>.<unknown>.<unknown>.,.VER.ADJ.NOM.,.556353.3472.2793.,.VER-<unknown>.ADJ-<unknown>.NOM-<unknown>.,.1069550.206355.4511888.,326989
25,cosa,552534,19272,NOM,cosa,642229,.cosa.,.NOM.,.552534.,.NOM-cosa.,.642229.,171192
26,le,543380,19356,DET,il,3975550,.il.le.,.DET.PRO
.,.471074.72306.,.DET-il.PRO-le.,.3975550.72306.,349973
27,con,537499,19339,PRE,con,537499,.con.,.PRE.,.537499.,.PRE-con.,.537499.,85130
28,ti,531801,19205,PRO,ti,480724,.ti.torre.,.PRO.VER.,.480724.51077.,.PRO-ti.VER-torre.,.480724.51294.,356662
29,no,519841,19192,ADV,no,518212,.no.no
.,.ADV.NOM.,.518212.1629.,.ADV-no.NOM-no.,.518212.1629.,76040
30,""",505369,17740,PON,"",505369,.".,.PON.,.505369.,.PON-.,.505369.,215894
31,i,495321,19339,DET,il,3975550,.il.,.DET.,.495321.,.DET-il.,.3975550.,217295
32,se,493420,19310,CON,se,427613,.se.se.se
.,.CON.PRO.NOM.,.427613.61226.4581.,.CON-se.PRO-se.NOM-se.,.427613.61226.4581.,420648
ᐧ

Il giorno mar 19 gen 2021 alle ore 21:39 Josh Close <
notifications@github.com> ha scritto:

**Comment by JoshClose** [comment]
Can you post the object you're trying to convert a row to?

**Comment by AR1ES** [comment]
I have same issue.
If field contains text with quote symbol `"` inside, like `...;some "name";....` (`;` is delimiter), I get error `Field at index '10' does not exist`.
Source CSV is not well formated, but eveything worked fine with `IgnoreQuotes = true`.
Changing `Mode` parameter does not solve problem. Moreover changing `Quote` parameter to another symbol does not affect anything, the problem persists

**Comment by JoshClose** [comment]
You would need to change `Mode` and `Escape`. I'm about to release a 3rd mode called `NoEscape` which ignores quotes and escapes.

**Comment by AR1ES** [comment]
Thank you. Changing `Escape` solved the problem.

**Comment by JoshClose** [comment]
Version 21.1.0 is in NuGet. https://www.nuget.org/packages/CsvHelper/21.1.0

**Comment by slim16165** [comment]
Thanks!

Il gio 21 gen 2021, 20:33 Josh Close <notifications@github.com> ha scritto:

**Comment by rodyfernandez** [comment]
Mode = CsvMode.NoEscape,
