### ISSUE TITLE
parser.Read returns boolean instead of string array???

### ISSUE THREAD

**Issue by robalexclark** [JoshClose/CsvHelper#1660]
I upgraded from 19 to 21 and it seems that a breaking change is to return a boolean rather than a string array.

       string[] headerRow = parser.Read(); //no longer compiles.

I can see this is in the list of breaking changes, but no alternative is listed - please advise,

**Comment by JoshClose** [comment]
```cs
while (parser.Read())
{
    string[] record = parser.Record;
    // or
    string field1 = parser[0];
    string field2 = parser[1];
}
```
