### ISSUE TITLE
CsvConfiguration change to Record is a breaking change for older language versions (Visual Basic, prior versions of C#)

### ISSUE THREAD

**Issue by MartinJSoles** [JoshClose/CsvHelper#1661]
I updated the nuget package reference to the latest version of CsvHelper (21.0.4 with .net 4.7.2, using Visual Studio 2017).

The change to make CsvConfiguration a Record type is a breaking one, Visual Basic can no longer set any properties. This is problematic as it is necessary to set the PrepareForHeaderMatch property to enable case insensitive matches.

Is there another method for making the header matches case insensitive? Is it possible to do this in the NameAttribute?

For now, I reverted to version 19 of the nuget package.

**Comment by JoshClose** [comment]
It should be fine in C#. I run tests for all the versions of .NET I publish and they all pass. 

For VB users, I added a constructor that takes in all those properties. They are optional named arguments. It's in the latest NuGet release.

**Comment by supunlivera** [comment]
I'm having this issue on C#, specifically when running on LinqPad.

![image](https://user-images.githubusercontent.com/7525917/106754588-0e9e2380-6625-11eb-99ee-7576336e6ca1.png)

**Comment by JoshClose** [comment]
```cs
void Main()
{	
	var s = new StringBuilder();
	s.Append("1,one\r\n");
	var config = new CsvConfiguration(CultureInfo.CurrentCulture)
	{
		HasHeaderRecord = false,
		HeaderValidated = null,
	};
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, config))
	{
		csv.Context.RegisterClassMap<RowMap>();
		csv.GetRecords<Row>().ToList().Dump();
	}
}

public class Row
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class RowMap : ClassMap<Row>
{
	public RowMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```
