### ISSUE TITLE
Property or indexer 'IWriterConfiguration.ShouldQuote' cannot be assigned to -- it is read only

### ISSUE THREAD

**Issue by DAustin85** [JoshClose/CsvHelper#1664]
I am trying to quote all my fields (including headers), following the articles online it should just be the following code?

```
            using (var csv = new CsvWriter(writer, cfg))
                {
                    csv.Configuration.ShouldQuote = (field, context) => true; // <-- Compile Time Error, Property is read only
                    csv.WriteHeader<RMLabelCSV>();
                    csv.NextRecord();
                    csv.WriteRecord(label);
                }
```

This happens regardless of using a CSVConfiguration object in the CsvWriter constructor or not.  Is this an issue or am I missing something?  Only resource I could find was your answer to this StackOverflow comment: https://stackoverflow.com/questions/53995909/csvhelper-wrap-all-values-with-quotes

**Comment by DAustin85** [comment]
Seems the issue is only in V21, have downgraded.  Why is there a new major version every day?  Can you slow down you version numbering a bit?

**Comment by JoshClose** [comment]
You need to set the properties or use the constructor of `CsvConfiguration` to set it's values. It's read only now. This is to fix threading issues people were having.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    ShouldQuote = (field, context) => true;
};
```

The documentation reflects this change and it's also in the change log. 

https://joshclose.github.io/CsvHelper/getting-started
https://joshclose.github.io/CsvHelper/change-log

CsvHelper versioning follows [semantic versioning](https://semver.org/) `major.minor.revision.build` or `breaking-change.feature.bug.build`. Any breaking change is going to get a major version bump. That includes any changes to interfaces, method signatures, property types, etc. If update and build and it fails, that requires a breaking change.

If I run across StackOverflow answers that need updating, I'll update them, but the source of truth is the documentation.

**Comment by DAustin85** [comment]
Ok, thanks for the clarification

**Comment by Matt-17** [comment]
@JoshClose 
Why does CsvWriter not accept IWriterConfiguration like CsvReader accepts IReaderConfiguration? 
Is this with purpose or a minor bug?

Sorry for asking in this old thread.

**Comment by JoshClose** [comment]
@Matt-17 It should. That's a bug.

**Comment by JoshClose** [comment]
@Matt-17 Just pushed a fix for it. It'll be in the next release.

**Comment by Matt-17** [comment]
Thank you. Makes it easier to copy settings from another csvwriter.
