### ISSUE TITLE
HasHeaderRecord was setable in v19 and is now Readonly in v20

### ISSUE THREAD

**Issue by codeowl1** [JoshClose/CsvHelper#1671]
The following code now fails as HasHeaderRecord is now read-only:

```
using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
{
    csv.Configuration.HasHeaderRecord = false;
    ....
}
```

It appears that every property in the IWriterConfiguration is now read-only.

**Comment by AltruCoder** [comment]
Per Josh, "You need to set the properties or use the constructor of CsvConfiguration to set it's values. It's read only now. This is to fix threading issues people were having." https://github.com/JoshClose/CsvHelper/issues/1664#issuecomment-764714249

**Comment by JoshClose** [comment]
And then you can pass the config into the constructor of `CsvWriter`.
