### ISSUE TITLE
Values set at BooleanTrueValues and BooleanFalseValues attributes were not correctly reflected in final output

### ISSUE THREAD

**Issue by adriank09** [JoshClose/CsvHelper#1672]
**Describe the bug**
Values set in attributes `BooleanTrueValues` and `BooleanFalseValues` are not reflected correctly in final output.

**To Reproduce**
Replace and execute the code below in a newly created .NET 5 console app.
```c#
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;

namespace CsvHelperDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            var f = new List<Foo> { new Foo() { Id = 1, Bar = true }, new Foo() { Id = 2, Bar = false } };

            using var writer = new StreamWriter(Console.OpenStandardOutput());
            using var csv = new CsvWriter(writer, new CsvConfiguration(CultureInfo.InvariantCulture));
            csv.WriteRecords(f);
        }
    }

    class Foo
    {
        public int Id { get; set; }

        [Name("Bar Column")]
        [BooleanTrueValues("Is Bar")]
        [BooleanFalseValues("Is Not Bar")]
        public bool Bar { get; set; }
    }
}
```

**Expected behavior**
Output should be shown as follows.
```
Id,Bar Column
1,Is Bar
2,Is Not Bar
```
**Actual behavior**
Output below is shown instead.
```
Id,Bar Column
1,True
2,False
```
**Additional context**

- Tested using version 21.1.1.
- The output of the code, once executed, at https://joshclose.github.io/CsvHelper/examples/configuration/attributes appears to be incorrect (i.e. True/False was displayed instead of yes/no).

**Comment by JoshClose** [comment]
boolean values and null values have never output when writing. I guess I don't see why they shouldn't though. It'll pick the first one in the list then.

**Comment by JoshClose** [comment]
This is in 21.2.0 on NuGet. https://www.nuget.org/packages/CsvHelper/21.2.0

**Comment by adriank09** [comment]
Confirmed with correct output shown. Thanks!
