### ISSUE TITLE
Unable to set MissingFieldFound in CsvConfiguration constructor

### ISSUE THREAD

**Issue by coderpatros** [JoshClose/CsvHelper#1673]
**Describe the bug**
When initialising a CsvConfiguration using the constructor you are unable to set MissingFieldFound to null.

**To Reproduce**

```
var csvReaderConfiguration = new CsvHelper.Configuration.CsvConfiguration(
    cultureInfo: CultureInfo.InvariantCulture,
    missingFieldFound: null);
```

Inspect MissingFieldFound and it will not be null.

Doing this works

```
var csvReaderConfiguration = new CsvHelper.Configuration.CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture)
{
    MissingFieldFound = null
};
```

You can see in the constructor method that a value of null for the parameter missingFieldFound is essentially ignored.

https://github.com/JoshClose/CsvHelper/blob/725431d7dd467da3bc1700757c5d9f73e92d42ae/src/CsvHelper/Configuration/CsvConfiguration.cs#L354

**Expected behavior**
This was quite counter intuitive to me. But might be as designed. But I would expect that passing a supported value for the missingFieldFound parameter would have an affect.

**Comment by JoshClose** [comment]
That's a bug. I'll have to think of something. The constructor is only there for older platforms that can't use init. Maybe if people use the constructor they need to specify an empty function or something. If that's the case, I'll add a note to the constructor docs about it.

**Comment by JoshClose** [comment]
I can't think of anything good here. I think if you're using the constructor you'll just have to specify an empty delegate.

```cs
MissingFieldFound = () => { }
```

I can update the XML docs and other docs to show that I guess.

**Comment by JoshClose** [comment]
Is this clear enough?

```cs
/// <summary>
/// Initializes a new instance of the <see cref="CsvConfiguration"/> class.
/// Any arguments passed in as null will use their default value instead.
/// If you need to set a callback like <see cref="MissingFieldFound"/> to null, set it to an empty
/// function instead.
/// <code>
///		missingFieldFound: () => { }
/// </code>
/// </summary>
```

**Comment by sholland1** [comment]
I think this should be `(_1, _2, _3) => { }`, since the `MissingFieldFound` delegate type has three parameters.

**Comment by JoshClose** [comment]
@sholland1 Good point.

**Comment by JoshClose** [comment]
@sholland1 Btw, with `discards` you can use all `_`. https://docs.microsoft.com/en-us/dotnet/csharp/discards

**Comment by coderpatros** [comment]
Sounds like a reasonable workaround to me. Thanks!

**Comment by JoshClose** [comment]
Great!
