### ISSUE TITLE
BC30657, has a return type that is not supported or parameter types that are not supported.

### ISSUE THREAD

**Issue by gordonwalkedby** [JoshClose/CsvHelper#1675]
**Describe the bug**
I am using v21.2.1 csvhelper in VB .NET 5 ,i write a CsvConfiguration and want to change its properties.   
when i try to set a property, the error shows. every property is getting error.

**To Reproduce**
1. create a vb .net core project.
2. write the code like this.
```vb
    Sub WriteToCSV(l As Object(), writeHeader As Boolean)
        Using s = csvFile.AppendText
            Dim config As New CsvHelper.Configuration.CsvConfiguration(Thread.CurrentThread.CurrentCulture)
            With config
                .HasHeaderRecord = false
                .Encoding = New UTF8Encoding
                .MissingFieldFound = Nothing
            End With
            Using writer As New CsvWriter(s, config)

            End Using
        End Using
    End Sub
```

**Expected behavior**
when i use the v19.0 csvhelper , anything is good.

**Screenshots**
![](https://s3.ax1x.com/2021/01/26/sj7Ffg.png)

**Comment by ratamahatta88** [comment]
It seems that you have to move them to constructor because properties don't have setters anymore.

**Comment by JoshClose** [comment]
Properties have `init` setters, which means you can only set them on initialization. Until VB.NET updates their language to support this, you'll have to use constructor parameters as @ratamahatta88 said.
