### ISSUE TITLE
Unable to set Configuration.ShouldSkipRecord (v21.2.1)

### ISSUE THREAD

**Issue by holden525** [JoshClose/CsvHelper#1676]
Unable to set Configuration.ShouldSkipRecord in (v21.2.1) but was able to in (v19.0.0) with the following:

csv.Configuration.ShouldSkipRecord = (x) => x[0].StartsWith("Disclaimer");

Error message said this property only had a getter, no setter is defined...

**Comment by JoshClose** [comment]
You need to set it on creation and pass the config in.

https://joshclose.github.io/CsvHelper/getting-started

**Comment by holden525** [comment]
Thanks for the quick response.

 

CsvConfiguration() cannot be found.  Is there a directive I’m missing?

 

Regards,

Holden

**Comment by JoshClose** [comment]
```cs
var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
{
    ShouldSkipRecord = (x) => x[0].StartsWith("Disclaimer")
};
```

**Comment by holden525** [comment]
Thanks, that did the trick…

 

Regards,

Holden

**Comment by chippoman** [comment]
Did a new version break this? On 26.0.1 this doesn't work:

var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    HasHeaderRecord = false,
                    ShouldSkipRecord = (row) => row[0].Contains("For Period")
                };

The VS error is: 
error CS0021: Cannot apply indexing with [] to an expression of type 'ShouldSkipRecordArgs'

**Comment by JoshClose** [comment]
```cs
var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
{
    HasHeaderRecord = false,
    ShouldSkipRecord = (args) => args.Row[0].Contains("For Period")
};
```

**Comment by Eddict** [comment]
you sure?

> CS1061	'ShouldSkipRecordArgs' does not contain a definition for 'Row' and no accessible extension method 'Row' accepting a first argument of type 'ShouldSkipRecordArgs' could be found (are you missing a using directive or an assembly reference?)

Record seems to do the trick..

`args.Record[0].Contains("For Period")`

**Comment by faridomarzadeh** [comment]
> you sure?
> 
> > CS1061	'ShouldSkipRecordArgs' does not contain a definition for 'Row' and no accessible extension method 'Row' accepting a first argument of type 'ShouldSkipRecordArgs' could be found (are you missing a using directive or an assembly reference?)
> 
> Record seems to do the trick..
> 
> `args.Record[0].Contains("For Period")`


            var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = false,
                ShouldSkipRecord = (args) => args.Record[0].Contains("For Period")
            };

**Comment by JavierBuffa** [comment]
> 
>         var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
>         {
>             HasHeaderRecord = false,
>             ShouldSkipRecord = (args) => args.Record.Contains("For Period")
>         };
> 
as for the latest update (28.0.1) on CsvHelper there is no more Record attribute for ShouldSkipRecordArgs

**Comment by elfico** [comment]
@JoshClose is there another way around this? Just updated and it broke my code

**Comment by niteshsinghal85** [comment]
This works for me in with 28.0.1 
ShouldSkipRecord = args => args.Row.Parser.Record.All(string.IsNullOrWhiteSpace)
