### ISSUE TITLE
RawRecord not longer accessible via IReaderRow.Context

### ISSUE THREAD

**Issue by codeowl1** [JoshClose/CsvHelper#1681]
After upgrading to version 21 I get the following error relating to code that references: row.Context.RawRow, in the below example:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1061	'CsvContext' does not contain a definition for 'RawRow' and no accessible extension method 'RawRow' accepting a first argument of type 'CsvContext' could be found (are you missing a using directive or an assembly reference?)	

`
    public class DecimalTypeConverter: DefaultTypeConverter
    {
        public DecimalTypeConverter() { }

        public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
        {
            try
            {
                SqlDecimal result = 0;
                ... // removed as irrelevant to the issue
                return result;
            }
            catch (Exception ex)
            {
                string column_name = "Column# " + memberMapData.Index.ToString();
                if (memberMapData.Names.Count > 0)
                {
                    column_name = memberMapData.Names[memberMapData.Index];
                }
                throw new Exception("An Exception occured attempting to convert data '" + CodeOwlUtils.ToStr(text) + "' in Column '" + column_name + "' on Row# " + row.Context.RawRow.ToString() + " to Decimal." + Environment.NewLine + "Row: " + row.Context.RawRecord, ex);
            }
        }
`

**Comment by JoshClose** [comment]
It's on the parser now.

```cs
row.Parser.RawRow
```
