### ISSUE TITLE
Enum conversion broken in 22.0.0

### ISSUE THREAD

**Issue by mihalios** [JoshClose/CsvHelper#1682]
Enum parsing worked fine on 21.3.1, I upgraded to 22.0.0 and got the below exception, with nothing else changed in my code:
```
Reading Exception Occured
CsvHelper.TypeConversion.TypeConverterException: The conversion cannot be performed.
    Text: 'Dog'
    MemberType: src.Models.Animal
    TypeConverter: 'CsvHelper.TypeConversion.EnumConverter'
IReader state:
   ColumnCount: 0
   CurrentIndex: 8
   HeaderRecord:
[""]
IParser state:
   ByteCount: 0
   CharCount: 59062
   Row: 718
   RawRow: 718
   Count: 9
   RawRecord:
```
And enum definition:

```cs
internal enum Animal
    {
        Unset,
        Dog, 
        Cat
    }
```

**Comment by JoshClose** [comment]
It's trying to convert the string `"Animal"` to one of the enum values?

**Comment by mihalios** [comment]
Sorry, typo! Updated the issue description.

It's trying to convert a valid Enum value. Like I said I only see this in 22.0.0

**Comment by JoshClose** [comment]
I'll need some more information. This works:
```cs
void Main()
{
	var s = new StringBuilder();
	s.Append("Id,Name,Animal\r\n");
	s.Append("1,one,Dog\r\n");
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
	};
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, config))
	{
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
	public Animal Animal { get; set; }
}

public enum Animal
{
	Unset,
	Dog,
	Cat
}
```

The enum values are case sensitive now though, so if it's actually `dog` instead of `Dog` it won't work. If that's the case, you'll just need to set an option to make it ignore case.

**Comment by JoshClose** [comment]
I am seeing a bug if you turn on ignore case that it's not making it to the converter. I'm looking into that.

**Comment by JoshClose** [comment]
I figured out the issue. Writing some more unit tests for ignore case and the fix will be out shortly.

I still need to make sure your issue is case sensitivity though.

**Comment by JoshClose** [comment]
22.1.0 is out on NuGet. This has the fix for the value not making it to the converter when reading. I also added an `[EnumIgnoreCase]` attribute.

You can ignore via class map, attribute, or globally for the type (`Animal`).

**Comment by mihalios** [comment]
Thank you very much Josh.

**Comment by JoshClose** [comment]
No problem. Was it a casing issue?

**Comment by mihalios** [comment]
Affirmative.

So case sensitivity was added in 22.0.0, from what I understand?

**Comment by JoshClose** [comment]
Well, case insensitivity was added a few versions back when you could add the `[Name("name")]` attribute to an enum value. That was a mistake because `Enum.Parse` is case sensitive by default. I fixed a bug where there was issues when there were duplicate enum names with only casing differences and duplicate values. It made sense to make it case sensitive by default when the option for ignore case was added.

**Comment by junalmeida** [comment]
Is there a way to set it back to case insensitive globally instead on each Enum mapping?

**Comment by JoshClose** [comment]
You can do globally per type.

```cs
csv.Context.TypeConverterOptionsCache.GetOptions<MyEnum>().EnumIgnoreCase = true;
```

**Comment by junalmeida** [comment]
Is there a way to do globally by any `Enum`?

**Comment by JoshClose** [comment]
No. I would need to do some special handling for that to work. Create a feature request if you'd like this added.

**Comment by junalmeida** [comment]
Will do, I do think this should come available along with the non-backward compatible change of ignoring case on any enums. Thx
