### ISSUE TITLE
Compilation Error "'IWriterConfiguration' does not contain a definition for 'RegisterClassMap'"

### ISSUE THREAD

**Issue by gberkheiser** [JoshClose/CsvHelper#1683]
**Describe the bug**
Updated to the most-recent version of Csv halper.  Build fails with the above error. The project that uses this library was last built in October 2020.

**To Reproduce**
1. Update to the latest using nuget.
2. Build the project

**Expected behavior**
The expectation was that code that previously built and ran would still be in the same condition.

**Additional context**
Again, the code was last built in October of 2020 with no errors.

**Comment by JoshClose** [comment]
The configuration is now read only so any mutable things got moved onto the context.
```cs
csv.Context.RegisterClassMap<MyMap>();
```

**Comment by gberkheiser** [comment]
Thank-you very much for the quick reply.  I appreciate it.

I’m on a bit of a time crunch with this project and need to get updates to the customer so they can release.

Best Regards,
Gary Berkheiser


Gary Berkheiser
Software Engineer
gberkheiser@syncro.com<mailto:gberkheiser@syncro.com>
215.359.9329

886 Town Center Dr.
Langhorne, PA 19047
[cid:image001.png@01D6F92E.F82BF310]<https://www.linkedin.com/company/syncro-technology-corp./>   [cid:image002.png@01D6F92E.F82BF310] <https://www.facebook.com/syncromedical/>    [cid:image003.png@01D6F92E.F82BF310] <https://twitter.com/SyncroMedical>
[cid:image004.png@01D6F92E.F82BF310]<https://syncro.com/>
