### ISSUE TITLE
Delimiter  readonly now ?

### ISSUE THREAD

**Issue by kiquenet** [JoshClose/CsvHelper#1688]
This code not compiles now, for latest version.

Delimiter  readonly ?

```
 using (var writer = new StreamWriter(ficheroCSV, false, Encoding.UTF8)) // Encoding.Default))
            using (var csv = new CsvHelper.CsvWriter(writer, CultureInfo.InvariantCulture))
            {
                csv.Configuration.Delimiter = ";";
                csv.WriteRecords(records);
            }
```

**Comment by JoshClose** [comment]
Configuration is read only now to avoid threading issues. You need to create the config ahead of time and pass it into the reader/writer.

The docs were updated to reflect this. https://joshclose.github.io/CsvHelper/getting-started
The change log shows the breaking change. https://joshclose.github.io/CsvHelper/change-log

**Comment by dma550** [comment]
Sorry to reopen, I am scratching my head here.  I had to do a massive update of some older code and now all configuration is broken.  I realize there was a breaking change but it doesn't make sense that examples from here don't work.

Note I copied this verbatim from the examples page:
             var config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    PrepareHeaderForMatch = (string header, int index) => header.ToLower(),
                };

PrepareHeaderForMatch is throwing a compile error.
CS1913	Member 'PrepareHeaderForMatch' cannot be initialized. It is not a field or property.

I am temporarily using an older machine, .net 4.8.  Do I have to use an older version of CSVhelper?

**Comment by dma550** [comment]
ok, so an update to VS sends the syntax errors to the bin.  Must be a c# version thing.

**Comment by JoshClose** [comment]
Yeah, you need a certain version of msbuild and c# which comes with a visual studio update. The update was from November iirc.

**Comment by JoshClose** [comment]
Version 23.0.0 has settable properties again.

**Comment by InteXX** [comment]
@JoshClose 

> Configuration is read only now to avoid threading issues. You need to create the config ahead of time and pass it into the reader/writer.

OK, fair 'nuff. But the property there is readonly also!

```
Dim oConfig As IReaderConfiguration
oConfig = New CsvConfiguration(CultureInfo.InvariantCulture)
oConfig.Delimiter = "|"
```

Is there no longer a way to use a custom delimiter? (Using the latest version, v30.0.0)

**Comment by JoshClose** [comment]
It should be settable. https://github.com/JoshClose/CsvHelper/blob/701ede5487cabf28b31a2dbea160331cc09f9a0b/src/CsvHelper/Configuration/CsvConfiguration.cs#L47

**Comment by InteXX** [comment]
Say, while I've got you...

My CSV headers start on line 2 and the data starts on line 4. Can that be handled?
