### ISSUE TITLE
MissingFieldFound = null, is not working in version 22.1

### ISSUE THREAD

**Issue by buftoronto** [JoshClose/CsvHelper#1693]
**Describe the bug**

Setup:  Version 22.1.2. setting MissingFieldFound = null in the CsvConfiguration. I use a ClassMap with Name mapping to the header of the CSV file. I have a CSV file where one field of a row is blank. When reading the file, CsvReader reads the value from the next non-blank column value on the row to this blank field. I also tried to set default property value in my record class, e.g.

public string User { get; set; } = ""

Also tried setting the default value in Mapper, e.g.

Map(m => m.User).Name("User Name").Default("Test"); 

I also tried to define a lambda expression for MissingFieldFound. But the issue is the same.

When I tried version 20.0.0 the issue doesn't exist. The 20.0.0 behavior is the same as that in 7.1 where our project referenced before. It looks like the bug was introduced recently.

**To Reproduce**

**Expected behavior**

Default value of the string should be filled with an empty string, instead of replacing with the next available value on the row. 

**Screenshots**

**Additional context**

**Comment by JoshClose** [comment]
This works for me in the latest version.

```cs
void Main()
{
	var s = new StringBuilder();
	s.Append("Id,Name\r\n");
	s.Append("1\r\n");
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		MissingFieldFound = null,
	};
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, config))
	{
		csv.Context.RegisterClassMap<FooMap>();
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```

**Comment by buftoronto** [comment]
Hello Josh,

Thank you very much for the quick response. I copied your code in VS 2019 to test (CsvHelper version 22.1.2). The issue was that if there is a blank data in the row, the next available non-blank data will move to that column to fill the value. If there is another blank field the next non-blank field will move forward to fill. I modified your code to make the data 3 columns - the name value is blank (the middle column). I cannot replicate the issue so far. But when I added the TrimOptions option, it crashes. It might be those properties that caused the issue. We have other properties: AllowComments (true), Delimiter(tab), TrimOptions(Trim), Encoding (UTF8). We read from a file with 30 columns. 

Note: strange I cannot use object initializer to set properties. e.g. MissingFieldFound. I had to set the values in constructor. Not sure why. I tried on both .net core and .net framework.

static void Main(string[] args)
		{
			var s = new StringBuilder();
			s.Append("Id\tName\tId2\r\n");
			s.Append("1" + "\t\t" + "2\r\n");
			MissingFieldFound mising = null;
			bool hasHeader = true;
			string delim = "\t";
			TrimOptions to = TrimOptions.Trim;
			var config = new CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture,
				missingFieldFound: mising,
				hasHeaderRecord: hasHeader,
				delimiter: delim);
				//,trimOptions:to);

			using (var reader = new StringReader(s.ToString()))
			using (var csv = new CsvReader(reader, config))
			{
				csv.Context.RegisterClassMap<FooMap>();
				var records = csv.GetRecords<Foo>().ToList();
				Console.Write(records);
			}
		}

**Comment by JoshClose** [comment]
> The issue was that if there is a blank data in the row, the next available non-blank data will move to that column to fill the value.

How else would that work? If you have 30 columns and one is missing somewhere in the middle, how would you know which one?

> Note: strange I cannot use object initializer to set properties. e.g. MissingFieldFound. I had to set the values in constructor. Not sure why. I tried on both .net core and .net framework.

You might need to change your language version to 9 or Latest for init to work. It works when compiling net45 for me. 

Also, when using the constructor you can't set delegates to `null`. You'll need to set to a no-op instead.
```cs
MissingFieldFound missing = (_, _, _) => { };
```

**Comment by buftoronto** [comment]
> > The issue was that if there is a blank data in the row, the next available non-blank data will move to that column to fill the value.
> 
> How else would that work? If you have 30 columns and one is missing somewhere in the middle, how would you know which one?
> 

I reviewed the txt file in Excel and found the missing data columns. In code instead of using csv.GetRecords to get them all, I loop each row with GetRecord<> in a while loop. Set a break point to check the return of GetRecord for one row. Anyway the first row has a few missing data. Please note: all properties in the class definition are string type (e.g. Foo). For example, if I have the header columns: Id, Name, Id2, first row data: 1, blank, 2, I should get the result: Id ->"1", Name -> "", Id2 -> "2". But I got  Id ->"1", Name -> "2", Id2 -> "". 

		public class Foo
		{
			public string Id { get; set; }
			public string Name { get; set; }
			public string Id2 { get; set; }
		}
> > Note: strange I cannot use object initializer to set properties. e.g. MissingFieldFound. I had to set the values in constructor. Not sure why. I tried on both .net core and .net framework.
> 
> You might need to change your language version to 9 or Latest for init to work. It works when compiling net45 for me.
> 
Used <TargetFramework>netcoreapp3.1</TargetFramework> and  <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>. Maybe I need to install .Net library? I created the new project as Console App from VS 2019.
> Also, when using the constructor you can't set delegates to `null`. You'll need to set to a no-op instead.
> 
> ```cs
> MissingFieldFound missing = (_, _, _) => { };
I have to change (x, y, z) => { } to make it working. Now it can run without crashing. I can reproduce the issue. Check the result: I got  Id ->"1", Name -> "2", Id2 -> "". Please run the program I submitted to verify. Thanks. 
> ```

**Comment by JoshClose** [comment]
Oh so you're saying it looks like `1,,2`? When you say the field is missing, I'm thinking `1,2`, as in 2 fields instead of 3.

I ran the program:
```cs
void Main()
{
	var s = new StringBuilder();
	s.Append("Id\tName\tId2\r\n");
	s.Append("1" + "\t\t" + "2\r\n");
	MissingFieldFound mising = null;
	bool hasHeader = true;
	string delim = "\t";
	TrimOptions to = TrimOptions.Trim;
	var config = new CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture,
		missingFieldFound: mising,
		hasHeaderRecord: hasHeader,
		delimiter: delim);
	//,trimOptions:to);

	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, config))
	{
		csv.Context.RegisterClassMap<FooMap>();
		var records = csv.GetRecords<Foo>().ToList();
		Console.Write(records);
	}
}

private class Foo
{
	public string Id { get; set; }
	public string Name { get; set; }
	public string Id2 { get; set; }
}

private class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.Id2);
	}
}
```
This is my output.
![image](https://user-images.githubusercontent.com/114971/107097834-7a25f380-67d3-11eb-9683-3864e3c29f72.png)

**Comment by buftoronto** [comment]
Hi Josh,

Sorry. To be clear
1. Uncomment the code for CsvConfiguration: //,trimOptions:to); 
2. Change to MissingFieldFound mising = (x, y, z) => { };

Then I think you can reproduce the issue.

If you have MissingFieldFound mising = null and have the configuration on: ,trimOptions:to, you will get a crash.

**Comment by buftoronto** [comment]
This following is the whole testing code

using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace CsvHelperTest
{
   class Program
   {
		static void Main(string[] args)
		{
			var s = new StringBuilder();
			s.Append("Id\tName\tId2\r\n");
			s.Append("1" + "\t\t" + "2\r\n");
			MissingFieldFound mising = (x, y, z) => { };
			bool hasHeader = true;
			string delim = "\t";
			TrimOptions to = TrimOptions.Trim;
			var config = new CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture,
				missingFieldFound: mising,
				hasHeaderRecord: hasHeader,
				delimiter: delim
				,trimOptions:to);

			using (var reader = new StringReader(s.ToString()))
			using (var csv = new CsvReader(reader, config))
			{
				csv.Context.RegisterClassMap<FooMap>();
				var records = csv.GetRecords<Foo>().ToList();
				Console.Write(records);
			}
		}

		public class TestCsvHelper
		{
			public void TestCsv()
			{
				var s = new StringBuilder();
				s.Append("Id,Name\r\n");
				s.Append("1\r\n");
				MissingFieldFound mising= null;
				bool hasHeader = true;
				var config = new CsvConfiguration
					(cultureInfo:CultureInfo.InvariantCulture, missingFieldFound: mising, hasHeaderRecord: hasHeader);

				using (var reader = new StringReader(s.ToString()))
				using (var csv = new CsvReader(reader, config))
				{
					csv.Context.RegisterClassMap<FooMap>();
					Console.WriteLine(csv.GetRecords<Foo>().ToList());
				}
			}
		}

		public class Foo
		{
			public string Id { get; set; }
			public string Name { get; set; }
			public string Id2 { get; set; }
		}

		public class FooMap : ClassMap<Foo>
		{
			public FooMap()
			{
				Map(m => m.Id);
				Map(m => m.Name);
				Map(m => m.Id2);
			}
		}
   }
}

**Comment by buftoronto** [comment]
public class TestCsvHelper is not used in the above code.

**Comment by JoshClose** [comment]
I figured out the issue. You're using `TrimOptions.Trim` which will trim whitespace from the start/end of a field. You changed the delimiter to `\t` which is a whitespace character. After the first delimiter it sees the `\t` as whitespace and trims it.

Change your whitespace characters and it'll work correctly.

```cs
whiteSpaceChars: new[] { ' ' },
```

**Comment by buftoronto** [comment]
Hi Josh, thank you for the tip.
