### ISSUE TITLE
Replace TypeConverterCache 

### ISSUE THREAD

**Issue by TimSirmovics** [JoshClose/CsvHelper#1700]
**Describe the bug**
Previously I was able to replace the TypeConverterCache with my own implementation which derives from `TypeConverterCache` using
`csvReader.Configuration.TypeConverterCache = new MyTypeConverterCache();`
I tried to replace this with
`csvReader.Context.TypeConverterCache = new MyTypeConverterCache();`

But this is not possible due to the TypeConverterCache being init only.

**To Reproduce**
```
var csvReader = new CsvReader(textReader, CultureInfo.CurrentCulture);
csvReader.Context.TypeConverterCache = new SomeCustomTypeConverterCache();
```

**Expected behavior**
I was expecting to be able to replace the TypeConverterCache as per previous versions.

**Additional context**
If necessary I can go into detail about why I replace the TypeConverterCache.

**Comment by JoshClose** [comment]
I would like to know why. I'm curious what changes you're making to the cache.

**Comment by JoshClose** [comment]
This is now settable in version 23.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/23.0.0

I would still like to know why though. ;)

**Comment by TimSirmovics** [comment]
I have my own internal library which wraps CsvHelper to add some additional requirements.
One requirement is that we often allow invalid fields in a CSV (e.g. a character in an integer field) if that field is an optional field for that type of file. Sometimes we dynamically determine if the field is optional based on parameters like the source of the file.
We process a lot of CSV files, sometimes manually created by people, and have to be very flexible in what we allow.
If we encounter an invalid field, we want to still read the rest of the record.

The structure of the library uses `Read()` to go over each row and then `GetRecord<T>()` to read each record.

If  `GetRecord<T>()` encounters an error reading a field it will return a default instance of `T` without any of the previously read fields, and will not continue to read the rest of the fields.

The way I worked around this was to replace each `TypeConverter` with my own implementation which records the error and returns a default instance of the field:

```
internal class ErrorLoggingTypeConverter : ITypeConverter
{
    private readonly ITypeConverter _actualTypeConverter;
    private readonly Type _type;
    private readonly Action _logError;

    internal ErrorLoggingTypeConverter(ITypeConverter actualTypeConverter, Type type, Action logError)
    {
        _actualTypeConverter = actualTypeConverter;
        _type = type;
        _logError = logError;
    }

    public string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
    {
        return _actualTypeConverter.ConvertToString(value, row, memberMapData);
    }

    public object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
    {
        try
        {
            return _actualTypeConverter.ConvertFromString(text, row, memberMapData);
        }
        catch (Exception)
        {
            _logError();
            return _type.IsClass ? null : Activator.CreateInstance(_type);
        }
    }
}
```

The errors are then handled after the row has been read.

I was replacing the `TypeConverterCache` with another implementation to facilitate this:

```
internal class ErrorLoggingTypeConverterCache : TypeConverterCache
{
    private readonly Dictionary<Type, ITypeConverter> _typeConverters;
    private readonly Action _logError;

    internal ErrorLoggingTypeConverterCache(Action logError)
    {
        _typeConverters = (Dictionary<Type, ITypeConverter>)PrivateValueAccessor.GetPrivateFieldValue(typeof(TypeConverterCache), "typeConverters", this);
        _logError = logError;

        ReplaceAllTypeConvertersWithErrorLoggingTypeConverters();
    }

    internal new void AddConverter(Type type, ITypeConverter typeConverter)
    {
        _typeConverters[type] = new ErrorLoggingTypeConverter(typeConverter, type, _logError);
    }

    internal new void AddConverter<T>(ITypeConverter typeConverter)
    {
        _typeConverters[typeof(T)] = typeConverter;
    }

    private void ReplaceAllTypeConvertersWithErrorLoggingTypeConverters()
    {
        foreach (var typeConverter in _typeConverters.ToDictionary(d => d.Key, d => d.Value))
            AddConverter(typeConverter.Key, typeConverter.Value);
    }
}
```

However I wasn't sure if this would be made available again so I just replaced the type converters after creating the `CsvReader`, and then make sure any that I add are wrapped in an `ErrorLoggingTypeConverter`:

```
private void ReplaceAllTypeConvertersWithErrorLoggingTypeConverters(CsvReader csvReader)
{
    var typeConverters = (Dictionary<Type, ITypeConverter>)PrivateValueAccessor.GetPrivateFieldValue(
        typeof(TypeConverterCache),
        "typeConverters",
        csvReader.Context.TypeConverterCache);

    foreach (var typeConverter in typeConverters.ToDictionary(d => d.Key, d => d.Value))
    {
        csvReader.Context.TypeConverterCache.RemoveConverter(typeConverter.Key);
        csvReader.Context.TypeConverterCache.AddConverter(typeConverter.Key, new ErrorLoggingTypeConverter(typeConverter.Value, typeConverter.Key, LogError));
    }
}
```

The only alternative to this I could see was reading each field separately instead of using `GetRecord<T>()`, but this would involve re-creating all the work to hydrate a record that CsvHelper already handles.

I'm not sure if anyone else has this requirement, but if there was something similar to `ReadingExceptionOccurred` that was invoked on a field by field basis when using  `GetRecord<T>()`, that would be great.

**Comment by TimSirmovics** [comment]
Would it be worth submitting a PR to handle per field errors when using `GetRecord<T>()`? Or do you think there is a better way to achieve the above?

(Or do you think the above is so wacky that nobody else would have the same requirement)

**Comment by JoshClose** [comment]
I've been having a discussion with someone about creating a pipeline to process fields and records. This would allow for any step in the pipeline to easily be changed or replaced. This would make what you're trying to do much easier.

I just created 2 feature requests that should make your life easier. There could be some more convenience methods within this area also.

https://github.com/JoshClose/CsvHelper/issues/1736
https://github.com/JoshClose/CsvHelper/issues/1737

I created a discussion on the pipeline too. Please join in the discussion. 

https://github.com/JoshClose/CsvHelper/discussions/1738
