### ISSUE TITLE
Cannot process a stream downloaded through ftp

### ISSUE THREAD

**Issue by buftoronto** [JoshClose/CsvHelper#1702]
**Describe the bug**
CsvHelper Reader **version 22.1.2** and **20.0.0**. For both versions the same code can read the same local file, but cannot read  the same downloaded file from a FTP server. I tried to upload the file with both ASCII and Binary modes to test but both failed to be read. The same code works to read the ftp file in **version 7.1**. I have to rollback to version 7.1.

The program crashes at the first GetRecord<> in a while loop.

Error message like "Heade with name 'ABC' was not found. ...". Looks like it cannot read every column.

Configuration like:

MissingFieldFound mising = (x, y, z) => { };
			bool hasHeader = true;
			string delim = "\t";
			TrimOptions to = TrimOptions.Trim;
var config = new CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture,
				missingFieldFound: mising,
				hasHeaderRecord: hasHeader,
				delimiter: delim
				,trimOptions:to,
				whiteSpaceChars: new[] { ' ' });

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JoshClose** [comment]
If you set your delimiter to `\t` and turn trim on, you need to remove `\t` from your whitespace characters.
```cs
WhiteSpaceChars = new[] { ' ' };
```

**Comment by buftoronto** [comment]
Thanks Josh.

I added that line. Same results.

**Comment by buftoronto** [comment]
Version 20.0 doesn't need to add that line. Same results.

**Comment by JoshClose** [comment]
Is there a way I can test this?

**Comment by buftoronto** [comment]
Hi, that is company FTP site connected with SSH. I cannot reproduce the issue elsewhere.

**Comment by buftoronto** [comment]
I also tried changing setting: Encoding = Encoding.UTF8 and Encoding.ASCII in the CsvHelper configuration with no avail.

**Comment by JoshClose** [comment]
The encoding would need to be set on the `TextReader`.

**Comment by buftoronto** [comment]
It might be encoding issue. But I can use StreamReader to read the stream and loop each line without issue. 

var sRead = new StreamReader(ftpStream);
string line;
while ((line = sReader.ReadLine()) != null)
{
   Console.WriteLine(line);
}

**Comment by JoshClose** [comment]
Try using `CsvParser` instead of `CsvReaderr` and see what it spits out.

**Comment by buftoronto** [comment]
Using CsvParser. I can loop with it.

while (csvParser.Read())
{
   var record = csvParser.Record;
}
 The first record is the Header line, the second record starts the data line. 

PS: Encoding type is defined in .NET, there is no TextReader

**Comment by JoshClose** [comment]
`StreamReader` is a `TextReader`.

```cs
new StreamReader(stream, Encoding.UTF8)
```

**Comment by JoshClose** [comment]
When looping and looking at `record`, does it look like all the rows are coming out as expected?

**Comment by buftoronto** [comment]
Yes. All the rows are coming out as expected.

**Comment by JoshClose** [comment]
Since I have no way to test this, could you download the source code and step through and see why the issue is happening?

**Comment by buftoronto** [comment]
Ok. Will try. Thanks

**Comment by JoshClose** [comment]
Let me know what you find!

**Comment by buftoronto** [comment]
I downloaded 22.1.2 code and added to my project. At the beginning I found the error is from ValidateHeader<T>. After going through the code, I found that the header is not processed to be split into columns. There is only one column instead of the number of columns from a local text file. I set a breakpoint at line 373 in CsvParser.cs, it looks like for whatever reason the variable delimiterFirstChar is changed to a comma ',', instead of '\t' as defined. Debugging a local text file it is '\t'.

Will continue to look into that.

**Comment by buftoronto** [comment]
Hi Josh, I finally figured out. Actually it is my fault. I have another CsvReader constructor for Memory Stream. I didn't add the configuration class to the constructor. Thus the default delimiter is set. This is a bug from my upgrading.  After fixing the bug I can use the latest CsvReader version. 

Thank you very much for your help!

**Comment by JoshClose** [comment]
Awesome! Glad you figured it out.

**Comment by ppp3pol** [comment]
Hi Josh 
I am trying to read d csv file from ftp server  and I am getting an error System.ObjectDisposedException: 'Cannot access a disposed object. Here is my code  . Error is being showed  ReadCsvData method in the line
`var records = csvReader.GetRecords<RoqFleetViewModel1>().ToList();`
```
private WebRequest CreateRequest(string method)
        {
            WebRequest req = null;
            try
            {
                
                req = WebRequest.Create(_host + folderpath);
                req.Method = method;
                req.Credentials = _credentials;
            }
            catch(Exception ex)
            {

            }
                return req;     
        }
```
```
public void ReadCSVData(string filename)
        {
            List<string> myList = new List<string>();
            folderpath = folderpath + "/" + filename;
            var request = CreateRequest(WebRequestMethods.Ftp.DownloadFile);
            FtpWebResponse response = (FtpWebResponse)request.GetResponse();
            Stream responseStream = response.GetResponseStream();
            ///StreamReader reader = new StreamReader(responseStream, System.Text.Encoding.UTF8);
            //StreamReader reader = new StreamReader(responseStream);
            RoqFleetViewModel1 models = new RoqFleetViewModel1();
            using (StreamReader reader = new StreamReader(responseStream, System.Text.Encoding.UTF8))
            {
                using(var csvReader = new CsvReader(reader,CultureInfo.InvariantCulture))
                {
                    var records = csvReader.GetRecords<RoqFleetViewModel1>().ToList();
                }
            }
            
        }
```

**Comment by JoshClose** [comment]
@ppp3pol Try reading directly from the `StreamReader`. You'll probably get the same exception. This isn't something caused by `CsvReader`.
