### ISSUE TITLE
[23.0.0] CsvConfiguration properties are not writable because the class is a record

### ISSUE THREAD

**Issue by carlcyber** [JoshClose/CsvHelper#1712]
Hi,

CsvConfiguration properties cannot be set because the class itself is declared a record.

**Comment by JoshClose** [comment]
They're settable. 

Both of these work.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ";",
};
```

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture);
config.Delimiter = ";"
```

If you're trying to set them from the reader/writer, you're getting an interface back that doesn't have the set on them.

This does not work.
```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture);
var csv = new CsvWriter(writer, config);
csv.Configuration.Delimiter = ";";
```

**Comment by carlcyber** [comment]
I see, so this is user error. Thanks for the explanation.

**Comment by JoshClose** [comment]
Is it? Did that fix it for you? We've seen some weird issues with different versions of MSBuild, Visual Studio, and .NET.

**Comment by carlcyber** [comment]
Yes, it compiles and runs without a problem with Visual Studio 16.8.5 and .NET 5.0.103. Here is my code

```
TextReader reader = File.OpenText(path);
var config = new CsvConfiguration(CultureInfo.InvariantCulture) { HasHeaderRecord = false };
var csv = new CsvReader(reader, config);
```

**Comment by JoshClose** [comment]
Awesome!
