### ISSUE TITLE
FieldType is always a string

### ISSUE THREAD

**Issue by worthy7** [JoshClose/CsvHelper#1714]
**Describe the bug**
It seems that `ShouldQuoteArgs.Fieldtype` is always a `string`.

**To Reproduce**
1. Make a class with an int property.
2. try to csv write it and check the fieldtype

**Expected behavior**
Should be an Int type

I added a simple test to the repo:
https://github.com/worthy7/CsvHelper/tree/type-always-string-bug

My objective is to only have quotes on string types, that's why I am doing this.

**Comment by JoshClose** [comment]
I don't see any commits there.

**Comment by JoshClose** [comment]
I'm seeing it not working when using `WriteRecords`. I'll check into that.

**Comment by worthy7** [comment]
branch updated.

Yes, WriteRecords for some very strange reason was not working properly, but when I downloaded and looked at your tests it seems to have worked, so I have no idea about that....

**Comment by JoshClose** [comment]
Writing records bypasses the methods that figured out what type it was. I'll have a fix soon.

**Comment by JoshClose** [comment]
Fixed in 24.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/24.0.0
