### ISSUE TITLE
When using constructor read arguments as PascalCase

### ISSUE THREAD

**Issue by r3dr4gon** [JoshClose/CsvHelper#1719]
**Is your feature request related to a problem? Please describe.**
I'm using .net8 null reference which forces me to have a constructor with parameters.
This means CsvHelper will use the constructor (as there is no parameterless constructor).
However, per the conventions, the constructor parameters are camelCase, while the properties are PascalCase, this means that if I write a file using csvHelper then read a file using csvHelper, I will get errors due to missing headers.

**Describe the solution you'd like**
Would be great to have any fix really (maybe I missed something that is already there) as long as I can keep the naming conventions.
Ideally, I would like to write/read to use the same casing, i.e., or writing using camelCase or reading assuming PascalCase if a constructor is available.

**Describe alternatives you've considered**
ignoring casing in the headers will also work.

**Comment by JoshClose** [comment]
You can put a `[Name]` attribute on the constructor parameters. You can also map constructor parameters in a `ClassMap` by using `Parameter`.

Attributes:
```cs
private class Foo
{
	public int Id { get; private set; }
	public string Name { get; private set; }

	public Foo([Name("Id")] int id, [Name("Name")]string name)
	{
		Id = id;
		Name = name;
	}
}
```

Mapping:
```cs
private class Foo
{
	public int Id { get; private set; }
	public string Name { get; private set; }

	public Foo(int id, string name)
	{
		Id = id;
		Name = name;
	}
}

private class FooMap : ClassMap<Foo>
{
	public FooMap()
	{
		Parameter("id").Name("Id");
		Parameter("name").Name("Name");
	}
}
```

**Comment by JoshClose** [comment]
I created an issue to document this. https://github.com/JoshClose/CsvHelper/issues/1723
