### ISSUE TITLE
Row number in class map

### ISSUE THREAD

**Issue by ErikSchierboom** [JoshClose/CsvHelper#172]
I often find myself defining models that have a line number property:

```
public class MyModel
{
    public int LineNumber { get; set; }
    .....
}
```

I would love to be able to do something like this:

```
this.Map(c => c.LineNumber).LineNumber();
```

Is it possible to do something like this in the class mapping? Or should I code it myself and create a pull request?

**Comment by Sahilshetye** [comment]
The Above solution has been slightly changed to 
`
Map( m => m.LineNumber ).ConvertUsing( row => ( ( CsvReader )row ).Parser.Context.RawRow );
`
Row property has been moved to Context alongwith RawRow(I am still confused with difference if both properties.)
