### ISSUE TITLE
C# CsvHelper - Unable to set configuration ShouldQuote

### ISSUE THREAD

**Issue by vishwanathwins** [JoshClose/CsvHelper#1726]
**Unable to set the ShouldQuote**
```
csv.Configuration.ShouldQuote = (field, context) =>
{
        return true;
};
```

**Error**
Property or Indexer 'IWriterConfiguration.ShouldQuote' cannot be assigned to -- it is read only

**Screenshot**
![image](https://user-images.githubusercontent.com/11028217/109291413-f77eda00-784e-11eb-9024-97b052213b5c.png)

I am using the latest build of CsvHelper - v25.0.0

Can someone please help?

**Comment by vishwanathwins** [comment]
Although I found a similar issue with #1664 , I am still unable to set the configuration.

```
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    ShouldQuote = (field, context) => true
};
```

**Error**
Delete 'ShouldQuote' does not take 2 arguments

**Screenshot*
![image](https://user-images.githubusercontent.com/11028217/109295240-69a5ed80-7854-11eb-9da2-2b185835b80c.png)

**Comment by JoshClose** [comment]
The `ShouldQuote` delegate now takes in a single `args` parameters.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	ShouldQuote = args => true
};
```

**Comment by vishwanathwins** [comment]
Thanks JoshClose

How can we set the indexing for only specific columns.

Based on your previous responses on other issues, how can I achieve below requirement?

BTW, appreciate your quick response for user community.

```
var indexes = new[] { 0, 2, 3, 4 };
csv.Configuration.ShouldQuote = (field, context) => indexes.Contains(context.Record.Count);
```

**Comment by JoshClose** [comment]
You mean you want to quote specific columns?

```cs
var indexes = new[] { 0, 2, 3, 4 };
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	ShouldQuote = args => indexes.Contains(args.Row.Index)
};
```

**Comment by JoshClose** [comment]
```cs
void Main()
{
	var records = new List<Foo>
	{
		new Foo 
		{
			A = "0",
			B = "1",
			C = "2",
			D = "3",
			E = "4",
			F = "5",
			G = "6",
			H = "7",
			I = "8",
			J = "9",
			K = "10"
		},
	};
	var indexes = new[] { 0, 2, 3, 4 };
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		ShouldQuote = args => indexes.Contains(args.Row.Index)
	};
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer, config))
	{
		csv.WriteRecords(records);
		writer.Dump();
	}
}

private class Foo
{
	public string A { get; set; }
	public string B { get; set; }
	public string C { get; set; }
	public string D { get; set; }
	public string E { get; set; }
	public string F { get; set; }
	public string G { get; set; }
	public string H { get; set; }
	public string I { get; set; }
	public string J { get; set; }
	public string K { get; set; }
}
```

**Comment by vishwanathwins** [comment]
Yes, that's correct. I am trying to utilize indexes but not sure what args is for.

I get this compile error. Not sure what I am doing wrong / missing.

![image](https://user-images.githubusercontent.com/11028217/109331411-d1732d00-7882-11eb-957d-9d144f8f4199.png)

**Comment by JoshClose** [comment]
That's telling you that you already have a variable named `args` in scope. Change it to `a` or `shouldQuoteArgs` or something else.

**Comment by vishwanathwins** [comment]
Sorry, my bad. Excuse for my ignorance. I had that variable already assigned in main method arguments. 

It looks like there is no Row object for args.

![image](https://user-images.githubusercontent.com/11028217/109332193-c66ccc80-7883-11eb-8f7d-165bb38cae63.png)

**Comment by vishwanathwins** [comment]
But I got it working with 

`ShouldQuote = args => indexes.Contains(args.get_Row().Index)`

**Comment by JoshClose** [comment]
You need to update Visual Studio. It'll show `Row` after you do that.

**Comment by AyushKumar2019** [comment]
> You mean you want to quote specific columns?
> 
> ```cs
> var indexes = new[] { 0, 2, 3, 4 };
> var config = new CsvConfiguration(CultureInfo.InvariantCulture)
> {
> 	ShouldQuote = args => indexes.Contains(args.Row.Index)
> };
> ```

Hi Josh, 
I am having some trouble quoting the very first field in the CSV report that I am generating through code , 
                        CsvConfiguration csvConfig = new CsvConfiguration(new System.Globalization.CultureInfo("en-CA"))
                        {
                            Delimiter = "|",
                            ShouldQuote = (args) =>true// quote every field, 
                        };
even I am passing this, it's not letting me quote the very first field, any suggestions?

**Comment by AltruCoder** [comment]
@AyushKumar2019 This quotes all of the fields for me.
``` csharp
void Main()
{
	var records = new List<Foo>
	{
		new Foo { Id = 1, Name = "one" },
	};

	CsvConfiguration csvConfig = new CsvConfiguration(new System.Globalization.CultureInfo("en-CA"))
	{
		Delimiter = "|",
		ShouldQuote = (args) => true// quote every field,
	};
	
	//using (var writer = new StreamWriter("path\\to\\file.csv"))
	using (var csv = new CsvWriter(Console.Out, csvConfig))
	{
		csv.WriteRecords(records);
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by AyushKumar2019** [comment]
@AltruCoder  It's still removing quotes from first field even when i try to put index as 1

**Comment by hashim-hashi** [comment]
hi,
 below code for qouting specific columns. But I need to remove the quotes from the header. Here, the full column is quoted. can anyone help me?


var indexes = new[] { 0, 2, 3, 4 };
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	ShouldQuote = args => indexes.Contains(args.Row.Index)
};

**Comment by JoshClose** [comment]
What do you mean by this?
> But I need to remove the quotes from the header

**Comment by nihadcu** [comment]
> What do you mean by this?
> 
> > But I need to remove the quotes from the header

If we use this piece of code
`var indexes = new[] { 0, 1, 5 };
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
ShouldQuote = args => indexes.Contains(args.Row.Index)
};`
The output csv looks like this
![image](https://user-images.githubusercontent.com/19841359/201235241-9519df54-7602-41a3-917d-a9ee808e7647.png)

How to make csv look like this?
![image](https://user-images.githubusercontent.com/19841359/201235368-ec56f39c-7087-4a02-b9bc-690c9a9c0674.png)

**Comment by JoshClose** [comment]
You have row 0 specified there. Did you mean to quote the column numbers instead of the rows?

**Comment by nihadcu** [comment]
> You have row 0 specified there. Did you mean to quote the column numbers instead of the rows?

I want everything in columns 0,1,5 to be in quotes, except for the first row which are headers. How can we achieve this?

**Comment by nihadcu** [comment]
> This looks like it would work.
> 
> ```cs
> var config = new CsvConfiguration(CultureInfo.InvariantCulture)
> {
> 	ShouldQuote = args => args.Row.Row > 1 && indexes.Contains(args.Row.Index)
> };
> ```

It does. Thank You.
