### ISSUE TITLE
CsvHelperException HeaderRecord is blank in exception message

### ISSUE THREAD

**Issue by vinnyrose** [JoshClose/CsvHelper#1730]
The comma joined `context.Reader.HeaderRecord` is not appended to the string builder:

https://github.com/JoshClose/CsvHelper/blob/9518e79cba8bc2dc231f23d0bef459c2c0f85096/src/CsvHelper/CsvHelperException.cs#L90-L92

https://github.com/JoshClose/CsvHelper/blob/9518e79cba8bc2dc231f23d0bef459c2c0f85096/src/CsvHelper/CsvHelperException.cs#L128-L130

**Comment by JoshClose** [comment]
This is fixed in 26.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/26.0.0
