### ISSUE TITLE
Provide a method to exclude PII from CsvHelperException message

### ISSUE THREAD

**Issue by vinnyrose** [JoshClose/CsvHelper#1731]
CsvHelperException outputs the full raw record, which might not be desirable depending on the contents:

https://github.com/JoshClose/CsvHelper/blob/9518e79cba8bc2dc231f23d0bef459c2c0f85096/src/CsvHelper/CsvHelperException.cs#L111

If this field contains PII then this PII might get into logging systems where it would be undesirable to have this information.

Provide a method of excluding this field from the output.

**Comment by JoshClose** [comment]
Would this include the value of a field in a type converter exception?

**Comment by vinnyrose** [comment]
Safest to include them both. The other data in the exception is sufficient to track down the value of a field.

**Comment by JoshClose** [comment]
This is in 26.0.0 on NuGet. https://www.nuget.org/packages/CsvHelper/26.0.0

The config is called `ExceptionMessagesContainRawData` and is `true` by default.
