### ISSUE TITLE
Missing NewLine at the end of Header

### ISSUE THREAD

**Issue by adupont-logiq-ca** [JoshClose/CsvHelper#1733]
Missing Newline at the end of headers. The first row of records is append to the Header.

         using var csvWriter = new CsvWriter(textWriter, cfg);

            csvWriter.WriteHeader<T>();
            csvWriter.WriteRecords(sources);
            string csvResult = textWriter.ToString();
            return csvResult;

CustomerInternalCode,CustomerFirstName,CustomerName,CustomerContact,CustomerType,CustomerSex,CustomerDOB,CustomerCreatedDate,CustomerStreet,CustomerStreet2,CustomerCityId,CustomerProvince,CustomerCountry,CustomerZip,CustomerEmail,CustomerPhone,CustomerPhone2,CustomerFax,CustomerWebsite,CustomerActive,CustomerBioalimentaire,CustomerVedetteProduit,CustomerCategorieProduit,CustomerCategorieProduitDetails,CustomerCategorieProduitSousDetails,CustomerCategorieProduction,CustomerCategorieProductionDetails,CustomerMiseMarche,CustomerTypeProduit,CustomerTypeProduitDetails,CustomerListeDistributeurs,CustomerInfosSuppOuverture,CustomerPlatsVedette,CustomerListeFournisseursRestaurateurs,CustomerDistributeursDetails,CustomerTypeDetaillants,CustomerTypeRestaurateurs,CustomerListeBannieres,CustomerListeFournisseursDetaillants,0,,AUTRE,,,,01/01/0001 00:00:00,01/01/0001 00:00:00,,,,,,,,,,,,False,,,,,,,,,,,,,,,,,,,

**Comment by adupont-logiq-ca** [comment]
I found my probleme.

**Comment by guillermoeuillades** [comment]
@adupont-logiq-ca What was your issue? I had the same issue. Thanks in advance
