### ISSUE TITLE
When registering a classmap the following exception is thrown: Could not load file or assembly 'Microsoft.Bcl.HashCode ....  (CsvHelper 26.0)

### ISSUE THREAD

**Issue by RudiSzalai** [JoshClose/CsvHelper#1735]
This line in the code:

csvreader.Context.RegisterClassMap<ClassMapBcReservation>();

throws this exception in runtime:
"Could not load file or assembly 'Microsoft.Bcl.HashCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)"

if I remove the above line then the next one will throw the same exception: (so it is not just the registerclassmap as I thought
csvreader.GetRecords<BcReservation>().ToList(); 

Nuget:
CsvHelper 26.0
Microsoft.Bcl.HashCode 1.1.1

<PackageReference Include="Microsoft.Bcl.HashCode">
      <Version>1.1.1</Version>
 </PackageReference>

Microsoft.Bcl.HashCode.dll is in the application's folder after installation with all other dlls.

How could I eliminate this exception?

**Comment by JoshClose** [comment]
Can you try a binding redirect? https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/bindingredirect-element

**Comment by JoshClose** [comment]
This sort of thing usually happens because you have another version installed somewhere.

**Comment by RudiSzalai** [comment]
Found the problem and the solution. Actually this is an Visual Studio Installer Project bug.
Factors:
1. converted the packages.config to PackageReference on the project
2. the nuget package (like for the above dll, but happens other dlls too) contains both a lib and ref version of the dll
3. the project installed with a visual studio installer project

here is the full description:
https://github.com/NuGet/Home/issues/9310

The workaround is to put this into the .csproj file:

<Target
	Name="BuiltProjectOutputGroupDependencies"
	DependsOnTargets="$(BuiltProjectOutputGroupDependenciesDependsOn)"
	Returns="@(BuiltProjectOutputGroupDependency)">
	<ItemGroup>
		<BuiltProjectOutputGroupDependency Include="@(ReferenceCopyLocalPaths->'%(FullPath)');
                                              @(ReferenceDependencyPaths->'%(FullPath)');
                                              @(NativeReferenceFile->'%(FullPath)');
                                              @(_DeploymentLooseManifestFile->'%(FullPath)');
                                              @(ResolvedIsolatedComModules->'%(FullPath)')"/>
	</ItemGroup>
</Target>

**Comment by JoshClose** [comment]
Glad you found a fix! This will be good documentation for when others run across this issue.

**Comment by JamalSBS** [comment]
This same issue happened to me. I resolved it in the Package Manager Console in Visual Studio by doing the following command:
```
Update-Package Microsoft.Bcl.HashCode -reinstall
```
