### ISSUE TITLE
Question on reading DateTime strings

### ISSUE THREAD

**Issue by champlin2** [JoshClose/CsvHelper#1744]
When reading a field that is specified as a DateTime if the CSV only contains a date the time portion is set to midnight (00:00:00).  Is there any way to tell if the CSV just contained the date portion (and the time was set to midnight automatically on reading) or if the CSV actually contained a time portion of 00:00:00?

**Comment by JoshClose** [comment]
Where would you be looking at the data? You could create an extra property like `ContainsTime` and set that based on the value of that field. You'd do that either through a type converter, or in a mapping using the `Convert` map method.
