### ISSUE TITLE
Running out of memory writing a csv?

### ISSUE THREAD

**Issue by EricZimmerman** [JoshClose/CsvHelper#1749]
Hopefully this is an easy one.

using latest version, i am reading a csv thats 2.35 GB in size.

process memory usage sits below 7 MB when running, but then this happens

![image](https://user-images.githubusercontent.com/4265254/111540642-c7d43b00-8745-11eb-81d7-d58848fad883.png)

the code doing the work looks like this, where tmp is the path to the csv

```
using (var sw = new StreamReader(tmp))
    {
        var csv = new CsvReader(sw, conf);    

        csv.Read();
        csv.ReadHeader();

        while (csv.Read())
        {
            var record = csv.GetRecord<dynamic>();

            var gr = GetIpInfo(ip, reader);

            record.GeoCity = gr.City;
            record.GeoCountry = gr.Country;

            csvOut.WriteRecord(record);

        }


        csvOut.Flush();
        csvOut.Dispose();
        
        sw.Close();
    }
    File.Delete(tmp);
 
}
```

the line it explodes on is:

```
 csvOut.WriteRecord(record);
```

is there a way to flush csvout or clear out the array to avoid hitting the end of the supported range?

**Comment by EricZimmerman** [comment]
is it as simple as calling

csvOut.Flush();

every 100k rows?

**Comment by EricZimmerman** [comment]
welp, this seems to have worked. running a few more tests and will post back on the results

**Comment by EricZimmerman** [comment]
confirming it worked with adding flush

**Comment by JoshClose** [comment]
You need to call `NextRecord`. You won't get new lines otherwise. This will also flush for you.

**Comment by EricZimmerman** [comment]
Ah perfect. I fixed that issue as well already when I was cleaning up

Thanks!
