### ISSUE TITLE
HasHeaderRecord issue with default encoding

### ISSUE THREAD

**Issue by mkalinski93** [JoshClose/CsvHelper#1750]
**Describe the bug**
When specifying the "hasHeaderRecord" as "false" in the CsvConfiguration, the generated output can be inspected by the default windows editor. It automatically encodes the text as UFT 16 LE instead the given UTF 8 Encoding.
When "hasHeaderRecord" is true, the given encoding will be used

**To Reproduce**
using (CsvWriter writer = new(streamWriter, new CsvConfiguration(CultureInfo.CurrentCulture, encoding: new UTF8Encoding(false), hasHeaderRecord: false))) {
                    writer.WriteRecords(model.Lines);
                }

**Expected behavior**
The Editor should display UTF 8 encoded data

**Screenshots**
HasHeaderRecord = true
![image](https://user-images.githubusercontent.com/64005967/111596544-92733000-87cd-11eb-9808-ea127d7070bf.png)

HasHeaderRecord = false 
![image](https://user-images.githubusercontent.com/64005967/111596650-aae34a80-87cd-11eb-8aaa-94584fc9a5ba.png)

**Additional context**
-

**Comment by JoshClose** [comment]
I believe the editor is making it's best guess of the encoding based on the content it sees. You should be able to change the encoding to the correct one in the editor somewhere.

CsvHelper knows nothing about the encoding that is being written. The encoding is specified in the `TextWriter` (`StreamWriter`, `StringWriter`, etc), which is passed into CsvHelper.

**Comment by mkalinski93** [comment]
I do agree. Other Editors like Visual Studio Code and Sublime Text doesn´t have this problem. In the default Windows editor itself, I am not able to find any Encoding option.  I am trying to specify the encoding in the other application parts, maybe I am lucky with it.

**Comment by mkalinski93** [comment]
EDIT 

`using (StreamWriter streamWriter = new(stream, Encoding.UTF8))
                using (CsvWriter writer = new(streamWriter, new CsvConfiguration(new CultureInfo("de-DE"), encoding: new UTF8Encoding(false), hasHeaderRecord: false))) {
                    writer.WriteRecords(model.Lines);
                }`

When you add Encoding.UTF8 to the StreamWriter, the issue disappears. This Issue can be closed then :)
