### ISSUE TITLE
Never returns when using GetRecordsAsync

### ISSUE THREAD

**Issue by Sellorio** [JoshClose/CsvHelper#1751]
**Describe the bug**

I output a file using the library. No problems. I try to read the same file to the same data structure. Program is stuck on GetRecordsAsync endlessly.

**To Reproduce**

As stated above. Really simple use case.

Switching to GetRecords works so it's clearly not any issues on my end.

**Expected behavior**

Should work.

There is absolutely no circumstance where a library should just hold a thread forever. If there is an error, bubble it up. Never use infinite loops.

Needless to say, after spending ages dealing with this, I'm very frustrated.

**Comment by JoshClose** [comment]
Can you give a small example that reproduces this?

**Comment by Sellorio** [comment]
```csharp
private async Task SaveAsync()
{
    var directory = Path.GetDirectoryName(Filename);

    if (!Directory.Exists(directory))
    {
        Directory.CreateDirectory(directory);
    }

    using var stream = new StreamWriter(Filename);
    using var csvWriter = new CsvWriter(stream, CultureInfo.InvariantCulture);

    await csvWriter.WriteRecordsAsync(_data);
}

public static async Task<VocabularyUserData> LoadAsync()
{
    if (File.Exists(Filename))
    {
        using var stream = new StreamReader(Filename);
        using var csvReader = new CsvReader(stream, CultureInfo.InvariantCulture);

        return new VocabularyUserData(await csvReader.GetRecordsAsync<VocabularyUserDataItem>().ToListAsync());
    }
    else
    {
        return new VocabularyUserData(new List<VocabularyUserDataItem>());
    }
}
```

I'm saving the file using SaveAsync so only CSV Helper is interacting with the file (so the format can't be wrong).

I've debugged it a fair bit so I can confirm it's the `GetRecordsAsync` and not anywhere else that it is getting stuck.

**Comment by Sellorio** [comment]
Now also experiencing lock ups during save.

**Comment by Sellorio** [comment]
And the data was lost despite failing to save.

**Comment by JoshClose** [comment]
Try putting brackets in for your `using` blocks.

```cs
using var stream = new StreamWriter(Filename);
using var csvWriter = new CsvWriter(stream, CultureInfo.InvariantCulture);
{
    await csvWriter.WriteRecordsAsync(_data);
}
```

**Comment by Sellorio** [comment]
This won't make a difference. Even before the new using syntax was implemented, having no braces would be equivalent to the following:

```csharp
using (var stream = new StreamWriter(Filename))
{
    using (var csvWriter = new CsvWriter(stream, CultureInfo.InvariantCulture))
    {
        await csvWriter.WriteRecordsAsync(_data);
    }
}
```

**Comment by JoshClose** [comment]
I'm not able to reproduce the issue.

Here is my test code.

```cs
async Task Main()
{
	var records = new List<VocabularyUserDataItem>();
	for (var i = 0; i < 1_000_000; i++)
	{
		var row = i + 1;
		records.Add(new VocabularyUserDataItem
		{
			Kanji = $"row {i}",
			LastAnswered = DateTime.Now,
			Rank = row,
		});
	}
	
	var path = @"C:\Users\narsh\Documents\issue-1751.csv";
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
	};
	using (var stream = File.Open(path, FileMode.Create))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer, config))
	{
		await csv.WriteRecordsAsync(records);
	}
}

private class VocabularyUserDataItem
{
	public string Kanji { get; set; }
	public DateTime LastAnswered { get; set; }
	public int Rank { get; set; }
}
```

**Comment by Sellorio** [comment]
Your code is not similar to mine.

**Comment by Alik2015** [comment]
@JoshClose  I also tried your code for async but does not work gives error.

`Error	CS1061	'IAsyncEnumerable<VocabularyUserDataItem>' does not contain a definition for 'ToListAsync' and no accessible extension method 'ToListAsync' accepting a first argument of type 'IAsyncEnumerable<VocabularyUserDataItem>' could be found (are you missing a using directive or an assembly reference?)`

CSVHelper version 27.2.1
dotnet version 6.0

**Comment by wongomao** [comment]
I am also experiencing this issue for csv.GetRecordsAsync(...)
CSVHelper version 27.2.1
dotnet version 6.0

**Comment by JoshClose** [comment]
@Alik2015 `ToListAsync` is a part of `System.Linq` in assembly `System.Linq.Async`.

**Comment by JoshClose** [comment]
If someone can give me a unit test that produces the issue, I'll take a look at it. Right now I can't reproduce it.

**Comment by LuciferSam86** [comment]
> `Error CS1061 'IAsyncEnumerable<VocabularyUserDataItem>' does not contain a definition for 'ToListAsync' and no accessible extension method 'ToListAsync' accepting a first argument of type 'IAsyncEnumerable<VocabularyUserDataItem>' could be found (are you missing a using directive or an assembly reference?)`
> 
> CSVHelper version 27.2.1 dotnet version 6.0

You have to install System.Linq.Async from nuget @Alik2015

**Comment by MaxBrooks114** [comment]
Same issue. Never returns. No error message. csv file is 13kb.

**Comment by MarkPflug** [comment]
I believe the folks in this issue are experiencing a deadlock caused by running in a SynchronizationContext (blazor server, or window GUI app for example). There are a few missing ConfigureAwait(false) calls in the code that I think are the culprits. PR #2007 should hopefully resolve it.

**Comment by ckarcz** [comment]
also getting no records with `GetRecordsAsync`

`<PackageReference Include="CsvHelper" Version="33.0.1" />`

on

`<TargetFramework>net6.0</TargetFramework>`

Example:
```
var formFile = formData.Files.Single();
using (var memoryStream = new MemoryStream())
{
    await formFile.CopyToAsync(memoryStream); // stream does have data (length)

    using (var streamReader = new StreamReader(memoryStream)) // stream does have data (length)
    using (var csv = new CsvReader(streamReader, TagOptionsCsvConfiguration))
    {
        await foreach (var record in csv.GetRecordsAsync<CsvRecord>(ct))
        {
            // ommited

            // this is never iterated
        }
    }
}
```

**Comment by matthetherington** [comment]
I just ran into this. My code was doing:

```
using var reader = new StreamReader(inputStream);
using var csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture)
{
    HasHeaderRecord = true
});

csv.Context.RegisterClassMap<MyClassMap>();

await foreach (var record in csv.GetRecordsAsync<T>(cancellationToken))
{
    //...
}
```

and a breakpoint inside the `await foreach` was never hit.

My ClassMap didn't match the input schema so an exception was being thrown, but it never made it to my code and it was just stuck waiting for a row.

I still think there's an issue here, that exception should have bubbled up.

**Comment by MarkEnverus** [comment]
Why was this closed? is it resolved?
