### ISSUE TITLE
change in parsing behavior between v12 and 26.1

### ISSUE THREAD

**Issue by nukeme1** [JoshClose/CsvHelper#1756]
**In version 12, we had the following test case:**
`'a_'b_'c'_d `where the delimiter was _ and the quote character was ' 
**The expected result (which would pass) was 3 records:**
```
a_b
c
d
```
**however, with v26.1, we now obtain:**
```
a_'b
c
d
```

**Comment by JoshClose** [comment]
Do you need to set the escape char too?

```cs
void Main()
{
	var s = new StringBuilder();
	s.Append("'a_'b_'c'_d\r\n");
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		Delimiter = "_",
		Quote = '\'',
		Escape = '\'',
		BadDataFound = null
	};
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvParser(reader, config))
	{
		while (csv.Read())
		{
			csv.Record.Dump();
		}
	}
}
```

![image](https://user-images.githubusercontent.com/114971/112886490-9f2e3880-9097-11eb-8da0-3bd52f3279d6.png)

**Comment by nukeme1** [comment]
That's exactly what the issue is. Thanks!
