### ISSUE TITLE
Class maps with fields marked optional get conversion exceptions on those columns.

### ISSUE THREAD

**Issue by jbuedel** [JoshClose/CsvHelper#1758]
Class maps with fields marked optional are not being honored. I suspect it is because the columns are defined by index, not via headers.

To Reproduce, run this unit test:
```
      [Test]
      public void Test()
      {
         CsvReader GetReader(string s)
         {
            var csvReader = new CsvReader(new StringReader(s), new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                  HasHeaderRecord = false
            });

            csvReader.Context.RegisterClassMap<TestFileMap>();
            return csvReader;
         }


         var data = @"""Superman5"",1,,60.000";
         var data2 = @"""Superman5"",2,5";
         var data3 = @"""Superman5"",1,100,,,,";


         Assert.DoesNotThrow(() => GetReader(data).GetRecords<Record>().ToList(),
                             "column 2 is optional, and the data is an empty string");
         Assert.DoesNotThrow(() => GetReader(data2).GetRecords<Record>().ToList(),
                             "column 3 is optional, and the commas for it's position do not even exist");
         Assert.DoesNotThrow(() => GetReader(data3).GetRecords<Record>().ToList(),
                             "column 3 is optional, the commas are present but there is no data");
      }

      private sealed class TestFileMap : ClassMap<Record>
      {
         public TestFileMap()
         {
            Map(m => m.ORDER_).Index(0);
            Map(m => m.BUNDLE).Index(1);
            Map(m => m.QTY).Index(2).Optional();
            Map(m => m.LENGTH).Index(3).Optional();
         }
      }

      public class Record
      {
         public string ORDER_ { get; set; }
         public int BUNDLE { get; set; }
         public int QTY { get; set; }
         public decimal LENGTH { get; set; }
      }
```

I expected no errors as all required fields are present and contain legit data. The optional fields may or may not be present (as in, the separators defining the position may exist) in the various examples, but even when present they are empty and would not be expected to interfere with parsing.

**Comment by JoshClose** [comment]
Yes, it's because the index is set. You're specifically saying the field is at that index. `Optional` will look for a field name, and ignore if it isn't found. You can use `Default` in the case of `data` and `data3`. There isn't a way to do that with indexes because you would have no idea which column is missing if some random one in the middle is.

**Comment by jbuedel** [comment]
In our situation we have like 30 fields, and all fields after the sixth are not required, but can be sent. So if a customer chooses to send one or more they will typically have empty columns (juxtaposed commas) up to the data, and then not bother with trailing commas to denote remaining columns if they are all going to be empty anyway. Just to be clear, this isn't records of different lengths, it's simply that we do not require trailing commas after the last column with data. Is it safe to say this simply isn't going to be possible with CsvHelper?

**Comment by JoshClose** [comment]
You can do it easily if you read manually, which might be a better option in your case. You can determine the logic needed to figure out which column and property needs to be set. You should be able to use `GetField` for the first 6 if you want, or just do them all manually.

```cs
void Main()
{
	IEnumerable<Record> GetReader(string s)
	{
		var csvReader = new CsvReader(new StringReader(s), new CsvConfiguration(CultureInfo.InvariantCulture)
		{
			HasHeaderRecord = false
		});

		csvReader.Context.RegisterClassMap<TestFileMap>();

		while (csvReader.Read())
		{
			var record = csvReader.GetRecord<Record>();
			
			var length = csvReader.Parser.Count;
			
			if (length > 2) 
			{
				record.QTY = csvReader.GetField<int?>(2).GetValueOrDefault();
			}

			if (length > 3)
			{
				record.LENGTH = csvReader.GetField<decimal?>(3).GetValueOrDefault();
			}
			
			yield return record;
		}
	}

	var data = @"""Superman5"",1,,60.000";
	var data2 = @"""Superman5"",2,5";
	var data3 = @"""Superman5"",1,100,,,,";

	GetReader(data).ToList().Dump();
	GetReader(data2).ToList().Dump();
	GetReader(data3).ToList().Dump();
}

private sealed class TestFileMap : ClassMap<Record>
{
	public TestFileMap()
	{
		Map(m => m.ORDER_).Index(0);
		Map(m => m.BUNDLE).Index(1);
	}
}

public class Record
{
	public string ORDER_ { get; set; }
	public int BUNDLE { get; set; }
	public int QTY { get; set; }
	public decimal LENGTH { get; set; }
}
```

**Comment by jbuedel** [comment]
Yeah, I think that is the way to proceed. Thanks.
