### ISSUE TITLE
CsvConfiguration is not detected by IntelliSense

### ISSUE THREAD

**Issue by BillG212** [JoshClose/CsvHelper#1760]
Hi Josh,
Thanks for the great tool, it saved a lot of time. Yet I've faced a problem detecting the CsvConfiguration. I want to append data to the existing csv file and I don't want to write the header again. Although I've imported the 'using `CsvHelper.Configuration;` and using `CsvHelper.Configuration.Attributes;` but still not detecting CsvConfiguration.
Please see the code below.
Thanks

```
public void WriteToCSV()
    {
        var records = new List<Data>
    {
        new Data { nameData = fNameIF.text, pwData = pwIF.text},
    };

        // Append to the file.
        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            // Don't write the header again.
            HasHeaderRecord = false,

        };

        // Write to a file.
        using (var writer = new StreamWriter(Application.persistentDataPath + "/ReadWriteCSV.csv"))
        using (var csv = new CsvWriter(writer))
        {
            csv.Configuration.CultureInfo = CultureInfo.InvariantCulture;
            csv.WriteRecords(records);
        }

        using (var stream = File.Open(Application.persistentDataPath + "/ReadWriteCSV.csv", FileMode.Append))
        using (var writer = new StreamWriter(stream))
        using (var csv = new CsvWriter(writer,config))
        {
            csv.WriteRecords(records);
        }
    }

```
![Screen Shot 2021-04-03 at 6 09 33 PM](https://user-images.githubusercontent.com/54684616/113482537-cc1f8880-94a7-11eb-9917-1f21ac0bb4f6.png)

**Comment by JoshClose** [comment]
What is the error that the red line is giving?

**Comment by BillG212** [comment]
Assets/Scripts/ReadWriteCSV.cs(83,26): error CS0246: The type or namespace name 'CsvConfiguration' could not be found (are you missing a using directive or an assembly reference?)

**Comment by JoshClose** [comment]
If you look in your project dependencies, is CsvHelper shown there? What version? Do you have other `using` statements that could conflict with it? Do you have your own namespace that could be conflicting?

**Comment by BillG212** [comment]
Yes, CsvHelper is in my project dependencies.
CsvHelper version 26.1.0
I'm using this in my code 
```
using System;
using System.IO;
using UnityEngine;
using UnityEngine.UI;
using System.Linq;
using System.Globalization;
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using System.Data;
```
And no I don't have my own name space.
Thanks Josh for taking the time to support so far.

**Comment by JoshClose** [comment]
Looks like you're using Unity. How are you installing CsvHelper? Are you using `NuGetForUnity`?

**Comment by BillG212** [comment]
Yup I'm using unity. I've downloaded CsvHelper through Visual Studio >Project >Manage NuGet Packages... then search for CsvHelper and download. 
Unity version 2019.4.21f1
Visual Studio 2019 for Mac version 8.3 9(Build 1805)
NuGet version 5.3.0.6192

**Comment by JoshClose** [comment]
What people that are using Unity have recommended is installing NuGet apps through a Unity tool called NuGetForUnity. I don't believe normal NuGet does things properly to work with Unity. https://github.com/GlitchEnzo/NuGetForUnity

**Comment by BillG212** [comment]
Thanks a lot. I will give it a try.

**Comment by BillG212** [comment]
I installed NuGetForUnity and while trying to install CsvHelper it generate errors and I already posted an issue. 
https://github.com/GlitchEnzo/NuGetForUnity/issues/374 
It seems that the problem is in the integration between Unity and CsvHelper.

**Comment by JoshClose** [comment]
Oh good. It looks like it's a lot of libraries on Mac and not just CsvHelper. They'll get it figured out.

**Comment by ekorudiawan** [comment]
I got a same issue, btw I used normal nuget for installing

**Comment by JoshClose** [comment]
This is a Unity project?

**Comment by ekorudiawan** [comment]
No, I used it for Winform project

**Comment by JoshClose** [comment]
Is Visual Studio up to date?

**Comment by ekorudiawan** [comment]
Yes, it is up to date
