### ISSUE TITLE
How to change column names in csv after WriteRecords method

### ISSUE THREAD

**Issue by YellowFlashLeo** [JoshClose/CsvHelper#1767]
The problem I have is:
```cs
 public byte[] BuildProductsFile(List<object> records)
    {
      var firstRow = records.FirstOrDefault();
      var columnHeaders = ((IDictionary<string, object>) firstRow).Keys.ToList();

      using var memoryStream = new MemoryStream();
      using (var streamWriter = new StreamWriter(memoryStream))
      {
        using var csvWriter = new CsvWriter(streamWriter);
        csvWriter.WriteRecords(records);

      }
      return memoryStream.ToArray();
```
When I do WriteRecords, it changes header names to alphabetic order which I dont want since after it my rows correspond to incorrect headers. I cant use Class to specify header names because they will be different depending on different tables which user would like to get. My question is can I overwrite header names with correct sequence which I got from var columnHeaders = ((IDictionary<string, object>) firstRow).Keys.ToList(); Or is there a way to disable alphabetical order header placing

**Comment by JoshClose** [comment]
[The order isn't guaranteed by .NET](https://docs.microsoft.com/en-us/archive/blogs/haibo_luo/member-order-returned-by-getfields-getmethods) but is generally the order the properties are listed in the class. If you want them in a specific order, you need to use a `ClassMap` or attribute on the members. The values in each row should be in the same order the header is written in, so they shouldn't be mismatched.

Is each record a `IDictionary<string, object>`?

**Comment by YellowFlashLeo** [comment]
Wow, I didn't expect such a quick response, thank you for that
I am trying to attach print screen of how data looks in List<object> records
And resulting csvFile
![List_byte_ records](https://user-images.githubusercontent.com/73524752/113881645-495b3e00-97c5-11eb-9c16-d4468451741c.PNG)

**Comment by YellowFlashLeo** [comment]
![Csvfile](https://user-images.githubusercontent.com/73524752/113882118-b53da680-97c5-11eb-9eb1-763302d19400.PNG)

**Comment by YellowFlashLeo** [comment]
As you can see for some reason first column name is EventData not UserId but data beneath corresponds to UserId not EventData

**Comment by JoshClose** [comment]
What is the type of each record?

**Comment by YellowFlashLeo** [comment]
object,
Since I basically need it for my asp.core app which allows users to run sql script against database with tons of tables, so i am taking their sql script and run against database. I get List<objects> as response and send it to this BuildProductsFile method. I cant specify specific Classes (for tables) with props (columns) because I dont know before hand which table user will want to get  that is why type is object

**Comment by YellowFlashLeo** [comment]
Is there a way to rewrite headers with correct values, if order cant be fixed?

**Comment by JoshClose** [comment]
I want to figure out why the ordering is different because that shouldn't be happening. Can you give me the type in this one instance here so I can try and reproduce?

**Comment by YellowFlashLeo** [comment]
Sorry I am confused what type instance.
Unfortunately I cant share my source code as I am working in a company which doesn't allow it.
But what I can do, is I can create simple app just with the same problem and then I can post it in Github the only thing you will need to do is to create some table and database in Microsoft SQL Server Management Studio and mention its name in appsettings.json. Will it be ok? If yes I can do it now

**Comment by JoshClose** [comment]
Yes

**Comment by YellowFlashLeo** [comment]
Done, https://github.com/YellowFlashLeo/DataWithCsvHelper.git
Just change appsettings json and create some simple table and you are good to go

**Comment by JoshClose** [comment]
The very first one I created had different ordering. All the rest were the same. The object type is `dynamic`. I wonder if `DynamicMetaObject.GetDynamicMemberNames` doesn't always return the values in the same order. If that is the case, every single row could have a different order.

What you can do to ensure this works is set the configuration `DynamicPropertySort` so it sorts the same way each time.

If we find that it's not giving the same order every time, I'll set a default `DynamicPropertySort` value so the header and each row are the same.

**Comment by JoshClose** [comment]
So that is the case. The data inside of `ExpandoObject` is a `Dictionary<string, object>` which doesn't have a specified order. This means some sort of order should always be applied to ensure every row is the same.

Setting `DynamicPropertySort` will fix your problem. I need to make a default for it I think, since the order is not guaranteed.

**Comment by YellowFlashLeo** [comment]
Great, thanks, could you should some example of how to set DynamicPropertySort?

**Comment by YellowFlashLeo** [comment]
I mean how to sort it to be the same version as it came via List<objects>

**Comment by JoshClose** [comment]
Every single row could be different, so there is no way to do that. The names of the properties are stored in a dictionary which doesn't have a guaranteed sort order.

If you want it to be in the same order as the SQL table, you could query for the list of column names for the table first, then sort in that order.

```cs
void Main()
{
    var records = new List<dynamic>();
    dynamic record = new ExpandoObject();
    record.Name = "one";
    record.Id = 1;
    records.Add(record);
    
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        DynamicPropertySort = Comparer<string>.Create((x, y) => x.CompareTo(y)),
    };
    using (var writer = new StringWriter())
    using (var csv = new CsvWriter(writer, config))
    {
        csv.WriteRecords(records);
        writer.Dump();
    }
}
```

**Comment by YellowFlashLeo** [comment]
But cant I sort headers based on those I got from ?
`var firstRow = records.FirstOrDefault();
var columnHeaders =((IDictionary<string,object>)firstRow).Keys.ToList();`
columnHeaders will have list of strings which represent name of headers in correct order

**Comment by YellowFlashLeo** [comment]
Thanks for help anyways

**Comment by YellowFlashLeo** [comment]
Sir I fixed it, I feel so bad right now, I was using CSVHelper version 12.0.0 once I changed it to latest and chnaged
`  using var csvWriter = new CsvWriter(streamWriter); `
to
`  using var csvWriter = new CsvWriter(streamWriter, CultureInfo.CurrentCulture); `
IT WORKED!

**Comment by JoshClose** [comment]
Oh, that's good.

**Comment by JoshClose** [comment]
The first time I ran it was with your code on version 12, then I put the latest source in to debug and couldn't reproduce anymore.
