### ISSUE TITLE
unable to read header from csv file

### ISSUE THREAD

**Issue by markat1** [JoshClose/CsvHelper#1770]
I'm trying to read data from a csv file, but csv helper is having problems reading the headers from the csv file.

```
  public static string ReadDataFromCsv(FileAttachment filedata)
        {

            MemoryStream stream = new MemoryStream(filedata?.ContentBytes);

            using (var reader = new StreamReader(stream))
            {
          
                CsvConfiguration csvConfiguration = new CsvConfiguration(CultureInfo.InvariantCulture);

                using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
                {
                  
                    while (csv.Read())
                    {
                        csv.Context.RegisterClassMap<FooMap>();
                        var records = csv.GetRecords<Foo>();
                    }
                }
            }

            return "";

        }

  public class Foo
    {
        public int Description { get; set; }
    }

    public sealed class FooMap : ClassMap<Foo>
    {
        public FooMap()
        {
            Map(m => m.Description).Name("Original part number");
        }
    }
```

Expected to receive the content from csv file mapped as a Foo class.

csv file contains: 

`number;test number;Description;amount;No;test\n;99999999999;77777777;test;1;5555555555555;
`
Error I got is: 
""Header with name 'test number'[0] was not found.\r\nIf you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.\r\n\r\nIReader state:\r\n   ColumnCount: 0\r\n   CurrentIndex: -1\r\n   HeaderRecord:\r\n[\";99999999999;77777777;test;1;5555555555555;\"]\r\nIParser state:\r\n   ByteCount: 0\r\n   CharCount: 131\r\n   Row: 2\r\n   RawRow: 2\r\n   Count: 1\r\n   RawRecord:\r\n;99999999999;77777777;test;1;5555555555555;\r\n"

**Comment by JoshClose** [comment]
You don't call `Read` when you use `GetRecords`. https://joshclose.github.io/CsvHelper/examples/reading/get-class-records

**Comment by JoshClose** [comment]
It looks like your delimiter is `;` and not `,`. You'll need to set your delimiter.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ";",
};
using (var csv = new CsvReader(reader, config))
```

**Comment by markat1** [comment]
That worked thanks! I have question regarding the encoding. I tried several encodings , but can't seem to decode
the description "T�GE" to "tåge.


`using var reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-1"));`
 

`using var reader = new StreamReader(stream,Encoding.UTF8);`

**Comment by markat1** [comment]
I have question regarding the encoding. I tried several encodings , but can't seem to decode
the description "T�GE" to "tåge.


`using var reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-1"));`
 

`using var reader = new StreamReader(stream,Encoding.UTF8);`
