### ISSUE TITLE
Autodetect Delimiter

### ISSUE THREAD

**Issue by objecttothis** [JoshClose/CsvHelper#1776]
**Is your feature request related to a problem? Please describe.**
Unless I missed something, I don't think CsvHelper currently has the ability to autodetect the delimiter.  We have a globally used software for our non-profit, so we don't always know what delimiter will be used, but we can limit them to a few possible delimiters.  I was hoping not to make the user enter the delimiter they are using.  I understand that CSV stands for Comma Separated Values, but there isn't a hard ISO standard like there is for many other things.  Further, some prefer to use the pipe (|) because it guarantees that data containing commas that don't get quoted won't cause problems.

**Describe the solution you'd like**
I think this would be somewhat straight forward to implement if, for example there was a CsvConfiguration field that took an array of possible delimiters, then used the array to attempt to parse the header row (or 1st row, if indexed) and then used whichever character parsed properly to parse the rest of the file.  Something like 

`CsvConfiguration.DetectDelimiters = new char[] { ",", "|", "\t",";" };`

**Describe alternatives you've considered**
If you knew that the first data row contained quote encapsulated data, then you could detect the delimiter easier, but I don't think that's guaranteed.

**Additional context**

**Comment by JoshClose** [comment]
I implemented this and it will be in version 27.0.0. I'm going to try and put a few other features in before releasing.
