### ISSUE TITLE
Space in header doesn't map to property

### ISSUE THREAD

**Issue by stefanloerwald** [JoshClose/CsvHelper#1801]
**Describe the bug**

I have a CSV file with contents
```
A, B,C
0,1,2
2,3,3
4,5,1
```

My type is defined as
```cs
public class Foo
{
   public int A {get;set;}
   public int B {get;set;}
   public int C {get;set;}
}
```

Trying to read the CSV file using `Foo` will fail because the second column is called ` B`, instead of `B` (it has a leading space).

The exception is
```
CsvHelper.MissingFieldException: Field with name 'B' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
      IReader state:
         ColumnCount: 0
         CurrentIndex: -1
         HeaderRecord:
      ["A"," B","C"]
```

**To Reproduce**

See above

**Expected behavior**

The intention here is fairly clear, and while I can map columns with leading/trailing whitespace, I prefer not to have to bother with that. Is it perhaps something to consider implementing the feature "Ignore leading/trailing whitespace in headers"?

**Comment by JoshClose** [comment]
If you want to do it to all fields, you can set `TrimOptions` in the config. If you only want to do it on the header, you can use `PrepareHeaderForMatch`.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    PrepareHeaderForMatch = args => args.Header.Trim(),
};
```
