### ISSUE TITLE
Skips first row when reading despite HasHeaderRecord = false

### ISSUE THREAD

**Issue by CsOnline-mika** [JoshClose/CsvHelper#1804]
When reading csv, skips the first row, despite setting HasHeaderRecord to false.

Code and test file as follows.

public static void CsvTestHeader()
    {
        var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.CurrentCulture)
        {
            Delimiter = ";",
            HasHeaderRecord = false,
            Quote = '"',
            Encoding = encoding
        };
    
        using (var reader = new System.IO.StreamReader(fullPath, encoding))
        using (var csv = new CsvReader(reader, config))
        {
            csv.Read();
            while (csv.Read())
            {
                var id = csv.GetField(0);
                var name = csv.GetField(1);
                var price = csv.GetField(2);
            }
            
            
        }
    }
    
![image](https://user-images.githubusercontent.com/84454841/118986827-f528a980-b97f-11eb-915a-7c664dda7cb3.png)

**Comment by JoshClose** [comment]
You are calling `Read` which reads the first row. You are then calling read again immediately after which goes to the second row. You're skipping the first row.

`HasHeaderRecord` is only used when calling `GetRecords`, so it doesn't matter what you set there when manually reading rows like you are doing.

**Comment by CsOnline-mika** [comment]
@JoshClose Thanks, my bad. Good to know HasHeaderRecord is not needed for what I want to do.
