### ISSUE TITLE
First line of headerless csv not being read - GetRecords

### ISSUE THREAD

**Issue by realfaisalk** [JoshClose/CsvHelper#1805]
.NetCore v3.1
CsvHelper v27.0.4

I have got a headerless csv file with around 162 columns and 13 rows.
Using _GetRecords_ it only returns 12 lines.

Setting _HasRecordHeader_ to false results in an exception.

```
private static void Main(string[] args)
{
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        //MissingFieldFound = null,
        //HeaderValidated = null,
        HasHeaderRecord = false
    };

    using (var reader = new StreamReader(DataGenHelper.csvLocation))
    using (var csv = new CsvReader(reader, config))
    {
        records = csv.GetRecords<InstrumentTradeTableEntity>().ToList();
        var blah = records.Count();
    }
}
```
Screenshots of error:

![csvhelper1](https://user-images.githubusercontent.com/23498757/119474552-2ddfce80-bd44-11eb-80d9-86780f54f55f.jpg)
![csvhelper2](https://user-images.githubusercontent.com/23498757/119474553-2e786500-bd44-11eb-9d4b-586fef63d6db.jpg)

CSV file:

![csvhelper3](https://user-images.githubusercontent.com/23498757/119474911-8c0cb180-bd44-11eb-8ae8-8ecb2be33f03.jpg)

**Comment by realfaisalk** [comment]
UPDATE:
1. Am using class definition with index attribute mapping.
2. Adding dummy columns names (e.g. column1, column2 etc) and setting _HeaderValidated_ to null the correct number of rows are imported

**Comment by JoshClose** [comment]
The `InnerCxception` shows `String '0' was not recognized as a valid DateTime`. You must have a field that has `0` in it where it should be a `DateTime`. If you need to parse `0` as a `DateTime`, there are ways to do that.

**Comment by realfaisalk** [comment]
Couple of questions:

1. The csv is parsed correctly when HeaderValidated is not set in config. Why don't we get the exception there? Is the prblem to do with the first row in the csv?
2. The class definition file is setting all columns as strings. Not setting any to DateTime

**Comment by realfaisalk** [comment]
Class Definition example:

 ```
        [Index(0)]
        public string TradeType { get; set; }
        [Index(1)]
        public string ProductGroup { get; set; }
        [Index(2)]
        public string TradeDate { get; set; }
        [Index(3)]
        public string TradeNumber { get; set; }
```

**Comment by JoshClose** [comment]
I don't have enough info to answer you. Can you make a small example app that shows the issue?

**Comment by JoshClose** [comment]
Something similar to this:

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("1,one\r\n");
    s.Append("2,two\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        HasHeaderRecord = false,
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, config))
    {
        csv.GetRecords<Foo>().ToList().Dump();
    }
}

private class Foo
{
    [Index(0)]
    public int Id { get; set; }
    [Index(1)]
    public string Name { get; set; }
}
```

**Comment by JoshClose** [comment]
FYI `.Dump()` is a [LINQPad](https://www.linqpad.net/) method that display the data.

**Comment by realfaisalk** [comment]
Thanks.
I've put it into .Net Fiddle with the first 2 rows of data. `Dump` is returning results so I assume that it's working in this example?
https://dotnetfiddle.net/0j7tdg

Obviously I'm using `StreamReader` for an actual .csv file in my real code.

**Comment by JoshClose** [comment]
Yes, it's working just fine there. The error message should say the row and column the error happened on, and give the raw row. Maybe you can see if there is something bad with the data on that row.

**Comment by realfaisalk** [comment]
Yeah, must be something with the actual csv file. It works with dummy headers which are replaced by the class def headers so I'll just use it like that going forward.
If I get time to do more investigation and get to the actual issue i'll let you know.

Thanks again for the great support!

**Comment by realfaisalk** [comment]
@JoshClose - Sorry to bother you with this again, but think I know what the issue is. I had set my indexes correctly. I am trying to parse ~160 columns but there are 278 columns in total.
My class definition file only has indexes for the 160. There is data at columns 277 & 278 that contains "0.00000000" which the parser is then trying to convert to a DateTime?

Is there any way for the parser to _ignore_ columns that aren't indexed?

Thanks

**Comment by JoshClose** [comment]
> Something that says if a column isn't mapped, ignore it, or parse a default mapping that is set by the user

This is how class maps work. You specify only the fields you want mapped.

**Comment by realfaisalk** [comment]
Sorry, for my example where I am using Index mapping. If I don't supply an Index for a column, ignore that column?

e.g.

```
[Index(0)]
public string TradeType { get; set; }
[Index(1)]
public string ProductGroup { get; set; }

public string TradeDate { get; set; }
[Index(3)]
public string TradeNumber { get; set; }
[Index(4)]
```

In the above example I would want _TradeDate_ to be ignored

**Comment by JoshClose** [comment]
I want auto mapping to map everything based on convention by default. The attributes allow you to modify that. You can put an `[Ignore]` attributes on the members you don't want mapped.

I'm creating an `[IgnoreBase]` attribute to stop base classes from being mapped.

**Comment by realfaisalk** [comment]
Ahhh, sorry didn't know there was an _[Ignore]_ attribute. I would have put that on the DateTime field in the inherited class. But having an _[IgnoreBase]_ makes sense. Nice one.

**Comment by JoshClose** [comment]
This feature is in 27.1.0 on NuGet.
