### ISSUE TITLE
CsvReader can be reused by resetting internal states

### ISSUE THREAD

**Issue by carlcyber** [JoshClose/CsvHelper#1806]
Hi,

I am currently reading lots of CSV strings from separate sources around and wanted to prevent instantiating `CsvReader` everytime a CSV comes in. Is it possible to reset internal states (buffer positions) in `CsvReader` so it can be reused by updating `BaseStream`? I've already achieved the same effect in `CsvWriter` after noticing performance issues, so having `CsvReader` to be reusable is highly appreciated.

**Comment by JoshClose** [comment]
Once the `TextReader` is exhausted and all the records are read, you should be able to fill the `TextReader` with more data and continue reading. There is no way to change the `TextReader` that is being used.

**Comment by carlcyber** [comment]
I see. I am not intended to change the reference of `TextReader`, just wanna clear and fill new contents for next use. But your solution should still hold. Thanks for the tips.
