### ISSUE TITLE
Skip properties when writing with attributes

### ISSUE THREAD

**Issue by royberris** [JoshClose/CsvHelper#1809]
**Is your feature request related to a problem? Please describe.**
We cannot skip properties when writing to CSV.

**Describe the solution you'd like**
Allow us to "ignore" properties through attributes. With attributes like `[Ignore]` or existing ones to skip a property all together.

**Describe alternatives you've considered**
Creating new models for everything and mapping, which is not a great solution.

**Comment by JoshClose** [comment]
This already exists.

```cs
void Main()
{
    var records = new List<Foo>
    {
        new Foo { Id = 1, Name = "one" },
    };
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
    };
    using (var writer = new StringWriter())
    using (var csv = new CsvWriter(writer, config))
    {
        csv.WriteRecords(records);
        writer.Dump();
    }
}

private class Foo
{
    public int Id { get; set; }
    [Ignore]
    public string Name { get; set; }
}
```

![image](https://user-images.githubusercontent.com/114971/120500999-e0d4ab80-c386-11eb-9486-8c05d5c40d5d.png)

**Comment by royberris** [comment]
@JoshClose sorry I couldn't find this on the docs

**Comment by JoshClose** [comment]
There used to be an API section which would help. I'm waiting for the static site generator to finish theirs and it'll be back again. There is a small section about attributes here. https://joshclose.github.io/CsvHelper/examples/configuration/attributes/
