### ISSUE TITLE
Unexpected exception 「CsvHelper.ReaderException: 'No members are mapped for type」

### ISSUE THREAD

**Issue by qwas368** [JoshClose/CsvHelper#1819]
**Describe the bug**
Unexpected exception 「CsvHelper.ReaderException: 'No members are mapped for type 'ConsoleApp1.Foo'.」

**To Reproduce**
Success Case
```csharp
public class Foo
{
    public int ID { get; set; }

    public int a { get; set; }

    public string b { get; set; } = "";
}

class Program
{
    static async Task Main(string[] args)
    {
        string csvText = @"ID,Name,Test
1,Tom,A
2,Jerry,B";
        MemoryStream stream = new MemoryStream(Encoding.ASCII.GetBytes(csvText)); 
        using var reader = new StreamReader(stream);
        using var csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HeaderValidated = null,
            MissingFieldFound = null,
            UseNewObjectForNullReferenceMembers = true,
        });

        var records = csv.GetRecords<Foo>().ToList();

    }
}
```

Exception happened Case 
```csharp
public class Foo
{

// remove ID

    public int a { get; set; }

    public string b { get; set; } = "";
}

class Program
{
    static async Task Main(string[] args)
    {
        string csvText = @"ID,Name,Test
1,Tom,A
2,Jerry,B";
        MemoryStream stream = new MemoryStream(Encoding.ASCII.GetBytes(csvText)); 
        using var reader = new StreamReader(stream);
        using var csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HeaderValidated = null,
            MissingFieldFound = null,
            UseNewObjectForNullReferenceMembers = true,
        });

        var records = csv.GetRecords<Foo>().ToList();

    }
}
```

**Expected behavior**
No exception happened  in Exception happened Case. Records' count is two.  a, b property are default value. 

**Additional context**
Two case is same for me. It should also have same behavior.
Success Case -「Name」and「Test」 doesn't map to any member in Foo class. We get records normally.
Exception happened Case  -  「ID」,「Name」and「Test」 doesn't map to any member in Foo class too.

**Comment by JoshClose** [comment]
You have a header with columns `ID`, `Name`, and `Test`. Your class `Foo` has properties `ID`, `a`, and `b`. CsvHelper is matching the property names to the header names. You're turning off all the error things to let it run even through it would be telling your about missing fields. If you remove the `ID` property, there are no other properties that match with the CSV columns, so it gives you the error that there are no columns that match.

**Comment by qwas368** [comment]
@JoshClose  Got it. Thank you for your detail.
