### ISSUE TITLE
Delimiter detection doesn't work in async read method

### ISSUE THREAD

**Issue by InlineAsm** [JoshClose/CsvHelper#1820]
Hi,

In the CsvParser the async method checks against row 0 while the sync method is checking against row 1. This prevents the autodetection from working.

https://github.com/JoshClose/CsvHelper/blob/e0545f61a00932024fc07fbcd65587fc349232ab/src/CsvHelper/CsvParser.cs#L253

**Comment by JoshClose** [comment]
Thanks! Fixed and in version 27.1.1 on NuGet.
