### ISSUE TITLE
CsvWriter should accept a Stream to write to as an alternative to the TextWriter

### ISSUE THREAD

**Issue by GSFatDaemon** [JoshClose/CsvHelper#1823]
**Is your feature request related to a problem? Please describe.**
Our API returns our data in CSV format as an array of bytes. The CsvWriter constructor only accepts a TextWriter to write the data to. This means that we must create a temporary file to write the bytes to, read the file as a byte array and then delete the file. Apart from unnecessarily using the file system this makes the API slow because of the use of the file system. It also makes unit testing more cumbersome.

**Describe the solution you'd like**
I would like CsvWriter to accept a memory based alternative to TextWriter so I can avoid using the file system.

**Describe alternatives you've considered**
None.

**Additional context**
Ideally CsvWriter would use System.IO.Abstractions (https://github.com/System-IO-Abstractions/System.IO.Abstractions) so that we could mock the file system and write genuine unit tests.

**Comment by JoshClose** [comment]
Can't you use a `MemoryStream`?

**Comment by GSFatDaemon** [comment]
A MemoryStream would be perfect. Unfortunately the CsvWriter's constructor only accepts a TextWriter, not a MemoryStream.

**Comment by AltruCoder** [comment]
```csharp
void Main()
{
	var records = new List<Foo>
	{
		new Foo { Id = 1, Name = "one" },
	};

	using (var ms = new MemoryStream())
	using (var writer = new StreamWriter(ms))
	using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
	{
		csv.WriteRecords(records);
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by GSFatDaemon** [comment]
Apologies, Josh, that was a dumb question. Thank you. Please feel free to close this now.

**Comment by JoshClose** [comment]
Don't worry about it. You learned something new!
