### ISSUE TITLE
Memory leak when run from unit-test

### ISSUE THREAD

**Issue by jenscollin** [JoshClose/CsvHelper#1827]
**Describe the bug**
We have a rather big solution where we use CsvHelper but experience that process memory grows and is never returned until process exit. I have narrowed it down to a simple console application (attached) to replicate the behavior.
If run from the main program, memory does not grow, run referenced from a unit-test it does.

**To Reproduce**
I've built the class in the ConsoleApp, with only CsvHelper as nuget package. 27.1.1

The method brief:
```cs
                using (var sr = new StringReader(data))
                {
                    using (var csv = new CsvReader(sr, CultureInfo.InvariantCulture))
                    {
                        var records = csv.GetRecords < Ragnar > ();
                        foreach (var rec in records)
                        {
                            var header = rec;
                        }
                    }
                }
```
The Ragnar class looks like this:
```cs
    public class Ragnar
    {
        public int A { get; set; }
        public int B { get; set; }
        public int C { get; set; }
    }
```
Start the program right out of the box and it shows about 5Mb of RAM continuously on my machine. No growth.
Kill the program.
Run the unit-test that uses the exact same code, look at process manager and the process called testhost.net472 or something similar. Grows with about 5Mb/sec and does not stop until killed. 

**Expected behavior**
No memory leak since we disposed the objects when using "using"-blocks.

**Screenshots**
screenshots not applicable.

**Additional context**
We discovered this in our main code tree, a process started to grow unexpectedly. We use dependency injection and many things that might affect, so the unit-test is just a way of showing it isolated.

[LeakyCsv.zip](https://github.com/JoshClose/CsvHelper/files/6795813/LeakyCsv.zip)

**Comment by JoshClose** [comment]
Would you be able to run the profiler on it? I bet that will say what's been kept around in memory.

**Comment by JoshClose** [comment]
I wonder if the unit test runner tries to be smart and is holding on to memory for some reason.

**Comment by JoshClose** [comment]
I just tried under net5.0 and netcoreapp2.1 and neither of them have this issue. I then tried under net4.8 and the issue is there. I think this might be an issue with the .NET Framework test runner.

**Comment by jenscollin** [comment]
Thanks for testing!
Good news in one way, but bad news for me. Because the issue still exists in our main code and this was a way of trying to isolate the code and remove all other deps. So probably something else in our code (injection things etc) could behave the same as the unit-test-runner does.
I'll see if I can reproduce without unit-test-runner but still simplified. (And the profiler route as well).
Any tips from experience to what to look for?

**Comment by JoshClose** [comment]
If you can reproduce it outside of the test runner, that would be the best case scenario. I'm not sure if you'll be able to profile the test runner. I briefly tried and couldn't get it to work, but there may be a way.

You might want to create a ticket with MS. They'll more than likely escalate it quickly and have someone on the team that works on the test runner looking into it.

**Comment by jenscollin** [comment]
Sorry, been doing some tries but I can't reproduce it. We took out all CsvHelper-code from the main projects (pain) and it still leaks, so CsvHelper is not to blame for any leakage in this discussion. We got sidetracked with the test-runner.
Thanks for helping out!
