### ISSUE TITLE
Add CsvContext.RegisterClassMap() overload that takes a Type

### ISSUE THREAD

**Issue by IanKemp** [JoshClose/CsvHelper#1829]
**Is your feature request related to a problem? Please describe.**
The `CsvContext.RegisterClassMap()` method lacks an overload allowing you to provide an arbitrary `Type` deriving from `ClassMap`. This precludes the use of raw types with this method, forcing the end-user to resort to reflection or expression trees to build and execute a generic delegate. It's also not congruent with e.g.  `CsvReader.GetRecords()` which does have an overload accepting a `Type`.

**Describe the solution you'd like**
Add an overload of `CsvContext.RegisterClassMap(Type type)` that constructs that type at runtime and uses it, as per the rules for `CsvContext.RegisterClassMap<TClassMap>()`. This could be as simple or naïve as constructing, executing and disposing of a generic delegate via reflection, although some sort of cache may be useful. There will also need to be validation to ensure that the type specified does indeed derive from `ClassMap`.

**Comment by JoshClose** [comment]
This already exists. https://github.com/JoshClose/CsvHelper/blob/808dea2456b9c695eed1c124f67a2385e88b8a81/src/CsvHelper/CsvContext.cs#L119

**Comment by IanKemp** [comment]
And I'm apparently blind. Thank you!

**Comment by JoshClose** [comment]
No problem!
