### ISSUE TITLE
Cannot use field methods in Validate expression

### ISSUE THREAD

**Issue by ewaschenko** [JoshClose/CsvHelper#1834]
The documentation for Validate function has the variable for the Validate expression use the Contains method.  I use that code directly, however, the field variable (ValidateArgs) only has field.Field, and not field.Contains. It throws the error in the image.

```
public class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
    public DateTimeOffset? Date { get; set; }
}

public class FooMap : ClassMap<Foo>
{
    public FooMap()
    {
        Map(m => m.Id);
        Map(m => m.Name).Validate(field => !field.Contains("-"));
    }
}
![image](https://user-images.githubusercontent.com/9055167/126210426-59a5ac5d-85c7-431b-9752-626cdff24961.png)

```

![image](https://user-images.githubusercontent.com/9055167/126210473-d2a810f6-31fe-4eee-82cd-0ce19d54ae29.png)

**Comment by AltruCoder** [comment]
I'm guessing that example should be updated to the following.
```csharp
public class FooMap : ClassMap<Foo>
{
  public FooMap()
  {
    Map(m => m.Id);
    Map(m => m.Name).Validate(args => !args.Field.Contains("-"));
  }
}
```

**Comment by ewaschenko** [comment]
What if the field is an int? Do I manually have to convert to int?

`Map(m => m.Name).Validate(args => !Int32.Parse(args.Field) != 5);`

**Comment by AltruCoder** [comment]
Yes, since it appears that you only get the raw string from the field before it has been converted.  

https://github.com/JoshClose/CsvHelper/blob/dfd643d1b57a83b7ea5099e92e38f87723baac2c/tests/CsvHelper.Tests/Reading/ValidateTests.cs
