### ISSUE TITLE
ClassMap Not Working

### ISSUE THREAD

**Issue by mwasson74** [JoshClose/CsvHelper#1840]
**Describe the bug**
When using `ClassMap` to map the column names to their respective property names, a `HeaderValidationException` is thrown. However, when using the `Name` attribute to do the name mapping, it does not throw an exception and it works as expected.

**Example**
```csharp
    [TestClass]
    public class CsvTests
    {
        [TestMethod]
        public void ClassMapTests()
        {
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                Delimiter = ","
            };

            const string myLittleFile = "Column One,Column Two\r\n" +
                                        "123456,ABCDEFG\r\n";

            using (var csv = new CsvReader(new StringReader(myLittleFile), config))
            {
                try
                {
                    csv.Context.RegisterClassMap<MyLittleClassMap>();
                    var records = csv.GetRecords<MyLittleClass>().ToList();
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    throw;
                }
            }
        }
    }

    public class MyLittleClassMap : ClassMap<MyLittleClass>
    {
        public MyLittleClassMap()
        {
            Map(m => m.ColumnOne).Index(0).Name("﻿Column One");
            Map(m => m.ColumnTwo).Index(1).Name("Column Two");
        }
    }

    public class MyLittleClass
    {
        //[Name("Column One")]
        public string ColumnOne { get; set; }
        //[Name("Column Two")]
        public string ColumnTwo { get; set; }
    }
```
**Exception**
> CsvHelper.HeaderValidationException: Header with name '﻿Column One'[0] was not found.
> If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.
> 
> IReader state:
>    ColumnCount: 0
>    CurrentIndex: -1
>    HeaderRecord:
> ["Column One","Column Two"]
> IParser state:
>    ByteCount: 0
>    CharCount: 23
>    Row: 1
>    RawRow: 1
>    Count: 2
>    RawRecord:
> Column One,Column Two
> 
> 
>     at CsvHelper.Configuration.ConfigurationFunctions.HeaderValidated(HeaderValidatedArgs args)
>    at CsvHelper.CsvReader.ValidateHeader(Type type)
>    at CsvHelper.CsvReader.ValidateHeader[T]()
>    at CsvHelper.CsvReader.<GetRecords>d__87`1.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at SuperSecretNamespace.CsvTests.ClassMapTests()

**Expected behavior**
Values mapped to properties just as they are when the Name attribute is used.

**Additional context**
It is definitely possible that I am using the library incorrectly but I (obviously) don't think that I am.

**Comment by JoshClose** [comment]
When I do a `.ToCharArray()` on your `.Name("Column One");` I get this:
```
{char[11]}
    [0]: 65279 '﻿'
    [1]: 67 'C'
    [2]: 111 'o'
    [3]: 108 'l'
    [4]: 117 'u'
    [5]: 109 'm'
    [6]: 110 'n'
    [7]: 32 ' '
    [8]: 79 'O'
    [9]: 110 'n'
    [10]: 101 'e'
```
Looking that up, 65279 is a byte order mark (BOM).

I'm not sure how you got a BOM in there, but I'm guessing you copy/pasted it from somewhere. If it was at the beginning of a file you opened, the text editor may have used the wrong encoding or something. I'm only guessing though.

**Comment by mwasson74** [comment]
I have no idea how that got in there either 🤷‍♂️ but I deleted it and rewrote it and it's working. What a fun day I've had 🤦‍♂️.

Thanks!!

**Comment by JoshClose** [comment]
lol no problem
