### ISSUE TITLE
Support .NET 6 DateOnly and TimeOnly types

### ISSUE THREAD

**Issue by jnm2** [JoshClose/CsvHelper#1854]
Reading to a DateOnly property doesn't work out of the box in 27.1.1:

> CsvHelper.TypeConversion.TypeConverterException: 'The conversion cannot be performed.
> Text: '2021-09-04'
> MemberType: 
> TypeConverter: 'CsvHelper.TypeConversion.DefaultTypeConverter'

These are BCL types that will be released in November with .NET 6:
https://docs.microsoft.com/en-us/dotnet/api/system.dateonly
https://docs.microsoft.com/en-us/dotnet/api/system.timeonly

The easiest way to implement support for these might be to add a `net6.0` build and build using the most recent .NET 6 SDK, but it would also be possible to implement support dynamically in a `netstandard2.0` build using reflection or compiled expressions which lights up whenever it sees types with the full type name `System.DateOnly` and `System.TimeOnly` without having compile-time references to these types. This would not require building using the .NET 6 SDK and would not require adding a `net6.0` assembly.

**Comment by JoshClose** [comment]
Do you know if there will be a backwards compatibility nuget package for this?

I generally don't like installing pre-releases as they've messed up my computer in the past. Maybe that is a non-issue these days.

You could probably just copy the `DateTimeConverter` and create one for each type. You then just register them globally.

```cs
csv.Context.TypeConverterCache.AddConverter<DateOnly>(new DateOnlyTypeConverter());
csv.Context.TypeConverterCache.AddConverter<TimeOnly>(new TimeOnlyTypeConverter());
```

**Comment by jnm2** [comment]
Not that I'm aware of, and I'm skeptical that there would be. Either way, I don't think it would be ideal to depend on such a package. It would add a .dll file that every app using CsvHelper would automatically begin distributing.

I've been using VS prereleases for ~3 years on my home and work machines (so always the next .NET SDK preview) without any cross-contamination issues.

Like I mentioned, CsvHelper can support these types out of the box without any compile-time references to DateOnly and TimeOnly types and without using a newer SDK. It's a little extra work but not that much. I'd be willing to help out if you're interested.

Thanks for noting the workaround!

**Comment by JoshClose** [comment]
When new releases of the preview come out, can you just install the new one or do you need to remove the old one first? From both the OS and VS I guess.

**Comment by jnm2** [comment]
If you're speaking just about the preview of the .NET SDK, you never need to remove any and they don't clean up automatically when you install the next one (that I know of). I don't manually install .NET SDK previews though; I let the Visual Studio preview installer keep my preview SDK version up to date, and the VS installer is nice enough to remove previous SDK versions that had originally been installed by the VS installer.

**Comment by JoshClose** [comment]
Can you test out these 2 and make sure they work as you expect?

```cs
// Copyright 2009-2021 Josh Close
// This file is a part of CsvHelper and is dual licensed under MS-PL and Apache 2.0.
// See LICENSE.txt for details or visit http://www.opensource.org/licenses/ms-pl.html for MS-PL and http://opensource.org/licenses/Apache-2.0 for Apache 2.0.
// https://github.com/JoshClose/CsvHelper
#if NET6_0
using CsvHelper.Configuration;
using System.Globalization;

namespace CsvHelper.TypeConversion
{
	/// <summary>
	/// Converts a <see cref="DateOnly"/> to and from a <see cref="string"/>.
	/// </summary>
    public class DateOnlyConverter : DefaultTypeConverter
    {
		/// <summary>
		/// Converts the string to an object.
		/// </summary>
		/// <param name="text">The string to convert to an object.</param>
		/// <param name="row">The <see cref="IReaderRow"/> for the current record.</param>
		/// <param name="memberMapData">The <see cref="MemberMapData"/> for the member being created.</param>
		/// <returns>The object created from the string.</returns>
		public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
		{
			if (text == null)
			{
				return base.ConvertFromString(null, row, memberMapData);
			}

			var formatProvider = (IFormatProvider)memberMapData.TypeConverterOptions.CultureInfo.GetFormat(typeof(DateTimeFormatInfo)) ?? memberMapData.TypeConverterOptions.CultureInfo;
			var dateTimeStyle = memberMapData.TypeConverterOptions.DateTimeStyle ?? DateTimeStyles.None;

			return memberMapData.TypeConverterOptions.Formats == null || memberMapData.TypeConverterOptions.Formats.Length == 0
				? DateOnly.Parse(text, formatProvider, dateTimeStyle)
				: DateOnly.ParseExact(text, memberMapData.TypeConverterOptions.Formats, formatProvider, dateTimeStyle);
		}
	}
}
#endif
```

```cs
// Copyright 2009-2021 Josh Close
// This file is a part of CsvHelper and is dual licensed under MS-PL and Apache 2.0.
// See LICENSE.txt for details or visit http://www.opensource.org/licenses/ms-pl.html for MS-PL and http://opensource.org/licenses/Apache-2.0 for Apache 2.0.
// https://github.com/JoshClose/CsvHelper
#if NET6_0
using CsvHelper.Configuration;
using System.Globalization;

namespace CsvHelper.TypeConversion
{
	/// <summary>
	/// Converts a <see cref="TimeOnly"/> to and from a <see cref="string"/>.
	/// </summary>
	public class TimeOnlyConverter : DefaultTypeConverter
	{
		/// <summary>
		/// Converts the string to an object.
		/// </summary>
		/// <param name="text">The string to convert to an object.</param>
		/// <param name="row">The <see cref="IReaderRow"/> for the current record.</param>
		/// <param name="memberMapData">The <see cref="MemberMapData"/> for the member being created.</param>
		/// <returns>The object created from the string.</returns>
		public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
		{
			if (text == null)
			{
				return base.ConvertFromString(null, row, memberMapData);
			}

			var formatProvider = (IFormatProvider)memberMapData.TypeConverterOptions.CultureInfo.GetFormat(typeof(DateTimeFormatInfo)) ?? memberMapData.TypeConverterOptions.CultureInfo;
			var dateTimeStyle = memberMapData.TypeConverterOptions.DateTimeStyle ?? DateTimeStyles.None;

			return memberMapData.TypeConverterOptions.Formats == null || memberMapData.TypeConverterOptions.Formats.Length == 0
				? TimeOnly.Parse(text, formatProvider, dateTimeStyle)
				: TimeOnly.ParseExact(text, memberMapData.TypeConverterOptions.Formats, formatProvider, dateTimeStyle);
		}
	}
}
#endif
```

**Comment by jnm2** [comment]
Works great for me!

**Comment by JoshClose** [comment]
I get this error when trying to build with `dotnet build`.

> The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.  C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props

**Comment by JoshClose** [comment]
```
"C:\Program Files\dotnet\dotnet.exe" build C:\Users\narsh\Projects\CsvHelper\CsvHelper.sln --configuration Release --no-restore /property:AssemblyVersion=27.0.0.0 /property:FileVersion=27.2.0.0 /property:InformationalVersion=27.2.0+Branch.master.Sha.b62760c9d133922bd869627952463924d69d95bf
```

You can leave out the `--no-restore` part.

**Comment by jnm2** [comment]
Is this in a pushed branch, or just after adding `net6.0` to csproj TargetFrameworks?

**Comment by JoshClose** [comment]
Pushed.

Run this:
```
./build.cmd pack --configuration Release
```

**Comment by jnm2** [comment]
Fails for me too, and I haven't heard of the WorkloadAutoImportPropsLocator SDK before.

> The SDK 'Microsoft.NET.SDK.WorkloadAutoImportPropsLocator' specified could not be found.  C:\Program Files\dotnet\sdk\6.0.100-preview.7.21379.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.ImportWorkloads.props

**Comment by jnm2** [comment]
Looks like https://github.com/dotnet/sdk/issues/17461.

**Comment by JoshClose** [comment]
And you have the latest Visual Studio 2022 installed, right? So that shouldn't be the issue.

**Comment by jnm2** [comment]
Based on Mikalya's comment, I'm guessing that Nuke is resolving a non-preview MSBuild.

**Comment by jnm2** [comment]
`dotnet build . -c Release` works for me.

**Comment by JoshClose** [comment]
I'll ask in their Slack channel.

**Comment by JoshClose** [comment]
Actually... I should probably update to the latest and make sure that doesn't fix it.

**Comment by jnm2** [comment]
In the meantime, here's how to call DateOnly.Parse without compiling for .NET 6, working as expected when people use your .NET 5 etc builds on .NET 6:

```cs
using System.Globalization;
using System.Linq.Expressions;
using System.Reflection;

var method = Type.GetType("System.DateOnly")?.GetMethod(
	"Parse",
	BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly,
	null,
	new[] { typeof(string), typeof(IFormatProvider), typeof(DateTimeStyles) },
	null);

if (method is null) throw new NotImplementedException("Not .NET 6. Perhaps prevent DateOnlyConverter from being instantiated and included in the first place?");

var parameters = Array.ConvertAll(method.GetParameters(), p => Expression.Parameter(p.ParameterType));

// This should probably be cached as a static class field
var parseDelegate = Expression.Lambda<Func<string, IFormatProvider, DateTimeStyles, object>>(
	Expression.Convert(Expression.Call(method, parameters), typeof(object)),
	parameters).Compile();

var dateOnlyAsObject = parseDelegate.Invoke("2021-09-08", null, DateTimeStyles.None);
```

**Comment by JoshClose** [comment]
I got it working. Is it safe to publish older .net assemblies built with net6.0 preview?

**Comment by jnm2** [comment]
Awesome! I'm sure it is safe, though go-live is still around the corner. This is a guess based on how bad of a bug that would probably be and the fact that I haven't personally heard of it happening. Paranoid mode could be to diff the assemblies.

**Comment by JoshClose** [comment]
This feature is in version 27.2.0 on nuget.
