### ISSUE TITLE
Problem with '=' char

### ISSUE THREAD

**Issue by dvign72** [JoshClose/CsvHelper#1879]
Hi, 
I have the following CSV file:
```
Codice Cliente;Codice Agente;Nome Agente
="10000003";A000008;ROTTIGNI RICCARDO
="10000007";A000008;ROTTIGNI RICCARDO
="10000009";A000008;ROTTIGNI RICCARDO
```
When I try to parse, I receive an error.

After a while I see that the problem is due to the '=' character present in the lines. In fact, if I remove the character, I am able to read correctly.

Clearly, I cannot edit the CSV file that comes to me.

How can I solve the problem?

Ciao
Davide

**Comment by Gerappa92** [comment]
Hi,

I have reproduced the issue and the error message is:
```
An unhandled exception of type 'CsvHelper.BadDataException' occurred in CsvHelper.dll: 'You can ignore bad data by setting BadDataFound to null.
```

According to the recommendation from the error message I have set BadDataFound to null:
```cs
var config = new CsvConfiguration(System.Globalization.CultureInfo.InvariantCulture);
config.Delimiter = ";";
config.BadDataFound = null;

using(var reader = new StreamReader(@"./test-files/problem-with-equal-char.csv"))
using (var csv = new CsvReader(reader, config))
{
    records = csv.GetRecords<Foo>().ToList();
}
```

After that, the values with "=" are parsed without exception.

Is it correct behaviour or should it be fixed somehow? I'm ready to help with this issue 😃

**Comment by JoshClose** [comment]
Ignoring bad data could put you in a bad state, so I would avoid that.

Did you try the trim suggestion from above?

**Comment by Gerappa92** [comment]
Your suggestion works however it changes input data by removing "=" char.
I'm not sure if it was what @dvign72 wanted to achieve.

**Comment by JoshClose** [comment]
The `=` before is something Excel inserts. It's not a part of the data. It actually makes the CSV file invalid. 

https://stackoverflow.com/a/34596323/68499

**Comment by Gerappa92** [comment]
So I understand that it is not a bug in the library but it is a problem with data.

**Comment by JoshClose** [comment]
Yes, and I have chosen to not implement Excel specific things.
