### ISSUE TITLE
Bring Back the ShouldSkipRecord Setter

### ISSUE THREAD

**Issue by matiaspecile** [JoshClose/CsvHelper#1888]
Hi Josh,

I'm back with my bi-yearly support request.  I don't know if explicitly expressed thanks or not for the previous help, so thanks again! :)

I'm migrating an existing project to v20+, but I'm not sure I'm doing it correctly whilst dealing with ShouldSkipRecord's setter removal.

In the project, we have logic that identifies the index of a given header value, then that index is used in the ShouldSkipRecord lambda along/within with some other logic.

Now, since I can't get the index of the header values until after setting the configuration of the CsvReader, I'm in a bit of a chicken/egg conundrum.

My initial thought is to instantiate two CsvReaders - one for the header and one for the rest of the rows.  It could be that I've used this with a setter for so many years that I'm biased, but the extra reader seems excessive.

Is this a viable solution?  Is there another way?

Thanks again!

**Comment by matiaspecile** [comment]
there's something to be said here about the indispensable hiding in plain sight or something like that...  that works like a charm.  thanks for the help!

**Comment by JoshClose** [comment]
Great! You're welcome.
