### ISSUE TITLE
ignore this

### ISSUE THREAD

**Issue by realbart** [JoshClose/CsvHelper#1895]
I try to redirect the CsvHelper's output directly to the http response output stream, which only supports asynchronous writes.
If I use CsvHelper.WriteAsync -> StreamWriter -> HttpContext.Response.Body, it throws an exception telling synchonous writes are not allowed.

**Comment by JoshClose** [comment]
`CsvHelper.WriteAsync` doesn't exist. Did you mean `CsvWriter.WriteRecordsAsync`?

**Comment by realbart** [comment]
Yes, that one

**Comment by realbart** [comment]
When attempting to recreate this problem everything worked.
I *did* get a messeage I wasn't supposed to write to the stream synchronously at the WriteRecordsAsync-line earlier, but that might have been due to errors somewhere else in my code.

Thanks for responding so quickly and my apologies for wasting you time.

```
        [HttpGet("GetCsv")]
        public async Task GetCsvAsync()
        {
            Microsoft.AspNetCore.Http.HttpResponse response = HttpContext.Response;
            response.ContentType = "text/csv; charset=utf-8";
            response.Headers.Add("Content-Disposition", "attachment;filename=RideList.csv");
            var rides = new[] {
                new RideListViewDto{Id=1, LicensePlate="ABC123"},
                new RideListViewDto{Id=2, LicensePlate="DEF456"},
                };
            using var writer = new StreamWriter(response.Body);
            using var csvWriter = new CsvWriter(writer, CultureInfo.InvariantCulture);
            csvWriter.Context.RegisterClassMap<CsvMap>();
            await csvWriter.WriteRecordsAsync(rides);
            await HttpContext.Response.CompleteAsync();
        }
```

**Comment by JoshClose** [comment]
No worries! Glad you figured it out.
