### ISSUE TITLE
Dependency Microsoft.Bcl.AsyncInterfaces currently bound to version 5.0.0, can it be changed to allow 6.0.0 also?

### ISSUE THREAD

**Issue by cearny** [JoshClose/CsvHelper#1901]
**Is your feature request related to a problem? Please describe.**
I currently am having issues with using both Microsoft.Extensions.DependencyInjection 6.0.0 and CsvHelper 27.1.1 because one wants Microsoft.Bcl.AsyncInterfaces 6.0.0 and the other one is locked on Microsoft.Bcl.AsyncInterfaces 5.0.0

**Describe the solution you'd like**
Could it be possible to change the dependencies so that both Microsoft.Bcl.AsyncInterfaces 5.0.0 and Microsoft.Bcl.AsyncInterfaces 6.0.0 are allowed?

**Describe alternatives you've considered**
I could directly add Microsoft.Bcl.AsyncInterfaces 5.0.0 as a dependency where CsvHelper is also used. This does make me end up with two versions of Microsoft.Bcl.AsyncInterfaces.

**Additional context**
N/A

**Comment by KoalaBear84** [comment]
Should be fixed with this now:
https://github.com/JoshClose/CsvHelper/commit/e3d1962f525d4a5dc97e81feb893e3856b0c9bc2

**Comment by cearny** [comment]
@KoalaBear84 thanks but I don't think that's it. My project's target is `net47` and it relies on other class libraries that are `netstandard2.0` which, in turn, use MS's dependency injection, which can be updated to version 6.0.0 when targeting that as well.

So I have a base class library that's netstandard2.0 and uses Microsoft's DI. It gets consumed by other projects, some of which are (just recently) targeting `net6.0`, and some of which are targeting `net47`.

The problem is here I believe: https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvHelper.csproj#L63 (for target net47, require Microsoft.Bcl.AsyncInterfaces version 5.0.0 _only_). Same issue with the netstandard2.0 target, actually, now that I'm looking at it.

I'll try and change those dependencies to read `[5.0.0,6.0.0]` and run the test suite locally. `Microsoft.Bcl.AsyncInterfaces` hasn't been meaningfully touched in 16 months (see https://github.com/dotnet/runtime/tree/release/6.0/src/libraries/Microsoft.Bcl.AsyncInterfaces) so I expect no conflicts.

**Comment by mattmckinstry** [comment]
Looking forward to a release with this change as we cant fully update to .net 6 without it

**Comment by JoshClose** [comment]
Have you tried assembly redirects? I'm curious if that will work also.

**Comment by bjallemad** [comment]
Do you really need to specify exact versions of dependencies?
We have about 30 other nuget-packages references, and none of them uses exact version references, CsvHelper is the only one...
For now we are using version 27.0.2 instead, since that version did not specify exact dependencies...
That version works perfectly when targeting multiple frameworks.

**Comment by JoshClose** [comment]
There is a discussion about this here. https://github.com/JoshClose/CsvHelper/issues/1597 I'm thinking that using a known range that works is probably the best idea. I'll have to go through each reference and find the lowest version that works. :(

**Comment by eerhardt** [comment]
Check out https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/dependencies#nuget-dependency-version-ranges

❌ AVOID NuGet package references that demand an exact version.

❌ AVOID NuGet package references with a version upper limit.

Unless you know a newer version doesn't work with your package, you shouldn't set an upper limit.

For `Microsoft.Bcl.AsyncInterfaces`, it should never have breaking changes in it. Thus every new version should work.

**Comment by JoshClose** [comment]
All the references have been changed to use the lowest version that works with CsvHelper. >=

**Comment by JoshClose** [comment]
```xml
<PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.0.0" />
```

**Comment by cearny** [comment]
Can confirm it works a treat now. Thanks a bunch!

**Comment by zxsanny** [comment]
we're having .net 4.7 and aspnet webworms, with packages.config, which doesn't allow to set package versions range, only exact version unfortunatelly. So, we're using Microsoft.Bcl.AsyncInterfaces version 6.0.0, and still can't use csvHelper, cause it has only 5.0.0 version of this lib. Unfortunately now I'm forced to write csv file manually..

**Comment by dplabsindia** [comment]
> =



> ```
> <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="1.0.0" />
> ```



> All the references have been changed to use the lowest version that works with CsvHelper. >=

As per my understanding the CSVHelper now looking for only the version 1.0.0.0 of Bcl Interfaces instead taking the available latest version. 
The problem still persists as any version of CSVHelper is not working with bcl interfaces 5.0.0.0. It always look at a particular version. No one can maintain multiple versions in one application.
