### ISSUE TITLE
Update Microsoft.Bcl.AsyncInterfaces

### ISSUE THREAD

**Issue by rubenalves** [JoshClose/CsvHelper#1908]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependencies. 'Microsoft.Bcl.AsyncInterfaces 6.0.0' is not compatible with 'CsvHelper 27.2.0 constraint: Microsoft.Bcl.AsyncInterfaces (= 5.0.0)'.				

Is it possible to change Microsoft.Bcl.AsyncInterfaces (= 6.0.0) or Microsoft.Bcl.AsyncInterfaces (>= 5.0.0)
I canot update my application because CsvHelper that is dependante on Microsoft.Bcl.AsyncInterfaces V. 5.0

Thanks for your very good work.
Ruben

**Comment by LuckyTil** [comment]
Same issue

**Comment by rubenalves** [comment]
Looks like this project is not updated for a long time, do probably time to find a new one.

**Comment by JoshClose** [comment]
> Looks like this project is not updated for a long time, do probably time to find a new one.

![image](https://user-images.githubusercontent.com/114971/143104793-ed4e681b-590a-40e1-b633-0d8a7be39248.png)

I'm currently in the process of making the dependencies >= the lowest version that works for each version. Should be released soon and should fix this issue.

**Comment by rubenalves** [comment]
Ok, thanks for your feedback,

**Comment by JoshClose** [comment]
Fix in 27.2.1 in NuGet.

If this doesn't fix your issue, let me know and we can figure out what needs to changes.
