### ISSUE TITLE
How to handle empty datetime column

### ISSUE THREAD

**Issue by blupje** [JoshClose/CsvHelper#191]
Hi,

I use the GetRecords<> method. I have a datetime column that is empty like ;;
The reader crashes in the typeconverter. How do I handle this? I don't want default dates just null.

**Comment by yangs2016** [comment]
Even I have a property DateTime? in the class BadData, when I called IEnumerable<BadData> records=CsvReader.GetRecords<BadData>().ToList(), still got the "FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0.".

**Comment by AltruCoder** [comment]
@yangs2016, we would need more information, like what your BadData class looks like and the data in your csv file that is failing.

**Comment by yangs2016** [comment]
`public class BadData
	{
		public DateTime? SomeDateCouldBeEmptyInCsv { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
        }`
I had to do this to get it to work finally:
1. Created a custom class DateFieldConverter<T>:
`public class DateFieldConverter<T> : DefaultTypeConverter
		{
			public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
			{
				bool result = DateTime.TryParse(text, out DateTime ret);
				if (result) return ret;
				return null;
			}

			public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
			{
				return value.ToString();
			}
		}`

2. and used in the Map:
`Map(m => m.SomeDateCouldBeEmptyInCsv).TypeConverter<DateFieldConverter<string>>();`

Thanks!

**Comment by AltruCoder** [comment]
I'm not certain why you were having issues.  Using the latest version of CsvHelper, this worked for me.  The problem I see with your converter is you could have bad data and not just an empty string and I would expect bad data to throw an error, but now bad data will return null.
 ```csharp
using (var stream = new MemoryStream())
using (var writer = new StreamWriter(stream))
using (var reader = new StreamReader(stream))
using (var csv = new CsvReader(reader))
{
    writer.WriteLine("SomeDateCouldBeEmptyInCsv,FirstName,LastName");
    writer.WriteLine(",First Name,Last Name");
    writer.Flush();
    stream.Position = 0;

    var records = csv.GetRecords<BadData>().ToList();
}

public class BadData
{
    public DateTime? SomeDateCouldBeEmptyInCsv { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

**Comment by facebook-audience-networ** [comment]
@AltruCoder https://stackdev.space/questions/assigning-a-string-as-the-value-for-a-tsource
