### ISSUE TITLE
TrimOptions.Trim does not work

### ISSUE THREAD

**Issue by EatonZ** [JoshClose/CsvHelper#1910]
**Describe the bug**
Specifying `TrimOptions.Trim` in a `CsvConfiguration` has no effect.

**To Reproduce**
1. Set up a reader: `var csvReader = new CsvReader("Sample.csv", new CsvConfiguration(CultureInfo.InvariantCulture) { TrimOptions = TrimOptions.Trim };`
2. [Download this sample CSV file to load into the CsvReader.](https://github.com/JoshClose/CsvHelper/files/7591279/Sample.csv)
3. Create a record class containing `FirstName` and `FirstName` string properties, and call `csvReader.GetRecords<YOUR_RECORD_CLASS>();`
4. Observe how the first record's `FirstName` still has a trailing space character.

**Expected behavior**
`John ` should be `John` (no trailing space).

**Comment by JoshClose** [comment]
This took a bit, but that is not a space char. Space has a character code of 32. This character is 160. You would need to add this character to the whitespace list.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    TrimOptions = TrimOptions.Trim,
    WhiteSpaceChars = new char[]{ (char)32, (char)160 }
};
```

**Comment by EatonZ** [comment]
@JoshClose Good catch! This is the space character that Microsoft Excel saves into the CSV. Maybe this is something you may consider adding to the default since Excel is so common.

**Comment by JoshClose** [comment]
This is the char you get when using the spacebar in excel? It's a non-breaking space. Same as `&nbsp;` in html.

**Comment by EatonZ** [comment]
@JoshClose Actually it appears to be coming from a particular email. Copying the text with the space results in this. That makes sense since it's being copied from a web page.

**Comment by ari-walter** [comment]
@JoshClose I don't see the `WhiteSpaceChars` property anymore, was it removed or is there a new way of doing it?

**Comment by JoshClose** [comment]
It should be there. https://github.com/JoshClose/CsvHelper/blob/852bd465e0d460eb60013abdc07fff8f68f68a59/src/CsvHelper/Configuration/CsvConfiguration.cs#L158

**Comment by JoshClose** [comment]
Looks like version 20 it was introduced.
