### ISSUE TITLE
New version 27.2.1, but what is the content ?

### ISSUE THREAD

**Issue by mikkelbu** [JoshClose/CsvHelper#1911]
First, thanks for a great package.

**Describe the bug**
A new version 27.2.1 has been uploaded to NuGet https://www.nuget.org/packages/CsvHelper/27.2.1, but I cannot find any trace of this in this project. The latest commit and tag are both for 27.2.0 and the change log - https://joshclose.github.io/CsvHelper/change-log/ - only mentions 27.1.1, so it is impossible to tell what has changed in the new version.

Also fuget cannot find any API difference between 27.2.0 and 27.2.1 - https://www.fuget.org/packages/CsvHelper/27.2.1/lib/netstandard2.1/diff/27.2.0/

**Comment by kieronlanning** [comment]
It looks like it solves the issue detailed here: #1910

**Comment by adiessl** [comment]
The dependencies have changed, see https://github.com/JoshClose/CsvHelper/issues/1908#issuecomment-977176268 for further information.

![image](https://user-images.githubusercontent.com/42088160/143223201-74e35424-a531-460f-ab6d-4bfcd25fc06e.png)

I don't know why there are no corresponding code changes in this GitHub repository though.

**Comment by mikkelbu** [comment]
Thanks @adiessl 👍. I guess the changea and the release have been made locally and then the repository have been forgotten. I'm closing this as this was all I needed to know.

**Comment by JoshClose** [comment]
I just pushed the source. The change was to make the dependencies >= the lowest that are needed for CsvHelper to function.

**Comment by EatonZ** [comment]
@kieronlanning I can confirm it does **not** fix that issue I reported.

**Comment by JoshClose** [comment]
@EatonZ Are you referring to #1910? This wouldn't fix that.

**Comment by EatonZ** [comment]
@JoshClose Yes. Just wanted to confirm here that it didn't.🙂
