### ISSUE TITLE
Writing a record class that is set via a constructor has unnecessary pitfalls

### ISSUE THREAD

**Issue by kchristman54** [JoshClose/CsvHelper#1915]
# The problem
I followed the example in the documentation 
![image](https://user-images.githubusercontent.com/33758481/144127133-d0c7faef-dbab-49ca-9620-f812c84537ab.png)

But my "mistake" was that I used a constructor to set my properties (as opposed to using property setters): 

```c#
public class IssueLinkException
{
    public string LinkIssue { get; }
    public string ExceptionString { get; }
    public int IssueId { get; }
    public int ProjectId { get; }

    public IssueLinkException(string linkIssueJson, string exceptionString, int issueId, int projectId)
    {
          LinkIssue = linkIssueJson;
          ExceptionString = exceptionString;
          ProjectId = projectId;
          IssueId = issueId;
     }
}


[Test]
public void CsvHelperHasException()
{
      List<IssueLinkException> myRecords = new List<IssueLinkException>()
      {
              new IssueLinkException("blah blah", "more", 1, 2),
      };
            
       using StreamWriter writer = new StreamWriter(@"c:\dev\csvHelper.csv"); 
       using (CsvWriter csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
       {
             csv.WriteRecords(myRecords);
        }

}
```

Running my above code resulted in an un-informative exception on `WriteRecords`.
![image](https://user-images.githubusercontent.com/33758481/144127922-d584f8b2-9cb2-4d02-8de3-29aacdbad4de.png)

After awhile, I found out that I needed a default constructor on my record class. So I eventually got it to work when I added a default constructor:
```c#
public IssueLinkException() {}  // Do not remove this seemingly useless constructor, since csvHelper fails without it.

```

# Proposed
- Update the documentation to make it clear that a (seemingly useless) default constructor is needed when the record class is set using another constructor. 
- Make that exception message a little more explicit as to what the problem is.
- Make csvHelper flexible enough so that a default constructor is not needed in the case where another constructor is being used? Not sure if this is possible. 

Thanks for your work on this project!

**Comment by JoshClose** [comment]
I think there must be something else going on. This works fine for me. What I am doing wrong here?

```cs
void Main()
{
    var records = new List<Foo>
    {
        new Foo(1, "one")
    };
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
    };
    using (var writer = new StringWriter())
    using (var csv = new CsvWriter(writer, config))
    {
        csv.WriteRecords(records);
        writer.Dump();
    }
}

private class Foo
{
    public int Id { get; }
    public string Name { get; }
    
    public Foo(int id, string name)
    {
        Id = id;
        Name = name;
    }
}
```

![image](https://user-images.githubusercontent.com/114971/144141876-16f002c5-45e4-4dd6-a261-7524b6ec1469.png)

**Comment by kchristman54** [comment]
If I make a new project (e.g., console app) things work fine. So I must have something strange on my project that results in this strange behavior. Feel free to close. Thanks again!

**Comment by JoshClose** [comment]
If you find something, feel free to open this back up.
