### ISSUE TITLE
CSVHelper is Skipping the First Row of Records

### ISSUE THREAD

**Issue by wedadts** [JoshClose/CsvHelper#1921]
I am reading from csv file that has headers. But it skips the first row of data.

using(var reader = new StreamReader(path))
                
                using (var csv = new CsvReader(reader,CultureInfo.InvariantCulture))
                {
                    csv.Read();
                    while (csv.Read())
                    {
                        csv.ReadHeader();
                        var csvReaderConfiguration = new CsvHelper.Configuration.CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture)
                        {
                            MissingFieldFound = null
                        };
                        //csv.ValidateHeader(null);
                        list = csv.GetRecords<T>().ToList();
                    }
                    
                }

**Comment by JoshClose** [comment]
You are calling `Read` which reads the first row, then immediately after calling it again in the `while` loop which reads the second row.

**Comment by JoshClose** [comment]
Put the `ReadHeader` call before the `while` loop.

**Comment by JoshClose** [comment]
```cs
csv.Read();
csv.ReadHeader();
while (csv.Reader())
{
...
}
```

**Comment by wedadts** [comment]
It still skips the first row of data

**Comment by wedadts** [comment]
Solved it! I had to do "do while". Thank you for the hint!
using (var csv = new CsvReader(reader,CultureInfo.InvariantCulture))
                {
                    

                    do
                    {
                        csv.Read();
                        csv.ReadHeader();
                        var csvReaderConfiguration = new CsvHelper.Configuration.CsvConfiguration(cultureInfo: CultureInfo.InvariantCulture)
                        {
                            MissingFieldFound = null
                        };
                        list = csv.GetRecords<T>().ToList();
                    } while (csv.Read());


                }

**Comment by JoshClose** [comment]
If you're doing `GetRecords<T>` you don't have to do any of that.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    MissingFieldFound = null,
};
using (var cs = new CsvReader(reader, config)
{
    list = csv.GetRecords<T>().ToList();
}
```

**Comment by zebi6321** [comment]
do
{
    //code
}
while((csv.Read( ));

Using this the problem of not reading first row of records will be resolved.

**Comment by LeaderXinjianSun** [comment]
CsvHelper Version="30.0.1".Write Read() and ReadHeader() before GetRecords will work.
```
using (var reader = new StreamReader(Path.Combine(@"D:\BaiduNetdiskDownload", "1234.csv"), Encoding.GetEncoding("gb2312")))
 using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
 {

     csv.Read();//⬅
     csv.ReadHeader();//⬅

     csv.Context.RegisterClassMap<ComparisonMap>();
     var records = csv.GetRecords<Comparison>().ToList();
     Console.WriteLine(records.Count);
 }
```

**Comment by AltruCoder** [comment]
@LeaderXinjianSun if you look at the [Getting Started](https://joshclose.github.io/CsvHelper/getting-started/) page for CsvHelper you will see.

> The GetRecords<T> method will return an IEnumerable<T> that will yield records.

What this means is that when you call `records.Any()` CsvHelper has to look at the first record to see if there are any records, but because it is `yielding` records, it can't go back.  So when you call `.ToList()` it will continue to `yield` records after the first row that was already read in `records.Any()`.  

What you could do is call `.ToList()` before `records.Any()`
```csharp
var records = csv.GetRecords<Comparison>().ToList();
if (records.Any())
{
    // Now you can do whatever you wanted to do with records instead of list.
}
```
