### ISSUE TITLE
Space not reflecting

### ISSUE THREAD

**Issue by RenjithPr90** [JoshClose/CsvHelper#1929]
If a space is provided for property string then output CSV data not showing properly
Eg :
Var data = new sample {Id = 1,data =" ", date2=sampledata}# SPACE IS PROVIDED FOR DATA

Now when CSV is generated it is showing space within quotes as shown below:

1," ",sampledata

Expected
1, ,sampledata

In expected space should be there between commas as , ,

**Comment by AltruCoder** [comment]
It appears this was intentional. The code add quotes if the string either starts or ends with a space. 

https://github.com/JoshClose/CsvHelper/blob/afd759f022edbfb842fffe527bf64dac0a8f1320/src/CsvHelper/Configuration/ConfigurationFunctions.cs#L94-L109

**Comment by AltruCoder** [comment]
You could create your own version of `ShouldQuote` in the config and remove the starts and ends with a space parts.
```csharp
void Main()
{
	var records = new List<Sample>
	{
		new Sample {Id = 1,data =" ", data2="sampledata"},
	};

	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		ShouldQuote = args => !string.IsNullOrEmpty(args.Field) &&
			(
			args.Field.Contains('"') // Contains quote
			|| args.Field.Contains(',') // Contains delimiter 
			|| args.Field.IndexOfAny(new char[] { '\r', '\n' }) > -1 // Contains line ending characters
			)
	};

	using (var csv = new CsvWriter(Console.Out, config))
	{
		csv.WriteRecords(records);
	}
}

public class Sample
{
	public int Id { get; set; }
	public string data { get; set; }
	public string data2 { get; set; }
}
```

**Comment by RenjithPr90** [comment]
@AltruCoder  Yes it is working now. Thanks for the support

**Comment by RenjithPr90** [comment]
Closing issue as there is provision inside config to fix issue
