### ISSUE TITLE
Reading file with a multiline cell fails as of ver. 20.0.0

### ISSUE THREAD

**Issue by adimcohen** [JoshClose/CsvHelper#1935]
Getting the following error on CsvReader.Read() the attached file:

```
CsvHelper.BadDataException: You can ignore bad data by setting BadDataFound to null.
IReader state:
   ColumnCount: 0
   CurrentIndex: -1
   HeaderRecord:

IParser state:
   ByteCount: 0
   CharCount: 9
   Row: 1
   RawRow: 1
   Count: 1
   RawRecord:
"test"
```

It works with no issues with ver. 19.0.0, but fails with all versions as of ver. 20.0.0.
The file is using CRLF for line breaks (both in and outside the multiline cell).

My code:

```
var config = new CsvConfiguration(CultureInfo.InvariantCulture);
csvReader = new CsvReader(reader, config);
csvReader.Read()
```

[testfile.csv](https://github.com/JoshClose/CsvHelper/files/7946530/testfile.csv)

**Comment by i2van** [comment]
Works with `config.BadDataFound = true`

Could you please reformat you message to make it readable? Just add new lines before and after code blocks.

**Comment by adimcohen** [comment]
Thank you for your reply.
`config.BadDataFound = true` fails with `Cannot implicitly convert type 'bool' to 'CsvHelper.BadDataFound'`.
Explicit conversion fails with the same error.
Tried on ver. 27.2.1

**Comment by i2van** [comment]
Try `config.BadDataFound = null`.

**Comment by adimcohen** [comment]
Works!
Thank you.
