### ISSUE TITLE
Support for appending new record to the existing file

### ISSUE THREAD

**Issue by GraceYuJuSong** [JoshClose/CsvHelper#194]
Current WriteRecord/WriteRecords methods overwrite existing records.
No support for appending new record to the existing file.

**Comment by killnine** [comment]
Just thought I'd mention a detail about this: where it's complicated is when there's a header for a CSV you're writing. That's the situation where having some real 'append' logic would help. However, I'm not sure where that responsibility would lie.

**Comment by JoshClose** [comment]
So you're appending and you have headers, so it writes the header again? Does turning headers off for writing not work in that situation?

**Comment by killnine** [comment]
Yeah, the way I was going to resolve was to actually set it via some logic at runtime with an if-check on `File.Exists(...)`.
