### ISSUE TITLE
ShouldSkipRecord ignoring header when HasHeaderRecord is true

### ISSUE THREAD

**Issue by luclava** [JoshClose/CsvHelper#1947]
**Is your feature request related to a problem? Please describe.**
When ShouldSkipRecord is set the reader checks the header row as well, even when HasHeaderRecord is set to true.
I think this could be a misleading behavior and could potentially lead to unexpected results like a HeaderValidationException because of header row skipped or losing the first data row even when it does not match the ShouldSkipRecord criteria.

If I'm not misunderstanding the purpose of ShouldSkipRecord and HasHeaderRecord, I believe the header shouldn't be checked by ShouldSkipRecord when HasHeaderRecord is set to true.

**Describe the solution you'd like**
A condition should be added to the code which filters out the matching rows to prevent checking the header when HasHeaderRecord is set to true.

**Describe alternatives you've considered**
The easiest workaround I found is to manually add a condition to ShouldSkipRecord to prevent matching the header.

**Comment by JoshClose** [comment]
If the CSV contains several blank lines, or other garbage info before the actual records start, then this won't work.

The next version has `IReaderRow` in the args instead of `string[]` so you'll be able to check if the current row is the first row and skip if you need to.
