### ISSUE TITLE
Specify null values

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#195]
Ability to specify a list of values in configuration that will evaluate to `null`. e.g. "NA", "NULL", "EMPTY".

Also allow `null` to be written as one of these values.

**Comment by MolallaComm** [comment]
I wanted this to work out of the box without having to write a bunch of custom converters/mappings, so I extended TypeConverterOptions with a new NullString property, and then I can globally do this:

            CsvHelper.TypeConversion.TypeConverterOptionsFactory.AddOptions<short?>(new CsvHelper.TypeConversion.TypeConverterOptions() { NullString = "NULL" });
            CsvHelper.TypeConversion.TypeConverterOptionsFactory.AddOptions<int?>(new CsvHelper.TypeConversion.TypeConverterOptions() { NullString = "NULL" });
            CsvHelper.TypeConversion.TypeConverterOptionsFactory.AddOptions<DateTime?>(new CsvHelper.TypeConversion.TypeConverterOptions() { NullString = "NULL" });
            CsvHelper.TypeConversion.TypeConverterOptionsFactory.AddOptions<string>(new CsvHelper.TypeConversion.TypeConverterOptions() { NullString = "NULL" });

The only other change required is in DefaultTypeConverter:

		public virtual string ConvertToString( TypeConverterOptions options, object value )
		{
			if( value == null )
			{
                return string.IsNullOrEmpty(options.NullString) ? string.Empty : options.NullString;
			}

			var formattable = value as IFormattable;
			if( formattable != null )
			{
				return formattable.ToString( options.Format, options.CultureInfo );
			}

			return value.ToString();
		}

Sure would like you to consider this change so I don't have to maintain my own build - don't think it could have any negative side effects.  Also, you might add documentation for TypeConverterOptions - as even the Format stuff doesn't appear anywhere that I saw in the documentation but is really useful. I didn't know about it until I looked at the code.  Great library!

**Comment by JoshClose** [comment]
This is in version 3.0. The default values are `"null"` and `"NULL"`.

**Comment by jzabroski** [comment]
@JoshClose This only allows users to specify CsvReader-side settings.  There is no equivalent for CsvWriter, as far as I can tell.  CsvWriter would pick a specific null value.  Use case is to write NULL instead of blank in an Excel document.

**Comment by JoshClose** [comment]
True. I just added a feature request for it. https://github.com/JoshClose/CsvHelper/issues/1497
