### ISSUE TITLE
Quotes inside unquoted fields flags malformed data.

### ISSUE THREAD

**Issue by Budsy** [JoshClose/CsvHelper#1953]
Description: In a csv file if there is a field that contains inner quotation marks, the scan will fail. Not really a true bug. Maybe this is more of a feature request.

Reproduce by using a csv file that includes a field constructed as follows:
.something else,  George "Buck" Smith, something else, something else, ...

Using CsvReader.GetRecords method and using default settings, it will fail at that line, giving a 'malformed data' error.

Expected: The field with ,George "Buck" Smith, appears to be valid csv. I can't find clear definitions on the web that this should be illegal for CSV. Given that it shouldn't cause a problem, I would expected these cases to be accepted by default. I see the delegate for BadDataFound works fine to accept these cases.  A helpful improvement would be the ability to set a property to opt-in to accepting these cases. That would save lines of code building out the delegate function.

version 27.2.1
tested under .NET 5

Request: Allow default scanning behavior accept these kinds of fields.

**Comment by kmcclive** [comment]
I ran into this issue as well.  I agree with @Budsy though.  This appears to be valid CSV to me.  RFC 4180 states the following:

> 7.  If double-quotes are used to enclose fields, then a double-quote
       appearing inside a field must be escaped by preceding it with
       another double quote.  For example:

       "aaa","b""bb","ccc"

Its validity depends on how you interpret "_If double-quotes are used to enclose fields_".  Does this apply at the field level or at the file/parser level?  In my case, I worked around this by setting ```Mode``` to ```NoEscape```.  This only works for me because the provider of the files has agreed that no field will contain commas or newlines.

```
var opts = new CsvConfiguration(CultureInfo.InvariantCulture) {
    Mode = CsvMode.NoEscape
};

using (var sr = new StringReader(data))
using (var csv = new CsvReader(sr, opts)) {
    // Do things.
}
```

**Comment by Budsy** [comment]
I guess the CSV world is a little loose on having a standard. But since I am having to deal with processing large files from outside sources, and some fields do have these inner quote cases (e.g.  ,Bob "Snoopy" Jones,) I went ahead and implemented the delegate hook in order to allow these kinds of fields. Here's an example of a lookup method implementation:

`static void MyBadDataFound(BadDataFoundArgs args)  // my method for the BadDataFound hook, c# 10 (.NET 6)
{
    // allows a well-formed inner quote string, but this example might pass additional malformations.
    if ( !((args.Field.StartsWith('"') && args.Field.EndsWith('"')).Equals(false) && args.Field.Contains("\"")))
    {
        throw new CsvHelperException(args.Context, "Bad data found");
    }
}

Customer? CustomerLookup(string accountId="")  // the lookup method. Combs a large file pretty quickly.
{
        using FileStream readStream = new FileStream(@".\Customers.csv", FileMode.Open);
        using StreamReader reader = new StreamReader(readStream);
        using CsvReader csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture) { 
            BadDataFound = new BadDataFound(MyBadDataFound),
        });
        csv.Context.Configuration.Encoding = System.Text.Encoding.UTF8;
        return  csv.GetRecords<Customer>().Where(x => x.NG_AcctNo == accountId).FirstOrDefault();
}`

**Comment by crowbar27** [comment]
@kmcclive Thanks for pointing out `CsvMode.NoEscape` - I was looking for s.th. like that, but did not find it.

Furthermore, I did not read the RFC, but IMHO _"If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped "_ can only be interpreted as that double quotes are valid and need not to be escaped if the field itself is not enclosed in quotes. From my investigation of #1954, I think that the parser does not implement this behaviour in `CsvMode.RFC4180`, but requires the field to be enclosed in quotes if it contains quotes.

`fieldIsQuoted` is only set when handling the start of a field:
https://github.com/JoshClose/CsvHelper/blob/afd759f022edbfb842fffe527bf64dac0a8f1320/src/CsvHelper/CsvParser.cs#L387-L389

And later, if `fieldIsNotQuoted`, any quote or escape character triggers malformed data:
https://github.com/JoshClose/CsvHelper/blob/afd759f022edbfb842fffe527bf64dac0a8f1320/src/CsvHelper/CsvParser.cs#L420-L428

**Comment by crowbar27** [comment]
Actually, the parser is right, because the RFC states at bit earlier

> 5.  Each field may or may not be enclosed in double quotes (however
       some programs, such as Microsoft Excel, do not use double quotes
       at all).  If fields are not enclosed with double quotes, then
       double quotes may not appear inside the fields.  For example:

**Comment by JoshClose** [comment]
When 7 says

> If double-quotes are used to enclose fields...

that was already preceded by 5

> ...If fields are not enclosed with double quotes, then double quotes may not appear inside the fields...

and preceded by 6

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

You can't have double quotes in a field without the field being double quoted and the double quotes inside escape by doubled quotes.

If not there is no way to determine field separation and line breaks. You would be able to have a single quote in a field then too.

You want there to be able to have quotes in a field with no field quoting and not quote escaping. Only a human could possibly determine where the fields and rows end. If anyone is able to come up with an algorithm on how to parse something like that, I'd be more than happy to look into it.

For now there are 2 other modes besides RFC `4180` which has been mentioned. `Escape` which doesn't care about double quotes around a field and only an escape character on quotes and `NoEscape` which will ignore field double quotes and escape characters. `NoEscape` sounds like it may work in your situation.

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("something else, George \"Buck\" Smith, something else, something else\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        Mode = CsvMode.NoEscape,
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvParser(reader, config))
    {
        while (csv.Read())
        {
            csv.Record.Dump();
        }
    }
}
```

![image](https://user-images.githubusercontent.com/114971/157267893-d50a16bf-c4eb-4f1a-a61c-64abdfe3d23d.png)

If you have commas or line breaks in a field, this will not work.
