### ISSUE TITLE
Quoted fields are not correctly identified if buffer swap occurs on white space before quote

### ISSUE THREAD

**Issue by crowbar27** [JoshClose/CsvHelper#1954]
**Describe the bug**
If a CSV file is parsed which contains quoted fields and if there is a white space between the delimiter and the quote character and if that white space happens to be the last character in the buffer, the white space is not trimmed and bad data are detected incorrectly in line 422 of the parser:
```c#
						if (c == quote || c == escape)
						{
							// If the field isn't quoted but contains a
							// quote or escape, it's has bad data.
							fieldIsBadData = true;
						}
```

**To Reproduce**
1. Consider the following code:
```c#
public class Row {
    [Name("field1")] public int Field1 { get; set; }
    [Name("field2")] public int Field2 { get; set; }
    [Name("field3")] public string Field3 { get; set; }
}

var data = @"field1, field2, field3
1, 1, ""test""
2, 2, ""test""";

var opts = new CsvConfiguration(CultureInfo.InvariantCulture) {
    Delimiter = ",",
    TrimOptions = TrimOptions.Trim,
    BufferSize = 44
};

using (var sr = new StringReader(data))
using (var csv = new CsvReader(sr, opts)) {
    while (csv.Read()) {
        var r = csv.GetRecord<Row>();
    }
}
```

2. If this runs, a `BadDataException` is thrown in the above-mentioned line, because the parser does not recognise correctly that it needs to skip the space before the quote. In line 374 `var isFirstCharOfField = fieldStartPosition == bufferPosition - 1;`, it is assuming that this is not the begin of the field, wherefore it reaches the else branch in line 426.

**Expected behaviour**
I would expect that the parser ignores white spaces between the delimiter and therefore recognises that the field starts at the quote and correctly detected that the field is quoted. If you change the `BufferSize` to 45 (such that the swap is not happening on the space), the CSV is fully parsed.

**Comment by JoshClose** [comment]
Fix merged.
