### ISSUE TITLE
Quotes will not encapsulate fields

### ISSUE THREAD

**Issue by paulconcerto** [JoshClose/CsvHelper#1956]
With this config it will not encapsulate fields with quotes on the output.

                var config = new CsvHelper.Configuration.CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    HasHeaderRecord = true,
                    HeaderValidated = null,
                    MissingFieldFound = null,
                    IgnoreBlankLines = true,
                    ShouldQuote = args => args.FieldType == typeof(string),
                    Quote = '"'
                };

Here is the class that's being written. I need encapsulated fields.

 public class Category
        {
          
            [Index(1)]
            public string Name { get; set; }
    
            [BooleanTrueValues("yes")]
            [BooleanFalseValues("no")]
            public bool Published { get; set; }
    
            [Name("ParentCategoryName")]
            public string ParentCategoryName { get; set; }

            [Constant(1)]
            public int CategoryTemplateId { get; set; }
    
            [Constant(1)]
            public int DisplayOrder { get; set; }
    
            [Ignore]
            public int ParentCategoryId { get; set; }	
        }

**Comment by HolisticDeveloper** [comment]
Are you passing the config to the object to the CsvWriter constructor?

**Comment by paulconcerto** [comment]
Sorry forgot I opened this. Turned out to be my fault and not a bug. Got it working.
