### ISSUE TITLE
Custom NullValuesAttribute values throws a TypeConverterException when using with arrays

### ISSUE THREAD

**Issue by faarbaek** [JoshClose/CsvHelper#1960]
**Describe the bug**
When using the ```IndexAttribute``` and providing a range to extract an array of values, and setting the ```NullableValuesAttribute``` to other values other than an empty throws a ```TypeConverterException``` in the ```NullableConverter``` type converter

**To Reproduce**
```csharp
using(var reader = new StringReader("\"***\",\"\",\"2\""))
{
    using var csv = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture) { HasHeaderRecord = false });
    var rows = csv.GetRecords<Row>().ToList();
}

public class Row 
{
    [Index(0, 2)]
    [NullValues("", "***")]
    public int?[] Field {get;set;}
}
```

**Expected behavior**
Values set in ```NullValuesAttribute``` should be correct converted to null values in the resulting array.

**Comment by JoshClose** [comment]
Fixed in next version.
