### ISSUE TITLE
An inconsistent number of columns has been detected

### ISSUE THREAD

**Issue by bjarnef** [JoshClose/CsvHelper#1961]
**Describe the bug**
We are using CsvHelper in a project using v16.0.0 where we had this configuration:

```
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ",",
    DetectColumnCountChanges = true,
    HasHeaderRecord = true,
    HeaderValidated = null,
    MissingFieldFound = null,
    IgnoreBlankLines = false,
    IgnoreQuotes = false
};
```

In a newer project I have moving the logic to .NET Core using a newer v27.2.1 but same CSV file.
I noticed `IgnoreQuotes` property is no longer an option, but instead I have this:

```
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ",",
    DetectColumnCountChanges = true,
    HasHeaderRecord = true,
    HeaderValidated = null,
    MissingFieldFound = null,
    IgnoreBlankLines = false,
    Mode = CsvMode.Escape,
    // Ignore header case.
    PrepareHeaderForMatch = args => args.Header.ToLower()
};
```

However this now fails, because it identify 13 columns and there are only 12 header columns.

I am not sure if `IgnoreQuotes` handled this in a different way than the current `Mode` property.

Header column: 
`Cust no,Brand,Brand Name,Country,Country Name,Address,Zip,City,Name,Status,Phone,E-mail`

Record: 
`101704,10,ProDesign,353,Ireland,"25 Abbey Street, Ennis,",IE-CO. CLAIRE,Ennis,Eye Candy Opticians,10 - President,0656868800,info@eyecandyopticians.com`

It seems it doesn't like when quoted field also contain the delimiter. However when the quoted column (address) only contain a single comma (delimiter) everything seems to work.

Previous it seemed just to ignore the quotes and get whatever text it had inside quotes inclusive comma, which it mapped fine to the `Address` field.

![image](https://user-images.githubusercontent.com/2919859/160241882-756c3363-410b-4a8a-8cab-a94e054d936a.png)

**Expected behavior**
The record to identify 12 fields in the row.

**Screenshots**

![image](https://user-images.githubusercontent.com/2919859/160240890-2ef381a4-757b-4f75-883d-f2ad98ef87c4.png)

**Comment by JoshClose** [comment]
There are 3 parsing modes now you can use. I don't believe I have them documented, but there are descriptions in the xmldocs/intellisense. If you want to ignore quotes, you probably want to set the mode to `NoEscape`.

```cs
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Mode = CsvMode.NoEscape
};
```

**Comment by bjarnef** [comment]
HI @JoshClose

Yes, I saw this as well https://stackoverflow.com/a/65849138/1693918 

I tried with `CsvMode.NoEscape` as well, but it didn't seem to work either.

But downgrading to v19.0 which the following configuration works.

```
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ",",
    DetectColumnCountChanges = true,
    HasHeaderRecord = true,
    HeaderValidated = null,
    MissingFieldFound = null,
    IgnoreBlankLines = false,
    IgnoreQuotes = false,
    //Mode = CsvMode.Escape,
    // Ignore header case.
    //PrepareHeaderForMatch = args => args.Header.ToLower()
    PrepareHeaderForMatch = (header, index) => header.ToLower()
};
```

**Comment by JoshClose** [comment]
`IgnoreQuotes = false` was the default. Using the `Rfc4180` mode is what you want then. Maybe we can narrow down the issue you're running into.

**Comment by bjarnef** [comment]
Okay, it seem `CsvMode.RFC4180` did the trick instead, thanks. I guess `CsvMode.RFC4180` is default?

**Comment by JoshClose** [comment]
Yes that is the default. ;)
