### ISSUE TITLE
leading/trailing zeros on numeric field

### ISSUE THREAD

**Issue by gwely** [JoshClose/CsvHelper#197]
Is there any implementation of the `="0045"` syntax? I could not find it anywhere in the config or in the docs. This prevents Excel from removing the leading and trailing zeros on a number. Quotes alone do not prevent this. I would be more than happy to add it but wanted to check first if I was missing it somewhere.

**Comment by darkmyst** [comment]
Has this been implemented?

**Comment by JoshClose** [comment]
This was completed a long time ago. I'm not sure why I never marked is as closed.

**Comment by FarshanAhamed** [comment]
Hi @JoshClose, Is this option removed in the latest CsvHelper? I couldn't find the Prepend option.
