### ISSUE TITLE
Bad records added to result of GetRecords<T>

### ISSUE THREAD

**Issue by ajaffer91** [JoshClose/CsvHelper#1973]
**Describe the bug**
If you have a file that has more fields of data on a row than there are headers.
When `DetectColumnCountChanges = true `and the error thrown is handled in the callback to `ReadingExceptionOccured`. The record that threw the exception is still parsed and added to the result of GetRecords<T>. Even though it is parsed incorrectly and will have fields missing/incorrectly mapped.

For example: 
```
NAME, ADDRESS LINE 1, ADDRESS LINE 2, POSTAL CODE
Alpha, 1 Alpha Road, Alphaville, A1 ABC
Beta,   2, Beta Road, Betaville, B2 DEF
Gamma, 3 Gamma Road, Gammaville, G3 GHI
```
Here, the "Beta" row has an extra field compared to the header. This causes "B2 DEF" to be ignored and the resulting record is returned from `GetRecords<T>` even though a reading exception occurred on that row

**Expected behavior**
The record with incorrect number of fields should be omitted from the result of `GetRecords<T>`

**Comment by JoshClose** [comment]
This is expected. The parser will do a basic line parse initially, and will do a more in depth parse when accessing the fields.
