### ISSUE TITLE
Take in CsvParserConfig instread of CsvConfiguration in CsvParser's ctor

### ISSUE THREAD

**Issue by Genbox** [JoshClose/CsvHelper#1976]
Currently, CsvParser takes in a CsvConfiguration in its ctor: https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvParser.cs#L160

As a consequence, the user can set a lot of properties like `config.ShouldSkip` which is not used by the CsvParser, and that would create a lot of confusion.

Since [CsvConfiguration](https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfiguration.cs) inhertis from `IReaderConfiguration`, which in turn inherts from `IParserConfiguration`, it should be possible to just change CsvParsers ctor from using `CsvConfiguration` to start using `IParserConfiguration` instead.

To make usage easier for people, it might be prudent to add a class that inherits from `IParserConfiguration`, and make CsvConfiguration inherit from that instead of the interface. That way, the library supports this:

```csharp
CsvParserConfig parserConfig = new CsvParserConfig(); //Inherit from IParserConfiguration
parserConfig.Delimiter = "|";
//parserConfig.ShouldSkipRecord = x => x.Record[0] == string.Empty; //No longer possible, which is correct. Only CsvReader uses this property. Users can't shoot themselves in the foot anymore.

using (FileStream fs = File.OpenRead(file))
using (StreamReader sr = new StreamReader(fs))
using (CsvParser reader = new CsvParser(sr, parserConfig))
{
    //do stuff
}
```

**Comment by Genbox** [comment]
Thank you Josh!

**Comment by JoshClose** [comment]
I didn't change the config class though, just passing in the interface. The same one is used for writing too, which would make it more difficult. It would be easy enough if it was just `CsvReaderConfiguration : CsvParserConfiguration`, but it would somehow need to include `CsvWriterConfiguration` also.
