### ISSUE TITLE
CSVReader uses double the required memory due to "shouldSkipRecord" check.

### ISSUE THREAD

**Issue by alainbryden** [JoshClose/CsvHelper#1977]
**Describe the bug**
The code at:
https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvReader.cs#L245

```c#
do
{
    hasMoreRecords = parser.Read();
}
while (hasMoreRecords && shouldSkipRecord(new ShouldSkipRecordArgs(parser.Record)));
```
Forces a retrieval of `parser.Record` on every loop. This results in every field being converted to a string (time and memory allocation), and these strings dropped after the check. If the user subsequently requests the current record (or fields), they must pay the price a second time.

**Expected behavior**
Either retrieve the record in a way that is cached, so that subsequent requests for the record or fields by the user can re-use the strings (and array) it built, or else be very selective as to when that shouldSkipRecord condition is run (i.e. if the delegate has no handlers). Ideally both.

**Screenshots**
I caught this profiling, where I noticed all my calls to `Read` were responsible for the exact same amount of memory allocation as the calls to 'GetField' for each field:
![image](https://user-images.githubusercontent.com/2285037/167240597-01322f78-9261-411d-9efc-5bdce21e6721.png)

**Comment by JoshClose** [comment]
I was just looking into this because of another issue! It should only pull the fields that need to be accessed too. If they only want one field, then the entire row shouldn't be returned. Lots of processing is ignored until field retrieval.

Thanks for submitting this.

**Comment by JoshClose** [comment]
This is the issue I was referring to. https://github.com/JoshClose/CsvHelper/issues/1873

**Comment by JoshClose** [comment]
Things I'm doing to fix this:

- Field processing is cached in the parser. The generated field string is stored.
- Record processing is cached in the parser. The generated record `string[]` is stored.
- If `CsvConfiguration.ShouldSkipRecord` is null, it won't be called. It's null by default now.
- `ShouldSkipRecordArgs` now takes in `IReaderRow`. This allows the consumer to only look at the fields they want and not the entire record. This is unfortunately a breaking change.

If you see any issues with these or have any other suggestions, let me know.

**Comment by JoshClose** [comment]
Actually... I could make it so it's not a breaking change and deprecate some things for the next time I have to break it.

**Comment by JoshClose** [comment]
Looks like I can't actually.

**Comment by JoshClose** [comment]
This will be in the next release.
