### ISSUE TITLE
Quotes set to all columns except first one

### ISSUE THREAD

**Issue by PSViseca** [JoshClose/CsvHelper#1978]
Using version 27.2.1

If the configuration ShouldQuote is set to true then all the columns in output file are quoted except the first one. 

Example:
2022-05-09;"2022-W19";"2022-05"

Please fix the quote on the first column

**Comment by JoshClose** [comment]
Can you create a small example that reproduces this issue? This works for me.

```cs
void Main()
{
    var records = new List<Foo>
    {
        new Foo { Id = 1, Name = "one" },
    };
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        ShouldQuote = args => true
    };
    using (var writer = new StringWriter())
    using (var csv = new CsvWriter(writer, config))
    {
        csv.WriteRecords(records);
        writer.Dump();
    }
}

private class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
![image](https://user-images.githubusercontent.com/114971/167904775-c8484ace-4782-44c4-8803-ed430717a575.png)

**Comment by PSViseca** [comment]
I'm writing data from OleDBCommand but this shouldn't be a problem:

`OleDbCommand cmd = new OleDbCommand(query, con);

                cmd.CommandTimeout = 3600000;

                con.Open();

                DataTable dataTable = new DataTable();

                dataTable.Load(cmd.ExecuteReader());

                con.Close();

                reportsConnection.ReleaseConnection(con);

                MemoryStream ms = new MemoryStream();
                StreamWriter sw = new StreamWriter(ms, Encoding.UTF8);

                CsvConfiguration config = new CsvConfiguration(CultureInfo.CurrentCulture)
                {
                    HasHeaderRecord = hasHeaderRecord,
                    Delimiter = columnDelimiter,
                    Escape = Char.Parse(escapeCharacter),
                    ShouldQuote = x => (x.Row.Row > 1 && useQuotes)
                };

                if (rowDelimiter.Equals("CRLF"))
                {
                    config.NewLine = "\r\n";
                }
                else if (rowDelimiter.Equals("CR"))
                {
                    config.NewLine = "\r";
                }
                else if (rowDelimiter.Equals("LF"))
                {
                    config.NewLine = "\n";
                }

                using (var csv = new CsvWriter(sw, config))
                {

                    // Write columns
                    foreach (DataColumn column in dataTable.Columns)
                    {
                        csv.WriteField(column.ColumnName);
                    }
                    csv.NextRecord();

                    // Write row values
                    foreach (DataRow row in dataTable.Rows)
                    {
                        for (var i = 0; i < dataTable.Columns.Count; i++)
                        {
                            csv.WriteField(row[i]);
                        }
                        csv.NextRecord();
                    }`

**Comment by JoshClose** [comment]
Can you put a conditional breakpoint in your `ShouldQuote` implementation and see when it's returning false?

**Comment by PSViseca** [comment]
Sorry. My bad. It was problem of my Excel. The quotes are there. Only Excel doesn't display them correctly. Every other editor shows correct quotes
