### ISSUE TITLE
how to handle Double Quotes Inside Data?

### ISSUE THREAD

**Issue by TejendraPrasad** [JoshClose/CsvHelper#1998]
Hi All,

> 

Please label it as **question** - sorry for raising here..

> 

I have **First CSV** file as below with double quotes

> 

**Input:**
"Name","Description"
"test", " Desc"/1234"

> 

I want to remove all the double quotes and trim apart from description data i.e. Desc"/1234

> 

My **Output** should be as below

Name: test
Description: Desc"/1234
------------------------------------------------------------------------------------
I have **Second CSV** as below with no Double quotes

> 

Name,Description
test,  Desc/1234

> 

**My Output should be as below**

Name: test
Description: Desc/1234
------------------------------------------------------------------------------------
I tried below configuration but its removing double quotes in the middle...

`               

             var config = new CsvConfiguration(CultureInfo.InvariantCulture)   {
                HasHeaderRecord = true,
                BadDataFound = null,
                Delimiter = ",",
                //Quote = '"',
                Mode = CsvMode.NoEscape,
                TrimOptions = TrimOptions.Trim,
                //TrimOptions = TrimOptions.InsideQuotes  
            }; 
`

Please try to help with the configuration which works for both the csv file input</div>

**Comment by JoshClose** [comment]
You don't have a valid CSV file. Is there any way you can get the source in a valid format?

**Comment by TejendraPrasad** [comment]
Hi @JoshClose  thank you for your response.

Second CSV working perfectly fine.

Only problem is with first CSV when there is double quotes in the middle....

There are large number of end user sometimes CSV is enclosed with double quotes header and data which can be also escaped...

Problem is with double quotes in middle for example:

"Name","Description"
"test", " Desc"1234"

Output should be as below

Name: test
Description: Desc"1234

Currently it allows me to remove/escape double quotes front and end along with trim... But i don't want to remove double quotes in middle...

Should i handle Double quote in middle using BadDataFound event and do manually transformation for that row and column ?

I assume its almost similar issue https://github.com/JoshClose/CsvHelper/issues/1916

Please share your thoughts on this it would be helpful...

**Comment by AltruCoder** [comment]
I can accomplish what you are trying to do using `CsvMode.NoEscape` and a custom `TypeConverter`.  The problem is, you will need a separate `TypeConverter` for each different property type you have in your data.  For instance, in my example I need one for both `string` and for `int`.  Also, be advised that if you have a comma inside your outer quotes,  this workaround is going to fail.
```csharp
void Main()
{
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
		Mode = CsvMode.NoEscape,
		PrepareHeaderForMatch = options => options.Header.Trim('"')
	};
	
	using (var reader = new StringReader("\"Id\",\"Name\",\"Description\"\n\"1\",\"test\",\"Desc\"1234\""))
	using (var csv = new CsvReader(reader, config))
	{
		csv.Context.TypeConverterCache.AddConverter<string>(new RemoveStringQuotesConverter());
		csv.Context.TypeConverterCache.AddConverter<int>(new RemoveIntegerQuotesConverter());
		
		var records = csv.GetRecords<Foo>().Dump();
	}
}

public class Foo
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Description { get; set; }
}

public class RemoveStringQuotesConverter : StringConverter
{
	public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
	{
		var trimmed = text.Trim('"');

		return base.ConvertFromString(trimmed, row, memberMapData);
	}
}

public class RemoveIntegerQuotesConverter : Int32Converter
{
	public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
	{
		var trimmed = text.Trim('"');
		
		return base.ConvertFromString(trimmed, row, memberMapData);
	}
}

```

**Comment by TejendraPrasad** [comment]
@AltruCoder Thank you so much.. Yes, agreed with regards to comma or line break inside your outer quotes .. Especially for List conversion..

However, above workaround resolve the question..

But somewhere we can provide optional way to handle "Double Quote in middle" would be great.

thank you!

**Comment by JoshClose** [comment]
It's really not possible logically. Double quotes needs to be escaped by double quotes, otherwise it's the end of the field. If you have commas or line breaks in there, it really messes things up.

**Comment by waltniemczura** [comment]
> It's really not possible logically. Double quotes needs to be escaped by double quotes, otherwise it's the end of the field. If you have commas or line breaks in there, it really messes things up.

We have files where the field delimiter is a vertical bar and the creator feels then that quotes need not be escaped.  It'd be nice to have a setting other than ignoring bad data for this situation.
