### ISSUE TITLE
How to handle with Skip record?

### ISSUE THREAD

**Issue by lucasrochadejesus** [JoshClose/CsvHelper#1999]
Hi @JoshClose  and people, first of all thank you so much for CSVHelper, it's awesome!!!
I've an issue below about this example csv file: [Print Screen](https://i.stack.imgur.com/Dh39h.jpg)

I'm using the last version of CSVHelper (27.2.1)
I've created this topic in StackOverflow: [My StackOverflow topic](https://stackoverflow.com/questions/72886065/csv-file-blank-field-error-with-csvhelper-c-sharp/72886351#72886351)

For this example my MissingFieldFound = null doesn't work, I need to Skip the second record(in case row three record). my Map example is in StackOverflow topic.  I need to skip the row two in this case and send a Log message for example.

In this case is it possible to add in CSVHelper? for example, counting the Map and Headers in .csv file
Example:
Header1, Header2, Header3
Data1,Data1 column2,Data 1 column3
Data2,Data2 column2

to read the .csv file I'm using:
`var tempList = CsvHelper.GetRecords<WheelProsAccessoriesInventoryItem, WheelProsAccessoriesInventoryItemMap>(filePath).ToList();`

In my case I received Exception for example: 
```
CsvHelper.MissingFieldException: 'Field at index '23' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
IReader state:
   ColumnCount: 0
   CurrentIndex: 23
   HeaderRecord:
["PartNumber","PartDescription","Brand","CapHardwareDescription","CapScrewQuantity","CapWrench","CapStyleDescription","ImageURL","TotalQOH","MSRP","MAP","RunDate","1011","1015","1019","1022","1028","1031","1036","1071","1072","1085","1086","1088","4033","4035"]
IParser state:
   ByteCount: 0
   CharCount: 701
   Row: 4
   RawRow: 4
   Count: 14
   RawRecord:
ZSD60,XDS RIVETS XD799 BLACK,XD,N/A,,,,https://images.wheelpros.com/Accessories/ZSD60.png,30,0.37,0.00,07/04/2022 10:07:54 PM,0,
```
 
My csv file Example:
[accessoriesInvPriceData.csv](https://github.com/JoshClose/CsvHelper/files/9056617/accessoriesInvPriceData.csv)

**Comment by JoshClose** [comment]
You can use the config option `ShouldSkipRecord` to test if you want to skip it.

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("Id,Name\r\n");
    s.Append("1,one\r\n");
    s.Append("2\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
        ShouldSkipRecord = args => args.Record.Length != 2
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, config))
    {
        csv.GetRecords<Foo>().ToList().Dump();
    }
}

private class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
![image](https://user-images.githubusercontent.com/114971/177602975-000f122a-bd05-44ef-a95f-0733d621c9f3.png)

**Comment by JoshClose** [comment]
You can log in there too.

```cs
ShouldSkipRecord = args =>
{
    var skip = args.Record.Length != 2;
    if (skip)
    {
        // Log here.
    }
    
    return skip;
}
```

**Comment by lucasrochadejesus** [comment]
For example if I've one , missing : 
```
using CsvHelper;
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using Microsoft.VisualBasic.FileIO;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace test
{
    class Program
    {

        static void Main(string[] args)
        {

            var s = new StringBuilder();
            s.Append("PartNumber,PartDescription,Brand,CapHardwareDescription,ImageURL,TotalQOH,MSRP,MAP,RunDate,1011,1015,1019,1022,1028\r\n");
            s.Append("ZSD1,XDS1 RIVETS XD799 BLACK,XD1,NA,image2,30,100,200,A,1,2,3,0\r\n"); 
            s.Append("ZSD2,XDS2 RIVETS XD799 BLACK,XD2,NA,image2,30,200,300,C,1,\r\n"); 
            s.Append("ZSD4,XDS4 RIVETS XD799 BLACK,XD2,NA,image2,30,200,300,C,1,\r\n");

      
            int countSkips = 1;
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {

                MissingFieldFound = null,
                // ShouldSkipRecord = args => args.Record.Length <= 10
                ShouldSkipRecord = args =>
                {
                    
                    var skip = args.Record.Length < 6;
                    if (skip)
                    {
                        Console.WriteLine("\nSkipped fields:" + countSkips);
                        Console.WriteLine("PartNumber:" + args.Record[0].ToString() + " " + " | " + "PartDescription/Brand: " + args.Record[1].ToString() + "/" + args.Record[2].ToString());
                        Console.WriteLine("### END LOG SKIPPED RECORD ###");
                        countSkips++;
                    }

                    return skip;
                }
            };
            using (var reader = new StringReader(s.ToString()))
            using (var csv = new CsvReader(reader, config))
            {
                var foo = csv.GetRecords<Foo>().ToList();

                foreach (var item in foo)
                {
                    Console.WriteLine("\n\n\n" + "Result Readed" + item.PartNumber + " | " + item.PartDescription + " | " + item.Brand);
                }
            }
        }

        private class Foo
        {
            public string PartNumber { get; set; }
            public string PartDescription { get; set; }
            public string Brand { get; set; }
            public string CapHardwareDescription { get; set; }
            public string ImageURL { get; set; }
            public string TotalQOH { get; set; }
            public string MSRP { get; set; }
            public string MAP { get; set; }
            public string RunDate { get; set; }
          

            [Name("1011")]
            public string num1011 { get; set; }

            [Name("1015")]
            public string num1015 { get; set; }

            [Name("1019")]
            public string num1019 { get; set; }

            [Name("1022")]
            public string num1022 { get; set; }

            [Name("1028")]
            public string num1028 { get; set; }

 
        }


    }

 }

```

**Comment by JoshClose** [comment]
It's not skipping any of them because the record is never less than 6. You have `MissingFieldFound = null` which is ignoring that row. You should remove that and figure out what you need to do to skip rows instead.

**Comment by lucasrochadejesus** [comment]
I'm deleted because I type wrong code rsrs, but other thing is why I received an exception? 
Is it because I've more HeaderColumns then data rows right?

For example: I've one header with 26 columns and I Open with Notepad++ .
I have header:
`PartNumber,PartDescription,Brand,CapHardwareDescription,CapScrewQuantity,CapWrench,CapStyleDescription,ImageURL,TotalQOH,MSRP,MAP,RunDate,1011,1015,1019,1022,1028,1031,1036,1071,1072,1085,1086,1088,4033,4035`

 I have line 1:   
`ZSD60,XDS RIVETS XD799 BLACK,XD,N/A,,,,imageslink,30,0.37,0,07/04/2022 10:07:54 PM,1,,,,,,,,,,,,,`

**But** I don't have control for this data sometimes I receive a bad row with like this:
``ZSD60,XDS RIVETS XD799 BLACK,XD,N/A,,,,imageslink,30,0.37,0,07/04/2022 10:07:54 PM,1,,``
or
`ZSD60,XDS RIVETS XD799 BLACK,XD,N/A,,,,imageslink,30,0.37,0,07/04/2022 10:07:54 PM,1,2,3,4,5`

I Need to read the good data values and put in log the "bad" but I receive a Exception in the bad values..

Thank you so much! you are very helpful!!

**Comment by JoshClose** [comment]
Maybe you should just read manually. You'll have full control over everything then.

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("Id,Name\r\n");
    s.Append("1,one\r\n");
    s.Append("2\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, config))
    {
        var records = new List<Foo>();
        csv.Read();
        csv.ReadHeader();
        while (csv.Read())
        {
            var foo = new Foo();
            records.Add(foo);
            foo.Id = csv.GetField<int>(nameof(Foo.Id));
            if (csv.TryGetField<string>(nameof(Foo.Name), out var name))
            {
                foo.Name = name;
            }
        }
        
        records.Dump();
    }
}

private class Foo
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
![image](https://user-images.githubusercontent.com/114971/177808705-de2387af-e1ad-47e1-a7d1-94be70a75e65.png)

**Comment by lucasrochadejesus** [comment]
[test2.zip](https://github.com/JoshClose/CsvHelper/files/9067408/test2.zip)

I've created this example have a csv file inside the .csproj

**Comment by JoshClose** [comment]
Your configuration isn't being used. You need to pass it into the `CsvReader` constructor.

**Comment by lucasrochadejesus** [comment]
I don't know whats is wrong? 
`using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace test
{
    public class CsvHelper
    {
        public CsvHelper()
        { }

        public static IEnumerable<T> GetRecords<T, TMap>(string filename,int minFields = 0, bool hasFrenchChars = false)
       where T : class
       where TMap : ClassMap<T>
        {
            int countSkips = 1;

            using (var streamReader = new StreamReader(filename))
            {
                var config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    Delimiter = ",",
                    HasHeaderRecord = true,
                    Encoding = hasFrenchChars ? Encoding.GetEncoding("ISO-8859-1") : Encoding.UTF8,
                    IgnoreBlankLines = true,

                    ShouldSkipRecord = args =>
                    {
                        var skip = args.Record.Length < 14;
                        if (skip)
                        {
                            Console.WriteLine("\nSkipped fields:" + countSkips);
                            Console.WriteLine("PartNumber:" + args.Record[0].ToString() + " " + " | " + "PartDescription/Brand: " + args.Record[1].ToString() + "/" + args.Record[2].ToString());
                            Console.WriteLine("### END LOG SKIPPED RECORD ###");
                            countSkips++;
                        }

                        return skip;
                    },



                };

                using (var csvReader = new CsvReader(streamReader, config))
                {
                     

                    csvReader.Context.RegisterClassMap<TMap>();
               
                    return csvReader.GetRecords<T>().ToList();


                }

            }


        }

    }
}
`

**Comment by lucasrochadejesus** [comment]
After update 28.0 ShouldSkipRecord is broken

**Comment by JoshClose** [comment]
https://joshclose.github.io/CsvHelper/migration/v28/

**Comment by lucasrochadejesus** [comment]
> https://joshclose.github.io/CsvHelper/migration/v28/
 the correct is it below?
var skip = args.Row.Parser.Record.Length < 10; 

I've received the same issue above.

**Comment by JoshClose** [comment]
Yes, you are correct. I'll fix the docs.

**Comment by JoshClose** [comment]
Docs are updated.

**Comment by lucasrochadejesus** [comment]
Thank you..
