### ISSUE TITLE
WriteRecords adds an extra delimiter at the start of the first line.

### ISSUE THREAD

**Issue by thomas-molander** [JoshClose/CsvHelper#2017]
**Describe the bug**
WriteRecords adds an extra delimiter at the start of the first line when first adding custom header.

**To Reproduce**
I need to create a CSV file with a custom header. 
First line is the normal header, second line must only conatin three dashes (---). (Yes I know this is stupid but this is what the vendor has done)
Third line is where the data records start.

Actual code:
```cs
using (var writer = new StreamWriter(fileName)) {
    var config = new CsvConfiguration(CultureInfo.InvariantCulture);
    config.Delimiter = "\t";
    using (var csv = new CsvWriter(writer, config)) {
        csv.WriteHeader(typeof(MyRecordClass));
        csv.Flush();
        writer.WriteLine("\r\n---");
        csv.WriteRecords(records);
    }
}
```

The third line in the file now starts with a tab (the delimiter) which breaks the import of the CSV file at the other end. The extra delimiter is only on the first record, the rest are OK.
Example:
```
Col1\tCol2\tCol3
---
\tData1\tData2\tData3
Data1\tData2\tData3
```

**Expected behavior**
Earlier versions och CSV Helper (12.2.2) created a correct file where the third line start with the first column data.

Example:
```
Col1\tCol2\tCol3
---
Data1\tData2\tData3
Data1\tData2\tData3
```

This code has worked with earlier versions of CVSHelper (vserion 12.2.2) and this bug now occurs after I updated to 27.1 and still remains in version 28.0.1.

BR /Thomas

**Comment by JoshClose** [comment]
Try this.

```cs
csv.WriteHeader<Foo>();
csv.NextRecord();

csv.WriteField("---");
csv.NextRecord();

csv.WriteRecords(records);
```

**Comment by thomas-molander** [comment]
That worked.

Thank you for the help with a workaround!
BR /Thomas
