### ISSUE TITLE
Optional is not compatible with Index

### ISSUE THREAD

**Issue by ishanpranav** [JoshClose/CsvHelper#2021]
**Describe the bug**
I am not sure if this is a bug or an intentional design, but it seems to be an inconvenience nonetheless. `OptionalAttribute` works well with auto-mapped properties and properties marked with `NameAttribute`, but those with `IndexAttribute` do not respect the "optional" behavior. Whenever a missing field is encountered, the missing field delegate triggers. The behavior is presumably the same when using the `Optional()` and `Index(int)` methods in a class map.

**To Reproduce**
Attempt to deserialize the following class using a `CsvReader` instance with the default configuration (invariant culture).
```csharp
public class Log
{
    [Optional]
    public int A { get; set; }

    [Name("Example")]
    [Optional]
    public int B { get; set; }

    [Index(2)]
    [Optional]
    public int C { get; set; }
}
```
**Expected behavior**
When present, the "A" and "Example" are used to fill `A` and `B`. Otherwise, the value of each missing property is zero. This works as expected. When there are three columns, the third (zero-based index 2) is used as the value of `C`. This also works as expected.

However, there are only two columns, `C` should be 0. Instead, the missing filed delegate triggers, causing an exception or other error handling behavior.

**Comment by JoshClose** [comment]
This is intentional. It's only optional when mapping names. The reason is, if index 3 is optional, what happens with index 4, 5, and 6? They are all shifted and those indexes aren't valid anymore.

**Comment by ishanpranav** [comment]
Got it, thank you! What do you recommend as a workaround if a column and all the succeeding columns should be optional? Currently, I have to set `MissingFieldFound` to `null` and use a custom converter that ignores null fields.

**Comment by JoshClose** [comment]
Easiest way is to read manually instead of using mapping or attributes. https://joshclose.github.io/CsvHelper/examples/reading/reading-by-hand/
