### ISSUE TITLE
Documentation site copy/paste disabled

### ISSUE THREAD

**Issue by marfarma** [JoshClose/CsvHelper#203]
It appears that on the documentation site, http://joshclose.github.io/CsvHelper/, copy paste is disabled on context menu, on the browser edit menu and for Ctrl-C, at least for  code blocks.  On cursory review, appears to be be related to this codemirror issue: https://github.com/marijnh/CodeMirror/issues/1764

**Comment by JoshClose** [comment]
Fixed.
