### ISSUE TITLE
Hiding CR and LF from the csv file

### ISSUE THREAD

**Issue by SachACC** [JoshClose/CsvHelper#2037]
**When I open the csv file in notepad I see the following characters . Is there a way to hide them or remove them ? I tried using `text.Replace("\r", "").Replace("\n", "")**` but it didn't work.
![image](https://user-images.githubusercontent.com/108472445/191183825-423b378f-0aea-43ff-b14f-c36bf974768b.png)

**Comment by JoshClose** [comment]
You need the new lines. They separate each CSV row.

What text editor are you using? Maybe you have the wrong encoding set, and it shouldn't show them like that. Or maybe you have a setting on to show them.

**Comment by agillgilla** [comment]
This is not a bug.  Josh is right, it's a setting that you've enabled in Notepad++.

To disable showing line endings in Notepad++, go to **View >> Show Symbol >> Show End of Line**.

Picture [here ](https://i.stack.imgur.com/JcmqN.jpg) if you need it.
