### ISSUE TITLE
Implement OWASP Best Practices for CSV Injection

### ISSUE THREAD

**Issue by samuel-knutson** [JoshClose/CsvHelper#2038]
**Is your feature request related to a problem? Please describe.**
This library implemented controls for CSV Injection vulnerabilities in 2017. Since then, OWASP has updated their recommendation. I propose this library be updated to reflect the latest recommendation from OWASP.

The current implementation prepends a tab character to any field value that starts with `=`, `+`, `-`, or `@`.

As of the writing of this issue, OWASP recommends:

> ensure that no cells begin with any of the following characters:
> - Equals to (=)
> - Plus (+)
> - Minus (-)
> - At (@)
> - Tab (0x09)
> - Carriage return (0x0D)

> Alternatively, apply the following sanitization to each field of the CSV, so that their content will be read as text by the spreadsheet editor:
> - Wrap each cell field in double quotes
> - Prepend each cell field with a single quote
> - Escape every double quote using an additional double quote

**Describe the solution you'd like**

_Possible Solution 1_

This is my preferred approach, but I recognize it is a breaking change.

Replace `CsvConfiguration.SanitizeForInjection (bool)` with `CsvConfiguration.InjectionSanitizationOption (enum)`. That enum would have three options: `RemoveUnsafeCharacters`, `SanitizeAllFields`, and `Disabled`. Based on your comment on #1586, the default would be `Disabled`.

Add Tab and Carriage Return to the default value for `CsvConfiguration.InjectionCharacters`.

Remove `CsvConfiguration.InjectionEscapeCharacter`. (Or alternatively, preserve this property and add a fourth enum option for `SanitizeUnsafeFields`.)

_Possible Solution 2_

This is my idea if you are averse to breaking changes.

To support the first recommendation, add a new property `CsvConfiguration.RemoveUnsafeCharacters (bool)`. Default to `false`. Throw exception if `RemoveUnsafeCharacters ` and `SanitizeForInjection` are both `true`.

To support the second recommendation, add a property `CsvConfiguration.FieldPrefix (string)`. This prefix gets prepended to every field. Default to null or empty string. Then we can use this prefix and set `ShouldQuote = _ => true` to implement the OWASP-recommended sanitization.

In both cases, we can use the existing `CsvConfiguration.InjectionCharacters` to configure the latest list of characters - no changes required to the library.

**Describe alternatives you've considered**
First, I tried configuring CsvHelper to satisfy the latest recommendations. I cannot figure out how to strip the insecure characters. I can get pretty close to the second recommendation from OWASP, but I can't figure out how to configure it exactly as written. The sticking point is I cannot figure out how to prepend a single quote to every field value. Here is one example where I got pretty close:

```
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                SanitizeForInjection = true,
                InjectionCharacters = new []{'=', '+', '-', '@', '\t', '\r'},
                InjectionEscapeCharacter = '\'',
                ShouldQuote = args =>
                {
                    // TODO can we access CsvConfiguration.InjectionCharacters here?
                    var injectionCharacters = new[] { '=', '+', '-', '@', '\t', '\r' };

                    var firstCharacter = args.Field.FirstOrDefault();
                    if (injectionCharacters.Contains(firstCharacter))
                    {
                        return true;
                    }

                    return ConfigurationFunctions.ShouldQuote(args);
                }
            };
```

Second, I considered implementing my own CSV library (or implementing my own controls on top of CsvHelper). I would prefer to leverage an existing library if possible. CsvHelper already claims to implement controls for CSV Injection, so I believe those controls should be maintained.

**Additional context**
- Original issue: #724
- OWASP Reference: https://owasp.org/www-community/attacks/CSV_Injection

**Comment by samuel-knutson** [comment]
I can probably pick up this issue if we can agree on some change.

**Comment by JoshClose** [comment]
Stripping the characters seems like a bad idea. These aren't Excel/Sheets files. People may open them in those things for viewing, but CSV isn't made for that. I would think the user would want to see the character there than it being removed.

**Comment by samuel-knutson** [comment]
My understanding is that web applications often generate reports in CSV format, and users typically open those reports in Excel/Sheets. I understand there are other use cases, but I think this one is pretty common.

I agree the library should not randomly start stripping characters. But what about making it configurable, with it being disabled by default? Then clients can opt in to the feature if they know these characters are not valid for their application.

**Comment by JoshClose** [comment]
Yeah, an enum would work.

```cs
enum
{
    Disabled = 0,
    Strip,
    Escape
}
```

**Comment by samuel-knutson** [comment]
Do you want me to post a PR that we can iterate on? Or would you rather sort out some implementation details here first?

**Comment by samuel-knutson** [comment]
The main question IMO is how to reconcile with the existing implementation. Ideally, I'd prefer to replace the original implementation to avoid confusion. But that is a breaking change. If you are averse to breaking changes, I can come up with an implementation that is backwards compatible. Ideally, it should have some guardrails to prevent devs from using inconsistent configuration. And maybe we mark the old features as Obsolete and tag them for removal in the next major release.

Sounds like you are OK with some change in principle and it's just a matter of implementation. If that's true, then let me know if you prefer to discuss here or iterate on a PR.

**Comment by JoshClose** [comment]
I'm looking into it. I'll have a branch for you to look at soon.

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/commit/639e0fb889a8b205b18b29baafd5d52de0403731

**Comment by JoshClose** [comment]
Let me know what you think.

**Comment by samuel-knutson** [comment]
I commented on the commit. Also I realized that OWASP does not specifically say to strip unsafe characters, but rather "ensure that no cells begin with any of the [unsafe] characters." So can you add a fourth option in the enum to throw an exception? If this is invalid data for your application, then I think a noisy exception might be preferable to silently sanitizing the data.

**Comment by JoshClose** [comment]
Updated based on your recommendations. https://github.com/JoshClose/CsvHelper/compare/injection

**Comment by samuel-knutson** [comment]
Looks good. Couple small suggestions/questions, nothing major.

1. The docs say "a `CsvWriter` exception is thrown" - maybe specify the exact Exception type?
2. All the tests use the `WriteField` method. I assume these changes also apply to the other methods like `WriteRecords`?
3. I think it would be valuable to test a value like `a=b` to make sure we don't process unsafe characters in the middle of a string. Ideally (1) quoted and unquoted (2) Strip / Escape / Exception (3) for each unsafe character.

**Comment by JoshClose** [comment]
1. The type is `CsvWriterException`. I'll have to update the docs.
2. Everything in the writer funnels through that single method.
3. I'll add these.

**Comment by JoshClose** [comment]
Updated.

**Comment by JoshClose** [comment]
Updated again.

**Comment by samuel-knutson** [comment]
Looks good to me! When can I expect a new release?

**Comment by JoshClose** [comment]
Since this is a breaking change, I'm going to see if there are any other small things I can add before pushing this out. If it's not out by Monday, comment here and I'll push.

**Comment by samuel-knutson** [comment]
Good morning! Just sending a reminder to push the new release. Thank you!

**Comment by JoshClose** [comment]
Thanks. Working on a delimiter detection change that is breaking also. Feel free to remind me again if you don't get an update in a day.

**Comment by samuel-knutson** [comment]
Update?

**Comment by samuel-knutson** [comment]
@JoshClose - any update? Hoping to get this soon if possible so I don't have to reinvent the wheel on my side. Thanks!

**Comment by JoshClose** [comment]
I've been going through pull requests and merging them. Trying to get as much low hanging fruit in. I'll release sometime today.

**Comment by JoshClose** [comment]
I'm on a roll here so it might be a while. I'll create a release right now. I need to update the documentation change log and migration doc for it, and then I'll push the release. Should be within the next hour. I'll let you know when it's pushed.

**Comment by JoshClose** [comment]
Pushed version 29.0.0 to NuGet.

**Comment by samuel-knutson** [comment]
Thank you!
