### ISSUE TITLE
GUID is being type casted into an uint16

### ISSUE THREAD

**Issue by adam-bentley** [JoshClose/CsvHelper#2040]
**Describe the bug**
I have a CSV containing just GUIDs that I need to convert into a class. When I convert the objects, I get a TypeConverterException with a member type Uint16.

I have converted other classes using GUID's just fine, but for some reason is wont covert this class.

![image](https://user-images.githubusercontent.com/57919023/193125112-399b31bb-6a0d-49c3-b948-46e7ac81e86f.png)
![image](https://user-images.githubusercontent.com/57919023/193125158-86f1d0bd-0720-456a-972d-d89051ac32ce.png)

```
public class CategoryInstance
    {
        /// <summary>
        /// Id of the instance
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// The position of the category when loaded,
        /// also used to sync categories with the racenet system
        /// </summary>
        public int Number { get; set; }

        /// <summary>
        /// Name of the sponsor
        /// </summary>
        public string? Sponsor { get; set; }
}
```

`List<CategoryInstance> categoryInstances = CSVReader.ReadObjects<CategoryInstance>($"{baseFilePath}CategoryInstances.csv");`

```
public static List<T> ReadObjects<T>(string filepath)
        {
            using StreamReader reader = new(filepath);
            using CsvReader csv = new(reader, new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HeaderValidated = null,
                MissingFieldFound = null,
                //BadDataFound = null
            });
            return csv.GetRecords<T>().ToList();
        }

```
Any help would be appreciated.

**Comment by JoshClose** [comment]
Can you create a small failing example the demonstrates this?

**Comment by adam-bentley** [comment]
When i run a local using the NuGet package I get the same error, if I copy across the classes I get a different error.

**Comment by JoshClose** [comment]
I can't reproduce it and need an example that does.

**Comment by adam-bentley** [comment]
I setup a map which fixes this issue.
