### ISSUE TITLE
Unable to Update Header Value in PrepareHeaderForMatch

### ISSUE THREAD

**Issue by AYColumbia** [JoshClose/CsvHelper#2042]
**Describe the bug**
I need to update field header values that have fields that end in "Id" to "ID" but it's not working.  The code is hit inside the function but does not affect the actual value.

Here's the code:
```
new CsvConfiguration(CultureInfo.InvariantCulture)
{
	HasHeaderRecord = true,
	PrepareHeaderForMatch = args =>
	{
		string header = args.Header;
		if (header.EndsWith("Id"))
		{
			header = Regex.Replace(header, "^(.*)Id$", "$1ID");
		}
		return header;
	}
};
```

**To Reproduce**
1. in an asp.net project, add CsvHelper v28.0.1
2. set up a file that has fields
3. use CsvHelper configuration object with PrepareHeaderForMatch and return updated header value
4. Use CsvReader and CsvDataReader to load data into a DataTable object
5. Check column names in data table

**Expected behavior**
Columns in DataTable after using Load of CsvDataReader object to match changed columns from PrepareHeaderForMatch.

**Screenshots**
N/A

**Additional context**
N/A

Please let me know if any additional info is needed.  Thank you.

**Comment by JoshClose** [comment]
You are mistaking what `PrepareHeaderForMatch` does. It's a way to match the header names with the property names. If the header is `First Name` and the property is `FirstName`, for them to match you'd want to remove spaces.

There is no way to change things like that by default. I would suggest creating the `DataTable` with the headers you want and passing it into the `CsvDataReader` constructor.

**Comment by AYColumbia** [comment]
Hi Josh, yeah, I wound up working around it that way, i.e., after I populate the table with .Load

```
foreach (DataColumn dc in dataTable.Columns)
{
	if (dc.ColumnName.EndsWith("Id"))
	{
		dc.ColumnName = Regex.Replace(dc.ColumnName, "^(.*)Id$", "$1ID");
	}
}

```

Would love to see this as a feature though.  Thank you.
