### ISSUE TITLE
CsvParser - Unable to set delimiter or Quote

### ISSUE THREAD

**Issue by PattonK** [JoshClose/CsvHelper#2043]
**Describe the bug**
I am able to set the delimiter and quote values using CsvConfiguration, however, it does not appear that they are used when CsvParser is used.  Not sure what I am missing unless there is a separate configuration for CsvParser. 
```cs
var csvParser = new CsvParser(textReader, System.Globalization.CultureInfo.InvariantCulture);
var csvconfig = new CsvConfiguration(System.Globalization.CultureInfo.InvariantCulture);
csvconfig.Delimiter = Convert.ToString(GlobalVar.CharS);                               
csvconfig.Quote = GlobalVar.CharQ;
string MyDelimiter = csvconfig.Delimiter;
char MyQuote = csvconfig.Quote;
string ParserDelimiter = csvParser.Configuration.Delimiter;
char ParserQuote = csvParser.Configuration.Quote;
```

**Comment by JoshClose** [comment]
You're not assigning the configuration to the parser. You'll need to pass it into the constructor for it to be used. All the variables the parser uses are set locally in the constructor.
