### ISSUE TITLE
Investigate usage of ref / in / ref struct / AggressiveInlinings in the codebase

### ISSUE THREAD

**Issue by Gnbrkm41** [JoshClose/CsvHelper#2047]
**Describe the bug**
I'm seeing random `ref` / `in`  / `ref struct` keywords and `MethodImplOptions.AggressiveInlining` in the codebase where those are unnecessary. Additionally, some of these will cause the code to not compile in newer versions of C#.

For example, in this code: 
https://github.com/JoshClose/CsvHelper/blob/52ce5d64c52e3b480662fb89d673387c2d8a8feb/src/CsvHelper/CsvParser.cs#L1110-L1139

`ProcessedField` does not contain any `ref struct`s such as `Span<T>` or `ref` field (new in C# 11), however it is made a `ref struct` (which is unnecessary)

https://github.com/JoshClose/CsvHelper/blob/52ce5d64c52e3b480662fb89d673387c2d8a8feb/src/CsvHelper/CsvParser.cs#L1013

There is no need for `int`s to be passed in as `in` (as those are small primitive types that can be passed as value through registers), however they are.

https://github.com/JoshClose/CsvHelper/blob/52ce5d64c52e3b480662fb89d673387c2d8a8feb/src/CsvHelper/CsvParser.cs#L814-L830

Those two facts, [combined with a breaking change in C# 11, ](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/breaking-changes/compiler%20breaking%20changes%20-%20dotnet%207#method-ref-struct-return-escape-analysis-depends-on-ref-escape-of-ref-arguments) means the code will not compile in C# 11.

![image](https://user-images.githubusercontent.com/42944058/194236744-ce58038d-191f-41f6-8487-53865476e582.png)

The solution here would be to remove `ref` and `in`s from the code. Those aren't necessary in the first place.

Furthermore, there are lots of methods that are marked as `AggressiveInlining` for no apparent reason:
![image](https://user-images.githubusercontent.com/42944058/194242898-a264fa8e-6f60-42f3-b8a0-a4a3e32624e9.png)

And some of those appear to be quite complex:
![image](https://user-images.githubusercontent.com/42944058/194243242-bba0dc55-6dac-4cae-8e62-cdb408dbe010.png)

Unless methods contain small and simple logics that are run often in a hot path, such liberal use of `AggressiveInlining`s may result in suboptimal code generation, as this will result in size bloating of the jitted method, increasing memory consumption. Additionally, the Just-In-Time compiler has limited resources when it comes to generating optimised code; If too much locals exist within a function (possibly due to forced inlining) JIT gives up tracking the rest of the locals, meaning no optimizations are performed on those, most importantly register allocation.

Generally it is advised to not place AggressiveInlining on functions unless you have good reasons (i.e. benchmarks) justifying use of such attributes. JIT does perform inlining on its own based on heuristics as well, so it's not like you won't have functions inlined unless you mark it explicitly.

**Comment by JoshClose** [comment]
I just removed all of the `AgressiveInlining` and there wasn't much of a difference. What about using `AggressiveOptimization` on a hot path?

These seem to be the hotpath methods, and it works well on them.
- `ReadDelimiter`
- `ReadLineEnding`/`ReadNewLine` One or the other is used depending on a config value.
- `AddField`
- `FillBuffer`/`FillBufferAsync`

**Comment by JoshClose** [comment]
I removed all of them. I'll let the compiler figure it out.

**Comment by JoshClose** [comment]
I removed all the `in` from the params and the `ref` from the struct. I believe that struct did contain a `Span` at one, but it was removed.
