### ISSUE TITLE
Documentation would be more helpful if it mentioned what textReader is/does

### ISSUE THREAD

**Issue by muzzamo** [JoshClose/CsvHelper#206]
In the documentation at http://joshclose.github.io/CsvHelper/ , you have the following two lines: 

var csv = new CsvReader ( textReader );
var records = new CsvReader<MyClass>();

In terms of the documentation being a quickstart guide, it would be helpful if you included the line for the creation of textReader or described more obviously what it does.

**Comment by MattNewbill** [comment]
Just throwing out I didn't know what textReader was either in the quick start. Had to google what it was and it landed me here. Makes the quick start less useful, nothing more frustrating than the easiest thing being difficult.

**Comment by JoshClose** [comment]
I'm probably going to have `textReader` link out to the docs. https://msdn.microsoft.com/en-us/library/system.io.textreader(v=vs.110).aspx
