### ISSUE TITLE
ValidateHeader - At runtime getting "This Operation is only valid on generic types.

### ISSUE THREAD

**Issue by Dovernh** [JoshClose/CsvHelper#2069]
**Describe the bug**
At runtime getting "This Operation is only valid on generic types.

**To Reproduce**
```
            using var ms = new MemoryStream(file.Data);
            using var reader = new StreamReader(ms);
            using var csv = new CsvReader(reader, config);

            csv.Context.TypeConverterOptionsCache.GetOptions<string>().NullValues.Add("NULL");
            csv.Context.TypeConverterOptionsCache.GetOptions<int?>().NullValues.Add("NULL");
            csv.Context.RegisterClassMap(csvClassMapType);

            csv.Read();
            csv.ReadHeader();
            **csv.ValidateHeader<ClientModelImportClassMap>();**

            result = csv.GetRecords<ClientModelImportCsv>().ToList();

public class ClientModelImportClassMap : ClassMap<ClientModelImportCsv>
{
    public ClientModelImportClassMap()
    {
        Map(m => m.PhysicalName).Name("COLUMN_NAME", "COLUMNNAME", "COLUMNPHYSICALNAME");
        Map(m => m.TableName).Name("TABLE_NAME", "TABLENAME", "TABLEPHYSICALNAME");
        Map(m => m.ColumnOrderInTable).Name("ORDINAL_POSITION", "ORDINALPOSITION", "COLUMNORDERINTABLE").Default(0);
        Map(m => m.IsNullable).Name("IS_NULLABLE", "ISNULLABLE").Default("YES");
        Map(m => m.ColumnDataType).Name("DATA_TYPE", "DATATYPE").Default(null);
        Map(m => m.Size).Name("CHARACTER_MAX_LENGTH", "CHARACTER_MAXIMUM_LENGTH", "CHARACTERMAXIMUMLENGTH", "CHARACTERMAXLENGTH", "SIZE");
        Map(m => m.Precision).Name("NUMERIC_PRECISION", "NUMERICPRECISION", "PRECISION");
        Map(m => m.Scale).Name("NUMERIC_SCALE", "NUMERICSCALE", "SCALE");
    }
}
```

**Expected behavior**
Code works in 27.2.1, doesn't work in 29.0.0 or 30.0.0. We thought it was b/c of this noted breaking change. 
Fixed constructor mapping issue where parameter has a type converter but would still try and use constructor mapping.

**Screenshots**
![image](https://user-images.githubusercontent.com/1800249/200430233-283b3992-f160-4828-891c-03ff2c302f32.png)

**Additional context**
We would like to use the more modern version of the code. Just hoping we could make a small adjustment to our code and it would work.

**Comment by scott7106** [comment]
We are unable to update to the latest releases due to this issue. Could we get an response on the proposed [PR](https://github.com/JoshClose/CsvHelper/pull/2086) to address this?

**Comment by sybaris** [comment]
Hi,

I think it's the same issue, but not sure, so I post here my unit test that reproduce the same error "System.InvalidOperationException: This operation is only valid on generic types."

`      public class ListOfString : List<string> { }

        public class MyClass
        {
            public Guid Id { get; set; }
            public string Description { get; set; } 
            public ListOfString Attributes { get; set; }
        }

        private class MyClassMap : ClassMap<MyClass>
        {
            public MyClassMap()
            {
                AutoMap(CultureInfo.InvariantCulture);
            }
        }

        //System.InvalidOperationException: This operation is only valid on generic types.
        [TestMethod]
        public async Task TestIssue()
        {
            const string UT_DATA = @"id;Description
99356344-32de-4b36-8aae-038c36e65ea3;myDescription";
            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                Delimiter = ";",
                HasHeaderRecord = true,
            };

            using (var reader = new StringReader(UT_DATA))
            using (var csv = new CsvReader(reader, config))
            {
                csv.Context.RegisterClassMap<MyClassMap>();
                var records = csv.GetRecords<MyClass>(); // This line throw the exception
            }
        }`

Regards
Sybaris

**Comment by sybaris** [comment]
Hi

Thanks. 
Test is ok in 30.1.0 version.

Regards
Sybaris
