### ISSUE TITLE
RegisterMap throws Error

### ISSUE THREAD

**Issue by sathenoseki** [JoshClose/CsvHelper#2071]
While trying to Call RegisterMap I get the following error.
```
System.InvalidOperationException: This operation is only valid on generic types.
   at System.RuntimeType.GetGenericTypeDefinition()
   at CsvHelper.TypeConversion.CollectionConverterFactory.Create(Type type, TypeConverterCache cache, ITypeConverter& typeConverter)
   at CsvHelper.TypeConversion.TypeConverterCache.GetConverter(Type type)
   at CsvHelper.Configuration.ClassMapCollection.SetMapDefaults(ClassMap map)
   at CsvHelper.Configuration.ClassMapCollection.Add(ClassMap map)
   at CsvHelper.CsvContext.RegisterClassMap(ClassMap map)
   at CsvHelper.CsvContext.RegisterClassMap[TMap]()
```

The Class I am trying to add is something like this.

```cs
public class Incoming
    {
        public DateTime Date { get; set; }
        public JObject CsvDataDump { get; set; }
    }

public static class CsvHelperExtensions
	{
		public static MemberMap<T, JObject> MapRowToJObject<T>(this MemberMap<T, JObject> _memberMap, 
                       ICollection<(string header, int index)> headers) =>
			_memberMap.Convert(r =>
			{
				var jobject = new JObject();
				foreach (var (header, index) in headers)
				{
					jobject[header] = r.Row.GetField(index);
				}
				return jobject;
			});
	}

 public static class CsvDataDumpHelper
    {
        public static readonly (string header, int index)[] CsvHeaders = new[]
        {
            (header: "Date", index: 0),
        };
    }

private class NonGenericTestClassMap : ClassMap<Incoming>
		{
			public NonGenericTestClassMap()
			{
				Map(m => m.Date);
				Map(m => m.JObject).MapRowToJObject(CsvDataDumpHelper.CsvHeaders);
			}
		}
```

Looking at the code it seems in the CollectionConverterFactory.cs file line 120-121
the code checks if the type is a generic type and then calls type.GetGenericTypeDefinition()
the issue is GetGenericTypeDefinition will blow up if the type is not generic but there is no check that 
the type is generic. (On line 120 the code checks if the type is generic but still calls GetGenericTypeDefinition() without using the result of the check)

**Comment by JoshClose** [comment]
The issue here is you're mapping `JObject` and don't have a `TypeConverter` for it. `JObject` implements `IEnumerable` so the `CollectionConverterFactory` wrongly thinks it can convert that type.

I'm looking into what can be done here. If you supply a `Convert` function, a `TypeConverter` is used so it shouldn't be looking for one anyways.

**Comment by JoshClose** [comment]
This is the offending code. https://github.com/JoshClose/CsvHelper/blob/d25c426886e8fb1fe317e6e49858ce02cad77db1/src/CsvHelper/Configuration/ClassMapCollection.cs#L165

If I change this to check if there are any converts too, it works fine.

**Comment by JoshClose** [comment]
This is fixed and will be in the next release.
