### ISSUE TITLE
New class level attributes are ignored, e.g. DelimiterAttribute

### ISSUE THREAD

**Issue by dnh-developer** [JoshClose/CsvHelper#2076]
I have been experimenting with the new class level attributes for things like Delimiter, HasHeaderRecord, IgnoreBlankLines, etc. which were introduced in version 30.0.0. However, they don't appear to be working and they are ignored.
```c#
[Delimiter("|")]
[HasHeaderRecord(false)]
[IgnoreBlankLines(true)]
[TrimOptions(TrimOptions.Trim)]
public class Result
{
    [Index(0)]
    public string Type { get; set; }
    [Index(1)]
    public string Name { get; set; }
    [Index(3)]
    public string Ccy { get; set; }
}

//This works with settings in config file
var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
    Delimiter = ",",
    HasHeaderRecord = false,
    IgnoreBlankLines = true,
    TrimOptions = TrimOptions.Trim,
};

using (var reader = new StreamReader(file))
using (var csv = new CsvReader(reader, config))
{
    results.AddRange(csv.GetRecords<Result>());
}

//This does not work with settings as class level attributes on Result class
using (var reader = new StreamReader(file))
using (var csv = new CsvReader(reader, CultureInfo.InvariantCulture))
{
    results.AddRange(csv.GetRecords<Result>());
}
```

**Comment by JoshClose** [comment]
You need to either pass the `Type` into the constructor or call `ApplyAttributes`.

```cs
new CsvConfiguration(CultureInfo.InvariantCulture, typeof(Result));
// or
new CsvConfiguration(CultureInfo.InvariantCulture).ApplyAttributes<Result>();
// or
new CsvConfiguration(CultureInfo.InvariantCulture).ApplyAttributes(typeof(Result));
```

Maybe it could be called automatically when passed into the `CsvReader` or `CsvWriter` constructor.

**Comment by dnh-developer** [comment]
Great that works, thanks...

**Comment by TdSch** [comment]
I ran in the same issue. Maybe [this page](https://joshclose.github.io/CsvHelper/examples/configuration/attributes/) needs to be amended to add the configuration block ?

**Comment by JoshClose** [comment]
Yes. I'll reopen this and change to documentation.

**Comment by Georginfanger** [comment]
Hello, I had the intetion, that if i have a List ob dynamic Records I could define a Delimiter for eacht Type by itself with the Attribut. Is my intetion wrong, since i only can apply one Type to the Configuration. 
Would be nice if it was possible to have a delmiter for each Recordtype.

**Comment by AltruCoder** [comment]
@Georginfanger  can you provide an example of what you are trying to do?

**Comment by Georginf** [comment]
Sorry to be on another Account.
Lets say i have two Recordtypes:

`[Delimiter("|")]
	public class IntItem
	{}`

`[Delimiter(" ")]
	public class SnaItem
	{`
And those two have different Delimiters. It will not work with a dynamic List.

`var records = new List<dynamic>();
						records.Add(new IntItem();
						records.Add(new SnaItem());`

**Comment by FrankSzendzielarz** [comment]
> ```cs
> new CsvConfiguration(CultureInfo.InvariantCulture).ApplyAttributes(typeof(Result));
> ```

This took me forever to find. Definitely feels that it would be more intuitive if the attributes were just used if they were there. I'd say they should override whatever config is specified for the reader.

**Comment by RespectMathias** [comment]
> > ```cs
> > new CsvConfiguration(CultureInfo.InvariantCulture).ApplyAttributes(typeof(Result));
> > ```
> 
> This took me forever to find. Definitely feels that it would be more intuitive if the attributes were just used if they were there. I'd say they should override whatever config is specified for the reader.

Agreed. Also, documentation still hasn't been updated.

**Comment by JoshClose** [comment]
You can now do

```cs
var config = CsvConfiguration.FromAttributes<Result>();
```

**Comment by JoshClose** [comment]
> documentation still hasn't been updated

PRs are welcome! The `CsvHelper.Website` project is what gets updated, not the `docs` folder.

**Comment by JoshClose** [comment]
Just updated it. https://joshclose.github.io/CsvHelper/examples/configuration/attributes/
