### ISSUE TITLE
CsvWriter.WriteRecords(IEnumerable records) ignores CsvConfiguration.HasHeaderRecords

### ISSUE THREAD

**Issue by Oblomoff** [JoshClose/CsvHelper#2092]
CsvWriter.WriteRecords(IEnumerable records) ignores CsvConfiguration.HasHeaderRecords = false.

```C#
internal class CsvWriterTests
{
    record Record(int Value);

    [Test, Description("WriteRecords(IEnumerable records) ignores CsvConfiguration.HasHeaderRecords")]
    public void HasHeaderRecordsBug()
    {
        // Arrange
        var configuration =
            new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = false //!
            };
        using var stringWriter = new StringWriter();
        using var csvWriter = new CsvWriter(stringWriter, configuration);
        // IEnumerable<object> records = new[] { new Record(42) }; // This is OK
        IEnumerable records = new[] { new Record(42) }; // This results in а header being written

        // Act
        csvWriter.WriteRecords(records);
        var csv = stringWriter.ToString();

        // Assert
        Assert.That(csv, Is.EqualTo("42" + Environment.NewLine));
        // Expected string length 4 but was 11. Strings differ at index 0.
        // Expected: "42\r\n"
        // But was:  "Value\r\n42\r\n"
    }
}
```

**Expected behavior**
CSV header must not be written when CsvConfiguration.HasHeaderRecords is set to false.

**Comment by ngndevelopment** [comment]
I am also seeing this : note I have a workaround in the comment block for anyone else who may run into this before it's fixed.
`public string write(IEnumerable records)
        {
            string ret;

            // Write to a file.
            var config = new CsvHelper.Configuration.CsvConfiguration(System.Globalization.CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = true,
            };
            using (var writer = new StringWriter())
            using (var csv = new CsvWriter(writer, config))
            {
                csv.WriteRecords(records)
                
                /* Workaround 
                foreach(var record in records)
                {
                    csv.WriteRecord(record);
                    csv.NextRecord();
                }
                */
                ret = writer.ToString();
            }

            return ret;
        }`

**Comment by DaveInCaz** [comment]
What release was this incorporated into? Thanks
