### ISSUE TITLE
ExecutionEngineException: Attempting to call method 'CsvHelper.Configuration.MemberMap` but no AOT code generated

### ISSUE THREAD

**Issue by estellise-yukihime** [JoshClose/CsvHelper#2095]
Hi,

The Plugin works fine on Editor, but causes an ExecutionEngineException about no MemberMap AOT Code Generated on Android and iOS.

Unity Version
- 2021.3.14f1

CsvHelper Version
- 30.0.0

Error Code
```
ExecutionEngineException: Attempting to call method 'CsvHelper.Configuration.MemberMap`2[[SQLite.Model.Content, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]::.ctor' for which no ahead of time (AOT) code was generated.
```
<br/>
<br/>
Thank you.

**Comment by JoshClose** [comment]
You can't use things like reflection on iOS and apparently Android too. You can't use maps or `GetRecords`/`WriteRecords`. You need to stick to `GetField` and `WriteField` and manually create your objects.

**Comment by estellise-yukihime** [comment]
@JoshClose I see, thank you. 👍🏼

**Comment by JoshClose** [comment]
I recently looked into creating a source generator which would solve your problem. This is a massive undertaking though, so it won't be soon.

**Comment by bashen1291** [comment]
Just a reminder. For unity usage right now, there is a way to fix this with a little extra work.
Make a [Preserve] method, can be in a monobehiavour or static or what every you want, just make sure it compile when build.
Add all you used MemberMap<T,S> combination into it. So the il2cpp will generate MemberMap code when build.
```
 public static void UsedOnlyForAOTCodeGeneration()
 {
  new MemberMap<CSVData, bool>(null);
  //XXX all combinations
 }
```
And to know what combination you need, its you "recordType" combine any field type in it. As i use source code, i simple log it from source.
