### ISSUE TITLE
Can't Read Special Characters

### ISSUE THREAD

**Issue by ExCx** [JoshClose/CsvHelper#213]
I'm working on a Turkish CSV file here. So there are special letters like ç, ş, ğ, ü...

But CsvReader can't read them properly and show those chars as a "?" symbol.

I tried to configure it as:

```
using(var reader = new CsvReader(new StreamReader(rootDirS + "/Stok.csv", Encoding.UTF8))) {
    reader.Configuration.Encoding = Encoding.UTF8;
    reader.Configuration.CountBytes = true;
    reader.Configuration.CultureInfo = new CultureInfo("tr-TR");
}
```

But it just doesn't work. How can I achieve this?

**Comment by panigo** [comment]
Help me please!!! Do not read or write files. Thank you. pankratowgp@gmail.com
https://yadi.sk/i/bnIMo_Ww3RdY8p
https://yadi.sk/i/nvfGc7oU3RdYAN

**Comment by Rajasivaranjan** [comment]
Try using Open command as below. It worked for me.
df = pd.read_csv(open(filename, 'r'))
