### ISSUE TITLE
.NET 4.6.2 is not properly supported

### ISSUE THREAD

**Issue by ManelBH** [JoshClose/CsvHelper#2173]
**Describe the bug**
When trying to compile the project I notice it fails because of the .NET 4.6.2 target.
This does not compile:

`<TargetFrameworks>net6.0;netstandard2.1;netstandard2.0;net47;net462</TargetFrameworks>
`

This does:

`<TargetFrameworks>net6.0;netstandard2.1;netstandard2.0;net47</TargetFrameworks>
`

I notice this is one of the last changes, replacing net45 with net462 in the targetted frameworks, but the project and the compilation rules weren't updated accordingly and they are still referencing 4.5:

![image](https://github.com/JoshClose/CsvHelper/assets/48496885/afea8b14-ded1-4b9d-8f89-111b4985e52e)

Is there an intention to maintain support for 4.6.2? Maybe this target should just be removed.

**Comment by TrevorMcCubbin** [comment]
Is addressed in #2113. It is currently approved and waiting to be merged.

**Comment by JoshClose** [comment]
Should be fixed.
