### ISSUE TITLE
Misleading name of Configuration.IgnorePrivateAccessor

### ISSUE THREAD

**Issue by dobrou** [JoshClose/CsvHelper#218]
CsvReader option "IgnorePrivateAccessor" works, but in opposite way than it's name suggests.

With 'IgnorePrivateAccessor=False', private properties are ignored.
With 'IgnorePrivateAccessor=True', private properties are properly mapped and loaded with data.

----------------------
I think this option should have different name or following condition in CsvReader.CanRead should be changed and '!' should be removed.
bool cantRead = propertyMap.Data.Ignore || (propertyMap.Data.Property.GetSetMethod() == null && !this.configuration.IgnorePrivateAccessor) || propertyMap.Data.Property.GetSetMethod(true) == null;

**Comment by JoshClose** [comment]
I changed the name to `IncludePrivateProperties`. I think this is even more clear on intention.

This is in version 3.0
