### ISSUE TITLE
Inline Type Conversion example docs have wrong code.

### ISSUE THREAD

**Issue by HarryDavisgithub** [JoshClose/CsvHelper#2180]
Hi,
Found a little mistake in the docs. Trying to access GetField on the parameter not the row itself.
`        Map(m => m.Json).Convert(row => JsonConvert.DeserializeObject<Json>(row.GetField("Json")));
`

Should be something like:
`        Map(m => m.Json).Convert(o=> JsonConvert.DeserializeObject<Json>(o.Row.GetField("Json")));
`

https://joshclose.github.io/CsvHelper/examples/configuration/class-maps/inline-type-conversion/

Thanks!

**Comment by JustinAFaulkner** [comment]
I second this change, spent quite a while today trying to figure out why this wasn't working for me despite following the docs!

**Comment by JoshClose** [comment]
Fixed.
