### ISSUE TITLE
Access to the raw line

### ISSUE THREAD

**Issue by LiorBanai** [JoshClose/CsvHelper#2201]
I would like to have access to the raw parsed line in addition to the parsed fields.
This will help me sicne I also need the raw text for ech line to process separately.

**Comment by Rob-Hague** [comment]
You can use `csvReader.Parser.RawRecord`

**Comment by LiorBanai** [comment]
@Rob-Hague great. thanks!

btw can I replace the separator character?  in my csv I have | as separator and not ,

**Comment by Rob-Hague** [comment]
Yes you can do something like

```c#

var config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	Delimiter = "|"
};

using var csvReader = new CsvReader(textReader, config);
```

See https://joshclose.github.io/CsvHelper/ (or the unit tests in the repo) for more documentation/examples

**Comment by LiorBanai** [comment]
Great. Thank again!
