### ISSUE TITLE
Reading writing dynamic csv causes the first line to drop

### ISSUE THREAD

**Issue by lanchapman** [JoshClose/CsvHelper#2205]
When reading and writing a CSV file as a dynamic object, if headers are enabled, the first line after the header is dropped.
```cs
  using var readstream = new StreamReader("input.csv");
  using var writestream = new StringWriter();
  using var csvreader = new CsvReader(readstream, CultureInfo.InvariantCulture);
  using var csvwriter = new CsvWriter(writestream, CultureInfo.InvariantCulture);
  var records = csvreader.GetRecords<dynamic>();
  csvwriter.WriteRecords(records);
  File.WriteAllText("output.csv", writestream.ToString());
```
```
input.csv
t1,t2,t3
1,2,3
4,5,6
7,8,9
```
The files input.csv and output.csv should be the same.

The output.csv shows
```
t1,t2,t3
4,5,6
7,8,9
```

**Comment by AltruCoder** [comment]
This is an issue with how `CsvReader.GetRecords<T>()` works. https://joshclose.github.io/CsvHelper/getting-started/
> The `GetRecords<T>` method will return an `IEnumerable<T>` that will `yield` records.

If you take a look at the internal `private bool WriteHeader<T>(IEnumerable<T> records)`, you will see that if it knows the class, it can `WriteHeader(recordType)`.  If, however, it isn't a standard class, it must read the first record with `WriteHeader(records.FirstOrDefault())`.  That `FirstOrDefault()`, unfortunately calls the first yielded result from `CsvReader` and there is no way to go back to the beginning of the `IEnumerable<dynamic>`.  
```csharp
private bool WriteHeader<T>(IEnumerable<T> records)
{
	if (!hasHeaderRecord || hasHeaderBeenWritten)
	{
		return false;
	}

	var recordType = typeof(T);
	var isPrimitive = recordType.GetTypeInfo().IsPrimitive;
	if (!isPrimitive && recordType != typeof(object))
	{
		WriteHeader(recordType);
		return hasHeaderBeenWritten;
	}

	return WriteHeader(records.FirstOrDefault());
}
```
You can call `ToList()` on `csvreader.GetRecords<dynamic>()` and this will solve the issue.  Unfortunately, it means pulling the whole list into memory first before writing it.
```csharp
using (var readstream = new StringReader("t1,t2,t3\n1,2,3\n4,5,6\n7,8,9"))
using (var csvreader = new CsvReader(readstream, CultureInfo.InvariantCulture))
using (var csvwriter = new CsvWriter(Console.Out, CultureInfo.InvariantCulture))
{
	var records = csvreader.GetRecords<dynamic>().ToList();
	csvwriter.WriteRecords(records);
}
```
Unfortunately, I don't think there is a good way for @JoshClose to fix this issue without making major and likely unwelcome changes to how `CsvReader` works.

**Comment by jzabroski** [comment]
> Unfortunately, I don't think there is a good way for @JoshClose to fix this issue without making major and likely unwelcome changes to how `CsvReader` works.

I would throw an exception saying its an invalid CsvHelper configuration.

**Comment by JoshClose** [comment]
This is actually fixed now because of https://github.com/JoshClose/CsvHelper/issues/2247.

```cs
void Main()
{
	var s = """
		t1,t2,t3
		1,2,3
		4,5,6
		7,8,9
		""";
	using var readstream = new StringReader(s);
	using var writestream = new StringWriter();
	using var csvreader = new CsvReader(readstream, CultureInfo.InvariantCulture);
	using var csvwriter = new CsvWriter(writestream, CultureInfo.InvariantCulture);
	var records = csvreader.GetRecords<dynamic>();
	csvwriter.WriteRecords(records);
	writestream.Dump();
}
```
<img width="100" alt="image" src="https://github.com/JoshClose/CsvHelper/assets/114971/e51c43c7-69b1-4d32-a830-bcec6d208ebb">

> Unfortunately, I don't think there is a good way for @JoshClose to fix this issue without making major and likely unwelcome changes to how CsvReader works.

I had to use an IEnumerator from the IEnumerable instead. It's a bit strange in the code, but actually cleaned up some things.
