### ISSUE TITLE
Unable to set datetime  format for reading csv data

### ISSUE THREAD

**Issue by rupesh-kachhi** [JoshClose/CsvHelper#2207]
Problem-
I am trying to read this type of data from CSV-
**DATE,grain
1/1/1992,grain
2/1/1992,grain**
here date is in the format **dd/MM/yyyy**.

here is the necessary code -
//To read

 **var records = csv.GetRecords<CsvRecord>().ToList();**

//to write

 **csvOutput.Context.RegisterClassMap<CsvRecordMap>();**
 // Write the header record.
 **csvOutput.WriteHeader<CsvRecord>();**
 **csvOutput.NextRecord();**
 // Write the updated data records.
 **csvOutput.WriteRecords(records);**

// Classes used 
 **public class CsvRecord
{
    public string Grain { get; set; }
    [Name("DATE")]
    public DateTime Date { get; set; }
}
 public class CsvRecordMap : ClassMap<CsvRecord>
 {
     public CsvRecordMap()
     {
         Map(m => m.Grain);
         **Map(m => m.Date).TypeConverterOption.Format("yyyy/MM/dd");**
     }
 }**

After execution everything is working fine
after **writecsv**, I am getting  date format as "**yyyy/dd/MM**" 

if we add one record like this
**13/1/1992,grain**
it will give error taking default format as **MM/dd/yyyy**

**Comment by AltruCoder** [comment]
If you are using `CultureInfo.InvariantCulture`, the default date format is `MM/dd/yyyy`.  (Which I think is silly, since the majority of countries have `dd/MM/yyyy` as their default).  

So you need to either use a `CultureInfo` that uses `dd/MM/yyyy` for your `CsvReader`
```csharp
using (var csv = new CsvReader(reader, new CultureInfo("en-IN")))
```

Or use another `ClassMap<CsvRecord>` for your `CsvReader` that sets the correct format.
```csharp
Map(m => m.Date).TypeConverterOption.Format("dd/MM/yyyy");
```

**Comment by AltruCoder** [comment]
I just remembered.  There is another way to do it.
```csharp
var options = new TypeConverterOptions { Formats = new[] { "dd/MM/yyyy", "d/M/yyyy" } };
csvReader.Context.TypeConverterOptionsCache.AddOptions<DateTime>(options);
```
