### ISSUE TITLE
New compatibility issue regression due to `System.Linq.Async` inclusion

### ISSUE THREAD

**Issue by mrtristan** [JoshClose/CsvHelper#2228]
Ironically, this compatibility improvement commit caused a regression in compatibility.

https://github.com/JoshClose/CsvHelper/commit/0c59831e69e8bd03a1d6d19246c5fc370aa5d944#diff-6083c99d8c47f7f689694c8c9fd0b00043da05ddc12c010efc96fb1898f0f6fbR53

Adding a dependency on `System.Linq.Async` causes all sorts of conflicts in EF land and the use of DbSets. Just updating CSVHelper from  `30.0.1` to `30.1.0` caused thousands of errors in my projects in unrelated areas due to `System.Linq.Async` coming in transitively and yielding duplicative extension methods to what's present in EF core.

For history on this, check out the dumpster fire of a thread here:
https://github.com/dotnet/efcore/issues/18124

more context here: https://github.com/dotnet/reactive/issues/1057
etc: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/pull/203

**Comment by JoshClose** [comment]
There was only a single method call that was using that, so I changed it. I can remove the package reference to System.Linq.Async for everything.

**Comment by JoshClose** [comment]
I have issues with Microsoft.Bcl.AsyncInterfaces now. Might not be as easy as just removing it.

**Comment by JoshClose** [comment]
Try version 31.0.2.
