### ISSUE TITLE
Header does not contain Quote, but some fields in row contain Quote, how should I read this kind of CSV

### ISSUE THREAD

**Issue by Zero-Xiong** [JoshClose/CsvHelper#2250]
really need help here, as I tried both Mode = RFC4180 & Mode = Escape

The CSV file content is like below (example):

=======================================================

Header1,Header2,Header3,IntHeader,DecimalHeader,DateTimeHeader
content1,"content , (i have comma inside) 2","content3",100,100.00,"04/23/2024"
content2,"content ,,, (many comma inside)","content2",200,200.00,"05/01/2024"

=======================================================

The problem is header without double quote, field1 does not contain double quote, but field2 contain both double quote and comma inside.

How do we read such CSV file?

**Comment by JoshClose** [comment]
Seems to work fine for me with defaults.

```cs
void Main()
{
	var s =
		"""
		Header1,Header2,Header3,IntHeader,DecimalHeader,DateTimeHeader
		content1,"content , (i have comma inside) 2","content3",100,100.00,"04/23/2024"
		content2,"content ,,, (many comma inside)","content2",200,200.00,"05/01/2024"
		""";
	var config = new CsvConfiguration(CultureInfo.InvariantCulture)
	{
	};
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader, config))
	{
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public string Header1 { get; set; }
	public string Header2 { get; set; }
	public string Header3 { get; set; }
	public int IntHeader { get; set; }
	public decimal DecimalHeader { get; set; }
	public DateTime DateTimeHeader { get; set; }
}
```
<img width="503" alt="image" src="https://github.com/JoshClose/CsvHelper/assets/114971/84da5ad3-4eda-4cb9-bada-b30de453d0eb">

**Comment by Zero-Xiong** [comment]
Sign.....  really sad! it's not working in my environment. 

FYI, my version is 31.0.3

**Comment by Zero-Xiong** [comment]
I guess maybe the Unicode character inside the actual CSV file.  

like below:

 
![image](https://github.com/JoshClose/CsvHelper/assets/13866194/db3243cf-6c22-412b-8c6a-49177a221be0)

**Comment by JoshClose** [comment]
CsvHelper doesn't care about that. You set the encoding in your `TextReader`. It'll use whatever delimiter you have set up in the config.
