### ISSUE TITLE
FastDynamicObject ignores headers while used together with CsvWriter

### ISSUE THREAD

**Issue by lorceroth** [JoshClose/CsvHelper#2257]
**Describe the bug**
We use CsvHelper to add an additional column to existing CSV files with unknown schemas. To achieve that, we're reading them as `dynamic` records like this:

```csharp
foreach (var record in csvReader.GetRecords<dynamic>())
{
    record.EXTRA_FIELD = "Extra Value";
    csvWriter.WriteRecord(record);
    csvWriter.NextRecord();
}
```

This worked perfectly fine in version `27.1.1`, and the headers (including the new one) were written to the new file without any issues.

However, when we updated CsvHelper to version `32.0.3`, we noticed that the headers disappeared from the new file.

**To Reproduce**
Create a new Console Application targeting .NET 8 and paste the following in Program.cs:

```csharp
using CsvHelper;
using CsvHelper.Configuration;
using System.Globalization;

var csv = @"
ID,NAME,EMAIL
1,John,john@example.com
2,Jane,jane@example.com
";

using var reader = new StringReader(csv);
using var csvReader = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture));

using var writer = new StringWriter();
using var csvWriter = new CsvWriter(writer, new CsvConfiguration(CultureInfo.InvariantCulture));

foreach (var record in csvReader.GetRecords<dynamic>())
{
    record.EXTRA_FIELD = "Extra Value";
    csvWriter.WriteRecord(record);
    csvWriter.NextRecord();
}

Console.WriteLine($"CsvHelper {typeof(CsvReader).Assembly.GetName().Version}");
Console.WriteLine("---");
Console.WriteLine(writer.ToString());
Console.ReadKey(true);
```

## This works
Install CsvHelper `27.1.1` (the one we had before the update).
Run the program and you should get the following output:

```
CsvHelper 27.0.0.0
---
ID,NAME,EMAIL,EXTRA_FIELD
1,John,john@example.com,Extra Value
2,Jane,jane@example.com,Extra Value
```

## This doesn't work
Now, update CsvHelper to version `32.0.3` and run the program again. This time, the output should show the following:

```
CsvHelper 32.0.0.0
---
1,John,john@example.com,Extra Value
2,Jane,jane@example.com,Extra Value
```

**Expected behavior**
We're expecting the headers to be written to the new CSV file like it did when `ExpandoObject` was used in previous versions.

**Comment by JoshClose** [comment]
This happens with `ExpandoObject` and normal objects too.

`WriteRecord` doesn't write the header anymore; only `WriteRecords` does. If you're looping your records manually, you'll need to write the header yourself. In your case, call `WriteDynamicHeader(record)`.

```cs
void Main()
{
	var csv = """
		ID,NAME,EMAIL
		1,John,john@example.com
		2,Jane,jane@example.com
		""";
	using var reader = new StringReader(csv);
	using var csvReader = new CsvReader(reader, new CsvConfiguration(CultureInfo.InvariantCulture));

	using var writer = new StringWriter();
	using var csvWriter = new CsvWriter(writer, new CsvConfiguration(CultureInfo.InvariantCulture));

	var hasHeaderBeenWritten = false;
	foreach (var record in csvReader.GetRecords<dynamic>())
	{
		record.EXTRA_FIELD = "Extra Value";

		if (!hasHeaderBeenWritten)
		{
			csvWriter.WriteDynamicHeader(record);
			csvWriter.NextRecord();
			hasHeaderBeenWritten = true;
		}
		
		csvWriter.WriteRecord(record);
		csvWriter.NextRecord();
	}
	
	csvWriter.Flush();
	
	writer.Dump();
}
```
```
ID,NAME,EMAIL,EXTRA_FIELD
1,John,john@example.com,Extra Value
2,Jane,jane@example.com,Extra Value```
