### ISSUE TITLE
CSV Helper seems to ignore its Encoding configuration parameter

### ISSUE THREAD

**Issue by nkostis** [JoshClose/CsvHelper#2278]
CSV Helper seems to ignore the `Encoding` configuration parameter that it allows users to set within `CsvConfiguration`. Tested with versions 32.X and 33.X

**The problem**
Using the standard way to set encoding (as provided by CsvHelper itself):
```csharp
                CsvConfiguration config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    Encoding = Encoding.GetEncoding("iso-8859-7"),
                    //...others
                };

                var reader = new StreamReader(stream);

                var csv = new CsvReader(reader, config);
```
File is read as UTF-8, even though i request iso-8859-7 (old greek encoding). 

 _NOTE: I don't have control of the incoming encoding or i'd certainly use utf-8!_

**It works with system.text.encoding explicitly**
If i do this instead (i.e. the same thing but explicitly and before CsvHelper):
```csharp
                var bytes = await stream.ReadToEndAsync();
                var text_gr = Encoding.GetEncoding("iso-8859-7").GetString(bytes);
```
then the text_gr contains (expected) greek characters, instead of utf-8 symbols.

**My workaround**
i have worked around the whole issue with the following:
```csharp
                var bytes = await stream.ReadToEndAsync();
                var text_gr = Encoding.GetEncoding("iso-8859-7").GetString(bytes);

                CsvConfiguration config = new CsvConfiguration(CultureInfo.InvariantCulture)
                {
                    //..
                };

                var reader = new StringReader(text_gr);   //not stream anymore

                var csv = new CsvReader(reader, CsvConfig);
```
not ideal (i grab the whole stream into memory to use the system's encoding-aware read and then pass the full text as `StringReader`) but it works.

**Comment by JoshClose** [comment]
The `Encoding` config is only used for byte counting.

You need to set the encoding on the `TextReader` that you pass into `CsvReader`.

```cs
var reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-7"));
```

**Comment by AltruCoder** [comment]
I'm not sure what the purpose is for the encoding option on the `CsvConfiguration`.  `CsvReader` uses the encoding from the `TextReader` that is passed in the constructor.  You should be able to set the encoding when you create the `StreamReader`
```csharp
CsvConfiguration config = new CsvConfiguration(CultureInfo.InvariantCulture)
{
	//...others
};

var reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-7"));

var csv = new CsvReader(reader, config);
```

**Comment by nkostis** [comment]
thanks, i will test and close, hopefully this will stay and help others that may encounter the same issue
