### ISSUE TITLE
There should be a tag for v33.0.1 

### ISSUE THREAD

**Issue by alex50105** [JoshClose/CsvHelper#2285]
For clearing purposes we need the exact source code that was used for a version defined by either a tag or a GitHub release.
There is a tag for 33.0.0 but none for 33.0.1, so we can't use that version.
Can a tag on the correct commit be added for 33.0.1?

**Comment by JoshClose** [comment]
Oops. Done.

**Comment by alex50105** [comment]
Thanks very much!
