### ISSUE TITLE
Exception information stored in an object

### ISSUE THREAD

**Issue by joero4** [JoshClose/CsvHelper#229]
It would be so much more useful if the CsvHelper exception data that is returned in the Data["CsvHelper"] key be stored as an object with properties describing the error instead of a string object.  I want to manipulate what is returned to the user, and to do that I need to rip apart the string that's returned and rebuild with the information I want presented to the user.  This can be error prone process if the structure of the Exception string changes.  

Thank You,
Joe

**Comment by JoshClose** [comment]
This is done and will be in NuGet version 3.0.0-beta6.

I added these properties to the `CsvHelperException` base class.

```cs
/// <summary>
/// The current row number.
/// </summary>
public int Row { get; set; }

/// <summary>
/// The property type of the current field.
/// </summary>
public Type Type { get; set; }

/// <summary>
/// The index of the current field.
/// </summary>
public int FieldIndex { get; set; }

/// <summary>
/// The field name.
/// </summary>
public string FieldName { get; set; }

/// <summary>
/// The field value.
/// </summary>
public string FieldValue { get; set; }
```
If another exception type is thrown, it's caught and wrapped with a CsvHelperException.
