### ISSUE TITLE
header and column value mismatch occassionally

### ISSUE THREAD

**Issue by ypeng-ming** [JoshClose/CsvHelper#2290]
I have a class 
`public class AlarmrecordModel : ObservableObject
{
    public DateTime AlarmTime { get; set; }
    public string AlarmIdentification {get;set; }
    public string AlarmMessage { get; set; }
     public string OperatingMode { get; set; }
}`

and it works fine normally, but sometimes header and corresponding column header will be mismatched

this is how I save to csv

`public void FillData2FileAlarm<T>(List<T> models, string modelName)
{
    try
    {
        string directoryPath = PrepararerDirectory(modelName);
        int count = Directory.GetFiles(directoryPath).Length;

        string fillPath = string.Empty;
        float fileSize = 0f;
        if (count > 0)
        {
            fillPath = Path.Combine(directoryPath, $"{modelName}{count - 1}.csv");
            fileSize = (float)new FileInfo(fillPath).Length / 1024;//kb
            if (fileSize >= 10240)
            {
                fillPath = Path.Combine(directoryPath, $"{modelName}{count}.csv");
            }
        }
        else
        {
            fillPath = Path.Combine(directoryPath, $"{modelName}{count}.csv");
        }
        if (!File.Exists(fillPath))
        {
            File.Create(fillPath).Close();
        }
        bool writetheheader = false;

        StringBuilder stringBuilder = new StringBuilder();
        try
        {
            if (File.ReadAllLines(fillPath).Length == 0)
            {
                writetheheader = true;
            }
        }
        catch (IOException ex)
        {
            Log.WriteExceptionCatch("FillData2FileAlarm<T>", ex);
            return;
        }

        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = writetheheader,
        };

        using (var stream = File.Open(fillPath, FileMode.Append, FileAccess.Write))
        {
            using (StreamWriter sw = new StreamWriter(stream, Encoding.UTF8))//new System.Text.UTF8Encoding(true),
            {
                using (CsvWriter csv = new CsvWriter(sw, config))
                {
                    csv.WriteRecords(models);
                }
            }
        }

    }
    catch (Exception ex)
    {
        Log.WriteExceptionCatch("FillData2FileAlarm<T>", ex);
        return;
    }

}`

Normally it works like this:
![image](https://github.com/user-attachments/assets/a2c7c09d-1e3f-4bcc-95b1-fb4022016037)
But sometimes I got this:
![image](https://github.com/user-attachments/assets/2db69d5c-61eb-4c45-ad8c-d3b8c688fd17)
I'm using .net framework 4.6.1
csvhelper 33.0.1
do you have a clue about how may this happened? Thanks

**Comment by AltruCoder** [comment]
From the Getting Started page for CsvHelper https://joshclose.github.io/CsvHelper/getting-started/#writing-a-csv-file

> Remember how we can't rely on property order in .NET? If we are writing a class that has a header, it doesn't matter, as long as we are reading using the headers later. If we want to position the headers in the CSV file, we need to specify an index to guarantee it's order. It's recommended to always set an index when writing.

I'm assuming that the mismatch is happening when the file is written to a second time and the property order has changed.  To ensure a specific order you will need to add an index to your properties.

**Comment by ypeng-ming** [comment]
> From the Getting Started page for CsvHelper https://joshclose.github.io/CsvHelper/getting-started/#writing-a-csv-file
> 
> > Remember how we can't rely on property order in .NET? If we are writing a class that has a header, it doesn't matter, as long as we are reading using the headers later. If we want to position the headers in the CSV file, we need to specify an index to guarantee it's order. It's recommended to always set an index when writing.
> 
> I'm assuming that the mismatch is happening when the file is written to a second time and the property order has changed. To ensure a specific order you will need to add an index to your properties.

Thanks AltruCoder! I will try that
