### ISSUE TITLE
Character '#' in data stops WriteRecords

### ISSUE THREAD

**Issue by amararray** [JoshClose/CsvHelper#2296]
When using the WriteRecords function, it stops writing data after it hits a # character.
I am fetching data from a database and passing that into my WriteRecords, and then trying to save it as a .csv file.

**To Reproduce**
```cs
var dbData = "Test Data, # This is cut off";

var stream = new MemoryStream();
using (var writeFile = new StreamWriter(stream, leaveOpen: true))
{
    var csv = new CsvWriter(writeFile, CultureInfo.InvariantCulture);
    csv.WriteRecords(dbData );
}
stream.Position = 0;
return File(stream, "application/octet-stream", "dbData.csv");
```

This will write each letter to a new row in the csv file, but you will notice that when we hit the # character, no further data is printed. 

**Expected behavior**
Should keep writing my data and not abruptly stop.

**Comment by AltruCoder** [comment]
How about if you try,
```csharp
using (var writeFile = new StreamWriter(stream, leaveOpen: true))
using (var csv = new CsvWriter(writeFile, CultureInfo.InvariantCulture))
{	
	csv.WriteRecords(dbData);
}
```

**Comment by AltruCoder** [comment]
Also, I didn't try it with `File`, but I it prints out all of the letters for me with this.
```csharp
var dbData = "Test Data, # This is cut off";

var stream = new MemoryStream();
using (var writeFile = new StreamWriter(stream, leaveOpen: true))
{
	var csv = new CsvWriter(writeFile, CultureInfo.InvariantCulture);
	csv.WriteRecords(dbData);
}
stream.Position = 0;
var reader = new StreamReader(stream);
Console.Write(reader.ReadToEnd());
```

**Comment by amararray** [comment]
That is very interesting. I am still getting the same problem when trying to use File, but yes in the console all of it is coming. 
Seems to be an issue with File and not CsvHelper, I tried doing it manually without CSVHelper just writing to the stream and I am getting the same issue. 

Thank you AltruCoder! I will close this issue and try to figure out what File is doing :)
