### ISSUE TITLE
Configurable line ending for writing.

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#230]
Make a config option to set the line ending when writing. By default it will use `Environment.NewLine`.

**Comment by rkeethadath** [comment]
It would be great to have feature. I have a RRF file which ends as vertical bar+line feed (|LineFeed). So row delimiter would be vertical bar & Environment.Newline.

**Comment by JoshClose** [comment]
I'm working on speeding up the parser which is a complete re-write and restructuring of the parser. It should facilitate doing this easier.

**Comment by JoshClose** [comment]
You can set this on the `TextWriter` already. 

```cs
TextWriter.NewLine = "\n";
```

https://msdn.microsoft.com/en-us/library/system.io.textwriter.newline(v=vs.110).aspx

`CsvSerializer` calls `TextWriter.WriteLine()` to write the line ending, so if you change it in the `TextWriter`, you should be good.

Keep in mind, if it's anything besides `\r`, `\n`, or `\r\n`, `CsvReader` won't be able to read it.
