### ISSUE TITLE
IgnoreHeaderWhiteSpace bug

### ISSUE THREAD

**Issue by ronnieoverby** [JoshClose/CsvHelper#232]
When IgnoreHeaderWhiteSpace is set to true, you ought to ignore whitespace in the name mapping. For example:

Given this config:
```c#
var config = new CsvConfiguration
{
	IgnoreHeaderWhiteSpace = true,
	HasHeaderRecord = true,
	Delimiter = "|",
	IsHeaderCaseSensitive = false,
};
```

Given this heading:
`CARD NUMBER/SUFFIX`

And this mapping:
```c#
Map(x => x.CardNumber).Name("CARD NUMBER/SUFFIX");
```

One would not expect this:
`Fields 'CARD NUMBER/SUFFIX' do not exist in the CSV file.`

But that's exactly what happens.

I think this is because when comparison happens  you're removing whitespace on one side of the comparison but not the other.

**Comment by JoshClose** [comment]
This is fixed in version 3.0.
