### ISSUE TITLE
Create DataReader/DataTable examples

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#234]
People want to read from a table directly to csv without using any class in between and same for the other direction. Create examples on the doc site for this.

**Comment by JoshClose** [comment]
You can write header just like it's another row.

```cs
csv.WriteField( "Header 1" );
csv.WriteField( "Header 2" );
csv.NextRecord();
```

There is nothing special about it being a header.

**Comment by JoshClose** [comment]
I put some examples in the FAQ section. http://joshclose.github.io/CsvHelper/#misc-faq

**Comment by marcrocny** [comment]
That link no longer works. Where do these live now?

**Comment by JoshClose** [comment]
https://joshclose.github.io/CsvHelper/examples/data-table

There is a `CsvDataReader` now too.

**Comment by marcrocny** [comment]
Ah, I was looking for the other direction. Thought I had seen an example somewhere for `IDataReader` -> CSV, but now my google-fu is failling me.

**Comment by JoshClose** [comment]
This? https://joshclose.github.io/CsvHelper/old/1.x/#misc-faq
