### ISSUE TITLE
Mapper: Write a static string instead of getting it from property

### ISSUE THREAD

**Issue by mdmoura** [JoshClose/CsvHelper#240]
Hello,

I have the following Mapper to write a List<UserModel> to a CSV file:

```
public class UserModelCsvMapper : CsvClassMap<UserModel> {
  public override void CreateMap() {
    Map(x => x.Name).Name("Name");
    Map(x => x.Email).Name("Email"); 
  }
}
```

On the output (CSV file) I would like to have an extra column named Country.
The Country column would always have the value "UK" so I tried

```
    Map(x => "UK").Name("Country"); 
```

But I get an error ... Wouldn't be logic to be able to do this?

Thank You,
Miguel

**Comment by JamesItSolutionsLtd** [comment]
Did this get added?
