### ISSUE TITLE
Nested properties in header

### ISSUE THREAD

**Issue by malx122** [JoshClose/CsvHelper#244]
Hi!
Thanks for a great library.

I use it mainly for dumping dataclasses to be used in Matlab. The thing is that they usually using nested classes.
Ex::

```
public class XYZData
{
public int X;
public int Y;
public int Z;
}

public class SensorsData
{
public XYZData Gyro;
public XYZData Magnometer;
}
```

To serialize a list of SensorData in this example would give a file:

```
X,Y,Z,X,Y,Z
...
...
...
```

As you can see it quite difficult to see what kind of data I send when I send it to someone that doesnt have a clue about the C# classes.
What I expected was:

```
Gyro.X, Gyro.Y, Gyro.Z, Magnometer.X, Magnometer.Y, Magnometer.Z
```

I can't find any options about it. Is it implemented?

**Comment by AjaySewradj** [comment]
Hi, sorry to bump this issue, but my question is similar.

I'm trying to read from a csv file that has two header rows, where the first header row is a grouping.
In your example that would be:

```
Gyro,,,Magnometer,,
X,Y,Z,X,Y,Z
1,2,3,4,5,6
```

Is there a way to parse such a csv file?

**Comment by JoshClose** [comment]
Please create a new issue and reference this one. I don't look through closed issues at a later date and will probably miss this.
