### ISSUE TITLE
How to change the codepage used to read the file ?

### ISSUE THREAD

**Issue by stivoberlin** [JoshClose/CsvHelper#25]
CSVHelper works fine for me, but I trying to find the way to read correctly my ANSI files.

Thanks in advance for the tip..

**Comment by dotnetchris** [comment]
For future readers. I ended up here from the code:

```c#
var file = System.IO.File.OpenRead(path);
var csv = new CsvReader(new StreamReader(file));
```

I actually needed:

```c#
var csv = new CsvReader(new StreamReader(file, Encoding.Default));
```

If there's any code samples here that show overload usage without` Encoding.Default` overload maybe they should be updated.

**Comment by JoshClose** [comment]
The issue is completely outside of the library though. It's strictly dealing with the `Stream`. CsvHelper just get's a `TextReader` or `TextWriter` which might not even be attached to a stream. The consumer is giving it the means to read and write, and it doesn't care how it's done.
