### ISSUE TITLE
Add Line Number

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#254]
There currently is a Row number which is the logical row in the CSV file. Add a line number count which is the actual line the parser is on. i.e. The line if you were to open the file in a text editor.

**Comment by xrabohrok** [comment]
It would be nice if this number is referenced upon the throwing of exceptions, that way they can be fixed in very large .csv's.

**Comment by JoshClose** [comment]
`Exception.Data["CsvHelper"]` contains the extra information you're looking for.
