### ISSUE TITLE
Support for sep= on first line of file to define delimiter.

### ISSUE THREAD

**Issue by KevinHoward** [JoshClose/CsvHelper#257]
One feature that MS Excel supports for reading CSV files is the ability for the file to specify it's delimiter.  This is done by adding `sep=_` (_where _ is the delimiter_) to the first line of the file.  So for example, if the file's delimiter is a semicolon, it would have `sep=;` for the first line.

I would submit a pull request for this, however, I'm having a hard time determining how to implement it.  The main issue is that the CsvParser's reader is a TextReader, so there is no way to reset the reader back to the beginning. When a line is read, it's consumed and if the first line isn't a delimiter definition, I can't pass it's data off to the downstream logic to get the headers or fields without storing a copy of the line off and adding a bunch of extra conditions.

If the parser's reader was a StreamReader, then I could implement a Reset method once it's determined if the first line is a delimiter definition. However, this may have some impact on performance.

**Any advice or alternative methods would be greatly appreciated.**

Here is my Reset method if the reader is switched to a StreamReader:

``` csharp
/// <summary>
/// Resets the reader back to the beginning.
/// </summary>
public virtual void Reset()
{
    CheckDisposed();

    reader.BaseStream.Position = 0;
    reader.DiscardBufferedData();

    currentRow = 0;
    FieldCount = 0;
    CharPosition = 0;
    BytePosition = 0;
    RawRecord = null;
}
```

**Comment by henkmollema** [comment]
@JoshClose I noticed this feature (or rather Excel compatibility) was removed a while ago. What's the reasoning behind that? And is there a way to configure/infer the CSV delimiter apart from `Configruation.Delimiter`?

Thanks in advance.

**Comment by JoshClose** [comment]
It really has nothing to do with CSV. I'd like that stuff to not be a part of the normal library, and instead be in a contrib project of add on stuff. I have a contrib project setup, but no one has wanted to do the work.

**Comment by henkmollema** [comment]
That makes sense. Thanks!

**Comment by Kralizek** [comment]
@JoshClose is there a link to the contrib project?
