### ISSUE TITLE
Changing delimter does not remove default delimiter

### ISSUE THREAD

**Issue by richardsawyer** [JoshClose/CsvHelper#259]
I am reading tab-delimited text files. Set the delimiter to 'tab' and all is good until there is a comma in a number to read. CsvHelper appears to read the comma as a delimiter and then column mapping fails.
Of course, commas commonly appear in numbers so this is a regular problem.

**Comment by JoshClose** [comment]
Did you end up sending this? If so, I don't think I received it. If this is still and issue, send the test file my way, and post on here to make sure I got it. Thanks.

**Comment by IlincescuMihai** [comment]
Hi,

This is still a problem for me.
I changed the delimiter to be ;
csvWriter.Configuration.Delimiter = ";";

But I have a text: "Tidningar, facklitteratur" which has coma
csvWriter.WriteField(text);

and is putting the text "facklitteratur" in a separated column

**Comment by JoshClose** [comment]
Can you create a failing example for me? This works.

```cs
void Main()
{
	using (var writer = new StringWriter())
	using (var csv = new CsvWriter(writer))
	{
		csv.Configuration.Delimiter = ";";
		csv.WriteField("1");
		csv.WriteField("2a, 2b");
		csv.WriteField("3");
		csv.NextRecord();
		writer.ToString().Dump();
	}
}
```
Output:
```
1;2a, 2b;3
```

**Comment by djanjicek** [comment]
Yes, and when you open it in Excel, it's messed up

**Comment by JoshClose** [comment]
@djanjicek What is messed up?

**Comment by SimonCropp** [comment]
@JoshClose propose to close?
