### ISSUE TITLE
Question: Column ordering with a mixture of References and Map

### ISSUE THREAD

**Issue by GraemeF** [JoshClose/CsvHelper#265]
I'm using the following class to control writing: 

```
public class MyCsvMap : CsvClassMap<ContrivedExample>
{
    public MyCsvMap()
    {
        References<FirstCsvMap>(m => m.First);
        References<SecondCsvMap>(m => m.Second);
        Map(m => m.Third).Name("Third");
    }
}
```

I would expect the columns to be ordered as listed - so the columns from `FirstCsvMap`, then the columns from `SecondCsvMap`, and finally `Third`. But, `Third` is the first column in the output. Is there some way to control the column order in this case?

**Comment by vkumarcit** [comment]
How to write a logic for List. For example(SecondClass changed to List<SecondClass>)

 private class ThirdClass
    {
        public int Third { get; set; }

        public List<SecondClass> Second { get; set; }
