### ISSUE TITLE
WP8.1 Targeting (universal app)

### ISSUE THREAD

**Issue by jschneidereit** [JoshClose/CsvHelper#266]
I'm getting this error when I try to install CsvHelper from nuget - I'm wondering if there's anything I'm missing, but google-fu hasn't turned up much.

Could not install package 'CsvHelper 2.6.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by EliezerBee** [comment]
I believe I'm getting the same error:

System.IO.FileNotFoundException: Could not load file or assembly 'CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823' or one of its dependencies. The system cannot find the file specified.
File name: 'CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'
 
I tried removing the reference that NuGet inserted and inserting one manually as you suggested above but still get the same error. I've got Package Manager Console Host Version 2.8.60610.756.

Please advise. Thank you...

**Comment by JoshClose** [comment]
What type of project are you pulling it into?

**Comment by EliezerBee** [comment]
WinForms C#

**Comment by JoshClose** [comment]
Ugh... NuGet has an issue with not using a client profile of a higher version, and chooses a lower version of a full profile. It seems like every time they fix it, it breaks on the next release. I'm tempted to just make it a full version and forget the client profile. Or maybe separate the .NET 2.0 version into a different package.
