### ISSUE TITLE
csvHelper.Reader.Configuration.Delimiter doesn't set.

### ISSUE THREAD

**Issue by eaydemir** [JoshClose/CsvHelper#27]
i have csv file like :

column1;column2;column3
rec11;rec12;rec13
rec21;rec22;rec23
rec31;rec32;rec33

İ use csvHelper like that:

FileStream fs = new FileStream("fileName.csv", FileMode.Open);
CsvHelper.CsvHelper csv = new CsvHelper.CsvHelper(fs); 
csv.Reader.Configuration.Delimiter = ';'; csv.Configuration.Delimiter = ';';
List<entityRec> records = csv.Reader.GetRecords<entityRec>().ToList(); // Result: three record and all is empty. i look at debug mode csv.Reader.Parser.Configuration.Delimiter is ','  how i can this -delimiter- change. csv.Reader.Parser is non-public.

entityRec is :

```
public class entityRec
{
    [CsvField(Name = "column1")]
    public string col1 { get; set; }

    [CsvField(Name = "column2")]
    public string col2 { get; set; }

    [CsvField(Name = "column3")]
    public string col3 { get; set; }
}
```

**Comment by kiquenet** [comment]
Latest version 22.0 is readonly `string Delimiter { get; }`

**Comment by tinus-office** [comment]
var config = new CsvConfiguration(CultureInfo.CurrentCulture, delimiter: ";");
var csvWriter = new CsvWriter(streamWriter, config);

**Comment by JoshClose** [comment]
You can use the `init` properties too.

```cs
var config = new CsvConfiguration(CultureInfo.Currentculture) { Delimiter = ";" }
```

**Comment by sbsw** [comment]
@JoshClose Is there a reason why the property initializer syntax is preferred over the constructor argument? I had used

    var config = new CsvConfiguration(CultureInfo.CurrentCulture, delimiter: ";");

in a [StackOverflow](https://stackoverflow.com/a/66166656/1637105) answer, and you edited the answer to use the other syntax:

    var config = new CsvConfiguration(CultureInfo.Currentculture) { Delimiter = ";" }

**Comment by JoshClose** [comment]
That constructor was removed. ;) 

The constructor has issues because it needs to default to null to allow for named properties, but then still needs a default. This is a problem when trying to actually set one of them to null. That constructor was only there because VB.NET doesn't understand `init` properties. I changed the properties to be settable until VB.NET updates (which is probably never) and removed the constructor, as it will and has caused a lot of confusion.

**Comment by harry-gordon** [comment]
On a related note, I was trying to set `DetectDelimiter` after instantiation the reader, which is allowed but has no effect on the parsing:

```c#
using var csv = new CsvReader(reader, configuration);

csv.Context.RegisterClassMap<EuropeanUnionSanctionsRowClassMap>();
csv.Context.Configuration.DetectDelimiter = true; // Ignored
```

I'm guessing this shouldn't be possible? Let me know if you'd like me to open a separate issue for it

**Comment by JoshClose** [comment]
@harry-gordon Yes that's not possible. It's read only at that point.
