### ISSUE TITLE
Parser fails when csv-fields contain newline-chars

### ISSUE THREAD

**Issue by eskimoe** [JoshClose/CsvHelper#274]
I have cases where certain fields contain newline-chars like \r and/or \n...
Therefore it would be great if you could define one 'real' newline-string
(eg \r\n), and the parser would ignore all other single \r or \n and treat them like any other characters!
Right now, it seems that csvhelper treats all (or at least most) combinations of CR/LF as a new line and therefore treats the rest of the line as a new record?
If thats too much to ask, maybe you know of a workaround?
Thanks for considering, and thanks for your great work!

**Comment by hardikddesai143** [comment]
public static IEnumerable<string> SplitToLines(this string input)
        {
            if (input == null)
            {
                yield break;
            }

            using (System.IO.StringReader reader = new System.IO.StringReader(input))
            {
                string line = string.Empty;
                string line1 = string.Empty;
                while ((line = reader.ReadLine()) != null)
                {
                    if (!string.IsNullOrEmpty(line1))
                        line = string.Concat(line1, Environment.NewLine, line);
                    if (line.Count(x => x == '"') % 2 == 0)
                    {
                        line1 = string.Empty;
                        yield return line;
                    }
                    else
                    {
                        line1 = line;
                    }
                }
            }
        }

**Comment by broll** [comment]
Sorry for commenting on such an old post... Ran into the same issue. I have no control over fixing the malformed files but still need to be able to read them. They were small enough that I just read them into memory in a MemoryStream removed the erroneous characters and gave that to CsvReader to parse. This is obviously not very ideal and you lose a lot of the efficiency of this package but gets the job done.
