### ISSUE TITLE
Cannot read special characters

### ISSUE THREAD

**Issue by ng-le** [JoshClose/CsvHelper#280]
Hi Josh,
How can i read value like 'Génifique '? I set the Encoding to Unicode but it's still happen. The character 'é' can't read.

Thanks
MillDol
![specialcharacter](https://cloud.githubusercontent.com/assets/8045581/3453576/8a344724-01c6-11e4-9433-592a4bff8c86.png)

**Comment by RedhwanGhailan** [comment]
Let's suppose:

-  that the CSV file splits by comma.
- we have a class model student.

 The following code reads the CSV file with all characters.
`    private static List<Student> ReadWholeCsv()
        {
            var fullPathName = @"Your file path";
            var encodingType = Encoding.GetEncoding("iso-8859-1");
            using (CsvReader csv = new CsvReader(new StreamReader(fullPathName, encodingType), CultureInfo.CurrentCulture))
            {
                csv.Configuration.Delimiter = ",";
                csv.Configuration.IgnoreQuotes = true;
                csv.Configuration.MissingFieldFound = null;

                return csv.GetRecords<Student>().ToList();
            }
        }`

**Enjoy**
