### ISSUE TITLE
Encoding with BOM(Byte Order Mark)

### ISSUE THREAD

**Issue by Austin-Liang** [JoshClose/CsvHelper#283]
Hi All, 

I have try something like this:

var utf8_Bom = new System.Text.UTF8Encoding(true);  // true to use bom.

and set it to:

using (var memoryStream = new MemoryStream())
{
    using (var streamWriter = new StreamWriter(memoryStream, utf8_Bom))
    using (var csvWriter = new CsvWriter(streamWriter))
    {
        // write csv bytes
        csvWriter.Configuration.Encoding = utf8_Bom;
        csvWriter.WriteRecords<DataRecord>(records.ToList());
    }

```
return memoryStream.ToArray();
```

}

but when I download csv file and open it with excel, it shows unreadable character encoding. ( I have Chinese in my data )

then I use emeditor to open csv file to check encoding, it shows UTF-8 without BOM.

so, I just save it again with UTF-8(BOM) option and open it with excel, this time everything works perfectly.
# 

It looks [ new System.Text.UTF8Encoding(true); ] doesn't work with CsvHelper properly.

Is there any workaround about this problem?

Thanks in advance.

Austin Liang.

**Comment by chucklu** [comment]
Finally I tried with this [solution](https://www.cyotek.com/blog/manually-writing-the-byte-order-mark-bom-for-an-encoding-into-a-stream)
```C#
string fileName;
byte[] data;
Encoding encoding;

fileName = Path.GetTempFileName();
data = new byte[0]; // assume you have a populated byte array!
encoding = Encoding.UTF8;

using (FileStream stream = new FileStream(fileName, FileMode.Create))
{
  using (BinaryWriter writer = new BinaryWriter(stream, encoding))
  {
    writer.Write(encoding.GetPreamble());
    writer.Write(data);
  }
}
```

**Comment by chucklu** [comment]
StreamWriter also work fine with a new created file
https://github.com/dotnet/runtime/blob/6ef4b2e7aba70c514d85c2b43eac1616216bea55/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs#L273

**Comment by daniol** [comment]
I share my code to write a CSV file with BOM:

```csharp
var utf8_Bom = new UTF8Encoding(true); // UTF with BOM encoding
using var stream = new FileStream("file.csv", FileMode.Create);
using var writer = new StreamWriter(stream, utf8_Bom);
var config = new CsvConfiguration(CultureInfo.CurrentCulture) { Delimiter = ";", Encoding = Encoding.UTF8 };
using var csv = new CsvWriter(writer, config);
csv.WriteRecords(records);
```
