### ISSUE TITLE
Commas within comma separated values issue

### ISSUE THREAD

**Issue by shadargee** [JoshClose/CsvHelper#291]
sample input csv: "a", "b", "c", "d1,d2,d3" (4 columns)
csvHelper reads it as: "a", "b", "c", "d1", "d2", "d3" (6 columns)

any way around this?
IgnoreQuotes = true/false does not help
Delimiter = ','

**Comment by VladDerptastic** [comment]
@JoshClose 
(v12.1.2 here)
However, for code:
```
var csvConfig = new Configuration()
{
     Encoding = Encoding.UTF8,
     Delimiter = ",",
     IgnoreQuotes = true
};
using (var streamReader = new StreamReader(fileStream))
{
     using (var parser = new CsvParser(streamReader, csvConfig))
      {
           //values: "CE272A","15,000.0","1","1.0","141.8"
           var row = parser.Read();
           ...
      }
}
```
I keep getting "15,000.0" as "\"15" and "000.0\"", and the file opens up in Excel with no issues. 
I was looking to replace the VisualBasic.FileIO parser (not .NET Standard compatible) which is handling this case as expected (value stays as "15,000.0"). 

Am I missing something in the configuration?

**Comment by marcrocny** [comment]
Remove `IgnoreQuotes = true`. This is expected behavior. See the [Configuration doc](https://joshclose.github.io/CsvHelper/api/CsvHelper.Configuration/Configuration/).

**Comment by VladDerptastic** [comment]
@marcrocny Indeed, that solved the issue! Thank you.

**Comment by sikemullivan** [comment]
Porting some older code to .NET Standard and I was looking at using this library to replace the use of Microsoft.VisualBasic.FileIO.TextFieldParser. This was actually in one of the unit tests, so it's a scenario that must have occurred. 

What exactly is the issue with writing some code that looks forward to see if the quote is there? This isn't really "Bad Data", so I'm not sure I understand some of the responses. 

If I have to "sanitize" the entire file before I read it through this library, I might as well write what I need from scratch.

**Comment by sikemullivan** [comment]
After some testing, I found that:

Considered Invalid Data
VAL1,VAL2,VAL3, "VA,L4",VAL6
                          ^ Space Inserted

Not Considered Invalid Data
VAL1,VAL2,VAL3,"VA,L4" ,VAL6
                                      ^ Space Inserted
