### ISSUE TITLE
Simple list of strings to CSV, what am I doing wrong?

### ISSUE THREAD

**Issue by crowbarsolutions** [JoshClose/CsvHelper#294]
Just trying to dump a List of strings to CSV, the resulting memorystream is always null:

```
    public static byte[] MakeCsvFile(List<string> records)
    {
        using (var memoryStream = new MemoryStream())
        using (var streamWriter = new StreamWriter(memoryStream))
        using (var csvWriter = new CsvWriter(streamWriter))
        {
            csvWriter.Configuration.HasHeaderRecord = false;
            foreach (var x in records)
            {
                csvWriter.WriteField(x.ToString());
            }
            streamWriter.Flush();
            memoryStream.Position = 0;
            return memoryStream.ToArray();
        }
    }
```

Also, instead of the foreach(), trying to do csvWriter.WriteRecords(records) causes the error: "Types that inhererit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?"

**Comment by aphex3k** [comment]
So you explained the error message but I don't seem to see how to solve it?

**Comment by Gaggle-Ltd** [comment]
To fix the problem you must use WriteRecords(..)
As eplained Josh the string implement interface IEnumerable that's why you can not pass string value to the WriteRecord.

var csv = new CsvWriter(writer);
csv.WriteRecords("sdfsdffds");
csv.NextRecord();
