### ISSUE TITLE
Malformed file does not trigger error

### ISSUE THREAD

**Issue by jimbillig** [JoshClose/CsvHelper#308]
I am just getting started with CsvHelper and was testing some random errors (created manually) when I came across what seems to be a bug.

Using the following code:
```
var csvFile = @"F:\test\cbhtest.csv";
var textReader = File.OpenText(csvFile);
var parser = new CsvParser(textReader);
while (true)
{
    var row = parser.Read();
    if (row == null)
    {
        break;
    }
}
```

And given the following data:
```
CBH,AAAAA,12277,CARRS,000000000339354.TXT
CBH,BBBBB,12335,"CARRS
"",000000000339355.TXT
CBH,CCCCC,18543,CARRS,000000000339359.TXT
```

The first two rows will read, but the third call to parser.Read() returns null.  No errors are triggered.  The issue seems to be triggered by the un-closed quoted text with the two quotes starting the next line.  I tried it a few different ways, but this was the only way that I could produce the issue.

I have no additional code or configuration settings (was just a test project).

I'm not too worried about it as the odds on it happening are pretty low, but I wanted to submit the issue just in case.

Regards,

Jim

**Comment by JoshClose** [comment]
Fixed. dab7ac7ffa91082aa345b52de3db2d869aec1f8f
