### ISSUE TITLE
Make TypeConverterOptionsFactory an instance variable.

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#318]
Having `TypeConverterOptionsFactory` be static and hold instances of types, we run into a problem in a multi-threaded environment if you want to use different cultures. https://github.com/JoshClose/CsvHelper/issues/290#issuecomment-63682538

Make `TypeConverterOptionsFactory` an instance on configuration like mentioned here. https://github.com/JoshClose/CsvHelper/issues/199#issuecomment-34404294

**Comment by cleftheris** [comment]
Hi Josh I was wondering if you are planning v3 any time soon.

Regards.

**Comment by JoshClose** [comment]
Hopefully in the next few months. I've been sick the past 2 weeks, and just busy in general. I want to get the current items out there done too before I do 3.0.

**Comment by StefanBertels** [comment]
Hi Josh,

this would be a great option to reduce explicit mapping, reducing coding overhead.

This would make writing anonymous types with custom datetime format a lot easier, like this one:

```
var element = new
                    {
                        Id = 9,
                        Text = "",
                        Timestamp = DateTime.UtcNow,
}

 using (
                            CsvWriter cw = new CsvWriter(tw,
                                new CsvConfiguration()
                                {
                                    Delimiter = ";",
                                    IsHeaderCaseSensitive = false,
                                    HasHeaderRecord = true
                                    // option missing for datetime format (typeconverter)
                                }))
                        {
                            cw.WriteRecords(new[] { element });
                        }
```

In the meantime I will use explicit class mapping (much more code) or use the memory inefficient and ugly way of making DateTime values string before:

```
TimeStamp = DateTime.UtcNow.ToString(...)
```

**Comment by JoshClose** [comment]
This is done and will be in NuGet version 3.0.0-beta6.
