### ISSUE TITLE
CultureInfo property on TypeConverterOptions doesn't work

### ISSUE THREAD

**Issue by xperiandri** [JoshClose/CsvHelper#320]
```C#
public void WriteRecordsTest()
{
    var options = new TypeConverterOptions
    {
        Format = "c",
        CultureInfo = new CultureInfo("EN-US")
    };
```
Doesn't work
Conversion is done without taking in account culture

Try change system culture to other then EN-US or try to set it within CsvConfiguration.
CsvConfiguration will be used regardless of TypeConverterOptions

Is this behavior desired?

**Comment by xperiandri** [comment]
Have you tried that?

**Comment by JoshClose** [comment]
No, sorry, been very busy.

**Comment by aamarber** [comment]
Same problem over here :( Any workaround or fix? I'm changing the CurrentThread culture to avoid this bug, but it's not an elegant solution.

**Comment by JoshClose** [comment]
I'm not able to reproduce this. I installed the Russian language and put it at the top. I switch to it using Win+Space. I open Visual Studio and run the tests (using NCrunch). I'm not getting any failing tests.

What am I doing wrong?

**Comment by xperiandri** [comment]
This is my language list
![Languages list]
(http://clip2net.com/clip/m407107/4d5e1-clip-58kb.png?nocache=1)

And this is my regional settings
![Regional Settings]
(http://clip2net.com/clip/m407107/444fb-clip-46kb.png?nocache=1)
Which means "the same as interface language" i.e. Ukrainian in my case.

So try to set regional settings to Russian.

**Comment by JoshClose** [comment]
I'm still having some trouble with it. Can you give me a code example that reproduces this? I can then follow the code through and find out why it's not being set for you.

**Comment by JoshClose** [comment]
I tried changing my settings and couldn't reproduce it. If you can give me failing example code that I can test with, I'll open this back up.
