### ISSUE TITLE
Map end of variable length csv to string array

### ISSUE THREAD

**Issue by ScottGuymer** [JoshClose/CsvHelper#328]
I have a CSV file where i know all of the columns in the csv and can map them but the last column(s) are repeating data that i would like to capture into a string array (or break out into an array of objects)

for instance i have a csv with the columns

a | b | c | d | e | e | e | e

So i know that abcde all occur and the type of e in the mapped object will be string[] and will contain an item in the array for each occurrence of the column e at the end of the file.

Is this possible with the library?

**Comment by JoshClose** [comment]
You can now map to collections in version 3.0.
