### ISSUE TITLE
Consider switching to a more friendly license

### ISSUE THREAD

**Issue by TimTheTinker** [JoshClose/CsvHelper#331]
Hello,

I'm trying to minimize the number of open-source licenses I'm using in 3rd party dependencies. Would it be possible to switch to (or dual-license) a more friendly (and GPL-compatible) license, like the BSD or Apache 2.0 license?

Thanks,
Roy

**Comment by JoshClose** [comment]
What under the MS-PL do you not like, or is too restrictive? I thought it was as open as MIT or Apache 2. The only reason I chose it is because corporations that only use MS products are more likely to allow a MS licensed OS project... silly, but true.

**Comment by TimTheTinker** [comment]
The MS-PL actually has a copyleft clause. Perhaps you could dual license?

Thanks for considering.

On Thursday, January 8, 2015, Josh Close <notifications@github.com> wrote:
> What under the MS-PL do you not like, or is too restrictive? I thought it
was as open as MIT or Apache 2. The only reason I chose it is because
corporations that only use MS products are more likely to allow a MS
licensed OS project... silly, but true.
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci4.googleusercontent.com/proxy/AO1hmTgalxBomWbKw1iX8IZG-_g4r2zEg1DaFJjhShVxBERZxpAP1w5arVkUspEtrNJtrsU0ka6Y5AXKRxkBKHAwZagEhHRI0316X0khJDjgYpJSY9GnEdwwFKYefP2-3eQPAv0viUyiN6DZQL139hK-gsnAIQ=s0-d-e1-ft#https://github.com/notifications/beacon/AA8EEAbso695lyvjkbAh4zVGxGeZP7kyks5nfzUsgaJpZM4DQLNV.gif
>

**Comment by JoshClose** [comment]
In here http://opensource.org/licenses/MS-PL is this what you are referring to?

(D) If you distribute any portion of the software in source code form, you may do so only under this license by including a complete copy of this license with your distribution. If you distribute any portion of the software in compiled or object code form, you may only do so under a license that complies with this license.

I just want to understand the problem. I'm kinda dumb when it comes to licensing. ;)

**Comment by TimTheTinker** [comment]
Yes, that's it. The FSF license lists it as a "weak copyleft":
http://www.gnu.org/licenses/license-list.html#SoftwareLicenses

I just think folks interested in incorporating your project into a
commercial product might think twice because of that.

**Comment by JoshClose** [comment]
I'll add Apache 2.0 and dual license it. I'll use this as a feature request until I get it complete. Hopefully by tomorrow.

**Comment by TimTheTinker** [comment]
Great, thanks!

**Comment by JoshClose** [comment]
Updated.
