### ISSUE TITLE
Ignore static property when writing

### ISSUE THREAD

**Issue by dlongest** [JoshClose/CsvHelper#332]
I'm getting an ArgumentException when I try to write a custom type record with a static property.  The exception text says `Static property requires null instance, non-static property requires non-null instance` so I assume the reflection that looks up properties on the type is blowing up trying to get the static property value using the instance itself instead of getting it for the type.  I don't actually need/want the static property value to show up when I call WriteRecord, I just want it to be ignored. 

Type looks something like:

````
class A
{
public int X { get; set;
public string Y { get; set; }

private static A _noA = new A();
public static A NoA { get { return this._noA; } }
}
````

I'm trying to avoid having to use WriteField manually.  Is there a way to address this using a custom class map or some other standard way this is handled?

**Comment by JoshClose** [comment]
Hmm... that seems like a bug to me. I will look into why it's mapping statics. 

For now you can create a mapping file and explicitly map all the properties.

```c#
public class AMap : CsvClassMap<A>
{
	public AMap()
	{
		Map( m => m.X );
		Map( m => m.Y );
	}
}
```

Then register the mapping before you write.

```c#
csvWriter.Configuration.RegisterClassMap<AMap>();
```

**Comment by dlongest** [comment]
Thanks for the tip.  I tried adding a map as you demonstrated, but I'm still getting the same exception, it acted like it didn't see the map.  I just removed the property altogether temporarily and noticed that a custom sub-type of the object wasn't outputting at all.  I wrote a map for the complex sub-type using yours as a guide, but none of its fields get written to the output file.  In debug mode I can see the map is in the Configuration on the CsvWriter instance, but it's not being used.   For example, in the types below when I write an instance of A, the value of Num gets written as does EventDate.When, but nothing about MyB is. 

````

public class A
{
public B MyB { get; set; }
public int Num { get; set; }
public C EventDate { get; set;
}

public class B
{
public string Name { get; set; }
public string Rank { get; set;
}

public class C
{
DateTime When { get; set; }
}

public class BMap : CsvClassMap<B>
{
public BMap()
{
Map(m => m.Name);
Map(m => m.Rank);
}

csvWriter.Configuration.RegisterClassMap<BMap>();
csvWriter.WriteHeader(typeof(A));
csvWriter.WriteRecords(enumerableOfAs);

````

**Comment by JoshClose** [comment]
If you don't use any mappings, it'll just work, but things may not be ordered like you want.

```c#
void Main()
{
	using( var stream = new MemoryStream() )
	using( var writer = new StreamWriter( stream ) )
	using( var reader = new StreamReader( stream ) )
	using( var csv = new CsvWriter( writer ) )
	{
		var list = new List<A>
		{
			new A
			{
				EventDate = new C
				{
					When = DateTime.Now,
				},
				MyB = new B
				{
					Name = "one",
					Rank = "1",
				},
				Num = 1
			},
		};
		
		csv.WriteRecords( list );
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class A
{
	public B MyB { get; set; }
	public int Num { get; set; }
	public C EventDate { get; set; }
}

public class B
{
	public string Name { get; set; }
	public string Rank { get; set; }
}

public class C
{
	public DateTime When { get; set; }
}
```

Result:
```text
Name,Rank,Num,When
one,1,1,1/13/2015 2:43:13 PM
```

If you want to use mappings with nested class, you need to use reference maps.

```c#
void Main()
{
	using( var stream = new MemoryStream() )
	using( var writer = new StreamWriter( stream ) )
	using( var reader = new StreamReader( stream ) )
	using( var csv = new CsvWriter( writer ) )
	{
		csv.Configuration.RegisterClassMap<AMap>();
		var list = new List<A>
		{
			new A
			{
				EventDate = new C
				{
					When = DateTime.Now,
				},
				MyB = new B
				{
					Name = "one",
					Rank = "1",
				},
				Num = 1
			},
		};
		
		csv.WriteRecords( list );
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class A
{
	public B MyB { get; set; }
	public int Num { get; set; }
	public C EventDate { get; set; }
}

public class B
{
	public string Name { get; set; }
	public string Rank { get; set; }
}

public class C
{
	public DateTime When { get; set; }
}

public class AMap : CsvClassMap<A>
{
	public AMap()
	{
		Map( m => m.Num ).Index( 3 );
		References<BMap>( m => m.MyB );
		References<CMap>( m => m.EventDate );
	}
}

public class BMap : CsvClassMap<B>
{
	public BMap()
	{
		Map( m => m.Name ).Index( 2 );
		Map( m => m.Rank ).Index( 1 );
	}
}

public class CMap : CsvClassMap<C>
{
	public CMap()
	{
		Map( m => m.When ).Index( 0 );
	}
}
```

Result:

```text
When,Rank,Name,Num
1/13/2015 2:54:16 PM,1,one,1
```

You only need to register the map for the class that is being passed into `WriteRecords`.

This is all documented here too. http://joshclose.github.io/CsvHelper

**Comment by dlongest** [comment]
Reference maps! Somehow I didn't see that in the documentation.  Thanks, that helped a lot.  Btw, really love your library, I'd love to contribute if there's something I could do to help.

**Comment by JoshClose** [comment]
I'm always behind on documentation. ;)

**Comment by dlongest** [comment]
Anything in particular you wish was more thorough or is missing?

**Comment by JoshClose** [comment]
Is there anything you see that is missing? That would be helpful. It seems like people are having a hard time following things or figuring out the more complex scenarios, or even the basic scenarios. I thought the doc starts out and explains the most common cases.

**Comment by JoshClose** [comment]
Fixed. 796e3b7f574b7cdcb7ab5971def9675344d24066
