### ISSUE TITLE
CSV Writer not writing child records

### ISSUE THREAD

**Issue by CallumVass** [JoshClose/CsvHelper#333]
I have the following setup:

    public class Parent 
    {
        public string Version { get; set; }
        public Child Child { get; set; }
    }

    public class Child 
    {
        public string Name { get; set; }
        public ICollection<OtherChild> OtherChildren { get; set; }
    }

    public class OtherChild
    {
        public string Location { get; set; }
        public DateTime LastSeen { get; set; }
    }

However, when I view what is being written, only the values of 'Parent' are there. I am writing like so:

    using (var fs = new FileStream(AppDomain.CurrentDomain.BaseDirectory + @"/file.csv", FileMode.Append, FileAccess.Write, FileShare.ReadWrite))
    {
        using (var streamWriter = new StreamWriter(fs))
            {
                var csv = new CsvWriter(streamWriter);
                csv.Configuration.AutoMap<Parent>();
                csv.WriteRecord(req); //req is an instance of Parent here with populated Children etc..
                streamWriter.Close();
            }
    }

**Comment by JoshClose** [comment]
Your call to `AutoMap<Parent>()` returns a `CsvClassMap` which you aren't setting to anything. Auto mapping will happen by default, so you don't have to do anything for that to occur.

Take a look at this example:

```c#
void Main()
{
	using( var stream = new MemoryStream() )
	using( var reader = new StreamReader( stream ) )
	using( var writer = new StreamWriter( stream ) )
	using( var csv = new CsvWriter( writer ) )
	{
		var list = new List<Parent>()
		{
			new Parent
			{
				Version = "1",
				Child = new Child
				{
					Name = "one",
					OtherChildren = new List<OtherChild>
					{
						new OtherChild
						{
							Location = "location",
							LastSeen = DateTime.Now,
						},
					},
				},
			},
		};
		
		csv.Configuration.au
		csv.WriteRecords( list );
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Parent 
{
    public string Version { get; set; }
    public Child Child { get; set; }
}

public class Child 
{
    public string Name { get; set; }
    public ICollection<OtherChild> OtherChildren { get; set; }
}

public class OtherChild
{
    public string Location { get; set; }
    public DateTime LastSeen { get; set; }
}
```

This will output:

```text
Version,Name
1,one
```

Here it's outputting from `Parent` and `Child`. The reason it doesn't output from `OtherChild` is because the property is a `ICollection`. Collections can't be used as a property map (currently). This is something I plan on adding in the future, but it's not very straight forward.

For now what you can do is write the record by hand.

```c#
csv.WriteField( "Version" );
csv.WriteField( "Child Name" );
csv.WriteField( "Location" );
csv.WriteField( "Last Seen" );
csv.NextRecord();
foreach( var item in list )
{
	csv.WriteField( item.Version );
	csv.WriteField( item.Child.Name );
	foreach( var c in item.Child.OtherChildren )
	{
		csv.WriteField( c.Location );
		csv.WriteField( c.LastSeen );
	}
	
	csv.NextRecord();
}
```
