### ISSUE TITLE
Possible to use auto map and custom class map in concert?

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#338]
Hello.  I have a CSV file where most of the column names map directly to properties of a POCO.  For a few columns, I need to create a custom map by name.  Does CsvHelper allow me to express something like "automap everything that you can automap, but if there's no mapping, then use this custom map"  OR  "use this custom map, but if there's no match, then fall back to an auto-map"

Or am I stuck with creating a custom class map and mapping everything by hand?

**Comment by JoshClose** [comment]
Yes.

```c#
public sealed class MyClassMap : CsvClassMap<MyClass>
{
    public MyClassMap()
    {
        AutoMap(); // Auto map everything
        Map( m => m.MyProperty ).Name( "blah" ); // Override one property
    }
}
```

**Comment by SurajGupta** [comment]
thanks for the quick reply and the example!  worked!
