### ISSUE TITLE
Ignore WillThrowOnMissingField for certain fields?

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#339]
Hello.  Is there a way to specify that a particular field might be missing, and if it is, then don't throw even if WillThrowOnMissingField = true?  For example, suppose you have a csv file that must have one set of fields, but another set of fields are optional.  Couldn't figure out how to configure for this scenario.  I could use a map with ConvertUsing where I TryGetField and if the field doesn't exist, set the property to some default value or null.  But with the out var, that lambda is looking pretty ugly =).  Any better way?

**Comment by JoshClose** [comment]
What do you want to happen if fields are missing? If you want an exception thrown, then no. If you don't need an exception throw, you can do this:

```c#
public class MyRecord
{
    public int RequiredField { get; set; }
    public int? OptionalField { get; set; }
}
```

**Comment by SurajGupta** [comment]
If a Required field is missing I'd like an Exception to be thrown.  If an Optional field is missing I'd like nothing to happen (no exception thrown)

**Comment by JoshClose** [comment]
That is how it should work if you use `Nullable<T>` fields for optional, and turn on `WillThrowOnMissingField`.

If this doesn't work, can you give me a small bit of example code to reproduce the issue?

**Comment by SurajGupta** [comment]
Hi Josh - 
- please create a new Console app and drop-in the following.  
- create a csv file with contents below
- Replace `filePath` with path to csv file.  

You'll get the error "Fields 'Opt' do not exist in the CSV file.'

**csv file contents**

    Req
    1
    4
    5

**code**

    using System.Globalization;
    using System.IO;

    using CsvHelper;
    using CsvHelper.Configuration;

    class Program
    {
        static void Main()
        {
            string filePath = @"c:\users\suraj\desktop\data.txt";
            using (var reader = new StreamReader(filePath))
            {
                using (var csvReader = new CsvReader(reader))
                {
                    ConfigureCsvReader(csvReader);
                    var myClassMap = new MyClassMap();
                    csvReader.Configuration.RegisterClassMap(myClassMap);

                    while (csvReader.Read())
                    {
                        var record = csvReader.GetRecord<MyRecord>();
                    }
                }
            }
        }
        
        public class MyRecord
        {
            public int RequiredField { get; set; }

            public int? OptionalField { get; set; }

        }
        
        public sealed class MyClassMap : CsvClassMap<MyRecord>
        {
            public MyClassMap()
            {
                Map(m => m.RequiredField).Name("Req");
                Map(m => m.OptionalField).Name("Opt");
            }         
        }

        internal static void ConfigureCsvReader(CsvReader csvReader)
        {
            csvReader.Configuration.AllowComments = false;
            csvReader.Configuration.CountBytes = false;
            csvReader.Configuration.CultureInfo = CultureInfo.CurrentCulture;
            csvReader.Configuration.Delimiter = ",";
            csvReader.Configuration.DetectColumnCountChanges = true;
            csvReader.Configuration.Encoding = Encoding.UTF8;
            csvReader.Configuration.HasExcelSeparator = false;
            csvReader.Configuration.HasHeaderRecord = true;
            csvReader.Configuration.IgnoreBlankLines = true;
            csvReader.Configuration.IgnoreHeaderWhiteSpace = false;
            csvReader.Configuration.IgnorePrivateAccessor = true;
            csvReader.Configuration.IgnoreQuotes = false;
            csvReader.Configuration.IgnoreReadingExceptions = false;
            csvReader.Configuration.IgnoreReferences = true;
            csvReader.Configuration.IsHeaderCaseSensitive = true;
            csvReader.Configuration.SkipEmptyRecords = false;
            csvReader.Configuration.ThrowOnBadData = true;
            csvReader.Configuration.TrimFields = false;
            csvReader.Configuration.TrimHeaders = false;
            csvReader.Configuration.WillThrowOnMissingField = true;
        }        
    }

**Comment by JoshClose** [comment]
Ok, I see the problem. You're not creating the CSV file too by chance are you?

You'll have to turn `WillThrowOnMissingFields` off. What you can do is check `csvReader.FieldHeaders` and if the required ones don't exist, throw an exception.

**Comment by SurajGupta** [comment]
Hi Josh - I am not creating the CSV file.  The file is already created and I'm just reading.  Does that change anything?  I don't fully understand the proposed solution.  Are you saying to check FieldHeaders right after I create the CsvReader?  If a required field is missing, then throw?  And that works because when parsing the data rows, if a value-type field has no data, then CsvHelper will throw because an empty string cannot be converted to a value type?

**Comment by JoshClose** [comment]
You'll need to read one row first so the header information is populated.

**Comment by SurajGupta** [comment]
Can I make a feature request for an easier way to distinguish between required and optional fields?  Perhaps `Map(m => m.OptionalField).IsOptional()` can be used to not throw when field is missing and WillThrowOnMissingFields is on?

**Comment by JoshClose** [comment]
You want to have `WillThrowOnMissingFields` on, but specify `Map( m => m.Field ).Optional()` so that it won't throw on that specific field?

**Comment by Thealexbarney** [comment]
Something like that would be a good solution. I'm dealing with a CSV file that may or may not have a certain field, and that would be really helpful.

**Comment by alexhelms** [comment]
I'd like to bump this as I am running into an issue where an Optional() method on the mapper would be super helpful. I have several columns in a CSV but some are required, some are optional and may or may not be present. I can't seem to find a way of keeping WillThrowOnMissingFields enabled and having support for optional fields.

**Comment by StefanBertels** [comment]
Maybe #716 is related. (With #716 you could throw some Exception in suggested OnMissingFields(...) -- dependent on field name).

**Comment by alexhelms** [comment]
While that is also a useful feature, my situation is different. I'm not trying to repair or replace missing data, some files have optional columns where the file can override the default value otherwise the default will suffice.

For an example, the CSV files I am using contain location information of features for a product. All products have some subset of features that are common. These headers are present across all CSVs. But some products have an additional column specifying an override for certain features and this override is only relevant for that product type. If the header isn't there, the default value of the mapper is fine.

**Comment by StefanBertels** [comment]
I understand, have similar use cases. And I don't want to abuse your request to just push #716.

This was just a hint for @JoshClose to compare the issues. But your use case might be easy to solve with something like a flexible OnMissingField callback.

A simple "Required" or "Optional" attribute is fine (and KISS).

**Comment by JoshClose** [comment]
@alexhelms There is now a `Validate( Func<string, bool> validateExpression )` for mapping. You can specify whatever criteria in there. Returning false will cause a `CsvValidationException` to be thrown. You could put this just on the properties you want to throw on.

**Comment by sebastienros** [comment]
+1 on having an `IsOptional()` method on a `MemberMap`. None of the solutions suggested here are compatible with custom mapping. Even the new ones since the last comment, like `Default`, or `MissingFieldFound`.

Throwing exceptions by default is fine, and should remain as it. But when we know a column is supposed to miss, it should be as simple as marking it like this. I will try to provide a PR.
