### ISSUE TITLE
CsvWriter - access to underlying TextWriter

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#340]
Would it be possible to expose the TextWriter that CsvWriter wraps?  In that way, if I want to write something directly to the stream, I don't have to pass around two objects.

**Comment by JoshClose** [comment]
What do you need to write directly to the stream? You shouldn't be putting non csv data in a csv file. :)

**Comment by SurajGupta** [comment]
I'd like to write 1 record X times, adding some contextual data (in csv format) each time.  For example (pseudocode):

    class MyRecord
    {
        string MyProp1 { get; set; }
        string MyProp2 { get; set;}
    }

    IEnumerable<MyRecord> allMyRecords = ...
    foreach(  MyRecord record in allMyRecords )
    {
        foreach(  var contextData in allContextData )
       {
            csvWriter.TextWriter.Write(  contextData.Item1 + "," + contextData.Item2 + ","  )
            csvWriter.WriteRecord(record)
       }
    }

I could create a new object with both the record and contextual data (maybe using something like [automapper]) and then write that instead, but with a large set of records and contextual data, it would be a bit of a performance hit.



[automapper]: http://automapper.org/

**Comment by JoshClose** [comment]
I really discourage doing that, but since it's passed in anyways, why not. :)

**Comment by SurajGupta** [comment]
thanks! =)

**Comment by JoshClose** [comment]
This is done in version 3.0.

**Comment by SurajGupta** [comment]
thanks!
