### ISSUE TITLE
Best way to read CSV file in parallel?

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#344]
Hello.  Is CSVHelper thread-safe for the read scenario?  Is there a recommended way or sample code to read records from a CSV file in parallel?

**Comment by JoshClose** [comment]
CsvHelper is not thread safe.

Do you want to read the same file in parallel or multiple files?

**Comment by SurajGupta** [comment]
I'd like the read the same file in parallel.  With a very large file, reading records can get time-consuming because converting a CSV string to a POCO is CPU-bound.  I was hoping to Parallel.ForEach or something similar to parallel process records.

**Comment by JoshClose** [comment]
It's really not possible. There is no way to tell where you can divide up the file. Line breaks can be contained inside fields. You have to actually parse it as a CSV record before you can tell.

What sort of times are you seeing? It should be able to chug through millions of records pretty quickly.

**Comment by SurajGupta** [comment]
hi Josh -   I had a process that was reading a file with 700+ million records.  When I gutted my own csv-to-POCO code in favor of CsvHelper, I added a 2 hours or so onto my processing time.  My code was sequentially reading lines from the CSV file into a List<string> and every 10K lines, it did a Parallel.ForEach over the elements of that list, calling a method that converted the CSV string to a record object.  

Because I cannot use CsvHelper in parallel, I can't do an apples-to-apples comparison of how much more time CsvHelper adds in the csv-to-record operation.  I'm expecting there will be some performance hit, because my own code was super thin and highly tailored to the record I was populating.

**Comment by JoshClose** [comment]
Can you show me the setup you're using for CsvHelper? CsvHelper will build an expression from your configuration/mappings and compile it so it should be as fast as doing it by hand. There are certain options that if you turn them on will slow things way down.

Can you try this for a test? Use just the parser with the default configuration and tell me how long it takes.

**Comment by SurajGupta** [comment]
I can certainly try with the default options.  Here are the options that I set.  Given this, would you still like me to do a full run over my file and report back?


        internal static void ConfigureCsvHelper(CsvConfiguration config)
        {
            config.AllowComments = false;
            config.CountBytes = false;
            config.CultureInfo = CultureInfo.CurrentCulture;
            config.Delimiter = ",";
            config.DetectColumnCountChanges = true;
            config.Encoding = Encoding.UTF8;
            config.HasExcelSeparator = false;
            config.HasHeaderRecord = true;
            config.IgnoreBlankLines = true;
            config.IgnoreHeaderWhiteSpace = false;
            config.IgnorePrivateAccessor = true;
            config.IgnoreQuotes = false;
            config.IgnoreReadingExceptions = false;
            config.IgnoreReferences = true;
            config.IsHeaderCaseSensitive = true;
            config.QuoteAllFields = false;
            config.SkipEmptyRecords = false;
            config.ThrowOnBadData = true;
            config.TrimFields = false;
            config.TrimHeaders = false;
            config.WillThrowOnMissingField = true;
        }

**Comment by JoshClose** [comment]
Yes, do a full run, but only use the parser.

```c#
using( var stream = File.Open( "my.csv" ) )
using( var reader = new StreamReader( stream ) )
using( var parser = new CsvParser( reader ) )
{
    while( parser.Read() != null ) { }
}
```
