### ISSUE TITLE
Need to have no quotes when empty field

### ISSUE THREAD

**Issue by BrianVallelunga** [JoshClose/CsvHelper#345]
Is it possible to configure things so that when an empty/null field is encountered, the writer just outputs the delimiter without any quotes, but otherwise uses quotes?

For example, given an object that looks like:

    var foo = new Foo
    {
        FieldA = "Hello",
        FieldB = null,
        FieldC = "World"
    }

I'd like the output to look like:

"Hello",,"World"

Right now I can only get:

"Hello", "", "World"

**Comment by JoshClose** [comment]
No. Currently the only options are: 

1. Quote when needed
2. Always quote
3. Never quote

`Quote when not empty` is not an option. 

What you could do is inherit `CsvWriter` and override `WriteField` and change the logic to your liking. Should be pretty simple. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvWriter.cs#L113
