### ISSUE TITLE
Rigid Column Count verification

### ISSUE THREAD

**Issue by xrabohrok** [JoshClose/CsvHelper#346]
For certain types of .csv files, where its output can be predicted, and deviation from certain formats would be...bad... it may be worthwhile to have a flag along the lines of

```C#
csv.Configuration.EnforceColumnCountConsistancy = true;
```

Which would then ensure that all columns are accounted for, and throw an exception if they deviate.  This would also be a step towards fixing the style of errors called out in bug #308 .

Implementation is, in theory, simply counting non-escaped delimiters in a line, subtracting one, and throwing an exception if this count deviates on other lines.

**Comment by JoshClose** [comment]
This is already implemented. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvParser.cs#L121

**Comment by xrabohrok** [comment]
Ah, there it is, called DetectColumnCountChanges .   My bad!

Since I already had the code open and was poking around it, quick question:
With that flag on, would you expect newline-only rows to trip that detection? Currently it doesn't.

**Comment by JoshClose** [comment]
No, because `Configuration.IgnoreBlankLines` is `true` by default.

**Comment by xrabohrok** [comment]
You can close this if you want, my needs are met.
