### ISSUE TITLE
Incorrect column output when consuming select iterators

### ISSUE THREAD

**Issue by ForNeVeR** [JoshClose/CsvHelper#349]
Consider the following code:

```csharp
var array = new[]
{
	new { a = "a1", b = "b1" }, // AnonymousType1
	new { a = "a2", b = "b2" }
};
var enumerable = array.Select(a => new { x = a.a, y = a.b, z = a.a + a.b }); // AnonymousType2

using (var csv = new CsvHelper.CsvWriter(Console.Out))
{
	csv.WriteRecords(enumerable);
}
```

It returns the following:

```
a,b
a1,b1,a1b1
a2,b2,a2b2
```

But I would except it to return the following:

```
x,y,z
a1,b1,a1b1
a2,b2,a2b2
```

And it can be fixed by adding the `ToList` after `Select` call:

```csharp
var enumerable = array.Select(a => new { x = a.a, y = a.b, z = a.a + a.b }).ToList();
```

I've debugged through the code and found that the column names indeed are taken from the `AnonymousType1` while they should be taken from the `AnonymousType2`. The reason is that the enumerator type is `System.Linq.Enumerable.WhereSelectArrayIterator<AnonymousType1, AnonymousType2>` and the code at https://github.com/JoshClose/CsvHelper/blob/master/src%2FCsvHelper%2FCsvWriter.cs#L433 is taking the _first_ generic argument.

**Comment by JoshClose** [comment]
Thanks for the pull request.
