### ISSUE TITLE
Remove garbage lines 

### ISSUE THREAD

**Issue by nanostrukturtechniker** [JoshClose/CsvHelper#351]
I have some (machine generated) CSV files with two garbage lines before the Header (both contain just one number):

12
54
Header1;Header2;...
34.43;454;...
.
.
.
It would be really a nice feature to skip a line, perhaps with an option like skipGarbageLinesBeforeHeader=2

This would be great! Thanks in advance!

Jörg

**Comment by JoshClose** [comment]
You can just do this:

```c#
for( var i = 0; i < 2; i++ )
{
    csv.Read();
}
```
