### ISSUE TITLE
Add Support for Windows Phone 8.1

### ISSUE THREAD

**Issue by holymoo** [JoshClose/CsvHelper#355]
Currently the package in NuGet only supports up to Windows Phone 8. It would be nice if it was also targeted for Windows Phone 8.1.

**Comment by jankratochvilcz** [comment]
+1

**Comment by JoshClose** [comment]
Done. 2.12.0.0 on NuGet should support 8.1 now.

**Comment by jankratochvilcz** [comment]
@JoshClose I just tried, it doesn't work for me. I create a new Windows Phone 8.1 (WinPRT) project, run `install-package CsvHelper -version 2.12.0` and get the following:

`Could not install package 'CsvHelper 2.12.0.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.`

Am I doing something wrong?

**Comment by JoshClose** [comment]
Hmm... I'll check it out tonight. I changed the PCL project to include Windows Phone 8.1.

**Comment by JoshClose** [comment]
NuGet is trying to download 2.1.0 from 2013... I'll fix the issue and get it pushed out hopefully tonight.

**Comment by JoshClose** [comment]
Got it in there...

**Comment by jankratochvilcz** [comment]
I can confirm that it works now. Thanks a bunch!

**Comment by JoshClose** [comment]
Ok, good!
