### ISSUE TITLE
Replace Null strings with a string of N length

### ISSUE THREAD

**Issue by AndiGibson** [JoshClose/CsvHelper#356]
Is there any way of passing in a value to the TypeConvertor? I basically want to replace any null values with a specified length string (padding fields in the csv to meet a specification)

I was hoping for something like this:

    Map(lambda).TypeConverter<MyStringConverter>(padLength);

I was hoping to do something like this:

    public class MyStringConverter : DefaultTypeConverter
    {
        public override string ConvertToString(TypeConverterOptions options, object value)
        {
            if (value == null)
            {
                return new string(' ',options.padLength);
            }

            return value.ToString();
        }
    }

**Comment by Chandu** [comment]
@AndiGibson I think you can use the `public virtual CsvPropertyMap TypeConverter( ITypeConverter typeConverter )` method to pass an instance of the type converter.

You can change the MyStringConverter to accept the padLength as a ctor parameter.

Something like this:

```
public class MyStringConverter : DefaultTypeConverter
{
	int _padLength = 0;

	public MyStringConverter(int padLength)
	{
		_padLength = padLength;
	}
    public override string ConvertToString(TypeConverterOptions options, object value)
    {
        if (value == null)
        {
            return new string(' ', _padLength);
        }

        return value.ToString();
    }
}
```

and the use this converter as follows:

`Map(lambda).TypeConverter(new MyStringConverter(padLength));`
