### ISSUE TITLE
Can I map class properties at runtime?

### ISSUE THREAD

**Issue by itaylorweb** [JoshClose/CsvHelper#36]
Hi,  Im trying to work out (if possible) how to map class properties at runtime hopefully the code below will demonstrate what im trying to achieve:

I am want to allow the user to map which fields from the csv will map to which fields in the Model. the code below receives the mappings as postdata.

```
        StreamReader reader = new StreamReader("file.csv");

        var csv = new CsvReader(reader);

        Data d = new Data();
        csv.Configuration.PropertyMap<Data>(p => p.DataID).Ignore();

        foreach (var key in postdata.AllKeys)
        {
            if (postdata[key.ToString()] != null)
            {
                PropertyInfo dMember = d.GetType().GetProperty(postdata[key].ToString());

                csv.Configuration.PropertyMap<Data>(p => dMember.Name).Name(postdata[key.ToString()].ToString());
            }
            else
            {
                PropertyInfo dMember = d.GetType().GetProperty(postdata[key].ToString());

                csv.Configuration.PropertyMap<Data>(p => dMember.Name).Ignore();
            }
        }

        IEnumerable<Data> theData = csv.GetRecords<Data>();
```

Please help.

Steve.

**Comment by vaibhavk10dec** [comment]
How can I map class properties at runtime for writing csv file using csv helper? It would be great for me 
if anyone send me sample code. Thanks !!!...

**Comment by JoshClose** [comment]
There is an example in the documentation. http://joshclose.github.io/CsvHelper/#mapping-runtime-mapping

**Comment by vaibhavk10dec** [comment]
Hi,
During runtime I want to change column name of csv file using csvhelper for this I write a below code but column name is not changed. 
Ex: public class customer
{
   public int cusId {get; set;}
   public string cusName {get;set;}
}

DefaultCsvClassMap customerMap<T> = new DefaultCsvClassMap<T>();
CsvClassMap CustomerMap;
using(CsvWriter writer = new CsvWriter(new StreamWriter(filePath)))
                {
foreach( string key in mapping.Keys )
{
    if( !String.IsNullOrEmpty( columnName ) )
    {
        var propertyInfo = typeof(T).GetType().GetProperty( key );
        var newMap = new CsvPropertyMap( propertyInfo );
        newMap.Name( columnName );  // Consider here I add new column name which I want to show           in csv file ex: "CustomerId" & "CustomerName"
        customerMap.PropertyMaps.Add( newMap ); // Here I already get proper Name properties & their type, no issues here
    }
}
CustomerMap = custCodeMap;
writer.Configuration.RegisterClassMap(CustomerMap);


                    writer.WriteRecords(lstCustomer);
                }

Assume list "lstCustomer" that contain customer type records having property name "cusId & "cusName"

By using these I want to export a record in csv file having column name "Customer Id" & "Customer Name" . But now in my case it export / write a csv file having column name "CusId" & "CusName"

**Comment by bborad** [comment]
Hi 

I am trying to do the same thing but it seems "CsvPropertyMap" is no longer available new latest version and there is no example at http://joshclose.github.io/CsvHelper/#mapping-runtime-mapping either. 

@itaylorweb would you mind posting your code if you have updated to latest version as well. 

@JoshClose  is there an example or documentation on how to do runtime mapping?

Thanks

**Comment by abrasat** [comment]
> The correct way is to create a class that derives from `CsvClassMap<T>` and register that mapping with the config.
> 
> https://github.com/JoshClose/CsvHelper/wiki/Fluent-Class-Mapping

The link does not work anymore... Where can be found the actualized example?

**Comment by JoshClose** [comment]
https://joshclose.github.io/CsvHelper/examples/configuration/class-maps

**Comment by abrasat** [comment]
Thanks for the link. Where can be found the mentioned example about the runtime mapping?

> There is an example in the documentation. http://joshclose.github.io/CsvHelper/#mapping-runtime-mapping

**Comment by JoshClose** [comment]
Search the issues here. This has been asked several times. There are answers for this on stackoverflow.com too.
