### ISSUE TITLE
Make currentIndex in CsvReader public

### ISSUE THREAD

**Issue by imachabeli** [JoshClose/CsvHelper#360]
The other day I was trying to find reason why CsvTypeConverterException was thrown. Exception does not give much clues about it, than looked at CsvReader  under debugger and realised that currentIndex   variable is actually the column number that threw the exception. Would be useful to expose it as readonly property.

**Comment by JoshClose** [comment]
The data you're looking for is in `Exception.Data["CsvHelper"]`. I will add this information to the documentation.

**Comment by richev** [comment]
I agree with @imachabeli that this would be a very useful enhancement to CsvHelper.
