### ISSUE TITLE
Auto Mapping without Header Record

### ISSUE THREAD

**Issue by marceloueda** [JoshClose/CsvHelper#361]
I've tested auto mapping with a CSV file without a header record.
The properties were declared in the same order of the CSV fields.

It worked. But is this safe? Is the map built according to Type.GetProperties() order (which is not guaranteed to be the declaring order) or does it use another approach?

**Comment by JoshClose** [comment]
Yes it does use that. Do you know of another way?

When there is no header, I would suggest creating a mapping file and specifying the index for each property.

**Comment by marceloueda** [comment]
Unfortunately not.
That was what I thought... just wanted to make sure I wasn't missing something.

Thanks for replying!
