### ISSUE TITLE
Documentation for mapping is outdated

### ISSUE THREAD

**Issue by geek0r** [JoshClose/CsvHelper#363]
The documentation for [mapping] (http://joshclose.github.io/CsvHelper/#mapping) currently says:

```csharp
// Does not work as CsvClassMap is actually CsvClassMap<T>. Map is not available here.
public sealed class MyClassMap : CsvClassMap
{
    public MyClassMap()
    {
        Map( m => m.Id );
        Map( m = > m.Name );
    }
}
```
But this is not working with the latest version ```2.11.1.1```. It should be:

```csharp
public sealed class MyClassMap : CsvClassMap<TehSourceClass>
{
    public MyClassMap()
    {
        Map( m => m.Id );
        Map( m = > m.Name );
    }
}
```

It would also be nice to mention the *setup of the mapping* on that page, too.
```csharp
var csv = new CsvWriter(tehStream);
csv.Configuration.RegisterClassMap(new MyClassMap ());
// ...
```

**Comment by JoshClose** [comment]
Thanks. I will get this updated soon.

**Comment by JoshClose** [comment]
So... this is an issue with using a '<' in the example, since that's a part of an HTML tag. The example actually does have it there, you just can't see it. Either way, I'll fix it.

**Comment by JoshClose** [comment]
Fixed.
