### ISSUE TITLE
First field is never escaped with quotes

### ISSUE THREAD

**Issue by gorgi** [JoshClose/CsvHelper#365]
Hi Josh and thanks for this awesome library! 

I noticed that when the QuoteAllFields is set to true, the first field is never wrapped in quotes, even if it contains the delimited character:

var csv = new CsvWriter(textWriter, new CsvHelper.Configuration.CsvConfiguration
            {
                CultureInfo = new System.Globalization.CultureInfo("en-US"),
                WillThrowOnMissingField = true,
                DetectColumnCountChanges = true,
                Delimiter = ",",
                QuoteAllFields = true
            });
            var l = forCounty.Select(x => new
            {
                AddressLine1 = x.AddressLine1,
                AddressLine2 = x.AddressLine2,
                City = x.City,
                Zip = x.Zip,
                TotalSales = x.TotalCharged
            }).ToList();
            csv.WriteRecords(l);

Am I doing something wrong?

**Comment by gorgi** [comment]
Actually, Excel is somehow removing the quote character from the first field. If I open the file with notepad++, everything seems in order.

Sorry, I will close the issue now

**Comment by JoshClose** [comment]
Gotta be careful with Excel. :)
