### ISSUE TITLE
DateTimeOffset properties are ignored when serializing type

### ISSUE THREAD

**Issue by Unrefraction** [JoshClose/CsvHelper#371]
Hi, 

I have a class with the next structure:

```
public class ReportDetail
{
        public DateTimeOffset Timestamp { get; set; }
        public string DetailType { get; set; }
        public Guid Reference { get; set; }
}
```

When calling 
```
writer.WriteHeader(typeof(ReportDetail));
```

I'd expect to get all three columns, but output file contains only DetailType and Reference.
Making Timestamp property nullable solves the problem, but it's rather workaround :)

**Comment by JoshClose** [comment]
There was no DateTimeOffsetConverter. I just added one. I will try and deploy a new build to NuGet tonight. aae8dc39ae261f4ee811276aa68874730e029e16
