### ISSUE TITLE
I want to use this lib at Unity Project

### ISSUE THREAD

**Issue by rapperkjm** [JoshClose/CsvHelper#373]
Unity 5 is supported to .Net 3.5.
Not support over .Net 4.0.

I tried to install package. Surely, I failed...

Is there another version to support .Net 3.5 under?

**Comment by JoshClose** [comment]
Are you using NuGet? There is a .NET 3.5 version available that should be installed using NuGet.

**Comment by rapperkjm** [comment]
Hmmm... yes. I used NuGet. But I couldn't install...

Error msg is...

PM> Install-Package CsvHelper
Installing 'CsvHelper 2.13.0.0'.
Successfully installed 'CsvHelper 2.13.0.0'.
Adding 'CsvHelper 2.13.0.0' to UnityVS.Client.CSharp.
Uninstalling 'CsvHelper 2.13.0.0'.
Successfully uninstalled 'CsvHelper 2.13.0.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'CsvHelper 2.13.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Unity Subset v3.5', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  CsvHelper
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 

Is there another solution to install?

**Comment by JoshClose** [comment]
Hmm... Try referencing the dll from the packages folder directly. It should have downloaded it. `packages\CsvHelper.2.13.0.0\net35-client\CsvHelper.dll`
