### ISSUE TITLE
Can I map class properties at runtime in version 2.12.0.2 ?

### ISSUE THREAD

**Issue by bilogik** [JoshClose/CsvHelper#375]
Hi,

I am trying to map class properties at runtime but I am unable to, the property map collection is not available to add etc., I tried following the steps mentioned in this  thread -  https://github.com/JoshClose/CsvHelper/issues/36
but I believe I am using a different version. (2.12.0.2). Is there any way that this can be done ?

**Comment by jamesbascle** [comment]
You could create a subclass of CsvClassMap that is also generic on T, and
make it's constructor take in a Dictionary<string,
Expression<Func<T,object>>> and loop through the items, calling
Map(kvp.value).Name(kvp.key).

**Comment by bilogik** [comment]
I looked around further and I was able to create a class map dynamically using "DefaultCsvClassMap" option. It works for now.

**Comment by Orcomp** [comment]
We will need to do something like this soon. Could you please post a code snippet here for reference, and I will then create a pull request for the docs.

**Comment by bilogik** [comment]
I have pasted the code below. I am unable to format the code (no option to format in the editor)

DefaultCsvClassMap<Customer> custCodeMap = new DefaultCsvClassMap<Customer>();
CsvClassMap CustomerMap;
      // mapping holds the Property - csv column mapping 
	foreach (string key in mapping.Keys)
	{
		string val = mapping[key].ToString();
		if (!String.IsNullOrEmpty(val))
		{
			PropertyInfo dMember = Activator.CreateInstance(typeof(Customer)).GetType().GetProperty(key);
			CsvPropertyMap newMap = new CsvPropertyMap(dMember);
			newMap.Name(val);
			custCodeMap.PropertyMaps.Add(newMap);
		}
	}
	CustomerMap = custCodeMap;
	csv.Configuration.RegisterClassMap(CustomerMap);

**Comment by jamesbascle** [comment]
Here's what I was thinking:

```c#
public class CsvMapSample
    {
//map from internal name to the expression for the poco property
        public Dictionary<string, Expression<Func<CsvEntityPoco,object>>> FieldNameToPropertyMemberExpression = new Dictionary<string, Expression<Func<CsvEntityPoco, object>>>
        {
            {"str1", c=>c.str1},
            {"str2", c=>c.str2},
            {"str3", c=>c.str3},
            {"str4", c=>c.str4},
            {"int1", c=>c.int1},
            {"int2", c=>c.int2},
            {"int3", c=>c.int3},
            {"int4", c=>c.int4},
        };

        public void WriteCsv()
        {
            //this maps between the field the user wants to put use for a particular value, and the internal name for the poco property
            var fakeUserInput = new Dictionary<string, string>
            {
                {"FakeName4", "str1"},
                {"FakeName1", "str2"},
                {"FakeName3", "str4"},
                {"FakeName2", "str3"},
                {"FakeName8", "int1"},
                {"FakeName5", "int2"},
                {"FakeName7", "int4"},
                {"FakeName6", "int3"}
            };

//join the user input, to the internal name to expression map to make a map between the field of the csv the user wants to use, to the field on the poco
            var userMappedEntity = fakeUserInput
                .Join(FieldNameToPropertyMemberExpression, 
                d => d.Value,
                d => d.Key,
                (d1, d2) => new {d1.Key, d2.Value})
                .ToDictionary(d => d.Key, d => d.Value);
            
//make the mapping
            var mapping =
                new GenericCsvMapper<CsvEntityPoco>(userMappedEntity);

            //do csv writing code here
        }
    }

    public class GenericCsvMapper<T> : CsvClassMap<T>
    {
        public GenericCsvMapper(Dictionary<string, Expression<Func<T, object>>> dict)
        {
            foreach (var expression in dict)
            {
                Map(expression.Value).Name(expression.Key);
            }
        }
    }

    public class CsvEntityPoco
    {
        public string str1 { get; set; }
        public string str2 { get; set; }
        public string str3 { get; set; }
        public string str4 { get; set; }
        public int int1 { get; set; }
        public int int2 { get; set; }
        public int int3 { get; set; }
        public int int4 { get; set; }
    }
```c#

**Comment by Orcomp** [comment]
Thanks.
You can use standard markdown syntax to highlight the code. (i.e. three back ticks).

I will make some minor changes and send a pull request to Josh tomorrow.

Here is what your code looks like using the markdown code block for C#:

```C#
DefaultCsvClassMap custCodeMap = new DefaultCsvClassMap();
CsvClassMap CustomerMap;

// mapping holds the Property - csv column mapping 
foreach (string key in mapping.Keys)
{
    string val = mapping[key].ToString();
    if (!String.IsNullOrEmpty(val))
    {
        PropertyInfo dMember = Activator.CreateInstance(typeof(Customer)).GetType().GetProperty(key);
        CsvPropertyMap newMap = new CsvPropertyMap(dMember);
        newMap.Name(val);
        custCodeMap.PropertyMaps.Add(newMap);
    }
}

CustomerMap = custCodeMap;
csv.Configuration.RegisterClassMap(CustomerMap);
```

Just looking at your code more closely could you replace:

```C#
PropertyInfo dMember = Activator.CreateInstance(typeof(Customer)).GetType().GetProperty(key);
```

with

```C#
PropertyInfo dMember = typeof(Customer).GetProperty(key);
```


Ok decided to tweak the code now. Could you please check if this still works for you:

```C#
var customerMap = new DefaultCsvClassMap();

 // mapping holds the Property - csv column mapping 
 foreach (string key in mapping.Keys)
{
    var columnName = mapping[key].ToString();

    if (!String.IsNullOrEmpty(columnName))
    {
         var propertyInfo = typeof(Customer).GetType().GetProperty(key);
         var newMap = new CsvPropertyMap(propertyInfo);
         newMap.Name(columnName);
         customerMap.PropertyMaps.Add(newMap);
     }
}

csv.Configuration.RegisterClassMap(CustomerMap); // Might have to cast back to a CsvClassMap here.
```

**Comment by JoshClose** [comment]
The auto map feature does everything dynamically if you want to take a look at that. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvClassMap.cs#L91

**Comment by bilogik** [comment]
The code works fine, I changed the below line from:
PropertyInfo dMember = Activator.CreateInstance(typeof(Customer)).GetType().GetProperty(key);
to
PropertyInfo dMember = typeof(Customer).GetProperty(key);

I am able to add properties dynamically at run time, thanks.
