### ISSUE TITLE
Docs website does not seem to be in sync with latest gh-pages

### ISSUE THREAD

**Issue by Orcomp** [JoshClose/CsvHelper#376]
![image](https://cloud.githubusercontent.com/assets/2459973/7275092/39330b28-e945-11e4-9cf9-b16da522fd18.png)

This is the md file in gh-pages. Which looks perfect. So I am not sure what the problem is.

![image](https://cloud.githubusercontent.com/assets/2459973/7275131/5f75616e-e945-11e4-8c1a-051b4b240e43.png)

**Comment by JoshClose** [comment]
It's an issue rendering the brackets; probably because they're being interpreted as html. I'll fix this soon.

**Comment by JoshClose** [comment]
It should be showing up correctly now.
