### ISSUE TITLE
csvHelper.Read() Skipping first record

### ISSUE THREAD

**Issue by anandneema14** [JoshClose/CsvHelper#380]
The helper seems to be reading the headers correctly, then skipping the first row of data (row 2 in csv)
IEnumerable records = csv.GetRecords();
csvhelper.Read();

the headers are on row 1, read in correctly, then data is read in starting with row 3 in CSV skipping the first data row (row 2) completely.

Please help.

-Anand

**Comment by jamesbascle** [comment]
Anand,

GetRecord returns a deferred execution reader that streams the results into the IEnumerable, and will read EVERYTHING in the file according to the config, headers first before returning the IEnumerable.

If you call csvHelper.Read(), you're essentially reading and throwing away the first data row, and then when you use the records variable, the reader reads the rest of the file.

Delete csvHelper.Read() and it should work just fine.

**Comment by anandneema14** [comment]
Thanks James for quick reply.

I called CsvHelper.Read(), because I need to verify all the headers present in CSV File.

Here is what I am doing:

CsvReader csvReader = new CsvReader(new StreamReader(file.InputStream));

IEnumerable<RawMTDataCSVUploadDetail> record = csvReader.GetRecords<RawMTDataCSVUploadDetail>();

csvReader.Read();
string[] headers = csvReader.FieldHeaders;

Is there any other way I can iterate the headers in CSV.

-Anand

**Comment by jamesbascle** [comment]
I believe that should still work without calling read according to the code in CsvReader.

**Comment by anandneema14** [comment]
Its not working actually, It is giving me exception to call the Read Method.

**Comment by jamesbascle** [comment]
What version are you using?

**Comment by anandneema14** [comment]
![image](https://cloud.githubusercontent.com/assets/12206932/7440292/f93f284a-f0c8-11e4-8fc0-81641a1f9cb8.png)

**Comment by jamesbascle** [comment]
Sorry, I meant of .NET 2, 3.5, 4, or PCL.  Also of the nuget package/dll itself rather than that info.

**Comment by anandneema14** [comment]
.NET 4.5

**Comment by jamesbascle** [comment]
Interesting.  Literally the first thing inside the code is 

	public virtual IEnumerable<T> GetRecords<T>() 
		{
			CheckDisposed();
			// Don't need to check if it's been read
			// since we're doing the reading ourselves.

			while( Read() )
			{

It seems quite strange that it is throwing that exception.

**Comment by anandneema14** [comment]
Any other alternative for this?

**Comment by jamesbascle** [comment]
You could set up symbol servers and get the symbols and step into the reader to see if Read() is not being called by GetRecords, and if the hasBeenRead flag has been set when you attempt to access  csvReader.FieldHeaders.

I see that you are not using any kind of maps or model objects or configurations in your call to GetRecords, and I've no experience in using it that way, unfortunately.

Other than that, I've never encountered this kind of problem, sorry.

**Comment by anandneema14** [comment]
NO issues I'll try to sort it out, and if found some workaround then I'll post it here.

-Anand

**Comment by anandneema14** [comment]
Hi James,

Solved the issue.
I used a configuration settings:
csvReader.Configuration.HasHeaderRecord = true;

-Anand

**Comment by JoshClose** [comment]
That setting is the default and you shouldn't have to change it. You must have explicitly been turning it off.

https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfiguration.cs#L25

**Comment by anandneema14** [comment]
Problem still persists.. :(

**Comment by JoshClose** [comment]
Can you paste a full working example (or unit test) that shows this happening?
