### ISSUE TITLE
Mapper classes with private constructors fail badly

### ISSUE THREAD

**Issue by bendetat** [JoshClose/CsvHelper#381]
As a consumer, passing a mapper class into `CsvReader.Configuration.RegisterClassMap` with a private constructor is a bad first experience as it fails with a null argument exception within the framework. Tweaking the reflection helper should allow private constructors, alternatively the framework should throw a better exception if the mapper can't be instantiated.

**Comment by JoshClose** [comment]
This is fixed and will be in release 3.0.

**Comment by bendetat** [comment]
Awesome. Fixed to allow private constructors, or to give a better error message?

**Comment by JoshClose** [comment]
Better error message. Sorry. I feel like it's a bad idea to call a private instructor like that. There is an overload that you can pass in your own map though, so you can create it via reflection if need be and pass it in.

If you have a very compelling reason why it should look for a private constructor, I'm all ears. I'd like to know why you want a private constructor on the mapping.

**Comment by bendetat** [comment]
Fair enough, I agree with not calling a private constructor now. It was ~15 months and several clients ago so I don't recall if I had a good reason or not. I'm now strictly using POCOs as DTOs when using CsvHelper so I haven't had this problem crop up again.

Thanks for the project BTW, it's been my go-to CSV parser for a long time now.

**Comment by JoshClose** [comment]
Great! I'm glad you're finding it useful.
