### ISSUE TITLE
Add option for ignoring underscores in header

### ISSUE THREAD

**Issue by kimsey0** [JoshClose/CsvHelper#385]
Being able to read for example a `first_name` header into a `FirstName` property without customizing the mapping would be neat. `IsHeaderCaseSensitive` manages half of that and `IgnoreHeaderWhiteSpace` does the other half, but only for whitespace characters. Could just be an extra flag, `IgnoreHeaderUnderscores`, or the configuration could have a collection of characters to ignore?

**Comment by JoshClose** [comment]
I think I may remove all of that and just have it be a Regex. You would easily be able to specify exactly what you want then. You should be able to do this then: `first_?last`. There would still need to be a case sensitive modifier I guess. `IgnoreHeaderWhiteSpace` wouldn't be needed anymore, and this should account for any other options that people may want.

**Comment by kimsey0** [comment]
That would be very nice. In the meantime, though, I've created a pull request for the option to ignore underscores that you can merge if you like. https://github.com/JoshClose/CsvHelper/pull/391

**Comment by jamesbascle** [comment]
Personally I think this should just be an array of characters to ignore in
the headers.  Seems much more extensible... And to keep from taking a
performance hit in the base case, maybe have it be a function that
transforms the column names however the consumer wants, and just have the
default be x=>x

**Comment by lightel** [comment]
That would be great to have either customizable regexp, overridable  lambda or array of characters that should be ignored. Just ran into this limitation when tried to parse a CSV with contacts exported from MS Outlook. A lot of fields have either whitespace or special symbols such as underscore, single quote or hyphen which cannot be mapped to property by default. Do you think it makes sense to post a pull request for any of this option?

**Comment by JoshClose** [comment]
I removed header matching manipulation configuration IsHeaderCaseSensitive, IgnoreHeaderWhiteSpace, and TrimHeaders and added a config for PrepareHeaderForMatch that is a function. Both the header field name and the property name are ran through this method before matching against each other.

Here are simple ways to solve those old configs.

```cs
// TrimHeaders
Configuration.PrepareHeaderForMatch = header => header.Trim();

// IsHeaderCaseSensitive
Configuration.PrepareHeaderForMatch = header => header.ToLower();

// IgnoreHeaderWhiteSpace
Configuration.PrepareHeaderForMatch = header => Regex.Replace( header, @"\s", string.Empty );
```

This will be in version 3.0.

**Comment by JoshClose** [comment]
```cs
// Remove underscores
Configuration.PrepareHeaderForMatch = header => Regex.Replace( header, "_", string.Empty );
```

**Comment by vanessaphinehas** [comment]
Is it possible to do a release soon with this option to remove underscores from headers, so that I can download it via Package Manager Console please? It would be very helpful. Thanks.

**Comment by JoshClose** [comment]
This is available in the release candidate.

```
Install-Package CsvHelper -Version 3.0.0-RC01
```

RTM should be happening pretty soon. I want to make sure all the possible breaking changes are done, and have a bare minimum for documentation up.

**Comment by peddanet** [comment]
I was not able to change a white space to an underscore. The element was named CWE ID and I changed it in my describing class to CWE_ID. But it then fails to recognize. Is this a known bug or did I just misinterprete the usage? In that case, I would be thankful for help :-)...

**Comment by JoshClose** [comment]
That method gets ran on both the header name and the member name, and you can do whatever you want to have them match. In your case, you might want to remove underscores and spaces maybe? Or you can replace white spaces with underscores or vice-versa.
