### ISSUE TITLE
Flattening collections

### ISSUE THREAD

**Issue by sumothecat** [JoshClose/CsvHelper#386]
In the wiki for the 2.0 release, I see a planned feature "Mapping IEnumerables".

I've been looking for a way to configure a collection to map to flattened columns, for both reading and writing.

For example, a property of type `List<Keyword>` where 

```cs
class Keyword 
{ 
    public string Vocab { get; set; } 
    public string Value { get; set;} 
}
```
 
should map to columns

```
Keyword1.Vocab, Keyword1.Value, Keyword2.Vocab, Keyword2.Value, etc...
```

Looking at the source, however, I don't think this can be done without some significant reworking.

**Comment by JoshClose** [comment]
Yeah. It's something that will need to be built in at the core. It's not really possible to create a converter for it. This is still planned, but like you said, it's not an easy change.

Currently for reading you can `ConvertUsing`. Here is a rough example...

```cs
Map( m => Keywords ).ConvertUsing( row =>
{
    var keywords = new List<Keyword>();
    for( var i = 4; i < 8; i = i + 2 )
    {
        var keyword = new Keyword();
        keyword.Vocab = row.Get( i );
        keyword.Value = row.Get( i + 1 );
        keywords.Add( keyword );
    }

    return keywords;
} )
```

For writing, you won't be able to use `WriteRecords` and you'll have to write things a little more manually.

```cs
foreach( var keyword in item.Keywords )
{
    csv.WriteField( keyword.Vocab );
    csv.WriteField( keyword.Value );
}
```

**Comment by sumothecat** [comment]
Thanks for the suggestions Josh. Unfortunately the writing workaround won't work from me (I need to be able to specify the mapping dynamically in a mapper) so looking forward to the feature. Would happily have a go but as you say it looks like it requires a low-level changing of assumptions in the CsvPropertyMap.

**Comment by JoshClose** [comment]
Can't you just not use a mapper for writing? Or do you want to keep all the logic in a single place?

**Comment by sumothecat** [comment]
We've got a piece of code which allows various configurations in the same library. We need to add another configuration with the flattening behaviour, so not really...!

**Comment by JoshClose** [comment]
Collections are supported in 3.0. You can try out the beta right now in NuGet.
