### ISSUE TITLE
Parser fails to correctly parse field if the field is escaped AND the last character is a quote

### ISSUE THREAD

**Issue by dkehring** [JoshClose/CsvHelper#388]
Simply try this unit test:

        [TestMethod]
        public void ParseEscapedFieldWithEscapedQuoteAtFieldsEndTest()
        {
            using (var stream = new MemoryStream())
            using (var writer = new StreamWriter(stream))
            using (var reader = new StreamReader(stream))
            using (var parser = new CsvParser(reader))
            {
                // 1,"two"",3
                writer.WriteLine("1,\"two\"\",3");
                writer.Flush();
                stream.Position = 0;

                var record = parser.Read();

                Assert.IsNotNull(record);
                Assert.AreEqual(3, record.Length);
                Assert.AreEqual("1", record[0]);
                Assert.AreEqual("two\"", record[1]);
                Assert.AreEqual("3", record[2]);
            }
        }

parser.Read() returns an array that contains 2 items: [1], [two",3]

**Comment by dkehring** [comment]
I think you need to make the distinction between a starting quote (immediately follows a delimiter), and ending quote (immediately precedes a delimiter) and an escaped quote.

**Comment by JoshClose** [comment]
It's parsing it correctly. 

You're field is `"two""`. The first `"` is saying the field is escaped. Any quote inside of a field now needs to be escaped. This is done by using 2 quotes in a row. `""` The field is not ended now until another quote is found, or the end of the file.

Based on your asserts, your line should look like this `1,"two""",3`.

**Comment by dkehring** [comment]
Thanks Josh. I now see my problem. The third-party software that is generating the CSV file that I am trying to parse is incorrectly outputting text that contains double quotes. It's not escaping them. You are correct.

**Comment by JoshClose** [comment]
Cool. Good luck with the tool.
