### ISSUE TITLE
Datetime format

### ISSUE THREAD

**Issue by lafama** [JoshClose/CsvHelper#39]
How does one control the datetime format of a property. I have tried the following 

[TypeConverter(typeof(CustomDateTimeTypeConverter))]
        public DateTime? Dob
        {
            get { return _dob; }
            set { _dob = value; }
        } 

public class CustomDateTimeTypeConverter : DateTimeConverter
    {
        public override object ConvertTo(ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType)
        {
            if (destinationType == typeof(string))
            {
                return ((DateTime)value).ToString("dd-MM-yyyy");
            }
            return base.ConvertTo(context, CultureInfo.InvariantCulture, value, destinationType);
        }
    }

**Comment by KevivL** [comment]
Do you have a config level / global type converter option or it needs to be attached on specific properties via type maps? Ex. When exporting i want all dates written as yyyy-MM-dd. Is there a way to do that outside of on a per property basis in individual type maps?

**Comment by JoshClose** [comment]
Yes.

```cs
var options = new TypeConverterOptions
{
	Format = "yyy-MM-dd",
};
CsvHelper.TypeConversion.TypeConverterOptionsFactory.AddOptions<DateTime>(options);
```

**Comment by KevivL** [comment]
Awesome. Thank You!

**Comment by JoshClose** [comment]
Not right now. It's planned though. https://github.com/JoshClose/CsvHelper/issues/318

**Comment by TheCycoONE** [comment]
Took me hours to find this, could you put a TypeConverterOptionsFactory example on your page?

**Comment by SupremeMagus** [comment]
CsvHelper.TypeConversion.TypeConverterOptionsFactory

unable to find this class, using version 2.2.0

**Comment by JoshClose** [comment]
It was renamed to `TypeConverterOptionsCache` because it wasn't a factory.
