### ISSUE TITLE
Default should be usable even when Index or Name not specified

### ISSUE THREAD

**Issue by SuperSkippy** [JoshClose/CsvHelper#393]
E.g. ::

```cs
public sealed class MyClassMap : CsvClassMap<MyClass>
{
    public MyClassMap()
    {
        Map( m => m.Id ).Name( "The Id Column" );
        Map( m => m.Name ).Name( "The Name Column" );
        **Map( m => m.AlwaysTheSame ).Default(32);**
    }
}
```

I'd like property AlwaysTheSame to be 32 for every row, but currently this isn't supported.

This might seem like a silly request, but I'm building my class maps dynamically using CSV mapping supplied by my users using their own CSV file formats. If they don't have a record in their CSV file that matches they often want to use a default.

**Comment by JoshClose** [comment]
Try this:

```cs
Map( m => m.AlwaysTheSame ).ConvertUsing( row => return 32; );
```

**Comment by JoshClose** [comment]
This is actually an example in the docs... not that it's an easy one to find. ;)

http://joshclose.github.io/CsvHelper/#mapping-convert-using

**Comment by JoshClose** [comment]
`Default` is meant to use a value when there is no value. If you only map the property and don't specify a `Name` or `Index`, the property name is used if there is a header and an index for the order it's in is used if there is no header. This means `Default` won't work in this situation.

I think creating a new config of `Constant( T value )` for this makes more sense.

**Comment by JoshClose** [comment]
This is in version 3.0.
