### ISSUE TITLE
Default DateTimeOffset converter

### ISSUE THREAD

**Issue by barclayadam** [JoshClose/CsvHelper#395]
Have just noticed a problem with our use of CsvConverter caused by our usage of DateTimeOffset and a missing default converter which means the field was just skipped (using auto mapping with a simple `.WriteRecords(...)`.

Our fix is a simple `TypeConverterFactory.AddConverter<DateTimeOffset>(new CsvHelper.TypeConversion.DateTimeConverter());` but not sure if that is enough for the library in general?

**Comment by JoshClose** [comment]
It's missing. I'm surprised you're the first person to catch that. :) https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/TypeConverterFactory.cs#L147

**Comment by barclayadam** [comment]
Have upgraded to 2.12 but it seems you have missed adding the new DateTimeOffsetConverter to the default list in TypeConverterFactory. Thanks for the quick turnaround though :)

**Comment by JoshClose** [comment]
I'll try and get that done tonight.
