### ISSUE TITLE
Calling Dispose breaks disposable pattern

### ISSUE THREAD

**Issue by TamusJRoyce** [JoshClose/CsvHelper#396]
Calling dispose disposes the TextWriter that the CsvHelper did not create (it is always passed through the new constructor). You should only dispose items which you have made new instance of yourself. Please eliminate these two lines of code from CsvSerializer:

```
if (disposing && this.writer != null)
    this.writer.Dispose();
```

Thanks! Sorry for any inconvenience.

Also, if you do create any StreamReaders and StreamWriters, please consider these functions (work-around's for where even Microsoft has broken their disposable pattern).

```
        public static StreamReader NewStreamReader(Stream stream)
        {
            return GetStreamReaderWorkaroundForBrokenDisposePattern(stream);
        }
        private static StreamReader GetStreamReaderWorkaroundForBrokenDisposePattern(Stream stream) 
        { 
            return new StreamReader(stream, Encoding.UTF8, true, 1024, true); 
        }

        public static StreamWriter NewStreamWriter(Stream stream)
        {
            return GetStreamWriterWorkaroundForBrokenDisposePattern(stream);
        }
        private static StreamWriter GetStreamWriterWorkaroundForBrokenDisposePattern(Stream stream) 
        { 
            return new StreamWriter(stream, Encoding.UTF8, 1024, true); 
        }
```

Both methods use the default parameters except for the last parameter. true means "don't dispose underlying stream." Unfortunately it requires .NET 4.0+

**Comment by TamusJRoyce** [comment]
Example:

```
               using(StreamWriter textWriter = WriteItem.OpenStream())
                {
                    /*using (*/var writer = new CsvWriter(textWriter, GetConfiguration(CsvConfig)) /*)
                    {*/
                        WriteRow(writer, Table.Headers);
                        writer.NextRecord();

                        foreach (string[] fields in Table.Rows)
                        {
                            WriteRow(writer, fields);
                            writer.NextRecord();
                        }
                    /*}*/

                    WriteItem.CloseStream();
                }
```
I shouldn't have to comment out the inner using block, as all IDisposable objects should guarantee be closed as soon as they aren't needed. Or they shouldn't be IDisposable.

The other fix would be to make this class not IDisposable?

**Comment by JoshClose** [comment]
Are you saying it doesn't work with the `using` around `CsvWriter` or that you shouldn't have to use a `using` around it?

Since it's passed in and shouldn't be handled, then there is no need to implement `IDisposable` at all. This would be a breaking change though. I would have to leave the interface implementation for now, and just remove the disposing, which might be kind of confusing.

**Comment by TamusJRoyce** [comment]
Yes. This shouldn't have needed to implement IDisposable.

On second thought, since it does implement it and others may rely on this functionality, could you add a boolean parameter to the constructor specifying if the class should dispose the stream? If this parameter is not specified, it should dispose the stream with the broken disposable pattern as before. Just like Microsoft has done.

Or it could be a property called DisposeStream, which is true by default. Instead of using a constructor parameter. Whatever you feel would be best practices.

Sorry for not thinking of the big picture when I first submitted this. Thanks for you help!

**Comment by piers7** [comment]
I've run into this a few times also, and when you hit it it is a real pain.

My recommendation would be to follow what Microsoft did on StreamWriter, and pass a boolean on the constructor that controls whether the supplied TextWriter is closed-on-dispose. Or expose a property in the configuration that does the same thing. Either are non-breaking changes.

BTW disposing the writer by default is still quite convenient (even if strictly speaking wrong), because it allows simple constructs like

    using(var writer = new CsvWriter(new StreamWriter(somepath))) { etc... }

ie doesn't force you to nest the using statements, and pull the writer out into a separate local variable

**Comment by JoshClose** [comment]
I'll be doing this. I'm real busy at the moment, so not sure when I'll get to it.

**Comment by TheCycoONE** [comment]
:+1: for a leaveOpen bool like Microsoft uses. I need access to my stream after csvhelper is disposed and the workaround of extending it's lifetime is ugly. At the moment I'm getting an ```ObjectDisposedException``` when I try to flush on the underlying writer.

**Comment by shift-evgeny** [comment]
Agree with the boolean parameter solution.

While you're at it, it would be nice to add a constructor that takes a file path and creates a StreamReader, which is then disposed when the CsvReader is disposed. Most CSV files are, well... files, so this would be a very common use case and it avoids having to wrap the reading code in another using statement, ie.

    using (var streamReader = new StreamReader(filePath))
    using (var csvReader = new CsvReader(streamReader))
    ...

**Comment by TamusJRoyce** [comment]
Duplicate of https://github.com/JoshClose/CsvHelper/issues/325

**Comment by JoshClose** [comment]
This done and will be in release 3.0.0-beta6.
