### ISSUE TITLE
Add documentation for reading into a dynamic object

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#399]
https://github.com/JoshClose/CsvHelper/commit/d992b1a436493d46989bc65d15ec641656781d97#commitcomment-11618573

**Comment by MrChilBoy** [comment]
This would be most appreciated. I'm trying to use CsvHelper to import user configured data files in and then output it as XML for consumption outside .NET - within .NET there will be no tightly coupled object structure. I've been trying to use ExpandoObjects so I could get an object back from GetProperty() but it doesn't add that level of decoration.

Even just a sample file using dynamics would be good enough.

Thanks Josh :)

**Comment by JoshClose** [comment]
This has been added to the 3.0 documentation. Did you figure it out? I didn't realize you were asking before and thought you just wanted to make sure it got documented.

I know it's way too late, but for anyone else that finds this:

```cs
var records = csv.GetRecords<dynamic>();
```

**Comment by MrChilBoy** [comment]
Thanks Josh. Yes, I've solved it already :)
