### ISSUE TITLE
Escaping comma between quotes

### ISSUE THREAD

**Issue by nbelley** [JoshClose/CsvHelper#401]
Currently, unless I'm missing something, if you have a string on a line that looks like this:

"some infos", "some infos with a ,comma", "etc"

... the field with the comma will get split. Is there any way to change that?

Thank!

**Comment by JoshClose** [comment]
It shouldn't be. Can you give me some example code that demonstrates this?

A string of

`"some infos", "some infos with a ,comma", "etc"`

should be interpreted as

`some infos` `some infos with a,comma`, `etc`

Technically, the format is bad. There shouldn't be any space in between the comma and the start of the field.

Open the file up in Excel. It should be rendered the same there.

**Comment by nbelley** [comment]
My case looks like that, I tried with only one line in file:

> "000000000","BESSETTE & BOUDREAU                ","JEAN ROUILLARD, PRES          ","111 RTE 111         ","WINDSOR             ","QC","XXX XXX","PIERRE ROBERT          ","(111) 111-1111","              ","(111) 111-1111"," ","1","1","0","00 ","CANADA",

The field in problem is "JEAN ROUILLARD, PRES          "

    using (var streamReader = new StreamReader(
                            File.Open(filePath, FileMode.Open),
                            Encoding.GetEncoding("iso-8859-1")))
                        {
                            var csv = new CsvReader(streamReader, new CsvConfiguration());

                            csv.Configuration.HasHeaderRecord = false;
                            csv.Configuration.RegisterClassMap<ImportRawDataClientMap>();
                            var records = csv.GetRecords<ImportRawDataClient>().ToList();
                        }

The mapper looks like that:

    public sealed class ImportRawDataClientMap : CsvClassMap<ImportRawDataClient>
    {
        public ImportRawDataClientMap()
        {
            Map(m => m.Number).Index(0);
            Map(m => m.Name).Index(1);
            Map(m => m.AttentionOf).Index(7);
            Map(m => m.PhoneNumber).Index(8);
            Map(m => m.PhoneNumber1).Index(9);
            Map(m => m.PhoneNumber2).Index(10);
        }
    }

**Comment by JoshClose** [comment]
Does Excel open the file as expected?
