### ISSUE TITLE
Ignoring commas in numeric data

### ISSUE THREAD

**Issue by adaam2** [JoshClose/CsvHelper#402]
I am receiving the error "The conversion cannot be performed." with regards to the following line in my CSV file:

```Row: '3' (1 based) Type: 'CsvRecord' Field Index: '10' (0 based) Field Name: 'TransactionAmount' Field Value: '1,925.36'```

My conversion method looks like:

    IEnumerable<CsvRecord> GetCsvRecords(TextReader reader)
    {

        var csvReader = new CsvReader(reader);
        csvReader.Configuration.Delimiter = ",";
        csvReader.Configuration.IgnoreBlankLines = true;

        return csvReader.GetRecords<CsvRecord>();
    }

Where the CsvRecord class is as below:

        public class CsvRecord
        {
            public DateTime TransactionPostedDate { get; set; }
            public string SettlementId { get; set; }
            public string AmazonTransactionId { get; set; }
            public string SellerReferenceId { get; set; }
            public string TransactionType { get; set; }
            public string AmazonOrderReferenceId { get; set; }
            public string SellerOrderId { get; set; }
            public string StoreName { get; set; }
            public string CurrencyCode { get; set; }
            public string TransactionDescription { get; set; }
            public decimal TransactionAmount { get; set; }
            public decimal TransactionPercentageFee { get; set; }
            public decimal TransactionFixedFee { get; set; }
            public decimal TotalTransactionFee { get; set; }
            public decimal NetTransactionAmount { get; set; }
        }

I believe that this error is most probably due to the fact that there are commas in the numeric data for these fields. How do I strip the commas before parsing?

**Comment by jamesbascle** [comment]
You could implement a TypeConverter, and have your mapping specify using it, and you could just manually remove the commas in the code for that type converter.

**Comment by JoshClose** [comment]
If you're not using mappings, you can change the global number styles for the decimal type.

```cs
TypeConverterOptionsFactory.GetOptions( typeof( decimal ) ).NumberStyle = NumberStyles.AllowThousands | NumberStyles.AllowDecimalPoint;
```

**Comment by peterbrennen** [comment]
TypeConverterOptionsFactory does not appear to exist/work in the latest version 4.0.2, but I really need a solution to this please.

**Comment by JoshClose** [comment]
`TypeConverterOptionsFactory` was renamed to `TypeConverterOptionsCache`

**Comment by xorith** [comment]
Sorry to bump this, but I'm having issues as well.

I have a transform object that has nullable decimals and a source with a formatted number. I'm getting the same issue, only the typeconverter is the NullableConverter.

Thoughts?

**Comment by marcolee149394** [comment]
When I started using it , I thought it was good. Now I think it is a junk. No style in header(bold) Missing 00 if the string is decimal value. It is only good for basic app

**Comment by JoshClose** [comment]
I don't understand. None of that is a part of CSV. Sounds like you might want to use an Excel library instead.

**Comment by xorith** [comment]
@marcolee149394 CSVs are strings, regardless of what the implied data type is. If you need decimal places in your string, then your code should properly format it. 

You can create a FormattedDecimalTypeConverter with something like this:
```C#
    public class FormattedDecimalTypeConverter : DefaultTypeConverter
    {
        public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
        {
            var _dec = value as decimal?;
            return _dec.HasValue ? $"\t{_dec:0.00}" : string.Empty;
        }
    }
```
