### ISSUE TITLE
DateTime column empty values when using GetRecords<T>

### ISSUE THREAD

**Issue by grisharav** [JoshClose/CsvHelper#404]
I'm using the library to parse a CSV file which should have data in all columns and I'm using
```
...
            reader.Configuration.HasHeaderRecord = true;
            reader.Configuration.TrimHeaders = true;
            reader.Configuration.TrimFields = true;
            reader.Configuration.WillThrowOnMissingField = true;
            reader.Configuration.ThrowOnBadData = true;
            reader.GetRecords<MyRecord>()
...
```
And when the DateTime field is empty I do receive records with default DateTime value (MinValue)
I saw #24 but I don't use GetField directly

Ideas?

**Comment by grisharav** [comment]
Just to clarify, I'm expecting an exception to be thrown

**Comment by JoshClose** [comment]
`WillThrowOnMissingField` gets called if `string GetField( int index )` gets called, which is the root of getting the value for any field. This means that column wouldn't exist. Getting by name just translates into getting by an index.

In your case, the column exists, but the field is empty. The built in .NET converters will convert an empty string into `DateTime.MinValue`. A `null` may throw an exception or convert... I don't remember off hand. The CsvHelper converters should behave the same.

A solution for you would be to create your own `DateTimeConverter`; possibly by inheriting from the existing one. If the value is null or whitespace, then throw some sort of exception.

Here is an example:

```cs
public class MyDateTimeConverter : DateTimeConverter
{
    public override object ConvertFromString( TypeConverterOptions options, string text )
    {
        if( string.IsNullOrWhiteSpace( text ) )
        {
            throw new CsvTypeConverterException( "DateTime field is empty." );
        }

        return base.ConvertFromString( options, text );
    }
}
```
You can then register the converter globally or for the specific field only.

**Comment by grisharav** [comment]
Thanks for the reply. I will do as you suggested.
