### ISSUE TITLE
TryGetField<T>(string name, int index, out T field) not working

### ISSUE THREAD

**Issue by AlanGRutter** [JoshClose/CsvHelper#405]
Using the normal version of TryGetField<T>(string name, out T field) on my row,  I get the expected results but when I change this to use the instance index version as per the subject line and use index 0, I get a result of false and I do not get the value.

My data contains multiple instances of the same field name so I wanted to use the above version of this method. Is this a bug?

**Comment by AlanGRutter** [comment]
I debugged into the code and I think I found a bug. The overloaded function TryGetField<T>(string,int,ITypeConverter,out t) gets the fieldIndex by calling GetFieldIndex (@ line 781) for the named field instance but then goes on to call TryGetField on line 788 using 'index' instead of fieldIndex.

**Comment by JoshClose** [comment]
Pushed to nuget.
