### ISSUE TITLE
Problems with entity framework

### ISSUE THREAD

**Issue by usercode** [JoshClose/CsvHelper#407]
Version: 2.13.2.0

It seems that proxy classes are not supported?! 

Map(x => x.Customer.FullName)

Property 'System.String FullName' is not defined for type 'System.Data.Entity.DynamicProxies.Customer_8308D9361561E93FB06F5667D996D9D896E0DBF5453BF77BB5822722E6A393A0'

or is there a workaround to export entities of the entity framework?

**Comment by JoshClose** [comment]
I will have to look into this.

**Comment by usercode** [comment]
Ok, thanks.

It's not especial a problem with entity framework. The problem is the inheritance handling. 

The property "FullName" is part of the class "Person". The "Customer" class inherits from "Person". When I disable the proxy creation of the entity framework, I get the same error message.

See CsvWriter, Line 577

-> return Expression.Property(recordExpression, propertyMap.Data.Property);

**Comment by JoshClose** [comment]
I don't think it's an inheritance issue. This works:

```cs
void Main()
{
	using( var stream = new MemoryStream() )
	using( var writer = new StreamWriter( stream ) )
	using( var reader = new StreamReader( stream ) )
	using( var csv = new CsvReader( reader ) )
	{
		writer.WriteLine( "Id,FullName" );
		writer.WriteLine( "1,User One" );
		writer.WriteLine( "2,User Two" );
		writer.Flush();
		stream.Position = 0;
		
		csv.GetRecords<Customer>().ToList().Dump();
	}
}

public class Person
{
	public string FullName { get; set; }
}

public class Customer : Person
{
	public string Id { get; set; }
}
```

**Comment by JoshClose** [comment]
It seems like your structure is a little different though. Can you give me the class structure? If you have a object that has a property `Customer` on it that is a `Customer` class, then you need to do a reference map.

```cs
References( m => m.Customer );
```

**Comment by usercode** [comment]
Try this example, please: 

class Program
    {
        public static void Main()
        {
            using (var stream = new MemoryStream())
            using (var writer = new StreamWriter(stream))

            using (var csv = new CsvWriter(writer))
            {
                csv.Configuration.RegisterClassMap<OrderMap>();

                Customer cust = new Customer() { FullName = "John Doe" };
                Order[] orders = new[] { new Order() { Customer =  cust} };

                csv.WriteRecords(orders);
            }

            Console.Read();
        }

        public class Customer
        {
            public string Id { get; set; }

            public string FullName { get; set; }
        }

        public class Order
        {
            public Customer Customer
            {
                get;
                set;
            }
        }

        public class OrderMap : CsvClassMap<Order>
        {
            public OrderMap()
            {
                Map(x => x.Customer.FullName);
            }
        }
    }

I checked a version with "reference" map and it works. BUT I don't want to map the class "customer" twice. A short and a long version with all properties. The order mapping should only output the "FullName" property. 

So, it's possible to make this simple mapping working?? :-)

  Map(x => x.Customer.FullName);

**Comment by JoshClose** [comment]
This is working as expected in the latest source.
