### ISSUE TITLE
Add config option to look at fields

### ISSUE THREAD

**Issue by wrummler** [JoshClose/CsvHelper#408]
Coming from [Is it possible to serialize fields (not just properties) with CsvHelper?](http://stackoverflow.com/a/22998076/402749)

It'd be an *extremely* valuable feature. It's true that sometimes you can just switch to using properties, but sometimes you're interfacing to legacy code that you can't touch for whatever reason... politics included `:-)`

I also think it might be helpful to add a config option to not look at properties (which could, for example, always set "look at fields" to true when it's set to false; setting "look at fields" to false could also set it to true). The parallel argument for this addition is probably not as compelling, but I have a feeling there are times when this would make CsvHelper users' lives easier.

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/issues/416

**Comment by JoshClose** [comment]
This is done and will be in 3.0. It was a crazy huge change to get it to work.
