### ISSUE TITLE
Writing DateTime to csv file without the Time part.

### ISSUE THREAD

**Issue by dannyboyng** [JoshClose/CsvHelper#414]
I was wondering how to write a DateTime "24-01-1988 0:00:00" to a CSV file without the Time part. I looked through your documentation but could not find an answer.

I tried using ConvertUsing

Map(m => m.Datum_UPDATE).ConvertUsing(row => row.GetField("Datum_UPDATE").Replace("0:00:00", ""));

and

Map(m => m.Datum_UPDATE).ConvertUsing(row => row.GetField\<DateTime\>("Datum_UPDATE").ToString("dd-MM-yyyy"));

but none of them worked. I'm using version 2.13.2.0

**Comment by Orcomp** [comment]
Map(m => m.Datum_UPDATE).TypeConverterOption("dd-MM-yyyy")

**Comment by dannyboyng** [comment]
Thank you. CsvHelper is amazing. It works

**Comment by Oxymoron290** [comment]
@dannyboyng Please close the ticket.
