### ISSUE TITLE
CsvClassMap has to map all fields otherwise they are ignored

### ISSUE THREAD

**Issue by abatishchev** [JoshClose/CsvHelper#419]
Once I register a class map to post process one of the fields I have to map the rest otherwise they will be ignored. It isn't a big deal for small classes but becomes annoying for huge ones.

Is there a workaround here?

**Comment by jamesbascle** [comment]
It's been a while, but I THINK you can do automap, then map the specific
special case ones.

**Comment by abatishchev** [comment]
Is there a special call to perform automapping?  I didn't find any.
My expectation was it'll be performed automatically and then on top of it - my custom logic.

**Comment by jamesbascle** [comment]
Check out this code sample:

````C#
public sealed class SampleClassMap : CsvClassMap<SampleClass>
{
    public SampleClassMap()
    {
        AutoMap();
        Map(m => m.Prop2).Name("SillyCsvName2");
        Map(m => m.Prop3).Name("SillyCsvName3");
    }
}

public class SampleClass
{

    public string Prop1 { get; set; }
    public string Prop3 { get; set; }
    public string Prop2 { get; set; }
}
````

This is much better behavior, since if you didn't want to actually map the entire object, you'd have no way to do that if it automatically mapped everything.

**Comment by JoshClose** [comment]
This also means you can automap, then ignore a couple.

```cs
AutoMap();
Map( m => m.MyProperty ).Ignore();
```

**Comment by abatishchev** [comment]
Awesome, thanks! That's exactly I was looking for.

**Comment by cheesemacfly** [comment]
Old issue (and seen twice https://github.com/JoshClose/CsvHelper/issues/338) but actually only found the solution here. Shouldn't this be part of the documentation? I can create a pull request if you think it's be useful.

**Comment by JoshClose** [comment]
A lot of documentation will be added when version 3.0 is released. I was expecting that to be a month or so ago, but have been very busy. I have a good 100 hour work week this week. :D
