### ISSUE TITLE
Reference class map prefix does not allow me specify the separator - always a period (.)

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#420]
It seems that if I use the Prefix feature, a period (.) is always used as the separator.  It would be great if I could configure that with a custom string.  In my case, I don't want any separator (so I would use empty string).

**Comment by JoshClose** [comment]
This was done at some point. Example here https://github.com/JoshClose/CsvHelper/blob/5b518a95feaa78bdda7687465dae6c4cf9e37c05/src/CsvHelper.Tests/CsvWriterReferenceMappingPrefixTests.cs#L85

If you don't specify a prefix, the default is to use `PropertyName.`.
