### ISSUE TITLE
Comments at the end?

### ISSUE THREAD

**Issue by plettb** [JoshClose/CsvHelper#421]
Does CsvHelper allow me to trim comments at the end of a line?  I've poked around but haven't found a way.  Here is a sample line:
'Field 1',1,0,'My description, which may include a comma or an exclamation mark!' !Comments that I want to trim and ignore, which may also include commas
Presently, with my configuration, that line gets parsed as follows:
    [0]: "Field 1"
    [1]: "1"
    [2]: "0"
    [3]: "My description, which may include a comma or an exclamation mark! !Comments that I want to trim and ignore"
    [4]: " which may also include commas"
That's certainly not what I want!

Thanks!
Brad.

**Comment by JoshClose** [comment]
[RFC 4180](https://tools.ietf.org/html/rfc4180) doesn't specify comments. They are commonly used for a whole line by putting a `#` at the beginning of the line though, so CsvHelper supports commenting a full line out.

If you want to have comments for each line, you could just create a field `Comments` and read that in. If you need it per field, you'd have to have an extra comment field for each field. You could also create your own way of parsing the fields and add comments to them. You can create a custom type converter and pull out the comment info too.

**Comment by plettb** [comment]
Yeah, the application that's producing the files I need to read has not exactly been written to any standards.

OK, looks like I'll have to work this out on my own.

Brad.

**Comment by JoshClose** [comment]
Give a custom type converter a try. You can inherit an existing one, parse out your comment, then pass the rest of the text along to the base to do it's thing.
