### ISSUE TITLE
IgnoreHeaderWhiteSpace - Tabs

### ISSUE THREAD

**Issue by chrisjn52** [JoshClose/CsvHelper#427]
I am a csvhelper newbie so apologies if I have missed something in the docs for this issue.

I have a csv file with Cr,LF,HorizTab at the beginning of the csv file prior to the header information, (0x0d,0x0a,0x09). I have set IgnoreHeaderWhiteSpace = true, but the code fails to find the first column header due to the leading Tab character.

Is there a way of ignoring the leading tab character when using csvhelper?

**Comment by JoshClose** [comment]
Did you figure it out?
