### ISSUE TITLE
CSV with first two Chars being 'ID' will throw an exception in Excel... Known issue.

### ISSUE THREAD

**Issue by TWhidden** [JoshClose/CsvHelper#429]
https://support.microsoft.com/en-us/kb/323626

Just experienced that when I had an export with the first column header ID.

Example:
ID,Name
1,Joe
2,Jack

I suspect the Column or first row, as long as its the first two bytes, will cause Excel to freak out.

**Comment by JoshClose** [comment]
Interesting. Are you suggesting anything for CsvHelper regarding this?

**Comment by TWhidden** [comment]
Might be fun to do a pull request fix, but just changed my column header
for a quick fix.

**Comment by JoshClose** [comment]
It's a valid CSV file though.

**Comment by TWhidden** [comment]
Yep, just an issue opening in excel.

**Comment by igitur** [comment]
CsvHelper should be agnostic to the application which will consume the .csv file. Therefore it's up to the user to ensure that any application specific issues are handled.
