### ISSUE TITLE
Support for DI Resolver

### ISSUE THREAD

**Issue by ravensorb** [JoshClose/CsvHelper#433]
I do a lot of work with frameworks that are heavily based on DI (and design by contract) as a result, most of my objects have collections and references based on interfaces and not concrete classes.  It would be cool if there was a way to define a ContractResolver callback and then have this used prior to a record being created.

**Comment by JoshClose** [comment]
I'm not really following. Can you give me an example or a link?

**Comment by ravensorb** [comment]
Absolutely.

Consider a class structure like this

	public interface IPerson
	{
		string FirstName { get; set; }
		string LastName { get; set; }
		IAddress Address { get; set; }
	}

	public interface IAddress
	{
		string Line1 { get; set; }
		string Line2 { get; set; }
		string Region { get; set; }
		string PostalCode { get; set; }
		string Country { get; set; }
		ILocation Location { get; set; }
	}

	public interface ILocation 
	{
		double Longitude { get; set; }
		double Latitiude { get; set; }
	}

	public class Person : IPerson
	{
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public IAddress Address { get; set; }
	}

	public class Address : IAddress
	{
		public string Line1 { get; set; }
		public string Line2 { get; set; }
		public string Region { get; set; }
		public string PostalCode { get; set; }
		public string Country { get; set; }
		public ILocation Location { get; set; }
	}

	public class Location : ILocation 
	{
		public double Longitude { get; set; }
		public double Latitiude { get; set; }
	}

Notice that Address, and Location are defined as interfaces inside the classes.  Now consider a CsvClassMap like this

	public sealed CsvMapPerson : CsvClassMap<IPerson>
	{
		public CsvMapPerson()
		{
			Map(m => m.FirstName).Name("First Name");
			Map(m => m.LastName).Name("Last Name");
			
			References<CsvMapAddress>(m => m.Address);
		}
	}
	
	public sealed CsvMapAddress : CsvClassMap<IAddress>
	{
		public CsvMapAddress()
		{
			Map(m => m.Line1).Name("Line 1");
			Map(m => m.Line1).Name("Line 2");
			Map(m => m.Region).Name("Region");
			Map(m => m.PostalCode).Name("ZipCode");
			Map(m => m.Country).Name("Country");
			
			References<CsvMapAddress>(m => m.Location);
		}
	}

	public sealed CsvMapLocation : CsvClassMap<ILocation>
	{
		public CsvMapLocation()
		{
			Map(m => m.Longitude).Name("Long");
			Map(m => m.Latitiude).Name("Lat");
		}
	}

Specifically notice the CsvClassMap declarations are using interfacces and so are the calls to "References"

The way I have handled this in other libraries (I did the implementation in Sqlite.NET is to create something like this

	public interface IContractResolver
	{
		/// <summary>
		/// Gets or sets the can create function method.
		/// This function take a <see cref="Type"/> object
		/// </summary>
		/// <value>Returns true if the type can be resolved.  Note, if the default constructor is used, this will always return true</value>
		Func<Type, bool> CanCreate { get; set; }

		/// <summary>
		/// Gets or sets the create function method.
		/// This function take a <see cref="Type"/> object and an array of <see cref="Object"/> items that can be passed to the constructor 
		/// if the resolve supports it.
		/// </summary>
		/// <value>The create.</value>
		Func<Type, object[], object> Create { get; set; }

		/// <summary>
		/// Creates the object.
		/// </summary>
		/// <param name="type">The type.</param>
		/// <param name="constructorArgs">The constructor arguments.</param>
		/// <returns>System.Object.</returns>
		object CreateObject(Type type, object[] constructorArgs = null);
	}

then anyone can implement this interface and it allows for the resolution of an interface to a concrete type using pretty much any DI framework (Autofac, Ninject, etc.)

Here is an example of how it could be used

	ContractResolver = new ContractResolverDelegate(
                (type1) => container.GetResolver().IsRegistered(type1),
		(type2) =>
		{
			var c = container.GetResolver().Resolve(type2);

			return c;
		});

Where 'container' in the above case is an Autofac container.

Does that help?

**Comment by jamesbascle** [comment]
I kind of hacked this functionality in by defining a number of CsvPropertyMaps for each interface, and then dynamically building ClassMaps per type at runtime based on implemented interfaces, and caching them by Type for speed/minimal resource usage.

**Comment by ravensorb** [comment]
I was looking over the code and at first glance, I could see adding the IContractResolver to the CsvConfiguration class and then passing in a reference to it when calling the ReflectionHelper methods.  The one flaw in this is I see that CsvClassMap and CsvClassMap`1 both use ReflectionHelp and do not have access to the CsvConfiguration

**Comment by ravensorb** [comment]
Hmm, that makes sense however that would also require the types to be known and also having access to all of the class implementation at compile time -- that is not always the case with DI frameworks and assemblies can be loaded that contain the concrete implementation at runtime.

**Comment by ravensorb** [comment]
If I went with the CsvPropertyMaps  idea -- is there an easy way to map a interface to a concrete class for a specific property (rather than having to load the type at runtime for every property)?  I ask because I have WAY more the 2 or 3 of these :smile:

**Comment by jamesbascle** [comment]
Hmm.  If you're only interested in partially mapping some classes that implement the interface, and not others, I'm not quite sure how I'd approach it... But I can say that I've got some couple hundred interfaces that I am dynamically building classmaps for concrete implementations of.

I'm extremely comfortable with CsvHelper after ~3 years of use though, so others might characterize what I've done as "abuse"...Works like a charm though.  I wish I could show some code, but I wrote it for the company I work for.

I can point you at my comment in this thread with the GenericCsvClassMap https://github.com/JoshClose/CsvHelper/issues/392 with the addendum of "you can also add a constructor/factory method that will create one based off of a collection of CsvPropertyMaps.

**Comment by ravensorb** [comment]
Ok, I think I actually have a fully working implementation of my idea (I created a fork and added it).  Just need to make sure I have enough unit tests to validate the new functionality correctly :smile:

**Comment by ravensorb** [comment]
Just created a pull request #437 that implements this functionality. Now it is easy to register a contract resolver with the configuration class and then when using CsvClassMap any classes with interface members can be instantiated during load (note the contract resovler can be setup uniquely inside each csvclassmap too if needed)

**Comment by JoshClose** [comment]
I've been looking through this. I want to get this into 3.0 because it'll cause a breaking change.

I don't really like how it intertwined all over the place. I don't like that `ReflectionHelper.CreateInstance` requires it to be passed in. I would rather have calling classes use the resolver or the create instance... though I think that would get really messy. 

It would be nice to have `RefelectionHelper.CreateInstance` be able to just have access to it. Using `ContractResolver.Current` would solve that issue, but I think that's an anti-pattern. I don't see another good way to keep it in the smallest amount of places though. Do you have any suggestions on how to keep the code for this small?

Is there a particular reason you need this pattern? Would it be possible to just have `Func<Type, object[], object> Configuration.ObjectCreator `? I'm guessing you need the `CanCreate` part so that if the resolver can't handle it, it can fall back. Having it on `Configuration` would also mean that `CsvClassMap` wouldn't have a hold of it, and I don't want to start passing that object around. Again, I'm coming back to using something like `ContractResovler.Current`.

I'm going to get this in as soon as possible here. There are way too many merge conflicts due to some major changes that have gone it, that I can't use this pull request anymore. I can take the unit tests and the `IContractResolver` and `ContractResolver` and put it in though.

**Comment by JoshClose** [comment]
What is the point of `CanCreate`? If it's false, `null` gets returned and things will blow up. Should it fall back to using another method of creating the object in this case?

If you're using a IoC container to create the objects, wouldn't you want it to always create them? Wouldn't you want it to configure the container to auto-resolver objects in this case?

**Comment by JoshClose** [comment]
Here is the initial implementation I have. I'd like to remove the `CanCreate` method though. https://github.com/JoshClose/CsvHelper/commit/5e6fe83e50875344e5ab282dfbe8e2b10cffb7e6

**Comment by ravensorb** [comment]
I usually use the "CanCreate" to reduce the overhead of calling the DI to instantiate classes that are not registered.. So what does the framework do if the concrete instance cannot be created do you fall back to the main framework to do a CreateInstance?

**Comment by JoshClose** [comment]
That's my questions too. ;) I would think you'd want the resolver to always do it. Are there any IoC containers that don't have the ability to create default objects that aren't registered?

If we fallback to creating objects that the container doesn't resolve, then I think we're not giving the user the control of what happens. What if we don't use `CanCreate` and let the user use handle the default method? Another option would be to create a config option property of `bool CreateDefault = true` or `AutoResolve` so if `CanCreate` is false, it'll fallback to automatically creating an instance.

**Comment by ravensorb** [comment]
Most of the DI frameworks I have been testing with actually don't things that are not registered -- I have been using ninject and autfac and both will fail if it is not registered.  

With your suggestion, would the resovler return a null to trigger the autocreate?  If so, what would be the difference between a failed creation and just not handling the specific type?

**Comment by JoshClose** [comment]
Ninject and Autofac both have option to have unregistered types resolve though. 

If `CanCreate` returned `false`, it would fallback. If `CanCreate` returns `true`, and the resolver gives back `false`, then things would just blow up. Maybe an `InvalidOperation` exception could be thrown if the resolver returns `null`, because that shouldn't ever happen.

**Comment by ravensorb** [comment]
Thats not a bad idea -- the way it works in Json.NET is that if CanCreate returns false, the resolver is never called (part of keeping performance consistent).  

Note: Are you thinking that consumers would be required to set their DI frameworks to handle unregistered base types in order to use this lib?  What about DI frameworks that do not handle the fallback (granted not sure there are any)

**Comment by JoshClose** [comment]
That's why I was thinking of maybe having an option to fallback that's set to `true` by default, since libraries don't resolved unregistered types by default. That way you'd have to option to let your custom resolver always handle it.

**Comment by JoshClose** [comment]
I added a fallback option that is on by default. Let me know what you think. https://github.com/JoshClose/CsvHelper/commit/e72c58acc04ba885406628e9345b72092c46e976

**Comment by JoshClose** [comment]
I just committed this on the main branch. If there are any changes you think are needed, let me know. 8afd0cd6c33006f627f41da2ccb3fde4c7cabbe2
