### ISSUE TITLE
Mapping one row to multiple objects

### ISSUE THREAD

**Issue by Thealexbarney** [JoshClose/CsvHelper#434]
I'm trying to map one row of a CSV file to two separate objects of the same type.

For example:

```
Columns: A, B, C1, C2, D1, D2
```

Gets mapped to:

```
Object 1: A, B, C1, D1
Object 2: A, B, C2, D2
```

I'm trying to do this cleanly without having to handle it with my own code. Is there a way to do this with mapping?

**Comment by JoshClose** [comment]
You might be able to create a class that has 2 properties on it that are of those 2 types. Set them up as reference maps. You'll need to register the main map file that contains the reference maps.

The other option is to register the 2 maps separately, then just pull them out.

```cs
var list1 = new List<Type1>();
var list2 = new List<Type2>();
while( csv.Read() )
{
    list1.Add( csv.GetRecord<Type1>() );
    list2.Add( csv.GetRecord<Type2>() );
}
```
