### ISSUE TITLE
Determining subclass type to instantiate based on field value

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#435]
Lets say I have an abstract class with two non-abstract subclasses.  I want to parse a file where each record translates to an instance of one of those subclasses.  Lets say the csv file has a field with a string that tells me the name of which subclass the record should be assigned to.  I can do a switch statement on the string to determine concretely which type the record belongs to.  Is this type of situation solvable using CsvHelper?

**Comment by jamesbascle** [comment]
You should be able to do this with an implementation of the ITypeConverter, and setting it up using the TypeConverter extension method while mapping to a property of the abstract base class.  In the type converter you'll get the field text, and can run your custom parsing logic, then simply return whichever subclass of the base is appropriate, populated with the proper data.

**Comment by SurajGupta** [comment]
is there a simple example you can point me to?

**Comment by SurajGupta** [comment]
here's an example csv:

    id,value,type
    1,joe,person
    2,skippy,dog

here are the classes:

    public abstract LivingThing 
    {  
        public Id { get; set;}
        public Name { get; set;}
    }

    public Dog : LivingThing { }
    public Person : LivingThing { }

how do I return a Person for the first row, and a Dog for the second row?

**Comment by jamesbascle** [comment]
Ahh, my apologies, u thought you were talkin about a specific property, not the whole type record type...im not sure what you're saying is directly possible unfortunately, but I'd have to defer to someone else like josh for a definitive answer.

-----Original Message-----

**Comment by JoshClose** [comment]
I don't want to get into the business of automatically pulling different types based on a field key or something. This isn't sql. ;)

Here is how you can do it.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine( "Id,Name,Type");
		writer.WriteLine( "1,joe,person");
		writer.WriteLine( "2,skippy,dog");
		writer.Flush();
		stream.Position = 0;

		var dogs = new List<Dog>();
		var people = new List<Person>();
		while (csv.Read()) 
		{
			var type = csv.GetField("Type");
			if (type == "dog")
			{
				var dog = csv.GetRecord<Dog>();
				dogs.Add(dog);
			}
			else if (type == "person")
			{
				var person = csv.GetRecord<Person>();
				people.Add(person);
			}
		}
	}
}

public abstract class LivingThing
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class Dog : LivingThing { }

public class Person : LivingThing { }
```

**Comment by SurajGupta** [comment]
thanks! good solution.
