### ISSUE TITLE
Adding raw file line number to reader, just as has been done for parser

### ISSUE THREAD

**Issue by KeesDijk** [JoshClose/CsvHelper#436]
Thanks for the nice lib, we find it very useful.

We are reading in a number of files using CsvHelper, the files contain newline characters, that all works great. In our code we first do a count on the linenumbers in the file (so not recordcount but linecount) and set a progressbar maximum to this count. When parsing the file we report progress using the Row field of the CsvReader (this indicates recordcount not linecount) so our progress is reported incorrectly.

I saw that on parser that there is a rawrow and that csvReader uses the parser. When exposing this rawrow through the ICsvParser.cs parser interface it would be enough and we could report progress correctly. In my pull request I also gave the CsvReader a rawrow property that chained to the ICsvParser rawrow. It is a pretty simple change the only problem I see is that the interface ICsvParser.cs is changed and people might have their own implementation, if that is a problem we could also place the rawrow in a separate new interface on CsvParser.

I already created a pull request, sorry I did not read the requirement to create an issue first.  https://github.com/JoshClose/CsvHelper/pull/424/files 
- it is a single commit
- unit test is included
- coding style is kept.

**Comment by JoshClose** [comment]
I would prefer you to do `CsvReader.Parser.RawRow` instead. Do you see any issues with accessing it from the `Parser` property?
