### ISSUE TITLE
Convert Using should provide access to Header Field and Current object

### ISSUE THREAD

**Issue by ravensorb** [JoshClose/CsvHelper#438]
It would useful if the Convert Using would provide access to both the header field and the current object (not the row, but the new object).  This could allow for things like conditional logic on what property is populated.

    Map(m => m.ID).Name("Google", "Bing").ConvertUsing((row, header, obj) => {
       if (header == "Google") obj.Source = "google";
       if (header == "Bing") obj.Source == "bing";

       return row[header];
    });

**Comment by jamesbascle** [comment]
ConvertUsing simply gives you access to the entire row, regardless of the
header.  In fact, there's no reason to even use the Name methods when using
the ConvertUsing method I believe.  A better way might be:

````
.ConvertUsing(r =>
            {
                string result;
                if (r.TryGetField<string>("Google", out result))
                {
                    obj.source = result;
                }
            })
````

**Comment by JoshClose** [comment]
It's not possible to give access to the object. The creation of the object done using expression trees and basically looks like this:

```cs
var row = new MyType
{
    Property1 = "one",
    Property2 = 2
};
```

It sets the properties on creation. There is no way around this, from what I understand.

**Comment by Neutrino-Sunset** [comment]
Is your current documantion for ConvertUsing wrong then? It shows this example:

```
// Convert to field
Map( m => m.Aggregate ).ConvertUsing( m => $"A + B = {m.A + m.B}" );

// Block
Map( m => m.Aggregate ).ConvertUsing( m =>
{
    var field = "A + B = ";
    field += ( m.A + m.B ).ToString();
    return field;
} );
```

If as you say you cannot access the current object this cannot be correct. In testing it doesn't compile due to the fact that 'm' in ConvertUsing is not the current object, but the row.

**Comment by JoshClose** [comment]
There is an overload for reading and writing that have a different signature. The "convert to member" is used when writing, and "convert to field" is used when reading. I should probably make that more clear.
