### ISSUE TITLE
CsvReader.Read() skipping first row

### ISSUE THREAD

**Issue by c5racing** [JoshClose/CsvHelper#440]
I'm not sure this is an issue with the latest release or something incorrect in my code; however, .Read() appears to be skipping the first record.  Here's my code, on my first loop, the current record is always the second row.

```cs
   var csvConfig = new CsvConfiguration
            {
                Delimiter = "^",
                HasHeaderRecord = false,
                TrimFields = true,
                DetectColumnCountChanges = true
            };

var csvConfig = GetCsvConfiguration(dataImportTemplate);
var importFile = new CsvReader(inputFileStream, csvConfig);

while (importFile.Read())
{
     var line= importFile.CurrentRecord;
}
```

**Comment by JoshClose** [comment]
The only reason it would skip is if `HasHeaderRecord = true`. After you create the reader, check what the value of `importFile.Configuration.HasHeaderRecord` is and make sure it's false.
