### ISSUE TITLE
how to use multiple delimiter 

### ISSUE THREAD

**Issue by sadid-khan** [JoshClose/CsvHelper#442]
First i want to thank the creator of this awesome library.

i want to know how can i use multiple delimiter, i used single delimiter before. i didn't find anything about multiple delimiter in doc.

i have a check-box list. user can select option. when user selects a option i pass the delimiters to parse and parse it with the library. for multiple delimiter i pass something like this "\t|,| " ...

i used the string as a single delimiter but got horrible output and didn't find any option to use multiple delimiter. how can i solve it..??

here is my code 

    var qconfig = new CsvConfiguration {Delimiter = delimiter, IgnoreQuotes = false};
    return GetSplit(text, qconfig); ["text is the string"]

    private static string[] GetSplit(string text, CsvConfiguration config)
        {
            var split = new string[] {};
            if (!string.IsNullOrEmpty(text))
            {
                var csv = new CsvReader(new StringReader(text), config);
                csv.Read();
                split = csv.FieldHeaders;
                return split;
            }
            return split;
        }

when user select quote thn 

    var qconfig = new CsvConfiguration {Delimiter = delimiter, IgnoreQuotes = true};
    return GetSplit(text, qconfig); ["text is the string"]

**Comment by KeesDijk** [comment]
Hi sadid-khan,

What exactly do you mean with multiple delimiters ? 
1 a single line can have different delimters : one, "two","three";"four";"five" (delimters : , and ;)
2 a delimter can consist out of multiple characters : "one" ,;" two" ,;"three",;"four" (delimiter ,;)

If you mean 1. I looked at the code and CsvHelper isn't able to do that, the code just expects a single delimiter. Letting the user choose multiple delimters sounds like a pretty generic solution that doesn't give you a lot of control on how the lines are formatted, so this might not be an option but you might be able to do multiple parses e.g. first parse with the , delimiter and than knowing that the last two fields contain the second delimiter parse just these two fileds with the second delimiter.

If you mean 2. you should be able to put in the multiple character delimiter ",;"  

Hope this helps.

**Comment by sadid-khan** [comment]
i meant number 1 and thanks for your answer

**Comment by Jeet-Sumit** [comment]
Number 2 is not working for me.

I am using delimiter : [~}

I have data like `22/11/2016[~}XYZ[PQR[~}ZZZ`
here it splits based on [ and [~] so it looks like
Col 1: 22/11/2016
Col 2: XYZ
Col 3: PQR
Col 4: ZZZ
However, it should be like:
Col 1: 22/11/2016
Col 2: XYZ[PQR
Col 3: ZZZ
Please advice how can i fix it.

**Comment by JoshClose** [comment]
What version are you using? Can you try it in the 3.0 beta?

**Comment by Jeet-Sumit** [comment]
I am using version 2.0. I will try the same in 3.0 beta and come back to you. Is 3.0 beta stable?

**Comment by Jeet-Sumit** [comment]
It worked with v2.16.3.. Thanks for your reply.

**Comment by JoshClose** [comment]
The beta is stable as far as bugs go, but it could have a breaking change at any time. It will probably have at least one more breaking change before release

**Comment by layos** [comment]
Hi, I've the following issue. I cannot know in advance if the input csv has comma or semicolon as separator. As far as I know I can define just one in my CsvConfiguration.Delimiter ('cause it is just a string). Any suggestion?

**Comment by JoshClose** [comment]
You'll have to do it outside of CsvHelper. Maybe read the first 10 or 100 lines and count the number of each. It really depends on the patterns of the files you're getting.

**Comment by layos** [comment]
Thank you for your answer, it is more or less what I did.
