### ISSUE TITLE
Reading British Dates

### ISSUE THREAD

**Issue by HighJumpJohn** [JoshClose/CsvHelper#446]
I'm reading a file with British date formats i.e. "dd/mm/yyyy" on a record by record basis like this:
Do While csv.Read()
       Dim record = csv.GetRecord(Of C_Import_CWS)()
       ...
       ...
Loop
But It is automatically reading them as American date format. How can I change this behaviour.
Can I do something in the mapping to a specific field:
Public NotInheritable Class _Import_CWS_Map
    Inherits CsvClassMap(Of C_Import_CWS)
    Public Sub New()
        Map(Function(m) m.Touchpoint).Index(0)   ----- this is the field I want British dates from
        Map(Function(m) m.Name).Index(1)
        Map(Function(m) m.Code).Index(2)
    End Sub
End Class
Thanks
John

**Comment by jamesbascle** [comment]
You should look at the type converter documentation. Just use one for that
date time format in your class map.

**Comment by HighJumpJohn** [comment]
I did have a look but couldn't find much documentation that I understood! Sorry I'm new to this!
I tried to set it globally like this but it didn't work:
csv.Configuration.HasHeaderRecord = True
csv.Configuration.Delimiter = vbTab
Dim CultureInfo As System.Globalization.CultureInfo = New System.Globalization.CultureInfo("en-gb")
csv.Configuration.CultureInfo = CultureInfo.CurrentCulture
csv.Configuration.RegisterClassMap(Of _Import_CWS_Map)()

any help would be appreciated.

**Comment by HighJumpJohn** [comment]
I also have this in web.config, but agian is doesn't change the behaviour:
    <globalization culture="en-GB" uiCulture="en-GB"/>

**Comment by HighJumpJohn** [comment]
Sorry - this is web.config:    
<globalization culture="en-GB" uiCulture="en-GB"/>

**Comment by JoshClose** [comment]
You should be able to set a [TypeConverterOption](http://joshclose.github.io/CsvHelper/#mapping-type-converter-options) for this.

```cs
Map( m => m.TouchPoint ).Index( 0 ).TypeConverterOption( CultureInfo );
```

**Comment by jamesbascle** [comment]
Hey sorry for not getting back to you before now.  Here's a little sample code for what your type converter could look like

````C#
    public class BritishDateTimeConverter: ITypeConverter
    {
        public object ConvertFromString(TypeConverterOptions options, string text)
        {
            DateTime.ParseExact("25/11/1987","dd/MM/yyyy",null)
        }

        public bool CanConvertFrom(Type type)
        {
            return type == typeof (string);
        }

        public string ConvertToString(TypeConverterOptions options, object value)
        {
            return value.ToString("dd/MM/yyyy");
        }

        public bool CanConvertTo(Type type)
        {
            return type == typeof(string);
        }
    }

````

Your model could look like:

````C#
    public class MuhFakeClass
    {
        public DateTime MuhDate { get; set; }
        public int MuhId { get; set; }
    }
````

And in your CSV ClassMap:

````C#
    public class MuhFakeClassMap
    {
        public MuhFakeClassMap()
        {
            Map(a=>a.MuhDate).Name("MuhDateColumnName").TypeConverter<BritishDateTimeConverter>();
Map(a=>a.MuhId).Name("MuhIdColumnName")        
        }
    }
````

**Comment by jamesbascle** [comment]
Or see Josh's much shorter solution >.>

**Comment by HighJumpJohn** [comment]
Josh
I'm in VB so I've modified my Mapping class & it now looks like this:

Public NotInheritable Class _Import_CWS_Map
    Inherits CsvClassMap(Of C_Import_CWS)
    Public Sub New()
        Map(Function(m) m.Touchpoint).Index(0).TypeConverterOption(CultureInfo)
        Map(Function(m) m.VIN).Index(1)
        Map(Function(m) m.DealerCode).Index(2)
    End Sub
End Class

But Visual Studio tells me "CultureInfo is a class type and cannot be used as an expression"
So I changed it to:
     Map(Function(m) m.Touchpoint).Index(0).TypeConverterOption(CultureInfo.CurrentCulture)

But this doesn't work, it still tries to read the dates as American format.

I'm doing this to try to force the culture correcty - am I doing the wrong thing...
Dim CultureInfo As System.Globalization.CultureInfo = New System.Globalization.CultureInfo("en-gb")
            csv.Configuration.CultureInfo = CultureInfo.CurrentCulture
            csv.Configuration.RegisterClassMap(Of _Import_CWS_Map)()
            csv.Configuration.IgnoreReadingExceptions = True
            Dim mycontext = New RecallContainer()
            mycontext.Configuration.AutoDetectChangesEnabled = False
            mycontext.Database.CommandTimeout = 180
            Try
                mycontext.Database.ExecuteSqlCommand("TRUNCATE TABLE _Import_CWS")
                Dim records = csv.GetRecords(Of C_Import_CWS)()

I know this is something to do with the culture settings because when I run this on UK based server it correctly reads british dates but when I run it on a US configured server it tries to read American dates.

What am I still doing wrong?

**Comment by JoshClose** [comment]
`CultureInfo` is just the type. Change it to `cultureInfo` and use that.

```vb
Dim cultureInfo As System.Globalization.CultureInfo = New System.Globalization.CultureInfo("en-gb")
Map(Function(m) m.Touchpoint).Index(0).TypeConverterOption(cultureInfo)
```
`CultureInfo.CurrentCulture` is the culture that is set on that server.

**Comment by HighJumpJohn** [comment]
That's working :) Thanks Josh
Is there any way to get it to read to web.config file <globalization culture="en-GB"> setting?
The dates in all the files I have to read are British format so it would be nice to have this globally set rather than setting it programmatically as above?

**Comment by HighJumpJohn** [comment]
This is also working for me & it means I don't have to set the culture on each map function...
Dim csv = New CsvReader(sr)
Dim britishculture As System.Globalization.CultureInfo = New System.Globalization.CultureInfo("en-gb")
csv.Configuration.CultureInfo = britishculture
csv.Configuration.RegisterClassMap(Of _Import_CWS_Map)()

**Comment by JoshClose** [comment]
Yes, that should set it globally.

You could put it in web.config, and just have your app pull out whatever is in there.

```cs
var cultureString = ConfigurationManager.AppSettings["Culture"];
var culture = new CultureInfo(cultureString);
```

**Comment by HighJumpJohn** [comment]
OK, thanks very much for the help & thanks to you to jamesbascle for your solution.

**Comment by JoshClose** [comment]
Thanks @jamesbascle for helping with questions all the time. :) It's much appreciated.

**Comment by jamesbascle** [comment]
Hey no problem - CsvHelper has made my life massively easier, I figure it
only right I return the favor every now and then.
