### ISSUE TITLE
Cannot save in windows-1251 charset

### ISSUE THREAD

**Issue by Radzhab** [JoshClose/CsvHelper#448]
i want save data in win1251, but it saved in utf-8

I try make this code, but same result
```
 Encoding encoding = Encoding.GetEncoding("windows-1251");
 row.Configuration.Encoding = encoding;
```

**Comment by JoshClose** [comment]
You need to make the change in your `StreamWriter`.

If you look at the [docs](http://joshclose.github.io/CsvHelper/#configuration-encoding) for that configuration it says:

> The encoding of the CSV file. This is only used when counting bytes. The underlying TextReader and TextWriter will have it's own encoding that is used. 

CsvHelper just reads/writes from the TextReader/TextWriter you give it. It doesn't care about those things.

**Comment by Radzhab** [comment]
thx
