### ISSUE TITLE
Occasional merging of two lines where one is a comment causing failure

### ISSUE THREAD

**Issue by ChangePlaces** [JoshClose/CsvHelper#451]
I'm having a problem when reading in a CSV file where the '#' character is used to denote a comment. 

It seems occasionally two lines are merged together, with the comment line not being omitted and being read in as the first field causing a conversion failure. The CSV file is parsed if I change the order of where the comment is, and there are no special characters other than the comment character in either record.

I'm finding it impossible to replicate reliably outside of my breaking example, which if I cut down to a small test case, succeeds.

May be related #444

**Comment by JoshClose** [comment]
I think this is the same as #444.

**Comment by JoshClose** [comment]
Btw, #444 is fixed an in NuGet.

**Comment by ChangePlaces** [comment]
Wonderful, thanks
