### ISSUE TITLE
Writing Comments

### ISSUE THREAD

**Issue by ab-tools** [JoshClose/CsvHelper#452]
First thanks for this great library!

I see it also supports comments while reading which is good, but I did not find a way to write a comment line. Did I miss something?

Basically I would expect a method like

    WriteComment("Any comment line.")

which then results in a line

    #Any comment line.

being written to the file (where "#" can be changed by "csv.Configuration.Comment").

Is that possible?

Thanks in advance
Andreas

**Comment by JoshClose** [comment]
If you don't have it always quoting, I think you should be able to just 
```cs
csv.WriteField( "#my comment" );
csv.NextRecord();
```
I don't have a way to test this at the moment though.

**Comment by ab-tools** [comment]
Hello Josh,

that works, great, thanks for your very quick reply!

Anyway, maybe you can consider such an addition for the future:
I think it would make it more explicit and also consider the configured comment sign automatically.

But for now that works fine for me.

Thanks again for your great support!
Andreas

**Comment by JoshClose** [comment]
Marked it as a feature request. :)

**Comment by ab-tools** [comment]
Thank you! :-)

**Comment by JoshClose** [comment]
This has been added an will be in NuGet version 3.0.0-beta6.

**Comment by ab-tools** [comment]
Thanks for adding this, Josh! :-)
