### ISSUE TITLE
Ability to skip whitespace only rows before header

### ISSUE THREAD

**Issue by jcfarsight** [JoshClose/CsvHelper#453]
Just a query about the way CsvReader handles blank lines with whitespace with regards to headers.

Let's say I have a file like this (ignore pipes as they are included for readability only):
||
|firstname|surname|
|john|doe|

If I state that headers are included then CsvReader will automatically skip the first row as it's empty and consider the second row the header. This is excellent and I would call that expected behaviour.

Now let's say I have another file like this (ignore pipes as they are included for readability only):
|     |
|firstname|surname|
|john|doe|

Even if I have the SkipEmptyFields, TrimHeaders, IgnoreHeaderWhiteSpace and TrimFields settings all set as true, it still considers the whitespace row as the header. Personally I would call this inconsistent behaviour if whitespace is explicitly set to be ignored right throughout the configuration.

Is there any way to mangle the configuration such that whitespace rows before the header will be ignored or would this need to be a new feature or pre-parse step?

**Comment by JoshClose** [comment]
It doesn't seem possible currently. There is a setting for `ShouldSkipRecord`, but it isn't used on the headers. You would be able to do this
```cs
csv.Configuration.ShouldSkipRecord = row => row.All( string.IsNullOrWhiteSpace );
```
This setting just allows you to specify when to skip a row.

For now, I would suggest manually advancing the position of the stream to the first character that you want to be read by CsvHelper.

**Comment by JoshClose** [comment]
I added this to work with the header record now too. It's been pushed to NuGet as version 2.13.5.

**Comment by jcfarsight** [comment]
Excellent. Thanks for the quick fix!
