### ISSUE TITLE
Parsing shouldn't stop at first error

### ISSUE THREAD

**Issue by gkinsman** [JoshClose/CsvHelper#454]
When parsing a large CSV file, it is sometimes useful to return the specific rows that failed to inform the user where the errors are. Currently, this isn't possible as an exception is thrown on first error.

It should be possible to hold on to a collection of errors, and to then throw.

In order to do this currently, I'd need to handle the exception, parse the error, seek the stream to the row after the error row, and keep reading.

I'm going to attempt this now as I require it in my current work, but I welcome input/guidance on how it should ideally be done :).

Thanks!

**Comment by gkinsman** [comment]
Somehow I missed the IgnoreReadingExceptions configuration setting that provides this behaviour.

Goodo!

**Comment by JoshClose** [comment]
Ok, great!
