### ISSUE TITLE
Add ReadHeader method

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#457]
Add a `ReadHeader` method so the headers can be retrieved before the first row.

**Comment by michaelpinnell** [comment]
Curious as to the status of this feature.

**Comment by JoshClose** [comment]
Still pending. I started a new job where I'm on a Windows machine again, so I'll be able to look over stuff during lunch again. Hopefully I can start clearing out the queue a little.

**Comment by JoshClose** [comment]
This is done.
