### ISSUE TITLE
Problem reading with escaped double quotes

### ISSUE THREAD

**Issue by kfarboud** [JoshClose/CsvHelper#458]
Hi, 

While reading Csv files, some records containing escaped double quotes such as ...,data1,"...""abc""...",data3,...
do not seem to be handled properly as the columns are thrown off. Is there a configuration flag that needs to be set to handle this? We are using CsvReader.GetRecords<T>() after registering a Class Map with the Configuration. Version CsvHelper.2.13.5.0

Thanks

**Comment by phillijw** [comment]
Can you provide a header and a full line as an example?

**Comment by kfarboud** [comment]
Please note the entry (""FDR"") under the ExteriorFeatures that is causing the problem. Once removed the file is read properly:

[SampleFailingFile.txt](https://github.com/JoshClose/CsvHelper/files/48920/SampleFailingFile.txt)

**Comment by JoshClose** [comment]
If you open in Excel, do you see this same undesired behavior?

**Comment by kfarboud** [comment]
The original file is an Excel .csv file (transformed to .txt to upload here) that I can successfully open in Excel. While importing through the application and inspecting in the debugger, I can see that the ExteriorFeatures column is incorrectly mapped such that it only contains the portion of text immediately after the entry (""FDR""). This in turns causes our bulk insertion to fail due to column size mismatches.

**Comment by shinriyo** [comment]
If I use the csv
```
"1","2"
```

result is `"1"` and `"2"`
our hope is just `1` and `2`

**Comment by phillijw** [comment]
Why don't you just use the csv:

    1,2

**Comment by JoshClose** [comment]
Either way, I think this is fixed in 3.0. Running the sample file through the parser I get 53 records for the header and the row. Looking through them, I don't see anything that looks to be broken up.

**Comment by RicardoGarciaM** [comment]
I am experiencing similar problems with CSVHelper 2.16.3. It doesn't consider normal Csv quote escape standards. For example, if input file is:
Tit""l""e,Country
Mr.,""U""SA
output is:
Title,Country
,"U""""SA"
Unfortunately will need for a different Csv reader package.

**Comment by RicardoGarciaM** [comment]
Also seems to have problems with more simple Csv files like:
"User Id","Title"
"29767833","Miss"
the csvReader.GetField(csvColumnIndex) returns random values skipping values
so get output file as 
User Id,Title
0,

**Comment by jamesbascle** [comment]
From what I've seen Josh say in the past, CSV Helper attempts to be an RFC 4180 - compliant csv parser.

According to section 2.7, this is only applicable to quoted fields and is, in fact, the behavior observed according to the following LINQPad snippet.

using (var tr = new StringReader(
@"""Tit""""l""""e"",Country
Mr.,""""""U""""SA"""))
using (var r = new CsvReader(tr))
{
	var records = r.GetRecords<dynamic>();
	records.Dump();
}

**Comment by jamesbascle** [comment]
From what I've seen Josh say in the past, CSV Helper attempts to be an RFC 4180 - compliant csv parser.

According to section 2.7, this is only applicable to quoted fields and is, in fact, the behavior observed according to the following LINQPad snippet.

using (var tr = new StringReader(
@"""Tit""""l""""e"",Country
Mr.,""""""U""""SA"""))
using (var r = new CsvReader(tr))
{
	var records = r.GetRecords<dynamic>();
	records.Dump();
}

![image](https://cloud.githubusercontent.com/assets/4188293/22256679/8693522c-e229-11e6-9ebd-7073da3b1ff2.png)

**Comment by RicardoGarciaM** [comment]
Think my problem is with the writer, what I am trying to do is
`    class Program
    {
        static void Main(string[] args)
        {
            StringBuilder output = new StringBuilder();
            StringBuilder line = new StringBuilder();
            line.AppendLine("\"Tit\"\"l\"\"e\",Country");
            line.AppendLine("Mr.,\"\"\"U\"\"\"\"S\"\"\"\"A\"\"\"");
            using (var tr = new StringReader(line.ToString()))
            using (var r = new CsvReader(tr, new CsvHelper.Configuration.CsvConfiguration
            {
                HasHeaderRecord = false,
                IgnoreQuotes = true
            }))
            using (var streamWriter = new StringWriter(output))
            using (var csvSerializer = new CsvSerializer(streamWriter))
            using (var w = new CsvWriter(csvSerializer))
            {
                while (r.Read())
                {
                    foreach (var v in r.CurrentRecord)
                    {
                        w.WriteField(v);
                    }

                    w.NextRecord();
                }

                Console.WriteLine(output.ToString());
            }

            Console.ReadLine();
        }
    }
}`
Duplicating all quotes
![image](https://cloud.githubusercontent.com/assets/20797208/22260540/789b1262-e261-11e6-8ffc-d4bd9d54221d.png)
