### ISSUE TITLE
Get Records grouped by an identifier

### ISSUE THREAD

**Issue by Romanx** [JoshClose/CsvHelper#461]
Hi there,

I'd had a search so couldn't find anything so I thought i'd open an issue as you seem rather active. I had a case where I had a CSV which contained Parent -> Child with duplicated data on each child line like so:

| Field A | Field B | Field C |
| --- | --- | --- |
| 1000 | ABC | 123 |
| 1001 | ABC | 123 |
| 1001 | DEF | 555 |

What I wanted in code was a List of Parents (T) who would have a property with a List of Children (C). Which in JSON would look like this

``` json
[
    { "fieldA": 1000, "children": [{ "fieldB": "ABC", "fieldC": 123 }] },
    { "fieldA": 1001, "children": [
        { "fieldB": "ABC", "fieldC": 123 },
        { "fieldB": "DEF", "fieldC": 555 }
    ] },
]
```

I've written extension methods to do this for my use case but I wondered if you'd be interested in a pull request with the functionality. 

Currently I've got a helper that does it lazily using yield and calling `Read()` and only yielding a _new_ parent value and assigns the children to the parent. This only works when the child rows are following their parent row.

I have another helpers that accounts for the other case but isn't lazy and reads all items into memory and looking for historical parents to aggregate with but this uses a list in memory to remember what it's seen before.

I'd be happy to share the implementation of these helpers if you'd be interested.

**Comment by JoshClose** [comment]
That seems like a very specific use case. I'd like the library to stay a little more generic.

I'm mentioned this before but no one has done it yet. Someone should start a contrib project to put extension methods and other helper functionality that I think doesn't belong in the core library.

I'll mark this one as another feature for a contrib project, if one gets started.

**Comment by Romanx** [comment]
Hey there,

Thanks for the response. I may take a look at creating a contrib project then with your blessing. I think you're right about it not necessarily being a mainstream usecase. Do you mind if i leave this issue open until I create the contrib and so other people can feed in?

**Comment by JoshClose** [comment]
I just created one and invited you to it.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#3
