### ISSUE TITLE
Incorrect Platform chosen by nuget in new VS2015 Projects

### ISSUE THREAD

**Issue by richardlawley** [JoshClose/CsvHelper#463]
When CsvHelper is added to a project using Visual Studio 2015's new project system, adding the CsvHelper nuget package seems to reference the wrong platform DLLs.  I'm aware there's no support for .NET Core yet, but that's not what this is about.

Steps to reproduce:
1.  Create a new project - either "Console Application (Package)", or one of the ASP.NET 5 projects.  I've done this targeting 4.5.2 and 4.6.1.
2.  Add CsvHelper: `Install-Package CsvHelper`
3.  Remove the "dnxcore50" section from project.json
4.  Add the following code somewhere: 
`new CsvReader(new StringReader("")).GetRecords(typeof(string));` 
(This is nonsense code, but it's a minimal example which SHOULD compile, but will not because GetRecords is not present).

Upon examining project.lock.json, it appears the net20 platform has been referenced:

    "DNX,Version=v4.5.1": {
      "CsvHelper/2.13.5": {
        "type": "package",
        "compile": {
          "lib/net20/CsvHelper.dll": {}
        },
        "runtime": {
          "lib/net20/CsvHelper.dll": {}
        }
      }
    },

Upon changing `net20` to `net40-client` in this file, the code then compiles again (this is undone if another nuget package is added).

I believe something must be wrong in the nuget spec for this to be being picked up incorrectly.

**Comment by JoshClose** [comment]
This is more than likely an issue in dnx somewhere, as it works fine with "normal" .net project. There is an issue submitted to the dnx team already. https://github.com/aspnet/dnx/issues/3205

**Comment by brucetp** [comment]
Here's a work around.   Copy the "C:\Users\[your username]\.dnx\packages\CsvHelper\2.13.5\lib\net40-client" folder to "C:\Users[your username].dnx\packages\CsvHelper\2.13.5\lib\dnx451".  Then Uninstall and reinstall using Package Manger.   It should pick up the .dnx version.  It's worked for me multiple times.

**Comment by JoshClose** [comment]
CsvHelper has support for .NET Core now and doesn't have a client profile build anymore, so this should be fixed.
