### ISSUE TITLE
Support for immutable classes with C#6 auto properties

### ISSUE THREAD

**Issue by mkorz** [JoshClose/CsvHelper#464]
First of all - big thanks for creating the CsvHelper, it is really a fabulous tool for anyone dealing with CSV files.

As for the question - is there a way to convert CSV to a immutable class which utilise C#6 auto properties? 
It currently throws *"No properties are mapped for type '...+Immutable'"* exception in
`CsvReader.CanRead(CsvHelper.Configuration.CsvPropertyMap)` as it cannot find a setter and therefore it ignores the property entirely.

Here is the failing unit test which tries to convert to `Immutable` class.
```c#
        [TestMethod]
        public void CanConvertToImmutableClass()
        {
            var queue = new Queue<string[]>();
            queue.Enqueue(new[] { "Number" });
            queue.Enqueue(new[] { "7" });
            queue.Enqueue(null);
            var parserMock = new ParserMock(queue);
            
            var csv = new CsvReader(parserMock);
            csv.Configuration.RegisterClassMap<ImmutableMap>();
            
            var records = csv.GetRecords<Immutable>().ToList();

            Assert.IsNotNull(records);
            Assert.AreEqual(1, records.Count);
            Assert.AreEqual(7, records[0].LuckyNumber);
        }

        public sealed class Immutable {
            public int LuckyNumber { get; }

            public Immutable(int luckyNumber)
            {
                LuckyNumber = luckyNumber;
            }
        }

        public sealed class ImmutableMap : CsvClassMap<Immutable> {
            public ImmutableMap()
            {
                Map(m => m.LuckyNumber).Name("Number");
            }
        }
```

**Comment by JoshClose** [comment]
I'll have to think about this. In general, it should use a public API, so setting private auto fields shouldn't be a thing. Maybe having a setting to use a constructor parameter would be the way for this to work.

**Comment by JoshClose** [comment]
#416 will cover this if I decide to do it. I will be looking into it more soon here.
