### ISSUE TITLE
Missing column reader

### ISSUE THREAD

**Issue by altohr** [JoshClose/CsvHelper#468]
Hello

I was just seeing this library. I would love to read Columns from some measurement series.
But this library only seems support rows. Is there any support for reading columns?

Regards,
Andi

**Comment by JoshClose** [comment]
I'm not sure I understand. Can you give an example of what the data looks like?

**Comment by altohr** [comment]
Here is a Table of a possible .csv file.
I already made an own reader but it would be handy if there is some advanced library to read such data and put it in different entities.

Current | Voltage
------------ | -------------
0.01 | 4.9
0.011 | 5.1
0.85 | 4.9
0.73 | 5.1
0.732 | 4.9
0.731 | 5.1

**Comment by JoshClose** [comment]
What is the ending object structure that you'd like?

**Comment by JoostvdB94** [comment]
I agree, I'm missing a way to read an entire column by header name or index. In a way that i get an array with the values of all rows in that column. 

for example:
|   Name   |   Age   |
|   John   |   24   |
|   Mike   |   27   |
|   Elsa   |   31   |

could become an array when asking for the "Name"-column:
`["John","Mike","Elsa"]`

**Comment by JoshClose** [comment]
That's not something I'm planning on supporting. You should be able to do this pretty easily using LINQ after you're read the data though.

```cs
var records = csv.GetRecords<Person>().ToList();
records.Select( r => r.Name ).ToArray();
```
