### ISSUE TITLE
Is it possible to have a property as part of multiple sets?

### ISSUE THREAD

**Issue by ravensorb** [JoshClose/CsvHelper#471]
Consider the following idea below.  

It is setup to have 2 properties that can always be supplied (Start/End Date), one property that can be supplied with the "file" and the "filter1" set, and then 1 property for the "filter1", 1 property for the "filter2" and 1 property for the "file" set.  Is this possible?

    public class Opts1
    {
        [Option('s')]
        public DateTime StartDate {get; set;}
        [Option('e')]
        public DateTime EndDate {get; set; }

        [Option('n', SetName = "file;filter1")]
        public string Name { get; set;}

        [Option('a', SetName = "filter1")]
        public int Age { get; set; }

        [Option('i', SetName = "filter2")]
        public string ID { get; set;}

        [Option('f', SetName = "file")]
        public string InputFile {get; set;}
    }

**Comment by JoshClose** [comment]
Are you reading or writing?

**Comment by ravensorb** [comment]
Reading from the command line

**Comment by JoshClose** [comment]
You can use `ConvertUsing` to combine multiple columns into a single property. http://joshclose.github.io/CsvHelper/#mapping-convert-using

**Comment by ravensorb** [comment]
rats! I posted this on the wrong issues list (had too many windows open).  Sorry about that!

**Comment by JoshClose** [comment]
lol, no problem

**Comment by DiWiWeinmannEmt** [comment]
Hey, this is closed, but if I would like to not only read say a DateTime from two columns, but have to write it, too? How could I get the names for the header right?
because `Index()` may take a start and an end value, but `Name()` uses the first element of the array for each column when writing.
