### ISSUE TITLE
Make it possible to control construction #63 - Possible tweak?

### ISSUE THREAD

**Issue by alexhopeoconnor** [JoshClose/CsvHelper#475]
ConstructUsing() works great, but I was wondering if it would be possible to provide more of a factory function then strictly a constructor expression.

`ConstructUsing(() => new MyModel());`

Works fine, however it would be handy to be able to specify a function as follows also:

`ConstructUsing(() => new MyModel() { Property1 = value, Property2 = value });`

This would allow for mapping to be easily fine tuned on classes where I may not be able to make modifications to the constructor, but require some property values to be initialized before mapping takes place.

**Comment by alexhopeoconnor** [comment]
I should have also explained the second example throws the following argument exception:
Not a constructor expression.
Parameter name: expression

**Comment by JoshClose** [comment]
Yeah, the second one is a `MemberInitExpression`. The expression tree I build from the mappings ends up being a `MemberInitExpression` actually. I just did this while trying to add a parameter of `ICsvReaderRow` in the lambda expression. I wasn't able to get it working with the param, but I'm pretty sure what you're asking should work just fine.

**Comment by JoshClose** [comment]
This is done and in version 3.0. It will be in version 3.0-beta8 on NuGet also.

**Comment by alexhopeoconnor** [comment]
Legend, thank you so much for actively maintaining this project, I have not used it in very many of my projects personally but this is always the first library I think of when reading CSV data from file.
