### ISSUE TITLE
Incorrect Field Count for Variable Column CSV

### ISSUE THREAD

**Issue by fungus1487** [JoshClose/CsvHelper#476]
Hello I have a variable column CSV, it appears that the FieldCount property on the CsvParser is set for the first record (I believe linked to this issue #102), this means I receive row data with too many columns for subsequent rows, an example shown below:

    CSV
    "abc","123","hello","world"
    "def","456"

the Read function on CsvParser then returns something like the following:

    var parser = new CsvParser ...
    
    string[] row1 = parser.Read();
    // This looks like:
    // string[] { "abc", "123", "hello", "world" }

    string[] row2 = parser.Read();
    // This looks like:
    // string[] { "abc", "123", null, null }

You can see that extra elements are added to the array with null value.

Is there are way to force the parser to recalculate the FieldCount per row?

**Comment by TheSentry** [comment]
I also would like this functionality. As it is now, the parser only increases the FieldCount, but never decreases it.

Sadly, this makes this library hard to use with variable column CSV files

**Comment by JoshClose** [comment]
Version 3.0 works the way you want. The parser will return an array of the exact data, which means the array size will go up or down for every row without returning nulls.
