### ISSUE TITLE
CsvHelper fluent class mapping ConstructUsing() ignored in referenced maps?

### ISSUE THREAD

**Issue by alexhopeoconnor** [JoshClose/CsvHelper#477]
Hello,

I have been having problems using the fluent class mappings and ConstructUsing() in referenced maps, after looking through the documentation I ended up posting the following question on SO:
http://stackoverflow.com/questions/34911419/csvhelper-fluent-class-mapping-constructusing-ignored-in-referenced-maps

If I am doing something incorrect in my configuration, could the documentation perhaps be updated with some more advanced examples of referencing other class maps?

Thanks,
Alex.

**Comment by JoshClose** [comment]
Taking a quick look at the source (as I don't have a computer to test it on at the moment), it looks like that isn't implemented, but should be a pretty quick thing to do.

**Comment by alexhopeoconnor** [comment]
Thanks man, I tried to reference the source code directly in my solution by referencing the CsvHelper project to debug this but it kept complaining about the .nuget folder not being in the right place. Will have another crack at debugging myself if I run into any more issues, but great library, really easy to use and quick to learn.

**Comment by JoshClose** [comment]
...now finding time to actually do it is another story. Sorry this has taken so long. 

I'm trying to get through most of the backlog for the version 3 release and I'll get this in.

**Comment by JoshClose** [comment]
This is done an in version 3.0. It will be a part of 3.0-beta8.
