### ISSUE TITLE
TrimUnquoted setting for CsvParser

### ISSUE THREAD

**Issue by TheCycoONE** [JoshClose/CsvHelper#479]
While it violates the RFC I find a lot of people submit CSVs with a space after the delimiter. For my use I have to maintain compatibility with older non-conforming CSV parsers because we have too many customers submitting their own hand / machine crafted CSVs. I was able to do that with LumenWorks but not with CsvHelper.

To that end I think a TrimUnquoted setting that is passed down to the parser would be helpful. Alternatively if the parser could tell me if a particular field was quoted or not I could apply the trim myself.

As the spec says: "Implementors should "be conservative in what you do, be liberal in what you accept from others"  when processing CSV files."

**Comment by JoshClose** [comment]
Does this setting not work in your case? http://joshclose.github.io/CsvHelper/#configuration-trim-fields

**Comment by TheCycoONE** [comment]
Unfortunately not as it also trims quoted fields. What I need is equivalent to: https://github.com/phatcher/CsvReader/blob/master/code/LumenWorks.Framework.IO/Csv/ValueTrimmingOptions.cs#L19

They perform the trim early in the parser so it would solve #422 as well. (https://github.com/phatcher/CsvReader/blob/master/code/LumenWorks.Framework.IO/Csv/CsvReader.cs#L1222)

**Comment by IanYates** [comment]
The distinction makes sense - if someone puts a space at the start of a quoted string, as in
`"blah"," prefixed_by_a_space"`
they really mean it, versus
`blah, just_another_value`

I think
`"blah", " prefixed_by_a_space"`
(note the space after the comma) should be able to have that leading space preserved due to the space in the quotes but the space after the comma should be ignored.

**Comment by TheCycoONE** [comment]
I have no idea why I closed this issue.

**Comment by JoshClose** [comment]
The default reading of malformed fields is to handle it like Excel does.
```
"one", "two", " three"," four"
```
gets interpreted as
```
one, "two", " three", four
```

**Comment by JoshClose** [comment]
Does trim unquoted trim everything before a quote, and trim quoted trims inside quotes? 

ex:
1. Unquoted ` " one"` -> ` one`
2. Quoted: ` " one"` -> ` one`
3. Both: ` " one"` -> "one"

1. The space before and after quotes are trimmed.
2. Only spaces inside the quotes are trimmed.
3. Both are trimmed.

**Comment by TheCycoONE** [comment]
@JoshClose The (simplified) rules of LumenVox are:
```
If TrimUnquoted: ignore until first non-whitespace
If first remaining character is a quote:
  skip the quote
  If TrimQuoted: ignore until first non-whitespace
  Read until unescaped quote into field value
  If TrimQuoted: discard whitespace at the end of fieldvalue
  ignore until next delimiter
Else
  Read until next delimiter into field value
  If TrimUnquoted: discard whitespace at end of fieldvalue
EndIf
```

So for your examples
```
1. Unquoted ` " one"` -> ` one`
2. Quoted:  ` " one"` -> ` " one"`
3. Both:    ` " one"` -> `one`
```
On the other hand:
```
Quoted: `" one"` -> `one`
```

**Comment by JoshClose** [comment]
I will have to move all trimming into the parser, which should actually speed things up a little. I'll have a setting similar to the one you posted. This is ugly functionality, but sounds like it'll help a lot of people.

**Comment by JoshClose** [comment]
Done. b2c1f2bd2e085e3a454681cd78fffd5b47945e32
