### ISSUE TITLE
Check the Length of a field.

### ISSUE THREAD

**Issue by NRV90** [JoshClose/CsvHelper#480]
Hi.

I am currently trying to read a csv file and I am trying to limit the length of a field to a certain number of characters. Eg: Column "Description" must have all the values smaller than 300 characters. Is there a configuration I am missing ? 
` Map(m => m.Description)
                        .Name("Descritpion");` (limit length)

Thank you.

**Comment by JoshClose** [comment]
What do you want to happen if the field has more than 300 characters?

**Comment by NRV90** [comment]
Hi,

If the limit is exceeded I would like to either throw it as a reading exception or treat it in the reading callback.

Thank you.

**Comment by JoshClose** [comment]
Will `ConvertUsing` work for you? http://joshclose.github.io/CsvHelper/#mapping-convert-using

You could do the check there and do whatever if it's too large, or just return what you want if it's valid.

**Comment by NRV90** [comment]
Hi Josh,

Thank you for you swift response. `ConvertUsing` will work just fine in my case.

**Comment by hellboy81** [comment]
Is there possible to extend `StringConverter` which acceptscustom option to  `limit` string length?

**Comment by jamesbascle** [comment]
You could certainly do it yourself with a custom converter.

**Comment by hellboy81** [comment]
Actually I am still don't understand how to provide `limit` parameter to custom converter:

This code has issue with specifing `limit` param

```c#
public class TrimmedTextConverter : StringConverter
    {
        private int limit;

        /// <summary>
        /// Issue: How can I speciy limit as optional field param
        /// </summary>
        /// <param name="limit">Optional max string length</param>
        public TrimmedTextConverter(int limit = 0)
        {
            this.limit = limit;
        }

        public override string ConvertToString(TypeConverterOptions options, object value)
        {
            // TODO call truncate only if limit >0
            string truncatedString = value.ToString().Truncate(limit);

            return base.ConvertToString(options, value);
        }
    }
```

**Comment by jamesbascle** [comment]
Just new it up and add it to your map in the class map constructor.

**Comment by hellboy81** [comment]
Please provide mor info

**Comment by jamesbascle** [comment]
Yes.  That is the correct way to go.  A type converter instance for every field/property.  The is no other way to specify.

You can always, of course, store the data in configuration of some sort, be it code, .config, a resource file, etc. and load it up at runtime to build your class maps, but that is outside the scope of this question, and I'm not sure it would make your use case too much simpler unless you anticipate frequently changing those settings.

**Comment by hellboy81** [comment]
OK, constructor injection should be prefered over "property" usage.

In real world export scenarious there are no perfomance bottlenecks  with using 100..256  converter instanes.

**Comment by haggis777** [comment]
I think some kind of attribute that could be added to the property of the item in the model would be the right way to go, that way using reflection you could just check it at read time but that's my opinion.
