### ISSUE TITLE
TryGetField with DateTimeConverter returns false for empty/null value even when output type is nullable

### ISSUE THREAD

**Issue by sparebytes** [JoshClose/CsvHelper#484]
https://github.com/JoshClose/CsvHelper/blob/9b78078ade1a76069d7bf57a043146abef460b0d/src/CsvHelper/CsvReader.cs#L729

Before returning false, we should check that `T field` isn't nullable. If it is nullable, then returning null for an empty value is okay and it should return true.

```
public virtual bool TryGetField<T>( int index, ITypeConverter converter, out T field )
{
	CheckDisposed();
	CheckHasBeenRead();

	// DateTimeConverter.ConvertFrom will successfully convert
	// a white space string to a DateTime.MinValue instead of
	// returning null, so we need to handle this special case.
	if( converter is DateTimeConverter )
	{
		if( StringHelper.IsNullOrWhiteSpace( currentRecord[index] ) )
		{
			field = default( T );
			return false;
		}
	}

	// ...
}
```

**Comment by JoshClose** [comment]
This should actually be done in the converter. That code was written before CsvHelper used it's own custom type converters.

I removed the code you posted completely. I also removed the part in the converters that would turn a string of spaces into `MinValue`, and now spaces will cause an exception to be thrown. This aligns more with all the other converters, but diverges from what the .NET Framework converters do. I think it's odd how the .NET ones work. If you can think of a good reason spaces should convert to `MinValue`, let me know.

For the `TryGetField` a `DateTime?` of `string.Empty` will give back a `true` and value of `null`, but any amount of spaces will give back a `false` and `null` value.
