### ISSUE TITLE
Prevent auto-conversion of DateTime

### ISSUE THREAD

**Issue by StampedeXV** [JoshClose/CsvHelper#486]
I have a string containing a date&time (26-Feb-2016 12:59:11.212). I write this to CSV-file using CsvWriter. 
Open CSV in Excel, it shows in cell 59:11.2 - although behind it still has it as a date (although formatted to default Excel (02/26/2015 12:59:11)).
Save to same csv.
Read with CsvReader.
Save with CsvWriter again, and it is really 59:11.2.

When I used my custom-CSV code, I just did the same CsvHelper does for numbers with leading zeros: ="26-Feb-2016 12:59:11.212". 
How about adding an option to use this format for all Fields & Records?

**Comment by lempface** [comment]
Is Excel changing the data when you save the file? I would examine the CSV in Notepad++ or similar. You can write a custom type converter and have it surround your value in quotes.

**Comment by StampedeXV** [comment]
Excel automatically converts it.
I can prevent this, in putting the datestring in ="DATESTRINGHERE", same as for the numbers with leading zeroes. 
Quotes do not change anything really, as Excel just ignores them for this case.

**Comment by lempface** [comment]
So if you surround the field in quotes then it works properly? You can use the configuration property QuoteAllFields to force all fields to be quote surrounded.

Quote All Fields
A flag that tells the writer whether all fields written should have quotes around them; regardless if the field contains anything that should be escaped. Both QuoteAllFields and QuoteNotFields cannot be true at the same time. Setting one to true will set the other to false.

// Default value
csv.Configuration.QuoteAllFields = false;

**Comment by StampedeXV** [comment]
Hi,

no, setting QuoteAllFields to true doesn't affect behavior in any way. This means Excel still treats everything it recognizes as valid date as date and converts it accordingly.
I want to prevent this as I don't want Excel to change my date formatting/content.

**Comment by lempface** [comment]
Okay, I think your issue is in the way excel handles csv data, not the way CsvHelper handles csv data. 

Can you use QuoteAllFields in conjunction with a TypeConverter that adds quotes around your date when saving to file and removes them prior to attempting to turn back into a DateTime?

I just tried creating a csv that looked like this: 
26-Feb-2016 12:59:11.212,26-Feb-2016 12:59:11.212,"""26-Feb-2016 12:59:11.212""" 

The 3rd column there renders as "26-Feb-2016 12:59:11.212" in excel (including quotes).

If you leave more information on the workflow of your users I can try to help more. Explain why the file is opened and edited in excel and saved again only to be read by CsvHelper later.

**Comment by JoshClose** [comment]
I can add the leading equals as an option for any field.

**Comment by StampedeXV** [comment]
Hi Josh,
that would be great. I tested a little on my own and it seems this doesn't work on "multiline"-fields. 

Thank you

**Comment by imranmahmood** [comment]
Hi Josh,

Is this feature done and available in latest version?  https://github.com/JoshClose/CsvHelper/labels/feature

**Comment by JoshClose** [comment]
No, it's still open.

**Comment by imranmahmood** [comment]
@JoshClose : when we can expect? Thanks

**Comment by JoshClose** [comment]
It'll be a bit. It's definitely behind some critical bugs that are out there right now.

**Comment by JoshClose** [comment]
All Excel functionality is being moved out into a contrib library so CsvHelper core can just focus on CSV.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#9
