### ISSUE TITLE
Support variable length whitespace as delimiter

### ISSUE THREAD

**Issue by chmartisoftware** [JoshClose/CsvHelper#488]
Is this a scenario that is already covered? If so, sorry about filing a feature request, but how do you do it? Other parsers i've seen support using "" as the delimiter to mean any amount of whitespace.

**Comment by JoshClose** [comment]
That is currently not supported.

**Comment by chmartisoftware** [comment]
Man, thanks for the almost immediate reply. Feel free to close this if you've got another request already, or treat this a new feature request. Thanks!

**Comment by JoshClose** [comment]
For now you can do this and it will work roughly the same way.

```cs
csv.Configuration.Delimiter = " "; // one space
csv.Configuration.TrimFields = true;
```

I'm not sure how I feel about this feature though. What sort of scenario requires this? It's such a badly malformed CSV file.

**Comment by JoshClose** [comment]
I don't think this is something I want to do at this time.
