### ISSUE TITLE
First cell in quoted pipe delimited file has enclosing quotes.

### ISSUE THREAD

**Issue by liamhughes** [JoshClose/CsvHelper#490]
Hello,

We are using CsvParser to read in the attached file.

```cs
var csvConfig = new CsvConfiguration();
csvConfig.Delimiter = "|";
using (var csvParser = new CsvParser(strReader, csvConfig))
{
    var row = csvParser.Read(); // ["﻿\"Col1\"", "Col2", "Col3", "Col4", "Col5"]
// ...
}
```

The library appears to be correctly ascertaining that it is quoted, but not until it gets to the second cell?

[Sheet1.txt](https://github.com/JoshClose/CsvHelper/files/164672/Sheet1.txt)

**Comment by liamhughes** [comment]
Solved it.

Before my code snippet, we were performing the following on the StreamReader:

```cs
strReader.DiscardBufferedData();
strReader.BaseStream.Seek(0, SeekOrigin.Begin);
strReader.BaseStream.Position = 0;
```

Removing this solves the issue.

**Comment by JoshClose** [comment]
Great! I was just about to test that out.

**Comment by liamhughes** [comment]
Thanks. Glad I didn't waste too much of your time. :-)

**Comment by JoshClose** [comment]
I figured there was some sort of stream manipulation that was causing it. The parser has a lot of tests around it.
