### ISSUE TITLE
Cannot properly read values with quotes and "=" sign in format: "=""0001"""

### ISSUE THREAD

**Issue by AlexBar** [JoshClose/CsvHelper#492]
I have to parse the file in the following format:

```
"=""Type""","=""Member ID""","=""Date""","=""UID"""
C,10000A,"=""10/01/2014""","=""01289871"""
```

Excel can successfully get that format but I have an issue with csv helper. CsvReader.GetRecords<> throw an error that header "Type" is not found. If I don't use header, I can read values as strings. But I get from **"=""01289871"""** => **="01289871"** instead of expected **01289871** (like Excel does)

Can CsvHelper support this type of formatting?

Thanks,
Alexey

**Comment by JoshClose** [comment]
I'm striving for Excel compatibility and I think I can see a pattern on what they're doing there, so I'll add this. 

I've seen some inconsistencies across versions of Excel with CSV compatibility also. If the CSV is malformed, Excel isn't guaranteed to do the same thing across versions.

**Comment by JoshClose** [comment]
That format is like it's double encoded too. This isn't going to be a fun one. :P

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#4
