### ISSUE TITLE
Can reuse a single instance on GetRecords iterations ?

### ISSUE THREAD

**Issue by eric-b** [JoshClose/CsvHelper#493]
Hi,

Thanks for that great lib.
I was wondering if CsvHelper does support the reuse of a same instance while iterating over GetRecords<T>() ? I looked for it and I suppose it's not the case.

For an example, you can take a look at [protobuf-net Deserialize method](https://github.com/mgravell/protobuf-net/blob/master/protobuf-net/Meta/TypeModel.cs#LC566). 

I have a CSV file with millions of rows to parse and to bulk insert in a database. It's a little waste to create a new class on each row.

Thanks again

**Comment by JoshClose** [comment]
Is it faster to reuse a single class? If so, do you have a link to some benchmarks or something?

In a "normal" case, people get more than a single record at a time. The only time I can think of that you wouldn't is if your streaming the data. I would think even during a bulk insert that you'd be building up a large set of data or something, but I guess that depends.

**Comment by eric-b** [comment]
Well, I don't have a benchmark right now. I can take some time to make a profiled example with and without instance reuse (not exactly a reliable benchmark).

I think the normal use case really depends on the kind of file people want to process. On a small file, it make sense to load it into memory before processing it. On a big file, I really think it's not the normal case because you definitely do not want to load gigabytes of data into RAM to parse it. Also, that's probably why you've implemented `IEnumerable<MyClass> GetRecords<MyClass>()` and not `MyClass[] GetRecords<MyClass>()`.

My use case is exactly as you said to stream data from a CSV file, parse it row by row, and insert each row into database via bulk insert. A similar use case would be to serialize data in another form. So at any time of the import, I really use a single row at a time. Previous rows are garbage.

Typical code:

```

var db = new MyDatalayer(...);

using (var fs = File.Open(path, FileAccess.Read, FileShare.Read))
using (var sr = new StreamReader(fs))
using (var csv = new CsvHelper(sr))
using (var cx = db.OpenConnection())
{
	// BulkCopy is an extension method (cf. Insight.Database).
	cx.BulkCopy("myTable", csv.GetRecords<MyClass>());
}

```

I understand that all data is not loaded into RAM because GC will do its job well enough. But I think it's a little waste of resources.

Other libraries support this technique. Protobuf-net and Lucene are some examples. For Lucene, you can take a look at this [tips page](http://wiki.apache.org/lucene-java/ImproveIndexingSpeed):
> Re-use Document and Field instances As of Lucene 2.3 there are new setValue(...) methods that allow you to change the value of a Field. This allows you to re-use a single Field instance across many added documents, which can save substantial GC cost.

**Comment by JoshClose** [comment]
If you can find some evidence that it's faster, I'll think about it.

This is completely anecdotal, but I did a little test.

```cs
void Main()
{
	var iterations = 100000000;
	Test t = new Test();

	var stopwatch = new Stopwatch();
	stopwatch.Start();
	for (var i = 0; i < iterations; i++)
	{
		t = new Test
		{
			Id = 1,
			Name = "one",
			Unique = Guid.NewGuid(),
			Prop1 = "prop1",
			Prop2 = "prop2",
			Prop3 = "prop3"
		};
	}
	stopwatch.Stop();
	stopwatch.Elapsed.Dump();
	
	stopwatch.Restart();
	for (var i = 0; i < iterations; i++)
	{
		t.Id = 1;
		t.Name = "one";
		t.Unique = Guid.NewGuid();
		t.Prop1 = "prop1";
		t.Prop2 = "prop2";
		t.Prop3 = "prop3";
	}
	stopwatch.Stop();
	stopwatch.Elapsed.Dump();
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public Guid Unique { get; set; }
	public string Prop1 { get; set; }
	public string Prop2 { get; set; }
	public string Prop3 { get; set; }
}
```
```
00:00:33.4377005
00:00:32.4682717
```
Not creating a new one is slightly faster.

Now if I clear the properties each time, like I would assume would have to be done.
```
void Main()
{
	var iterations = 100000000;
	Test t = new Test();

	var stopwatch = new Stopwatch();
	stopwatch.Start();
	for (var i = 0; i < iterations; i++)
	{
		t = new Test
		{
			Id = 1,
			Name = "one",
			Unique = Guid.NewGuid(),
			Prop1 = "prop1",
			Prop2 = "prop2",
			Prop3 = "prop3"
		};
	}
	stopwatch.Stop();
	stopwatch.Elapsed.Dump();
	
	stopwatch.Restart();
	for (var i = 0; i < iterations; i++)
	{
		t.Id = default(int);
		t.Name = default(string);
		t.Unique = default(Guid);
		t.Prop1 = default(string);
		t.Prop2 = default(string);
		t.Prop3 = default(string);

		t.Id = 1;
		t.Name = "one";
		t.Unique = Guid.NewGuid();
		t.Prop1 = "prop1";
		t.Prop2 = "prop2";
		t.Prop3 = "prop3";
	}
	stopwatch.Stop();
	stopwatch.Elapsed.Dump();
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public Guid Unique { get; set; }
	public string Prop1 { get; set; }
	public string Prop2 { get; set; }
	public string Prop3 { get; set; }
}
```
It's slightly slower.
```
00:00:33.9910290
00:00:34.6850248
```
The difference isn't huge either way. 

The code to implement something like this would be pretty large because it's all done in expression trees, so that's where most of my hesitation lies.

I just though of a way you could test this, and it wouldn't be a ton of code. You can loop the records and build and object yourself using `obj.Property = csv.GetField<PropertyType>( "field" );`. You could test with creating a new object each time or reusing the same one. I'd be curious to see what your results are like.

**Comment by eric-b** [comment]
Thanks for your previous answer. I missed it, probably lost in the middle of other github notifications. Anyway thank you for your time on the subject and my apologies for this late answer. 

I still think there is use cases, like I encounter sometimes. The issue is not the time taken to parse the file (GC took appart, it makes sense that creating a new class for each row is faster) but it is the memory pressure.

I perfectly understand that the development cost is not worth the feature on this library.

Now, I use CsvHelper most of the time I have to deal with "conventional" CSV files. And for very big files, I make my solution with instance reuse in foreach loops. Big CSV files are usually very well specified, so the code to parse them is pretty simple anyway.

**Comment by JoshClose** [comment]
What if someone does a `ToList()`? How does it re-use classes when multiple are returned? I'm not very familiar with class re-use.

**Comment by eric-b** [comment]
It's for advanced use case so the caller should know he shoudn't call .ToList() on it. If it would be supported in CsvHelper, there should be an option to switch to this behaviour, or another method with an explicit signature.

For example, if the method takes the instance to reuse as a parameter, like `GetRecords<T>(T entityToReuse)` or `GetRecords<T>(Func<T> entityInitializer)`, it is explicit to the caller. Protobuf-net does exactly that. If the instance parameter to reuse is null, it creates a new one.

**Comment by JoshClose** [comment]
I'll look more into this. I'm much more ok with it if there is a separate method that's being called.

**Comment by eric-b** [comment]
I appreciate. I think the separate and explicit method is the best approach too.

**Comment by JoshClose** [comment]
Where does Protobuf-net do this?

**Comment by JoshClose** [comment]
Would you be able to tell me where in protobuf-net this is used? I'm looking through the source and so far all I've seen is the value object that gets passed in just gets set.

**Comment by eric-b** [comment]
Yes: `ProtoBuf.Meta.RuntimeTypeModel.Deserialize(int key, object value, ProtoReader source)`, where `value` can be null or the instance to fill.

It's not a loop, but it's the same concept of reuse. I hope there wasn't a misunderstanding about the instance reuse with IEnumerable.

**Comment by JoshClose** [comment]
So from my little bit of testing, you give it an object, and it will overwrite the properties. It does not clear the object though, just overwrites with the stored values.

**Comment by eric-b** [comment]
Exactly: I'm even pretty sure it fills only the properties with a default value (0 for int, null for reference types, etc.). Also, if the deserialized stream does not contain a field, the property of the object is not cleared. Protobuf does not clear or replace any property already set.

In my opinion, a method `EnumerateRecords<T>(Func<T> recordInitializer) is more explicit: the caller is responsible to clear its instance in the specified function. When memory pressure is not an issue, it will be logically slower than creating a new instance. But if the caller prefers to priviledge memory consumption (for a >1Gb file for example), he can use the new method.

**Comment by JoshClose** [comment]
So when streaming data, meaning yielding a single result at a time, you're seeing the memory going way up? The GC isn't handling collection of those objects?

**Comment by eric-b** [comment]
It does, but most often than not, with a performant system, memory will typically have peaks before GC cleanup. The process will reserve more memory for its usage with instance creation on each row, and it will reserve less memory with instance reuse strategy.

Also, the GC is triggered on allocs (`new`). If you parse a very big file, and if .NET runtime don't manage to allocate memory to the process faster than program needs, I even think an OutOfMemoryException is possible. In my opinion, there is cases where you know that the files you process are so big that the strategy with instance reuse is better, even with a speed cost. Speed is not always the main quality attribute of a program.

It's just an opinion and it's debatable but I cited other libraries to show that it's not a strange idea.

I hope I'm clear, and sorry for my english here...

**Comment by JoshClose** [comment]
I would never have guessed you weren't a native English speaker. :)

If this is just setting properties of a single object and not clearing anything, it should actually be faster than normal reading.

I just want to make sure I understand everything here so I solve your issue.

My plan would be this. It'll take in an existing object and use that instead of creating a new one. Everything else will behave the exact same.

**Comment by eric-b** [comment]
Thanks :-)

It would be perfect for my use case.
I think it will be slower at the level of the program because even if CsvHelper does not clear the passed object, the caller will have to. And it is slower to reset property of an existing object than creating a new one (when there is no memory pressure).

**Comment by JoshClose** [comment]
I pushed this functionality to NuGet. https://www.nuget.org/packages/CsvHelper/3.0.0-RC04

Please give it a try and let me know if it fits your needs and works as expected.

**Comment by eric-b** [comment]
Thanks, I'll give it a try by the week end.

**Comment by eric-b** [comment]
So, I tried the new method `EnumerateRecords` and I do admit the difference is not very obvious with my test. 

My little test is a 3Gb file of 3 string columns. The memory consumption is visually comparable, with a little few GC collections with instance reuse but nothing significant.

	TestWithNew: 00:06:08.3560985
	# Gen 0 Collections	8 821
	# Gen 1 Collections	131
	# Gen 2 Collections	6


	TestWithReuse: 00:06:08.1199880
	# Gen 0 Collections	8 436
	# Gen 1 Collections	121
	# Gen 2 Collections	3


Made with the following program:

    class Program
    {
        const string filepath = @"C:\tmpF0D1.tmp";

        static void Main(string[] args)
        {
            TestWithReuse();
            //TestWithNew();
            Console.ReadKey(intercept: true);
        }

        static void TestWithReuse()
        {
            using (var fs = File.Open(filepath, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var reader = new StreamReader(fs))
            using (var csv = new CsvReader(reader))
            {
                csv.Configuration.HasHeaderRecord = false;
                csv.Configuration.Delimiter = ";";
                Stopwatch watch = Stopwatch.StartNew();
                var instanceToReuse = new Item();
                foreach (Item item in csv.EnumerateRecords<Item>(instanceToReuse))
                {
                    item.Clear();
                }
                watch.Stop();
                Console.WriteLine("Completed: {0}", watch.Elapsed);
            }
        }

        static void TestWithNew()
        {
            using (var fs = File.Open(filepath, FileMode.Open, FileAccess.Read, FileShare.Read))
            using (var reader = new StreamReader(fs))
            using (var csv = new CsvReader(reader))
            {
                csv.Configuration.HasHeaderRecord = false;
                csv.Configuration.Delimiter = ";";
                Stopwatch watch = Stopwatch.StartNew();
                foreach (Item item in csv.GetRecords<Item>())
                {
                    if (item.Col1 == null)
                        break;
                }
                watch.Stop();
                Console.WriteLine("Completed: {0}", watch.Elapsed);
            }
        }
    }

    

    sealed class Item : IClearable
    {
        public string Col1 { get; set; }

        public string Col2 { get; set; }

       public string Col3 { get; set; }

        public void Clear()
        {
            Col1 = default(string);
            Col2 = default(string);
            Col3 = default(string);
        }
    }

    interface IClearable
    {
        void Clear();
    }


I still have to try it on a realistic project at work, but I will not be able to do so soon.

**Comment by JoshClose** [comment]
I'll double check that it's not re-creating the Expression each loop.

**Comment by JoshClose** [comment]
It's not. I'm going to close this since it's complete. Let me know if you find anything else out.

**Comment by eric-b** [comment]
Yes, thanks for your time on that matter.
