### ISSUE TITLE
Always use the default converter when passing Types

### ISSUE THREAD

**Issue by GrantHoffman** [JoshClose/CsvHelper#496]
Say you have a generator class that is pulling the defaults.
How do you send the defaults as a string and have the string be resolved to its type to using the converter.

```
public class CsvMapGeneratorRule<T> : CsvClassMap<T>
{
    public CsvMapGeneratorRule(TemplateMapBase<T> templateMap)
    {
        foreach (var mappingInfo in templateMap.MappingInfos)
        {
            this.Map(mappingInfo.Property)
                .Index(mappingInfo.Index)
                .Default(mappingInfo.Default);
        }
    }
}
```

Perhaps adding a DefaultFromString() function which will send then default to be converted

**Comment by JoshClose** [comment]
Thanks for adding the question here. It'll be easier to have the discussion and paste code.

I'm making this a feature request.

I'm surprised that `Default( object )` takes in an object like that, and isn't a generic, but the class would have to be a generic, and that will present several problems.

When setting the default, it should use the type converter for that property.

For your code, I think this should work so you don't have to worry about working with modified source code.

```cs
var converter = TypeConverterFactory.GetConverter( mappingInfo.Property.PropertyType );
var defaultValue = converter.ConvertFromString( mappingInfo.Default );
Map( mappingInfo.Property )
    .Index( mappingInfo.Index )
    .Default( defaultValue );
```

I don't have a way to test this code currently though. :)

**Comment by GrantHoffman** [comment]
Thanks, I'll test this out

**Comment by GrantHoffman** [comment]
Could you also add a parameter to allow conversions for convertusing, it would be very helpful instead of having to manually use the converters

**Comment by GrantHoffman** [comment]
I created a pull request for this with tests

**Comment by JoshClose** [comment]
This was completed already. #499
