### ISSUE TITLE
enums always return null

### ISSUE THREAD

**Issue by GrantHoffman** [JoshClose/CsvHelper#497]
All my enum properties are not being converted properly,  I'm creating a mapping class which maps the property with a default.

      public void MapPropertyFromTemplate(TemplatePropertyInfo<TDTO> propertyInfo)
        {
            if (false == this._templateMap.Mappings.ContainsKey(propertyInfo.Name) &&
                false == this._templateMap.Defaults.ContainsKey(propertyInfo.Name))
            {
                return;
            }

            var mappedProperty = this.Map(propertyInfo.Property).Index(-1);

            if (this._templateMap.Mappings.ContainsKey(propertyInfo.Name))
            {
                var index = this._templateMap.Mappings.Get(propertyInfo.Name);
                mappedProperty.Index(index);
            }

            if (this._templateMap.Defaults.ContainsKey(propertyInfo.Name))
            {
                var defaultValue = this._templateMap.Defaults.Get(propertyInfo.Name);
                mappedProperty.Default(defaultValue);
            }
        }

Everything maps fine except for the Enums they are always resulting in null.  Is there a way to specify that they should by default try to parse the enum text and convert to enum or should I be implementing that myself?

**Comment by JoshClose** [comment]
Can you create a small self contained example that displays this not working? It's hard to tell what's going on with the level of abstraction you have there.

Converting enums is done using the `EnumConverter`. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/EnumConverter.cs if you want to test it out.

**Comment by GrantHoffman** [comment]
say you had a model with an Enum Gender in it
        enum Gender
        {
              Male,
              Female
        }

and you set up your mapping class like this

          this.Map(x => x.Gender)

your csv record is using the string "Male"

the Model is a Nullable<Gender>

When I parse the recorders I'm always being return null, instead of Gender.Male.  Is this expected and I have to map the enum class myself or should the default enum converter kick in

**Comment by JoshClose** [comment]
It should just work. I currently don't have a way to test this, but I can when I get home tonight. I'll see what's going on and give you a working example.

**Comment by GrantHoffman** [comment]
I just looked into it it seems fine I was doing the mapping wrong

**Comment by JoshClose** [comment]
Glad you figured it out!
