### ISSUE TITLE
Negative Index should be allowed to set defaults

### ISSUE THREAD

**Issue by GrantHoffman** [JoshClose/CsvHelper#498]
Say you were to attempt to map a non existent property of your csv to a default value

            public class model
            {
                count{ get; set;}
                name {get; set;}
            }

this statement would be convient for setting a default on a type that doesn't appear in the csv.
I believe currently this  will throw an index out of range exception during the parse instead of just setting the value to 3

            this.Map(x => x.Count).index(-1).Default(3)

**Comment by JoshClose** [comment]
You can do this in version 3.0 using `Constant` instead of `Default`. `Default` is meant to be applied when a value is missing, whereas `Constant` is always set no matter what.
