### ISSUE TITLE
JSON string to CSV and CSV to JSON conversion

### ISSUE THREAD

**Issue by vickyrathee** [JoshClose/CsvHelper#502]
I've dynamic json files and using streamreader to read that into a string, is there a way i can convert that Json Array object into CSV

Sample file (May be any number of fields)
```
[
{"COLUMN1":"a","COLUMN2":"b","COLUMN3":"c","COLUMN4":"d","COLUMN5":"e"},{"COLUMN1":"a","COLUMN2":"b","COLUMN3":"c","COLUMN4":"d","COLUMN5":"e"}
]
```

**My code ** But it's not working and getting blank in console
```
var content = readLocalFile("E:\\text-file.txt");
var jsonContent = JsonObject.ParseArray(content);
CsvHelper.CsvWriter csw = new CsvHelper.CsvWriter(new StringWriter());
foreach (var item in jsonContent)
{
    csw.WriteRecords(item);
}
Console.WriteLine(csw);
```

**Comment by jamesbascle** [comment]
I think the best you could do there is deserialize it to a JArray
(newtonsoft.json), which is an IList<JToken> and provide a JToken class
map.  CdvHelper doesn't know about json like in your example.

**Comment by vickyrathee** [comment]
Any example? Because i can't create a class map since the JSON string is dynamic and may have any number of fields with anything in heading.

**Comment by JoshClose** [comment]
I don't know how to use JSON.NET very well, but here is a simple example. You should at least be able to get an idea of how to write individual fields in CsvHelper.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var content = "[{ \"COLUMN1\":\"a\",\"COLUMN2\":\"b\",\"COLUMN3\":\"c\",\"COLUMN4\":\"d\",\"COLUMN5\":\"e\"},{ \"COLUMN1\":\"a\",\"COLUMN2\":\"b\",\"COLUMN3\":\"c\",\"COLUMN4\":\"d\",\"COLUMN5\":\"e\"}]";
		var array = JArray.Parse(content);
		foreach (var obj in array)
		{
			foreach (JProperty prop in obj)
			{
				csv.WriteField(prop.Value.ToString());
			}
			csv.NextRecord();
		}
		
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}
```
