### ISSUE TITLE
The example csv to datatable not working

### ISSUE THREAD

**Issue by vickyrathee** [JoshClose/CsvHelper#504]
I need to convert a local tab delimited file into a datatable and i was using the example code but it's not working..

```
            var content = readLocalFile("E:\\tsv-to-json.txt");
            var csv = new CsvReader(new StringReader(content));
            csv.Configuration.Delimiter = "\t";
            csv.Configuration.HasHeaderRecord = true;
            DataTable dt = new DataTable();
            while( csv.Read() )
            {
                var row = dt.NewRow();
                foreach( DataColumn column in dt.Columns )
                {
                    row[column.ColumnName] = csv.GetField(column.DataType, column.ColumnName);
                }
                dt.Rows.Add(row);
            }
```

Then I'm printing my table but it doesn't have any rows. In above example how the data is loaded? i guess the foreach is used for columns only and then rows.add is just adding empty row.

**Comment by JoshClose** [comment]
You need to set up your `DataTable` with columns. That part was left out of the example. It assumed that was already set up.
