### ISSUE TITLE
Using a type that doesn't have a parameterless constructor

### ISSUE THREAD

**Issue by wrummler** [JoshClose/CsvHelper#505]
An `ArgumentException` occurs at `Expression.New` in `CsvReader.CreateFuncForObject` when using `GetRecords` with a type that lacks a parameterless constructor. Here's a demo snippet:

```csharp
void Main()
{
    var reader = new StringReader("Alpha,Beta\n0.1,0.2\n0.3,0.4\n");
    var csv = new CsvReader(reader);
    var records = csv.GetRecords<Test>();
    Console.WriteLine(records.Count()); // throws
}

class Test
{
    public Test(string s)
    {
    }

    public double Alpha { get; set; }

    public double Beta { get; set; }
}
```

I couldn't find a place in the CsvHelper docs (pages or wiki) where it says that a parameterless constructor is required, though it does make sense that it would be required, since the few points of reference I've seen online indicate that robustly creating a "default" instance of a type that lacks a parameterless constructor is hard and/or slow.

So I'm not so much reporting this as a bug, but more just asking for clarification. Does CsvHelper always require a parameterless constructor for types that it maps?

If so, could there be some addition to the documentation and/or CsvHelper's exception API to make this explicit?

I know the `ArgumentException` explicitly says what the problem is, but the fact that it's a system exception with a generic (though specific) message makes its occurrence seem possibly unintentional. Still using an `ArgumentException` somewhere in CsvHelper's code to indicate this condition is not a bad idea, but using an exception message that is more CsvHelper-specific would mitigate (at least my) worry compared to the generic message that `Expression.New` provides.

@JoshClose Thanks for your time & work. From browsing past issues, I know I'm echoing many other users in saying that CsvHelper is an extremely useful library.

**Comment by JoshClose** [comment]
There is `ConstructUsing` as a mapping option. I was just creating an example with this, but you're not given the row to use during this, so I'm not sure how helpful that is. This is the scenario I was thinking of.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; private set; }

	public string Name { get; set; }

	public Test(int id)
	{
		Id = id;
	}
}

public class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		ConstructUsing( () => new Test( 1 ) );
		Map( m => m.Name );
	}
}
```

Does this work for you in it's current form? You would be able to pass something into the `TestMap` class to use for the constructor but you wouldn't be able to use the data from the row.

I think I should add the row as data that is passed to that.

**Comment by wrummler** [comment]
`ConstructUsing` fits well in my case, thanks for the suggestion. The type I have to deal with is a simple mutable DTO, so I can use `ConstructUsing` to provide a dummy input whose only purpose is to allow the parameterized constructor to succeed, then CsvHelper's mapping engine can fill in the actual properties from the row.

I don't know whether auto-mapping within a class map is implemented yet, but another way to do this that avoids potentially extensive manual spec'ing in the deriving map's constructor is to subclass the record type and have a parameterless constructor that gives the dummy input to the base constructor, e.g.:

```csharp
void Main()
{
    var reader = new StringReader("Alpha,Beta\n0.1,0.2\n0.3,0.4\n");
    var csv = new CsvReader(reader);
    var records = csv.GetRecords<DummyTest>();
    records.Dump();
}

class Test
{
    public Test(string s)
    {
        var values = s.Split(',');
        Alpha = double.Parse(values[0]);
        Beta = double.Parse(values[1]);
    }

    public double Alpha { get; set; }

    public double Beta { get; set; }
}

class DummyTest : Test
{
    public DummyTest() : base("0,0")
    {
    }
}
```

If the record type happens to be sealed, this wouldn't be an option. (And of course all of my comments are assuming the record type is not under one's control, which it isn't in my current case.)

Thanks again.

**Comment by wrummler** [comment]
I forgot to mention a possible behavior for CsvHelper that is probably best located in this issue thread.

It could be worthwhile for CsvHelper to attempt to use [`FormatterServices.GetUninitializedObject`](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatterservices.getuninitializedobject(v=vs.110).aspx) (in mscorlib's System.Runtime.Serialization namespacing) when a record type is supplied that lacks both a parameterless constructor and a custom `ConstructUsing` spec. Food for thought.

**Comment by JoshClose** [comment]
Auto mapping is available in a class map. You can call `AutoMap();` then just override the mappings you want to change.
