### ISSUE TITLE
Calling FirstOrDefault before iterating using foreach affects foreach start record

### ISSUE THREAD

**Issue by nlarson** [JoshClose/CsvHelper#507]
using (CsvReader csv = new CsvReader(File.OpenText(e.Argument.ToString())))
         {
               IEnumerable<CustomClass> data = csv.GetRecords<CustomClass>();
               var first = data.FirstOrDefault();
               foreach (CustomClass customClass in data)
               {
                   Assert(customClass == first); // Assert fails
...

The first record retrieved in the foreach loop is actually the second record. foreach should likely reset the stream to the start.

Nice work on this package, its very useful and easy to use, thanks!

**Comment by JoshClose** [comment]
CsvHelper doesn't know anything about a stream. It gets a `TextReader` that by definition 
> Represents a reader that can read a sequential series of characters.
That means forward only. It doesn't know that the data came from a `Stream` either. You would need to manage that yourself.

You can reset the stream yourself, but that will mess up the internals of CsvHelper. It keeps track of a lot of information. You'd probably have to create a new instance of `CsvReader` after getting `FirstOrDefault`.

Another option is to do a `ToList()` on the `IEnumerable` and pull the whole file into memory. You can then do any Linq operation you want on it.

Another option is to loops the records yourself.

```cs
var count = 0;
while( csv.Read() )
{
    var row = csv.GetRecord<CustomClass>();

    if( count == 0 )
    {
        // Do something with the first record.
    }

    count++;
}
```

**Comment by RhysC** [comment]
As a 3rd party i agree with @JoshClose : i would not expect the stream to reset, you have already started to iterate so to speak
