### ISSUE TITLE
Array properties

### ISSUE THREAD

**Issue by mg-alfa** [JoshClose/CsvHelper#509]
I have a use case that is very common for many of the files we use in the financial industry where we have "arrays" represented in the CSV with each element in a separate "numbered" column.

For instance, one of our file types has an array property "values" that is represented in columns labelled "Value1", "Value2", ...

I think this could be handled by Reference property maps, but I'm not 100% sure.  Given how often I have to do these I wanted to think of a way that would be more "standardized" for the library.

I've been considering the following:
1. make arrays be supported by the property mapping capability through a convention for the array name mapping (i.e. default to Name{0} format, but allow an override of the format).
2. support post processing of the properties that are array properties such that all values for the array are "gathered" into a List<T> or something and then assigned at the end of processing the record.

My questions are these:
1. Is this functionality you think fits into the library?
2. Do you have any suggestions on how you'd like to see it done if I were to do it and send a PR?

**Comment by kellypleahy** [comment]
Looks like I posted this under the wrong credentials.  I really wanted to post under mine (@kellypleahy)

**Comment by JoshClose** [comment]
I plan on supporting collections in the future, but it's not currently built in. You can use `ConvertUsing` to do it right now.

Here is an example. `Dump` is a LINQPad thing.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Value1,Value2,Value3,Name");
		writer.WriteLine("1,1,2,3,one");
		writer.WriteLine("2,4,5,6,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; set; }

	public string Name { get; set; }

	public List<int> Numbers { get; set; }
}

public sealed class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.Numbers).ConvertUsing(row => new List<int> { row.GetField<int>(1), row.GetField<int>(2), row.GetField<int>(3) });
	}
}
```

**Comment by JoshClose** [comment]
Collections are supported in 3.0 now.

**Comment by onionhammer** [comment]
AutoMap() seems to completely ignore collections. It would be nice if they at least came across as ignored (by default), then at runtime they could be handled by user code iterating over PropertyMaps.

**Comment by JoshClose** [comment]
In 3.0?

**Comment by onionhammer** [comment]
Ah, no.. I'm using stable on nuget.

**Comment by bsowa** [comment]
How are they supported in 3.0? Can you please provide some example code?
