### ISSUE TITLE
Update Documentation, please.

### ISSUE THREAD

**Issue by MB34** [JoshClose/CsvHelper#510]
Although you have this text "You need to register your class map in configuration.", it took me several readings of the entire Mapping section to see an example: 

csv.Configuration.RegisterClassMap(CustomerMap);

Please update the docs to make it clearer what to do for each Map.

**Comment by mudnug** [comment]
I think the examples may have been updated since this issue was created as I readily found https://joshclose.github.io/CsvHelper/examples/reading/reading-multiple-data-sets which demonstrates registering class maps
