### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by gipap123** [JoshClose/CsvHelper#511]
Hello! First of all, thank you for this masterpiece.
I experience a strange issue, with an Index was outside the bounds of the array error

My map class is

```
 public sealed class ProductMap : CsvClassMap<Product>
    {
        public ProductMap()
        {
            Map(m => m.VatRate).ConvertUsing(row =>
            {
                if (string.IsNullOrEmpty(row.GetField<string>("VatRate"))) throw new Exception("VatRate is required.");
                return row.GetField<string>("VatRate");
            }).Index(0);
        }
    }
```
My Product Class is

```
public class Product
{
    public decimal VatRate { get; set; }
}
```
While trying to get the records in a list,

`IEnumerable<Product> products  = csv.GetRecords<Product>().ToList();`
i get the following error.

Index was outside the bounds of the array.

if i change the type of the `VatRate` in `Product` class from `decimal` to `string`, i do not get any errors.

**Comment by JoshClose** [comment]
The type of `VatRate` in your class is a `decimal` so you need to return a `decimal` from `ConvertUsing`. 

There's no good way I've found to have better error reporting on that yet. I could possibly inspect the `Expression` and make sure it's the same type and throw an exception in that case...

**Comment by JoshClose** [comment]
I think if you just change the return to `return row.GetField<decimal>("VatRate");` it should work.

**Comment by JoshClose** [comment]
I just added a feature request for this. https://github.com/JoshClose/CsvHelper/issues/512
