### ISSUE TITLE
System.Runtime.CompilerServices.ExtensionAttribute needs to be removed from 2.14.0

### ISSUE THREAD

**Issue by vetdata-dev** [JoshClose/CsvHelper#513]
Just upgraded to 2.14.0 from 2.13.5 and now my project won't compiled because for some reason there is a copy of System.Runtime.CompilerServices.ExtensionAttribute in 2.14.0 which of course conflicts with mscorlib.

**Comment by JoshClose** [comment]
Which version or .NET are you using?

**Comment by vetdata-dev** [comment]
4.5

**Comment by JoshClose** [comment]
Are you using the client profile?

**Comment by GeertvanHorrik** [comment]
We have this as well.

**Comment by GeertvanHorrik** [comment]
I think it should be excluded by default (we are using .NET 4.0, but compiling with VS 2015).

**Comment by vetdata-dev** [comment]
No, not using the client profile.

**Comment by JoshClose** [comment]
I won't be able to look at this for 10 hours at the earliest... possibly 34 hours. Would you be able to look at the source and determine what is causing that?

**Comment by JoshClose** [comment]
This should be fixed now.

**Comment by vetdata-dev** [comment]
Working great, thanks Josh!
