### ISSUE TITLE
Map same field twice in CSV output

### ISSUE THREAD

**Issue by bbarvish** [JoshClose/CsvHelper#515]
I have POCO that i'm mapping to a CSV output and I want the same field from the POCO to be used twice in the output but in different ways.  For eg:

`Map(m => m.PlateNumber).Name("PlateNumber"); 
Map(m => m.PlateNumber).Name("VehicleType").TypeConverter<PlateToVehicleTypeMapper>();`

The output ignores the first mapping of the PlateNumber field even through i'm pushing out to different fields.  The second instance of the field works just fine.  I've also tried reversing the order and it seems that the Map(ing) instance with the TypeConverter always wins.  I've also tried with Index but have not been successful.

Any thoughts?

**Comment by JoshClose** [comment]
Currently it only allows for a property to be mapped once. Any subsequent property mappings will overwrite the previous.

I could look into doing this in the future though.

**Comment by asd-and-Rizzo** [comment]
I tried to map 
```
Map(m => m.Size).Name("size");
Map(m => m.Todo).Name("serviceName");
Map(m => m.Todo).Name("version");
Map(m => m.Date).Name("date");
```
and got exception that property can be used only once. Is it possible to use property 2 times?
I found next solution https://github.com/JoshClose/CsvHelper/issues/180#issuecomment-21146510, but it could be easier things work with mapping. 

Or if next to work
```
Map(m => m.Size).Name("size");
Map(m => "Todo").Name("serviceName");
Map(m => "Todo").Name("version");
Map(m => m.Date).Name("date");
```

I need this for quick iteration with product owners about unknown data sources.

**Comment by jamesbascle** [comment]
Josh is pretty good about merging well written PRs from what I've seen.
Doesn't seem like it should be too difficult of you need it so urgently.
Just change the internal implementation of the property maps holder to
contain multiple per key and write a few tests. Unfortunately that could be
a breaking change in some corner cases for current users.

You might also consider convertusing instead of you're in a hurry. I think
that should let you map the same field twice.

**Comment by juswes** [comment]
I’m also having a situation where I need to map the same field twice (or even more then twice) in the CSV output.

@bbarvish 
Have you find any final solution to this problem?

@JoshClose 
Any take on when or if this will be implemented in a next release?

**Comment by JoshClose** [comment]
This feature is complete and will be in 3.0 beta 7 on NuGet.

**Comment by pizzo00** [comment]
I am using v12 and this is still a problem
