### ISSUE TITLE
Unable to find a version of 'Microsoft.CSharp' that is compatible with 'CsvHelper 2.14.2'

### ISSUE THREAD

**Issue by csrakowski** [JoshClose/CsvHelper#516]
I have the NuGet package (2.14.1) installed in a .NET 4.6 class library project.
When trying to update the NuGet package from 2.14.1 to 2.14.2 I get the following error:

    Severity	Code	Description	Project	File	Line	Suppression State
    Error		Unable to find a version of 'Microsoft.CSharp' that is compatible with 'CsvHelper 2.14.2 constraint: Microsoft.CSharp (>= 4.0.1-beta-23516)'.			0	

The 'quick-fix' for a lot of people will probably be to just check the box and allow pre-release versions to download, but unfortunately that is not an option for us at this time.
Since 2.14.1 works perfectly fine, staying on this version till the issue is resolved is not a problem for us. I just wanted to notify you this is happening.

**Comment by JoshClose** [comment]
I'll fix this soon. There is a new version of .NET Core that was just released that changed pretty much everything.

**Comment by csrakowski** [comment]
Yeah, it's been a wild ride last year.
The new .NET Core system with the TFMs sounds way better than the old PCL approach.
I hope things turn out to work just as awesome as they sound in the conference sessions!

**Comment by JoshClose** [comment]
Me too.

**Comment by JoshClose** [comment]
I'm adding this for reference. http://dotnet.github.io/docs/core-concepts/dnx-migration.html

Doesn't look like all the dependencies are there yet to switch to `netstandard1.5`. I'm currently trying on a Mac though, so I'll see what it's like in Visual Studio on Windows later.

**Comment by JoshClose** [comment]
I have it working but it's not generating PDB files anymore. Once I get that working, I'll put out a new build.

**Comment by JoshClose** [comment]
Version 2.14.3 is on NuGet and is updated to .NET Core RC2. If this doesn't fix your problem, let me know.

**Comment by csrakowski** [comment]
Verified as working correctly for us; it loads the net45 version without pulling in any dependencies.
Thanks for the fix!
