### ISSUE TITLE
Out of memory exceptioin.

### ISSUE THREAD

**Issue by kirankaredla** [JoshClose/CsvHelper#519]
Hi

i had to read csv file having  10 laksh records(file size 99 MB) to  compare  with other files.
but i got out of memory exception.can u please help me to fix this issue. For smaller files my code working fine.

Exception:
An exception of type 'System.OutOfMemoryException' occurred in CsvHelper.dll but was not handled in user code

**Comment by JoshClose** [comment]
Can you provide the code that you're using or an example that reproduces the issue?

**Comment by JoshClose** [comment]
I will need an example to further help you. Thanks.
