### ISSUE TITLE
Validation while parsing.

### ISSUE THREAD

**Issue by vkurkotov** [JoshClose/CsvHelper#520]
Hello.
Is there a possibility to add some validation like `length` of a string or `required` when using `.GetRecords<T>`? 
For example like same as in [FluentValidation](https://github.com/JeremySkinner/FluentValidation):

```
public sealed class AddressMap : CsvClassMap<Address>
{
    public AddressMap()
    {
        Map( m => m.Street ).NotEmpty();
        Map( m => m.City ).Length(20, 250);
        Map( m => m.State ).NotEmpty().Length(20, 250);
        Map( m => m.Zip ).NotEmpty();
    }
}
```

Or support of some attributes:

```
public sealed class Address
{
    [Required]
    public string Street { get; set; }

    [Length(20, 250)]
    public string City { get; set; }

    [Required]
    [Length(20, 250)]
    public string State { get; set; }

    [Required]
    public string Zip { get; set; }
}
```

**Comment by JoshClose** [comment]
No attributes. They existed at one point, but the configuration got too complex and attributes weren't able to handle all the scenarios that class mapping can.

As far as validation goes, why not just use FluentValidation? It seems to have a lot of features, and it would be a ton of work to try and reproduce them.

It would only be an extra line or so, besides the setup.

```cs
while( csv.Read() )
{
    var address = csv.GetRecord<Address>();
    var validationResults = addressValidator.Validate(address);
}
```

**Comment by JoshClose** [comment]
Validation is now built into mapping. It's completely open ended. Take a look here. https://github.com/JoshClose/CsvHelper/issues/556
