### ISSUE TITLE
Parsing and Mapping CSV files with a header not on the first row

### ISSUE THREAD

**Issue by psubsee2002** [JoshClose/CsvHelper#523]
I have a situation with a CSV file that is generated by a tool we use throughout my company.  There some "meta" data that is included at the top of the file and at the bottom of the file (basically the top is just the settings selected by the user when generating the data, and the footer data is a rollup/summary of the data).  The settings data, the report data (which is what I want to parse), and the summary are always separated by a blank row.  The number of rows of the valuable data is variable and cannot be predicted.

The format is roughly:
```
Meta1
Meta2
Meta3

Header1,Header2,Header3,...
Value1,Value2,Value3,...
Value1,Value2,Value3,...
Value1,Value2,Value3,...

FooterHeader1,FooterHeader3,FooterHeader2,...
FooterValue1,FooterValue2,FooterValue3,...
FooterValue1,FooterValue2,FooterValue3,...
```

It is the stuff in the middle that I need to read.  Changing the format is not possible, so I'm left to find a word around.  I did not see an option in the configuration to specify a different row for the header, but I did find a solution by partially consuming the TextReader until I found the first blank line, then passing it to the CsvReader, then stopping the `Read()` method when I hit the next empty line.

```
var records = new List<CsvObject>();

var config = new CsvConfiguration();
config.RegisterClassMap(new TestCsvMap());


using (var sr = new StreamReader(path))
{
    bool emptyFound = false;
    while (!sr.EndOfStream && !emptyFound)
    {
        var line = sr.ReadLine();
        Console.WriteLine(line);

        var fields = line.Split(new[] { "," }, StringSplitOptions.RemoveEmptyEntries);

        if (fields.Length == 0)
            emptyFound = true;
    }
                
    using (var csv = new CsvReader(sr, config))
    {
        var dataComplete = false;

        while (csv.Read() && !dataComplete)
        {
            if (csv.IsRecordEmpty())
                dataComplete = true;
            else
            {
                var record = csv.GetRecord<CsvObject>();
                records.Add(record);
            }
                        
        }
    }    
}       
```

Is there a built in option to do what I need to accomplish, or is my only option to handle it this way?

**Comment by JoshClose** [comment]
I would suggest using the reader and testing the value of the first field.

```cs
while( csv.Read() )
{
    // Check if in meta data. Set flag when not.
    // Get records until blank line. Set flag again.
    // Get footer records until blank line.
}
```

**Comment by rmalcomber** [comment]
This would be a great feature, I've been having the same issue. Selecting which is the header row. Or defining meta data rows.

**Comment by JoshClose** [comment]
Those files are not valid CSV files. I'd like to stay away from adding in a bunch of special features for non-standard things. Doing this by hand is simple and only a few lines of code, and I don't think it should be a built in feature.

If you search the rows using the above method, you should be able to just start reading from that point on. If there are any issues there, let me know and I'll try to help out.

You could also look into using `ShouldSkipRecord`. I should really make it so you don't have to inherit `CsvReader` to use it though.

**Comment by JoshClose** [comment]
I added this. https://github.com/JoshClose/CsvHelper/issues/529

**Comment by JoshClose** [comment]
That feature is complete and you should be able to do what you're asking now.
