### ISSUE TITLE
Error updating nuget to 2.14.2 from 2.14.1

### ISSUE THREAD

**Issue by EricZimmerman** [JoshClose/CsvHelper#524]
Unable to find a version of 'Microsoft.CSharp' that is compatible with 'CsvHelper 2.14.2 constraint: Microsoft.CSharp (>= 4.0.1-beta-23516)'.	

Nothing has changed in my project. it is targeting 4.6 framework

**Comment by EricZimmerman** [comment]
Looks like this is a dupe of

https://github.com/JoshClose/CsvHelper/issues/516

**Comment by JoshClose** [comment]
Yeah. There is a new version of .NET Core now too, so we'll see what happens with that. It looks like everything has changed.
