### ISSUE TITLE
Custom options in TypeConverterOptions

### ISSUE THREAD

**Issue by WalkingMist** [JoshClose/CsvHelper#525]
I am making a custom TypeConverter and I am following one of your examples included in the code base. However, I would like to add some custom options to the TypeConverterOptions:

``` cs
public class MyCustomDateTimeConverter : ITypeConverter
{
  public string ConvertToString(TypeConverterOptions options, object value)
  {
    .....
    if(options.MyCustomOptionA)
      // Do something different
```

How can I accomplish this? 
Do I just derive from TypeConverterOptions with my own custom options?

**Comment by JoshClose** [comment]
I think you can do that and update the entry in `TypeConverterOptionsFactory`.

```cs
TypeConverterOptionsFactory.AddOptions<MyType>( myCustomOptions );
```

You would probably have to cast to your options type in your `TypeConverter` though.

**Comment by WalkingMist** [comment]
I have had a look at the TypeConverterOptionsFactoryTests class and saw this
`public void AddGetRemoveTest()
 {
     var customOptions = new TypeConverterOptions
     {
       Format = "custom",
     };
     TypeConverterOptionsFactory.AddOptions<string>(customOptions);`

Does it means that it is global once I set the value for my custom options?

My problem is that within a csv row, I have multiple DateTime fields with different formats and hence I need to specify which logic to use per column with the Map. And I have no control over the formats as the data was external to me.

**Comment by JoshClose** [comment]
I will have to try out an example. I don't have access to a Windows machine during the day though, so it won't be until late tonight at the earliest.

**Comment by JoshClose** [comment]
Sorry this took so long.

I don't quite understand everything you need to do, but in your custom type converter, you can take data in via the constructor, or a custom property.

```cs
public class CustomDateTimeConverter : DateTimeConverter
{
	public bool ShouldDoStuff { get; private set;}
	
	public CustomDateTimeConverter(bool shouldDoStuff)
	{
		ShouldDoStuff = shouldDoStuff;
	}

	public override string ConvertToString(TypeConverterOptions options, object value)
	{
		if (ShouldDoStuff)
		{
			// do stuff
		}
		else
		{
			// don't do stuff
		}
		
		return base.ConvertToString(options, value);
	}
}
```
Then you can assign a new type converter with different data for each property.
```cs
var doStuffConverter = new CustomDateTimeConverter( true );
var doNotdoStuffConverter = new CustomDateTimeConverter( false );
Map( m => m.Property1 ).TypeConverter( doStuffConverter );
Map( m => m.Property2 ).TypeConverter( doNotDoStuffConverter );
```

**Comment by GeekyEggo** [comment]
@JoshClose, has this changed in the latest v3 betas? `TypeConverterOptionsFactory` is no longer static.

**Comment by GeekyEggo** [comment]
https://github.com/JoshClose/CsvHelper/commit/a75ead6c2ae94a40f7675194450311e72554faaf

**Comment by GeekyEggo** [comment]
Apologies; just spotted this commit; https://github.com/JoshClose/CsvHelper/commit/a75ead6c2ae94a40f7675194450311e72554faaf!

**Comment by JoshClose** [comment]
It was causing race conditions being static.

**Comment by hellboy81** [comment]
``TypeConverterOptions` should still contain custom options.
