### ISSUE TITLE
customDateConverter

### ISSUE THREAD

**Issue by rkram564** [JoshClose/CsvHelper#528]
I am new to github so please excuse me if I am posting this in the wrong area.  

I am trying to create a custom type converter that will allow me to map a datetime with the format 12151994 (MMddyyyy).  I am currently reading each row individually. 

On running my code, my TDate is always added to my objects as {1/1/0001 12:00:00 AM}	System.DateTime

Am I missing a key piece of logic in my customDateConverter?

public class CustomDateConverter : DefaultTypeConverter
        {
            string longDate = "MMddyyyy";

            public override object ConvertFromString(TypeConverterOptions options, string text)
            {
                DateTime newDate = new DateTime(2000,12,12);

                try
                {
                    newDate = DateTime.ParseExact(text, longDate, CultureInfo.InvariantCulture);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(String.Format("Error parsing date '{0}': {1}", text, ex.Message));            
                }

                return newDate;
            }
        }

**Comment by JoshClose** [comment]
Have you tried using a type converter option? http://joshclose.github.io/CsvHelper/#mapping-type-converter-options

You should be able to just set the format there, and not write your own converter.

**Comment by rkram564** [comment]
I haven't.  This would make life a lot easier.  Thank you :)  I revised another property to accept currency values this way.

Map(m => m.Amount).Name(" Amount ").Default(0.00).TypeConverterOption(NumberStyles.Number | NumberStyles.AllowCurrencySymbol);

However, datetime is still tripping me up, how would I set the format I am expecting for the datetime during mapping?

 Map(m => m.TDate).Name("Transaction Date").TypeConverterOption(..?...);

**Comment by rkram564** [comment]
I was making it harder than it had to be, I apologize.  Figured it out.

Thanks for your help!

**Comment by JoshClose** [comment]
Great!

**Comment by rkram564** [comment]
Sorry to bring this back up, but I thought I had had it working.  The truth is, it worked for my test file which included a date column that was formatted MMddyyyy or 03152016.  The data that I will actually be responsible for handling is formatted as follows: Mddyyyy 3152016.  

Placing the format Mddyyyy in my type converter option allowed dates formatted like my test data and not my real data, which I cannot change.  

Map(m => m.TDate).Name("Transaction Date").TypeConverterOption("Mddyyyy").Default(new DateTime(2000, 3, 15, 16, 00, 00));

I was under the impression that M was for month data 1 - 12 and MM was for month data 01 - 12.  

Any advice you could give me in regards to this problem would be helpful

**Comment by JoshClose** [comment]
Take a look at the source. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/DateTimeConverter.cs#L21

It does `DateTime.ParseExact( text, options.Format, formatProvider, dateTimeStyle )`. 

You can use this to figure out the format. https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx
