### ISSUE TITLE
Add support to automatically skip over blank rows

### ISSUE THREAD

**Issue by roryprimrose** [JoshClose/CsvHelper#53]
We have an issue where the CSV file might contain either blank lines, or a row with all cells being empty.

The former might be a scenario where the user is formatting the document for readability (separating lines into groups). 

The later occurs when exporting a CSV from Excel where there is a space several lines below the last visible line.

My workaround is to provide the following parser to the constructor of the CsvReader:

```
/// <summary>
/// The <see cref="FilteredCsvParser"/>
///   class is used to provide CSV data that filters out blank rows.
/// </summary>
[CLSCompliant(false)]
public class FilteredCsvParser : CsvParser
{
    public FilteredCsvParser(TextReader reader)
        : base(reader)
    {
    }

    protected override string[] ReadLine()
    {
        var nextLine = base.ReadLine();

        if (nextLine == null)
        {
            return null;
        }

        var data = string.Join(string.Empty, nextLine);

        if (string.IsNullOrWhiteSpace(data) == false)
        {
            return nextLine;
        }

        // Recurse
        return ReadLine();
    }
}
```

**Comment by arjendemooij** [comment]
For easy reference, this is the setting Josh implemented:

csv.Configuration.SkipEmptyRecords = true;

**Comment by shwedberlin** [comment]
Cannot find SkipEmptyRecords anymore.
Using version 12.x.
How can I skip rows with only separators now?

**Comment by AltruCoder** [comment]
@shwedberlin 
```csharp
csv.Configuration.ShouldSkipRecord = record => record.All(string.IsNullOrEmpty);
```
