### ISSUE TITLE
CsvWriter NullReferenceException - v2.14.2

### ISSUE THREAD

**Issue by RichardD2** [JoshClose/CsvHelper#530]
In addition to issues #411 and #423, if `TrimFields` is set to `true`, calling `WriteField(String)` with a null string throws a `NullReferenceException`.

    var csv = new CsvWriter(Console.Out);
    csv.Configuration.TrimFields = true;
    csv.WriteField(default(string));

The problem seems to be on [line 110 of `CsvWriter.cs`](https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvWriter.cs#L110):

    if( configuration.TrimFields )
    {
        field = field.Trim();
    }

That should probably be:

    if( configuration.TrimFields && field != null )
    {
        field = field.Trim();
    }

**NB:** This will also affect the proposed fix for #423, since that ends up passing a null string to this method.

**Comment by JoshClose** [comment]
This is fixed in 3.0.

This code:

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		csv.Configuration.TrimFields = true;
		csv.WriteField("field1");
		csv.WriteField(default(string));
		csv.WriteField("field3");
		csv.NextRecord();
		writer.Flush();
		stream.Position = 0;		
		reader.ReadToEnd().Dump();
	}
}
```
Produces this output.

```
field1,,field3
```
