### ISSUE TITLE
Binary built in Debug Mode

### ISSUE THREAD

**Issue by BrianJVarley** [JoshClose/CsvHelper#531]
I installed CSV Helper via Nuget in a Windows Phone 8.1 app. But when I submit the appx bundle for certification it fails due to "Binary CSV Helper is built in debug mode".

Link to error on submission to Windows Phone Store - http://picpaste.com/pics/debug-qrPoJUQm.1465241283.PNG

Could you provide a **release** dll of CSV Helper as I can't use the debug dll on Nuget for an app submission at present.

Thanks,

Brian

**Comment by JoshClose** [comment]
That's odd. https://github.com/JoshClose/CsvHelper/blob/master/Pack%20NuGet%20Packages.bat

**Comment by BrianJVarley** [comment]
That is strange, here is a link to the actual error - 

I actually just tried removing the reference to CSV Helper then re-adding via Nuget and I still get the certification error about the dll being debug mode.

[http://picpaste.com/pics/debug-qrPoJUQm.1465241283.PNG](url)

Any ideas why? Or could you build the source in release and pass on the dll to me?

Thanks for your help. Brian

**Comment by JoshClose** [comment]
I can try.

**Comment by BrianJVarley** [comment]
The version I'm using is 2.14.2 for reference which was installed via Nuget.

**Comment by BrianJVarley** [comment]
I solved this in the end by using an older version [2.13.5](https://www.nuget.org/packages/CsvHelper/2.13.5) which was compiled in release mode as required by the Microsoft appx bundle certification process. You may want to re-check that the current 2.14.2 version is not  in fact built in debug as I believe it is due to the earlier certification error presented.

**Comment by JoshClose** [comment]
The whole dnx/dotnet core stuff isn't complete yet, so it wouldn't surprise me. There only difference in versions is 2.14.x has dotnet core support. Using 2.13.5 should be fine.

I'll try and figure this out, but the tools, libraries, and configurations are changing drastically at the moment. I haven't been able to get it working with the change from dnx to dotnet core that happened recently. The libraries are supposed to be updated in the future, and I'm guessing that's the main issue here with it not working.

**Comment by JoshClose** [comment]
I have it updated and the issue fixed. It's not outputting a PDB file though now, even though I have a `debugType` set. Once I get that figured out, I'll put out a new build.

**Comment by JoshClose** [comment]
NuGet build 2.13.3 contains a fix for this and is using .NET Core RC2. Let me know if you have any issues.
