### ISSUE TITLE
System.OutOfMemoryException while reading 1 million records using GetRecords<T> method

### ISSUE THREAD

**Issue by ponnapureddy** [JoshClose/CsvHelper#532]
I am getting Out of memory exception while reading more than 1 Million records.

It would be great if you help me on this.

The following is the sample line of code.

var list = csv.GetRecords<T>().ToList();
If am doing wrong, please let me know what is the correct way to do this.

Thank you in advance.

**Comment by JoshClose** [comment]
You're loading everything into memory when doing a `ToList`. If you use the `IEnumerable` that is returned from `GetRecords` instead, only a single row will be in memory at a time.

**Comment by ponnapureddy** [comment]
Thanks for your support.

I wanted to do some operations (validation's, removing records from the
list, assigning some values to the properties, etc.) after reading the
records from CSV. That is the reason to converted to ToList.

Is there any better way to do the above type of operations without loading
into memory?. Please suggest me.

**Comment by jamesbascle** [comment]
Either a projection using Linq Select, or you can write your own streaming
mutator Linq extension.

**Comment by ponnapureddy** [comment]
Thanks for your reply.

I will check the possible scenarios.

**Comment by JoshClose** [comment]
Just be careful that your Linq expression doesn't iterate the collection multiple times. That won't work. ReSharper let's me know when I do that; not sure how else to tell. Sorting would definitely do it.

Is there anything that you need the entire set for? If you're just doing validation and property manipulation, you can do that one row at a time. If you need to do things on whole sets, you might need to write the data to disc first. Separate the data into multiple files based on some criteria, then work with smaller sets. This has now become a computer science problem. :)

**Comment by ponnapureddy** [comment]
Yes, You are correct :).

My scenario is like below.

If the object is invalid then I am removing the object from the list. The
list object is declared globally.
If the object is valid. Assigning some values to the object.

I am thinking to return yield result of valid object s instead of removing.

**Comment by JoshClose** [comment]
Did that work for you?
