### ISSUE TITLE
Indexed source information could not be retrieved

### ISSUE THREAD

**Issue by DOMZE** [JoshClose/CsvHelper#535]
When using TFS, there's an error that occurs that the Symbol indexes could not be retrieved after building. The project builds properly however. PDB doesn't affects the build, but since this generates an error, it fails in our Build Server.

Using symchk, I checked the DLL and the PDB to see if they matched and I get:
SYMCHK: CsvHelper.dll        FAILED  - CsvHelper.pdb mismatched or not found

SYMCHK: FAILED files = 1
SYMCHK: PASSED + IGNORED files = 0

Is this because of the move to DotNet CORE?

**Comment by JoshClose** [comment]
What .NET build are you using? I am using the dotnet core compiler now, so that very well could be the issue.

**Comment by DOMZE** [comment]
I am using .NET 4.5

**Comment by farinha** [comment]
I am having the exact same problem, using .NET 4.5 as well.

**Comment by JoshClose** [comment]
Can you download directly from NuGet and test the files there? I'll submit a bug to MS about it. I'm currently on a Mac (work...) and can't run symchk myself.

https://www.nuget.org/packages/CsvHelper/

**Comment by DOMZE** [comment]
I downloaded the project, compiled it and still no go.
I believe it has to do with the dotNet core compiler.

Thanks!

**Comment by JoshClose** [comment]
I just pushed 2.15.0.1 to NuGet. This is using the 1.0.0 release from today. Let me know if it still doesn't work, and I'll submit a bug with them.

**Comment by farinha** [comment]
I'm still getting the same problem with version 2.15.0.1 freshly installed from NuGet:

> Indexed source information could not be retrieved from C:\Builds\7\foo\bin\CsvHelper.pdb. Error: Symbol indexes could not be retrieved.

Build still works, but TFS reports it as "Partially Succeeded" because of this.

**Comment by JoshClose** [comment]
I'll install the windows sdk debugging tools and symchk it, then submit a bug to the .NET Core team.

**Comment by DOMZE** [comment]
*work around*: Since it's a 3rd party library, you don't need to have it
with the DLL. To fix it, just delete the pdb from the package source in TFS
and it will work (no partial success)

**Comment by JoshClose** [comment]
I changed the .NET versions 2-4.5 pdb files to be full and PCL and corefx are portable. If you're using PCL or corefx, TFS might still complain. Sounds like TFS might need to be updated.

Version 2.15.0.2 is out on NuGet with this fix.

Let me know how it works for you.

**Comment by farinha** [comment]
That fixed it, TFS no longer complains.

Thanks!
