### ISSUE TITLE
GetRecords<T> throws Format exception for null dates

### ISSUE THREAD

**Issue by iSaruchi** [JoshClose/CsvHelper#537]
Hi There,

I am using GetRecords<T> function and Entity Framework for the Template class .
There is a nullable dateTime property in the class.

While parsing the csv  (which has "null" data for that dateTime column )using GetRecords, i am getting Format exception : "The string was not recognized as a valid DateTime. There is an unknown word starting at index 0." 

```
Stack trace:    at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider, DateTimeStyles styles)
   at CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(TypeConverterOptions options, String text)
   at CsvHelper.TypeConversion.NullableConverter.ConvertFromString(TypeConverterOptions options, String text)
   at lambda_method(Closure )
   at CsvHelper.CsvReader.CreateRecord[T]()
   at CsvHelper.CsvReader.<GetRecords>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at HBServiceCodeMapper.Program.ProcessExcel(String filePath, DateTime startDate, DateTime modificationDate) in d:\REPOSITORY\StandAloneApps\trunk\HBServiceCodeMapper
```
Is there something i am doing wrong? or is it the null data?

**Comment by iSaruchi** [comment]
CSV data: SEQUENCE,DESCRIPTION,UNIQUE_IDENTIFIER,SERVICE_CODE,OP_NAME,CREATION_USER,CREATI‌​ON_DATE,MODIFICATION_DATE 10893,ABACO,T01-E-INTRACEOF,2100403,Abaco colonial villa,AREYNOLDS,6/20/2014 12:59,NULL when i parse this data.. i get the exception stated above and SEQUENCE,DESCRIPTION,UNIQUE_IDENTIFIER,SERVICE_CODE,OP_NAME,CREATION_USER,CREATI‌​ON_DATE,MODIFICATION_DATE 10893,ABACO,T01-E-INTRACEOF,2100403,Abaco colonial villa,AREYNOLDS,6/20/2014 12:59, when i parse this.. there is no exception and MODIFICATION_DATE column has null value

**Comment by JoshClose** [comment]
Can you give example code that reproduces? Thanks.

**Comment by SaruchiTest** [comment]
Hi Josh,

Thanks for your reply :)
I have following columns: 
SEQUENCE,DESCRIPTION,UNIQUE_IDENTIFIER,SERVICE_CODE,OP_NAME,CREATION_USER,CREATION_DATE,MODIFICATION_DATE

with data: 
10958,Ephesus & Virgin Mary's House,T01-E-EPHESUSIST,EPHESUSIST,Ephesus and Virgin Mary's house,RECEP,2013-02-07 15:03:31.0,null

For column Modification Date , i am given null value from customer. 

If i try the same data by replacing null with blank , i.e:
10958,Ephesus & Virgin Mary's House,T01-E-EPHESUSIST,EPHESUSIST,Ephesus and Virgin Mary's house,RECEP,2013-02-07 15:03:31.0, 

It parses perfectly fine. Could you please help me out with this issue?

Thanks ,
Saruchi

**Comment by SaruchiTest** [comment]
Hi Josh,

I think this is an issue with csvHelper only. If i try to use null as DateTime in .net, it works fine 

            DateTime ?d = null;
            Console.WriteLine(d);
Could you please help me out on this? Does CsvHelper support null data for date/time?

**Comment by JoshClose** [comment]
This will work in 3.0. `null` and `NULL` will now translate to a `null` value if the property type is nullable.
