### ISSUE TITLE
Compiling with UWP App project

### ISSUE THREAD

**Issue by ptC7H12** [JoshClose/CsvHelper#538]
When compiling this lib within a UWP App project I got a certification error:
The binary CsvHelper.dll is build in debug mode

So I can not submit my app to the store...

Can you help me please?

**Comment by JoshClose** [comment]
What version?

**Comment by ptC7H12** [comment]
I've tested it with 2.14.2...

**Comment by JoshClose** [comment]
2.14.3 should have that issue fixed.
