### ISSUE TITLE
Assembly.Load fails - undeclared dependency on System.Reflection.TypeExtensions

### ISSUE THREAD

**Issue by SurajGupta** [JoshClose/CsvHelper#539]
The nuget package for CSVHelper does not declare a dependency on System.Reflection.TypeExtensions. As such, calling Assembly.Load in a .net 461 project  throws an exception.  This assembly is not in the GAC.

**Comment by JoshClose** [comment]
Thanks. I'll take a look.

**Comment by JoshClose** [comment]
What version of CsvHelper are you using? It's showing it does have a dependency. https://www.nuget.org/packages/CsvHelper/

**Comment by SurajGupta** [comment]
It's not a dependency for .net framework 4.5, which is what would be used if CSVHelper is added to a .net 4.6.1 project.  It's listed as a dependency of .net standard 1.3.  Perhaps the issue is here:
https://github.com/JoshClose/CsvHelper/blob/815aa6b1a647e56e00c87a1c48a949b906a09423/src/CsvHelper/CoreFxCompatibility/TypeExtensions.cs

It seems that that file is compiled into the project if !NET_4_5.  Perhaps that check should only be for !COREFX (because if COREFX then the System.Reflection.TypeExtensions dependency is used)??

**Comment by JoshClose** [comment]
I'll see if that works tonight.

**Comment by JoshClose** [comment]
Are you doing `Assembly.Load` on the CsvHelper.dll? Or is that loaded and you're loading something else and it fails?

Also, can you try this again? There have been some changes to how it all builds.
