### ISSUE TITLE
CsvWriter does not respect CultureInfo when formatting doubles

### ISSUE THREAD

**Issue by kyberias** [JoshClose/CsvHelper#540]
For example:

```
var writer = new CsvWriter(textWriter, new CsvConfiguration
                {
                    QuoteNoFields = true,
                    CultureInfo = CultureInfo.InvariantCulture
                });
writer.WriteField(0.45);

```
I'm expecting the writer to format the number as "0.45", but it gets formatted as "0,45" as per my locale's culture info.

Finally, setting the thread's CultureInfo accomplishes what I want.

Shouldn't the writer's configuration's CultureInfo affect how numbers are formatted?

(using version 2.14.2 from a nuget package)

**Comment by JoshClose** [comment]
Can you check out the 3.0 beta in NuGet? I think it's fixed there. At least I can't reproduce it with this code.

```cs
void Main()
{
	System.Threading.Thread.CurrentThread.CurrentCulture = CultureInfo.GetCultureInfo( "de-DE" );
	
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		csv.Configuration.QuoteNoFields = true;
		csv.Configuration.CultureInfo = CultureInfo.InvariantCulture;
		csv.WriteField(0.45);
		csv.NextRecord();
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}
```
I get `0.45`. If I comment out the `CultureInfo.InvariantCulture` line, I get `0,45`.
