### ISSUE TITLE
[UWP] Compiling error since 2.14.3 

### ISSUE THREAD

**Issue by ptC7H12** [JoshClose/CsvHelper#542]
For using the CsvHelper with Version 2.14.3 and higher I had to Update "Microsoft.NETCore.UniversalWindowsPlatform" to Version 5.2 within my Project.
But now I get allways the following error  while compiling:

> 2>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : Unbehandelte Ausnahme: OutOfMemoryException.
> 2>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(318,5): error : ILT0005: "C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\tools\Gatekeeper.exe @"C:\Users\Ptc\Documents\Visual Studio 2015\Projects\ReaderApp\ReaderApp\obj\x86\Release\ilc\intermediate\gkargs.rsp"" hat den Exitcode 255 zurückgegeben

I tried many combinations to figure out, where it comes from...
When using 2.14.2 it compiles successfull, but with all higher Versions I get the error above - without changing any line of code or configuration...

**Comment by JoshClose** [comment]
I released a new version based on the final release of .NET Core 1.0. Does it still fail for you?

**Comment by ptC7H12** [comment]
Yes, it still fails...
It says OutOfMemory, but only 60% of memory is used... So it can't be the issue. Maybe a bug which appears in combination of UWP and CsvHelper?

**Comment by JoshClose** [comment]
Can you create a small example that reproduces the problem?

**Comment by ptC7H12** [comment]
Hi,
I've just tested it on 2.16.0 - the issue still exists.

This is the Link to the project (Empty UWP Project with added CsvHelper):
[https://www.dropbox.com/sh/mgkxqpdbxje2q6y/AAAj96CIJIy4hiK7fIxwLyeTa?dl=0](url)

**Comment by weipah** [comment]
Hi,

we had the same error when updating to DevHelper 2.16.0.
Switching back to 2.14.2 which we used before the project builds fine again.
One of the projects is also UWP.

The error message is very misleading, I tracked ressources on the server while building and everything was doing ok.

**Comment by JoshClose** [comment]
@ptC7H12 This fails to build? The example you gave builds fine for me.

**Comment by weipah** [comment]
@ptC7H12 do you build locally in your Visual Studio or via Continua CI for example on a server?

**Comment by ptC7H12** [comment]
@JoshClose yes, it fails for me...

@weipah I'm building locally and don't use DevHelper... Maybe one other package causes this issue

**Comment by weipah** [comment]
@ptC7H12 meant CsvHelper, corrected my writing above.

**Comment by ptC7H12** [comment]
@weipah On 2.14.2 I could compile, but got certification errors - 
[https://github.com/JoshClose/CsvHelper/issues/538](url)

**Comment by JoshClose** [comment]
I should check with the .NET Core team about TFS and the portable/UWP situation. I think TFS needs an update for it to work properly.

**Comment by ptC7H12** [comment]
@weipah I've checked again with 2.14.2 but still error at certification

**Comment by simonmunro** [comment]
I have the same issue as @ptC7H12. I found that it only happens when trying to build in release mode.

**Comment by mstahl77** [comment]
Any progress with this issue? 

I get these errors when I compile in Release mode with the newest CsvHelper version:
Error		Unhandled Exception: OutOfMemoryException.
Error		ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\tools\Gatekeeper.exe @"[myprojectdirectory]\obj\x86\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766

With version 2.14.2 the compilation succeeds, but the UWP certification fails with this error: "The binary CsvHelper.dll is built in debug mode."

Any workarounds?

**Comment by mstahl77** [comment]
Any progress with this issue?

I get these errors when I compile in Release mode with the newest CsvHelper version:
Error Unhandled Exception: OutOfMemoryException.
Error ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x86\ilc\tools\Gatekeeper.exe @"[myprojectdirectory]\obj\x86\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766

With version 2.14.2 the compilation succeeds, but the UWP certification fails with this error: "The binary CsvHelper.dll is built in debug mode."

Any workarounds?

**Comment by JoshClose** [comment]
I think it's the PDB files that are causing the problem. Go in to the CsvHelper package and delete all the `.pdb` files from all folders. Let me know if this works. I will change the NuGet release to not include them if it works.

**Comment by mstahl77** [comment]
I could not find any pdb files in the 2.14.2 package (only in newer packages). Maybe the certification process is looking at the Debuggable attribute in the assembly manifest:
![csvhelpermanifest](https://cloud.githubusercontent.com/assets/13456643/18111713/77eb3ab8-6f2a-11e6-8bda-d4583008ecd2.PNG)

I downloaded the source and compiled an own assembly in Release mode. I added a reference to that assembly and now the certification succeeded.

**Comment by JoshClose** [comment]
Can you download this version an try it?

https://drive.google.com/open?id=0B2NTBOwhHn-Ud0h1YjZhVjhKUDQ

**Comment by JoshClose** [comment]
I was able to reproduce it. I think I have a fix. I pushed version 2.16.1 to NuGet. Please let me know if it works.

**Comment by mstahl77** [comment]
Both compilation and certification were successful with 2.16.1. Thank you for a very fast fix!

**Comment by delsoftusa** [comment]
Hi, I've a UWP project for windows 10 mobile which was working just fine and deployed to windows store several times without issues. But suddenly it stopped compiling in release mode only with this error. Need your help please. I spent two days messing up my VS environment but nothing worked. Whats wrong?

**ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\ARM\ilc\tools\Gatekeeper.exe @"D:\Think Projects\ThinkUniversal\ThinkUniversal\obj\ARM\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766		
Unhandled Exception: OutOfMemoryException.**
