### ISSUE TITLE
Store exception details as properties on the exception

### ISSUE THREAD

**Issue by Neaox** [JoshClose/CsvHelper#543]
It seems that `Exception.Data` is not the best place to store details about the exception - like `Row`, `Type`, `FieldIndex`, `FieldName` and `FieldValue` - especially if the consumer/handler of the exception wants to reference/use these values - perhaps as a message returned to the user, for instance to allow them to fix the issues with the source data.

Instead these values should be stored on the Exception itself, whether these exist on the root `CsvHelperException` on a more specific exception will depend on in what situations these Exceptions are thrown and the data available in the stack.

You could still store them in `Exception.Data` but deprecated. And then remove them in a major release.

**Comment by JoshClose** [comment]
I agree. There is already a task to do this.
