### ISSUE TITLE
How to deal with "extended" fields

### ISSUE THREAD

**Issue by morganski** [JoshClose/CsvHelper#544]
Hello,

I'm reading batch files and would like to be able to read arbitrary fields in from the incoming .csv, so that my customers can add their own data. In the CSV I might have the following...

    Name, Age, Gender, X-CustField1, X-CustField2
    Fred Bloggs, 23, Male, Sausages, Aardvark
    Bill Muttley, 45, Male, Pizza, Duck Billed Platypus

So here the customer has added two additional fields, both denoted as extra fields using the `X-` prefix.

Now, I'd like to read this data into the following class...

    public class Person
    {
      public string Name { get; set; }
      public int Age { get; set; }
      public Gender Gender { get; set; }
      public JObject Extra { get; set; }
    }

I'm using a JObject as the extensible container for any field that is prefixed with `X-`. What I'd like to end up with is a JObject that serialises as follows...

    {
      CustField1: "Sausages",
      CustField2: "Aardvark"
    }

All I'm doing here is removing the field prefix and using the remainder of the "name" as the field name in JSON. So far so good.

Now, I have this all working - but just wondered if there was a better way to do what I'm doing. What I have done is altered the loop that gets records as follows...

    using (var reader = GetReader(tr))
    {
        List<string> extendedHeaders = null;

        while (reader.Read())
        {
            var record = reader.GetRecord<Person>();

            // Now read the extra gubbins...
            if (null == extendedHeaders)
                extendedHeaders = GetExtendedHeaders(reader);

            record.Extra = FromExtendedHeaders(reader, extendedHeaders);
        }
    }

    private static JObject FromExtendedHeaders(ICsvReader reader, List<string> extendedHeaders)
    {
        JObject extra = null;

        if (extendedHeaders.Any())
        {
            extra = new JObject();
            foreach(var header in extendedHeaders)
            {
                extra.Add(header.Substring(2), reader.GetField(header));
            }
        }

        return extra;
    }

The `GetExtendedHeaders` method simply iterates through the headers of the ICsvReader using the FieldHeaders property, and finds all that begin with `X-`. Then I manually construct the JObject based on the headers found.

This all works fine - I'm just wondering if there is a more elegant solution that I can use.

Many thanks in advance for your help!

**Comment by JoshClose** [comment]
Currently there is not. People have asked for a solution where you could specify a range of fields, maybe a start with no end, where all those values will get stored into a list property.

**Comment by morganski** [comment]
Thanks for the prompt response @JoshClose - I'll keep doing what I'm doing for now then. Cheers!
