### ISSUE TITLE
Runtime map with class containing readonly public properties and single ctor with all public properties

### ISSUE THREAD

**Issue by jcasale** [JoshClose/CsvHelper#545]
I am trying to parse records and create objects for a class which I create a runtime map for using operator supplied values for csv column to property names. The class only has public getters, all parameters must be supplied in the ctor. What options do I have to use such a class?

**Comment by JoshClose** [comment]
Currently, I don't think there is a way to do it. There is a `ConstructUsing` mapping, but you don't get anything from the row in it to pass into the constructor. That may be something I can add in the future.

What you can do is this.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
	
		csv.Configuration.IgnorePrivateAccessor = true;
		csv.Configuration.RegisterClassMap<TestMap>();
		var records = csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public int Id { get; private set; }

	public string Name { get; private set; }

	private Test() {}

	public Test(int id, string name)
	{
		Id = id;
		Name = name;
	}
}

public class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
	}
}
```

The default constructor can be private, and it works. If for some reason you can't use a default constructor, you could use the `ConstructUsing` mapping and just pass in defaults.

**Comment by jcasale** [comment]
I can probably add the private elements to the contract without an issue, thanks for the detailed solution.
