### ISSUE TITLE
Mapping an inherited property to another name causes duplicate columns

### ISSUE THREAD

**Issue by cdanne** [JoshClose/CsvHelper#547]
I have a custom class map that uses .Name("") to map properties to specic column names. This works as expected for all properties of the entity class itself. 
The class also has some inherited properties from an abstract base class. Mapping these to a different name causes the data to appear twice in the output file, one column with the original name, and another column with the custom name from the mapping.

Is there a reason for this behaviour? 
And: is there a way to work around this?

**Comment by cdanne** [comment]
One addition: I use the .Name() Mapping after having done an AutoMap(). Seems that the issue is related to the combination of auto-mapping and specific mappings. Mappings for regular properties are overwritten, for inherited properties, an additional column is added.

**Comment by JoshClose** [comment]
Can you give a short example that reproduces the issue?

**Comment by JoshClose** [comment]
I can't reproduce it. If you can give me an example that reproduces it, I'll take a look.

Here is the example I tried.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Id = 1, Name = "one" },
			new Test { Id = 2, Name = "two" }
		};
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set;}
}

public class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		AutoMap();
		Map( m => m.Name ).Name("NewName");
	}
}
```

**Comment by cdanne** [comment]
Hi Josh,

sorry for not providing an example. By now I have worked around the issue another way, but using your example I tried to reproduce the issue and did not succeed.
My setup was different in the way I tried to change the name of a property which is inherited from an abstract base class. My example was more complex, and I admit that the issue cannot be reproduced easily. This is what I tried, but the result is as desired, a new column name for the Id attribute:

`        static void Main(string[] args)
        {
            using (var stream = new MemoryStream())
            using (var reader = new StreamReader(stream))
            using (var writer = new StreamWriter(stream))
            using (var csv = new CsvWriter(writer))
            {
                var records = new List<Test>
                {
                    new Test {Id = 1, Name = "one"},
                    new Test {Id = 2, Name = "two"}
                };

                csv.Configuration.RegisterClassMap<TestMap>();
                csv.WriteRecords(records);
                writer.Flush();
                stream.Position = 0;

                Console.WriteLine(reader.ReadToEnd());
            }

            Console.ReadKey();
        }

        public abstract class TestBase
        {
            public int Id { get; set; }
        }

        public class Test : TestBase
        {
            public string Name { get; set; }
        }

        public class TestMap : CsvClassMap<Test>
        {
            public TestMap()
            {
                AutoMap();
                Map(m => m.Id).Name("NewId");
            }
        }`
