### ISSUE TITLE
Make HasBeenRead Publicly Accessible

### ISSUE THREAD

**Issue by tomwarner13** [JoshClose/CsvHelper#548]
We recently ran into an issue in CsvReader.cs when we wanted to log detailed information about reader errors. The header row threw an error consuming a certain third-party CSV file, but this meant when we tried to record the row number, the reader threw an error from CheckHasBeenRead() on line 1125, since no data had successfully been read.

We realized that we need to ensure data was successfully read before logging detailed information about said data, however, there is currently no public property which indicates whether any data was successfully read. It's trivial to implement in our code (just set a bool to true after the first successful call to Read()) but it would be neat if we didn't have to.

Created #549 since it's a minor change.

**Comment by JoshClose** [comment]
I'm thinking maybe it just shouldn't throw an exception. The only time it's useful is if you try and access the row and a read hasn't happened. Seems almost pointless to me now.

**Comment by JoshClose** [comment]
`CurrentRecord` and `Row` would be the 2 that would have this check removed.

**Comment by tomwarner13** [comment]
That makes sense to me, want me to update the PR?

**Comment by tomwarner13** [comment]
PR Updated

**Comment by JoshClose** [comment]
Thanks!
