### ISSUE TITLE
Embedded CarriageReturn/LineFeed in Quotes

### ISSUE THREAD

**Issue by rmgalante** [JoshClose/CsvHelper#550]
I'm using version 2.16. I have a CSV file with embedded CR/LF between quotes. But the CsvParser is not reading the line correctly. I breaks at the embedded CR/LF instead of the last one on the line.

**Comment by JoshClose** [comment]
Are the fields that contain line breaks quoted?

**Comment by rmgalante** [comment]
Yes they are. That’s why I reported it.

And thanks for your quick response.

Rob

**Comment by JoshClose** [comment]
Can you give me an example that reproduces the issue?

**Comment by JoshClose** [comment]
Example CSV files, that is. Only needs to be 1 or 2 lines or whatever.

**Comment by rmgalante** [comment]
I have attached a small CSV file with one record that exhibits the problem. I am importing a csv file with UTF-8 characters in it. It’s a translations file.

Here is the code I’m using to read it. It looks like the closing double quote has been stripped off the first column.

private string[] ReadCsvFile(string cFile)
{
    List<string> lines = new List<string>();

    using (TextReader reader = File.OpenText(cFile))
    {
        CsvHelper.CsvParser parser = new CsvHelper.CsvParser(reader);
        while(true)
        {
            var row = parser.Read();
            if (row == null)
                break;
            lines.Add(string.Join(",", row));
        }
    }
    return lines.ToArray();
}

The array of strings is parsed and written to a database.

By the way, I’ve imported 200k records with this helper. So I’m not complaining.

Rob

**Comment by JoshClose** [comment]
I don't think attaching will work through github. I don't see the file here.

**Comment by rmgalante** [comment]
Looks like the bug is mine. That string.Join statement is stripping off the double quotes.

**Comment by JoshClose** [comment]
Glad you figured it out!

**Comment by rmgalante** [comment]
Here is a short CSV file that exhibits a problem for me. I'm getting 28 columns instead of the 17 I expect when I read.

Key,Type,Desc,English (United States),Arabic,Chinese (Simplified),Chinese (Traditional),French (France),German (Germany),Indonesian,Italian (Italy),Japanese,Korean,Portuguese (Brazil),Spanish (Mexico),Turkish,Vietnamese
"An email has been sent with instruction for verifying this email address. 
Note, you will not be able to login until you complete the verfiication process.",Text,,"An email has been sent with instruction for verifying this email address. 
Note, you will not be able to login until you complete the verification process.","تم إرسال رسالة بريد إلكتروني مع
تعليمات للتحقق من
عنوان البريد الإلكتروني هذا.
ملاحظة أنك لن تكون قادرة
للدخول حتى الانتهاء
عملية التحقق.",一封含有验证码的电子邮件已经发送至该电子邮件地址。请注意：完成验证程序后您才可登录。,一封含有驗證指令的電子郵件已經發送至此電子郵件。請注意，完成驗證後您才可登入頁面,"Un courriel a été envoyé à l'instruction de vérifier cette adresse email.
Notez que vous ne serez pas capable de se connecter jusqu'à ce que vous terminez le processus de vérification.","Eine Email ist mit der Anweisung zur Überprüfung der diese E-Mail-Adresse gesendet.
Beachten Sie, werden Sie nicht in der Lage, anmelden, bis Sie den Bestätigungsprozess abzuschließen.","Sebuah email telah dikirim dengan instruksi untuk memverifikasi alamat email ini.
Catatan, Anda tidak akan bisa login sampai Anda menyelesaikan proses verifikasi.","Una e-mail è stata inviata con le istruzioni per verificare questo indirizzo email.
Nota, non sarà in grado di accedere fino a completare il processo di verifica.","電子メールは、この電子メールアドレスを検証するための命令で送信されました。
あなたは、検証プロセスを完了するまでにはログインすることができません、注意してください。","이메일이 이메일 주소를 확인하기위한 명령으로 보냈습니다.
당신이 확인 프로세스를 완료 할 때까지 당신은 로그인 할 수 없습니다, 참고.","Um e-mail foi enviado com instruções para verificar este endereço de e-mail.
Nota, você não será capaz de acessar até concluir o processo de verificação.","Un correo electrónico ha sido enviado con instrucciones para la verificación de esta dirección de correo electrónico.
Tenga en cuenta, no podrá iniciar sesión hasta que se complete el proceso de verificación.","Bir e-posta Bu e-posta adresini doğrulamak için talimat gönderildi.
Doğrulama işlemini tamamlamak kadar giriş mümkün olmayacaktır unutmayın.","Một email được gửi đi với hướng dẫn để xác minh địa chỉ email này.
Lưu ý, bạn sẽ không thể đăng nhập cho đến khi bạn hoàn tất quá trình xác minh.

**Comment by JoshClose** [comment]
Is it working for you now then?

When I run this code I get 17 columns.
```cs
void Main()
{
	using (var stream = File.OpenRead(@"C:\Users\Josh\Desktop\test.csv"))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		csv.GetRecords<dynamic>().ToList().Dump();
	}
}
```

**Comment by rmgalante** [comment]
I'm using the CsvParser and the Read method. I get 28 columns.

**Comment by JoshClose** [comment]
When using the parser directly, I'm seeing 17 in the first row, and 18 in the second.

```cs
void Main()
{
	using (var stream = File.OpenRead(@"C:\Users\Josh\Desktop\test.csv"))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvParser(reader))
	{
		csv.Read().Dump();
		csv.Read().Dump();
	}
}
```

**Comment by rmgalante** [comment]
Yes, it is a bug in my code. The string.Join was removing the double quotes from the column values. I changed my logic to the following:

private List<string[]> ReadCsvFile(string cFile)
{
    List<string[]> lines = new List<string[]>();

    using (TextReader reader = File.OpenText(cFile))
    {
        CsvHelper.CsvParser parser = new CsvHelper.CsvParser(reader);
        while(true)
        {
            var row = parser.Read();
            if (row == null)
                break;
            lines.Add(row);
        }
    }
    return lines;
}

**Comment by JoshClose** [comment]
Ok, thanks!
