### ISSUE TITLE
On same clients machine I get extra ,,,, at the end

### ISSUE THREAD

**Issue by benaichouchem** [JoshClose/CsvHelper#554]
On Some clients machine, instead of getting the header (and all the other lines) just like this:

> Name;Id;Cost;Price;CurrentQuantity

I get this
>Name;Id;Cost;Price;CurrentQuantity,,,
``
Any ideas? I am unable to reproduce locally.

**Comment by TamusJRoyce** [comment]
Do you have a link to .csv file from the client having the issue? Not copy-pasted as text, as there could be extended characters that are lost. Need to keep the binary data intact.

Also, do you have version numbers of CsvHelper on the client machines? Maybe a bug in the past that is no longer present? Or even a recently introduced bug?

**Comment by benaichouchem** [comment]
We use CsvHelper in our web app to allow them to download their data. I don't have this issue when I try to reproduce it.  What kind data should I paste?

**Comment by TamusJRoyce** [comment]
Web app was the information not given. I'm assuming asp.net? or rest (like owin / katana or wcf)? I'm not as familiar with those as I should be. My guess would be whatever is streaming the .csv isn't in binary mode (Octet-stream). Or maybe it is browser specific? Maybe browser type w/ same version #, or impersonating the user having issues would get the error to reproduce.

Sorry for not being of more help. I will let someone else that might have and answer do so.

**Comment by benaichouchem** [comment]
Thanks @TamusJRoyce . Yes it is Asp.Net MVC. I tried with IE, Chrome. The user complains that he sees it with all browser. I am suspecting more a Culture issue.

MemoryStream stream = csvExporter.ExportStockTake(inventory, _context);

            var filename = "stocktake.csv";
            var contenttype = "text/csv";
            Response.Clear();
            Response.ContentType = contenttype;
            Response.AddHeader("content-disposition", "attachment;filename=" + filename);
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.BinaryWrite(stream.ToArray());
            Response.End();

**Comment by JoshClose** [comment]
Can you see what the CSV data is before it's put through the response?

**Comment by benaichouchem** [comment]
HI @JoshClose client can't reproduce this issue. And was never able to reproduce it. I will close  the issue
