### ISSUE TITLE
Override existing CsvPropertyMap on successive calls to RegisterClassMap<>()

### ISSUE THREAD

**Issue by rstuppi** [JoshClose/CsvHelper#555]
As a software developer using CsvHelper, I would like to override an existing CsvPropertyMap so that I do not have to recreate an entire CsvClassMap just to change the behavior of one mapping. For example:
```c#
private class PersonMappings : CsvClassMap<Person>
{
    public PersonMappings()
    {
        Map(c => c.Id);
        Map(c => c.FirstName);
        Map(c => c.MiddleName).ConvertUsing(SomeFunc);
        Map(c => c.LastName);
    }
}

private class PersonMappingsConvertMiddleName : CsvClassMap<Person>
{
    public PersonMappingsConvertMiddleName()
    {
        Map(c => c.MiddleName).ConvertUsing(SomeOtherFunc);
    }
}

Usage:

Configuration.RegisterClassMap<PersonMappings>();
Configuration.RegisterClassMap<PersonMappingsConvertMiddleName>();
```
Result:
   Map(c => c.Id);
   Map(c => c.FirstName);
   Map(c => c.MiddleName).ConvertUsing(SomeOtherFunc);
   Map(c => c.LastName);
 

We have an implementation and tests if you are interested.

**Comment by JoshClose** [comment]
I'm confused on your goal here and what you currently aren't able to do.

Do you want to be able to register a 2nd mapping for the same class that inherits the original map, just for the purposes of overriding the mapping?

**Comment by rstuppi** [comment]
Our goal is to map 106 different CSV formats onto the same class and to set a default value of null for those class properties that are either missing from the CSV file or are empty in the CSV file.

class MyClass
{
   string property1;
   string property2: 
   string property3;
   string property4;
}

For example:

   Format1.csv  (4 fields)
      ECMR,"Nissan Micra 3/5Dr",Budget,SUCCESS_001

   Format2.csv (3 fields)
      “Full-Size”,"Ford Expedition SUV or similar",SUCCESS_001 (3 fields)

   Format3.csv (4 fields, 2nd empty and last missing)
      "Mid Size Sedan Auto",””,ApexRentals,


Using CsvHelper, is it possible to ensure that regardless of the CSV format, we always end up with a properly initialized instance of MyClass?:

Format1.csv result:
   MyClass.property1 = “ECMR”;
   MyClass.property2 = "Nissan Micra 3/5Dr";
   MyClass.property3 = “Budget”;
   MyClass.property4  = “SUCCESS_001”;

Format2.csv result:
   MyClass.property1 = "Full-Size"
   MyClass.property2 = "Ford Expedition SUV or similar"
   MyClass.property3 = “SUCCESS_001”;
   MyClass.property4  = null;

Format3.csv result:
   MyClass.property1 = "Mid Size Sedan Auto";
   MyClass.property2 = null; 
   MyClass.property3 = “ApexRentals”;
   MyClass.property4  = null;

**Comment by JoshClose** [comment]
Are the property names really generic like that? Are the fields all strings?

**Comment by rstuppi** [comment]
No, just an example.

**Comment by rstuppi** [comment]
Sorry, fat fingered the previous comment.

Our goal is to map 106 different CSV formats onto the same class and to set a default value of null for those class properties that are either missing from the CSV file or are empty in the CSV file.

class MyClass
{
string property1;
string property2: 
string property3;
string property4;
}

For example:

Format1.csv (4 fields)
ECMR,"Nissan Micra 3/5Dr",Budget,SUCCESS_001

Format2.csv (3 fields)
“Full-Size”,"Ford Expedition SUV or similar",SUCCESS_001

Format3.csv (4 fields, 2nd empty and last missing)
"Mid Size Sedan Auto",””,ApexRentals,

Using CsvHelper, is it possible to ensure that regardless of the CSV format, we always end up with a properly initialized instance of MyClass?:

Format1.csv result:
MyClass.property1 = “ECMR”;
MyClass.property2 = "Nissan Micra 3/5Dr";
MyClass.property3 = “Budget”;
MyClass.property4 = “SUCCESS_001”;

Format2.csv result:
MyClass.property1 = "Full-Size"
MyClass.property2 = "Ford Expedition SUV or similar"
MyClass.property3 = “SUCCESS_001”;
MyClass.property4 = null;

Format3.csv result:
MyClass.property1 = "Mid Size Sedan Auto";
MyClass.property2 = null; 
MyClass.property3 = “ApexRentals”;
MyClass.property4 = null;

**Comment by JoshClose** [comment]
With some classes a property needs to be mapped differently though? So, one map has a straight value assignment, but another map needs to do so work using `ConvertUsing`?

You can auto map and just change the values you want. Would that work?

```cs
AutoMap();
Map( m => m.Property2 ).ConvertUsing( row => ... );
```

**Comment by rstuppi** [comment]
Can Map(...).ConvertUsing(...) be used outside of a CsvClssMap?

**Comment by JoshClose** [comment]
```cs
void Main()
{	
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
	
		var map = new DefaultCsvClassMap<Test>();
		map.AutoMap();
		map.Map(m => m.Id).ConvertUsing(row => int.Parse(row.GetField(0)));
		
		csv.Configuration.HasHeaderRecord = false;
		csv.Configuration.RegisterClassMap(map);
		
		csv.GetRecords<Test>().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by rstuppi** [comment]
Yes, that works.

Also, our Rate class lacked a default constructor and as such, members were of course initialized with their type defaults.  Defining a default constructor allowed us to initialize all properties to null.  We now  only have to add Default(null) to the mapping.

Anyway, as it turns out, CsvHelper satisfies our requirements "as-is".  Thank you for your help and thank you for creating such a useful tool!

**Comment by JoshClose** [comment]
You can use `ConstructUsing` to do construction of a non empty constructor. Currently the row isn't passed to it though, which I need to change.
