### ISSUE TITLE
UTC Dates from non-standard ISO representation

### ISSUE THREAD

**Issue by InsidiousForce** [JoshClose/CsvHelper#557]
Hi, I have a file that has dates like this:

value,2010-04-26 09:55:37,value
value,2016-02-19 21:38:40,value

I was surprised that these mapped to DateTime field with no problem. The issue is that the dates in the file are all UTC and they load into the DateTime in the local timezone. I need to dump them into a database and the dates need to be UTC. I know this isn't standard representation of UTC date, and the data can't easily be changed from the sources, and the final program could run in locations with different local timezones. I don't see an option for tweaking the date import.

**Comment by JoshClose** [comment]
In your mapping for the property, set a type converter option.

```cs
Map( m => m.DateTimeProperty ).TypeConverterOption( DateTimeStyles.AssumeUniversal );
```

**Comment by InsidiousForce** [comment]
I'm sorry, somehow I missed that whole TypeConverter section of the doc. Appreciate the answer.

**Comment by JoshClose** [comment]
No worries. I think that section is empty in the docs anyways. ;)
