### ISSUE TITLE
Is there an AssertAllFieldsDefined in Map?

### ISSUE THREAD

**Issue by billrob** [JoshClose/CsvHelper#559]
I need to be explicit to ensure I didn't miss any properties for my map class.  I have over 100 properties and need explicit control over the header naming and ordering.  I found there was a way to trigger exception if a field was read that wasn't defined, but what about writing?

This would be _kinda_ similar to AutoMapper.AssertConfigurationIsValid() type call.

**Comment by JoshClose** [comment]
Not today. The one or the reading side throws an exception if there are fields in the CSV file that don't match with your mappings.

Having some sort of mapping validation method would be useful. I'll mark this as a feature.

**Comment by JoshClose** [comment]
I think I would like this in the contrib project. There is probably more validation that could be done too.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#5

**Comment by jamesbascle** [comment]
I actually have code to do this in my architrctural tests...I will check to
see if I can open source it.
