### ISSUE TITLE
NuGet package versioning

### ISSUE THREAD

**Issue by maartenba** [JoshClose/CsvHelper#565]
The CsvHelper NuGet packages are using a weird versioning scheme. E.g. `3.0.0.0-beta1` can't be opened using my version of NuGet Package Explorer, as there is a "0" too much in there. Can versioning be updated to use SemVer instead (x.y.z-prerelease)?

**Comment by JoshClose** [comment]
Sure. I should be putting another version out in the next day or so here, and I'll do that.

**Comment by maartenba** [comment]
Awesome! Thanks Josh!

**Comment by JoshClose** [comment]
It's out there along with some new features.
