### ISSUE TITLE
GetRecord<T> Keeps Throwing Null Reference Exception 

### ISSUE THREAD

**Issue by jenaewhitmore** [JoshClose/CsvHelper#566]
This is the code I'm using to retrieve my records. I have the data variable there to test if all the information is properly retrieved. Version 2.16.0.0.

using (var csv = new CsvReader(File.OpenText(@"C:\Users\jwhitmore\Desktop\Test.csv")))
            {
                csv.Configuration.RegisterClassMap<TestMetaDataMap>();
                csv.Read();
                var data = csv.GetRecord<TestMetaData>();   
            }

My TestMetatDataMap Class (shortened for brevity):
 public sealed class TestMetaDataMap : CsvClassMap<TestMetaData>
    {
        public TestMetaDataMap()
        {
            Map(t => t.DocumentNameText).Ignore();
            Map(t => t.DocumentTypeText).Ignore();
            Map(t => t.DocumentDateText).Ignore();
            Map(t => t.BrowserName).Index(3);
            Map(t => t.Version).Index(4);
            Map(t => t.Alpha25).Index(5);
            Map(t => t.Currency).Index(6);
            Map(t => t.Date).Index(7);
            Map(t => t.DateTime).Index(8);
      }

My Custom Class (shortened for brevity):

 public sealed class TestMetaData : ObjectMetaData
    {
        public string DocumentNameText { get; set; }
        public string DocumentTypeText { get; set; }
        public  string DocumentDateText { get; set; }
        public string BrowserName { get; set; }
        public string BrowserNameValue { get; set; }
        public string Version { get; set; }
        public string VersionValue { get; set; }
        public string Alpha25 { get; set; }
        public string Alpha25Value { get; set; }
        public string Currency { get; set; }
        public string CurrencyValue { get; set; }
    }

Im not doing anything special in my custom class and I cant figure out why it keeps throwing null reference exception when GetRecord<TestMetaData> is called??

**Comment by jenaewhitmore** [comment]
Never mind I just had to set csv.Configuration.HasHeaderRecord = false; since I need the values of my header row.

**Comment by JoshClose** [comment]
So you have a header row, but you need to know what the values are? There is a property `ICsvReader.FieldHeaders` that has the headers in it.

For mapping, you don't need to `Ignore` anything unless it's already been mapped. This only comes into play when auto mapping occurs. If you had a lot of fields that all fall into the default mapping structure, you could do `AutoMap()` and just `Ignore()` the couple fields you don't want mapped.

**Comment by jenaewhitmore** [comment]
Thanks for the quick response! Yea to I have a header row where I only want some of the value, the first 3 header values I don't need, but the last 10+ I do need to populate a dictionary<string,string>. Would there be a better way to do that using auto-mapping? I didn't see any examples that really fit my needs.
Thanks for the tip on Ignore, it saved me lines of code in the end.
