### ISSUE TITLE
Cleanly get specific Header Data

### ISSUE THREAD

**Issue by jenaewhitmore** [JoshClose/CsvHelper#567]
I have a file structure like this:

DocName, DocDate, KeywordName1, KeywordName2
Test, 2/25/15. KeywordValue1, KeywordValue2

I need the KeywordNames and Keyword Values to populate a Dictionary<string, string>, but I don't need the DocName and DocDate Headers. 

I want my Model Class to be populated like:

string DocName {get; set}// only need the row value and not the column header
string DocDate {get; set}// only need the row value and not the column header
Dictionary<string, string> Keywords {get; set} // need the column header and column value as key/value

**Comment by JoshClose** [comment]
I recently added the ability to map to enumerables. It's in the pre-release in NuGet. I didn't add dictionary support because I couldn't think of a way to use that. This should be a fairly quick thing to do now that I have all the groundwork done for it.

**Comment by JoshClose** [comment]
This is done. It's in version 3.0.0-beta4 on NuGet.
