### ISSUE TITLE
config.ShouldSkipRecord Func overrides config.SkipEmptyRecords = true

### ISSUE THREAD

**Issue by elvishfiend** [JoshClose/CsvHelper#575]
This is problematic when using ShouldSkipRecord to skip non-empty non-data rows.
This seems like unexpected behaviour, and doesn't seem to be documented anywhere. It can only be determined by checking the source code directly.

Ideally the two should be completely independent, with SkipEmptyRecords = true causing empty rows to be skipped even if config.ShouldSkipRecord would not cause the row to be skipped and vice versa.

Example:
csv file:

    date, name, address
    skip this row, ,
    ,,
    13/09/2016, test name, test address

config:

    config.ShouldSkipRecord = (x) => { return x[0].StartsWith("skip"); };
    config.SkipEmptyRecords = true;`

should result in 1 record being produced, but currently results in 2 records, with the first being completely empty.

**Comment by JoshClose** [comment]
Merged.
