### ISSUE TITLE
Inheritance mapping

### ISSUE THREAD

**Issue by mrwillis** [JoshClose/CsvHelper#578]
Hi,

First off thanks for this library. It's incredible. Sorry if this is trivial but I just can't figure it out.

I have a parent class 

```
  public abstract class StructuredNote
    {
        public int Term { get; set; }
        public decimal Fee { get; set; }
        public DateTime AsOfDate { get; set; }
    }
```
with a map

```
   public sealed class StructuredNoteMap : CsvClassMap<StructuredNote>
    {
        public StructuredNoteMap()
        {
            Map(m => m.Fee).Name("sim_fee");
            Map(m => m.AsOfDate).Name("AsOfDate");
            Map(m => m.Term).ConvertUsing(row =>
            {
                int term;
                if (!row.TryGetField("sim_term", out term))
                {
                    if (row.GetField<string>("sim_term").Any(Char.IsLetter))
                        // parse failed so check if there are letters.
                    {
                        // Remove the letter and just take the integer.
                        return Int32.Parse(Regex.Match(row.GetField<string>("sim_term"), @"\d+").Value);
                    }
                    // Otherwise there are no letters and it can't be converted.
                    return -1;
                }
                return term;
            });
        }
    }
```

and a child class

```
 public class EquityLinkedNote: StructuredNote
    {
        public virtual List<VanillaOption> VanillaOptions { get; set; }

    }
```

with its own map:

```
 public sealed class EquityLinkedMap : CsvClassMap<EquityLinkedNote>
    {
        public EquityLinkedMap()
        {
            Map(m => m.VanillaOptions).ConvertUsing(row =>
            {
                const string baseOptionString = "sim_option";
                List<VanillaOption> options = new List<VanillaOption>();
                for (int i = 1; i < 120; i++)
                {
                    VanillaOption option = MapHelper.GetOptionFromRow(row, baseOptionString + i);
                    if (option != null)
                        options.Add(option);
                }

                return options;
            });
        }
    }
```
How can I access the mappings from my parent class in my child class? I've tried registering multiple class maps but I realize that not what I'm looking for. Is there a way to inherit the mappings or something? 

Thanks for your help.

**Comment by JoshClose** [comment]
What is the reason for doing this? Do you not want to have to do the same map configuration a second time?

**Comment by mrwillis** [comment]
Yeah essentially. I have a class with a bunch of derived classes and a lot of the fields are repeated with one or two extra fields in the csv files. I read your thread here [https://groups.google.com/forum/#!topic/csvhelper/l7B-jXOULrg](url) but couldn't figure it out if it was the same thing or not. If it can't be done, it's really not a big deal -I was just wondering if there was support for this.

**Comment by JoshClose** [comment]
Sounds like it, but they're creating their own `CsvClassMap` or editing the source.  There isn't a built in way to do this currently. You could pass a map into the contstructor of another map and copy all the it's mappings. That would be easy enough. I'll see if I can whip up an example.

**Comment by jamesbascle** [comment]
Check this code out.

public class FooMap<T> : CsvClassMap<T> where T : Foo
    {
        public FooMap()
        {
            Map(m => m.P1).Name("P1");
            Map(m => m.P2).Name("P2");
        }

        public class V1<T0> : FooMap<T0> where T0 : Foo.V1
        {
            public V1()
            {
                Map(m => m.P3).Name("P3");

            }
        }
    }

    public class Foo
    {
        public string P1 { get;  set; }
        public string P2 { get;  set; }

        public class V1 : Foo
        {
            public string P3 { get; set; }
        }
    }

**Comment by JoshClose** [comment]
Here is an example copying an existing map.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name");
		writer.WriteLine("1,one");
		writer.Flush();
		stream.Position = 0;
		
		var parentMap = csv.Configuration.RegisterClassMap<ParentMap>();
		var childMap = new ChildMap( parentMap );
		csv.Configuration.RegisterClassMap( childMap );
		
		csv.GetRecords<Child>().ToList().Dump();
	}
}

public class Parent
{
	public int Id { get; set;}
}

public class Child : Parent
{
	public string Name { get; set;}
}

public class ParentMap : CsvClassMap<Parent>
{
	public ParentMap()
	{
		Map( m => m.Id );
	}
}

public class ChildMap : CsvClassMap<Child>
{
	public ChildMap( CsvClassMap map )
	{
		// Copy existing map data.
		PropertyMaps.AddRange( map.PropertyMaps );
		ReferenceMaps.AddRange( map.ReferenceMaps );
		
		Map( m => m.Name );
	}
}

```

**Comment by JoshClose** [comment]
I like James' way better.

**Comment by mrwillis** [comment]
Great. Thanks for the help guys. I'm not sure about the class nesting to be honest. I like your solution Josh. Basically exactly what I was looking for.

**Comment by JoshClose** [comment]
Here is an un-nested version of James' code.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("P1,P2,P3");
		writer.WriteLine("1,2,3");
		writer.Flush();
		stream.Position = 0;

		csv.Configuration.RegisterClassMap<ParentMap<Parent>>();
		csv.Configuration.RegisterClassMap<ChildMap<Child>>();

		csv.GetRecords<Child>().ToList().Dump();
	}
}

public class Parent
{
	public string P1 { get; set; }
	public string P2 { get; set; }
}

public class Child : Parent
{
	public string P3 { get; set; }
}

public class ParentMap<T> : CsvClassMap<T> where T : Parent
{
	public ParentMap()
	{
		Map(m => m.P1).Name("P1");
		Map(m => m.P2).Name("P2");
	}
}

public class ChildMap<T> : ParentMap<T> where T : Child
{
	public ChildMap()
	{
		Map(m => m.P3).Name("P3");
	}
}
```

**Comment by jamesbascle** [comment]
Yeah there's no need for the nesting, I was just being lazy.  A normal
hierarchy will work just fine.

**Comment by mrwillis** [comment]
Thanks everyone. This actually makes a lot of sense.

Julian

**Comment by gandhis1** [comment]
Correct me if I'm wrong, but it seems the limitation with this approach is that you must map every member, and cannot fall back to `AutoMap()`. In my particular case, there are a number of fields which map perfectly fine with the default auto-mapping, and then I have to go back and manually override the map with specific names for some fields.

If I call `AutoMap()` in the derived class, then it will just override any mappings done in the base construcotr. Is there a way to just map anything that is not already mapped?
