### ISSUE TITLE
Writing incomplete CSVs

### ISSUE THREAD

**Issue by gregsdennis** [JoshClose/CsvHelper#581]
This seems to be happening with every set of data that I write.  The output I get is most of the data, but the last record written is always partial.  Some of the fields aren't written at all, sometimes only part of a field is written.

I get something like

    FirstName,LastName,Age
    John,Smith,36
    Jane,Smith,33
    Alex,Smith,8
    Barry,Smi

Most of the time there several more full records to write.

**Comment by JoshClose** [comment]
My guess without seeing any code examples is that you're not flushing the writer. `StreamWriter.Flush()`

If you're doing that, please post some example code that reproduces the issue.

**Comment by gregsdennis** [comment]
I'm not using a stream.  Simply creating a new writer with the filename and immediately writing items.

    new CsvWriter(filename).WriteRecords(items);

I'll try the streamed approach.

**Comment by gregsdennis** [comment]
Looks like that did the trick.  Thanks.

**Comment by JoshClose** [comment]
Great. I would recommend wrapping the code in a `using` block. Streams get flushed automatically at the end of a using block.

**Comment by gregsdennis** [comment]
This such noob stuff.  I feel ashamed to call myself a seasoned developer. :)

**Comment by JoshClose** [comment]
Lol. No worries. I forget about flushing the stream when I run into a situation where I can't use a using block. I'm so used to using them, that I forget I need to flush.
