### ISSUE TITLE
CsvHelper doesn't write large file (Stream was too long)

### ISSUE THREAD

**Issue by apranovich** [JoshClose/CsvHelper#582]
When I'm trying to write very large amount of data (~300 000 rows) to csv file, it throws the exception "**Stream was too long.|System.IO.IOException: Stream was too long.**".
Data class is rather big and has ~30 properties, consequently each record in the file has ~30 columns.

This is the actual writing code where exception throws:

```
using (var memoryStream = new MemoryStream())
{
    using (var streamWriter = new StreamWriter(memoryStream, encoding ?? Encoding.ASCII))
    {
        var csvWriter = new CsvWriter(streamWriter, GetConfiguration(delimiter, mappingClassType, mappingActions));
         csvWriter.WriteRecords(data);

         streamWriter.Flush();
         return memoryStream.ToArray();
    }
}
```

Please note, that the same **code works well when I write 100 000 records** to the file (in that case file has size about 1GB). By the way, my goal is to write more then 600 000 data records.

This is the relevant part of the stack trace related to this issue.
```
Stream was too long.|System.IO.IOException: Stream was too long.
at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
at CsvHelper.CsvWriter.NextRecord() in C:\Users\Josh\Projects\CsvHelper\src\CsvHelper\CsvWriter.cs:line 290
at CsvHelper.CsvWriter.WriteRecords(IEnumerable records) in C:\Users\Josh\Projects\CsvHelper\src\CsvHelper\CsvWriter.cs:line 490
at FileExport.Csv.CsvDocument.Create[T](IEnumerable`1 data, String delimiter, Encoding encoding, Type mappingClassType, IDictionary`2 mappingActions) in d:\Dev\DrugDevExport\FileExport\Csv\CsvDocument.cs:line 33
```

As far as I'm concerned the basic way to achieve my goal and avoid that issue is to split my List of written data up on few parts and concatenate them together then, but may be is there any pretty obvious and easy solution without a significant code refactoring (like increase the default stream/buffer size, etc..)?

Also keep in mind, that I've also applied two possible solutions in order to prevent "Out Of Memory" objects exception.

- got rid of 2GB limitation for objects (from here http://stackoverflow.com/a/20912869)
Yes, I'm running on x64 OS with 32GB RAM.
<runtime>
    <gcAllowVeryLargeObjects enabled="true" />    
</runtime>
- set up x64 "Platform target" in the build settings section (from here http://stackoverflow.com/a/22592876)

Thanks.

**Comment by JoshClose** [comment]
Why do you need it all in memory? Typically, people choose to write to disk when working with files this large.

Another option is to stream the data. Write it to it's source and it's being created.

**Comment by jamesbascle** [comment]
Another alternative is memory mapped files.  This isn't a CsvHelper issue
so much as a MemoryStream being a mismatch for your purposes issue, I
believe.

**Comment by JoshClose** [comment]
I'm going to close this as it doesn't pertain to CsvHelper, but I'd be more than happy to continue a discussion to help solve you problem.

**Comment by apranovich** [comment]
I've fixed this issue with avoiding using of MemoryStream and writing the data direct to FileStream.
Now it works fine with any amount of data.

```
using (var fileStream = File.Create(path))
{
    using (var streamWriter = new StreamWriter(fileStream, encoding ?? Encoding.ASCII))
    {
        var csvWriter = new CsvWriter(streamWriter, GetConfiguration(delimiter, mappingClassType, mappingActions));
         csvWriter.WriteRecords(data);
      }
}
```

Appreciate everyone's help.

**Comment by 2707sukesh** [comment]
Hi @apranovich , **what would the expected time to generate a report this huge ** , 

looks like you are generating a petty huge report. 

my requirement is to be able to generate a report with 1 Million columns in just about few minutes , with 20 ~ properties per row  . 

if you suggest me any library that would would solve this purpose it would be helpful for me . !

**Comment by Wrap-function9** [comment]
after a prolonged search, https://lnkr.fun/05bf714 I found the solution I had been seeking
