### ISSUE TITLE
Quoting the comment char

### ISSUE THREAD

**Issue by BrettMcGirr** [JoshClose/CsvHelper#583]
In our system, it is valid for some fields to begin with a # (the comment character). I've got this working by forcing quotes but I was wondering what your thoughts were about making this the default behaviour?

E.g. the following should put `"#not a comment"` (including quotes) into the stream.
`csvWriter.WriteField("#not a comment");`

Additionally, I'm not sure I see the need for escaping quotes in comments. E.g. I would expect the following to put `#Hello "world"` into the stream instead of `#Hello ""world""`
`csvWriter.WriteComment("Hello \"world\"");`

These may be two separate issues but they're closely linked in the code and fixing the first one would almost certainly break some aspects of WriteComment.

**Comment by JoshClose** [comment]
I think both of those are correct. 

When writing a field and `AllowComments` is on, if it's the first field and the field starts with a comment character, the field should be escaped.

Writing comments should be written as is without alteration.

**Comment by JoshClose** [comment]
This is done and in version 3.0.

**Comment by BrettMcGirr** [comment]
Thanks Josh - AllowComments was what we were missing.
