### ISSUE TITLE
Using Display Attribute "Name" values as Column Headers

### ISSUE THREAD

**Issue by adaam2** [JoshClose/CsvHelper#585]
Hi there,

I found an old thread for version 1 where someone wanted to make it so that the CSV used the values from the Display attributes (in particular the "Name" property) as the text to be displayed in the column headers, but seeing as this is v2 and everything has moved towards mapping now, I can't seem to figure out the way to do this. Note: I have also seen the (unmerged) PR here: https://github.com/JoshClose/CsvHelper/pull/358 

Here is an example class:

```
public class CsvRow
{
        [Display(Name = "Your Name")]
        public string Name { get; set; }
}
```

Here is my attempt at a class map (using Reflection to get a list of all of the properties - I don't want to have to write out every property in the model - there are tons. **note:** very wrong!):

```
private class CsvRowClassMap: CsvClassMap<CsvRow>
    {
        public CsvRowClassMap()
        {
            PropertyInfo[] properties = typeof(CsvRow).GetProperties(BindingFlags.Public);

            foreach(PropertyInfo prop in properties)
            {
                var method = prop.GetSetMethod();

                var call = Expression.Call(Expression.Constant(this), method);
                var param = Expression.Parameter(typeof(object), prop.Name);

                var compiled = Expression.Lambda<Func<CsvRow, object>>(call, param);
                //Map(compiled).Name = <== DisplayAttribute code here ==> ;
                // ??
            }
        }
    }
```

Any help or pointers on how to achieve this would be great!

**Comment by JoshClose** [comment]
Take a look at how the auto mapper works. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvClassMap.cs#L182

You shouldn't have to use expressions at all. The mapping is just meta data.

Here is an example of just changing the name.

```cs
var map = new DefaultCsvClassMap<Test>();
map.AutoMap();
var properties = typeof(Test).GetProperties(BindingFlags.Instance | BindingFlags.Public);
foreach (var property in properties)
{
	var displayAttribute = (DisplayAttribute)property.GetCustomAttribute(typeof(DisplayAttribute));
	map.PropertyMaps.Find(property).Name(displayAttribute.Name);
}
```

If you're interested in actually making this a part of the library, I can point  you in that direction also. I'd like that to be a part of the contrib project and not a part of the main one though.

**Comment by adaam2** [comment]
Hi Josh

That's awesome - thank you very much! Working as expected now.

Yes, with regards to the Contrib project - sounds like a good idea - I would be willing to contribute to this when I have some time! What other things are going to be moved to the Contrib project?

Adam

**Comment by JoshClose** [comment]
Basically anything that people want that I don't feel like should be a part of the main project. Things that pull in other libraries. etc

Attribute mapping is one thing. This would include the DisplayAttribute also, and probably some other component model things.  Using the EF attributes. Methods to convert to and from DataTable and DataReader.

The contrib project will probably be broken up into separate assemblies. One for general things. Then one for each library that would need to get pulled in.

**Comment by adaam2** [comment]
Awesome - cool I have a few ideas - I'll check out the source code and PR with any ideas I may have and then we can look at moving those pieces of functionality to the contrib library

Closing

Thanks again,
Adam

**Comment by JoshClose** [comment]
The contrib project is completely empty at this time. ;) People have asked for things, but no one wanted to do the work. ha ha

**Comment by adaam2** [comment]
Always the way ;) !

**Comment by nat42** [comment]
> Attribute mapping is one thing. This would include the DisplayAttribute also

I believe DisplayAttribute _is_ the Display(Name) attribute.

> The contrib project is completely empty at this time. ;) People have asked for things, but no one wanted to do the work. ha ha

It seems like support for getting the field name from attribute metadata has been in the code at least twice and has been removed (the Pull request and there is CsvHelper.CsvField(FieldName) mentioned in a aml documentation file).

Besides people that want this may not want it in a separate (and separately maintained) package, it's a pretty basic feature other CSV libraries have, so rather than being lazy perhaps they bite the bullet and look at moving to another library that has features like this included and fully supported. 

> ...and probably some other component model things. Using the EF attributes. Methods to convert to and from DataTable and DataReader.

If the implication is we can't have feature A because then people might expect features B & C, that seems a bit of a stretch, at least as far as rejecting feature A, surely that should be considered strictly on it's own merits/issues. Given the almost unlimited variants of possible less standard attributes you could support, I don't think the we have to support B&C for consistency argument applies.

Note: Not certain what "EF attributes" means, but yeah, if the library could support the DataTypeAttribute that'd be nice too I guess (even if that's not part of EF as far as I know)? Seems like the recommendation on formatting DateTimes as dates suggested in the docs (as part of the config) lets you down as soon as you need to write a CSV document with both a date and datetime columns...

**Comment by JoshClose** [comment]
The reason it was removed and I don't want to add it back in is because the feature is extremely limited compared to using a class map. You'll only be able to do a small subset of the features. Maybe that's fine with people.

**Comment by nat42** [comment]
The class map looks nice for doing more powerful stuff ;) I just don't think it's necessarily desirable to have field names as literals in a map class, especially if that means one locates the mapping away from the POCO model class which already have metadata attributes for say JSON output.

**Comment by JoshClose** [comment]
Have you seen the `Factory` class? You can create a map inline... I suppose that's not sitting with the POCO though.

```cs
var map = new Factory().CreateClassMapBuilder<Test>()
	.Map( m => m.Id ).Name( "the_id" )
	.Map( m => m.Name ).Name( "the_name" )
	.Build();
csv.Configuration.RegisterClassMap( map );
```

I'm looking into what it would take to add attributes back in... I'm up to 15 attribute classes already.

**Comment by nat42** [comment]
I think just supporting a name attribute (any one really, but DisplayAttribute.Name is probably the best; at least it's sitting in the POCO immediate above the field declaration) would be very much welcomed, even if you add no other attributes. It seems to be the most requested?

Some way of specifying Date/DateTime formatting (eg. DataType(DataType.DateTime) or DisplayFormat or something custom) per column would be super nice too though but more work I imagine...

I really don't believe there's any set you _have_ to implement, I genuinely think people just want a name attribute.

Many thanks for considering my ramblings!!

**Comment by JoshClose** [comment]
The way things are setup now actually make doing attributes fairly simple. We'll see how far I get here.

**Comment by JoshClose** [comment]
This has been implemented and is on NuGet as 3.2.0. 

Due to changing around a lot of how the internals work for 3.0, I was able to do almost all features that are available using a class map.

**Comment by totht91** [comment]
Our generic solution for `DisplayAttribute` is the following:

You can easily create a custom logic in a `ClassMap<T>` to read and set `Display(Name)`

```C#
public class AutoClassMapWithApplyDisplayNameAttribute<T> : ClassMap<T>
{
    public AutoClassMapWithApplyDisplayNameAttribute()
    {
        AutoMap();

        foreach (var memberMap in MemberMaps)
        {
            var displayAttribute = memberMap.Data.Member.GetCustomAttribute<DisplayAttribute>();
            if (displayAttribute != null)
            {
                memberMap.Data.Names.Clear();
                memberMap.Data.Names.Add(displayAttribute.Name);
                memberMap.Data.IsNameSet = true;
            }
        }
    }
}
```

usage:

```C#
using (var csv = new CsvWriter(writer))
{
    csv.Configuration.RegisterClassMap<AutoClassMapWithApplyDisplayNameAttribute<T>>();
    // ... Other configs and write data...
}
```

**Comment by rodrigoleitetr** [comment]
In my case as I was buiding the CSV file from a JSON, I have added the attribute `[JsonProperty(PropertyName = "FooBar")]` to my model. So when serializing to JSON, it already uses the display name which then is sent to the CsvWriter(string)

**Comment by michaelmairegger** [comment]
If you use displayAttribute.GetName() instead of .Name then you support l10n.

**Comment by tibitoth** [comment]
> If you use displayAttribute.GetName() instead of .Name then you support l10n.

correct, I updated my comment
