### ISSUE TITLE
PDB in NuGet package

### ISSUE THREAD

**Issue by p76984275** [JoshClose/CsvHelper#589]
NuGet **2.16.0** has the CsvHelper.pdb while **after 2.16.1**, the pdb file is no longer provided.
Is this a intended change?

After upgrading from 2.16.0 to 2.16.3, when copy the output of a project using CsvHelper, I notice the number of files is not match with the previous one.

It's just a little wondering which needs to be confirmed.
Thanks for this great lib.

**Comment by JoshClose** [comment]
Yes, they're not included anymore. They're uploaded separately to the SymbolSource repository. http://docs.nuget.org/ndocs/create-packages/symbol-packages

You're able to add that as a source location an debug through the code if needed.
