### ISSUE TITLE
Add automatic positional model mapping

### ISSUE THREAD

**Issue by mburbea** [JoshClose/CsvHelper#590]
I have several hourly vendor csv files I recieve from a source system with absolutely awful 3 letter header names. An example might be:::
```
aod|hid|rlz|unr|hxf|pid|qty|bot|sld
```
Since the names are essentially giberish, and I'd never write a class with such names, I have to map by position.
Now for every file, I have to build a class and use this mapper that looks like this::
```csharp
    public class PositionalMapper<T> : CsvClassMap<T>
    {
        public PositionalMapper()
        {
            int i = 0;
            foreach (var p in typeof(T).GetProperties())
            {
                Map(p).Index(i++);
            }
        }
    }
```
I'd like an option that I can specify on a CsvReader that I want to do positional mapping automatically.

**Comment by JoshClose** [comment]
There is an issue with what you're doing. `GetProperties` isn't guaranteed to return the properties in the order you have them in source. I see this in the unit tests for CsvHelper all the time. It'll get properties that are returned in a different order and fail a test.

Auto mapping will do what your'e doing there for you. You can do `AutoMap()` in your mapper. If that's all you're doing, there is no point in specifying a mapping then. The auto mapper will use the index in the order they were got from `GetProperties`, and have the property name. If you don't want it to use the names, you can read the header yourself, then set `HasHeaderRecord = false`.

Here is a full example.
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("a,b,c,d");
		writer.WriteLine("1,2,3,4");
		writer.WriteLine("5,6,7,8");
		writer.Flush();
		stream.Position = 0;
		
		csv.Read();
		csv.ReadHeader();
		csv.Configuration.HasHeaderRecord = false;
		csv.GetRecords<Record>().ToList().Dump();
	}	
}

public class Record
{
	public int Prop1 { get; set; }
	public int Prop2 { get; set; }
	public int Prop3 { get; set; }
	public int Prop4 { get; set; }
}
```
