### ISSUE TITLE
[BUG] CsvReader fails to read field names where header contains an internal space...

### ISSUE THREAD

**Issue by natiki** [JoshClose/CsvHelper#591]
Hi,
- Version 2.16.3
- Irresepective of setting for TrimHeaderFields
- It appears that should a header field name contain a space GetField() or TryGetField() fail even if the field is there

![image](https://cloud.githubusercontent.com/assets/4738140/19373013/73e79754-920c-11e6-8606-8d6995823bda.png)

[BugReport.txt](https://github.com/JoshClose/CsvHelper/files/528512/BugReport.txt)

**Comment by JoshClose** [comment]
Can you check if it happens in the beta?

**Comment by natiki** [comment]
Will have to get back to you as I will need to create a test harness. Due to the changes in the surface of the public API it was not a simple recompile of my current solution :-)

**Comment by JoshClose** [comment]
Yes. There are a lot of breaking changes. I'll take a look if I get some time too.

**Comment by JoshClose** [comment]
It seems to work perfectly fine for me, unless I'm doing something wrong. Here is the example code I'm using.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("\"Email Address\",\"First Name\",\"Last Name\",State,Postcode,Gender,Age,\"Source Name\",\"Have you cruised before?\",EMAIL_TYPE,MEMBER_RATING,OPTIN_TIME,OPTIN_IP,CONFIRM_TIME,CONFIRM_IP,LATITUDE,LONGITUDE,GMTOFF,DSTOFF,TIMEZONE,CC,REGION,LAST_CHANGED,LEID,EUID,NOTES");
		writer.WriteLine("john@smith.com,John,Smith,,,,,,Yes,html,5,\"2015-06-28 12:58:21\",58.173.121.37,\"2015-06-28 12:59:24\",58.173.121.37,'-33.7620000,151.2140000,11,11,Pacific/Noumea,AU,NSW,\"2015-06-28 12:59:24\",76416513,f222bd8453,");
		writer.Flush();
		stream.Position = 0;
		
		csv.Read();
		csv.GetField("Have you cruised before?").Dump();
		csv.GetField("First Name").Dump();
	}
}
```
Output:
```
Yes
John
```

**Comment by natiki** [comment]
Was this with the 2.x branch? Don't have the code in front of me atm. I am setting a few options so it may be a weird permutation of those.

**Comment by JoshClose** [comment]
Yes.

**Comment by JoshClose** [comment]
In the latest source there is a `Func<string, string> Configuration.PrepareHeaderForMatch` function that you can set where you can do anything you like to the header before it's matched to a property.
