### ISSUE TITLE
WriteHeader With Quotes?

### ISSUE THREAD

**Issue by kirikintha** [JoshClose/CsvHelper#592]
Hello,

I have been having great success with CsvHelper, but I have been stuck on an implementation issue with WriteHeader().

I can write Headers through fluent mapping, without issue - but I am noticing that my headers are not being quoted. 

`First_Name, Last_Name, Zip_Code, ...`

This is not an issue 99% of the time, but I do have one upcoming project where a header would have spaces in it, like 

`First Name`

Instead of 

`First_Name`

And I am wanting to quote the header fields like:

`"First Name", "Last Name", "Zip+4" ...`

For most cases, this would be of no bother - but in this case it has the potential to be problematic as the legacy software being used as an importer is notoriously not well supported and not well coded. I am just trying to cover myself, and follow their guidelines.

Do you have any suggestions for me writing the headers with quotes? Thank you in advance, and for a wonderful set of code!

**Comment by JoshClose** [comment]
What version?

**Comment by JoshClose** [comment]
I just tried both versions and it's not putting any quotes in there. It should be.

For now you can do `csv.Configuration.QuoteAllFields = true` and it will quote the headers.

**Comment by JoshClose** [comment]
I'm sorry, I don't know what I was thinking. It's completely valid to have a space in a header without quotes around the field. The only things that make the field need to have quotes are a delimiter, a line ending, or a quote. If you header doesn't contain those, you won't get a quote. If you need them always, use the config option I mentioned above.

**Comment by kirikintha** [comment]
Hi Josh, thank for the clarification - sorry, I forgot to put in the version number. 2.16.3

Just to let you know, I have been using QuoteAllFields, with

```

CSVWriter.WriteHeader(Of MyModel)()

```

Where MyModel has getters and setters of a type of String. My only difference is that I am using VB.net. 

My CSV Output is like this:

```
TRACKING_NUM,LAST_NAME,FIRST_NAME,MIDDLE_NAME,NAME_SUFFIX,
```

Here is my entire Configuration Chain: 

```
                csv = New CsvReader(reader)
                csv.Configuration.HasHeaderRecord = True
                csv.Configuration.IgnoreQuotes = False
                csv.Configuration.IsHeaderCaseSensitive = True
                csv.Configuration.QuoteAllFields = True
                csv.Configuration.SkipEmptyRecords = True
                csv.Configuration.TrimFields = True
                csv.Configuration.TrimHeaders = True
```

This is in Visual Basic, but the Configuration section is pretty straight forward. Sorry for the elaboration, just trying to understand the nuance. Thanks again for taking the time to explain.

**Comment by JoshClose** [comment]
I can't reproduce this. Can you give a full example that reproduces this? You can just read and write to a `MemoryStream` instead of a file.
