### ISSUE TITLE
Question: Export class1 with list of class2 which has a list of class3

### ISSUE THREAD

**Issue by pmeems** [JoshClose/CsvHelper#593]
I'm not sure if this is the right location to ask questions, but I couldn't find a forum or something.

I'm new to CSV Helper and it looks very nice. I want to use it to export some database data.
I have for instance class1 which has some properties and a list of class2. This class2 has properties and a list of class3.
More concrete. When all 3 classes have 2 items, I need a csv file like this:
class1-1, class2-1, class3-1
class1-1, class2-1, class3-2
class1-1, class2-2, class3-1
class1-1, class2-2, class3-2
class1-2, class2-1, class3-1
class1-2, class2-1, class3-2
class1-2, class2-2, class3-1
class1-2, class2-2, class3-2

So the first columns get repeated. Is this even possible with CSV Helper? If so how?

Thanks.

**Comment by jamesbascle** [comment]
You could, but not directly.  You could just model it as a class with 3
columns, and do a nested SelectMany statement to flatten your class
hierarchy down to the model for the CSV.

Think of the CSV in the same terms as you might think of a DTO on an API
controller.

**Comment by JoshClose** [comment]
As James said, you can't do it automatically. You could loop your records and sub-records and sub-sub-records and output them manually. Then you can determine when you want to call `NextRecord` to flush and add the line break.
