### ISSUE TITLE
Why is WriteField(type, object) being deprecated?

### ISSUE THREAD

**Issue by bpierson** [JoshClose/CsvHelper#594]
Sometimes you don't have access to  static typing, so you can't use a generic method. Consider this example using a DataTable:
```
foreach( DataRow row in dt.Rows )
{
	foreach( DataColumn col in dt.Columns )
	{
		writer.WriteField( col.DataType, row[col] );
	}
	writer.NextRecord();
}
```

**Comment by jamesbascle** [comment]
The only thing coming out of the database is primitives, right? Any reason the WriteField<T>(T obj) method with object as the generic parameter wouldn't work?

**Comment by JoshClose** [comment]
You don't need to specify the type. `row[col]` returns an object, but it's just boxed. It's an actual type, like an `int`. If you do `writer.WriteField( row[col] );` you get the same result. By specifying the generic `WriteField<T>`, the type is already there so you don't have to pass it in, or do `field.GetType()`.

If you can think of a scenario where passing in the type doesn't work, let me know.

Example:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var table = new DataTable("Person");
		table.Columns.Add("Id", typeof(int));
		table.Columns.Add("Name", typeof(string));
		var row = table.NewRow();
		row["Id"] = 1;
		row["Name"] = "one";
		
		row["Id"].GetType().FullName.Dump();
		csv.WriteField(row["Id"]);
		csv.WriteField(row["Name"]);
		csv.NextRecord();
		writer.Flush();
		stream.Position = 0;
		reader.ReadToEnd().Dump();
	}
}
```
Output:
```
System.Int32
1,one
```

**Comment by jamesbascle** [comment]
Good snippit Josh.

Worth adding for anyone reading this that Josh posted what looks like a
LINQPad script and output, so the

```C#

row["Id"].GetType().FullName.Dump();

```

is just writing that System.Int32 out to the LINQPad output.

**Comment by bpierson** [comment]
Ok, of course you are right - no need to pass the type when you have an instance to inspect instead. Thanks guys.

**Comment by JoshClose** [comment]
I love LINQPad!
