### ISSUE TITLE
Fallback policy is not documented when an input csv file is invalid.

### ISSUE THREAD

**Issue by osamu329** [JoshClose/CsvHelper#597]
CsvParser accept invalid escaped field like `"foo"bar"`, and return `foobar"`

I've checked #308 and this behavior is excel compatible.
However if fallback policy is described in FAQ, it will be helpfull for us.

```
When CSV file is not compatible with RFC4180, CsvParser and CsvReader try to treat
the file exactly as MS Excel does.
```

It make someone be happy that configuration for RFC-strict mode is introduced.

**Comment by JoshClose** [comment]
http://joshclose.github.io/CsvHelper/reading#malformed-field-fallback
