### ISSUE TITLE
Header isn't parsed in 3.0.0-beta7

### ISSUE THREAD

**Issue by Piedone** [JoshClose/CsvHelper#599]
Using the 7. beta header parsing seems to be broken.

The below code works in 2.16.3 (also further reading) but throws an exception on `ReadHeader()` in beta 7.

```
using (var csvReader = new CsvReader(reportReader))
{
    csvReader.Configuration.Delimiter = "	"; // Tab.
    csvReader.Configuration.CultureInfo = CultureInfo.InvariantCulture;

    var z = csvReader.ReadHeader();
}
```

The file in question is something like this:

```
Field1	Field2	Field3	Field4	Field5	Field6	Field7
a	somestring	somestring	somestring	somestring	1,123	-0,123
b	somestring	somestring	somestring	somestring	1,123	-0,123
```

**Comment by JoshClose** [comment]
You need to call `Read()` first. `ReadHeader()` no longer does it automatically to allow for you to do other operations on the row if you want. It also makes the API more consistent and matches with the writer.

**Comment by Piedone** [comment]
Thanks for the quick reply!

How should the code look then? Because the docs on `Read()` say that I should be able to do `Read()`s if there is a header row and `GetField()`s without issues. However that fails, and this is originally why I started to experiment with `ReadHeader()`:

```
using (var csvReader = new CsvReader(reportReader))
{
    csvReader.Configuration.Delimiter = "   "; // Tab.
    csvReader.Configuration.CultureInfo = CultureInfo.InvariantCulture;

    while (csvReader.Read())
    {
        var field1 = csvReader.GetField<string>("Field1");
    }
}
```

This throws `Fields 'Field1' do not exist in the CSV file.` because the first row will be the header row (and thus there won't be a Field1). So the header row, despite `csvReader.Configuration.HasHeaderRecord` being `true`, is not parsed as a header, but just as the first row.

**Comment by JoshClose** [comment]
The docs aren't updated for 3.0 yet, but will be when 3.0 is released.

You should be able to do this:

```cs
csvReader.Read();
csvReader.ReadHeader();
while( csvREader.Read() )
{
    var field1 = csvReader.GetField( "Field1" );
}
```

If you use `GetRecord` or `GetRecords` that is still done automatically for you though.

**Comment by Piedone** [comment]
Thank you, that works!

**Comment by StefanBertels** [comment]
Just had the same issue, now solved.

You should remove / update this comment to make clear the new behaviour is intended:

CsvReader.cs line 99ff
```
                /// <summary>
		/// Advances the reader to the next record.
		/// If HasHeaderRecord is true (true by default), the first record of
		/// the CSV file will be automatically read in as the header record
		/// and the second record will be returned.
		/// </summary>
		/// <returns>True if there are more records, otherwise false.</returns>
		public virtual bool Read()
```
