### ISSUE TITLE
How can I quote only selected fields, and write custom content to a header?

### ISSUE THREAD

**Issue by farnsy** [JoshClose/CsvHelper#600]
I'm trying to output to a file format that requires dates and strings to be quoted (whether they contain special characters or not) and all other fields should not be quoted. 

`QuoteAllFields` and `QuoteNoFields` don't appear to help here (well, I've asked the group we're integrating if all fields can be quoted, but until I hear back from them...).

I tried creating a `TypeConverter` that for any string would return `$"\"{value}\""` however when this gets written to the csv file it ends up as `"""value"""`, because it appears the quotes are being escaped. 

Do you have any suggestions as to how I can achieve this?

They also require 7 header rows written in the form:
`# HEADER: Generation Date: <date>`
`# HEADER: File Format: <format>`

however I can't see any way to write custom lines - is this at all possible, or will I have to start writing to the file with a standard textwriter and merge the csv content later?

Thanks for any help you can provide.

**Comment by jamesbascle** [comment]
The 7 file header rows will just have to be written manually, possibly just
using the WriteField/WriteRecord methods if that ends up working for you.
Quoting a particular field doesn't seem to be supported, your best bet
seems to be QuoteAllFields if there doesn't end up being a problem.  That
might be a useful pull request to improve the CsvPropertyMap class.

**Comment by farnsy** [comment]
Thanks for the response. 

Regarding the header at this stage I'm creating the `StreamWriter` and using it to write the header, and then passing it to the constructor of the CsvWriter.

I was able to resolve the quoting issue by setting `QuoteNoFields `to true, and then applying my `QuotedField` type converter to the relevant map definitions.

**Comment by jamesbascle** [comment]
Nice. Good to know.
