### ISSUE TITLE
Minor problem with CsvHelper.Example.program.cs

### ISSUE THREAD

**Issue by HenryMinute** [JoshClose/CsvHelper#602]
As it is the definition of CustomTypeTypeConverter will not compile. It inherits ITypeConverter but does not implement it's members.

Changing the definition to:
public class CustomTypeTypeConverter : **DefaultTypeConverter** solves this.

Only a silly thing and does not affect operation of the library but I thought I'd point it out.

**Comment by JoshClose** [comment]
That project isn't maintained and isn't included in the solution anymore. I will remove it.
