### ISSUE TITLE
Multiple date format support

### ISSUE THREAD

**Issue by mguinness** [JoshClose/CsvHelper#603]
I need to allow for more than a single date format for parsing dates when reading files.  Dates can be in either yyyy-MM-dd or yyyyMMdd formats.

My initial attempt was to use TypeConverterOption and set multiple options, which didn't work (I assume that only the last format is used).

`.TypeConverterOption("yyyy-MM-dd").TypeConverterOption("yyyyMMdd")`

The DateTime class has a ParseExact overload which accepts an array of format strings, is there a way to incorporate that into the default DateTimeConverter class?

**Comment by JoshClose** [comment]
Yes! It should be fairly easy to do I think.

**Comment by kibbled** [comment]
Since TypeConverterOption is used for output and input how would it know which one to use when outputting CSV files? It would seem to implement this properly it would require some refactoring or a custom converter.

**Comment by jamesbascle** [comment]
You can just check for dashes in your string and then choose which format
string to pass to datetime.parse.l in your converter.

**Comment by MichaelMcKechnie** [comment]
fyi in the meantime I have found it handy to use a simple extension method for this...

`        public static DateTime? DateConverter(this ICsvReaderRow row, string fieldName, string[] dateFormats)
        {
            if (!String.IsNullOrEmpty(row.GetField(fieldName)))
            {
                return DateTime.ParseExact(row.GetField(fieldName), dateFormats, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal);
            }
            return null;
        }`

**Comment by JoshClose** [comment]
Just committed this. e8d56c7a1c3207138303d1697f91279932a63882
