### ISSUE TITLE
2.15.2 -> 2.16.3 Map Order of Columns Not Automatic anymore

### ISSUE THREAD

**Issue by bryanallott** [JoshClose/CsvHelper#605]
I noticed an old thread where the Index of the column is "derived" and was kept without needing to use .Index() when mapping (which worked wonderfully, thank you!)

However, an update from 2.15.2 to 2.16.3 resulted in the order of mapped columns mixing up- although the header column order was preserved.

The column order was the same for all the records- just differed to the header....

**Comment by JoshClose** [comment]
I'm a little confused. Is the issue the column order isn't the order that is in your class? Or is the column order not correct when doing a mapping and specifying columns without an index?

**Comment by bryanallott** [comment]
The column header row is in the same order as the mapping file (not using Index())
But the subsequent row records column order is different.

(sample shortened from current codebase)
 
class Map {
Map(p => p.Id);
References<OtherMap>(p => p.CompanyInfo);
Map(p => p.Project);
Map(p => p.CoreReference).Name("Core");
...
}

The CSV header row will be
Id,CompanyId,CompanName,Project,Core...

But the records' rows will write in a different order entirely: i.e. Core,CompanyId,CompanyName,Id,Project

==
Rolled back the Nuget package to 2.15.2 and everything was good again.

**Comment by JoshClose** [comment]
That is really weird. Can you check if that's an issue in the 3.0 beta? Also, do you have code that will reliably reproduce it? Like a small example.

**Comment by JoshClose** [comment]
If you can give me an example that fails, I'll open this back up. In 3.0 it seems to work.

Code:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var list = new List<A>
		{
			new A
			{
				AId = 1,
				AName = "one",
				B = new B
				{
					BId = 2,
					BName = "two"
				}
			}
		};
		csv.Configuration.RegisterClassMap<AMap>();
		csv.WriteRecords( list );
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class A
{
	public int AId { get; set; }
	public string AName { get; set; }
	public B B { get; set; }
}

public sealed class AMap : CsvClassMap<A>
{
	public AMap()
	{
		Map( m => m.AId );
		References<BMap>( m => m.B );
		Map( m => m.AName );
	}
}

public class B
{
	public int BId { get; set; }
	public string BName { get; set; }
}

public sealed class BMap : CsvClassMap<B>
{
	public BMap()
	{
		Map( m => m.BId );
		Map( m => m.BName );
	}
}
```
Output:
```
AId,BId,BName,AName
1,2,two,one
```
