### ISSUE TITLE
CsvReader ignoring CsvConfiguration.HasHeaderRecord

### ISSUE THREAD

**Issue by jcasale** [JoshClose/CsvHelper#606]
I am creating an instance of **CsvReader** and passing an instance of **CsvConfiguration** with **HasHeaderRecord** set to **true** however **Read()** is returning the header?

    using (CsvReader csvReader = new CsvReader(textReader, csvConfiguration))
    {
        while (csvReader.Read())
        {
            // Header appears as first record.
        }
    }

This behavior occurred when updating 3.0.0-beta4 to 3.0.0-beta7 and converting **IgnoreHeaderWhiteSpace**, **IsHeaderCaseSensitive** and **TrimHeaders** to a delegate for use with **PrepareHeaderForMatch**.

The same behavior is observed with the **CsvReader(TextReader textReader)** overload.

**Comment by JoshClose** [comment]
The behavior changed a little in 3.0. Calling `Read()` will read in the current record. If you have a header record, you need to call `ReadHeader` afterwards. `HasHeaderRecords` is used when not manually doing things, such as calling `GetRecords<T>()`.

**Comment by jcasale** [comment]
Much appreciated!

**Comment by SaqibS** [comment]
I'm facing the same question - even this issue has been closed for some time - also asked in a StackOverflow question: https://stackoverflow.com/questions/63056761/csvhelper-how-to-ignore-the-header-row

@JoshClose  Appreciate any clarification.
