### ISSUE TITLE
Writing a null value of Nullable<?> type throws exception

### ISSUE THREAD

**Issue by AdrianPell** [JoshClose/CsvHelper#607]
I need to write a DateTime? value to a CSV file.  I would have thought this would work:

    CsvWriter wtr .... (initialized earlier)
    DateTime? val = null;
    wtr.WriteField(val);

However, it throws a null-reference exception inside WriteField<T>().

Looking at the current source, it looks as if this should no be an issue:

`var type = field == null ? typeof( string ) : field.GetType();`

However, looking a decompile (I'm using 2.16.3 from Nuget), I see this:

    this.CheckDisposed();
    Type type = field.GetType();
    if (type == typeof(string))
    {
        this.WriteField((object)field as string);
        return;
    }
    this.WriteField<T>(field, TypeConverterFactory.GetConverter(type));'

In that case, it's clear why I get the NRE since field is null.

Am I spacing out or does the repo code not match the deployed package?

**Comment by JoshClose** [comment]
This is fixed in 3.0, which is currently in beta.
