### ISSUE TITLE
special characters in headers

### ISSUE THREAD

**Issue by tdjastrzebski** [JoshClose/CsvHelper#609]
I try to read CSV file with header containing hyphen named "sub-category".
Configuration.AutoMap<MyType>() builds with no problem.
MyType properties order matches CSV structure, so no custom mapping should be required.
GetField() and GetValue() methods work fine, including the "sub-category" column.
Exception is thrown when executing GetRecord<MyType>().
svHelper.CsvMissingFieldException: Fields 'Subcategory' do not exist in the CSV file.

1. It seems like index map is not (properly) used when calling GetRecord<MyType>() which may be a bug.
2. There is IgnoreHeaderWhiteSpace option available. But what is actually so special about white space? How about adding an option to ignore other special character as well? E.g  IgnoreHeaderCharacters = new char {' ', '-', '%' etc. } Anyway, it is just a thought.

Thanks  for the great library.

**Comment by jamesbascle** [comment]
Could just automap and then map the one field manually using the overwrite
option.

**Comment by tdjastrzebski** [comment]
I am not clear about the "overwrite option"

**Comment by JoshClose** [comment]
`GetField( "sub-category" )` is going to work because that's your header. When you do `GetRecord`, it's going to use the name of the property by default. Your property name is `Subcategory` apparently. If you want to use `GetRecord` and the property names don't match the header names, you'll need to use a mapping file.

More than likely you won't be calling `Configuration.AutoMap` yourself. If you do, it returns a `CsvClassMap` that you'll need to register. `csv.Configuration.RegisterClassMap( myClassMap )` If you don't do anything, auto mapping occurs automatically. 

What James was referring to is using auto mapping, then changing the value for a single property. I'll paste an example that shows both here.

```cs
public class Row
{
	public string Category { get; set; }
	public string Subcategory { get; set; }
}

public sealed class RowMap : CsvClassMap<Row>
{
	public RowMap()
	{
		AutoMap();
		Map( m => m.Subcategory ).Name( "sub-category" );
	}
}
```

If you use a class map like this, you need to register it. `csv.Configuration.RegisterClassMap<RowMap>();`

**Comment by tdjastrzebski** [comment]
Thanks, now I see.
I do not use GetField( "sub-category"), although I agree, GetField( "subcategory") should fail.
However, GetRecord() could easily use autogenerated map based on MyRecord class properties order instead of properties name lookup by csv header name. Therefore I still suggest this may be seen as a bug or at least feature request.

**Comment by tdjastrzebski** [comment]
repro below

`using CsvHelper;
using CsvHelper.Configuration;
using System.IO;
using System.Text;

class Program
{
	static void Main(string[] args)
	{
		string cvsText =
@"category, sub-category
vehicle, passanger
vehicle, truck
";
		var stream = new MemoryStream(Encoding.UTF8.GetBytes(cvsText));
		var textReader = new StreamReader(stream);
		var csvReader = new CsvReader(textReader);
		csvReader.Configuration.RegisterClassMap<RowMap>();
		csvReader.Configuration.IsHeaderCaseSensitive = false;

		while (csvReader.Read()) {
			string f0 = csvReader.GetField("category");
			// all the below fail
			Row row = csvReader.GetRecord<Row>();
			string f1 = csvReader.GetField("sub-category");
			string f2 = csvReader.GetField("subcategory");
			string f3 = csvReader.GetField("Subcategory");
		}
	}
}

public class Row
{
	public string Category { get; set; }
	public string Subcategory { get; set; }
}

public sealed class RowMap : CsvClassMap<Row>
{
	public RowMap()
	{
		AutoMap();
		Map(m => m.Subcategory).Name("sub-category");
	}
}
`

**Comment by tdjastrzebski** [comment]
`using CsvHelper;
using CsvHelper.Configuration;
using System.IO;
using System.Text;

class Program
{
	static void Main(string[] args)
	{
		string cvsText =
@"category, sub-category
vehicle, passanger
vehicle, truck";

		var stream = new MemoryStream(Encoding.UTF8.GetBytes(cvsText));
		var textReader = new StreamReader(stream);
		var csvReader = new CsvReader(textReader);
		csvReader.Configuration.RegisterClassMap<RowMap>();
		csvReader.Configuration.IsHeaderCaseSensitive = false;

		while (csvReader.Read()) {
			string f0 = csvReader.GetField("category");
			// all the below fail
			Row row = csvReader.GetRecord<Row>();
			string f1 = csvReader.GetField("sub-category");
			string f2 = csvReader.GetField("subcategory");
			string f3 = csvReader.GetField("Subcategory");
		}
	}
}

public class Row
{
	public string Category { get; set; }
	public string Subcategory { get; set; }
}

public sealed class RowMap : CsvClassMap<Row>
{
	public RowMap()
	{
		AutoMap();
		Map(m => m.Subcategory).Name("sub-category");
	}
}
`

**Comment by jamesbascle** [comment]
As explained in other rickets, properties are not returned in a
deterministic order, so this is impossible.

**Comment by tdjastrzebski** [comment]
I just updated the comment, sorry, for any reason zip attachment with repro does not want to go through

**Comment by JoshClose** [comment]
You have spaces after the comma in your CSV file. The reason `sub-category` doesn't work is the file actually has `\ssub-category`. The other 2 after that aren't going to work because you have said in your mapping that the field header has name `sub-category`.

**Comment by tdjastrzebski** [comment]
Ach, that's right. Many thanks.

**Comment by hellboy81** [comment]
Have the same problems with column names containing spaces, `(` and hyphens

 Is there possible to write CSV containing this chars?

**Comment by JoshClose** [comment]
You can write using a mapping like this:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Id = 1, Name = "one" }
		};
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords( records );
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		Map( m => m.Id ).Name( "The-Id" );
		Map( m => m.Name ).Name( "(Name)" );
	}
}
```
Output:
```
The-Id,(Name)
1,one
```
You can write without a mapping like this:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		csv.WriteField( "The-Id" );
		csv.WriteField( "(Name)" );
		csv.NextRecord();
		csv.WriteField( 1 );
		csv.WriteField( "one" );
		csv.NextRecord();
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}
```
This has the exact same output.

**Comment by hellboy81** [comment]
it works! `Name` is write-only-property ;-)
