### ISSUE TITLE
Write, don't treat new line as new row

### ISSUE THREAD

**Issue by TimGeyssens** [JoshClose/CsvHelper#611]
Hey,

First of all massive kudos for such a great library! But I'm looking for something that I couldn't find so placing it here. 

I'm currently writing data but the data can return new lines and those carriage returns are currently treated as new rows... Is there anyway to config when writing data it should replace those new lines with another character?

Code I'm using:

`
public object GetExport(string typeAlias)
{
            var guid = Guid.NewGuid();

            using (var textWriter = File.CreateText(IOHelper.MapPath(@"~\App_Plugins\UIOMaticAddons\Exports\" + guid + ".csv")))
            {
                textWriter.NewLine = "\n";
                using (var csv = new CsvWriter(textWriter))
                {
                    var os = new UIOMatic.Services.PetaPocoObjectService();

                    var data = os.GetAll(UIOMatic.Helper.GetUIOMaticTypeByAlias(typeAlias));

                    csv.Configuration.Delimiter = ";";
                    //csv.Configuration.QuoteAllFields = true;
                    csv.Configuration.HasHeaderRecord = true;

                    csv.WriteRecords(data);
                }
            }
           
          return new { data = "../App_Plugins/UIOMaticAddons/Exports/" + guid.ToString() + ".csv" };
        }`
Thank you

**Comment by daheRDS** [comment]
I think, this is on the roadmap.
#604

**Comment by JoshClose** [comment]
Yes, it's coming in 3.0.

**Comment by TimGeyssens** [comment]
Awesome, is it already included in the beta? Then I can give that a go. Thanks

**Comment by JoshClose** [comment]
No. You can follow issue #604 for it's progress.
