### ISSUE TITLE
Add column and row indexes to CsvTypeConverterException

### ISSUE THREAD

**Issue by richardcox13** [JoshClose/CsvHelper#612]
To make it easier to work out where in the file triggered an issue with data conversion, please add information (whether in CSV terms: column index/name, row number) or file (line number, character index).

Currently, when using GetRecords<T>() to read everything one is left to manually search the file for data issues.

**Comment by JoshClose** [comment]
In the current version it's available in Exception.Data["CsvHelper"] (iirc). I the 3.0 beta, there are properties on the Exception itself with that information.
