### ISSUE TITLE
Auto Mapping does not work

### ISSUE THREAD

**Issue by AdamTub** [JoshClose/CsvHelper#614]
Hi,
I am trying to auto map my object SomeData. Always get only last property (SectionPrevious). SectionActual and SectionNext are missing. 

```cs
public class SomeData
{
        public TSection SectionActual { get; set; }
        public TSection SectionNext { get; set; }
        public TSection SectionPrevious { get; set; }
 }

public class TSection
{
        public string Df { get; set; }
        public string Nz { get; set; }
        public int Rp { get; set; }
 }
```

**Comment by jamesbascle** [comment]
Can you post your sample CSV file?  Generally automapping nested object
structures does not work, and you will need to set up a ReferenceMap for
the subobjects.

**Comment by AdamTub** [comment]
I think that nested properties of custom type are supported or should be supported. This is why I CsvHelper library downloaded. There si PrefixReferenceHeaders which do exactly what I need.
Try this:
this.csvWritter = new CsvHelper.CsvWriter(sw);
this.csvWritter.Configuration.Delimiter = ";";
this.csvWritter.Configuration.PrefixReferenceHeaders = true;
this.csvWritter.WriteHeader<Lm3Data>();

My complex data type is here (Lm3Data):
https://1drv.ms/u/s!Au5UM0WUfPfGhYhlQM272lfxEBm-VQ

Thanks
Adam

**Comment by jamesbascle** [comment]
Ah my mistake, I was unaware of that configuration option. I'll extract
myself from this thread now. Also that file appears to be a dll.

**Comment by AdamTub** [comment]
If you are afraid here is the source code: 
https://1drv.ms/u/s!Au5UM0WUfPfGhYhm_25GHFQUolykBw

**Comment by AdamTub** [comment]
Hi, 
It is hard for me to suggest solution for the bug because of complexity of CsvHelper library. 
The issue is IMHO in method AutoMapInternal(...). There is definitely problem with nested custom reference  types. Please try to "serialize" my type. 

Thanks Adam

**Comment by JoshClose** [comment]
Can you post how you're doing your mapping?

If I use automapping, meaning, I don't specify a map at all, I get this.

Code:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<SomeData>
		{
			new SomeData
			{
				SectionActual = new TSection
				{
					Df = "Df Actual",
					Nz = "Nz Actual",
					Rp = 1
				},
				SectionNext = new TSection
				{
					Df = "Df Next",
					Nz = "Nz Next",
					Rp = 2
				},
				SectionPrevious = new TSection
				{
					Df = "Df Previous",
					Nz = "Nz Previous",
					Rp = 3
				}
			}
		};
		
		csv.Configuration.Delimiter = ";";
		csv.Configuration.PrefixReferenceHeaders = true;
		csv.WriteRecords(records);
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class SomeData
{
	public TSection SectionActual { get; set; }
	public TSection SectionNext { get; set; }
	public TSection SectionPrevious { get; set; }
}

public class TSection
{
	public string Df { get; set; }
	public string Nz { get; set; }
	public int Rp { get; set; }
}
```
Output:
```
SectionActual.Df;SectionActual.Nz;SectionActual.Rp;SectionNext.Df;SectionNext.Nz;SectionNext.Rp;SectionPrevious.Df;SectionPrevious.Nz;SectionPrevious.Rp
Df Actual;Nz Actual;1;Df Next;Nz Next;2;Df Previous;Nz Previous;3
```

**Comment by AdamTub** [comment]
Hi, your sample code works for me too. OK. It seems that problem is with complex data type as you can see in my Lm3Data. Lm3Data has nested reference types like:
TPosition.Gnss.GPSWeekTime
or
TSection.Hmm.Meter

Please try this sample code (you can download Lm3Data type from link above...)
```
static void Main(string[] args)
{
    using (var stream = new FileStream("data.csv", FileMode.Create))
    using (var writer = new StreamWriter(stream))
    using (var csv = new CsvWriter(writer))
    {
         var records = new List<Lm3Data>
         {
                 new Lm3Data()
         };
         csv.Configuration.Delimiter = ";";
         csv.Configuration.PrefixReferenceHeaders = true;
         csv.WriteRecords(records);
         writer.Flush();
    }
}
```

Thanks

**Comment by JoshClose** [comment]
The network I'm on right now blocks onedrive, so I won't be able to look at until later. If you want to paste it here I can.

**Comment by AdamTub** [comment]
Rename to Lm3Data.cs
[Lm3Data.txt](https://github.com/JoshClose/CsvHelper/files/617282/Lm3Data.txt)

**Comment by JoshClose** [comment]
Seems like a bug. I'll dig into it.

Code:
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var reader = new StreamReader(stream))
	using (var writer = new StreamWriter(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Lm3Data>
		{
			new Lm3Data
			{
			}
		};

		csv.Configuration.Delimiter = ";";
		csv.Configuration.PrefixReferenceHeaders = true;
		csv.WriteRecords(records);
		writer.Flush();
		stream.Position = 0;

		reader.ReadToEnd().Dump();
	}
}
```
Output:
```
Version;DefSoubor;LocalDateOfSync;PreSyncFlag;UnusedBool;GPSWeekTimeOfSync;MSName;QmpInitial;PositionPrevious.Flags;PositionPrevious.MpRun;PositionPrevious.QMPenabled;PositionPrevious.DFMeasuring;PositionPrevious.MeasActive;PositionPrevious.OfficialData;PositionPrevious.HmmIncreasing;PositionPrevious.NoMovement;PositionPrevious.DFMeasFixed;PositionPrevious.MeasActiveChanged;PositionPrevious.DefUsekChanged;PositionPrevious.NazevChanged;PositionPrevious.HmmIncChanged;PositionPrevious.RPChanged;PositionPrevious.HmmIrregularity;PositionPrevious.DataBlockCount;PositionPrevious.QmpId;Gnss.HorPRMS;Gnss.PosSolType;Gnss.NumOfUsedSVs;Gnss.LatRad;Gnss.LonRad;Gnss.LatDeg;Gnss.LonDeg;Gnss.TrueCOG;Gnss.SpeedOG;Gnss.GPSWeekTime;Hmm.Hmeter;Hmm.Meter;Hmm.Kilometer;SectionPrevious.DefUsek;SectionPrevious.Nazev;Start.Hmeter;Start.Meter;Start.Kilometer;Tail.Hmeter;Tail.Meter;Tail.Kilometer;SectionPrevious.RP;TudcData.SISAzimuth;TudcData.MileageCorrection;TudcData.RepreTudu
;;;False;False;0;;0;0;False;False;False;False;False;False;False;False;False;False;False;False;False;False;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0.000;;;0;0;0.000;0;0;0.000;0;0;0;0
```

**Comment by JoshClose** [comment]
It's an issue with `CheckForCircularReference`. The types being passed in are a list of parents. Too many items are getting added to that list. Fix incoming.

**Comment by JoshClose** [comment]
Fixed. https://github.com/JoshClose/CsvHelper/commit/de9333be746cd1cec3bc287321217f45061773bf

It will be in the next NuGet pre-release 3.0.0-chi06
