### ISSUE TITLE
All records with a zero in a field being skipped.

### ISSUE THREAD

**Issue by dandrzej80** [JoshClose/CsvHelper#615]
In the following code, my csv file seems to be read with no problems except where there is a field with a zero.  Doesn't matter which field the zero is in that record ends up being skipped.  Any insight would be great have been starring at this for days.  Thanks for any help that can be provided.

        public static IEnumerable<CompProperties> UpdateComp(Stream file)
        {
            StreamReader stream = new StreamReader(file);
            CsvReader csvread = new CsvReader(stream);
            csvread.Configuration.Delimiter = ",";
            csvread.Configuration.HasHeaderRecord = false;
            csvread.Configuration.IgnoreReadingExceptions = true;
            csvread.Configuration.TrimFields = true;
            csvread.Configuration.WillThrowOnMissingField = false;
            csvread.Configuration.RegisterClassMap<CompClassMap>();

            return csvread.GetRecords<CompProperties>();
        }

    public class CompProperties
    {
        public double month { get; set; }
        public double lower { get; set; }
        public double upper { get; set; }
        public double percent { get; set; }
    }
    public class CompClassMap : CsvClassMap<CompProperties>
    {
        public CompClassMap()
        {
            Map(m => m.month).Index(0);
            Map(m => m.lower).Index(1).TypeConverterOption(NumberStyles.Any);
            Map(m => m.upper).Index(2).TypeConverterOption(NumberStyles.Any);
            Map(m => m.percent).Index(3).TypeConverterOption(NumberStyles.Any);
        }
    }

**Comment by JoshClose** [comment]
I'm not seeing this. Could you create a full example that reproduces the error?

This is what I tried.

```cs
void Main()
{	
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("1,2,3,4");
		writer.WriteLine("5,0,6,8");
		writer.WriteLine("9,10,11,12");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.Delimiter = ",";
		csv.Configuration.HasHeaderRecord = false;
		csv.Configuration.IgnoreReadingExceptions = true;
		csv.Configuration.TrimFields = true;
		csv.Configuration.WillThrowOnMissingField = false;
		csv.Configuration.RegisterClassMap<CompClassMap>();

		csv.GetRecords<CompProperties>().Dump();
	}
}

public class CompProperties
{
	public double month { get; set; }
	public double lower { get; set; }
	public double upper { get; set; }
	public double percent { get; set; }
}
public class CompClassMap : CsvClassMap<CompProperties>
{
	public CompClassMap()
	{
		Map(m => m.month).Index(0);
		Map(m => m.lower).Index(1).TypeConverterOption(NumberStyles.Any);
		Map(m => m.upper).Index(2).TypeConverterOption(NumberStyles.Any);
		Map(m => m.percent).Index(3).TypeConverterOption(NumberStyles.Any);
	}
}
```
Output:
```
month lower upper percent
1 2 3 4 
5 0 6 8 
9 10 11 12 
```

**Comment by dandrzej80** [comment]
@JoshClose Thanks for your response.  Turns out it was a formatting issue in my csv file.  I ended up writing it from scatch and everything is working great now.

**Comment by JoshClose** [comment]
Great!
