### ISSUE TITLE
intermittent extra commas in csv file

### ISSUE THREAD

**Issue by Contec-jfrost** [JoshClose/CsvHelper#616]
Seems to happen every once in a while. Have not been able to reproduce reliably.

**Comment by jamesbascle** [comment]
Please provide ClassMap and sample data.  If you can provide the actual line you've seen it on, it should be relatively trivial to reproduce it with enough iterations.

**Comment by jamesbascle** [comment]
Another potential thing is if you're using the QuoteNoFields option, and a field contains the delimiter when it is serialized, you could see this, but there would be 3 in a row, unless it were the last field.

**Comment by Contec-jfrost** [comment]
Hello,

Thank you for the notes.
I talked with the user and they suspect they may have introduced the extra commas through manual manipulation of the file(s).
There was some manual correction needed on certain data fields and possibly combining of multiple files.

I and another developer hit the system very hard trying to reproduce the issue and were not able to.
I asked the user to please keep track of what they do when they run the report to see if we can better pin down the cause…. If it happens again.

I think maybe the issue could be closed? Until we get confirmation its real?

Thank You for your response.
Let me know if you would like me to do anything more.

Thanks,
Jack
