### ISSUE TITLE
GetRecords inside using

### ISSUE THREAD

**Issue by vkairys** [JoshClose/CsvHelper#619]
I want to return a collection without exposing any implementation. I'm using GetRecords inside using block. When I try to get an object from the collection I get ObjectDisposedException. 
Example code:
```csharp
public IEnumerable<int> GetNumbers()
{
     using (var csv = new CsvReader(new StringReader("1")))
     {
          csv.Configuration.HasHeaderRecord = false;
          return csv.GetRecords<int>();
     }
}
```

**Comment by JoshClose** [comment]
The using block disposes the `CsvReader` instance. If you want to return the `IEnumerable`, you'll need to leave it open, and implement `IDisposable` on your class.

**Comment by vkairys** [comment]
I really don’t want to implement  IDsiposable. I changed my code to: 
```csharp
      public IEnumerable<int> GetNumbers()
        {
            using (var csv = new CsvReader(new StringReader("1")))
            {
                csv.Configuration.HasHeaderRecord = false;
                while (csv.Read())
                {
                    yield return csv.GetRecord<int>();
                }
            }
        }
```
It worked as I expected.  I just thought I could do the same with GetRecords.

Thanks for the great project.

**Comment by himanshuladola** [comment]
When reader and stream will get dispose in above example?

**Comment by JoshClose** [comment]
As as soon as possible after the using block exits.
