### ISSUE TITLE
Problem with inheritance in newer versions?

### ISSUE THREAD

**Issue by horizondave** [JoshClose/CsvHelper#620]
My setup is like this....

```
public abstract class myBase
{
    public int Id {get; set;}
    public int Title {get; set;}
    .... more properties....
}
public class myClass1 : myBase { }
public class myClass2 : myBase { }

```
...I manually mapped myBase....

```
public sealed class myBaseMap: CsvHelper.Configuration.CsvClassMap<myBase>
{
    public myBaseMap()
    {
        Map(m => m.Id);
        ...
    }
}
...
c.RegisterClassMap(typeof(myBaseMap));

```
... and in older versions of CsvHelper, when I got a collection of myClass1's or myClass2's the mapping was applied.

With the latest version, however, I find I am having to create a mapping for each of my non-abstract classes instead?  If I just register a mapping for the abstract base class, it isn't applied when I try to export a list of myClass1's.  I have to create a mapping specifically for myClass1 for it to be applied?

Not sure if this is intentional, or a bug, so I thought I'd raise it here.

**Comment by JoshClose** [comment]
By latest do you mean the 3.0 beta?

**Comment by horizondave** [comment]
Sorry, no, 2.16.3

**Comment by JoshClose** [comment]
Can you try the 3.0 beta and see if it makes a difference? I don't have access to a computer until Monday.
