### ISSUE TITLE
UseExcelLeadingZerosFormatForNumerics doesn't need to apply Excel format when column contains just zero

### ISSUE THREAD

**Issue by richeym** [JoshClose/CsvHelper#621]
Hi,

I propose a very minor change to the behaviour of CsvConfiguration.UseExcelLeadingZerosFormatForNumerics.

This doesn't need to apply to columns that contain just a zero and has an impact on the way Excel aligns text in columns that would otherwise contain numeric data. Rename the below files extension to "csv" to see how Excel treats the column data:

[ExcelFormatting.txt](https://github.com/JoshClose/CsvHelper/files/651781/ExcelFormatting.txt)

**Comment by JoshClose** [comment]
I'll look into this for version 3.0.

I believe I'll be moving the Excel specific stuff out of the main library also.

**Comment by JoshClose** [comment]
All Excel specific code is going to be moved out.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#6
