### ISSUE TITLE
Excel interprets cells containing / and - as dates

### ISSUE THREAD

**Issue by agrath** [JoshClose/CsvHelper#622]
Similar to UseExcelLeadingZerosFormatForNumerics when you load a CSV file in Excel, if that field contains a string such as "1/3" (that may be common in an address field split out into columns for each address part), it will be interpreted and displayed as a date.
The fix is to prefix the field with = and quote, exactly the same as UseExcelLeadingZerosFormatForNumerics  does for numbers that begin with 0.
The check there is field[0] = '0' && field.All(Char.IsDigit) which unfortunately means that UseExcelLeadingZerosFormatForNumerics can not be used for this purpose.
I manually fixed this my export by writing the field manually and using string.Format to add the ="xx" around the field.
I was going to submit a patch but that would change the meaning of UseExcelLeadingZerosFormatForNumerics  so we would have to introduce a new configuration value entirely.

**Comment by JoshClose** [comment]
Hold off for now. I'm going to be moving the Excel specific stuff out of the main library. There will probably be an Excel compatible parser that will contain all the Excel stuff to keep it out of the main library since it really has nothing to do with CSV files.

**Comment by ngbrown** [comment]
The way I've always escaped strings that would otherwise convert to a number, date, time, etc. in Excel is start the string with a single quote.   (`'`)  Like this:

```
'1/3
```

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#1
