### ISSUE TITLE
Deprecated WriteRecord method

### ISSUE THREAD

**Issue by joakimjm** [JoshClose/CsvHelper#623]
I'm using version CsvHelper version 2.16.3 and you seem to have deprecated `CsvWriter.WriteRecord(System.Type type, object record)`. The deprecation notice says to use the method `CsvWriter.WriteRecord<T>(T record)` instead. However, I'm writing an `OutputFormatter` for ASP.NET Core and it has no generic types available. Only the object reference and its particular System.Type instance. Thus the first method works, but is deprecated and the other method throws this:

```
CsvHelper.CsvWriterException: No properties are mapped for type 'System.Object'.
   at CsvHelper.CsvWriter.CreateActionForObject(Type type)
   at CsvHelper.CsvWriter.GetWriteRecordAction[T]()
   at CsvHelper.CsvWriter.WriteRecord[T](T record)
```

Does it make sense to deprecate `CsvWriter.WriteRecord(System.Type type, object record)` since it has an actual use case?

**Comment by JoshClose** [comment]
Have you tried in the 3.0 beta? This may be fixed.

```cs
var type = typeof( T );
if( type == typeof( object ) )
{
	type = record.GetType();
}
```

**Comment by JoshClose** [comment]
Meaning, it may detect it correctly. If not, can you create a small example that reproduces the issue, and I'll un-deprecate it.

**Comment by jedlake** [comment]
I use this feature in a custom media formatter, which also only have the object and type. Will this still be supported in 3.0 or will there be a similar way to accomplish this?


```
        public override void WriteToStream(Type type, object value, Stream writeStream, HttpContent content)
        {
            using (var writer = new StreamWriter(writeStream))
            {
                using (CsvWriter csvWriter = new CsvWriter(writer))
                {
                    foreach (var obj in (IEnumerable<object>)value)
                    {
                        csvWriter.WriteRecord(obj.GetType(), obj);
                    }
                }
            }
        }
```

**Comment by JoshClose** [comment]
This fails in 2.x as you have described, but works fine in 3.0. I don't think there is a need for the specific type overload.
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		object record = new Test { Id = 1, Name = "one" };
		
		csv.WriteRecord(record);
		csv.NextRecord();
		
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```
