### ISSUE TITLE
What happened to IgnoreHeaderWhiteSpace?

### ISSUE THREAD

**Issue by lorenh** [JoshClose/CsvHelper#624]
Trying out 3.0.0-beta7 in .NET Core and noticed that the configuration option IgnoreHeaderWhiteSpace is no longer present.  What is the correct alternative?

**Comment by JoshClose** [comment]
`Configuration.PrepareHeaderForMatch` 

I needed to added another header changing thing, so instead, I'm just letting the user do what they want with it. It's replacing `IsHeaderCaseSensitive`, `IgnoreHeaderWhiteSpace`, and `TrimHeaders`.

You just manipulate the header how you want it.

`IsHeaderCaseSensitive = true` would be `PrepareHeaderForMatch = header => header.ToLower()`

'IgnoreHeaderWhiteSpace = true` would be `PrepareHeaderForMatch = header => Regex.Replace( header, @"\s", string.Empty )`

`TrimHeaders = true` would be `PrepareHeaderForMatch  = header => header.Trim()`

You can obviously do whatever you want including combinations of all those.

`Regex.Replace( header.Trim().ToLoser(), @"\s", string.Empty )`

It basically puts the header matching in the hands of the user.

**Comment by lorenh** [comment]
Outstanding.  Nice change, just didn't see it documented anywhere.  THANKS for the quick response.

**Comment by JoshClose** [comment]
I have a lot of documentation to write for this release. :)
