### ISSUE TITLE
Change delimeter dynamically

### ISSUE THREAD

**Issue by sharok** [JoshClose/CsvHelper#626]
My users can upload csv with separate delimeter,  comma and semicolon for example. I wrote method which detect semicolon and after that I want to change delimeter, so I have:
```
 using (var streamReader = new StreamReader(stream))
{
   var csvReader = new CsvReader(streamReader, _configuration);
   csvReader.Read();
   var headerRow = csvReader.Parser.RawRecord;
   var delimeter = DetectDelimeter(headerRow);
   csvReader.Configuration.Delimiter = delimeter;
   csvReader.Parser.Configuration.Delimiter = delimeter;
   csvReader.ReadHeader();

  return csvReader.GetRecords(typeof(T)).Cast<T>().ToList();
}
```

So, I create reader, then get header, then try to detect delimeter and parse, but reader uses old delimeter.

**Comment by JoshClose** [comment]
I would suggest determining the delimiter before using CsvHelper. Read a single line, then test, then set the stream position back to 0, then start using CsvHelper.
