### ISSUE TITLE
Newline parsing fails if string contains a quoted string

### ISSUE THREAD

**Issue by mattbrailsford** [JoshClose/CsvHelper#627]
Whilst parsing a CSV with a string value  that contains both a quoted string and newlines, the parser will fail on any preceding newline following the quoted string treating the new line as a new record. Ie

    1,"My string value container a \"quoted\" string
    and a line break"

In this example, the parser will fail and treat "and a line break" as a new record, rather than a continuation of the entire string value.

**Comment by JoshClose** [comment]
`\"` is not how a quote is escaped. You need a double double quote `""`.

This is how the data should look based on what you're expecting.
```cs
1,"My string value container a '"quoted'" string
and a line break"
```
