### ISSUE TITLE
GetRecord when Csv does not contain columns expected with mapper

### ISSUE THREAD

**Issue by cookiekitty** [JoshClose/CsvHelper#629]
I have two or three records types that may or may not exist inside a Csv, meaning their columns may or may not be there.

I'm calling GetRecord<T> for the different types on one Csv file to get lists that I can manipulate after the reading is complete. I've noticed that if the columns for a certain record type do not exist in the Csv, I end up getting a record for every row that exists in the Csv instead, with an empty object inside it.

I have the reader configuration set to not throw on a missing field, as even if there is a missing field I don't want exceptions, but I also don't want empty records to be returned. It's also set to ignore reading exceptions.

Is there a way for GetRecord<T> to return an empty list when the columns for it are not present?

**Comment by JoshClose** [comment]
I'm not quite understanding... Could you make a small example that reproduces the issue?
