### ISSUE TITLE
CsvWriter not honoring name mapping?

### ISSUE THREAD

**Issue by LGreenberger** [JoshClose/CsvHelper#630]
I created the example below in linqpad. What I am not understanding is why doesn't the CsvWriter push the "D" property value in RecordB to the "D" column by adding an extra delimiter (a comma in this case)? And if this is not how name mapping works, how would I achieve this behavior? Thanks!

```
void Main()
{
    var a = new RecordA{A = 1, B = 2, C = 3, D = 4};
    var b = new RecordB{A = 1, B = 2, D = 4};
	
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvWriter(writer))
    {
        csv.Configuration.RegisterClassMap<RecordAMap>();    
        csv.Configuration.RegisterClassMap<RecordBMap>();

        csv.WriteHeader<RecordA>();
        csv.WriteRecord<RecordA>(a);
        csv.WriteRecord<RecordB>(b);
        writer.Flush();
        
        stream.Position = 0;
        reader.ReadToEnd().Dump();
    }
}

public class RecordA
{
    public int A { get; set; }
    public int B { get; set; }
    public int C { get; set; }
    public int D { get; set; }
}

public class RecordB
{
    public int A { get; set; }
    public int B { get; set; }
    public int D { get; set; }
}


public class RecordAMap : CsvClassMap<RecordA>
{
    public RecordAMap()
    {
        Map(m => m.A);
        Map(m => m.B);
        Map(m => m.C);
        Map(m => m.D);
    }
}


public class RecordBMap : CsvClassMap<RecordB>
{
    public RecordBMap()
    {
        Map(m => m.A);
        Map(m => m.B);
        Map(m => m.D).Name("D");
    }
}
```

Output
```
A,B,C,D
1,2,3,4
1,2,4
```

**Comment by jamesbascle** [comment]
Such a thing is not achievable at the moment.  When using a name mapping,
you're saying that, for some particular type, write it into the column
that, were I to call "WriteHeader" for that type, the header will appear
at. In general, one will get strange results when doing what you are doing
here. The best advice I can give off the top of my head is to map both A
and B to a separate mapping class that will properly map to the CSV file.
Index doesn't seem to work for this use case either.
