### ISSUE TITLE
[Feature Request] Autodetect column types

### ISSUE THREAD

**Issue by vSkullv** [JoshClose/CsvHelper#632]
Is there a way of auto detecting the column types of a file, e.g. Field1: bool, Field2:string and etc

**Comment by jamesbascle** [comment]
Do you mean during deserialization to dynamics?

**Comment by vSkullv** [comment]
I mean something like:
Type[] DetectColumnTypes(string csvFilePath, string delimiter, int maxNumberOfRows)

This method will return us the type of each column in the given csv file.

**Comment by jamesbascle** [comment]
Hm. That doesn't really fit with how CsvHelper works.  If that were a method at all, then it would need to be on a CsvReader.  It also doesn't really fit with the purpose of CsvHelper in my opinion, though I'll leave that up to Josh to decide.

In the meantime, my recommendation to you is to deserialize your file using CsvReader as a dynamic (all properties will be strings), then cast them to ExpandoObjects and iterate through each column found on the ExpandoObjects, attempting to parse them as various data types using things like Int32.TryParse, Uri.TryCreate, Decimal.TryParse, etc. to figure out which type they are.

**Comment by JoshClose** [comment]
There are too many possible types. A value of `1` could be a bool, byte, sbyte, char, decimal, double, float int, uint, long, ulong, short, ushort, or a string.
