### ISSUE TITLE
PropertyBindingFlags unused/ignored in CsvReader

### ISSUE THREAD

**Issue by JohnKozell** [JoshClose/CsvHelper#635]
Looks like **PropertyBindingFlags** is not implemented yet. 
Defaults to public/instance, I would like to use **IgnoreCase** so I can make my object accessor names more readable in the code. (lower in csv file, upper/lower in class)
I'll workaround for now, but would like to know if it's on anyone's list to implement?

**Comment by jamesbascle** [comment]
I don't quiie understand the relevance of the binding flags you mentioned,
but you should be able to just use the Name method in the constructor of
your class map.

**Comment by JohnKozell** [comment]
Sorry, I assumed that when I construct the CsvReader, I would just pass it a configuration object, and utilize the PropertyBindingFlags to control the conditions that the properties are bound to the columns, is this not the case?
`CsvConfiguration csvConfig = new CsvConfiguration() { PropertyBindingFlags = System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.IgnoreCase };`
`var csv = new CsvReader(textReader, csvConfig);`

**Comment by jamesbascle** [comment]
Hm. I believe that is just to specify the ability to get internal/private
properties.  I can't speak to the use of it for ignoring case, sorry.

**Comment by JohnKozell** [comment]
Thanks again for the thoughts James, seem like we're thinking in the same direction here, but looking at the code that particular property isn't used at the moment, even the default value of public/instance. So I have to assume it was a forward thinking capability that has not yet been implemented, and an opportunity for one of us in the future. For now, I'll work around it just fine by either using a map or renaming my accessors.

**Comment by JoshClose** [comment]
They used to be used until the PCL build came and those weren't an option anymore. I'll look into if it makes sense to add them back now. I believe netstandard has the capability.

**Comment by JoshClose** [comment]
So since a `CsvClassMap` is required and you map to public members, having the ability to map to internal/private doesn't make sense. It would only come into play when auto mapping, and I don't think auto mapping should have more privileges than a map file. 

If you just want to ignore case when matching the headers to your property names, you can do
```cs
// In 2.x
Configuration.IsHeaderCaseSensitive = false;

// In 3.x
Configuration.PrepareHeaderForMatch = header => header.ToLower();
```
