### ISSUE TITLE
When running concurrent CSV AutoMaps, the ReflectionHelper dictionary fails 

### ISSUE THREAD

**Issue by ukluk** [JoshClose/CsvHelper#638]
Not every case, but because the ReflectionHelper is a static, when concurrency occurs, adding elements to the dictionary are prompt for conflict.

The recommendation is to use a ConcurrentDictionary for funcCache and funcArgCache.

I also suggest to Change the ReflectionHelper into a Singleton, and convert all the static elements into class members or functions.

**Comment by JoshClose** [comment]
I pushed a fix. It will be in the next NuGet pre-release.

I just threw a locker around it. There is only one place that accesses it, so hopefully it won't be too much of a burden. It's definitely faster than re-compiling the delegate.
