### ISSUE TITLE
Question - Parsing Recommendation - Multiple Headers / Types of Records

### ISSUE THREAD

**Issue by sbroskie** [JoshClose/CsvHelper#639]
I'm looking for a recommended method for parsing CSV files with multiple types of records.

Here is an example:
http://www.spc.noaa.gov/climo/reports/170207_rpts.csv

This CSV has 3 types of records, with new headers for each set.  Would the best method be to go with the CsvParser and monitor for the headings?  Would it be more productive to pre-process the file using the CsvParser and then split it into 3 separate files and then work on each file individually?  

Suggestions much appreciated.

**Comment by oaknguyen** [comment]
Both ways would work fine, but I'd go with first method since I wouldn't want to iterate the csv more than once. You could clean up the first way by having 3 registered map classes and then progressing through them when you hit next headers. 

quick and dirty hack to show what I mean.
```C#
            var csv = new CsvReader(textReader);
            csv.Configuration.RegisterClassMap<a>();
            csv.Configuration.RegisterClassMap<b>();
            csv.Configuration.RegisterClassMap<c>();

            List<Func<CsvReader, baseObj>> rowReaders = new List<Func<CsvReader, baseObj>>()
            {
                 (csv) => csv.GetRecord>a>(),
                 (csv) => csv.GetRecord>b>(),
                 (csv) => csv.GetRecord>c>(),
            };
            int i = -1;
            Func<CsvReader, baseObj> rowReader;
            do            
            {
                string firstCol = csv.GetField<string>(0);
                if (row == "Time")
               {
                   rowReader = rowReaders[i]; 
                   continue;
               }
                yield return rowReader(csv);
            }while (csv.Read());

```
a,b,c extends baseObj here if that wasn't clear.

**Comment by JoshClose** [comment]
That is my suggestion also. Register a map for each type. Loop the records using `CsvReader`. Check the data to see before reading. Read the correct type from there on.
