### ISSUE TITLE
Creating a mapper that takes in tuple of generics

### ISSUE THREAD

**Issue by oaknguyen** [JoshClose/CsvHelper#640]
Let me start off by explain why I want generic Tuple mapper. I'm creating a lot of CSV's like 20ish and all different types and sometimes its a little bit of foo and a little bit of bar. So I wanted to create a mapper that allows me to say something like 
```C# 
new GenericMapper<Foo, Bar>()
 .FooProperties((foo) => foo.a, 
                   (foo) => foo.b)
 .BarProperties((bar) => foo.c,
                    (bar) => foo.d));
                              
```

My current implementation of it is a Mapper that extends the CsvClassMap with a two object Tuple. I have DefaultClassMappers that I build up and then add to the PropertyMaps. Example of it here

```C#
        CsvClassMap<S> _sMapper = new DefaultCsvClassMap<S>();
        public GenericMapper<S, T> FooProperties(params Expression<Func<S, object>>[] extractors)
        {

            foreach (var extractor in extractors)
            {
                PropertyInfo propertyInfo = ReflectionExtensions.GetPropertyInfo(extractor);
                CsvPropertyMap newMap = new CsvPropertyMap(propertyInfo);
                
                newMap.Name(propertyInfo.Name);
                _sMapper.PropertyMaps.Add(newMap);
            }

            PropertyInfo refProperty = ReflectionExtensions.GetPropertyInfo<Tuple<S, T>, S>((c) => c.Item1);
            CsvPropertyReferenceMap refMapper = new CsvPropertyReferenceMap(refProperty, _sMapper);
            this.ReferenceMaps.Add(refMapper);
            return this;
        }
``` 
The issue with this is that it does not allow self-pointing expression to be mapped. So 
```C# 
new GenericMapper<string, Bar>().FooProperties((s) => s)
```
won't get mapped correctly. 
I'm wondering what's the best way to go about this?
Am I on the right track here?

**Comment by JoshClose** [comment]
jamesbascle is working on a fluent builder, which seems like what you're looking for. https://github.com/JoshClose/CsvHelper/pull/587

**Comment by jamesbascle** [comment]
The PR is pretty much merge ready I believe. It doesn't have anything that
works inside the class maps on the property maps themselves for the reasons
given on the PR.

**Comment by JoshClose** [comment]
This will be a part of version 3.0 when it's released. Watch for Jame's pull request to get merged if you want to use it in a pre-release.
