### ISSUE TITLE
Change specific field value and save csv

### ISSUE THREAD

**Issue by sanchapereira** [JoshClose/CsvHelper#642]
Any ideas on how to change a field by name without mapping?

**Comment by GeekyEggo** [comment]
Have you got an example of the input, and desired output? If the field is a specific type, you could register an `ITypeConverter` globally.

**Comment by JoshClose** [comment]
You would need to read through the file and write it again. CsvHelper uses TextReader/TextWriter which is forward only, so there's no way to pull chunks of a file into memory and edit it.
