### ISSUE TITLE
Prescribed way to sanitize values?

### ISSUE THREAD

**Issue by killnine** [JoshClose/CsvHelper#643]
Hey Josh,

Fantastic library. I'm using it a lot in production environment and it's great.

However, I'm wondering if there's a prescribed way to sanitize field values to catch situations where the delimiter is used in the value? For example:

    Delimiter: |
    Value: Bob | Bob Publishing

I don't want it simply escaped, because our consuming system (a mainframe) doesn't have good mechanisms to escape the delimiter. I'm wondering if there's a way to strip out any use of the delimiter in the map itself without constantly overriding behavior via `ConvertUsing`.

If there's not already something, what about a new optional configuration akin to the `Quote` property that lets you replace any instance of a delimiter with the value you've configured? 

Thanks

**Comment by jamesbascle** [comment]
Is this in the context of reading or writing?

**Comment by killnine** [comment]
Sorry, I forgot to mention this was in context of writing out a file.

-D

**Comment by GeekyEggo** [comment]
@killnine, a possible solution would be to register a default `ITypeConverter` for strings to remove your desired delimiters. For example.
```
public class InvalidCharacterStringConverter : StringConverter
{
    public InvalidCharacterStringConverter(params char[] characters)
    {
        this.Characters = characters;
    }

    private char[] Characters { get; }

    public override string ConvertToString(object value, ICsvWriterRow row, CsvPropertyMapData propertyMapData)
    {
        char[] validCharacters = value.ToString()
            .Except(this.Characters)
            .ToArray();

        return base.ConvertToString(new string(validCharacters), row, propertyMapData);
    }
}
```
You can then register the convert to be used when handling strings with the following:
```
TypeConverterFactory.AddConverter<string>(new InvalidCharacterStringConverter('|'));
```

**Comment by JoshClose** [comment]
Either write a custom type converter, or override the `CsvSerializer.Write` method and check/update the values before writing them.
