### ISSUE TITLE
GetField by partial name

### ISSUE THREAD

**Issue by biserkazinreich** [JoshClose/CsvHelper#644]
When doing `csv.GetField<string>( "HeaderName" )` is there any way to get the field by partial name?
For example if my header name is "Work day (hrs)", is there a way to get the field with `"Work day%"` or something similar?
I know about  `Map(m => m.WorkDay).Name("Work day", "Work day (hrs)")`, but I really need to use `ConvertUsing` in my case.

Thanks.

**Comment by JoshClose** [comment]
You could take a look at `FieldHeaders` to find out the index.

**Comment by GeekyEggo** [comment]
For complete control, @biserkazinreich, you could introduce an extension method.
```
public static T GetField<T>(this CsvReader csv, Func<string, bool> predicate)
{
    string name = csv.FieldHeaders.FirstOrDefault(predicate);
    if (name == null)
    {
        return default(T);
    }

    return csv.GetField<T>(name);
}
```
