### ISSUE TITLE
CsvParser failes to parse quoted fields when they contain CarriageReturn ( \r ) without LineFeed ( \n )

### ISSUE THREAD

**Issue by rknoll** [JoshClose/CsvHelper#645]
See this example:
`new CsvParser(new StringReader("\"a\r\";b")).Read()`
This should return 2 values, the first containing a\r, the second b, but it will contain a\r";b, as it failes to detect the second quote.

I think this issue is caused by not checking the return value of ReadLineEnding() in CsvParser, resulting in a skipped character, which in this case is the second quote.

**Comment by mnye** [comment]
Hey, I attempted to fix this in the PR #650 .  Hope it helps!

**Comment by JoshClose** [comment]
Merged the PR.
