### ISSUE TITLE
Writer sometimes writes nothing to stream

### ISSUE THREAD

**Issue by rocifier** [JoshClose/CsvHelper#648]
A List<> of the below POCO won't write anything to stream in version 2.16.3 (other pocos work with this code):

    public class JVNZUserViewModel
    {
        public Guid Id { get; set; }
        public string Site { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime Created { get; set; }
        public bool AllowNewsletter { get; set; }
    }

my code:

        private Stream WriteToMemory(UsersPageViewModel request) {
            MemoryStream memoryStream = new MemoryStream();
            var textWriter = new StreamWriter(memoryStream);
            var csv = new CsvWriter(textWriter);
            csv.WriteRecords(request.Users);
            if (memoryStream.CanSeek) memoryStream.Seek(0, SeekOrigin.Begin);
            return memoryStream;
        }

**Comment by JoshClose** [comment]
After you `WriteRecords`, do a `textWriter.Flush()`. The `TextWriter` will flush itself automatically when it gets large enough, but you need to call it after you're done writing to make sure everything gets flushed. Exiting a `using` block will flush it also.
