### ISSUE TITLE
The documentation is not specific about CsvClassMaps for writing

### ISSUE THREAD

**Issue by accidentaldeveloper** [JoshClose/CsvHelper#651]
I have seen some confusion around the use of CsvClassMaps when writing to CSV. My understanding is that they are only used when reading, not writing. I have not seen anything in the documentation that makes this explicit. I admit that I may have missed it. 

If this is a desired addition then I would be happy to contribute. Thank you for a great library. Please let me know if I can be of assistance.

**Comment by accidentaldeveloper** [comment]
I did some more research and discovered that I was incorrect. My apologies. It appears that they are used but not fully. For instance you state that "Currently ConvertUsing is only used when reading." http://stackoverflow.com/a/22998319/1812515 It is also clear that they are being used based on [this test class](https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper.Tests/CsvWriterMappingTests.cs).

**Comment by JoshClose** [comment]
Most, but not all of the mapping options are used. Same with configuration. I started down a path of separating them, but they overlapped by all but a few, so I decided not to. The docs for the methods (intellisense docs) should say "when reading" or "when writing" of it only does one of them.
