### ISSUE TITLE
Problems to install package

### ISSUE THREAD

**Issue by firefoxmig** [JoshClose/CsvHelper#652]
I´ve a UWP project and i can´t install te package. The error is the following:

Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 proporciona un ensamblado de referencia en tiempo de compilación para System.Reflection.Emit.ILGeneration en 
UAP,Version=v10.0, pero no hay un ensamblado en tiempo de ejecución compatible con win10-arm-aot.
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Uno o más paquetes no son compatibles con UAP,Version=v10.0 (win10-arm-aot).
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 proporciona un ensamblado de referencia en tiempo de compilación para System.Reflection.Emit.ILGeneration en 
UAP,Version=v10.0, pero no hay un ensamblado en tiempo de ejecución compatible con win10-x64-aot.
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Uno o más paquetes no son compatibles con UAP,Version=v10.0 (win10-x64-aot).
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : System.Reflection.Emit.ILGeneration 4.0.1 proporciona un ensamblado de referencia en tiempo de compilación para System.Reflection.Emit.ILGeneration en 
UAP,Version=v10.0, pero no hay un ensamblado en tiempo de ejecución compatible con win10-x86-aot.
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Uno o más paquetes no son compatibles con UAP,Version=v10.0 (win10-x86-aot).
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
No se pudo restaurar el paquete para 'Flightoolsv3'.
Install-Package : Error al restaurar el paquete. Revirtiendo los cambios del paquete para 'Flightoolsv3'.
En línea: 1 Carácter: 1
+ Install-Package CsvHelper -Version 2.16.3
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
I´ve tried with Windows Phone blank project and it was installed fine. Also i´ve created a new project in UWP and i get the same error.

**Comment by JoshClose** [comment]
Do you think adding a build target for `uap` would solve your problem? https://docs.microsoft.com/en-us/nuget/schema/target-frameworks#supported-frameworks

**Comment by firefoxmig** [comment]
Sorry Josh but , i´m new in this. I needed read Csv data and i saw this. How can I solved it?

**Comment by firefoxmig** [comment]
Hello Josh, the issue has been solved. I updated microsoft NetCore to latest version 5.3.0. 

Regards

**Comment by JoshClose** [comment]
Good! I thought UWP could use core assemblies.
