### ISSUE TITLE
CsvParser fails to parse quoted fields if they contain: QUotes and Commas

### ISSUE THREAD

**Issue by RenetteNashua** [JoshClose/CsvHelper#653]
Simple test:
```
class Program
    {
        private static void Main(string[] args)
        {
            var stringToParse =
                @"""1st field containing Double Quote "" and more"", ""2nd field containing Single Quote ' and more"", ""3rd field containing Comma, and more"", 12345";
            var csvParser = new CsvParser(new StringReader(stringToParse));
            var quoteRequired = csvParser.Configuration.QuoteRequiredChars;
            var ignoreQuotes = csvParser.Configuration.IgnoreQuotes;

            csvParser.Configuration.TrimFields = true;
            var parsedFields = csvParser.Read();

            Console.WriteLine("Line to be parsed: " + stringToParse);
            foreach (var field in parsedFields)
            {
                Console.WriteLine("Field: " + field);
            }
            Console.Write("Press any char to exit.");
            Console.Read();
        }
    }
```
Output:
```
Line to be parsed: "1st field containing Double Quote " and more", "2nd field containing Single Quote ' and more", "3rd field containing Comma, and more", 12345
Field: 1st field containing Double Quote  and more"
Field:  "2nd field containing Single Quote ' and more"
Field:  "3rd field containing Comma
Field:  and more"
Field:  12345
```
We receive CSV files that we have to import from another system. Some of the text fields inside these CSVs can contain Double Quotes and Commas.

Any solution? Something as simple as a CsvParser.Configuration setting? I played araound with them, but had no joy.

**Comment by JoshClose** [comment]
If a field contains a `"`, `,`, `\r`, or `\n`, the field needs to be quoted. If there is a quote inside a field, it also needs to be escaped `""`. If these rules aren't followed, there really isn't much you can do. You're going to get weird results. There's really no way to get around that unfortunately. Check out [RFC 4180](https://tools.ietf.org/html/rfc4180)

The issue you're having with commas here is that your field starts with a blank space, then has a quote. There shouldn't be any spaces in between the commas and the field data.
