### ISSUE TITLE
ITypeConverter not respected with explicit implementation

### ISSUE THREAD

**Issue by madelson** [JoshClose/CsvHelper#655]
First, thanks for maintaining this great library!

My issue: I was registering a custom `ITypeConverter` via `TypeConverterFactory.AddConverter()`. However, this was causing an `ArgumentNullException` to be thrown calling `Expression.Call` in `CsvWriter.CreateActionForObject`.

Tracking it down in the code, the issue is where we try to get the ConvertToString method off the `ITypeConverter` (https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvWriter.cs#L802).

The way this is being done works if the implementation is public, but not if the interface implementation is explicit. I think the fix would be as simple as:

```
// before 
var method = propertyMap.Data.TypeConverter.GetType().GetMethod( "ConvertToString" );

// after
var method = typeof(ITypeConverter).GetMethod( "ConvertToString" );
```

This could even be cached in a static variable since it's the same each time.

Obviously, once I tracked down what was wrong the work-around was easy: just stop using explicit implementation. However, the error message was pretty non-obvious so it seems worth fixing. Right now, if you had an explicit implementation for ConvertToString and also a public ConvertToString method, the code would pick the public one (even if the arguments didn't match!).

**Comment by JoshClose** [comment]
Good find! I just pushed a fix. It will be available in the next pre-release on github.

**Comment by madelson** [comment]
Thanks!
