### ISSUE TITLE
Process GetRecord if exception was handled

### ISSUE THREAD

**Issue by cxubrix** [JoshClose/CsvHelper#658]
Currently there is no way to recover from tolerable exceptions in ReadingExceptionCallback function. 
`var record = csv.GetRecord<MyClass>();`
Let's assume that I can tolerate some(or all) empty fields in MyClass. In worst case it can be just MyClass with empty fields. This is needed in case I want to catch several exceptions and fall back to some values later.

For example Newtonsoft.JSON DeserializeObject has delegate which can set error to handled

```
var result = JsonConvert.DeserializeObject<MyClass>(payload, new JsonSerializerSettings
                {
                    Error = delegate (object sender, Newtonsoft.Json.Serialization.ErrorEventArgs args)
                    {
                        Console.WriteLine(args.ErrorContext.Error.Message);
                        
                        // set to Handled, since we want to get all errors
                        args.ErrorContext.Handled = true;
                    }
                }); 
```

**Comment by JoshClose** [comment]
Can you give an example of it not being able to recover? Setting `Configuration.IgnoreReadingExceptions` will allow reading to continue and call the callback function.

I believe only a parsing exception could be fatal.

**Comment by cxubrix** [comment]
I think the example below shows the issue.

```
    public class ReadCSV
    {

        private const string csv =
        @"S;I
        text;42
        more text;Invalid int";

        [Fact]
        public void Read()
        {

            var reader = new CsvReader(new StringReader(csv));
            reader.Configuration.ReadingExceptionCallback = (e, r) =>
            {
                Console.WriteLine($"Could not read field: {e.FieldName}");
            };
            reader.Configuration.Delimiter = ";";
            reader.Configuration.IgnoreReadingExceptions = true;

            var result = reader.GetRecords<Z>().ToList();
            result.Count().ShouldBeEquivalentTo(2);

        }

    }

    public class Z
    {
        public string S { get; set; }
        public int? I { get; set; }

        public override string ToString()
        {
            return $"S: '{S}', I: '{I}'";
        }
    }
```

**Comment by JoshClose** [comment]
In the latest pre-release, `Configuration.ReadingExceptionCallback` is the place that the error is thrown. If you change that function to not throw and do something else (or to null), it'll just skip the record.
