### ISSUE TITLE
CsvHelper adds " " around my string

### ISSUE THREAD

**Issue by gabygit** [JoshClose/CsvHelper#659]
Hello, when I export my string _Museums, art galleries, and botanical and zoological gardens_ into a xlsx file, CsvHelper adds _" "_ around it. Any idea why?

**Comment by JoshClose** [comment]
Can you paste the row in for me to take a look at?

**Comment by gabygit** [comment]
`// Write the list into a xls file then save this file
                using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
                {
                    using (var writer = new CsvWriter(new ExcelSerializer(workbook)))
                    {
                        writer.Configuration.RegisterClassMap<LeadClassMap>();
                        writer.WriteRecords(list);
                    }
                    workbook.SaveAs(pathString);
                }`   Not sure if it's what u asked to see

**Comment by gabygit** [comment]
![image](https://cloud.githubusercontent.com/assets/25452154/24256905/b4ce39ca-0fe9-11e7-8e6a-8e94eee5f7f8.png)

**Comment by gabygit** [comment]
![image](https://cloud.githubusercontent.com/assets/25452154/24257000/efac3d3a-0fe9-11e7-91e7-bddfbbf9e5ab.png)

**Comment by gabygit** [comment]
![image](https://cloud.githubusercontent.com/assets/25452154/24257127/43b0fd3a-0fea-11e7-9b82-c7ecc07b16d0.png)
We can see with visual studio that it's a normal string

**Comment by JoshClose** [comment]
What if you open the file with a text editor instead of excel?

**Comment by gabygit** [comment]
PK    ÇˆwJ±ùS  º    xl/workbook.xml ¢ (                      Ïn!Æ_…Ì½²nbÛlD/öà¥iRÓž—¸Àf@Ýwë¡ÔW(¬MO=1ÿ~ß|ÃÏ×÷|9¸Ž‘¢
^ÀtRC¯‚¶~'àÌÃ3,ó¡9ÚoCØ³<ïcCÚ”ú†ó¨Zt2NB>÷L 'SNiÇƒ1Vá*¨ƒCŸx]Uœ°“)ïŠ­í#\Ô†ÿ¨ÅžPêØ"&×Åœ´îÝ½ËÞñU:°imü¼4€ñ2WÂ‹§x•3–bz/âòH•ì7r;f™åàÑÇ-b~\ù2ô°±¶Öj`ÔØÐZ×W¡«ÑXºøg‡Jvª\‘ŸÂOëÙS=»‚WÇ‹_PK
     ÇˆwJÔ^S¨œ  œ    _rels/.rels ¢ (                      ï»¿<?xml version="1.0" encoding="utf-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="/xl/workbook.xml" Id="R3df90e6e225a477b" /><Relationship Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="/docProps/app.xml" Id="rId1" /><Relationship Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="/package/services/metadata/core-properties/7a17c4849f0b4e2ca72c4a5b525d9f97.psmdcp" Id="R52c10e934b014bcf" /></Relationships>PK    ÇˆwJÏµ `  :    docProps/app.xml ¢ (                      “MNÃ0…¯¼oB…P”¸ª  ¢,‘q&­Eb[ö4J¹ŽÄp(iùìÆo¾Ì¼yR^žžãI]AÖI­2†$ %t&Õ2!kÌ'dÂbn¢Ôj%¸À¢\TaBVˆ&¢Ô‰”Ü
=¡|3×¶äèŸvIužKgZ¬KPHÃð˜fZ4ÓÜÍbcÀ‘·yÜüwÔ*ƒl`¶IëyjL!G»Âj§sfµ€"¦{ý†÷cç ÖVâ†…-ÑWb.x§~
Ëyá e>´†8Þ„—ri‹+Œ*¨mpÏ4÷&¤âVr…$pòÑ?Ç¤Ã:µ­ãÐ²[mÜ
 ]L·b[öÙ~-ÇlÔ¾øìf]ò²àš«%üeÅá×+èöVÖÆ²„pWyÊ-~Mkà=˜#Òó:«¶Øw¹×:H­Tx7µÀ§:+Ÿnî¹ß3Kwþ ö
PK    ÇˆwJ>çÊ­a  ÿ    xl/sharedStrings.xml ¢ (                      ’ÉNÃ0†_eähÂ¢
U]$J…8ÐF¥H\Ýdšy	ö8*¼QoÜ9 ‘âp‚âÂeäñ|³ýöÇëÛp²U*´N=bÇ½˜êÔdBç#æistÎ&ãávàAj¼¦ 1ðZ<zœþ\„2Ú
¶#V•ƒ(riŠ»ž)Q‡ØÆXÅ)¸6\i‘g®@$%£“8îGŠÍÚ6¢±4ž‚äàL*êÕ»aÔû}£SÀÄ8â²¹Å”Ð[ÈxJ¢{ªµ}XUS`»¨ÄÖ;ý/ò’6›¤!ƒSù/Pí7"ÝË†!×6Ðž„Ž7Ë¹n}”Â0£°Ø‰,æÓY²‚Ù}²€«åâ.é"Ùwè•;n	r.%Z«3Xâ:Œ.[ïÙiòÖÍ¹ÍP;ÖUuUÔ;ûÔ½°^›®à2« ´Æ•á‰ƒbÍù	,jã+¸^Ái?~ùµßyü	PK    ÇˆwJ'J|2â   ¼    xl/_rels/workbook.xml.rels ¢ (                      µ’ANÃ0E¯bÍžL(¨B¨n7lº¥½€åLâ¨‰my¦´=‹©WÀ	aÄ‚M6¶üÇóôÆòíýºÚœÇA½Qâ>x
÷U
Š¼
Mï;
Giïž`³^½Ò`$ß`×GV¹Å³'ŸÙ:
W!’Ï•6¤ÑH>¦£±Ó.êz‰é'J¦Ú_"ý‡Ú¶·ôìq$/€‘IÔì$å	ÔÞ¤ŽDž‡²Te2¨m£!m›P8Ÿ‘\ú­2e…Ããœ§ìˆ¤ÔøŽ?ß-o…ÐbN!É½TÊLÑ×Zx,',þàúPK    ÇˆwJ´ÁmêM  z  
  xl/styles.xml ¢ (                      íVÛjÜ0ý¡÷F»†–²¬ÚC ¤¥ÙB_e{l«ÑÅHòÆ›_ëC?©¿PÝì½Z¶”@¡û¢™ã9£¹IÚï_¿­¯FÁÑ´aJæxy±Àd¥j&Û¶yñ_]®Ç•±;÷€EŽ!ÍjÌqgm¿"ÄTj.TÒ}k”Ô:U·Äôhm<Mp’-¯ˆ LbïQ¢Ö J
Òº­@—›:Ç.žèðZÕcŒÈåšÌdOi”<õâ!¿º¼ìÎZ‰¶”ç¸¤8“œ¸”ž"¼\& R\i¤Û2ÇE±¿ôERÑøšrVj–ð†
ÆwñK6ÅwOB‘q>‡˜á	òkO­-§¢$ov½ËTª(Ùÿ–Ôjº[f/yI‘”J×®ÙÇåŠ ªm•¤üSÊ>©ïÔ£ô€·äÐXF!ø«²‘hïM4k»³ˆàm¬êÏá9ó˜‘µJœCŒo4å}{â$W¾œb¨|œß{Ÿ›“Q›Óy—³èú–Äè*)´ïùîn%è"œßÊˆú¡ØkokÏ	§A€< |ÐÊBeãùõ3‚¸ª Æ«k“’›Ÿ¢Ï²+|rÜ—©O£Ecó,ÉÒÉuJ³'—¿‹Z )Çþf·¬
—_pŒ,Œö£²4:q{=jÚo&ë°¡5pg´…›=ôe0–5»[jì­»Gf:ÍäÃFl¢Qÿx¼Ÿs!Ï2RÿËý‡å&óÈÝR'OÄŒ#ÿæøÎ—–”½·L&-Ôý_ˆËPK    ÇˆwJryNÎm  ˆ    xl/worksheets/sheet.xml ¢ (                      •ÝnÛ0…_Åðýbç?
šmÒ´6¤h‡íZµéX¨,”Ü´}µ]ô‘ö
£¥¤H:ØH::!ú÷¯÷ó‹—JEÏ€V=‹»4Ž@g&—z;‹W|™Äóó—éÎà“-\D´â,.«§Ib³*a;¦Mß
ƒ•pâ61E!3Xš¬©@»¤—¦£A	G‡ÙRÖ6Þ«½üš­DîMT*ˆUBê¸µç³wØ.Mã”Ôp‡‘mªJàë(³£ÚâCâ^nKçÉü<9ÙœKrÚÞE„PÌâËîtÝóØžú!agO¢¨½™GcžÚ`ÏâôDötÃÊ—CÖr(D£Ü½ÙÝÂÞÍðøœ¥p¢
Ðì"Þk¡-­¦g¾à¬M_¶y"	XŸž§íÙÏÞAöA^qd—#ÙãÈ%Gö9òš#¹âÈ!GÞpäˆ#o9rÌ‘kŽœœ‰ïÉQkzÿhM‘:c[sLêCkú)ÛÇ'ÛeÑ%‹²=¿fQ¶é«€vMìÒAg”ŽÓn2™°ÞüµevúýáÙ(
&¬¡[îNØ*×¬õ>Û³äÓãªQj·©ý4ŠJƒòÍh'Ô‚f „§L£ÑÉìS²¤9D2œ»E™¥cOŸ„Å¾	ÜJÒUP³´3¦÷á©‡À™ú°|4Î™ª†ApÆ¸Œ‡Gâàš:ªE
ø ß rÙ®RrÑ2ô2¹Ùéï%è
UGT$â0}
CˆÎW"{ºÔùÏR:ðeä(¼í8Ê@©…©ÚNj£þˆ)Ê¥­•x…|o-X_yÏ!ãÄ£‚;ÎF™i´;”ùPK    ÇˆwJu±‘^«  »    xl/theme/theme.xml ¢ (                      íYMÛDþ+#ß[ÇIœfWM«M6i¡ÝvµŠzœ8{š±Çš™ì67Ô‘qAâÆ•Z‰Eü˜…"(Òþ^;^{œŒ»ÙvEl‰gü¼ß~Ç9þé—«×†!):–s¹f!y|L#¿cÍÔäRÛº~í*ÞT		p$7qÇ
”Š7m[z°åe“îM¸±‚¥ðí±À‡À$dv½VkÙ!¦‘…"’Žuw2¡AÃ„¥•3ï3øŠ”L6<&ö½T¢N‘bÇS'ù‘sÙc`Ö±@Î˜ÉCe!†¥‚«–~,d_»jçTLUk„ƒôsB˜QŒ§õ”Pø£œÒ47®lê	«À~¿ßë;Ç=¬uVÀÍAÛéæ\5Ôâr•{¯æÖšKš„Æ
ÁF·Ûu7Ê‚ ¹BÐ®µš[õ2A³ pWmènõz­2[´VW6ZÍ%‚0MWàId‹å˜	g7ø6àÛy.0[Ë´ƒHUå]ˆp1 @e¬h„Ô<&ì®‡Ã‘ 8•€7	Öne{ž\ÝKÄ!é	«Žõ~Œ¡@
Ìñ‹ïŽ_<CÇ/ž=z~ôèÇ£Çý`¢¼‰#_§|õÍ§}õúóÙ×¯ž|^A u‚ß¾ÿø×Ÿ?«@*ùò‹§¿?úòËOþøö‰	¿%ðHÇiH$ºCÑû"ÈHœ‘d`Z"Á@MÈ¾
JÈ;sÌŒÀ.)ûðž€¶`DÞ˜=(é»ˆ™¢&ä­ ,!w8g].Ì6ÝJÅi6Í"¿B¾˜éÀ=ŒŒâ{KQîÏbÈljdÚHIÕ]Ç>‰ˆBÉ=>%ÄDwŸÒ’w¨'¸ä…îSÔÅÔì˜!)3ÕMB€æF!ê%íÜC]ÎŒ¶ÉA
‚™‘)a%oÞÀ3…C³Ö8d:ô6VQÑý¹ðJŽ—
‚îÆQL¤4Ýó’Ê·0´(sì°yX†
E§FèmÌ¹ÝæÓ^€ÃØ¬7üžœBÆb´Ë•Y^®™d
ÁQuäïQ¢ÎXìP?0'Krg&Nºz©?‡4z]³fºõE³^jÖ[ð3Ér‹®þGó6žE»$Iþ‹¾|Ñ—/úòk*|ín\4`[Ÿ«S†aå=¡Œí«9#·eÚº%è=ÀfºH‰ò¡>àòD^	èœ^#ÁÕ‡TûŽAŽ“ŠðeÆÛ—(æV%óôlJÁütÏÍ” Çj‡ûÒI3g”®|©‹j$,Ö×¸ò¶âœrMyŽ[!Ï}½<[ó)ÔÂÉ›§UÏÔ”fdœx?ãps”ð˜d¡rÌ¶8u}×>Ýuš¼ÆÛÊ['VºÀf•@÷<‚U[
–½Z,*¯Ð!(æÖ]y8îX¼à2Œ¡LZf~Ô±<•Ysjm/Û\‘ N­Úæ’XHµe° Koå/e¢Â„ºÛLØ
¦þ´¦¶ó¯êa/G˜L&ÄS;Å2»ÇgŠˆý`|ˆFl&ö0hÞ\dÙ˜Jx”ÔOêµ™%`¹dõ°üê'«Ìâ g=ª­gÀŸ^çJ¤+M?»Bù7´¥qŽ¶¸ÿg[’ô…ñ¶1NÏa0Œ’<íX\¨€C?Šê
L©0PAm¤-‹%¯°eÉÖÂL
ÏÔõ‘ ÐõT ÙU™¥§psN:dV§¬ãä
Ëxñ;"„
“"n%.°P·•Ì)p9p¶©ÆFþà]žŠšUSÑ)cC!ªy–)¥©?´gÃÆÛjqÆp½Âìº»þ8†“
J¾ ‘Sá±bò=ÈT’—ÚY)æ›#Ðº­Û—ðúgg¬"íª¸Ÿëxªy¼QåñS¾¹Ç]ƒÃÝSüm¯¬­yÒÕÊß]|ô „oÃ™jÆ”ÌÞK=„Óiïäß	`”ÉL‰¯ý
PK
     ÇˆwJNUûýÚ  Ú  Q  package/services/metadata/core-properties/7a17c4849f0b4e2ca72c4a5b525d9f97.psmdcp ¢ (                      ï»¿<?xml version="1.0" encoding="utf-8"?><coreProperties xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"><dcterms:created xsi:type="dcterms:W3CDTF">2017-03-23T16:06:15.7944240Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2017-03-23T16:06:15.7944240Z</dcterms:modified></coreProperties>PK
     ÇˆwJ½g].5  5    [Content_Types].xml ¢ (                      ï»¿<?xml version="1.0" encoding="utf-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml" /><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml" /><Default Extension="psmdcp" ContentType="application/vnd.openxmlformats-package.core-properties+xml" /><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml" /><Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml" /><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml" /><Override PartName="/xl/worksheets/sheet.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml" /><Override PartName="/xl/theme/theme.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml" /></Types>PK-     ÇˆwJ±ùS  º                   xl/workbook.xmlPK- 
     ÇˆwJÔ^S¨œ  œ               L  _rels/.relsPK-     ÇˆwJÏµ `  :               -  docProps/app.xmlPK-     ÇˆwJ>çÊ­a  ÿ               ×  xl/sharedStrings.xmlPK-     ÇˆwJ'J|2â   ¼               †  xl/_rels/workbook.xml.relsPK-     ÇˆwJ´ÁmêM  z  
             ¼  xl/styles.xmlPK-     ÇˆwJryNÎm  ˆ               P  xl/worksheets/sheet.xmlPK-     ÇˆwJu±‘^«  »                 xl/theme/theme.xmlPK- 
     ÇˆwJNUûýÚ  Ú  Q               package/services/metadata/core-properties/7a17c4849f0b4e2ca72c4a5b525d9f97.psmdcpPK- 
     ÇˆwJ½g].5  5               j  [Content_Types].xmlPK    
 
 ¾  ì

**Comment by JoshClose** [comment]
This might be easier... Can you write a short contained example that recreates the problem?

**Comment by gabygit** [comment]
So you would like me to give you my C# file but with only what matters for this case? I can give you that, yes :)

**Comment by JoshClose** [comment]
Yes. Kinda like a unit test.

**Comment by gabygit** [comment]
```
namespace ConsoleApplication2
{
    public partial class Program
    {
        static void Main(string[] args)
        {
            string pathString = Server.MapPath(@"~\ExcelTmpFiles\file.xlsx");
            IList<String> list = new List<String>();
            list.Add("Museums, art galleries, and botanical and zoological gardens");
            // Write the list into a xls file then save this file
            using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                using (var writer = new CsvWriter(new ExcelSerializer(workbook)))
                {
                    writer.WriteRecords(list);
                }
                workbook.SaveAs(pathString);
            }
        }
    }
}
```

**Comment by gabygit** [comment]
```
using System.Collections.Generic;
using CsvHelper;
using CsvHelper.Excel;
using System.IO;
using ClosedXML.Excel;

namespace ConsoleApplication2
{
    public partial class Program
    {
        static void Main(string[] args)
        {
            string pathString = Directory.GetCurrentDirectory() + "\\ExcelTmpFiles\\file2.xlsx";

            IDictionary<string, string> map = new Dictionary<string, string>();
            map.Add("1","Museums, art galleries, and botanical and zoological gardens");
            map.Add("2", "example");
            // Write the list into a xls file then save this file
            using (var workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                using (var writer = new CsvWriter(new ExcelSerializer(workbook)))
                {
                    writer.WriteRecords(map);
                }
                workbook.SaveAs(@"C:\Users\gabriel\Documents\Mes notes\file2.xlsx", false);
            }
        }
    }
}
```

**Comment by gabygit** [comment]
![image](https://cloud.githubusercontent.com/assets/25452154/24291678/3c49e4a8-108a-11e7-915e-40f382f82523.png)
I got this :/

**Comment by gabygit** [comment]
It seems to be the comas that causes the problem. How can I do to write "," in my file but not the """" around my string?

**Comment by JoshClose** [comment]
What is `ExcelSerializer`?

**Comment by gabygit** [comment]
I don't really know what this is. I found this solution on the Internet. How would u create a new xlsx file?

**Comment by JoshClose** [comment]
You may need to contact the `CsvHelper.Excel` project and ask them this question. That serializer is what is doing the writing.

**Comment by gabygit** [comment]
Ok ;) Thnaks

**Comment by christophano** [comment]
In case anyone else has trouble with this the solution (as noted in christophano/CsvHelper.Excel#6) it was fixed by setting `writer.Configuration.QuoteNoFields = true;`
