### ISSUE TITLE
Type is not resolved for member 'CsvHelper.CsvReaderException,CsvHelper, Version=2.0.0.0,

### ISSUE THREAD

**Issue by pinaki1234** [JoshClose/CsvHelper#660]
I am getting this error:
Type is not resolved for member 'CsvHelper.CsvReaderException,CsvHelper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'.
Though I can see that I have added the latest package:
<package id="CsvHelper" version="2.16.3.0" targetFramework="net45" />
In packages.config.

What might have gone wrong? Thanks

**Comment by JoshClose** [comment]
Sorry, there isn't enough information for me to understand the issue. Are there any more details you can include?

**Comment by JohnyWaster** [comment]
pinaki1234, I have the same issue. Do you remember, how you solved it?
