### ISSUE TITLE
3.0.0-beta7: CsvWriter.WriteRecord don't calls NextRecord?

### ISSUE THREAD

**Issue by dmitry-azaraev** [JoshClose/CsvHelper#662]
Whenever we call CsvWriter.WriteRecord looks like NextRecord is not called automatically. This is looks like a bug.

**Comment by JoshClose** [comment]
This is intentional so the reader and writer are consistent. It also allows you to do other things after calling Read/WriteRecord. You may want to manually write more fields, and do something else.
