### ISSUE TITLE
Question - Support for global registration of custom type converters

### ISSUE THREAD

**Issue by lambdakris** [JoshClose/CsvHelper#664]
Is it possible to register global type converters such that once registered, the auto mapping will utilize the custom converter every time it encounters the type it is registered for?

**Comment by JoshClose** [comment]
Yes. You can use the `TypeConverterFactory` to do that. Check out how it's used internally. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/TypeConverterFactory.cs#L196
