### ISSUE TITLE
3.0.0-beta8 reports assembly version as 0.0.0.0

### ISSUE THREAD

**Issue by Mertsch** [JoshClose/CsvHelper#665]
`
    <Reference Include="CsvHelper, Version=0.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823, processorArchitecture=MSIL">
      <HintPath>..\packages\CsvHelper.3.0.0-beta8\lib\netstandard1.3\CsvHelper.dll</HintPath>
    </Reference>
`

**Comment by JoshClose** [comment]
Where are you seeing this?

**Comment by Mertsch** [comment]
By adding the package to a classic C# project with packages.config in the `.csproj` file

**Comment by JoshClose** [comment]
For some reason setting the `<AssemblyVersion>` in the `.csproj` file doesn't do the job. I have to set it in the `AssemblyInfo.cs` file. I'll push a new version that is fix, then ask the core team why this is.

**Comment by JoshClose** [comment]
I pushed version 3.0.0-beta10. It should show up shortly.

**Comment by Mertsch** [comment]
@JoshClose I assume you are now using the 2017 `.csproj` file.
If so, try setting the
`<Version>3.0.0-beta9</Version>` and remove all other `<xxxxVersion>`s
