### ISSUE TITLE
Writing a list of arrays

### ISSUE THREAD

**Issue by JaviFuentes94** [JoshClose/CsvHelper#667]
Hello,

I am trying to write a `List<double[]>` into a csv file. Based on my experiments it is not possible using `WriteRecords` directly, so I am looking for alternatives. 

I cannot create a class to map this data because the number of elements in the arrays varies from execution to execution, and ranges from 1 to 75. 

I have tried to go through each element of the array manually with `WriteField()` but it is really slow., and I have thousands of elements. 

Is there anyway to accomplish this fast enough?

Thanks.

**Comment by JoshClose** [comment]
I would suggest serializing the data into a string. Make up a format, or just use a json serializer. Then you can just write that single field.
