### ISSUE TITLE
CheckHasBeenRead() called twice

### ISSUE THREAD

**Issue by kslesinsky** [JoshClose/CsvHelper#672]
Just a quick thing I noticed: In CsvReader.IsRecordEmpty() it calls CheckHasBeenRead() and then IsRecordEmpty(true).  But in IsRecordEmpty(bool checkHasBeenRead), it calls CheckHasBeenRead() again... since it passed in true to the boolean.

**Comment by JoshClose** [comment]
Thanks!

**Comment by kslesinsky** [comment]
sure thing!
