### ISSUE TITLE
Writing Byte Array

### ISSUE THREAD

**Issue by jamesbascle** [JoshClose/CsvHelper#676]
Change in behavior between 2.16.3 and 3.0.0-chi02 is that byte[] used to not have a default serialization.  Now it simply writes them out as a list of integers in base 10 separated by the delimiter.

**Comment by JoshClose** [comment]
I can create a type converter for it... What do you think the default should be? Base64 encoded?

**Comment by jamesbascle** [comment]
A good question... For binary data SQL Server uses 0x9B3C42D0AA4...
format.  Perhaps that with some options?

**Comment by JoshClose** [comment]
What format is that? I'm not easily finding the answer from google.

**Comment by jamesbascle** [comment]
Just it's just a hexadecimal number, like you can write in C# to write a
hex literal.

**Comment by JoshClose** [comment]
What if the binary is large? Like an image or something.

**Comment by jamesbascle** [comment]
Hmm. Good question. I've only tried it on relatively small ones.  I'll give
it a shot and see if there's a size limit next time I log into a SQL
server.

**Comment by jamesbascle** [comment]
select 0xE5353655952F3A0222D47A178D8854FABECCC682F74101234F74A7 .... seems to work fine up to many thousands of characters. If you think this is the way to go for the default converted, I can run putting the one I wrote into the project  by my boss , if you like.

**Comment by JoshClose** [comment]
There are some interesting discussions on this...

http://stackoverflow.com/questions/311165/how-do-you-convert-byte-array-to-hexadecimal-string-and-vice-versa

http://stackoverflow.com/questions/14332496/most-light-weight-conversion-from-hex-to-byte-in-c/14332574#14332574

**Comment by jamesbascle** [comment]
Yeah I wrote something similar using the unsafe byte lookup method at an
old job.  That's probably the right way to go if you want to do the 0x...
As the default implementation.  We could also add some enum options to it
to select base64, without the 0x, another delimiter separated decimals(like
it is now, just not using the primary delimiter), etc.

**Comment by JoshClose** [comment]
Since you can use your code, I assigned this to you. ;)

**Comment by jamesbascle** [comment]
Sounds good - I've started making it ready to pull into CsvHelper at https://github.com/jamesbascle/CsvHelper/tree/FT-ByteArrayConverter - what are your thoughts?  Want to make sure I'm on the right track in terms of concept (still no tests yet ;))

**Comment by JoshClose** [comment]
I missed this. I'll take a look now.

**Comment by JoshClose** [comment]
Is this supposed to be `b[0]` here not `b[i]`? https://github.com/jamesbascle/CsvHelper/blob/FT-ByteArrayConverter/src/CsvHelper/TypeConversion/ByteArrayConverter.cs#L53

**Comment by JoshClose** [comment]
I think it looks good. Having options to do either format will be nice.

**Comment by jamesbascle** [comment]
Yeah definitely supposed to be b[i], bug left over from some other change i had made from the original. good catch

**Comment by JoshClose** [comment]
I'm sure the future unit test would have caught that anyways. ;)

**Comment by JoshClose** [comment]
Man, it's funny because I hate writing unit tests and do it minimally most of the time, but for this project I make sure I cover absolutely everything. It's saved my butt so many times. Especially when re-writing the parser from scratch like I did recently.

**Comment by Bitfiddler** [comment]
So I have tried using @jamesbascle code, I needed to adapt it because the ITypeConverter definition in his project is different than the stable version of CsvHelpers on nuget, but when I try to register the type converter like so:

    TypeConverterFactory.AddConverter(typeof(Byte[]), new ByteArrayConverter());

When the ConvertFromString method is called, the 'text' being passed to the typeconverter is "System.Byte[]" and not the value in the csv file.  To me this looks like a bug, but perhaps I am not understanding how this should all fit together.

**Comment by Bitfiddler** [comment]
I just tried downloading the latest pre-release and now the ITypeConverter definition lines up with @jamesbascle version (so now I know where that came from) but the issue of the TypeConverterFactory passing the TypeName instead of the conversion text value remains.

**Comment by JoshClose** [comment]
.NET Core 2.0 is out and I'm down to the last couple of features. I'm planning on releasing pretty soon here.

Is this something you want to finish, or should I take it over?

**Comment by jamesbascle** [comment]
I thought I submitted a PR for this? I am currently recovering from a
surgery, so cannot check at the moment.

**Comment by JoshClose** [comment]
Get well soon James! You did submit one but it wasn't complete, based on the conversation here. Just one bug and a unit tests left though. I'll merge your pull request and put the unit tests in. Thanks for doing this work!

**Comment by JoshClose** [comment]
I merged your pull request. Thanks again.
