### ISSUE TITLE
Update Documentation for ConvertUsing Only Works on Reads

### ISSUE THREAD

**Issue by spottedmahn** [JoshClose/CsvHelper#679]
Can the documentation at [joshclose.github.io/CsvHelper](http://joshclose.github.io/CsvHelper/) on ConvertUsing be updated to mention it only works on reading, not writing?  Is this page in the repo?  Perhaps I can submit a PR for it?

[Source](http://stackoverflow.com/questions/21678385/csvhelper-convertusing-not-changing-output)

Thanks,
Mike D.

**Comment by hellboy81** [comment]
Is there alternative for writting?

**Comment by JoshClose** [comment]
Currently, no. I would think it would be useful consider it is for reading.

**Comment by StefanBertels** [comment]
I currently (CsvHelper 2.x) use this workaround:
```
    public static CsvPropertyMap UsingExpression<T>(this CsvPropertyMap map, Func<string, T> readExpression,
            Func<T, string> writeExpression)
        {
            return map.TypeConverter(new ExpressionConverter<T>(readExpression, writeExpression));
        }
```

```
        public ExpressionConverter(Func<string, T> readExpression, Func<T, string> writeExpression)
        {
            _ReadExpression = readExpression;
            _WriteExpression = writeExpression;
        }

        private Func<string, T> _ReadExpression { get; set; }
        private Func<T, string> _WriteExpression { get; set; }

        public bool CanConvertFrom(Type type)
        {
            return type == typeof(string);
        }

        public bool CanConvertTo(Type type)
        {
            return type == typeof(string);
        }

        public object ConvertFromString(TypeConverterOptions options, string text)
        {
            return _ReadExpression(text);
        }

        public string ConvertToString(TypeConverterOptions options, object value)
        {
            return _WriteExpression((T) value);
        }
```

```
// example using Option<int> for property "ColumnName" (using LanguageExt.Core)
// parseInt is the readExpression (reads raw string and returns Option<int>)
// oi => oi.Match(i => i.ToString(), () => "") is the writeExpression (turns Option<int> into string representation)

Map(m => m.ColumnName).UsingExpression(parseInt, oi => oi.Match(i => i.ToString(), () => ""));
```

My current problem is: this does not work in 3.x anymore. @JoshClose: Is there some replacement?
A ConvertUsing with both directions would be fine.

**Comment by JoshClose** [comment]
There is a ConvertUsing overload for writing now in 3.0. I don't remember if I've released it to NuGet yet though. I can check later when I get to a computer

**Comment by JoshClose** [comment]
I just pushed a new pre-release version to nuget. This is the commit that adds `ConvertUsing` for writing. https://github.com/JoshClose/CsvHelper/commit/e40570fb314af1af1bf2b598695c6e0bff234594

**Comment by JoshClose** [comment]
I'm closing this since it doesn't apply anymore.

**Comment by spottedmahn** [comment]
thanks Josh!
