### ISSUE TITLE
TypeConverterOption additional 'object CustomOption'

### ISSUE THREAD

**Issue by gojanpaolo** [JoshClose/CsvHelper#680]
It would be really great if we could add another parameter to the TypeConverterOption.
This will further enhance the flexibility when using Custom TypeConverter.
As a sample,

```
    public class CustomTypeConverter : ITypeConverter
    {
        public object ConvertFromString(TypeConverterOptions options, string text)
        {
            var myCustomOption = options.CustomOption as CustomOptionClass;
            //do what other things for conversion based on custom option...
        }
        //...
    }
```

**Comment by jamesbascle** [comment]
Just add it to the constructor of your type converter. No need for the
this, I think.

**Comment by JoshClose** [comment]
If James's solution doesn't work for you, let us know.

**Comment by hellboy81** [comment]
Solution with constructor params has following issues:

If custom params is field specific => it should be multiple custom converter instantiated.  

Also constructor injection => global csv specific params.

I need field specific conveter params => For example max field length.

**Comment by jamesbascle** [comment]
I dont understand your problem or question. Can you post your code and/or
be very specific with a failing test or piece of code.

**Comment by hellboy81** [comment]
I have posten some code: 

See sample:

https://github.com/JoshClose/CsvHelper/issues/480#issuecomment-307320336

>Just add it to the constructor of your type converter. No need for the this, I think.

I have CSV with 256 columns with string type. 

Each column has distinguish maxLength param.
In this case I should create 256 converter object instances.

Is it bad or not so bad?

**Comment by hellboy81** [comment]
At the moment see the only option to avoid creating converter intance for each field:

use `format` option:

````c#
.TypeConverterOption.Format(":limit => 5");
````

**Comment by hellboy81** [comment]
>If James's solution doesn't work for you, let us know.

@JoshClose  I need your opinion.
