### ISSUE TITLE
TypeConverterOptionsFactory.typeConverterOptions is a dictionary instead of a ConcurrentDictionary

### ISSUE THREAD

**Issue by jamesbascle** [JoshClose/CsvHelper#682]
If the configuration is used in more than one writer at the same time, an "An item with the same key has already been added." System.ArgumentException can be thrown.

Should this be concurrent, or is 1 instance of CsvConfiguration explicitly prohibited from being used in multiple writers/readers at the same time?

**Comment by jamesbascle** [comment]
Also, this is in Chi2

**Comment by JoshClose** [comment]
What method is that exception happening in?

**Comment by jamesbascle** [comment]
Here's the stacktrace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(Type type)
   at CsvHelper.CsvWriter.CreateActionForObject(Type type)
   at CsvHelper.CsvWriter.GetWriteRecordAction[T](T record)
   at CsvHelper.CsvWriter.WriteRecords(IEnumerable records)

**Comment by JoshClose** [comment]
By `at the same time` do you mean on different threads?

**Comment by jamesbascle** [comment]
Yes. I had to change the code in question to lock on first use,
unfortunately, but that should be unnecessary imo.

**Comment by JoshClose** [comment]
Do you think this should be solved with a `ConcurrentDictionary` or locking or something better?

Having the factory be a part of the config was supposed to solve that problem... unless you're sharing the config I guess. :)

**Comment by jamesbascle** [comment]
I think a double checked lock is probably the best approach over a
concurrent dictionary.  Do any other methods access it?

**Comment by JoshClose** [comment]
http://stackoverflow.com/a/6018823/68499

Looks like there could be issues with double check locking in this case.

**Comment by JoshClose** [comment]
I just added good old fashioned locking. The code isn't run often. https://github.com/JoshClose/CsvHelper/commit/1e306db6788d5f6758d01aab025b91815692b27e
