### ISSUE TITLE
 [EF6] Context.SaveChanges() replace class FK ID

### ISSUE THREAD

**Issue by nolme** [JoshClose/CsvHelper#683]
Hi,

I've posted on MSDN a strange behaviour during call to SaveChanges() : 
https://social.msdn.microsoft.com/Forums/en-US/e9bbba46-af21-486c-896c-5e3f88d87dd9/ef6-contextsavechanges-replace-class-fk-id?forum=csharpgeneral

They tell me it's a CSVHelper issue but I'm not sure about it. Does someone can confirm this ?
Thanks,
Vincent

**Comment by jamesbascle** [comment]
CsvReader implements IDisposable. It may not be properly flushing the
buffers without a using block.  I would suggest to you to only hold the
reader open as long as absolutely necessary.

Define records outside the using block as List<AnimalSubSpecie> record.
Capture the records using records =
csv.GetRecords<AnimalSubSpecie>().ToList();
inside the using block.

Do your EF stuff outside the using block with the items now in the list in
the records variable.

**Comment by JoshClose** [comment]
Looks like you shouldn't be using `AddOrUpdate` http://stackoverflow.com/a/31273044/68499

Instead, update the tracked entity from EF that you just queried for.

**Comment by jamesbascle** [comment]
Also a good idea.  My suggestion was to enable isolation of the problem,
since CsvHelper and EF would be used in different peices of code instead of
being intermixed.

**Comment by nolme** [comment]
You're right, I've changed my code to separate CSVHelper & EF6 :
`public static DBImportResult CsvImport_AnimalSubSpeciesById(GpaContext ctx, string csvFile, char separator)
        {
            DBImportResult result = new DBImportResult();

            try
            {
                List<AnimalSubSpecie> records;
                using (TextReader reader = File.OpenText(csvFile))
                {
                    var csv = new CsvReader(reader);
                    csv.Configuration.Delimiter = separator.ToString();
                    csv.Configuration.Encoding = Encoding.Default; ;
                    records = csv.GetRecords<AnimalSubSpecie>().ToList();
                }

                // Method 2 - Check each item to update counters
                foreach (AnimalSubSpecie rec in records)
                {
                    // List all species by IDs.
                    List<AnimalSubSpecie> searchQuery = ctx.AnimalSubSpecies
                                    .Where(b => b.Id == rec.Id)
                                    .OrderBy(b => b.Id)
                                    .ToList();

                    if (searchQuery.Count == 0)
                    {
                        // Insert item
                        ctx.AnimalSubSpecies.Add(rec);
                        result.NewItems++;
                    }
                    else
                    {
                        // Update item manually
                        searchQuery.First().Name = rec.Name;
                        searchQuery.First().SpecieId = rec.SpecieId;

                        // Change state
                        ctx.Entry(rec).State = EntityState.Modified;
                        result.UpdatedItems++;
                    }
                    result.TotalItems++;
                }
            }
            catch (FileNotFoundException)
            {
                result.ErrorItems = -1;
            }
            catch (Exception e)
            {
                result.ErrorItems = -1;
                throw;
            }

            return result;
        }
`

My table is empty at first run. We can see that records contains good values for SpecieId : 
![csvhelper1](https://cloud.githubusercontent.com/assets/4461224/26281885/b025e136-3e04-11e7-9536-bbb34f18fe23.png)

Just a little check BEFORE SaveChanges() :
![csvhelper2](https://cloud.githubusercontent.com/assets/4461224/26281895/ead067f2-3e04-11e7-85d8-a28b04e66558.png)

And just AFTER, values are changed : 
![csvhelper3](https://cloud.githubusercontent.com/assets/4461224/26281914/62c0e3f4-3e05-11e7-9ba0-fc8fe7eeaaf7.png)
