### ISSUE TITLE
why my second line is't records,and is a current record and rawrecord

### ISSUE THREAD

**Issue by veyvin** [JoshClose/CsvHelper#686]
lat	lon	rotation	type
45.001	120	0|0|0	1
45.002	120	0|0|0	1
45.003	120	0|0|0	1
45.004	120	0|0|0	1
45.005	120	0|0|0	1
45.006	120	0|0|0	1
45.007	120	0|0|0	1
45.008	120	0|0|0	1
45.009	120	0|0|0	1
45.01	120	0|0|0	1
45.011	120	0|0|0	1
45.012	120	0|0|0	1
45.013	120	0|0|0	1
45.014	120	0|0|0	1
45.015	120	0|0|0	1
45.016	120	0|0|0	1
45.017	120	0|0|0	1
45.018	120	0|0|0	1
45.019	120	0|0|0	1

**Comment by JoshClose** [comment]
I don't understand what you're asking. Do you have some example code?

**Comment by veyvin** [comment]
`public class TowerInfo
{
    public string lat { get; set; }
    public string lon { get; set; }
    public string rotation { get; set; }
    public int type { get; set; }
}
public sealed class TowerMapping : CsvClassMap<TowerInfo>
{
    public TowerMapping()
    {

        Map(m => m.lat).Name("lat").Index(0);
        Map(m => m.lon).Name("lon").Index(1);
        Map(m => m.rotation).Name("rotation").Index(2);
        Map(m => m.type).Name("type").Index(3);
    }
}`
`    public void ReadCSV()
    {
        var tr = new StreamReader(csvPath);
        var csv = new CsvReader(tr);
        csv.Configuration.RegisterClassMap<TowerMapping>();
        csv.Read();
        var records = csv.GetRecords<TowerInfo>().ToList();
        foreach (var item in records)
        {
            latlon.Add(new Vector2d(Convert.ToDouble(item.lat), Convert.ToDouble(item.lon)));
            Debug.Log(item.lat);
        }
        tr.Close();
    }`

**The item.lat is** 
lat,lon,rotation,type
45.002,120,0|0|0,1
45.003,120,0|0|0,1
45.004,120,0|0|0,1
45.005,120,0|0|0,1
45.006,120,0|0|0,1
45.007,120,0|0|0,1
45.008,120,0|0|0,1
45.009,120,0|0|0,1
45.01,120,0|0|0,1
45.011,120,0|0|0,1
45.012,120,0|0|0,1
45.013,120,0|0|0,1
45.014,120,0|0|0,1
45.015,120,0|0|0,1
45.016,120,0|0|0,1
45.017,120,0|0|0,1
45.018,120,0|0|0,1
45.019,120,0|0|0,1

**not contain** 
45.001,120,0|0|0,1

**Comment by veyvin** [comment]
In unity I find this error,but this is right. Above write in Unity3d with mono .  Below is .net framework.

```
namespace ConsoleApp3
{
    public class TowerInfo
    {
        public string lat { get; set; }
        public string lon { get; set; }
        public string rotation { get; set; }
        public string type { get; set; }
    }
    public sealed class TowerMapping : CsvClassMap<TowerInfo>
    {
        public TowerMapping()
        {

            Map(m => m.lat).Name("lat").Index(0);
            Map(m => m.lon).Name("lon").Index(1);
            Map(m => m.rotation).Name("rotation").Index(2);
            Map(m => m.type).Name("type").Index(3);
        }
    }
}
```

```
namespace ConsoleApp3
{
    class Program
    {
        private static string csvPath;
        static void Main(string[] args)
        {
            csvPath = @"F:\Technology\testmapbox\sdkproject\Assets\StreamingAssets\towerLatlon.csv";
            ReadCSV();
        }
         static void ReadCSV()
        {
            var tr = new StreamReader(csvPath);
            var csv = new CsvReader(tr);
            csv.Configuration.RegisterClassMap<TowerMapping>();
            csv.Read();
            var records = csv.GetRecords<TowerInfo>().ToList();
            foreach (var item in records)
            {

                Console.WriteLine(item.lat);
            }
            tr.Close();
        }
    }
}

```

**Comment by veyvin** [comment]
@JoshClose  sorry .oh should not use **csv.Read();** i'm ok
```
 using (var streamReader=File.OpenText(csvPath))
            {
                var reader = new CsvReader(streamReader);
                var users = reader.GetRecords<TowerInfo>().ToList();
                foreach (var item in users)
                {
                    Console.WriteLine(item.lat);
                }
            }
```
