### ISSUE TITLE
Type safety (avoid runtime errors) with Map / Default / ConvertUsing

### ISSUE THREAD

**Issue by StefanBertels** [JoshClose/CsvHelper#689]
(Thought I had submitted this already, but cannot find the issue.)

In 2.0 it worked, in 3.0 I get a runtime exception for

`
Map(e => e.ByteProperty).Name("FIELDNAME").Default(0);
`

because 0 is an `int` and ByteProperty is of type `byte`. I can fix this in two ways:

`
Map(e => e.ByteProperty).Name("FIELDNAME").Default((byte) 0);
`

Which seems straightforward because the type of the Property gets lost.
Or I can use this one:

`
Map(e => e.ByteProperty).Name("FIELDNAME").Default<byte>(0);
`

Which looks better to me.

Suggestion: Make the result of Map a generic type like CsvPropertyMap<T> here so Default and ConvertUsing would be forced to have the correct type (and I could ommit `(byte)` and `<byte>`).

Remark: somewhat related to #499, see comment there.

**Comment by jamesbascle** [comment]
I think this is a good simple change.

**Comment by jamesbascle** [comment]
@JoshClose Are you still on board with making a fluent interface for property maps using the same concept as my fluent class map builder from https://github.com/JoshClose/CsvHelper/pull/587 ?

If so, it would do the same thing as this.

**Comment by JoshClose** [comment]
Probably. :)

**Comment by JoshClose** [comment]
Everyone, check this out and let me know what you think. You now get compile time type checking on the mappings. `CsvClassMap.Map` is now internal, but there is a static method to create a `CsvPropertyMap<T>` instead: `CsvPropertyMap.CreateGeneric( MemberInfo member )`

https://github.com/JoshClose/CsvHelper/commit/1f7d1bd6b347286eb0c4e5eac92c89be8ae39371

**Comment by JoshClose** [comment]
Actually, the map method should be back to public now. That was the whole reason behind doing the create generic method. ;)

**Comment by JoshClose** [comment]
I pushed this in main now.
