### ISSUE TITLE
How can i read a large file using csvhelper

### ISSUE THREAD

**Issue by laliyas** [JoshClose/CsvHelper#690]
Hi, 
I am trying to read a huge csv file and getting out of memory exception
```
var csvreader = new StreamReader(@"C:\testfile\Prod\PCST1705.TAB");
var csvconfig = new CsvConfiguration();
csvconfig.Delimiter = "\t";
 csvconfig.HasHeaderRecord = false;
 var csv = new CsvReader(csvreader, csvconfig);
 while (csv.Read())
            {
                var address = new Master();
                address.ID = int.Parse(csv.GetField(0));
                 address.PostCode = csv.GetField(1);
        }
```

Please assist

I have tried to use mapping way too
```
 public sealed class MyClassMap : CsvClassMap<Master>
    {
        public MyClassMap()
        {
            Map(m => m.PostCode).Index(0);
            Map(m => m.Line1).Index(0);
                   }
    }

IEnumerable<Master> records = csv.GetRecords<Master>();
foreach (Master item in records)
            {
                var address = new Master();
                address.PostCodeID = int.Parse(csv.GetField(0));
----------------------
}
```

but again getting the error in foreach (Master item in records)

An unhandled exception of type 'CsvHelper.TypeConversion.CsvTypeConverterException' occurred in CsvHelper.dll

Additional information: The conversion cannot be performed.

**Comment by laliyas** [comment]
I got the above to be working. Seems i missed the registry.
I am trying to read a huge csv - 615 MB and it is always failing with out of memory
Is there any way i could do that ??

**Comment by laliyas** [comment]
total records would be 29 million rows

**Comment by jamesbascle** [comment]
Make sure you're running in x64 mode, and you have the <gcAllowVeryLargeObjects enabled="true" /> set in your  app.config.

Alternatively, you can do your work in the read loop as you're reading.

Also, be sure to use using blocks as follows:
```
var csvconfig = new CsvConfiguration{
Delimiter = "\t",
HasHeaderRecord = false
};
using(var csvreader = new StreamReader(@"C:\testfile\Prod\PCST1705.TAB"))
using(var csv = new CsvReader(csvreader, csvconfig))
{
    while (csv.Read())
    {
        var address = new Master();
        address.ID = int.Parse(csv.GetField(0));
        address.PostCode = csv.GetField(1);
    }
}```

so that the allocated resources are freed after use.

**Comment by laliyas** [comment]
I am still getting out of memory exception at record 14130409

**Comment by jamesbascle** [comment]
To be clear, this has nothing to do with CsvHelper, and everything to do
with your machine and environment.

Investigate the ways to ease or expand memory usage, and get a profiler.

**Comment by laliyas** [comment]
Thanks James. I forgot your comments"Make sure you're running in x64 mode"
It worked oince i have done that.
Yeah it had nothing to do with cvhelper. 
Thanks again for ur help

**Comment by jamesbascle** [comment]
No problem.

**Comment by JoshClose** [comment]
You should be able to stream the data and not take up any memory too. Maybe you have the situation where you need to pull all records into memory to do some work though, I don't know.

Also, you can do `csv.GetField<int>( 0 )` and it will return an `int` for you. All the type conversions are built in.

**Comment by DavidDeSloovere** [comment]
Hey @JoshClose, when you say "stream the data", do you mean reading record by record using `GetRecord `instead of reading the whole file using `GetRecords`? When reading a very large file, my idea right now is to read like 100k lines using GetRecord, validate and saving those to the database and then reading the next 100k (or until EOF) and so on.

**Comment by JoshClose** [comment]
`GetRecords` returns an `IEnumerable<T>` that will `yield` records. This means that if you don't do any set operations with LINQ or a `ToList` or something, you're able to iterate over the records and it will only have a single record in memory at once time.

**Comment by DavidDeSloovere** [comment]
That's awesome. Thanks for the answer and even more thanks for the library!

**Comment by djStolen** [comment]
Hi guys,

I have, what appears to be, a same problem. Just my file is much smaller. My file is 7.5MB.
It looks like this:

```
ChannelName;Timestamp;ScaledValue
Channel_1;638404102934852000;71,95900431
Channel_2;638404102935042000;90,84624168
Channel_3;638404102935192000;98,97225229
Channel_1;638404102935822000;36,13739891
Channel_2;638404102935972000;59,93655136
Channel_3;638404102936132000;57,59677992
Channel_1;638404102936612000;96,28719697
Channel_2;638404102936772000;54,85207809
Channel_3;638404102936932000;0,212733122
Channel_1;638404102937402000;62,99430223
Channel_2;638404102937552000;64,79355901
Channel_3;638404102937702000;22,70342643
Channel_1;638404102938172000;97,19814183
Channel_2;638404102938323000;15,34089661
Channel_3;638404102938472000;8,606882118
Channel_1;638404102938942000;18,67551711
Channel_2;638404102939102000;70,90478384
Channel_3;638404102939253000;89,00143145
Channel_1;638404102939733000;6,912768589
Channel_2;638404102939883000;63,88499092
Channel_3;638404102940032000;95,32662034
Channel_1;638404102940503000;37,06507843
Channel_2;638404102940663000;58,35199014
Channel_3;638404102940823000;53,0795533
Channel_1;638404102941353000;75,08313664
Channel_2;638404102941523000;8,4127049
Channel_3;638404102941673000;20,29174637
Channel_1;638404102942073000;8,592699426
Channel_2;638404102942223000;9,758784301
Channel_3;638404102942373000;46,82764702
Channel_1;638404102942823000;22,2687997
Channel_2;638404102942983000;68,4256147
Channel_3;638404102943143000;43,17649991
Channel_1;638404102943623000;27,86021625
Channel_2;638404102943783000;6,45445362
Channel_3;638404102943943000;90,68501438
Channel_1;638404102944563000;86,43376291
```
If I shorten the file to e.g. couple hundred lines, my import works.
With the 7.5MB it does not and gives:

``Field with name 'ChannelName' does not exist. You can ignore missing fields by setting MissingFieldFound to null.
IReader state:
   ColumnCount: 0
   CurrentIndex: -1
   HeaderRecord:
["C``

My import function looks like this:

```
public static List<SingleSnapshotImport> ImportCSV(string filePathAndName = @"test.csv")
{
    List<SingleSnapshotImport> fileContent;
    var config = new CsvConfiguration(CultureInfo.GetCultureInfo("de-DE"))
    {
        Delimiter = ";",
        Encoding = Encoding.UTF8,
        //HasHeaderRecord = true,
        //MissingFieldFound = null,
    };

    using (var reader = new StreamReader(filePathAndName))
    using (var csv = new CsvReader(reader, config))
    {
        csv.Read();
        csv.ReadHeader();
        var records = csv.GetRecords<SingleSnapshotImport>();
        fileContent = records.ToList();
    }
    return fileContent;
}
```

What is wrong here, so it wont read the 7.5MB file?
[test.csv](https://github.com/JoshClose/CsvHelper/files/13938731/test.csv)

**Comment by JoshClose** [comment]
@djStolen

I opened this file in VSCode and it says it's `UTF-16 LE`. `UTF-16` and `UTF-16LE` both seem to work. You need to specify the encoding in the `StreamReader`.

```cs
using (var reader = new StreamReader(stream, Encoding.GetEncoding("UTF-16LE")))
```

The encoding in the settings is only used when you're counting bytes, which you haven't turned on.
