### ISSUE TITLE
BadDataCallback should give more details

### ISSUE THREAD

**Issue by StefanBertels** [JoshClose/CsvHelper#692]
Currently BadDataCallback just gives the content of the bad field value.
WillThrowOnMissingField will cause an exception with same information (something like "Field: BADVALUE").

Would be great if one could get more information. Maybe have more arguments for the callback or a rich object with properties:

- raw field value
- **line number**
- raw line
- field name
- **column number**
- reason why this is bad (error message like "could not be converted", "unquoted separators", "unquoted quote"...)

I guess some of this information is not available (always) and is not directly accessible at the code line where the callback/exception is thrown. So this is just a suggestion because I think it would be helpful to have more information, e.g. for logging.

There is another (small) related issue: When reading files with bad data in some field the callback/error occurs regardless whether the column is actually mapped. This makes sense in some way because you might not know whether this error is in fact a problem with mapped columns (think about a partly unquoted column separator which might result in columen mismatch or similar problems) or you just want to verify whether the complete CSV file has a valid format overall. But a bad field value in an unused column maybe does not matter.

Otherwise: From what I've seen BadDataCallback is only used on the raw parser level (before mapping, independent of column names etc.) Is this your design choice (so rich errors occuring in mapping/casting never will result in BadDataCallback)? Might make sense, too.

My personal case was an unquoted quote character in a raw field (probably IgnoreQuotes = true is the correct solution here -- together with #688).

**Comment by StefanBertels** [comment]
A comment to add some real world use case.

My current workaround for ignoring bad data in non-relevant lines is like this:

config:
```
BadDataCallback = s => { badData = true; }
```

read loop:
```
while (true)
{
    row++;
    badData = false;
    if (!cr.Read()) break; // EOF

    var record = cr.GetRecord<MyType>();

    if(!filterPredicate(record)) continue; // skip record if not relevant

    if(badData) throw Exception($"bad data in line {row}");

    // process relevant data here
}
```

Of course there is a problem if bad data would cause the filterPredicate to be buggy.
My use case would allow to filter on raw data, too. So if BadDataCallback had more data
I would put "throw" into the callback (conditional).

**Comment by JoshClose** [comment]
The issue here is the work happens in `FieldReader`. `CsvReader -> CsvParser -> FieldReader`

I need to somehow detect in `CsvReader` that this happened.

**Comment by JoshClose** [comment]
FYI: For your `filterPredicate`, there is `Func<string[], bool> Configuration.ShouldSkipRecord` that passes in the current record and you return a boolean saying if you want it to be skipped.

**Comment by JoshClose** [comment]
So I did some major architecture changes for this to work. (thanks to @jamesbascle for the idea) There is now a `ReadingContext` and `WritingContext` that holds all the state data. That object is passed to all the reading/writing objects. This will allow for the `FieldReader` to have access to all the data only used in `CsvReader` and anywhere an exception happens, the state of the application can be given or dumped.

I'll have a change done soon. (within a day or two)

**Comment by JoshClose** [comment]
The base `CsvHelperException` object now has a `ReadingContext` and `WritingContext` property on it where all the state information is.

Let me know if there anything else missing.

**Comment by JoshClose** [comment]
Also, I changed `BadDataCallback` from `Action<string>` to `Action<ReadingContext>`.

**Comment by StefanBertels** [comment]
Thank you for implementing this!
