### ISSUE TITLE
Option: always quote only string fields

### ISSUE THREAD

**Issue by hellboy81** [JoshClose/CsvHelper#693]
Is there possible to quote only string fields? numeric fields should not be quoted.

**Comment by JoshClose** [comment]
No. You'd have to do some sort of configuration combination to get that to work. If you want only strings, you could do `Configuration.QuoteNoFields = true`, the specifically quote all string fields using a custom `StringConverter` or if the property amount is small, you could use `ConvertUsing` on the specific fields.
