### ISSUE TITLE
Exceptions should be Serializable

### ISSUE THREAD

**Issue by jamesbascle** [JoshClose/CsvHelper#694]
This one isn't https://github.com/JoshClose/CsvHelper/blob/b74a2f95a101158f4cdedd25fae6e8392b58855b/src/CsvHelper/CsvMissingFieldException.cs

There may be more.

**Comment by JoshClose** [comment]
It's not a part of .NET Core. Why do you need it? It's only used for binary serialization.

**Comment by JoshClose** [comment]
Btw, from what I can tell, the current recommendation is to leave it up to the consumer to figure out serialization if they need `[Serializable]`.

**Comment by jamesbascle** [comment]
I see. I use CsvHelper inside of an app domain for Azure Datafactory.  Due
to certain constraints in the framework, the jobs ("activities") tend to
need to new up an app domain and do the work inside of that.  When an
exception is thrown, it needs to bubble up to the DF framework in the
parent app domain.  It then says that whichever CsvHelper exception
occurred is not serializable, and thus it does not display any useful
information about the actual exception in the monitoring tool.

How would I supply app domain serialization outside of the binary itself?
Is that possible?

**Comment by JoshClose** [comment]
Might be a good question for the core team. I've asked them several questions lately and they've been very responsive.

**Comment by JoshClose** [comment]
Can you catch the exception and throw a new one with the contents of the csv exception?

**Comment by jamesbascle** [comment]
Maybe?  The general strategy is just to let anything bubble up and have dev/ops/support diagnose and come up with a fix the rerun the job.

If the recommended strategy from core is to always wrap and take apart your exceptions when working with app domains and custom exceptions, I'd be surprised (and disappointed).  It's a lot of pointless code.

How would I ask them, exactly?

**Comment by JoshClose** [comment]
Find the appropriate project here https://github.com/dotnet/core and submit an issue. I'm thinking dotnet/standard is probably the place to ask.

**Comment by jamesbascle** [comment]
@JoshClose Per response from the .NET Standard team:

> With .NET Standard 2.0 (currently in preview) the serialization attributes are included so you should be able to write custom exceptions with the correct serialization annotations.

Thoughts.

**Comment by JoshClose** [comment]
I think I need to update to `netstandard2.0`. https://github.com/dotnet/standard/blob/master/docs/versions.md

I'll look into what needs to be done.

**Comment by JoshClose** [comment]
This is interesting https://gist.github.com/davidfowl/8939f305567e1755412d6dc0b8baf1b7

**Comment by jamesbascle** [comment]
Hm.  I think that would leave people on old versions of .NET out in the cold...Maybe could do a 2.0 build with preprocessor statements around the serializable attributes?  I'm not quite sure how all that works with this .NET Standard stuff.

**Comment by JoshClose** [comment]
I've already left them out in the cold. I haven't had anyone complain yet. I can always create a .NET 4.0 build if it ends up being a problem. I figure people on old versions of .NET can use CsvHelper 2.x. I don't want to put in `#if`s if possible. netstandard1.3 and 2.0 have the same reach for the most part.

I think I'm going to wait until the RTM to upgrade. NCrunch doesn't work in the preview which means unit testing will be a pain.

**Comment by JoshClose** [comment]
I'm making this blocked pending the release of .NET Core 2.0.

**Comment by jamesbascle** [comment]
Do you mean .net standard 2? or?

**Comment by JoshClose** [comment]
.NET Core as a generic term meaning .NET Core and .NET Standard, since they come together. .NET Core is for apps and .NET Standard is for libraries.

![image](https://user-images.githubusercontent.com/114971/26990182-622d81f2-4d1b-11e7-9e77-14bc5bfbae3e.png)

![image](https://user-images.githubusercontent.com/114971/26990170-53edf54a-4d1b-11e7-85d2-3a23784d307d.png)

**Comment by jamesbascle** [comment]
Gotcha.

**Comment by JoshClose** [comment]
There also is a command line install and the tooling that comes with visual studio and you have to install them separately.

**Comment by JoshClose** [comment]
NCrunch hasn't updated to work with 2.0 yet. I'm hoping that happens soon because running unit tests without that is a major pain. I'm hesitant to update before NCrunch is fixed.

**Comment by JoshClose** [comment]
7771a658cfb94604bbe3bc44e93268f15e654c29
