### ISSUE TITLE
WriteRecord<>() : Choosing the format when writing a Date? 

### ISSUE THREAD

**Issue by chadbruels** [JoshClose/CsvHelper#697]
How can one write a date field to a csv file and choose the format written when using the WriteRecord<>() method?

**Comment by jamesbascle** [comment]
In your ClassMap use Map(m=>m.Prop1).TypeConverterOptions.Format("o"); for
ISO, or another string for others.

**Comment by chadbruels** [comment]
https://www.screencast.com/t/NQ1JZInv 

"CsvPropertyMap does not contain a definition for TypeConverterOptions", so I fell back on attempting to use TypeConverterOption("yyyy-MM-dd"). You can see this did not work if you follow the link above. Please advise - and thank you for quickly responding today. I'm pleasantly surprised to hear from you so quickly.

**Comment by JoshClose** [comment]
Here is an example.
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Id = 1, Name = "one", Date = DateTimeOffset.Now },
			new Test { Id = 2, Name = "two", Date = DateTimeOffset.Now },
		};
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);
		
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public DateTimeOffset Date { get; set; }
}

public sealed class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.Date).TypeConverterOption("o");
	}
}
```

**Comment by chadbruels** [comment]
How do you write a DateTime in the format yyyy-MM-dd?

**Comment by jamesbascle** [comment]
Just replace "o" with "yyyy-MM-dd" or whatever your preferred format is

**Comment by JoshClose** [comment]
Changing to
```cs
Map(m => m.Date).TypeConverterOption("yyyy-MM-dd");
```
Outputs:
```
Id,Name,Date
1,one,2017-06-14
2,two,2017-06-14
```

**Comment by chadbruels** [comment]
https://www.screencast.com/t/NQ1JZInv >> I did just that - only difference was including .Index().

**Comment by jamesbascle** [comment]
Are your u registering the ClassMap with your CsvConfiguration?

**Comment by JoshClose** [comment]
Can you post a failing example?

**Comment by chadbruels** [comment]
Ahh, I had registered the class map where I was reading the original CSV but I had not done so when I was writing data to a new CSV. It is working for me. Thank you.

**Comment by DiskJunky** [comment]
The code `Map(m => m.Date).TypeConverterOption("o")` no longer works as of v12.1.2. `TypeConverterOptions` is a property, not a method and cannot be invoked as this thread applies.

**Comment by klym1** [comment]
Is there a way to specify format for all properties of a certain type? E.g. I want all DateTimes in all DTOs to have format "yyyy-MM-dd" and don't want to specify each property individually.

**Comment by AltruCoder** [comment]
@klym1 You can set the `TypeConverterOptionsCache`.
```cshapr
using (var writer = new StreamWriter("path\\to\\file.csv"))
using (var csv = new CsvWriter(writer))
{
    csv.Configuration.TypeConverterOptionsCache.GetOptions<DateTime>().Formats = new []{"yyyy-MM-dd"};
    csv.WriteRecords(records);
}
```

**Comment by klym1** [comment]
Wow, that's awesome, thanks for the help @AltruCoder

**Comment by nikita-starostin** [comment]
> @klym1 You can set the `TypeConverterOptionsCache`.
> 
> ```
> using (var writer = new StreamWriter("path\\to\\file.csv"))
> using (var csv = new CsvWriter(writer))
> {
>     csv.Configuration.TypeConverterOptionsCache.GetOptions<DateTime>().Formats = new []{"yyyy-MM-dd"};
>     csv.WriteRecords(records);
> }
> ```

If you have `DateTime?` in the model, then this would be working for `ReadRecords`, but for `WriteRecords` have to use `<DateTime?>`

```
            // read, in model all the fields are DateTime?
            csvReader.Configuration.TypeConverterOptionsCache.GetOptions<DateTime>().Formats =
                new[] { DateTimeConstants.ClientDateFormat };
            var records = csvReader.GetRecords<CsvPropertiesImportItemPropertyFields>();
```

```
            // write, in model all the fields are DateTime?
            csvWriter.Configuration.TypeConverterOptionsCache.GetOptions<DateTime?>().Formats =
                new[] { DateTimeConstants.ClientDateFormat };
            csvWriter.WriteRecords(new[] { csvPropertyImportItemPropertyFields });

```

**Comment by andreasblueher** [comment]
This isn't current state of the solution anymore, check this issue to see how it's done in current version

#1645
