### ISSUE TITLE
Write Date Format : Solution did not work

### ISSUE THREAD

**Issue by chadbruels** [JoshClose/CsvHelper#702]
My last issue was closed before I confirmed it was working and there has not been a response to the comment I left there. I need to control how a date writes to the CSV file. The proposed solution was: 

In your ClassMap use Map(m=>m.Prop1).TypeConverterOptions.Format("o"); for
ISO, or another string for others.

My response to that suggestion and continued difficulty follows. 

https://www.screencast.com/t/NQ1JZInv

"CsvPropertyMap does not contain a definition for TypeConverterOptions", so I fell back on attempting to use TypeConverterOption("yyyy-MM-dd"). You can see this did not work if you follow the link above.

**Comment by JoshClose** [comment]
Sorry, just been busy. I'll comment on the other thread.
