### ISSUE TITLE
Reading/Writing to multiple sheets/a specific sheeet

### ISSUE THREAD

**Issue by sharathsridhar** [JoshClose/CsvHelper#704]
Hello,

Is it possible to read multiple sheets from an .xlsx or a .csv and load them to separate datatables ? Assuming there is a Sheet1 and Sheet2 in the csv/excel file, can I read both or a particular one ?

An extension of the same question - Can we write data from a datatable to a particular sheet of an already existing csv file? An example - Sheet 1 may have fancy formatting, pivot tables, cell merges etc and will have formulas pointing to data in sheet 2. Can we read the metadata of this file and write only to sheet 2 ?

Thank You.

**Comment by JoshClose** [comment]
A CSV file and Excel file are not the same thing. Excel has the functionality of exporting to a CSV file, and is able to open a CSV file and manipulate it, but they're not the same at all.

CsvHelper doesn't read xlsx files, so reading multiple sheets isn't possible either. 

CSV files don't have sheets, formulas or pivot tables. It's literally Comma Separated Values. This is the format of a CSV file. https://tools.ietf.org/html/rfc4180

You'll need to find an Excel library to do the things you're looking to do.

**Comment by jamesbascle** [comment]
If you have money, Aspose.net is great. If not, NPOI, among others, is
decent.
