### ISSUE TITLE
why would this date throw System.FormatException:

### ISSUE THREAD

**Issue by ChangePlaces** [JoshClose/CsvHelper#705]
I have this date string as a value for a DateTimeOffset field:

`5/27/2017 11:59:05 PM +00:00`

It's throwing `System.FormatException: 'String was not recognized as a valid DateTime.'` - should it?

**Comment by JoshClose** [comment]
What does your mapping look like?

**Comment by ChangePlaces** [comment]
For the created field, I'm using automap

**Comment by JoshClose** [comment]
This works for me in both 2.x and 3.x. Would you be able to give me a failing example?

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name,DT");
		writer.WriteLine("1,one,5/27/2017 11:59:05 PM +00:00");
		writer.Flush();
		stream.Position = 0;
		
		csv.GetRecords<Test>().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public DateTimeOffset DT { get; set; }
}
```

**Comment by ChangePlaces** [comment]
No such method as `.Dump()`? So I subsituted the `.GetRecords` line with:

                var records = csv.GetRecords<Test>();
                var d = records.First().DT;

and I get `System.FormatException: 'String was not recognized as a valid DateTime.'`

**Comment by JoshClose** [comment]
`Dump` is a method on [LinqPad](https://www.linqpad.net/) to automatically dump the contents of an object.

**Comment by JoshClose** [comment]
I changed to this

```cs
var records = csv.GetRecords<Test>();
Console.WriteLine( records.First().DT );
```
and I'm not getting an error. What version of .NET are you using? What version of CsvHelper are you using?

**Comment by ChangePlaces** [comment]
I think because your culture is set to use a 12 hour clock. Being British, I'm using 24 hours, and that's why it's throwing for me, and not for you.

The docs state: "Because the DateTime.TryParse(String, DateTime) method tries to parse the string representation of a date and time using the formatting rules of the current culture, trying to parse a particular string across different cultures can either fail or return different results. If a specific date and time format will be parsed across different locales, use the DateTime.TryParse(String, IFormatProvider, DateTimeStyles, DateTime) method or one of the overloads of the TryParseExact method and provide a format specifier."

So, I manually convert it in the mapper with something like: 

            DateTime result = new DateTime();
            Map(m => m.Created).ConvertUsing(
                row =>
                {
                    DateTime.TryParse(row.GetField<string>(14), System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.AdjustToUniversal, out result);
                    return result;
                });

I think this means it's a non-issue?

**Comment by JoshClose** [comment]
I could reproduce after setting the thread culture to `en-GB`.

You can set options without having to use `ConvertUsing`.
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		Thread.CurrentThread.CurrentCulture = new CultureInfo("en-GB");
		writer.WriteLine("Id,Name,DT");
		writer.WriteLine("1,one,5/27/2017 11:59:05 PM +00:00");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestMap>();
		var records = csv.GetRecords<Test>();
		Console.WriteLine( records.First().DT );
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public DateTimeOffset DT { get; set; }
}

public sealed class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.DT)
			.TypeConverterOption(CultureInfo.InvariantCulture)
			.TypeConverterOption(DateTimeStyles.AdjustToUniversal);
	}
}
```
The converter does this by default:
```cs
var formatProvider = (IFormatProvider)propertyMapData.TypeConverterOptions.CultureInfo.GetFormat( typeof( DateTimeFormatInfo ) ) ?? propertyMapData.TypeConverterOptions.CultureInfo;
var dateTimeStyle = propertyMapData.TypeConverterOptions.DateTimeStyle ?? DateTimeStyles.None;

return string.IsNullOrEmpty( propertyMapData.TypeConverterOptions.Format )
	? DateTimeOffset.Parse( text, formatProvider, dateTimeStyle )
	: DateTimeOffset.ParseExact( text, propertyMapData.TypeConverterOptions.Format, formatProvider, dateTimeStyle );
```
Do you think there is a different way that would work better for other cultures that could be used by default?

**Comment by ChangePlaces** [comment]
Oh nice, thanks - that's certainly nicer than what I have!

As for other cultures I think it's best to leave it as it currently is. It's how C# manages cultures by default and I don't think you want to mess with DateTime's by converting them to universal without the user explicitly setting it to do so.
