### ISSUE TITLE
IgnorePrivateAccessor = false doesn't work but true does!

### ISSUE THREAD

**Issue by kabua** [JoshClose/CsvHelper#707]
The logic for ```IgnorePrivateAccessor``` is backward!

The following code doesn't work:
```
            using (var reader = new CsvHelper.CsvReader(new StreamReader(fullFileName)))
            {
                reader.Configuration.HasHeaderRecord = true;
                reader.Configuration.IgnorePrivateAccessor = false;

                return reader.GetRecords<Sample>().ToList();
            }

    public class Sample
    {
        public Sample(int id, DateTime startDateTime, DateTime endDateTime)
        {
            Id = id;
            StartDateTime = startDateTime;
            EndDateTime = endDateTime;
        }

        protected Sample()
        {
        }

        public int Id { get; private set; }
        public DateTime StartDateTime { get; private set; }
        public DateTime EndDateTime { get; private set; }
    }
```
We get the following exception:
```CsvHelper.CsvReaderException: 'No properties are mapped for type 'Testing.Sample'.'```

However, if we change the ```IgnorePrivateAccessor = false``` to ```IgnorePrivateAccessor = true``` it works! Therefore, you ```IgnorePrivateAccessor``` logic is backwards.

**Comment by JoshClose** [comment]
It's not backwards, but the naming is confusing. In the 3.0 pre-release, it's been renamed to `IncludePrivateMembers`, which makes more sense.
