### ISSUE TITLE
IgnorePrivateAccessor doesn't work period for derived types.

### ISSUE THREAD

**Issue by kabua** [JoshClose/CsvHelper#708]
The following code doesn't work:
```
            using (var reader = new CsvHelper.CsvReader(new StreamReader(fullFileName)))
            {
                reader.Configuration.HasHeaderRecord = true;
                reader.Configuration.IgnorePrivateAccessor = true;  // or false doesn't matter

                return reader.GetRecords<Sample2>().ToList();
            }

    public class Sample
    {
        public Sample(int id, DateTime startDateTime, DateTime endDateTime)
        {
            Id = id;
            StartDateTime = startDateTime;
            EndDateTime = endDateTime;
        }

        protected Sample()
        {
        }

        public int Id { get; private set; }
        public DateTime StartDateTime { get; private set; }
        public DateTime EndDateTime { get; private set; }
    }

    public class Sample2 : Sample
    {
    }
```

The only way to get it work is to make all the properties setters public (note protected doesn't work either). However, we don't want these properties setters public that's why we want them marked as private.

**Comment by JoshClose** [comment]
Interesting. Good find.

**Comment by jamesbascle** [comment]
I actually encountered another issue in writing a test to ensure all
properties are mapped on my entities in my ClassMaps that stems from the
same root issue.

The issue is that a particular MemberInfo is not a singleton for a class
hierarchy, it is only a singleton for each class where it is accessible
from.  So if a private method (which is what a private setter is compiled
to) makes its way into a child class, it is undetectable.  To detect it,
you'll have to access the BaseClass property of the Type/TypeInfo.

**Comment by kabua** [comment]
Glad I could help. Overall I like your CsvHelper component (very handy).

**Comment by JoshClose** [comment]
You're also going to have an issue with that `protected` constructor.

**Comment by JoshClose** [comment]
Fixed 603dc8acdcdb170cf24e7c20a893bec69194196a

**Comment by sigorbor** [comment]
Similar issue is there for writing. I have

public interface ITick
    {
        DateTimeOffset DateTime { get; }
    }

public interface ICandle: ITick
    {
        decimal Open { get; set; }
        decimal High { get; set; }
        decimal Low { get; set; }
        decimal Close { get; set; }
        decimal Volume { get; set; }
    }

I write the list of ICandle objects, the base DateTime property is not written.

**Comment by JoshClose** [comment]
Can you give a full example in a new issue?
