### ISSUE TITLE
Getting "CsvConfigurationException: Types that inherit IEnumerable cannot be auto mapped" when exporting list of ExpandoObjects

### ISSUE THREAD

**Issue by NikolayIT** [JoshClose/CsvHelper#709]
I have this object:
    
    var exportData = new List<ExpandoObject>();

And this code for saving CSV to memory:

    private byte[] WriteCsvToMemory<T>(IEnumerable<T> records)
    {
        using (var memoryStream = new MemoryStream())
        using (var streamWriter = new StreamWriter(memoryStream))
        using (var csvWriter = new CsvWriter(streamWriter, new CsvConfiguration { HasHeaderRecord = true,  }))
        {
            csvWriter.WriteRecords(records);
            streamWriter.Flush();
            return memoryStream.ToArray();
        }
    }

Calling it with 

    var result = this.WriteCsvToMemory(exportData);
    var memoryStream = new MemoryStream(result);

Gives me the following exception:

```CsvConfigurationException: Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?```

**Comment by jamesbascle** [comment]
What is T?  I suspect T is an  IEnumerable<U>.  This does not work with automapping.

If this is not the case, please provide a full code sample with an actual type for your T.

**Comment by osamamourad** [comment]
I have the same issue, T is dynamic ExpandoObject

**Comment by JoshClose** [comment]
This will not work in 2.x. 3.0 (pre-release) has support for this. 

There is one weird issue though. It works with `IEnumerable<dynamic>` but gets that same exception for `IEnumerable<ExpandoObject>`. I believe this is because it's only doing special logic when it's a dynamic type. Otherwise `ExpandoObject` is treated just like any other object, which wouldn't work well.

**Comment by anphonic** [comment]
I recently updated to the 3.0 pre-release to try to take advantage of the automapping but it's still failing on an enumberable list from a class. I've created a classmap for it to try overcome this but it's still throwing the error that it can't automap it. The map exactly mirrors the class.  Is still still an issue with the mapping of IEnumerables?

Shared.Shared.HmsAdjustments is of List<HmsAdjustments>. All elements of the class are public.
`CsvConfiguration csvConfig = new CsvConfiguration
{
//IgnorePrivateAccessor = true, //Must set class items to public :/
HasHeaderRecord = true
};

using (CsvWriter writeCsv = new CsvWriter(new StreamWriter($@"Path{DateTime.Today:yyyy-MM-dd}-{importFileName}-dupes.csv", true), csvConfig))
{
writeCsv.WriteRecords(Shared.Shared.HmsAdjustments);
}
///


/// Map class for CsvHelper HmsAdjustments
///

/// 
public sealed class HmsAdmustmentsMap : CsvClassMap
{
public void HmsAdjustmentsMap()
{
Map(m => m.RecId);
Map(m => m.PatNo);
Map(m => m.SeqNum);
Map(m => m.Cycle);
Map(m => m.Tcode);
Map(m => m.Tamt);
Map(m => m.GlNum);
Map(m => m.Ptype);
Map(m => m.Inscop);
Map(m => m.ArBuc);
Map(m => m.Batch);
Map(m => m.ArRef);
Map(m => m.AcctPr);
Map(m => m.CCode);
Map(m => m.OptDsc);
Map(m => m.OptKey);
Map(m => m.Hsv);
Map(m => m.AppTyp);
Map(m => m.IsOtrDate);
Map(m => m.IsOoDate);
Map(m => m.IsOmtendd);
Map(m => m.NwFinCl);
Map(m => m.TcodeAdj);
            }
        }`

**Comment by JoshClose** [comment]
Are you writing a single class instance to `WriteRecords`? That method is expecting an `Enumerable`.

**Comment by anphonic** [comment]
Yes in the example above, it's an IEnumerable List<> of HmsAdjustment objects.

 I've since abandoned it and just used StreamWriter and PropertyInfo but it's possible though that I had the class variables as internal rather than public.  I found this was an issue when I was later trying to get the properties from two classes where one was public and the internal was failing to work.  I'm too far into the process now to go back and retest with CSVHelper but I'll keep the internal/public in mind. I knew private variables would cause issues but it never occurred to me that internal might.

**Comment by JoshClose** [comment]
Can you create a full small example that recreates the problem and post it here?

**Comment by Aznariy** [comment]
same problem on my side. **csv.WriteRecords** method fails to write **List<string>** to the .csv file. I'm using CsvHelper library v7.1.0

**Comment by JoshClose** [comment]
You're getting that because you're trying to write a `string` as a record. A `string` is a single field. If you want to write a single field on each row, you can do this instead.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		var values = new List<string> { "one", "two", "three" };
		foreach (var value in values) 
		{
			csv.WriteField(value);
			csv.NextRecord();
		}
		
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}
```
