### ISSUE TITLE
Version 3.0

### ISSUE THREAD

**Issue by Skoucail** [JoshClose/CsvHelper#711]
I've been using the 3.0 version for some time now and it looks very stable. And i love the project btw.
But its sometimes a pain to use CsvHelper in projects distributed with nuget as the 3.0 version is still pre-release.
So i'm wondering when version 3.0 be released?

**Comment by JoshClose** [comment]
I'm really hoping soon. I need to get all breaking changes done first. Being that so many things are interfaces, things can break pretty easily. I've pretty much spending all my free time working on getting this finished. The feature list is getting pretty small now though. https://github.com/JoshClose/CsvHelper/issues?q=is%3Aopen+is%3Aissue+label%3Afeature

The only other thing is updated documentation. That will take a while, so I may release before the documentation is complete. I would say in the next month or 2 it will be out. I also this this last September, but had many breaking changes features come in. Maybe I should just release faster and version more.

**Comment by Skoucail** [comment]
Yea very nice work and for sure i don't want to rush you :)
Its just annoying that nuget doesn't allow to use pre-release packages as dependency in stable packages.
(They there is a fix coming for this in nuget 4, but yea not yet)

**Comment by JoshClose** [comment]
I kind of want netstandard2.0 to be released first so I can release with a dependency on that instead of netstandard1.3.
