### ISSUE TITLE
Writing records results in incomplete data

### ISSUE THREAD

**Issue by devoncustard** [JoshClose/CsvHelper#714]
Data appears to be read in fine, however writing data results in an incomplete file
Read from csv using class and a Registered map.
Write the data to new CSV file using csvwriter. Incomplete file. No exception just didnt complete.

For instance....

EU (Ireland),OnDemand,c3.4xlarge,Windows,Shared,1.5040000000,NA
EU (Ireland),OnDemand,cc2.8xlarge,Linux,Shared,2.2500000000,NA
EU (Irel
Always fails at same point, removing one of the fields from the class moved the point it failed at so assume its a buffer sizing issue?

**Comment by JoshClose** [comment]
Are you flushing the writer after you're done writing?

**Comment by devoncustard** [comment]
Yup that did it. Appreciate the fast response. Class works wonders, just what i need.

Can i humbly suggest you add that titbit to the docs. I openly admit i should have spotted that ( i dont play with streams that much) but it would save eeediots like me a lot of time.

**Comment by JoshClose** [comment]
Yes, I should put something in the docs about this. It's not CsvHelper specific, but it's something a lot of people run into.
