### ISSUE TITLE
File that does not look like csv does not generate exception

### ISSUE THREAD

**Issue by mabead** [JoshClose/CsvHelper#715]
I use the csv helper with the following code:
```
            using (var csvReader = new CsvReader(textReader))
            {
                csvReader.Configuration.CultureInfo = CultureInfo.InvariantCulture;
                csvReader.Configuration.SkipEmptyRecords = true;
                csvReader.Configuration.DetectColumnCountChanges = true;
                csvReader.Configuration.Delimiter = "	"; // tab
                csvReader.Configuration.IsHeaderCaseSensitive = false;
                csvReader.Configuration.IgnoreBlankLines = true;
                csvReader.Configuration.RegisterClassMap<MyMap>();
                csvReader.Configuration.TrimHeaders = true;
                csvReader.Configuration.TrimFields = true;

                return new List<MyRow>(csvReader.GetRecords<MyRow>());
            }
```
Where MyRow & MyMap define a CSV with two columns (A and B).

When I load a file that only contains the following text:
```
*
```
I would expect the CsvReader to throw an exception because it doesn't have the expected number of columns and it doesn't have the header. 

What should I do to have the CsvReader to throw an exception when parsing this file?

**Comment by JoshClose** [comment]
That's a valid CSV file, so there isn't much the library can do about it. You can inspect the beginning of the file to look for what you consider to be a valid CSV file in your environment before running it through CsvHelper.

**Comment by mabead** [comment]
Sorry but then I don't understand what is a valid file. If I parse, the following file:
```
B
1
2
```
(so a file that is missing the `A` column), then I get the following exception:
```
CsvHelper.CsvMissingFieldException: 'Fields 'A' do not exist in the CSV file.'
```
So my understanding is that when one of the column is missing, it throws an exception. So, in the file that only contains a `*`, I don't have either the `A` or `B` column, so I would expect a similar exception to be thrown.

Could you please explain why it is a valid file if it does not include a header that contains the required columns?

There is probably something that I am missing...

**Comment by JoshClose** [comment]
That exception is only thrown when reading records. Since there is only 1 row, the header, the header gets read, and no record rows get read, so that exception never has a chance to be thrown. This exception is based off the `WillThrowOnMissingField` config option. Technically there were no fields, so that exception can't be thrown.

**Comment by mabead** [comment]
Ok got it. The validations about the columns of the csv only start when reading records. The validations are not done when reading the header.

Thanks for your support and the great library!

**Comment by jamesbascle** [comment]
@joshclose just caught up in this thread.  Is there any header validation
before reading records? Should there be?

**Comment by JoshClose** [comment]
There is now.
