### ISSUE TITLE
Automatically fill missing columns

### ISSUE THREAD

**Issue by StefanBertels** [JoshClose/CsvHelper#716]
Hi,

this is a feature request for poor-man's file format versioning (and some other scenarios).

I often have a situation where file formats change slightly and writing converters or supporting multiple formats is overhead. So upgrades are done manually... Maybe this could be solved with a little help by CsvHelper for some common use cases.

It would be great to have something like this:

```
CsvPropertyMap.OnMissingFields<TClass, TProperty>(Func<IReaderRow, out TProperty, bool> tryRepairExpression)
```

`tryRepairExpression` would work like readExpression in `ConvertUsing` but would return true when successful and false when not

If returning true then `out TProperty` would contain the result for the property (working like ConvertUsing).

if returning false then everything would continue as usual.

`tryRepairExpression` would only be called if mapping wasn't successful but before raising errors.

This way one could fill missing columns with individual default values (coming from other columns) which would be a very code-effective solution for column renaming or adding columns.

```
Map(m => m.PropName).Name("NewFieldName").OnMissingFields(fillNewFieldName);
Map(m => m.PropName).ConvertUsing(readPropAsInNewFormat).OnMissingFields(tryReadPropAsInOldFormat);
```

It's a bit advanced but IMO has these advantages:
- very little code
- explicit (you still get errors on other missing columns, WillThrowOnMissingField := false, no catch-all)
- explicit value creation (missing column != empty column, individual values possible)

I'm lookup forward to here about any existing / workaround solutions.

**Comment by JoshClose** [comment]
This looks like it can be post 3.0 release. Shouldn't be any breaking changes.

**Comment by JoshClose** [comment]
Wouldn't `ConvertUsing` cover this scenario?

**Comment by StefanBertels** [comment]
You are right. Combining `ConvertUsing` and `OnMissingFields` isn't meaningful. `ConvertUsing` can handle this and there is no _missing field_ (just maybe an exception).

And with regard to
 ```Map(m => m.PropName).Name("NewFieldName").OnMissingFields(fillNewFieldName);```
 I think due to complicated `tryRepairExpression` definition above there is only a small step to write a `ConvertUsing` and handle fallbacks myself.

I personally build my own extension function for such use cases (similar to simplification of ConvertUsing in my comment to #698). So I'm happy with closing this issue.

**Comment by JoshClose** [comment]
OK. I think this is somewhat of an edge case. `ConvertUsing` is specifically there so if you need to do something out of the ordinary that won't be used by many people, you can easily do it. This means less one off specific features for people
