### ISSUE TITLE
Centralize configuration for mapping

### ISSUE THREAD

**Issue by ayazaliuk101** [JoshClose/CsvHelper#717]
Hi

I really like this tool however I was wondering if it was possible to centralize the mapping configuration in one location without the need to pass it around, as this can lead to polluting various projects. so every time I call the either it takes the default configuration set by me or allows me to override it.

Hope that make sense.

Regards

Ayaz

**Comment by JoshClose** [comment]
Does this scenario not work for you?

```cs
var csv = new CsvReader( someReader );
csv.Configuration.HasHeaderRecord = false;
```

**Comment by ayazaliuk101** [comment]
No, say for example I have mappers, and I want the csv reader to use those
mapping classes every time I use the parser, I would have to pass the
config around which makes it more difficult. Ideally you would call config
once during start up or something, set up the configuration then every time
CsvReader is instantiated that configuration would be injected into it or
something like that.

**Comment by JoshClose** [comment]
That sounds like what an IoC container is used for.

**Comment by jamesbascle** [comment]
That's exactly what I do. IoC is the answer.

**Comment by JoshClose** [comment]
Closing this as I don't think it's the responsibility of this library.
