### ISSUE TITLE
Tests failing / CurrentCulture ListSeparator

### ISSUE THREAD

**Issue by StefanBertels** [JoshClose/CsvHelper#718]
Some Tests in source project are failing here because I have a different CurrentCulture (german, 1031).

Reason seems to be the default delimiter.

```
		private string delimiter = CultureInfo.CurrentCulture.TextInfo.ListSeparator;
		private CultureInfo cultureInfo = CultureInfo.CurrentCulture;
```

Test like `WriteFieldTest` set CulturInfo to "en-US", do not set delimiter explicitely and expect comma as result.

Options:

a) Make delimiter always a comma (instead of ListSeparator). Everything else should be set explicitely. This makes RFC4180 fans happy, but might be problematic for users of non-US-compatible cultures. I think being explicit is good here.

b) replace every use of delimiter by Delimiter (property), don't allow setting `null` to Delimiter and use 
`private string delimiter = null;` as initialization. Change Delimiter get to `return delimiter ?? cultureInfo.TextInfo.ListSeparator`.  This way setting cultureInfo would implicitely set ListSeparator as delimiter -- as long as not set explicitely. Tests are then ok, because you set comma implicitly by setting cultureInfo to "en-US". Maybe more of the Excel way.

c) You use cultureInfo for number and date formatting and for nothing else. Delimiter is delimiter and is a separate setting. This is current behaviour. A little bit odd because you use CultureInfo.CurrentCulture for delimiter initialisation but not the currentCulture property. In this case you should add explicit Delimiter to those failing tests.

**Comment by JoshClose** [comment]
I think it should be a comma, since that's what CSV means. It doesn't matter what country you're in or culture code you're using, based on the RFC it should still be a comma.

I'm going to change the private delimeter to default to a comma. I believe that's option `a)`.
