### ISSUE TITLE
Runtime mapping example for 3.0?

### ISSUE THREAD

**Issue by sereeth** [JoshClose/CsvHelper#719]
Are there any examples of runtime mappings for 3.0 since the docs are way out of date.  I'm looking to do something like read a dictionary of property name to column name, and create a map from that.  Maps would be stored in a database, so for each customer a different map can be created to read their files.

**Comment by JosephMDavis** [comment]
I'm looking for the same thing. Please help.

**Comment by jamesbascle** [comment]
Just make a subclass of csvclassmap that takes in whatever type you need to
use, and consume it in the constructor to configure the map.

**Comment by JoshClose** [comment]
I don't know all of the criteria you have, but here is one way.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("IdField,NameField");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;

		var dict = new Dictionary<string, string>
		{
			{ "IdField", "Id" },
			{ "NameField", "Name" }
		};

		var map = new DefaultCsvClassMap<Test>();
		foreach (var pair in dict)
		{
			var property = typeof(Test).GetProperty(pair.Value);
			var propertyMap = CsvPropertyMap.CreateGeneric(typeof(Test), property);
			propertyMap.Data.Names.Add(pair.Key);
			map.PropertyMaps.Add(propertyMap);
		}
		csv.Configuration.RegisterClassMap(map);
		csv.GetRecords<Test>().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

**Comment by sereeth** [comment]
For anyone that comes along to this issue here is how you do it in 5.0. 

```
 public class MyNewMap : ClassMap<YourModel>
 {

 }


 var map = new PortalPartMap();

// note customMapping is just a dictionary mapping the property name to the csv column 

               foreach (var key in customMapping.Keys)
                {
                    var propertyInfo = typeof(YourModel).GetProperty(key);
                    var newMap = MemberMap.CreateGeneric(typeof(YourModel), propertyInfo);
                    newMap.Data.Names.Add(customMapping[key]);
                    map.MemberMaps.Add(newMap);
                }

csv.Configuration.RegisterClassMap(map);

```

**Comment by JoshClose** [comment]
I'm adding the ability to do `newMap.Name( customMapping[key] )` instead of accessing the data directly. A lot of those methods have other things that happen when set.

**Comment by sereeth** [comment]
That will be better for sure, I kinda guessed.

**Comment by JoshClose** [comment]
This is done and in 6.0.0 on NuGet.

**Comment by nawfalhasan** [comment]
This could be slightly easier like this: 

               // Assume you have a dictionary of 'property names'/'column header' pairs.
               var columnHeadersByPropertyName = Dictionary<string, string> { ... };

                var classMap = myCsvWriter.Configuration.AutoMap(myElementType);
                foreach (var property in elementType.GetProperties())
                {
                    classMap .Map(myElementType, property).Name(columnHeadersByPropertyName [property.Name]);
                }

Should work for `CsvReader` as well.
