### ISSUE TITLE
Question: Does the reader support / manage the underlying stream's properties

### ISSUE THREAD

**Issue by brianro** [JoshClose/CsvHelper#720]
Love the library. Does the reader / writer manage or follow the underlying "reader / writer" properties - NewLine, Encoding?

**Comment by JoshClose** [comment]
For writing it uses `TextReader.WriteLine()`. For reading it uses `TextReader.Read()`. It uses whatever encoding you've set there. For reading it will look for '\r', '\n', or '\r\n' for new lines, so it doesn't matter where there file was created.

**Comment by brianro** [comment]
Is it possible for you to read the newline character from the underlying stream? Or add it to the configuration and override it? I have internal customers that want to use unorthodox EOLs. Ditto with encoding.

**Comment by JoshClose** [comment]
You can set the encoding on your stream. 

It's currently not possible to specify a new end of record. Using the text readers methods it would only be possible to do `ReadLine` which would read until the streams newline character(s). This is a problem for a couple reasons. The file could have been generated on linux and used '\n' and you could be reading on windows using '\r\n'. Second, a field could contain the newline character.

I think it would be possible to have the line ending be configurable. Currently it accounts for 3 different line endings. Those will always need to be accounted for. Maybe if you explicitly set it, it will override and just use that instead. Does it need to be multiple characters or a single character?

**Comment by brianro** [comment]
I envision EOL and Encoding set from the underlying Stream. The reader / writer gets the values from the Stream. Feels to me that's where the responsibility should be. Additionally, you could use the underlying readers to manage EOL for reading and the parser buffer contains a line at a time. This will reduce the amount of code you require and the edge cases for boundary detection when EOL straddles the buffer boundary.

Definitely needs to be multiple characters for EOL.

**Comment by JoshClose** [comment]
Is it possible to get that information? https://msdn.microsoft.com/en-us/library/system.io.textreader(v=vs.110).aspx

**Comment by brianro** [comment]
Its shaky, but there is this protected field. I must have stumbled on that when I was checking this out.
https://msdn.microsoft.com/en-us/library/system.io.textwriter.corenewline(v=vs.110).aspx

**Comment by JoshClose** [comment]
I can't count on that to be there, unfortunately.
