### ISSUE TITLE
writing CSV file with mapping and default value

### ISSUE THREAD

**Issue by darksonwolf** [JoshClose/CsvHelper#722]
Hi

I try to write a CSV file with mapping and default value.
this is my mapping class

    public class Report
      {
        
        public string Name{ get; set; }
      
        public string Car{ get; set; }
    }

    public sealed class ReportMap : CsvClassMap<Report>
    {
        public ReportMap()
        {
            Map(m => m.Name).Name("name");
            Map(m => m.Car).Name("car_owner").Default("NA");
        }
    }
and here is how I write the csv file

            var array = new[] {new Report() {Name= "mahdi"}, new Report(){Name = "Eli"}};
           using (TextWriter writer = new StreamWriter(@"C:\temps\report.csv"))
            {
                using (var csv = new CsvWriter(writer))
                {
                    csv.Configuration.RegisterClassMap<ReportMap>();

                    writer.Flush();
                    csv.WriteRecords(result);
                }
            }

but the default values will not replace into empty value.
I wonder if this is an expected behavior?

**Comment by JoshClose** [comment]
Currently it's only used when reading.
