### ISSUE TITLE
Custom mapping function to apply to all headers

### ISSUE THREAD

**Issue by tmenier** [JoshClose/CsvHelper#723]
This is a feature request, unless it's already possible somehow, in which case please set me straight. I want to map header names to properties based on a custom mapping function that will apply to _all_ headers, rather than mapping one by one. (Some files I need to deal with have dozens of headers, making things a little tedious.) Basically I want to say for all headers, strip out characters that are not valid in a C# identifier. More generically, it would be great to be able to do something like this:

```c#
csv.Configuration.MapHeader(h => h.Replace("/", "").Replace("-", "").Replace(" ", ""));
```

Thanks! Great library!

**Comment by JoshClose** [comment]
This exists in the pre-release. `Func<string, string> CsvHelper.Configuration.PrepareHeaderForMatch`

```cs
csv.Configuration.PrepareHeaderForMatch = header => header.Replace("/", "").Replace("-", "").Replace(" ", "");
```

It would probably be better to use `Regex` instead of chaining `Replace` calls though.

**Comment by tmenier** [comment]
Perfect, thanks. No doubt the real version will use a Regex, I just use them so seldom I couldn't remember the syntax off the top of my head. :)

**Comment by JoshClose** [comment]
The pre-release code is stable, but the api/naming could change before release.
