### ISSUE TITLE
Provide parameters to custom TypeConverter

### ISSUE THREAD

**Issue by christinehnguyen** [JoshClose/CsvHelper#726]
I need to do a custom date time conversion. Our date-times are stored in UTC and I need to display it in a local time zone depending on who is logged in and what geographical region they are based in. Can I and how do i inject time zone information into my custom type converter?  I found a way to do this with ConvertUsing methods,  but it seems this only works for reading and not writing CSV files. Conversion in writing files requires a custom TypeConverter, but it's not useful unless a can provide parameters to the converter.

**Comment by JoshClose** [comment]
When mapping you can use `Map( m => m.Property ).TypeConverterOption( string format )` to specify the format you want to use.

For future reference, the 3.0 pre-release does have `ConvertUsing` for writing. ;)

**Comment by christinehnguyen** [comment]
Thanks for your reply. Unfortunately, it's more than just string format information I need to pass in. I have a custom class that converts from UTC to other time zones and I want to pass an instance of this class in. Is that possible? And happy to 3.0 pre-release supports ConvertUsing for writing. :)

**Comment by JoshClose** [comment]
Can you use the constructor of the type converter to pass the information in you need?

**Comment by christinehnguyen** [comment]
Possibly. How do I pass the information into the constructor? Could you give me an example?

**Comment by JoshClose** [comment]
This is very basic, but hopefully it can give you and idea.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<Test>
		{
			new Test { Id = 1, Name = "one", DateTime = DateTime.Now.AddDays( 1 ) },
			new Test { Id = 2, Name = "two", DateTime = DateTime.Now.AddDays( 2 ) },
		};
		
		csv.Configuration.RegisterClassMap<TestMap>();
		csv.WriteRecords(records);
		
		writer.Flush();
		stream.Position = 0;
		
		reader.ReadToEnd().Dump();
	}
}

public class Test
{
	public int Id { get; set; }
	public string Name { get; set; }
	public DateTime DateTime { get; set; }
}

public sealed class TestMap : CsvClassMap<Test>
{
	public TestMap()
	{
		var dateTimeConverter = new TestConverter(new UtcConverter());
		
		Map(m => m.Id);
		Map(m => m.Name);
		Map(m => m.DateTime).TypeConverter(dateTimeConverter);
	}
}

public class TestConverter : DateTimeConverter
{
	private readonly UtcConverter utcConverter;
	
	public TestConverter(UtcConverter utcConverter)
	{
		this.utcConverter = utcConverter;
	}
	
	public override string ConvertToString(TypeConverterOptions options, object value)
	{
		var dt = value as DateTime?;
		if (dt != null)
		{
			dt = utcConverter.Convert(dt.Value);
			return base.ConvertToString(options, dt.Value);
		}
		
		return base.ConvertToString(options, value);
	}
}

public class UtcConverter
{
	public DateTime Convert( DateTime dt )
	{
		return dt.ToUniversalTime();
	}
}
```

**Comment by christinehnguyen** [comment]
Looks straightforward enough. I will give it a try. Thanks! :)

**Comment by JoshClose** [comment]
Let me know if you have any more questions.

**Comment by christinehnguyen** [comment]
Worked beautifully, thank you!!

**Comment by JoshClose** [comment]
Great!
