### ISSUE TITLE
Generic exeption thown with no details

### ISSUE THREAD

**Issue by MrHinsh** [JoshClose/CsvHelper#727]
I get no exceptions when running in debug mode, but when I look at the pull out in Visual Studio I can see a random:

`csv.CurrentRecord	'csv.CurrentRecord' threw an exception of type 'CsvHelper.CsvReaderException'	string[] {CsvHelper.CsvReaderException}`

With no way to debug! This CSV file I am importing was created by:

```
StreamWriter sw = File.CreateText(Path.Combine(exportPath, "AzureADGroups.csv"));
            sw.AutoFlush = true;
            using (var csv = new CsvWriter(sw))
            {
                csv.WriteHeader<AzureAdGroupItem>();
```

I am not sure how to proceed or debug!?

![image](https://user-images.githubusercontent.com/5205575/29242676-5689969e-7f91-11e7-8545-663218f76b1b.png)

**Comment by JoshClose** [comment]
It's the first item in the FAQ in the docs. http://joshclose.github.io/CsvHelper/#misc-faq

This is changing in 3.0 though and the exception itself will contain all the information.

**Comment by JoshClose** [comment]
`Exception.Data["CsvHelper"]`

**Comment by MrHinsh** [comment]
Since no exception is thrown how do I access "Exception.Data["CsvHelper"]"... Even Visual Studio does not detect any actual exceptions (you can see the 0 of the right.

**Comment by JoshClose** [comment]
Oh, I see what's happening. When you hover over `csv`, Visual Studio pops up that windows that shows the values of the properties. At the point you're in, those aren't valid and will throw exceptions when called. The exception text more than likely says `You must call read on the reader before accessing its data.`

**Comment by JoshClose** [comment]
If you run this code, you'll see the exception.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		Console.WriteLine(csv.Row);
	}
}
```
