### ISSUE TITLE
NET Standard

### ISSUE THREAD

**Issue by marlon-tucker** [JoshClose/CsvHelper#728]
Hi,

With the release of NET Standard 2.0, has there been any thoughts on migrating this project to use it? 

I've been looking for a CSV Writer which is compatible with NET Core and don't particularly want to roll my own as I'll get escaping wrong.

**Comment by marlon-tucker** [comment]
Apologies, did not realise the project had a NET Core target.

**Comment by JoshClose** [comment]
Did 2.0 come out? The source is definitely updated so you can use the 3.0 pre-release if the 2.x version doesn't have core. I don't remember off the top of my head.

**Comment by jamesbascle** [comment]
It was just finalized in the last few days. I dont think a release, per se,
has been done yet, or the tooling is RTM.

**Comment by JoshClose** [comment]
It's live now!
