### ISSUE TITLE
Map indexes are not reindexed after removal

### ISSUE THREAD

**Issue by edudutra** [JoshClose/CsvHelper#730]
This is the scenario: I have a lot of model classes that are almost the same as the csv files being loaded, except for one ```Id``` column that exists in the table and not in the files. The files do not have Headers. To solve that, I've just used AutoMap to each class and removed the ```Id``` column from PropertyMaps, using reflection. But when I do that, I get a ```CsvHelper.CsvMissingFieldException``` error, with message  _Field at index '2' does not exist_ . 
On further investigation, I found that happens because when I remove one column from the PropertyMapsCollection, Indexes for the remaining properties are not rebuilt, causing the error. 
The following code reproduces this behavior:

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            var fileContents =
                "ABC,3\n" +
                "DEF,2\n" +
                "XYZ,1\n";

            var byteArray = Encoding.UTF8.GetBytes(fileContents);

            using (var ms = new MemoryStream(byteArray))
            using (var sr = new StreamReader(ms))
            {
                var csv = new CsvReader(sr);
                csv.Configuration.HasHeaderRecord = false;
                csv.Configuration.Encoding = Encoding.UTF8;

                csv.Configuration.RegisterClassMap(csv.Configuration.AutoMap<MyModelClass>());
                csv.Configuration.Maps[typeof(MyModelClass)].PropertyMaps.RemoveAt(0);

                
                var records = csv.GetRecords<MyModelClass>().ToList();


            }
        }
    }

    class MyModelClass
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        
    }
```
Is this the intended behavior or could this be modified? Is there any other way to accomplish that without forcing the reindex?

**Comment by gary-palmer** [comment]
Just for a bit of info; I changed the indexes to fix my issue without any problems;
[https://github.com/JoshClose/CsvHelper/issues/731](https://github.com/JoshClose/CsvHelper/issues/731)

**Comment by JoshClose** [comment]
Hmm... I don't think it should do that because you may have configured the map yourself. You'd only want to do this if you've created the map through auto mapping, and haven't changed anything after.

If this is a concern, maybe I can open up the `int ReIndex( int indexStart = 0 )` method and make it public.

**Comment by edudutra** [comment]
Thanks. That would be nice. 
I saw this method and thought exactly that. Make it public. 

By the way, congrats for the great library!!!

**Comment by JoshClose** [comment]
I made `GetMaxIndex` public also. This may be useful if you're manually messing around with that stuff.

**Comment by JoshClose** [comment]
f8e026de17021aa0122063455c195032e2d6969e
