### ISSUE TITLE
Question: CSVWriter - Is it possible to specify the order of some columns and have the remainder autofill in?

### ISSUE THREAD

**Issue by gary-palmer** [JoshClose/CsvHelper#731]
Given a class/POCO that represents a row in a datatable, can I order it such that the primary key columns are written first and the remaining columns auto-ordered onwards?

I'm hoping that if the POCO changes I don't have to then worry about maintaining the csv mapping for that  object (on the assumption that the the primary keys are unlikely to change).  I could just hold a mapping or whatever for the primary keys, without specifying every other column.

**Comment by JoshClose** [comment]
Do you have a header in the CSV file?

**Comment by gary-palmer** [comment]
Yes

**Comment by gary-palmer** [comment]
Think I may have figured this one out;  Use the automapper to get a map of the object and then build a new one from that picking the required columns first.  

Are their any issues with changing the index after the map has been autogenerated? 
[https://gist.github.com/gary-palmer/f1121a48e7538534718439eefc495d0e
](https://gist.github.com/gary-palmer/f1121a48e7538534718439eefc495d0e)

**Comment by JoshClose** [comment]
If there is a header file, I don't understand the need to map on indexes. Is there a reason you can't use the header names instead?

**Comment by gary-palmer** [comment]
Apologies, it's probably my misunderstanding of what is possible.

How would I go about re-ordering columns for output, only specifying the columns I want at the beginning i.e. without specifying every single column?

**Comment by JoshClose** [comment]
Does the pkey names have to by dynamic like you have in your example?

**Comment by gary-palmer** [comment]
I guess not.  I don't have to use a list of strings. I could create a map for just those columns in the usual way i.e.  `Map( m => m.Name ).Name( "The Name Column" );`

But I may have assumed it would just ignore the remaining columns??

**Comment by JoshClose** [comment]
The way your came up with is perfectly fine. I don't think there is an easy class mapping way to do what you're trying to do.

**Comment by gary-palmer** [comment]
OK, thanks for your help (and the great library!)

**Comment by JoshClose** [comment]
You're welcome!
