### ISSUE TITLE
Make TypeConverterFactory a property of CsvConfiguration

### ISSUE THREAD

**Issue by wojciechrak** [JoshClose/CsvHelper#732]
Hi,
would it be possible to refactor TypeConverterFactory from a static class into a property of CsvConfiguration?

It seems very limiting to have this as static class.
Let's say I have two workflows: A and B, where eg. `DateTime` values should be treated differently.
I can't register a global TypeConverter for DateTime in this case (unless I re-register default DateTimeConverter afterwards).

To avoid breaking changes, the static class can still be there, so when TypeConverterFactory property on CsvConfiguration is not set, the static class will be used.

Or maybe there is some justification for this design decision that I am not aware of ;)
What do you think?

**Comment by JoshClose** [comment]
The only reason it's a singleton is because that's how the .NET type converter system worked. This is a different beast and I don't see any reason why this can't be moved into the config.

**Comment by JoshClose** [comment]
I moved it to the configuration class. There are some places that don't have the configuration, so I added a static `Current` property to it than can be used in those cases.

912d3d175d1cf87b3c3756592e272573922a9f2b
