### ISSUE TITLE
Using .Constant(null) leads to CsvHelper.CsvWriterException: 'An unexpected error occurred.'

### ISSUE THREAD

**Issue by Mertsch** [JoshClose/CsvHelper#734]
`this.Map().Name("Time stamp UTC").Constant(null);` leads to
```
CsvHelper.CsvWriterException occurred
  HResult=0x80131500
  Message=An unexpected error occurred.
  Source=CsvHelper
  StackTrace:
   at CsvHelper.CsvWriter.WriteRecord[T](T record)
   at [...]

Inner Exception 1:
InvalidOperationException: No method 'WriteConvertedField' on type 'CsvHelper.CsvWriter' is compatible with the supplied arguments.
```

**What I expected**
`this.Map().Name("x").Constant(null);` === `this.Map().Name("x").Constant(string.Empty);`
Just print nothing to the column

**Comment by JoshClose** [comment]
This is fixed. It'll be in chi08. If you need that released soon, let me know. It may just end up being in RC1 too, if you don't need it immediately. 67d6895497cca3e69d8fdc786407a5e0befef448

**Comment by Mertsch** [comment]
@JoshClose In RC0 this no longer throws an exception, but it also does not work.
Rows for `ClassMap`s with `Constant(null)` will simply be ignored and not written to the CSV.

**Comment by JoshClose** [comment]
Looks like I need another unit test. :)

**Comment by JoshClose** [comment]
29b8a9a54077ec955d283c3ba3840fcffef5c39f
