### ISSUE TITLE
Race condition in ReflectionHelper.cs

### ISSUE THREAD

**Issue by CornedBee** [JoshClose/CsvHelper#735]
The `CreateInstanceWithoutContractResolver` method uses the static `funcArgCache` member, which is a map from number of arguments to another map, which goes from a key string to factory function.

Access to `funcArgCache` itself is protected by a mutex. However, the result of the lookup is cached, and access to the result is not protected from concurrent access. If two threads ask for construction of objects with the same number of arguments at the same time (in the case of mappings, the argument count is always 0) they will get the same inner cache map and thus race on it.

The easiest, but not only, way to solve this would be to get rid of the top level cache altogether and simply lock the access to the map that contains all key-func mappings. (The top level cache doesn't seem useful to me.)

Alternatively, a `ConcurrentMap<string, Lazy<Delegate>>` provides a simple way of creating a thread-safe cache when construction of the value might be expensive or should otherwise only happen once.

**Comment by JoshClose** [comment]
You're going to have to be a little more specific. Can you paste the method here and put comments in it about what you're talking about? I think that will be a little easier for me to follow then.

**Comment by CornedBee** [comment]
Here's the function I'm talking about, with additional comments explaining the problem.

```
		public static object CreateInstanceWithoutContractResolver( Type type, params object[] args )
		{
			Dictionary<string, Delegate> funcCache;
			lock( locker )
			{
				// funcArgCache is a static member, shared globally.
				// This access to it is protected by the lock and thus safe.
				if( !funcArgCache.TryGetValue( args.Length, out funcCache ) )
				{
					funcArgCache[args.Length] = funcCache = new Dictionary<string, Delegate>();
				}
			}

			var typeNames = new List<string>();
			typeNames.Add( type.FullName );
			typeNames.AddRange( args.Select( a => a.GetType().FullName ) );
			var key = string.Join( "|", typeNames );

			Delegate func;
			// Note, however, that funcCache here is *also* shared. It refers to one of the
			// dictionaries stored in funcArgCache, and thus if two threads enter this function
			// at the same time with the same args.Length (e.g. 0, for zero arguments, as is the
			// case if you're coming from CsvConfiguration.RegisterClassMap<TMap>()), they
			// get the *same* dictionary.
			// This means that the lookup and insertion here is two threads accessing the same
			// dictionary. This is a data race and lead to bad results (my program threw a
			// NullReferenceException inside the implementation of Dictionary.this[index]=, i.e.
			// the indexed assignment inside the if.
			if( !funcCache.TryGetValue( key, out func ) )
			{
				funcCache[key] = func = CreateInstanceDelegate( type, args );
			}

			try
			{
				return func.DynamicInvoke( args );
			}
			catch( TargetInvocationException ex )
			{
				throw ex.InnerException;
			}
		}
```

**Comment by JoshClose** [comment]
You don't have the latest source. This was already fixed on June 3rd, which is where my confusion lied. 960a3c8c96d693a8aa1b64a9b90ef375f379caaf

**Comment by CornedBee** [comment]
If you check my post again, you will see that I listed the function after this commit, already including the lock. I also explain why this lock is insufficient.

I will create a pull request that fixes this bug. Give me a few days.

**Comment by JoshClose** [comment]
A pull request would help. Here is the current code that has locking around `funcCache`, which is where your comment in your example was.

```cs
public static object CreateInstanceWithoutContractResolver( Type type, params object[] args )
{
	Dictionary<string, Delegate> funcCache;
	lock( locker )
	{
		if( !funcArgCache.TryGetValue( args.Length, out funcCache ) )
		{
			funcArgCache[args.Length] = funcCache = new Dictionary<string, Delegate>();
		}
	}

	var typeNames = new List<string>();
	typeNames.Add( type.FullName );
	typeNames.AddRange( args.Select( a => a.GetType().FullName ) );
	var key = string.Join( "|", typeNames );

	Delegate func;
	lock( locker )
	{
		if( !funcCache.TryGetValue( key, out func ) )
		{
			funcCache[key] = func = CreateInstanceDelegate( type, args );
		}
	}

	try
	{
		return func.DynamicInvoke( args );
	}
	catch( TargetInvocationException ex )
	{
		throw ex.InnerException;
	}
}
```

**Comment by CornedBee** [comment]
Ah, this second lock block fixes the issue. That wasn't in the commit you linked before.

**Comment by JoshClose** [comment]
Oops. I must have linked the wrong commit.
