### ISSUE TITLE
Issue with Read() and GetRecord<T>()

### ISSUE THREAD

**Issue by philwindsor** [JoshClose/CsvHelper#736]
Hi Josh,

hopefully i'm just doing something silly here and you can correct me...

```
// My config settings pasted here for clarity

_csvConfig.PrepareHeaderForMatch = header => header.Trim();
_csvConfig.PrepareHeaderForMatch = header => Regex.Replace(header, "[^a-zA-Z0-9]", string.Empty);
_csvConfig.IgnoreBlankLines = true;
_csvConfig.HasHeaderRecord = true;

IList<T> itemsToReturn = new List<T>();            

using (var streamReader = new StreamReader(stream))
{
    var csv = new CsvReader(streamReader, csvConfig);
                
    while (csv.Read())
    {       
            var record = csv.GetRecord<T>();

            if (record != null)
            {
                itemsToReturn.Add(record);
            }
        }       
    }
}
```
So my code above fails if I try and parse a file that only contains the header row and no data rows.

The error is: 

> The reader has already exhausted all records. If you would like to iterate the records more than once, store the records in memory. i.e. Use CsvReader.GetRecords<T>().ToList()

What am I doing wrong? I cant use GetRecords<T>() because the bottom of the csv file i'm parsing can sometimes contain another table which is an annoyance to say the least, hence why I need to parse row by row and ignore the last few when I get there...

*Edit*
I forgot to mention i'm using one of the beta versions so i could access the new PrepareHeaderForMatch property. 3.0.0-beta7

**Comment by philwindsor** [comment]
I've updated to the latest beta build 3.0.0-chi06 and the issue has been resolved. Any idea when the next stable release will be done?

**Comment by JoshClose** [comment]
Soon!!! There are only a few breaking change features left I want to implement before I can release. Breaking change meaning interface changes. I'm planning on releasing in the next couple weeks.

**Comment by philwindsor** [comment]
Thanks for the update Josh. Hopefully it's released by the time I need to release my project, September wink wink 😉
