### ISSUE TITLE
Support Immutable Types

### ISSUE THREAD

**Issue by piers7** [JoshClose/CsvHelper#739]
CsvHelper can't load CSV data onto immutable types, such as F# records and C# anonymous types. It'd be nice to directly support these types, by instead directing column data via their constructor. The heuristic for this could be as simple as: if no writable properties, attempt to use longest constructor.

There's a workaround for F# records - mark them as CLIMutable - but native support (like JSON.Net has) would be preferable

**Comment by JoshClose** [comment]
I had never even heard of this. https://www.newtonsoft.com/json/help/html/DeserializeAnonymousType.htm That shouldn't be a problem.

Can you give an example of an immutable type in F#? I see this in JSON.net https://www.newtonsoft.com/json/help/html/DeserializeImmutableCollections.htm

**Comment by piers7** [comment]
All F# records (unless annotated with CLIMutable) are immutable.

As far as I can tell, looking back through old JSON.Net release notes, they've supported creating objects via constructor parameters (and hence supporting immutable objects) for a long time, potentially introducing in [3.5.5](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/3.5.5). More recently there's been some explicit F# support for discriminated unions and so forth, but I suspect F# records primarily 'just work' because of the constructor-parameters support.

**Comment by JoshClose** [comment]
There is support for a contract resolver now, which I believe should solve that problem.

**Comment by piers7** [comment]
Awesome. So is that 'should solve' as in 'should already work in latest code' or 'basic underpinnings already in place, so shouldn't be too hard'?
Happy to help BTW.

**Comment by JoshClose** [comment]
It's in the 3.0 pre-release on nuget. I'm planning on getting 3.0 RTM out the door very soon. I have only a couple things left before I'll release. I don't think I'll do a RC because this pre-release has been out there for over a year and has had several hundred thousand downloads. I just need to make sure there won't be any interface changes.

I'm adding the anonymous type feature to the 3.0 release though. That seems like a really nice feature.

**Comment by JoshClose** [comment]
I have this working completely for anonymous types. They can have nested anonymous types, or nested reference types, and it'll work all the way down the tree.

There is no reason this wouldn't work for any type that doesn't have a parameterless constructor. I may just have it do in that case also, and just choose the constructor that has the most parameters by default. It would probably also be a good idea to include a way to choose which constructor it uses.

**Comment by JoshClose** [comment]
I have this completed if you want to see. d20cc2a5da1b11b2846596ef2ee1cf78b3653401

I think I'm going to add it for all classes that don't have a parameterless constructor instead of just anonymous types. We'll see how this goes.

**Comment by JoshClose** [comment]
I got it working for any constructor now. 804fdb51d9dcdae900391199b62d0ad493be8486

Take a look at the unit tests here to see how it's used.

https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper.Tests/Reading/AnonymousTypesTests.cs
https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper.Tests/Reading/ConstructorParametersTests.cs

**Comment by piers7** [comment]
Had a look this evening, and doesn't seem to work against F# records in the 3.0.0-chi06 nuget. Simple linqpad repo available at http://share.linqpad.net/bi4h5p.linq (with references etc...) but code below.

Looking (briefly) at the diff I think you're only applying this for what appear to be anonymous types (based on a heuristic). Wouldn't it be just easier (and safer) to apply this strategy for _any_ type with no default constructor (especially if they had no writable properties) - which would work for F# records, C# anonymous types and pretty much any other immutable type?

```
let testData = @"
Name,Legs
Spider,8
Cat,4
Parrot,2
Worm,0
"

// Attribute should not be required when CsvHelper handles F# records
//[<CLIMutableAttribute>]
type Animal = { Name : string; Legs : int }

do
    use reader = new IO.StringReader(testData)
    use csvReader = new CsvHelper.CsvReader(reader)
    csvReader.GetRecords<Animal>() |> Dump
    ()
```

**Comment by JoshClose** [comment]
NuGet hasn't been updated. I'll push chi07 right now so you can check it out.

**Comment by JoshClose** [comment]
Ok, pushed. You should see chi07 on NuGet soon.

**Comment by JoshClose** [comment]
It hasn't been indexed yet, but you can probably add it by name.

https://www.nuget.org/packages/CsvHelper/3.0.0-chi07

**Comment by JoshClose** [comment]
`PM> Install-Package CsvHelper -Version 3.0.0-chi07`

**Comment by piers7** [comment]
Sorry to take so long to reply. I ran into the issue with Linqpad not supporting .net standard (but took me a while to twig what was going on).
Successfully used this in a full C#/F# project instead: my only comment would be that it didn't initially work because the constructor parameters were cased differently to the properties - I wonder if maybe case sensitivity should apply differently in that scenario?

**Comment by JoshClose** [comment]
You can use `Configuration.PrepareHeaderForMatch` to change that behavior.

```cs
csv.Configuration.PrepareHeaderForMatch = header => 
    CultureInfo.CurrentCulture.TextInfo.ToTitleCase( header );
```

If there are multiple constructors, it'll use the one with the most parameters by default. You can change that behavior using `Configuration.GetConstructor`.

```cs
csv.Configuration.GetConstructor = type => type.GetConstructors().First();
```

You can also change if it uses constructor parameters instead of class members by changing `Configuration.ShouldUseConstructorParameters`. The default is this.

```cs
csv.Configuration.ShouldUseConstructorParameters = type => 
    !type.HasParameterlessConstructor()
    && !type.IsUserDefinedStruct()
    && !type.IsInterface
    && Type.GetTypeCode( type ) == TypeCode.Object;
```
