### ISSUE TITLE
Map multiple values from .csv file into one property field

### ISSUE THREAD

**Issue by ivasiva** [JoshClose/CsvHelper#74]
Hello, 

is there a way to map, for e.g., two values (from two different fields) from .csv file into one property field?
e.g
Map(m => m.UserAddress).Name("StreetName"_someDelimiter_"StreetNumber");

**Comment by Nasoki-Koide** [comment]
Is it possible to map multiple value into one property via constructor? ParameterMap does not have Convert method.

**Comment by JoshClose** [comment]
Not at this time. I don't think it was possible for some reason... I switched Convert from a Func to a delegate at some point, so maybe it's possible now to add it now.
