### ISSUE TITLE
CsvClassMap with partial name

### ISSUE THREAD

**Issue by huazhb** [JoshClose/CsvHelper#742]
I have a csv file with a name like 'Amount(Currency)', the Currency will be any currency, how do I do it in the CsvClassMap? If I can use Name("Amount(%)") will be fantastic.

**Comment by JoshClose** [comment]
There is currently no way to do that. Is there a finite list of currencies? You can use a list of names, so you could list them all individually. 

Will there be multiple columns that have a variable currency? What you might be able to do is to use the `Configuration.PrepareHeaderForMatch` in 3.0 to remove or replace the `(%)` part, or even the whole name depending on the currency.

**Comment by huazhb** [comment]
Hope you can add such function in the future. Thank you very much.
