### ISSUE TITLE
Problems with .net core 2

### ISSUE THREAD

**Issue by Maquiavelo1408** [JoshClose/CsvHelper#743]
Is the library supported by .netcore 2?

**Comment by JoshClose** [comment]
The pre-release on NuGet is. https://www.nuget.org/packages/CsvHelper/3.0.0-chi07

This release will hopefully RTM within the next few weeks.

**Comment by JoshClose** [comment]
3.0.0-RC02 is out there now. RTM is pretty much just pending me getting some basic documentation up.
