### ISSUE TITLE
Exporting a csv file

### ISSUE THREAD

**Issue by Maquiavelo1408** [JoshClose/CsvHelper#744]
Hi, how can i write the csv file and after that make a download of the file.
I hope i explain

**Comment by JoshClose** [comment]
In MVC, Roughly like this.

```cs
var stream = new MemoryStream();
var writer = new StreamWriter(stream);
var csv = new CsvWriter(writer);
csv.WriteRecords(records);
return File( stream, "text/csv", "MyFile.csv" );
```

**Comment by lukegibbins** [comment]
Does returning File safely dispose of memorystream,streamwriter and csvwriter? I'm wondering whether to use these in using blocks...

**Comment by JoshClose** [comment]
If you put using blocks around them, they will be disposed of before the file is sent back to the client, so you don't want to do that. If you create the variables in the controller action like that, they will be disposed of when the garbage collector gets around to it, which is fine.
