### ISSUE TITLE
Fails compiling in Release with error: ILT0005

### ISSUE THREAD

**Issue by delsoftusa** [JoshClose/CsvHelper#751]
Hi, I've a UWP project for windows 10 mobile which was working just fine and deployed to windows store several times without issues. But suddenly it stopped compiling in release mode only with this error. Need your help please. I spent two days messing up my VS environment but nothing worked. Whats wrong?
Target Version: Windows 10(10.0; Build 10586
Min Version: Windows 10(10.0; Build 10240)
Compiles and works fine in Debug.

ILT0005: 'C:\Program Files (x86)\MSBuild\Microsoft.NetNative\ARM\ilc\tools\Gatekeeper.exe @"D:\Think Projects\ThinkUniversal\ThinkUniversal\obj\ARM\Release\ilc\intermediate\gkargs.rsp"' returned exit code -532462766
Unhandled Exception: OutOfMemoryException.

**Comment by JoshClose** [comment]
What version of CsvHelper are you using?
