### ISSUE TITLE
Ignoring fields

### ISSUE THREAD

**Issue by neslekkim** [JoshClose/CsvHelper#753]
I'm trying to do as you described in the bottom here: https://github.com/JoshClose/CsvHelper/issues/278

```
public sealed MyClassMap : CsvClassMap<MyClass>
{
    public MyClassMap()
    {
        AutoMap();
        Map( m => m.MyProperty ).Ignore();
    }
}
```
That is the file does not have the given field when I read it, but still the reader crashes and gives me this message:

> CsvHelper.ValidationException: 'Header 'MyProperty' was not found. If you are expecting some headers to be missing and want to turn this validation check off, set the configuration ThrowOnBadHeader to false.'

What is the idea here?, do I need to use the Ignore, AND throw on bad header?, I don't want to do the latter, in case the file actually IS bad.

**Comment by JoshClose** [comment]
This is a bug. There is a new header validation that is turned on by default. It doesn't validate one's that can't be written to. It should also include ignored properties. 

For now, you can do `csv.Configuration.ThrowOnBadHeader = false;` to have it not validate the header. I'll change the validation to look at the `Ignore` setting too.

**Comment by JoshClose** [comment]
Done. 538307ce8f4da4fe1100dcf6d713c5e30c4159bf

**Comment by RomanOwensby1** [comment]
I am having this same issue as well
