### ISSUE TITLE
Problem compiling / .net standard 2.0

### ISSUE THREAD

**Issue by neslekkim** [JoshClose/CsvHelper#755]
Can you give some info about compiling this, I'm currently using vs2017 15.3.4, and it looks like this project is for .net standard 2.0 now.
I'm not quite into this "standard" thingy yet, but I'm currently using CsvHelper with .net Framweork which works fine (that is, the 3.0.0 RC01 (is that also .net standard 2.0? )

When I create an .net standard project in vs2017, I only get max v1.6, not 2.0.

How did you go about to get 2.0?
I find it a bit confusing from microsoft at the moment about the versioning of everything, so I'm not complaining, but rather want to be able to compile so I can follow the progress (and get the latest fixes that was done, not using this for any production use)

help? :)

**Comment by JoshClose** [comment]
Install the SDK. https://www.microsoft.com/net/core#windowscmd

If that's not working for VS, you might need to run the Visual Studio Installer and update the .NET Core integration to 2.0. I don't remember if I had to do that or not. If you don't have the Visual Studio Installer on your computer, just download the latest VS 2017 installer (should be tiny), and that will install it and let you select new features or update existing ones.

**Comment by neslekkim** [comment]
Ok, I guess things work better when 15.4 is released atleast .net core 2 should come with that version.
Checked the installer again now (did a couple a days ago due to 15.3.4), but no 2.0 stuff there yet.

**Comment by neslekkim** [comment]
Good, after installing that sdk, everything worked.

**Comment by JoshClose** [comment]
Oh Good! They have a bunch of installers, and I'm not clear on which does what. ;)

**Comment by neslekkim** [comment]
Yes, that is the problem, and this doesn't make it easier:
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
I thought .net standard would be bundled with 4.7, which also came earlier, but no.

**Comment by JoshClose** [comment]
I'm glad it works with 4.6.1 though.
