### ISSUE TITLE
Multiline quoted cells can't be read

### ISSUE THREAD

**Issue by AqlaSolutions** [JoshClose/CsvHelper#757]
E.g.

    A,B
    1,ok
    2,"sdfsf
    continue"

Can't read the 2nd row correctly, it treats "continue" as another row.

**Comment by JoshClose** [comment]
I'll need a failing example. This works:

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("A,B");
		writer.WriteLine("1,ok");
		writer.WriteLine("2,\"sdfsf");
		writer.WriteLine("continue\"");
		writer.Flush();
		stream.Position = 0;
		
		csv.GetRecords<Test>().Dump();
	}
}

public class Test
{
	public int A { get; set; }
	public string B { get; set; }
}
```

![image](https://user-images.githubusercontent.com/114971/30559765-579e692c-9c7b-11e7-82eb-978a352eccd4.png)

**Comment by AqlaSolutions** [comment]
I'm not sure but somehow it was writing csv files impossible to be read later. I'll reopen this if can reproduce it again.

**Comment by RedX2501** [comment]
With version 12.1.2 If I try the example and replace `Dump()` with `First()` I get the following error:

> CsvHelper.HeaderValidationException: 'Header with name 'A' was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.'

**Comment by JoshClose** [comment]
This doesn't work for you?

```cs
void Main()
{
	var s = new StringBuilder();
	s.AppendLine("A,B");
	s.AppendLine("1,ok");
	s.AppendLine("2,\"sdfsf");
	s.AppendLine("continue\"");
	using (var reader = new StringReader(s.ToString()))
	using (var csv = new CsvReader(reader))
	{
		csv.Configuration.Delimiter = ",";
		csv.GetRecords<Foo>().ToList().Dump();
	}
}

public class Foo
{
	public int A { get; set; }
	public string B { get; set; }
}
```

**Comment by RedX2501** [comment]
That seems to fix it. Do you know what is happening?

**Comment by JoshClose** [comment]
My guess is that your `CultureInfo.CurrentCulture.TextInfo.ListSeparator` is not a comma.

**Comment by RedX2501** [comment]
Why did you choose to go with the culture ListSeparator if even the RFC states that a comma separates fields (and not a language dependent character)?

**Comment by JoshClose** [comment]
Good point! The reason was that a lot of programs in other cultures would write files using that and I wanted CsvHelper to read files without configuration. 

I've found that brings up other issues though, so it's changing back to read and write a comma by default in an upcoming version.

**Comment by jzabroski** [comment]
@JoshClose Maybe just make the configuration easily discoverable, e.g. via enum behavior

**Comment by jzabroski** [comment]
I'm curious what the behavior is when you define: `IgnoreMissingFields = true` and/or:

```csharp
new CsvHelper.Configuration.Configuration
            {
                IgnoreBlankLines = true,
                TrimOptions = TrimOptions.Trim
            };
```

I'm running into an issue that isn't related to the culture info line separator.

**Comment by jzabroski** [comment]
Nevermind - found my issue.
