### ISSUE TITLE
Written strings looking like numbers with starting 0 are showed incorrectly by Excel

### ISSUE THREAD

**Issue by AqlaSolutions** [JoshClose/CsvHelper#758]
E.g. the string value `0971234567` is showed as `971234567`. Is anything possible to do at your side?

**Comment by JoshClose** [comment]
You can include a `=` before the number for Excel to keep it. CsvHelper does not support Excel though, so you'll have to add the `=` yourself. There are numerous ways of doing this. Creating a type converter for `int` or whatever number type you're using is probably the easiest.
