### ISSUE TITLE
Error "No header record found"

### ISSUE THREAD

**Issue by maverick09** [JoshClose/CsvHelper#76]
I am doing following to read data from a csv file and upload into database. Have fixed size to  100,000 rows in the each file. There can be 20 such files at one go to be processed one by one. 

Usually this code works fine and processes files successfully however in some intermittent cases it throws error "No header record found" and fails to process file. 

```
    /// <summary>
    /// LoadCsvIntoTable
    /// </summary>
    /// <param name="streamReader"></param>
    /// <returns></returns>
     private bool LoadCsvIntoTable(StreamReader streamReader)
    {
        try
        {
            var config = new CsvConfiguration() { HasHeaderRecord = true };

            using (var csvReader = new CsvReader(streamReader, config))
            {
                int totalRecordsCounter = 0;
                var dateTimeTypeConverter = new DateTimeTypeConverter();
                var booleanTypeConverter = new CustomBooleanTypeConverter();

                while (csvReader.Read())
                {
                    try
                    {
                         var playerGame = GetRowFromCsv(csvReader, dateTimeTypeConverter, booleanTypeConverter);

                        localContext.AttachTo(EntitySetNames.MyEntitySetName, playerGame);

                        // Change the state of the entity to "Modified"
                        localContext.UpdateObject(playerGame);

                        totalRecordsCounter++;
                    }
                    catch (Exception exception)
                    {
                        throw;
                    }
                }
                localContext.SaveChanges(SaveChangesOptions.Batch);
                localContext.IgnoreResourceNotFoundException = false;
            }
        }
        catch (Exception exception)
        {
            NLogWrapper.LogException("Failed in LoadCsvIntoTable", exception);
            throw;
        }
        return true;
    }



    /// <summary>
    /// Gets Row From Csv
    /// </summary>
    /// <param name="csvReader"></param>
    /// <param name="dateTimeTypeConverter"></param>
    /// <param name="booleanTypeConverter"></param>
    /// <returns></returns>
    private Game GetRowFromCsv(CsvReader csvReader,
                                DateTimeTypeConverter dateTimeTypeConverter,
                                CustomBooleanTypeConverter booleanTypeConverter)
    {
        return new Game()
        {
            PlayerIdId = csvReader.GetField(0) ?? String.Empty,
            RowKey = csvReader.GetField(1) ?? String.Empty,
            HasWonGame = csvReader.GetField<Boolean>(2, booleanTypeConverter),
            JoinedOn = csvReader.GetField<DateTime>(3, dateTimeTypeConverter),
            IsCompleted = csvReader.GetField<Boolean>(4, booleanTypeConverter),
            ModifiedOn = csvReader.GetField<DateTime>(5, dateTimeTypeConverter),
            RegionId = csvReader.GetField<int>(6)
        };
    }
```

Any suggestion to overcome this issue would be really helpful.

Regards,
Sandeep

**Comment by gmcit** [comment]
I'm also having an issue with this,    
     
**Exception Details: CsvHelper.CsvReaderException: No header record was found.**

   var config = new CsvConfiguration() { HasHeaderRecord = true};

                using (var csv = new CsvReader(new StreamReader(uploadFile.InputStream), config))
                {
                    var details = csv.GetRecords<TrackingFileDetail>().ToList();
                }

**Comment by gmcit** [comment]
I did the same using another CSV helper LumenWorks and it worked.

`using (CsvReader csv = new CsvReader(new StreamReader(uploadFile.InputStream), true))
                {
                    int fieldCount = csv.FieldCount;

                    string[] headers = csv.GetFieldHeaders();
                    while (csv.ReadNextRecord())
                    {
                        for (int i = 0; i < fieldCount; i++)
                        {
                            Console.Write(string.Format("{0} = {1};", headers[i], csv[i]));
                        }

                        Console.WriteLine();
                    }
                }`

I wonder what's the issue with CsvHelper.

**Comment by JoshClose** [comment]
Can you create a new issue and provide more detail on how to reproduce it? That would include sample data that causes the issue.

**Comment by gmcit** [comment]
Hi Josh, Thanks i was able to resolve the issue, it was a mistake on my part since i did some processing on the stream prior to reading it which was causing the error. CsvHelper is working fine. Thanks.

**Comment by nathikoza** [comment]
I know this is an old thread but I got here because I was experiencing the same issue and learned that (well in my case) it had nothing to do with the CsvHelper but the Stream position being at the end.

**Comment by nolme** [comment]
Same problem today. I've post a very short project. As long I can remember, it was working with previous old version (2.x ) : 
[https://wetransfer.com/downloads/e085f9fa6c898b4fcdb4e1ecc12cf69a20180114224621/e64df35e87a7ff8a791b265eb345622020180114224621/7e4e59](url)

**Comment by ankku** [comment]
I followed the suggested solution for the issue above but I am getting the same error on reading stream. What's wrong in the below code:

```
private IEnumerable<Dictionary<string, EntityProperty>> ReadCSV(Stream source, IEnumerable<TableField> cols)
        {
            
                using (TextReader reader = new StreamReader(source, Encoding.UTF8))
                {
                
                    var cache = new TypeConverterCache();
                    cache.AddConverter<float>(new CSVSingleConverter());
                    cache.AddConverter<double>(new CSVDoubleConverter());
                    var csv = new CsvReader(reader,
                        new CsvHelper.Configuration.CsvConfiguration(global::System.Globalization.CultureInfo.InvariantCulture)
                        {
                            Delimiter = ";",
                            HasHeaderRecord = true,
                            CultureInfo = global::System.Globalization.CultureInfo.InvariantCulture,
                            TypeConverterCache = cache
                        });
                    csv.Read();
                    csv.ReadHeader();


                    var map = (
                            from col in cols
                            from src in col.Sources()
                            let index = csv.GetFieldIndex(src, isTryGet: true)
                            where index != -1
                            select new { col.Name, Index = index, Type = col.DataType }).ToList();

                    while (csv.Read())
                    {
                        yield return map.ToDictionary(
                            col => col.Name,
                            col => EntityProperty.CreateEntityPropertyFromObject(csv.GetField(col.Type, col.Index)));
                    }
                
                }
            
        }
```

**Comment by buffdaddy570** [comment]
Hi

> The issue is that `csvItems.Count()` causes all the records to be read, then `@foreach (var info in ViewBag.ImportData)` causes them to be read again. At this point, the stream has already been used up, so strange things start to happen.
> 
> One way to solve this would be to do `var csvItems = csvReader.GetRecords<CsvImportData>().ToList();` instead. Notice the `.toList()` at the end.
> 
> I will have to check into what the right way to fix the library is for this situation.
> 
> Thanks for giving me some example code that reproduces this!

Hi, to let you know, this comment was really helpful in resolving my "No header record found" problem. I needed to set the stream position to zero.
