### ISSUE TITLE
CsvWriter could be faster

### ISSUE THREAD

**Issue by hvdijk** [JoshClose/CsvHelper#760]
I'm using CsvHelper in the generation of a lot of test data for an external system and noticed a few things in CsvHelper itself that could be changed to improve the performance. I see the CsvHelper.Performance test project and the improvements are measurable in that too.

- `Enum.HasFlag` is used, including in `WriteField`. It is a relic from the .NET 1 era when generics didn't exist. It takes its argument as type `Enum`, therefore causes boxing. The one in `WriteField` gets called a *lot*. The total hit on time is small but still measurable, the big impact I'm seeing here in my own program is on memory. I actually wouldn't have expected this to make a difference because .NET's garbage collector is supposed to be pretty good at getting rid of short-lived objects, but still it does.

  Note: while changing this, I found a minor bug. `ReflectionExtensions.cs` contains `type.Attributes.HasFlag( TypeAttributes.NotPublic )`, but this is trivially always true, because `TypeAttributes.NotPublic == 0`. This check should be done using `TypeAttributes.Public` instead.

- `DynamicInvoke` is used. Performance is improved significantly by using `Invoke`, but this requires statically typed delegates. It's possible to make `GetWriteRecordAction<T>` return `Action<T>` with a few changes to how delegates get cached.

- `WriteRecords` takes an `IEnumerable`, there is no generic version taking `IEnumerable<T>`. This one is actually not measurable in the CsvHelper.Performance project because that uses reference types. For value types, `IEnumerable` again requires boxing because its `Current` property is of type `object`.

I've published these changes on [hvdijk/performance](https://github.com/hvdijk/CsvHelper/tree/performance), but they are not in a form appropriate for pull request: they're intentionally split up into separate commits for easier investigation, and besides, they introduce (small) API and ABI incompatibilities, which is probably not a good thing when you're in release candidate stage.

Is there any interest in getting these changes, or something to the same effect, in the official version in some form? If so, is there anything more I can do to help?

**Comment by JoshClose** [comment]
Instead of `Enum.HasFlag`, is using `( type.Attributes & Attributes.Public ) == Attributes.Public` what will speed it up?

**Comment by JoshClose** [comment]
I definitely want to get any breaking changes done now. Otherwise it might be a while before 4.0 is released.

**Comment by hvdijk** [comment]
Yes, using bitwise operators instead of `HasFlag` is the first speed up. I changed all uses of `HasFlag` for consistency, but only the one in CsvWriter.cs was called often enough to matter.

For `type.Attributes`, the code was trying to check for non-public types, since anonymous types are non-public, so it's `== 0`, not `== TypeAttributes.Public`.

I can create pull requests for these if you like, but I'd probably have to wait with the second one until the first one is merged and so on. If it makes things easier, I'd be happy to do that. If you can take them directly, that's also great.

**Comment by JoshClose** [comment]
Btw, there is also huge speed improvements that could be made to the serializer. I may do that too.

**Comment by JoshClose** [comment]
What kind of performance improvements are you seeing for the `DynamicInvoke` change to `Invoke`? I'm seeing 15 seconds down to 13 seconds.

**Comment by JoshClose** [comment]
The serializer speed improvements didn't pan out and slowed things down considerably. Oh well.

**Comment by JoshClose** [comment]
These have all been done and pushed.

**Comment by hvdijk** [comment]
Thanks! Your numbers are close to mine, I was seeing just under 16 s to just under 13 s. That's with the test of 50 columns, the effect is bigger with fewer columns: when reducing it to 10 columns, closer to my real code, and increasing the number of rows to 5x the original, I see a speedup from just over 15 s to just under 10 s.

**Comment by hvdijk** [comment]
I re-tested with what you pushed, but I found one case not working that did work in my branch:

    struct S /* or class */
    {
        public string F1 { get; set; }
        public string F2 { get; set; }
    }
    using( var csv = new CsvWriter( Console.Out ) )
    {
        csv.WriteRecords(new List<S> { new S { F1 = "1", F2 = "2" } });
        csv.WriteRecords(new List<object> { new S { F1 = "1", F2 = "2" } });
    }

This now fails with a wrapped `InvalidCastException` because it attempts to re-use the cached delegate of type `Action<S>` as an `Action<object>`. This was the reason I had modified the delegate caching to allow storing two delegates for each type.

Should I report this as a new bug, or do you want to pick it up as part of this one?

**Comment by JoshClose** [comment]
I'll just do it as a part of this one. I'm going to try and find a way to not use to caches though.

**Comment by JoshClose** [comment]
Fixed. I'm using a single cache but change the key to a string. Doesn't seem to be any performance decrease.
