### ISSUE TITLE
Impossible to implement custom parser

### ISSUE THREAD

**Issue by christophano** [JoshClose/CsvHelper#762]
https://github.com/JoshClose/CsvHelper/blob/ed975f2c4694f9f35cf98441bfea182fbd81b42f/src/CsvHelper/CsvReader.cs#L80

The above line in the `CsvReader` constructor checks that the `parser.Context` is of type `ReadingContext` or it throws an exception. Unfortunately the constructor for `ReadingContext` is internal, so it is impossible for me to create one (without using reflection).

Ideally this should check if it implements `IReaderContext` and if not it should create a default implementation of `IReaderContext` instead of throwing an exception.

**Comment by JoshClose** [comment]
I was planning on releasing this weekend, so I'm glad you caught this now. Let's get all the changes that'll make your life easier in before the release.

**Comment by JoshClose** [comment]
This is one sticky area of all the changes that I really don't like that much, so I'm up for any suggestions. I'm looking over what you suggested and seeing how I can fit that in. I think ideally, `IParser.Context` should only need to implement `IParserContext`.

**Comment by JoshClose** [comment]
One issue with changing `ReadingContext` to `IReaderContext` is that I will need to expose all the property setters and several properties that I didn't want a user to worry about. It would make it possible for someone to really screw some stuff up. Maybe that's OK.

**Comment by JoshClose** [comment]
Would having your context object inherit `ReadingContext` be an option? If you don't want to worry about properties that you don't use/need, you could just override the properites/methods that you want to change and let the default functionality stay the same. I've tried to make everything `virtual` so it can be changed as much or little as you like.

The constructor probably will still need to be made at least `protected` then.

**Comment by JoshClose** [comment]
Any thoughts on making all the `internal` stuff in `ReadingContext` to `public`?

**Comment by christophano** [comment]
I _shouldn't_ need to access anything internal on the `ReadingContext`. My preference would be for `CsvReader` to allow the `IReaderContext` intersect rather than a concrete implementation, but even then I think there's a lot on there that simply doesn't apply to the Excel implementation.

**Comment by JoshClose** [comment]
I could move all the internal properties out and into `CsvReader` itself. I guess it doesn't make sense for them to be on the context if they're internal. The context is a property on the exceptions, and users won't be able to see that stuff anyways.

**Comment by JoshClose** [comment]
I made changes in a new branch for you to test out. Can you let me know if these work for you and what other changes might help you out? https://github.com/JoshClose/CsvHelper/tree/issue-762-changes-for-custom-parser

**Comment by JoshClose** [comment]
Would you be able to look at this by the weekend? I'd like to get the release out and want to make sure it works well for you. I'm working getting as much documentation done, but probably won't be 100% by the time I release.

**Comment by christophano** [comment]
I'll try again tonight, but looking at the commits this should work.
The `CsvReader` and `CsvWriter` now accept the interfaces rather than the concrete implementations, which is perfect. The `ReadingContext` and `WritingContext` classes also have a public class, which means I should be able to use them rather than rolling my own, which is also fantastic - thanks.

**Comment by JoshClose** [comment]
This is in master now and on NuGet as 3.0.0-RC05.
