### ISSUE TITLE
Consider targeting net461 too

### ISSUE THREAD

**Issue by mkasperski** [JoshClose/CsvHelper#763]
Would you consider multitargeting this library to both netstandard2.0 and net461 (or higher)?

At this time, referencing netstandard2.0 libraries in full .NET framework apps still comes with quite a bit of issues, like getting all the ns2.0 reference libraries pulled into output package, version mismatches, required binding redirects, etc. The story is better for netcoreapps, but there's still a lot of us doing 'classic' stuff.

In our case, we're currently stuck on version 3.0.0-beta7, which targets full .net (in addition to netstandard1.3). Later betas started targeting only netstandard1.3 and that's where we had to stop. Looks like we were not the only ones: https://www.nuget.org/stats/packages/CsvHelper?groupby=Version

In one of other issues here you wrote you were not fully sold on targeting NS2.0 only, so this is my vote in favor of adding full framework target too.

**Comment by JoshClose** [comment]
I'll look into what the lowest version I can target without having to put a bunch of `#if` defines all over.

**Comment by jamesbascle** [comment]
I think the only thing there was a need to upgrade to 2.0 for was
SerializableAttribute.

If you just if that you can distribute 1.3 i think

**Comment by JoshClose** [comment]
Looks like I can target net45 with no changes, so I'll probably add that.

**Comment by JoshClose** [comment]
I just pushed RC03 which has a net45 build in it. https://www.nuget.org/packages/CsvHelper/3.0.0-RC03
