### ISSUE TITLE
Writing a list of strings

### ISSUE THREAD

**Issue by eseg81** [JoshClose/CsvHelper#765]
Hi,
I have a list of strings and I want this list to be one record in the csv file, with each element in the list being one field.
I am calling csv.WriteRecord(listOfStrings) but getting the error: 
>Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records? | Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?

Each list should be one record in the file, one line.
How do I achieve this?

I know I can use WriteField for each individual field but am trying to speed up the program by limiting how many method calls are invoked, so attempting to have just one WriteRecord call for the whole row.
Thanks for your time.

**Comment by JoshClose** [comment]
Lots of method calls aren't going to slow you down, so don't worry about that. It's how long the method takes to execute that you need to worry about.

No matter what you do, internally it's just going to call a bunch of write methods too, so there isn't a way to get around that, and it's not going to slow things down either.

Looping through the records and writing a bunch of strings should be fine and be fast.

If you're only dealing with only strings, you could use the `CsvSerializer` directly.

**Comment by eseg81** [comment]
OK thanks, but in any case how do I use WriteRecord with a list of strings as desired above?

**Comment by JoshClose** [comment]
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvWriter(writer))
	{
		var records = new List<List<string>>
		{
			new List<string> { "a1", "a2", "a3" },
			new List<string> { "b1", "b2", "b3" }
		};

		foreach (var record in records)
		{
			foreach (var field in record)
			{
				csv.WriteField(field);
			}
			
			csv.NextRecord();
		}
		
		writer.Flush();
		stream.Position = 0;
		
		Console.WriteLine(reader.ReadToEnd());
	}
}
```

**Comment by eseg81** [comment]
Thanks, but what about using WriteRecord directly on the list of strings?

**Comment by JoshClose** [comment]
What version of CsvHelper are you using?

**Comment by eseg81** [comment]
Do you mean above that I won't get any significant speedup by using WriteRecord on a whole row instead of using WriteField on each individual field in the row?

**Comment by jamesbascle** [comment]
Not just that, but it's not a thing that is supported I believe

**Comment by JoshClose** [comment]
It won't be any faster. You can use the serializer directly if you want to do this though.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvSerializer(writer))
	{
		var records = new List<string[]>
		{
			new [] { "a", "b", "c" },
			new [] { "d", "e", "f" }
		};

		foreach (var record in records)
		{
			csv.Write(record);
		}
		
		writer.Flush();
		stream.Position = 0;
		
		Console.WriteLine(reader.ReadToEnd());
	}
}
```

**Comment by eseg81** [comment]
If using CsvSerializer will speed things up, can you please post an example of its usage? 
It doesn't have a NextRecord method so I can't use it the same way I'd use CsvWriter, using Write instead of WriteRecord.

**Comment by JoshClose** [comment]
It's really not going to speed things up. Make method calls isn't slow. Even when done hundreds of thousands of times. It's only slow if the method is slow. You're not going to see any speed improvements using serializer directly instead of the parser. If your data is in a string array/list format, then you might as well just use the serializer then. The writer's job is to turn class objects into a `string[]` and pass it to the serializer to write.

**Comment by eseg81** [comment]
So how do I use the serializer? since Write is a method of a CsvSerializer object, and the object doesn't have a NextRecord method to write the next row, I can't use it the way I've been using the csv object, if I now make a CsvSerializer object using var csv = CsvHelper.CsvSerializer(file);.

**Comment by JoshClose** [comment]
I gave a full example above.
