### ISSUE TITLE
In multi-thread environment CsvWriter throws CsvHelper.WriterException: An unexpected error occurred. ---> System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by RomanDidenko** [JoshClose/CsvHelper#767]
```cs 
CsvHelper.WriterException: An unexpected error occurred. ---> System.ArgumentException: An item with the same key has already been added.
           at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
           at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
           at CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(Type type)
           at CsvHelper.CsvWriter.CreateActionForObject[T](Type type)
           at CsvHelper.CsvWriter.GetWriteRecordAction[T](T record)
           at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
```

**Comment by JoshClose** [comment]
What version?

**Comment by RomanDidenko** [comment]
3.0.0-RC04

**Comment by JoshClose** [comment]
Crap. ;) I'll look into it.

**Comment by RomanDidenko** [comment]
It seems like I use same instance of Configuration class with different instances of CsvWriter class (via CsvSerializer) that are executed in different threads. As a result, instance of Configuration class is shared between different threads that lead to different kind of exceptions.
I suspect it is not proper use of Configuration class from my side as the class is not thread safe by design.
Maybe it is something to be improved in future.
Feel free to close the issue.
Thanks

**Comment by JoshClose** [comment]
I'll have to think about what I want to do here. Maybe I'll just create a `Copy()` method on the `Configuration`.

**Comment by JoshClose** [comment]
I moved a lot of the stuff into the config to make it more thread safe. I don't want to make `Configuration` thread safe either. It gets accessed way too much and would slow it down a lot.

I don't want to create a copy method either. The starts a long chain of copy methods on other objects too, and it's really easy to forget something when new members are added to a class.

My suggestion if you want to share config files in a multi-threaded environment is to not share them, but create a method that generates a new config to use for each instance. That way you can have the same values for each config, but they will be separate instances.

If you need to update a config in the middle of running for some reason, I could try and help find a solution for that.

**Comment by frg** [comment]
Was this fixed by any chance @JoshClose ? Seems like its is still happening on 3.0.0-RC05

**Comment by JoshClose** [comment]
Are you sharing configs across reader/writer instances?

**Comment by frg** [comment]
Seems like it was simply Nuget cache. RC05 is fine - Thanks @JoshClose
