### ISSUE TITLE
No Support for changing row delimiter

### ISSUE THREAD

**Issue by mikeytinks** [JoshClose/CsvHelper#768]
I have a situation where newline is not the row delimiter for the CSV data being read.
Currently have to pre-parse the whole file to replace existing delimiter with newline so can read in csvhelper.

**Comment by JoshClose** [comment]
Currently it supports 3 options: `\r` `\n` `\r\n`

I'll look into having it support an arbitrary list of line delimiters.

**Comment by JoshClose** [comment]
I've looked into this and I don't think it's a good idea. It will slow down the parser quite a bit. Records are supposed to be separated by a line break of some sort also. I think this is going too far off spec.

**Comment by mikeytinks** [comment]
Thanks for considering this.
I'll go with my work around pre-parser.
