### ISSUE TITLE
Writing to a CSV using a DataTable Problem - Incomplete data but no exceptions

### ISSUE THREAD

**Issue by PaulD2** [JoshClose/CsvHelper#770]
Hi there.

I've been writing DataTable data to a CSV using your Nuget package successfully for some weeks, however, I've found an issue for one DataTable whereby my program executes and completes without exception, but the data is incomplete.  This datatable contains SQL Query strings in some fields.

In basic terms - I might be writing 20 rows but on the 15th row and the 6th field (added by 'WriteField'), the field in question is clipped (incomplete) and no further data appears to be written to the file.  Interestingly, a virtually identical row is inserted without issue, so I believe it can't be anything to do with problems escaping characters or similar.

Without any exceptions generated I'm not sure how best to proceed. 

While debugging - all the way to the end of the Datatable - everything looks in order prior to csv.WriteField() and csv.NextRecord().

I'm wondering where to look next.  Have attached a word doc with further info and screenshots.

Best wishes

Paul
[CSVHelper.docx](https://github.com/JoshClose/CsvHelper/files/1351770/CSVHelper.docx)

**Comment by PaulD2** [comment]
Further information: .......  I experimented by 'parsing' each string value through Regex to try to clean them up using **string clean = Regex.Replace(colString, "[^0-9a-zA-Z]+_", "");**  This has helped the process move on by processing many, many more rows.  However, it still hasn't managed to deliver an acceptable CSV file as the file 'terminates' mid row, with rows still not written.  I will investigate further.

**Comment by PaulD2** [comment]
A final piece of information today.  When cleaning the strings further with string **clean2 = string.Join(" ", Regex.Split(clean, @"(?:\r\n|\n|\r)"));** - removing carriage returns I get still further before encountering a problem.  Strangely these often don't cause any issue.  Happy to share my SQL table with you (only around 50 records) if you'd like to test it yourself.

**Comment by JoshClose** [comment]
Are you flushing your `TextWriter`? after you write, you need to make sure the `TextWriter` gets it's data flushed. Calling [TextWriter.Flush](https://msdn.microsoft.com/en-us/library/system.io.textwriter.flush(v=vs.110).aspx) will do it. Also if your `TextWriter` and `CsvWriter` is wrapped in a `using` block, it will be flushed automatically at the end of the `using` block.

**Comment by PaulD2** [comment]
Many thanks for your help Josh.  I enclosed the CsvWriter within a using block and it's fixed the issue for me.

Its a great package to have and I'm very grateful for your help. 

Cheers

Paul

**Comment by JoshClose** [comment]
You're welcome!
