### ISSUE TITLE
TypeConverter to a nullable

### ISSUE THREAD

**Issue by InsidiousForce** [JoshClose/CsvHelper#772]
I'm trying to convert a tri-state boolean to a bool? field.

Unfortunately, the csv data has data like true,false,false,null,false - that is they have the word null for null fields. It's beyond aggravating.

Anyway, string fields, I was able to put together a typeconverter:

```
        public class NullableCsvStringConverter : StringConverter
        {
            public NullableCsvStringConverter()
            {
            }

            public override object ConvertFromString(string text, IReaderRow row, MemberMapData memberMapData)
            {
                return base.ConvertFromString(text == "null" ? string.Empty : text, row, memberMapData);
            }

            public override string ConvertToString(object value, IWriterRow row, MemberMapData memberMapData)
            {
                var text = value as string;
                return base.ConvertToString(text == "null" ? string.Empty : text, row, memberMapData);
            }
        }
```

and then I use it like this:

```
                var nullableCsvStringConverter = new NullableCsvStringConverter();
                Map(m => m.Email).Name("email").TypeConverter(nullableCsvStringConverter);
```

I tried to do the same thing with BooleanConverter and remove the null and replace it with string.empty then pass it to the base class, but it throws errors in BooleanConverter when it's empty rather than mapping to the bool? in my data object.

Am I going about this the right way? Maybe there's another place I can hook in to rewrite _all_ columns with null as string.empty regardless of type before they get processed by the regular converters that detect type?

**Comment by InsidiousForce** [comment]
Now that I'm looking into the source for nullableconverter I'm thinking maybe there's a way to set global TypeConverterOptions for all conversions for TypeConverterOptions.NullValues ?

**Comment by JoshClose** [comment]
```cs
csv.Configuration.TypeConverterOptionsFactory.GetOptions<string>().NullValues.Add( "null" );
```

**Comment by InsidiousForce** [comment]
Thanks sorry, I just found these tests (I guess being lazy):

csv.Configuration.TypeConverterOptionsFactory.GetOptions<string>().NullValues.Add( string.Empty );
var records = csv.GetRecords<Test>().ToList();
csv.Configuration.TypeConverterOptionsFactory.GetOptions<string>().NullValues.Add( "null" );

Will that cover all types or just fields mapped to strings?

**Comment by InsidiousForce** [comment]
Help much appreciated, missed this in configuration.

**Comment by JoshClose** [comment]
Just strings. So any member that is a string. 

You can set that directly on a map also.

```cs
Map( m => m.Name ).TypeConverterOption.NullValues( string.Empty );
```

**Comment by JoshClose** [comment]
It should work for any nullable type though.

**Comment by JoshClose** [comment]
The release is coming very soon, and along with that, new documentation. :)

**Comment by InsidiousForce** [comment]
I know I shouldn't be chatty in issues, especially closed issues heh, but I want to say I've had zero issues with the RC04/RC05 with this .NET Core bulk importer project I've been working on, no performance issues, etc. Only issue I've experienced is with documentation/examples and you seem to be aware of that and want to make it better. And your issue response time is amazing. Thanks so much for all your good work, and now I'll shut up

**Comment by JoshClose** [comment]
lol, no worries. Ask as many questions as you like. I don't have the docs for the next version up yet, so it's completely understandable. You're actually looking at source and unit tests, so you're way ahead of most people anyways.

**Comment by JoshClose** [comment]
I had all the feature done a couple of weeks ago and was going to release, and a person that uses this library to build another had some concerns about extensibility, so I had to make some changes regarding that. A few other things came in during that time also. Basically I just want to have some base documentation up. I'm planning on releasing this weekend. I can continue updating docs nightly after the release, so I'm not really concerned about the docs being complete.
