### ISSUE TITLE
Is there any interest in doing a VB.NET version of this?

### ISSUE THREAD

**Issue by jgiudice** [JoshClose/CsvHelper#774]
I am new to using GitHub and the tools here. I recently came across CsvHelper when looking for ways to help in a VB.Net app I am writing. (I am experienced with VB.NET). I was wondering if folks would be interested in a version of this in VB. Should be fairly straightforward to translate from C#.

Also, I would welcome any guides or tips on working with GitHub and NuGet tools. Thanks for any and all suggestions.
John G.

**Comment by JoshClose** [comment]
I don't think there is any use to having the source code in VB.NET. Having documentation examples in VB.NET would definitely be useful. I will need to add in the ability in the docs to have multiple languages shown though. http://joshclose.github.io/CsvHelper/

**Comment by JoshClose** [comment]
If you have any specific questions on git, github, or nuget, I'd be more than happy to answer them. For general usage I would suggest looking at the docs for each of those. They're pretty thorough.

**Comment by jgiudice** [comment]
Thanks, I am going through the documentation on NuGet and GitHub now to learn more. If you want any help on the documentation examples for VB developers, I would be interested in helping.

**Comment by JoshClose** [comment]
Great! I would definitely like some help. I will need to add a language toggle first. I'll let you know when everything is ready.

**Comment by jgiudice** [comment]
Sounds good.

**Comment by JoshClose** [comment]
I'm leaving this open so I don't forget to do the multiple language thing.

**Comment by SimonCropp** [comment]
3 years later. is this still worth doing? IMO it is not

**Comment by JoshClose** [comment]
I would need to build it into the doc system and someone would have to do all the VB code and update it when any of the C# code updates. I don't think it'll ever happen.
