### ISSUE TITLE
Writing anonymous types

### ISSUE THREAD

**Issue by igitur** [JoshClose/CsvHelper#778]
Hi

I have an `IEnumerable` (the non-generic version) being returned from a class. Previously I was able to use `CsvWriter.WriteRecords` to write it. https://github.com/JoshClose/CsvHelper/commit/38a82dbcd862a0aabd56cd9c09746715d62d4a0c broke that.

Is it possible have both `WriteRecords(IEnumerable records)` and `WriteRecords<T>( IEnumerable<T> records )` ?

thanks

**Comment by JoshClose** [comment]
Ah crap... This will be a breaking change, but I think that's OK if it's been less than 24 hours?

**Comment by igitur** [comment]
Breaking a breaking change is probably not too bad.

**Comment by JoshClose** [comment]
I'd consider this a bug for sure.

**Comment by JoshClose** [comment]
Fixed and pushed. 3.1.1 on nuget.
