### ISSUE TITLE
ICsvWriter/ICsvReader rename missing from release notes for version 3.1.0

### ISSUE THREAD

**Issue by stansellick** [JoshClose/CsvHelper#779]
As per title, the renaming of ICsvReader and ICsvWriter to IReader and IWriter respectively, is missing from the release notes. Should probably be in there under breaking changes?

https://github.com/JoshClose/CsvHelper/commit/4842ef079682c9f753c26f817a8ef46a99d946b9

**Comment by ronaldbarendse** [comment]
Same with the rename of `CsvClassMap` to `ClassMap` (including inherited classes) and signature of the `AutoMap` function...

As per SemVer specification, these changes would require a new major version, since they are incompatible API changes.

**Comment by JoshClose** [comment]
@ronaldbarendse I'm confused. It went from version 2.x to 3.x.

**Comment by JoshClose** [comment]
I added the items to the breaking changes in the change log for 3.0.

**Comment by ronaldbarendse** [comment]
Great to see the updated change logs! Makes upgrading a lot easier 👍 

I hadn't checked what version this was changed (assumed 3.1.0 from the issue title). Now I see this was updated in 3.0.0, so blame me for reiterating known knowledge!

**Comment by JoshClose** [comment]
There was another breaking change, so it's on 4.x now. Change log updated
