### ISSUE TITLE
Implement escaping method or class for the common CSV vulnerabilities

### ISSUE THREAD

**Issue by NikolayIT** [JoshClose/CsvHelper#781]
There are well-known CSV security problems, described in http://georgemauer.net/2017/10/07/csv-injection.html. It would be very nice to have some kind of escaping mechanism in CsvHelper for these vulnerabilities.

**Comment by JoshClose** [comment]
This exists. :)

http://joshclose.github.io/CsvHelper/writing#injection-warning
http://joshclose.github.io/CsvHelper/configuration#malicious-injection-protection

**Comment by JoshClose** [comment]
George Mauer was actually the person that helped me with the details of this feature.

**Comment by chucklu** [comment]
http://joshclose.github.io/CsvHelper/writing#injection-warning was locate in new url https://joshclose.github.io/CsvHelper/examples/writing/
