### ISSUE TITLE
Verions 2.16 vs 3.2

### ISSUE THREAD

**Issue by dustinbartlett** [JoshClose/CsvHelper#783]
I have a file I was reading in using Read() and GetRecord<SimpleClass>() in 2.16 with no issues.  SimpleClass is just some string and integer properties with names that match the file headers except for case.  I made what I thought was all the appropriate code changes required by 3.2.  Added an appropriate PrepareHeader method (which got a field index lookup I needed to do working), updated some methods to new versions/locations etc. I also kept getting the header row as my first row.  Updated it to do an initial Read() followed by a ReadHeader() to get around that.  Is this the expected solution for that issue?

The issue I haven't been able to get around is when I call GetRecord on the first data row of the file it calls my PrepareHeader method twice for each column in the file.  Alternating between passing in the value from the row and the name of the first property in the SimpleClass.  At the end of that I then get an exception saying "Header matching [FirstProperty] names at index 0 was not found."  Same result if I don't try and iterate the file myself and just use GetRecords<SimpleClass>().

Any incite into what I'm doing wrong?

**Comment by JoshClose** [comment]
Yes, you need to call `Read()` then `ReadHeader()`. This is so you can do other things on the header row if needed.

`PrepareHeaderForMatch` getting called multiple times is a bug.

**Comment by JoshClose** [comment]
Actually, I'm wrong. It call that method for both the header and the property name before it checks if they are equal, so it's ok.

**Comment by JoshClose** [comment]
This method here shows what's going on.

https://github.com/JoshClose/CsvHelper/blob/839f46d292cecca27cf2ff1748698cade06f1af8/src/CsvHelper/CsvReader.cs#L1207

**Comment by JoshClose** [comment]
I was able to reduce the number of calls. It will now only be called once for every header row and once for each name in the `GetField` call.

**Comment by JoshClose** [comment]
I can't decide if this is a bug or a feature. lol I was working properly before, just needless calls, so I guess it's a feature.

**Comment by dustinbartlett** [comment]
Glad that improvement could be made, but I still have the issue where the GetRecord call isn't working for me.  I always get an exception saying "Header matching [FirstProperty] names at index 0 was not found."  Is there some extra code required to get an auto mapping that worked in version 2 to work in version 3?

**Comment by JoshClose** [comment]
Can you give me example code the reproduces the issue?

**Comment by dustinbartlett** [comment]
I'll try to strip my code down to something that can be posted that demonstrates the issue this afternoon.

**Comment by dustinbartlett** [comment]
I had a bug in my code that was calling the ReadHeader method multiple times. Fixing that and realizing I was working with a complete file instead of a partial file along with the delegates added for handling reading or parsing errors meant I could use the GetRecords method. It's all working great and taking a 3rd the time it was before.

**Comment by JoshClose** [comment]
Nice! Your bug pointed out an inefficiency that got corrected too. :)
