### ISSUE TITLE
csv.GetRecords returns nothing

### ISSUE THREAD

**Issue by corbo1523** [JoshClose/CsvHelper#784]
Hi,
I am having trouble getting my records back from GetRecords, i am new to your code so i am sure i am doing something wrong but unsure what,

my project is a VB.NET 4.5 windows forms application, i am trying to read in a CSV with a list of vehicles in and add them to the system,

i have created a class with the properties which i need, these property names are identical to the headers in the CSV

I am assuming that its probably an issue with a column or row of data in the CSV but cannot locate it.

```
 Using fileReader = File.OpenText(OpenFileDialog1.FileName)
            Try
                Using csv = New CsvHelper.CsvReader(fileReader)
                    'csv.Read()
                    'csv.ReadHeader()
                    'csv.ValidateHeader(Of DMSVehicle.UsedVehicleImportCl)()
                    Dim records = csv.GetRecords(Of DMSVehicle.UsedVehicleImportCl)
                    'Dim vehicle As New DMSVehicle.ImportExport
                    BackgroundWorker1.RunWorkerAsync(records)
                End Using
            Catch ex As Exception
                MsgBox(ex.Message)
            Finally
            End Try
        End Using
```
Please can you help

**Comment by corbo1523** [comment]
fixed this by adding a ToList() to the GetRecords line haha

**Comment by JoshClose** [comment]
> The most common scenario is using one of the `GetRecords` methods. You can specify the type of object you want returned, and it will return an `IEnumerable` that will `yield` results. This means when iterating the results, only a single record will be in memory at a time, instead of the entire file. Records aren't pulled until you actually start iterating the results.

http://joshclose.github.io/CsvHelper/reading#getting-all-records

So `ToList()` will pull it all into memory at once. If you iterate the records through looping or the iterator, you'll only have one record in memory at a time.

**Comment by corbo1523** [comment]
Thanks for your reply,

i ended up doing this 
 ```
 Dim records = csv.GetRecords(Of DMSVehicle.UsedVehicleImportCl).ToList
                    'Dim vehicle As New DMSVehicle.ImportExport
                    BackgroundWorker1.RunWorkerAsync(records)
```

```
 Dim records As IEnumerable(Of DMSVehicle.UsedVehicleImportCl)
        Dim import As New DMSVehicle.ImportExport
        records = e.Argument
        Dim recordCount As Integer = records.Count
        Dim i As Integer = 0
        SplashScreenManager.Default.SendCommand(DmsControls.DmsProgressControl.SplashScreenCommand.SetMax, recordCount)
        For Each rec As DMSVehicle.UsedVehicleImportCl In records
            i += 1
            SplashScreenManager.Default.SendCommand(DmsControls.DmsProgressControl.SplashScreenCommand.SetProgress, i)
            importResults.Add(import.ImportUsedStockData(rec))
        Next
```

this works but is this the correct approach or should i be able to call GetRecords() without the tolist()?

**Comment by JoshClose** [comment]
I see the issue here. The `IEnumerable<T>` that is returned from `GetRecords<T>` is forward only. Once it reaches the end, it's done and you can't start reading from it again. Doing `records.Count` like you have there will cause the whole file to be read in to be able to do the count. Then you're looping the records, but the `TextReader` that was passed to `CsvReader` has already been exhausted. In your case, you'll need to do the `ToList` so it's all in memory and you can then run as many projections on it as you like.

**Comment by corbo1523** [comment]
Thanks for the advice Josh, Great work on the package
