### ISSUE TITLE
Provide option for `Name` method for class mappings to be case-insensitive

### ISSUE THREAD

**Issue by alexreg** [JoshClose/CsvHelper#787]
Something like:

```
public sealed class FooClassMap : ClassMap<Foo>
{
	public FooClassMap()
	{
		Map(v => v.Foo).Name(true, "foo"); // Just matches "foo".
		Map(v => v.Bar).Name(false, "foobar"); // Matches "foobar", "Foobar", "FooBar", etc.
	}
}
```

Alternatives could be passing a `StringComparer` / `IEqualityComparer<String>` to the method, optionally.

Would something like this be possible?

**Comment by JoshClose** [comment]
You have some options to do that currently. 

The signature of `Name` is `Name( params string[] names )`. You can pass as many names as you want in to match. 

Another option is to use `PrepareHeaderForMatch`. This method is called on the header name and member name before checking if they are the same. If you want all headers to be case insensitive, you can do something like `ToLower()` or `ToUpper()`. You can also remove characters like whitespace or underscores.

**Comment by alexreg** [comment]
`PrepareHeaderForMatch` does the trick, I think. Thank you.

**Comment by michaelmmcrae1** [comment]
To be clear, Doing `ToLower` in `PrepareHeaderForMatch` would not solve the problem by itself.
You would need to use that along with doing `.Name("nameofproperty")`
