### ISSUE TITLE
Allow class mappings to be generated for public fields

### ISSUE THREAD

**Issue by alexreg** [JoshClose/CsvHelper#788]
This is useful for binding to a struct with public fields rather than (public) properties, and I suspect would be quite a common scenario. When I tried, it failed for me, complaining of no class mapping being found.

**Comment by JoshClose** [comment]
You can do this in configuration.

```cs
csv.Configuration.MemberTypes = MemberTypes.Fields;
```

This is a `flags` type, so you can specify both if you want.

**Comment by alexreg** [comment]
Oh, I wasn't aware of that, thanks!
