### ISSUE TITLE
Dynamic or Generic Type Mapping Possible?

### ISSUE THREAD

**Issue by matthewpomar** [JoshClose/CsvHelper#792]
I have created a custom mapping for `Account`:

    public class AccountMap : ClassMap<Account>
    {
        public AccountMap()
        {
            AutoMap();
            Map(m => m.Key).Ignore();
        }
    }

Basically, this will map all fields, and exclude 'Key'. I'm using like so:

    using (var stream = new MemoryStream())
    using (var reader = new StreamReader(stream))
    using (var writer = new StreamWriter(stream))
    using (var csv = new CsvHelper.CsvWriter(writer))
    {
        csv.Configuration.RegisterClassMap<AccountMap>();
        csv.WriteRecords(batchedRecords);
        writer.Flush();
        stream.Position = 0;
        content = reader.ReadToEnd();
    }

However, `Account` is just one of many entities that we will be creating CSVs for. Is there a way to create a dynamic or generic mapping that ignores the `Key` field so I don't have to do a bunch of `if` `else` blocks?

For example, I want to avoid this:

    if(source == "Account") 
    {
        csv.Configuration.RegisterClassMap<AccountMap>();
    }
    else if(source == "Lead")
    {
        csv.Configuration.RegisterClassMap<LeadMap>();
    }

`source` is the table name of the Entity Framework entity.

**Comment by JoshClose** [comment]
If all of your classes are auto mapped and you only want to exclude that single property, maybe using the attribute `[Ignore]` on that property instead of using a class mapping. You wouldn't need to register a class map then either.

**Comment by eahsan89** [comment]
But in my case classes are not auto mapped , how can i register as generic ?

**Comment by JoshClose** [comment]
Can you create a new issue and include more details?

**Comment by seewaldchris** [comment]
For anyone who may happen upon this 4 years later, this is the generic implementation I'm using to generate a byte array of the csv.
```

public static byte[] WriteIEnumerableToCsvByteArrayWithMap<T, U>(IEnumerable<T> list, U map) where U : ClassMap<T>
        {

            using (var stream = new MemoryStream())
            {
                using (var writer = new StreamWriter(stream))
                using (var csv = new CsvWriter(writer, CultureInfo.InvariantCulture))
                {
                    csv.Context.RegisterClassMap<U>();
                    csv.WriteRecords(list);
                }
                return stream.ToArray();
            }

        }

```
