### ISSUE TITLE
Excel libary

### ISSUE THREAD

**Issue by kendallb** [JoshClose/CsvHelper#793]
Hi Josh,

I have been using CsvHelper for years and wrote my own port of the code from and older version of CsvHelper years go to support Excel using the Component One libraries. I recently re-wrote it to support OpenXML Excel files using the ClosedXML library and thought you might be interested:

https://github.com/kendallb/ExcelHelper

One thing I could use help with is I have never build a NuGet package before. Any change you can help me figure out how to get this on NuGet?

**Comment by kendallb** [comment]
I figured it out and it is published now ;)

**Comment by JoshClose** [comment]
Sweet! I have some some bat files in source `Pack NuGet Packages.bat` and `Push NuGet Packages.bat` that I use.

There is another library that does something similar too, if you haven't seen it yet. https://github.com/christophano/CsvHelper.Excel

**Comment by kendallb** [comment]
Yeah the CsvHelper.Excel library is not as useful because you don't get full control over the resulting Excel file such as the ability to do bold headers and control cell formatting using excel native formatting. 

I had been wanting to release it as Open Source for a long time but the Component One library is commercial, so now it has been re-written to use ClosedXM it is all open source :)

**Comment by JoshClose** [comment]
Nice!
