### ISSUE TITLE
Unable to change quote value

### ISSUE THREAD

**Issue by julian-goldsmith** [JoshClose/CsvHelper#794]
I've been using CsvHelper to read and write oddly-formatted CSV files that use a tilde ('~') as quotes.

In CsvHelper 2.16.3, I was able to set the quote value to a tilde using the Quote property on the CsvConfiguration class.  The new IWriterConfiguration class doesn't allow the Quote property to be set.

Is there a way for me to set the Quote property on a CsvWriter in CsvHelper 3.4.0, or is there a reason why users shouldn't be allowed to?

**Comment by JoshClose** [comment]
Oh man... ok. Changing coming soon.

**Comment by JoshClose** [comment]
Fixed and in 4.0.0 on NuGet.

**Comment by julian-goldsmith** [comment]
Excellent, thank you for the quick response.

**Comment by JoshClose** [comment]
Thanks for giving me a reproducible unit test!

**Comment by JoshClose** [comment]
It's 4.0.1 now... I realized that I didn't change the file and assembly version to 4.0.0.0 so release 4.0.0 isn't on NuGet anymore.
