### ISSUE TITLE
Mapping column to a FK in another entity

### ISSUE THREAD

**Issue by drewlsvern** [JoshClose/CsvHelper#801]
This is more of question then an issue. Just curious what the recommended way of pulling in a FK value based on the column value from the csv I want to import.

For example:
FirstName LastName Address
John          Doe           103 Some Rd.

The address actually matches an existing record in an Address table, I just want to pull out the id from that table and map that value.

**Comment by JoshClose** [comment]
I'm confused. You have a single CSV file that has a person and an address. Then you have 2 tables in a database, something like Person and Address. You want to find the ID in the database that matches the row in CSV?

**Comment by drewlsvern** [comment]
Yes, that is correct.

**Comment by JoshClose** [comment]
Is the foreign key in the CSV row?

**Comment by drewlsvern** [comment]
Yes, sorry I kind of explained that wrong.

**Comment by drewlsvern** [comment]
It doesn't even really have to be specific to a database. 

For example, for any given column I want to take the value from the csv, run it through a function and have it do something based on that value and give me a return value.

**Comment by JoshClose** [comment]
Are you creating a list of class objects in the end? Is the value returned from this function going to be set to a property of a class object that represents a row? I'm still not understanding your end goal.

**Comment by drewlsvern** [comment]
Yes, I am creating a list of class objects in the end and the value returned from this function will be the value that is saved as a property of a class object.

**Comment by JoshClose** [comment]
You can either use a custom type converter, which is a little more involved, or you can use `ConvertUsing` in your mapping. `ConvertUsing` will allow you to do anything you want. If you think you need  custom type converter, let me know and I can help with that.

Here is the `ConvertUsing` docs. http://joshclose.github.io/CsvHelper/mapping#convertusing

**Comment by drewlsvern** [comment]
Perfect thanks. I took a brief look at that, I'll take a closer look and have a look at the tests to have a better understanding of how it works.

**Comment by JoshClose** [comment]
Can you open a new issue and provide some code examples?

**Comment by alvinchesaro** [comment]
Hi, I have a challenge importing the foreign key column of my CSV file.

**Comment by alvinchesaro** [comment]
Hi Josh,
Similar issue, more or less. I have several foreign key fields, CountyId, SubCountyId, WardId and VarietyId, they link to county, subcounty etc. tables, obviously. Now, I have HeaderValidated as null, MissingFieldFound = null how can I use convert to link the foreign key entries? Right now with the code below, the foreign key entries are not mapped and my related tables end up having new values inserted.

```
List<Farmer> farmers = new List<Farmer>();

            #region Read CSV

            var path = $"{Directory.GetCurrentDirectory()}{@"\wwwroot\files"}" + "\\" + fileName;
            var conf = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HeaderValidated = null,
                MissingFieldFound = null,
        };
            using (var reader = new StreamReader(path))
            using (var csv = new CsvReader(reader, conf))
            {                
                csv.Read();
                csv.ReadHeader();
                while (csv.Read())
                {
                    var farmer = csv.GetRecord<Farmer>();
                    farmers.Add(farmer);
                }
            }
            return farmers;
```
My csv file looks like this:
[27TH APRIL 2022Single.csv](https://github.com/JoshClose/CsvHelper/files/8629802/27TH.APRIL.2022Single.csv)
