### ISSUE TITLE
CR LF line endings missing since upgrade to 4.0.0

### ISSUE THREAD

**Issue by slacksi** [JoshClose/CsvHelper#802]
I recently upgraded from CsvHelper 2.16.3 to 4.0.0.  Since the upgrade, records written to a CSV file no longer have a line ending.  Before the upgrade, they had a CrLf line ending, like:
![image](https://user-images.githubusercontent.com/19539956/31811312-0cb92662-b577-11e7-9d9b-8a1d431d4d67.png)

This is the code:
```
public Setup(IHostingEnvironment env)
{
    var filePath = env.ContentRootFileProvider.GetFileInfo(_filename).PhysicalPath;
    _streamWriter = new StreamWriter(filePath, true)
    {
        AutoFlush = true
    };
    _csvWriter = new CsvWriter(_streamWriter);
    _csvWriter.Configuration.RegisterClassMap<LoggableRequestMap>();
}

public void SaveRequest(LoggableRequest request)
{
    if (request == null)
        throw new ArgumentNullException(nameof(request));

    _csvWriter.WriteRecord(request);
}
```
Did I do something wrong or is there a bug here?

**Comment by JoshClose** [comment]
If you're using anything but `WriteRecords( IEnumerable )`, you'll need to call `NextRecord` after you're done writing.

**Comment by JoshClose** [comment]
I'm considering doing this by default and having a configuration for turning it off. This is tripping up a lot of people.
