### ISSUE TITLE
No members are mapped for type

### ISSUE THREAD

**Issue by drewlsvern** [JoshClose/CsvHelper#805]
I must be missing some configuration step, but I can't seem to figure it out. I've tried creating a ClassMap class but I keep receiving "No members are mapped for type". If I just map from a POCO it works fine.

```
public class MyClass
{
            public string StreetNumber { get; set; }
            public string StreetName { get; set; }
            public string StreetType { get; set; }
}

public class MyClassMap : ClassMap<MyClass>
        {
            public MyClassMap()
            {
                Map(m => m.StreetNumber).Name("STREET NUMBER");
                Map(m => m.StreetName).Name("STREET NAME");
                Map(m => m.StreetType).Name("STREET TYPE");
                
            }
        }


var csvReader = new CsvReader(stream);                
                
csvReader.Configuration.RegisterClassMap<MyClassMap>();
var records = csvReader.GetRecords<MyClassMap>().ToList();
```

**Comment by JoshClose** [comment]
When you call `GetRecords` you want to specify the type you want back, not the mapping type. So `GetRecords<MyClass>` instead of `GetRecords<MyClassMap>`. `RegisterClassMap` requires the mapping type.

**Comment by drewlsvern** [comment]
Oh wow, I feel so dumb. I knew it was going to be something simple I overlooked. Thanks for your help.
