### ISSUE TITLE
WriteRecord not working in version 4.0.2

### ISSUE THREAD

**Issue by kadyrkulovr** [JoshClose/CsvHelper#807]
I updated csvhelper from 2.16.3 to last stable version 4.0.2.

this code works fine:
```
var items = new List<Simple>
{
    new Simple { Id = 1, Name = "one" }
};

csv.WriteRecords(items);
writer.Flush();
ms.Position = 0;

var data = reader.ReadToEnd();
```

this code returns empty string:
```
var items = new List<Simple>
{
    new Simple { Id = 1, Name = "one" }
};

foreach (var item in items)
{
    csv.WriteRecord(item);
}
writer.Flush();
ms.Position = 0;

var data = reader.ReadToEnd(); // <--empty
```

**Comment by jamesbascle** [comment]
You need to either manually call nextrecord, or use the configuration
setting that makes you not have to I believe.

**Comment by JoshClose** [comment]
That config setting doesn't exist yet. I'm debating creating one and turning it on by default.

**Comment by JoshClose** [comment]
This config setting doesn't really make sense. You may want to call `WriteRecord` multiple times with different objects. There would be no way to determine when `NextRecord` would need to be called.
