### ISSUE TITLE
Mapping Multiple Navigation-Reference properties of same type

### ISSUE THREAD

**Issue by bborad** [JoshClose/CsvHelper#814]
Hi 

I am trying to map multiple navigation properties of same entity type but it seems to be mixing it up. 

Entity Structure

```c#
Schedule{
   string code;
   string description;
   int createdid;
   date createdts;
}

Site{
  int siteid;
  string namel
  int PrimaryScheduleID;
  int SecondaryScheduleID;

  public Schedule PrimarySchedule;
  public Schedule SecondarySchedule;
}

 var t = typeof(Site)

 var ps = DefaultClassMap<Schedule>();
 var r = new MemberReferenceMap(t.GetProperty('PrimarySchedule'), ps);

 var rm = MemberMap.CreateGeneric(typeof(Schedule), typeof(Schedule).GetProperty('code'));
 rm.Data.Names.Add('PrimaryScheduleCode);
 r.Data.Mapping.MemberMaps.Add(rm);

 var rm = MemberMap.CreateGeneric(typeof(Schedule), typeof(Schedule).GetProperty('description'));
 rm.Data.Names.Add('PrimaryScheduleDescription');
 r.Data.Mapping.MemberMaps.Add(rm);

 //this is in for loop for every navigation property
 var ps = DefaultClassMap<Schedule>();
 var r = new MemberReferenceMap(t.GetProperty('SecondarySchedule'), ps);
 var rm = MemberMap.CreateGeneric(typeof(Schedule), typeof(Schedule).GetProperty('code'));
 rm.Data.Names.Add('SecondaryScheduleCode');
 r.Data.Mapping.MemberMaps.Add(rm);
```

This creates 2 Reference Member which is correct but both has all of these 3 properties in their member mapping, which is incorrect. 

Test.csv
---------------
```csv
SiteName, PrimaryScheduleCode, PrimaryScheduleDescription, SecondaryScheduleCode
ssaaa, A-1 Part B, A-1 Part B, A-4 Part B
```

what it reads is 

```json
  "PrimarySchedule":{  
      "ScheduleCode":"A-4 Part B",
      "ScheduleDescription":"A-1 Part B",
      "CreatedTS":"2017-10-27T06:35:15.2769414Z",
      "CreatedID":-1,
      "ScheduleID":0,
    }
 "SecondarySchedule":{  
      "ScheduleCode":"A-4 Part B",
      "ScheduleDescription":"A-1 Part B",
      "CreatedTS":"2017-10-27T06:35:15.2769414Z",
      "CreatedID":-1,
      "ScheduleID":0,
 }

```

**Comment by JoshClose** [comment]
I'm going to publish a new version that will make some of this easier before I give you an answer. It will be in the next day here.

**Comment by bborad** [comment]
Go it working, Issue was in my code. I was adding using same instance object inside loop to add memberMap and then add that instance into main ReferenceMap collection. I moved instance creation inside loop so it creates new instance of every navigation property.

**Comment by bborad** [comment]
would still like to see new version with easier way to add reference mapping.

**Comment by JoshClose** [comment]
I can't see a way to make doing reference mapping dynamically any easier. You need to specify the `MemberInfo` for every property. It would need to require you to give a stack of `MemberInfo`s or something. With normal mapping you can do `Map( m => m.A.B.C.Id )` and it will create the entire chain for you.

**Comment by JoshClose** [comment]
I'm making it so when doing a runtime mapping you'll still be able to do `.Name( "name" )`, etc. That should help some since there are some other things that happen with setting those, and you really shouldn't be setting `.Data.` properties by hand.

**Comment by bborad** [comment]
Thanks for that.

**Comment by JoshClose** [comment]
Done and will be in next version.
