### ISSUE TITLE
TypeConverterException is missing current field information

### ISSUE THREAD

**Issue by DarkDaskin** [JoshClose/CsvHelper#818]
When type conversion throws an exception in a `GetRecord<T>()` call, where is no information about which field caused the exception. The `ReadingContext.Field` is empty when the exception occurs.

Probably you should extend `TypeConverterException` with current `MemberMapData` or some other information which will allow to identify which field could not be converted.

**Comment by JoshClose** [comment]
Is your exception message `The conversion cannot be performed.`?

**Comment by DarkDaskin** [comment]
Yes. 
As a workaround I just defined my own converters which include `MemberMapData` into thrown exceptions, but it would be nice to have this feature out-of-the-box.

**Comment by JoshClose** [comment]
There is a commit that hasn't made it to NuGet yet that changes that message to this:

```cs
var message =
	$"The conversion cannot be performed.\r\n" +
	$"    Text: '{text}'\r\n" +
	$"    MemberType: {memberMapData.Member?.MemberType().FullName}\r\n" +
	$"    TypeConverter: '{memberMapData.TypeConverter?.GetType().FullName}'";
```

Does that cover your situation?

**Comment by DarkDaskin** [comment]
No. It still does not contain field name. Even if it did, it feels wrong to parse exception message, I'd prefer to get the value directly, so I can build my own human-friendly error message.

Also I would like to have `Text` property on the exception for convenience. This is optional because text can be extracted from `ReadingContext` when `MemberMapData.Index` is known.

So I think the exception should look as follows:

    public class TypeConverterException : CsvHelperException
    {
        public string Text { get; }
        public MemberMapData MemberMapData { get; }
    
        // Constructors skipped...
    }

**Comment by JoshClose** [comment]
Sure. I can add that.

**Comment by JoshClose** [comment]
Done.
