### ISSUE TITLE
Custom Expressions

### ISSUE THREAD

**Issue by ajorkowski** [JoshClose/CsvHelper#821]
Unfortunately with the upgrade to 3/4 of CsvHelper, the internals have changed enough so that it is pretty much impossible to do custom expression work.

Here is my example (and maybe there is a cleaner way to deal with this) - I have IEnumerables (of objects) in my data and to make them come out nicely in the csv I use a custom attribute to specify how many copies of the items I want. So for example if I had an object with two properties (Name/Code) and the attribute has a count of 4, then I will output 8 fields in total (with headers and everything).

How I went about implementing it before is in two areas:

1) Create a custom class map, and during the automap phase if I detect the attribute then instead of creating an IEnumerableConverter, I instead just create N reference maps equal to the loop amount (using a custom class map to track the index), and the reference map uses the type definition of the IEnumerable. We also add some prefixing here so that the output will have some indexes in the headers.

2) If I just use the above then of course I will get an error during the mapping, since the reference map would be trying to map members on top of the IEnumerable<T> (not just T itself), so the second step was to overwrite the expression code to add in something like {IEnumerable<T>}[index] in the expression, so that the members would be accessing from the right type.

I managed to make the relevant changes in v4, however I have a problem with actually being able to use my overwritten `ExpressionManager` class. There are a large number of nested classes that makes it basically impossible to inject the custom class:

`ExpressionManager` -> `ObjectRecordWriter` (built in constructor of RecordWriter) -> `RecordWriterFactory` (built in factory method) -> `RecordManager` (built in constructor) -> `CsvWriter` (built in constructor).

Apart from the objects being built in the constructor (so you can't change the implementation), the `RecordWriterFactory.MakeRecordWriter<T>` method is not virtual so again not possible to change the implementation.

Perhaps there are enough 'components' that it would be worth inverting all the dependencies and building a central container - that way it is easier for someone like me to replace components easily? I've already spent the time in my code updating this, so I would really prefer to not have to roll back my csvhelper version... I might try pushing up a PR with a possible implementation.

**Comment by JoshClose** [comment]
Did you see `CsvHelper.ObjectResolver`? Maybe that can be utilized to help this also. I'll have to look over your pull request in more detail, but I think I'm on board with everything you're proposing.

**Comment by ajorkowski** [comment]
Hi Josh,

Thanks for your quick reply - I didn't actually get a notification so sorry about not responding sooner. I didn't notice `CsvHelper.ObjectResolver` before, but unfortunately it doesn't help since that is used to build objects, mappers, converters, etc. But to be able to get around this problem requires some access to the expressions.

Of course, the alternative thing I could do is to pre-map my objects into a flat structure dynamically, but at this point I would basically be re-writing the entire expression logic that you already have done such a great job in csvhelper - I just want to make a slight modification so that I can support 'flattening' those enumerables. 

P.S. If there is anything you don't like in the PR please make a comment and I will change it. I tried to make it low touch, but obviously I had to pick a place for the container etc which was fairly arbitrary.

**Comment by JoshClose** [comment]
I meant using `ObjectResolver` instead of the `IContainerFactory` in your pull request.

**Comment by JoshClose** [comment]
The dependencies definitely could be inverted or at least created using the `ObjectResolver` instead.

**Comment by ajorkowski** [comment]
Oh, I see what you are saying! Hrm sure I will try another PR then using that instead.

**Comment by ajorkowski** [comment]
Ok - I have updated the PR to use the ObjectResolver, and got rid of the container. Let me know what you think.

**Comment by ajorkowski** [comment]
Oh - I kept the 'inverting' of the dependencies in there. I guess I could start from scratch and just do the resolving in each seperate class like it was doing before? Actually that might be better, since overridden classes might not use certain dependencies...

Let me try this PR again!

**Comment by JoshClose** [comment]
Done. This will be in version 6.0.0. Man, these major versions are just flying by these days.

**Comment by ajorkowski** [comment]
@JoshClose Sorry to bother you, but could we get this out in a release? I it wasn't included on v5 right? It could even be on a pre-release branch if you wanted to get a few other things done before pushing another major release. 

The problem is that this is a blocker for me, and the only remedy without this fix is to roll back my work or include a fixed assembly manually :(

**Comment by JoshClose** [comment]
Sure. Let me see if there is anything else small I can throw in first. I'll get something out today for you though.

**Comment by ajorkowski** [comment]
Awesome, I really appreciate it 👍 Also I noticed the added generic version of the Resolve - was a good change.

**Comment by JoshClose** [comment]
6.0.0 is on NuGet.

**Comment by ajorkowski** [comment]
Thank you again. I have already updated to it and everything is working perfectly. Cheers!

**Comment by JoshClose** [comment]
That's good to hear!
