### ISSUE TITLE
Mapping same field twice in ClassMap

### ISSUE THREAD

**Issue by Sinjai** [JoshClose/CsvHelper#823]
This is reported as resolved in [this](https://github.com/JoshClose/CsvHelper/issues/515) issue, but I'm using v4.0.3 and I'm still getting the behavior described on that page. 

Here's what my code looks like:
```
public MyClassMap(string argument)
{
	Map(e => e.Field).Name("Mapping 1").TypeConverter(new FirstTypeConverter(argument));
	Map(e => e.Field).Name("Mapping 2").TypeConverter(new SecondTypeConverter(argument));
	Map(e => e.Field).Name("Mapping 3").TypeConverter(new ThirdTypeConverter(argument));
}
```

When I use `csv.WriteRecords()`, only the third mapping is written, so in this case the result only has one column.

**Comment by JoshClose** [comment]
`Map(expression)` takes a second parameter `bool useExistingMap = true`. You can just set that to false.

```cs
Map(m => m.Field).Name("Field1");
Map(m => m.Field, false).Name("Field2");
```

**Comment by Sinjai** [comment]
Why is the default behavior to overwrite? In what circumstance would you want previous mappings to not matter?

**Comment by JoshClose** [comment]
It's accessing that member, kinda like a property getter. You're saying "this member has this name and this type converter". If you do it again, you're still saying "this member has this name and this type converter."

**Comment by Sinjai** [comment]
Gotcha.
It's really great that you're still actively supporting this! Guys like you are what makes the programming community thrive. 
This one's definitely on me for not looking at optional parameters.

**Comment by JoshClose** [comment]
Thanks and no worries! I'm trying to make the API as intuitive as possible. When functionality gets complex, sometimes the API suffers a little, but I'm trying to make everything as easy to use as possible.
