### ISSUE TITLE
symbol issue

### ISSUE THREAD

**Issue by lnu** [JoshClose/CsvHelper#824]
We got this exception when building in tfs and pushing the symbols:
```
Indexed source information could not be retrieved from f:\Builds\5\20\Binaries\cdt.eai\CdT.EAI.WebApi\CsvHelper.pdb. Error: Symbol indexes could not be retrieved
```
.net 4.6.1 and csvhelper 4.0.3

We moved from 2.16.3.0 to 4.0.3.

Is the pdb needed in the package?

**Comment by JoshClose** [comment]
Hmm... I don't think so. The symbols should be included. If you download the package separately from NuGet, you should see the `.pdb` file in there. The `.nupkg` file is just a zip.

**Comment by lnu** [comment]
Usually two packages are generated, one with the symbols and one without. Like this:https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages
What do you think?

**Comment by JoshClose** [comment]
I use this to [pack](https://github.com/JoshClose/CsvHelper/blob/master/Pack%20NuGet%20Packages.bat) the NuGet packages.

```
dotnet pack src\CsvHelper --include-symbols --configuration release --output ..\..\NuGet
```

I use this to [push]() the NuGet packages.

```
dotnet nuget push NuGet\*.symbols.nupkg -s nuget.org
```

So I'm pushing the symbols package to the NuGet server.

**Comment by lnu** [comment]
So if you do this:

dotnet nuget push NuGet\*.nupkg
And
dotnet nuget push NuGet\*.symbols.nupkg

The package without symbols will be pushed to nuget.org and the package with the symbols will be pushed to https://nuget.smbsrc.net/?

**Comment by JoshClose** [comment]
Do you want the symbols or want a package without the symbols? Or do you want the symbols pushed to a symbol server?

**Comment by lnu** [comment]
A standard package without symbols is exactly what I need.
My point was just to say it’s possible to support both scenarios without too many changes.
Thanks for your response and all your work on the library.

**Comment by JoshClose** [comment]
Ok. I'll see what I can do to push one without and one with.

**Comment by JoshClose** [comment]
I'm now pushing the non symbol package to nuget.org and pushing the symbols package to https://nuget.smbsrc.net/

**Comment by lnu** [comment]
Thanks a lot!

**Comment by JoshClose** [comment]
No problem! I didn't realize it wasn't doing what it was supposed to. It was supposed to push the right one to the right location (so the docs say) and that wasn't happening. It also didn't work pushing to the symbol server using the symbols flag. I wouldn't be surprised if this breaks at some point. ;)
