### ISSUE TITLE
No way to ignore comma where a field value is enclosed in quotes when it contains a comma

### ISSUE THREAD

**Issue by CodingNawab** [JoshClose/CsvHelper#825]
I have CSVs where the field is enclosed with quotes only when there is a comma in the content of the field. Such comma should not be treated as a delimiter. There seems to be no way to do this.

I think this needs something like
csv.Configuration.IgnoreDelimeterInQuotes = true;

**Comment by JoshClose** [comment]
It does this by default.

**Comment by JoshClose** [comment]
`one,"two,three",four` gets parsed as `[one][two,three][four]` by default.

**Comment by CodingNawab** [comment]
Ah, I just retested; found that there is a further double quote in the content that's already closed in quotes since it had a comma. That is effectively leading to BadDataFound which is the expected behaviour any way.  I need to see what I can do about nested quotes!

**Comment by JoshClose** [comment]
Great, good luck! CSV files that aren't created by you tend to be poorly formatted, unfortunately.

**Comment by demyanmk** [comment]
> `one,"two,three",four` gets parsed as `[one][two,three][four]` by default.

it is not working if IgnoreQuotes is true.

**Comment by demyanmk** [comment]
i use dynamic record and wanna pass double quotes as is or change double quotes to single quotes. if IgnoreQuotes is false, double quotes erased

**Comment by JoshClose** [comment]
> it is not working if IgnoreQuotes is true.

That's exactly what that setting does.
