### ISSUE TITLE
Does not work on .NETFramework 4.7?

### ISSUE THREAD

**Issue by coke187** [JoshClose/CsvHelper#830]
Hello, I get this error when trying to install CsvHelper 5.0.0.1 NuGet package:
Install-Package : Package CsvHelper 5.0.0.1 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x86-aot. 

Any thoughts.
Cheers.

P.S. I am creating a Windows 10 UWP app.

**Comment by JoshClose** [comment]
.NET 4.5 and netcore2.0 are the two builds that are available. Do neither of those work with a UWP app?

**Comment by jamesbascle** [comment]
Make sure you are using the newest version. They just added aupport.

**Comment by JoshClose** [comment]
Newest version of UWP?

**Comment by coke187** [comment]
I've got an existing UWP app that I have been writing for a while now. My Visual Studio Enterprise 2017 has .NET Framework Version 4.7.02556.

**Comment by JoshClose** [comment]
What version of .NET is the UWP project using?

**Comment by coke187** [comment]
Apparently UWP's don't target a .NET Framework version, but they target an SDK version. Mine targets:
Windows 10 Creators Update (10.0; Build 15063) and Min version: Windows 10 November Update (10.0; Build 10586).

**Comment by coke187** [comment]
I could try downgrading to .NET Framework version 4.5. Hopefully this doesn't break all of my other code; I have 3 other people working on some separate classes.

**Comment by coke187** [comment]
I've already written my own CSV file parsing routines. All I need now is to be able to append a new column of data to an existing CSV file. The data will come from a website, and I will have parsed it into a Dictionary object. I might switch that to a List object to make it easier to iterate over. I'd love to just implement your code though haha.  
Thanks for all of your help so far guys.

**Comment by JoshClose** [comment]
Take a look at the compatibility here. https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by jamesbascle** [comment]
Like, October 10 is when they added .net standard 2.0 support. If you have
not installed anything with VS or UWP since then, you need to update.

**Comment by coke187** [comment]
I have updated everything.

**Comment by jamesbascle** [comment]
Still getting the same error message?

**Comment by jamesbascle** [comment]
Also apparently you have e to be on latest windows 10, fall creators update
as well.

**Comment by coke187** [comment]
I have the newest Windows update and newest VS 2017. Maybe I need to install more SDKs? 
I will try again tomorrow :) Thanks guys.

**Comment by jamesbascle** [comment]
Damn I scoured the internet as much as I could. Unfortunately I have never
done any UAP dev, so I can't help from experience at all.

**Comment by coke187** [comment]
I might just read the source code and grab what I need to write to a CSV
file :)

Bryan Eriksson

**Comment by coke187** [comment]
![targets](https://user-images.githubusercontent.com/8400541/32389953-bcdac146-c089-11e7-886b-6b33d67fa2cb.PNG)
Here are my targets.

**Comment by JoshClose** [comment]
I tried with target an min version both as the fall creators update and it worked. I'm guessing you need the min version to be fall creators update also.

**Comment by coke187** [comment]
That worked, thanks so much!

Bryan Eriksson

**Comment by coke187** [comment]
Now I get the following error when writing this code:
   
            StorageFile file = await picker.PickSingleFileAsync();
            
            var writer = new StreamWriter(await file.OpenStreamForWriteAsync());
            var csv = new CsvWriter(writer);

![image](https://user-images.githubusercontent.com/8400541/32420963-c94c5808-c247-11e7-9493-1533c3ae88c9.png)

**Comment by coke187** [comment]
Fixed this error by updating NuGet!
