### ISSUE TITLE
Mapping against interfaces results in unmapped headerless columns

### ISSUE THREAD

**Issue by ccopsey** [JoshClose/CsvHelper#832]
In 2.16.2 the following code produced the result:
```
RenameA
1
3
```
but from 2.16.3 (to date) produces the result:
```
RenameA
1,2
3,4
```
The former is what I was hoping for, but certainly the headerless columns in the latter must be wrong.

```
namespace CsvHelperTest
{
    interface IRecord
    {
        int A { get; }
        int B { get; }
    }

    class Record : IRecord
    {
        public int A { get; set; }
        public int B { get; set; }
    }

    sealed class RecordMap : CsvClassMap<IRecord>
    {
        public RecordMap()
        {
            Map(m => m.A).Name("RenameA");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var records = new List<IRecord>
            {
                new Record {A = 1, B = 2},
                new Record {A = 3, B = 4}
            };

            var writer = Console.Out;
            var csv = new CsvWriter(writer);
            csv.Configuration.RegisterClassMap<RecordMap>();
            csv.WriteRecords(records);
            Console.Read();
        }
    }
}
```

**Comment by ccopsey** [comment]
The same test with ```RecordMap : CsvClassMap<Record>``` produces:
```
A,B
1
3
```

**Comment by JoshClose** [comment]
If I run this in the latest version, I get this for the results.

```
RenameA
1,2
3,4
```

**Comment by ccopsey** [comment]
The code only maps column A.  The values 2 and 4 should not be there.  As far as I understand it.

**Comment by JoshClose** [comment]
I'll see what's going on there.

**Comment by JoshClose** [comment]
What's happening here is you register a mapping for type `IRecord` then you give it a type of `Record` to write, which isn't mapped, so it auto maps it. The header is written off the of `IEnumerable`s generic type, which is why the header is correct.

I will look into if it's possible to use that generic type when writing the records too, or if it will screw up other things. Currently it's using the individual records type.

**Comment by JoshClose** [comment]
It wasn't possible. I had to add a method `WriteRecords<T>( IEnumerable<T> records )`. This issue is fixed in any case that uses that now. If an `IEnumerable` is used, such as `ArrayList` or any of the old non-generic lists, this won't work.

**Comment by ccopsey** [comment]
Thanks for the prompt response.

**Comment by adamreed90** [comment]
I was able to get this to work by introducing a <T> to the IRecord this then allows you to specify the type when writing records and it will map appropriately.
