### ISSUE TITLE
Guidance for setting custom header field for a column

### ISSUE THREAD

**Issue by scsloan** [JoshClose/CsvHelper#833]
Looking for guidance on how to handle an issue with column headers. 

Issue:
Microsoft Excel registers itself as the default handler for CSV files. There is a [known issue](http://support.microsoft.com/kb/323626) within excel, that when the first column of the first row starts with the chars ID, the user will experience an "SYLK: File format is not valid" error message.

Workaround:
To mitigate this, Microsoft's workaround to is to place an apostrophe before the field. 

Looking at the [documentation](https://joshclose.github.io/CsvHelper/configuration#headers) for CsvHelper, I seem to be missing how to go about this. 

Suggestion:
Ideally, it would be nice if CsvHelper would check for the [Display Attribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.displayattribute.name(v=vs.110).aspx) from System.ComponentModel to get header information. Looking through the source, it looks as though CsvHelper just looks at PropertyName?

**Comment by JoshClose** [comment]
Is this for reading or writing or both?

**Comment by scsloan** [comment]
Writing

**Comment by JoshClose** [comment]
You can control over the headers. If you want the first header to be `ID` you can just map it to `'ID` instead.

You can either create a map http://joshclose.github.io/CsvHelper/mapping/ or there are attributes you can use that aren't documented yet. `[Name("'ID")]` They are in namespace `CsvHelper.Configuration.Attributes`

**Comment by scsloan** [comment]
Awesome Thanks!

**Comment by bsell93** [comment]
> You can control over the headers. If you want the first header to be `ID` you can just map it to `'ID` instead.
> 
> You can either create a map http://joshclose.github.io/CsvHelper/mapping/ or there are attributes you can use that aren't documented yet. `[Name("'ID")]` They are in namespace `CsvHelper.Configuration.Attributes`

This should make its way into the documentation 😄

**Comment by ShaneFromFargo** [comment]
[http://joshclose.github.io/CsvHelper/mapping/](http://joshclose.github.io/CsvHelper/mapping/) this page is now a 404

**Comment by jvanderbiest** [comment]
@ShaneFromFargo https://joshclose.github.io/CsvHelper/examples/configuration/class-maps/mapping-by-name/

**Comment by jonathanmoosekian-hpg** [comment]
> @ShaneFromFargo https://joshclose.github.io/CsvHelper/examples/configuration/class-maps/mapping-by-name/

This link is also a 404 now.

**Comment by JoshClose** [comment]
If you take the `/` off the end it will work. I'll have to see if I can change it so it works with a `/` on the end.
