### ISSUE TITLE
Reading/Writing Multiple Fields to List<Object>?

### ISSUE THREAD

**Issue by MSWCRB** [JoshClose/CsvHelper#837]
I'm looking for example code in the latest version on how to read/write a mapping between the following MyClass and CSV:

Class:
```cs
public MyClass{
public string Id {get;set;}
public Custom MyCustom {get;set;}
}

public Custom {
public string Property1 {get;set;}
public string Property2 {get;set;}
}
```

CSV:
```
Id, Property1, Property2
123, 456, 789
```

Essentially, the 2 fields in the CSV need to map to create a new Custom object and map to the 2 fields in it.  Ideally, we'd want to use an ITypeConverter since we have many classes that have a Custom property in them and we wouldn't want to have to re-write mapping code each time.

thanks!

**Comment by JoshClose** [comment]
What do you mean by re-write mapping code?

The simple case is a map would look like this.

```cs
public class MyClassMap : ClassMap<MyClass>
{
	public MyClassMap()
	{
		Map(m => m.Id);
		Map(m => m.MyCustom.Property1);
		Map(m => m.MyCustom.Property2);
	}
}
```

If you have many classes that need to reference `Custom` or you have more than 1 `Custom` property across multiple classes, that may be ways to reduce duplicating the maps for each of those classes.

**Comment by MSWCRB** [comment]
We have 7 or 8 classes that have a property of type Custom and I'm hoping to avoid having to write a class map for each one. That's why I suggested an Itypeconverter implementation. Is it possible or must I write a map for each class?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by JoshClose** [comment]
If all the names of the properties match the CSV file headers, you don't have to map at all. If you don't want to create maps, attributes might be a nicer way. `CsvHelper.Configuration.Attributes` namespace has most of the features that a `ClassMap` does.

**Comment by MSWCRB** [comment]
Attributes still need to be done on each class.

Now level 2 of the question. What if the property on MyClass is a List<Custom> instead? How can we get the code to create a list and populate the first item in the list with a Custom object with those two property values from the CSV? Likewise, how can we output two fields from the first item in the list?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by JoshClose** [comment]
You're going to need to configure every class in some way. There's really no avoiding that. If the names match the headers, you'll have minimal amount of configuration. Attributes will eliminate needing a separate mapping class. An `ITypeConverter` is used to convert a member (property/field) to and from a string, so that won't help with re-use.

Collections are supported. I don't think there is any docs on it yet, but you can look around the unit tests to see how they work. https://github.com/JoshClose/CsvHelper/tree/master/src/CsvHelper.Tests/TypeConversion

**Comment by MSWCRB** [comment]
I checked there and can't come close to figuring out how to do what I need.  I think it would be very helpful to many people if you could reply with the code needed to translate between, where the Propety1 and Property2 in the CSV map to the first element of the list.  I agree that Attributes would seem to be the smoothest way to do it (I think I can inherit from a base class then and avoid duplication):

Class:
```
public MyClass{
public string Id {get;set;}
public List<Custom> MyCustoms {get;set;}
}

public Custom {
public string Property1 {get;set;}
public string Property2 {get;set;}
}
```
CSV:

```
Id, Property1, Property2
123, 456, 789
```

I'm sure it's trivial for you because you live this code, but I checked the examples and can't see it.
thanks!

**Comment by JoshClose** [comment]
Ok, so you want there to be a list  of `Custom` for the property. It would contain only a single item though, right?

**Comment by JoshClose** [comment]
Since you have a list of custom class objects and not value types, it's not as straight forward. If you wanted a list of strings or something, it would be a lot more simple. Here is a way you can do it with the class/csv you provided.

```cs
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Property1,Property2");
        writer.WriteLine("123,456,789");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.RegisterClassMap<MyClassMap>();
        csv.GetRecords<MyClass>().ToList().Dump();
    }
}

public class MyClass
{
    public string Id { get; set; }
    
    public List<Custom> MyCustoms { get; set; }
}

public class Custom
{
    public string Property1 { get; set; }    
    
    public string Property2 { get; set; }
}

public class MyClassMap : ClassMap<MyClass> 
{
    public MyClassMap()
    {
        Map(m => m.Id);
        Map(m => m.MyCustoms).ConvertUsing(row =>
        {            
            var list = new List<Custom>
            {
                new Custom { Property1 = row.GetField("Property1"), Property2 = row.GetField("Property2") },
            };
            return list;
        });
    }
}
```

**Comment by MSWCRB** [comment]
Hey Josh - thanks for that!  I think this is helpful to many users.  Two follow ups.
1) If I specify a ClassMap do I need to map each property, even when the mapping is straightforward?  In the example, class MyCLass has only 2 properties, but in real life, it has 40.  I'd like to avoid duplicating the property list in the mapping class for maintainability.
2) Is there a way to achieve the above mapping of the List<Custom> by using attributes?  As I mentioned, we have several classes that have a property names List<Custom> and if I can get this done using an attribute, I think I can inherit from a base class and avoid writing a mapping for each one.

thanks again!

**Comment by MSWCRB** [comment]
bump...

**Comment by JoshClose** [comment]
For writing, there is another overload of `ConvertUsing` that gives you your object and you return a `string`. There isn't a way to do `ConvertUsing` with attributes.

If every file has a `List<MyCustom>`, I guess a custom type converter might work in this case. Since this is using attributes and the type is an `IEnumerable` it requires an `Index` attribute, even though it's not used. You also have to register the type converter globally instead of an attribute.

```cs
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using CsvHelper.TypeConversion;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace CsvHelper.Tests
{
	[TestClass]
    public class Issue837
    {
		[TestMethod]
        public void Test1()
		{
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvReader( reader ) )
			{
				writer.WriteLine( "Id,Property1,Property2" );
				writer.WriteLine( "123,456,789" );
				writer.Flush();
				stream.Position = 0;

				csv.Configuration.HeaderValidated = null;
				csv.Configuration.MissingFieldFound = null;
				csv.Configuration.TypeConverterCache.AddConverter<List<Custom>>( new MyTypeConverter() );

				var records = csv.GetRecords<MyClass>().ToList();
				Assert.AreEqual( "456", records[0].MyCustoms[0].Property1 );
				Assert.AreEqual( "789", records[0].MyCustoms[0].Property2 );
			}
		}

		private class MyClass
		{
			public string Id { get; set; }

			[Index(1, 2)]
			public List<Custom> MyCustoms { get; set; }
		}

		private class Custom
		{
			public string Property1 { get; set; }

			public string Property2 { get; set; }
		}

		private class MyTypeConverter : DefaultTypeConverter
		{
			public override object ConvertFromString( string text, IReaderRow row, MemberMapData memberMapData )
			{
				var list = new List<Custom>();
				var custom = new Custom
				{
					Property1 = row.GetField<string>( "Property1" ),
					Property2 = row.GetField<string>( "Property2" )
				};
				list.Add( custom );

				return list;
			}
		}
	}
}
```

**Comment by MSWCRB** [comment]
Josh - appreciate the response.  It again looks to me like the example you just provided only handles the reading and not the writing.  Following with your most recent response, how could I use a TypeConverter to write those 3 elements from MyClass to 3 fields in the CSV?  If it can't be done with a TypeConverter, I'm really open to whatever you think the best way is to do it at this point; I'm just trying to get something working.

thanks!

**Comment by JoshClose** [comment]
Here it is with writing added. You're in very strange territory here with what you're doing, so there is some very non-conventional things going on because of the list of objects being used with attributes. Normally I'd recommend other ways of doing this, but this will get you the most re-usable code with the least amount of configuration. Another option might be to dynamically create the mappings, but I don't know enough about your situation to determine if that would be a good option.

```cs
using CsvHelper.Configuration;
using CsvHelper.Configuration.Attributes;
using CsvHelper.TypeConversion;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace CsvHelper.Tests
{
	[TestClass]
	public class Issue837
	{
		[TestMethod]
		public void WriteTest()
		{
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvWriter( writer ) )
			{
				var list = new List<MyClass>
				{
					new MyClass
					{
						Id = "123",
						MyCustoms = new List<Custom>
						{
							new Custom
							{
								Property1 = "456",
								Property2 = "789"
							}
						}
					}
				};
				csv.Configuration.TypeConverterCache.AddConverter<List<Custom>>( new MyTypeConverter() );
				csv.WriteRecords( list );
				writer.Flush();
				stream.Position = 0;

				var expected = new StringBuilder();
				expected.AppendLine( "Id,Property1,Property2" );
				expected.AppendLine( "123,456,789" );
				Assert.AreEqual( expected.ToString(), reader.ReadToEnd() );
			}
		}

		[TestMethod]
		public void ReadTest()
		{
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvReader( reader ) )
			{
				writer.WriteLine( "Id,Property1,Property2" );
				writer.WriteLine( "123,456,789" );
				writer.Flush();
				stream.Position = 0;

				csv.Configuration.HeaderValidated = null;
				csv.Configuration.MissingFieldFound = null;
				csv.Configuration.TypeConverterCache.AddConverter<List<Custom>>( new MyTypeConverter() );

				var records = csv.GetRecords<MyClass>().ToList();
				Assert.AreEqual( "456", records[0].MyCustoms[0].Property1 );
				Assert.AreEqual( "789", records[0].MyCustoms[0].Property2 );
			}
		}

		private class MyClass
		{
			public string Id { get; set; }

			[Index( 1, 2 )]
			[Name( "Property", "Property1" )]
			public List<Custom> MyCustoms { get; set; }
		}

		private class Custom
		{
			public string Property1 { get; set; }

			public string Property2 { get; set; }
		}

		private class MyTypeConverter : DefaultTypeConverter
		{
			public override string ConvertToString( object value, IWriterRow row, MemberMapData memberMapData )
			{
				var list = (List<Custom>)value;
				var custom = list[0];
				row.WriteField( custom.Property1 );
				row.WriteField( custom.Property2 );

				return null;
			}

			public override object ConvertFromString( string text, IReaderRow row, MemberMapData memberMapData )
			{
				var list = new List<Custom>();
				var custom = new Custom
				{
					Property1 = row.GetField<string>( "Property1" ),
					Property2 = row.GetField<string>( "Property2" )
				};
				list.Add( custom );

				return list;
			}
		}
	}
}
```

**Comment by MSWCRB** [comment]
thanks Josh - I'll give it a try!

**Comment by MSWCRB** [comment]
Josh - I'm implementing this and would appreciate some additional clarification on:
		```
	[Index( 1, 2 )]
			[Name( "Property", "Property1" )]
			public List<Custom> MyCustoms { get; set; }
```
I'm just trying to figure out what I need to change since my Custom object has more than 2 properties and they are named differently.  I noticed the Name attribute uses names a little different then the 2 property names in the Custom class, yet you have a test there that compares values which I assume passed, so I'm trying to figure it out.

1) If I have 4 properties in my Custom class instead of the 2, do I need to have [Index 1,2,3,4]?
2) Is the Name attribute jsut used for spitting out the column headers and the fact you have "Property", "Property1" instead of "Property1", "Property2" a typo?
thanks!

**Comment by JoshClose** [comment]
This is where the weirdness comes in because this sort of thing isn't supported, but it's do-able, so I'll try to explain what's going on.

# Writing

You need to specify the property name you want to have written. This should be the first one in the name list. The header will be written based off of this and append the numbers after. It might be a better idea to hand write the headers, and you can then just write whatever you want for the customs stuff.

The index will determine how many are written. The number doesn't matter, just the amount between the numbers; which is basically the columns. You could put `1,2` or `8,9`, it doesn't matter. Both will make 2 fields or that property. In your case the difference needs to be the number of properties you want written.

# Reading

Since you need the name for writing, it'll exist for reading too. There is no property named `Property`. You just need to specify any property that exists so you don't get an exception. The custom converter is being used and it doesn't care about the property name you specify.

Again, I don't recommend doing things this way, but if you can't change your class structure or can't use mapping files, you're not left with many other options.

**Comment by MSWCRB** [comment]
Josh - thanks for the great explanation. If on writing we want to name the header columns the names of the properties (e. g. Jim Pam and Toby in my previous post) how would you suggest it?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by JoshClose** [comment]
Let's try a different approach. Does this work in your setup?

Code:
```cs
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,A,B");
        writer.WriteLine("1,2,3");
        writer.WriteLine("4,5,6");
        writer.Flush();
        stream.Position = 0;
        
        var records = new List<MyClass>();
        csv.Read();
        csv.ReadHeader();
        while(csv.Read())
        {
            var record = csv.GetRecord<MyClass>();
            record.Customs = new List<Custom>
            {
                csv.GetRecord<Custom>()   
            };
            records.Add(record);
        }
        
        records.Dump();
    }
}

public class MyClass
{
    public int Id { get; set; }
    
    [Ignore]
    public List<Custom> Customs { get; set; }
}

public class Custom
{
    public int A { get; set; }   
    
    public int B { get; set; }
}
```
Result:
![image](https://user-images.githubusercontent.com/114971/33037272-99ded694-cdf6-11e7-8432-07b0cb61a91b.png)

**Comment by MSWCRB** [comment]
Hey - to be clear - the reading is working perfectly with what you shared previously.  So is the writing of the data rows.  The only issue is the writing of the Header row.  What you just shared is an example of reading, so I'm not sure what problem you are trying to solve...

**Comment by JoshClose** [comment]
Sorry, having different header names for the list items when writing in the previous way isn't possible. I'm curious if doing things in this way is feasible.

Here is the same sort of different way of doing it, but with writing.
```cs
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvWriter(writer))
    {
        var records = new List<MyClass>
        {
            new MyClass
            {
                Id = 1,
                Customs = new List<Custom>
                {
                    new Custom   
                    {
                        A = 2,
                        B = 3
                    }
                }
            }
        };
        csv.WriteHeader<MyClass>();
        csv.WriteHeader<Custom>();
        csv.NextRecord();
        foreach (var record in records)
        {
            csv.WriteRecord(record);
            csv.WriteRecord(record.Customs[0]);
            csv.NextRecord();
        }
        writer.Flush();
        stream.Position = 0;
        
        reader.ReadToEnd().Dump();
    }
}

public class MyClass
{
    public int Id { get; set; }

    [Ignore]
    public List<Custom> Customs { get; set; }
}

public class Custom
{
    public int A { get; set; }

    public int B { get; set; }
}
```

**Comment by MSWCRB** [comment]
I see.  The issue with that kind of approach is that we need to write all that code to tap-dance around the Custom list every time we read or write from any of the 8+ classes that have a List<Custom> in them.  We're trying to minimize code for maintainability.  
I was thinking maybe to use the customconverter on reading since it works perfectly and something like the above on writing, but I'm guessing the [Ignore] attribute clashes with the customerconverter on reading so we'd need to switch completely over.  
I think those being my only options I'd probably just do something nasty like output all of the properties on the Custom class to a single field, concatenated with a colon.  We need the header row since the MyClass actually has over 100 properties in it and it would be impossible to understand otherwise.

**Comment by JoshClose** [comment]
You could serialize the list of customs into a json blob too and store in a single field. I don't think json serialization is all that fast though.

**Comment by MSWCRB** [comment]
Last note on this - since both solutions offered above utilize attributes, it requires our distributable Models assembly to reference the CSVHelpers NuGet.  Any plans to offer the attributes in a lighter distribution package so we don't need to require them to pull the full CSVHelper implementation?

**Comment by JoshClose** [comment]
No, that's not something I want to do. You could do this yourself though. Create your own attributes, then create your own `ClassMap` and override the `ApplyAttributes` methods and populate the data with values from your attributes. This makes me think that the `ApplyAttributes` code should probably be removed from the `ClassMap` class.

As far as your name question goes...

The index has a start and an end value. Only the start is used unless the type is an `IEnumerable`, in which the end is used to know the range of the fields to include. If you have an `IEnumerable` and don't specify and end, it will just use all the rest of the fields.

The name property is used as the name. For convenience when reading, if there might be multiple different names used, you can specify the list of them there. So if your property is `Name` but is sometimes `the person's name`, it will be able to read both. When writing, you can't have multiple possibilities be used, so it just uses the first one in the list. 

The name isn't setup to use multiple for a list. The concept of having a list of objects is not supported. If you have an object, it will pull in all the properties for that object. If you have a list of primitives, it will pull in that list of primitives. You'd doing something that isn't supported, but it's possible to hack it in, which is making the concepts of what's going on a little confusing.

**Comment by Vejahatf** [comment]
Hi Guys,
I have a related question and not able to figure it out myself. my problem goes one more layer deep as:

public class MyClass
{
    public string Id { get; set; }
    
    public List<Custom> MyCustoms { get; set; }
}

public class Custom
{
    public string Property1 { get; set; }    
    
    public List<string> Property1 { get; set; }
}

Can you kindly give me a hint how to map this ?
thanks

**Comment by FarshanAhamed** [comment]
Hi @JoshClose , Is there any way to write the list of strings to multiple columns with the same header name?

My object looks like this

```c#
public class Foo
{
    public int Id { get; set; }
    public List<string> Bars { get; set; } 
}

public class FooMap : ClassMap<Foo>
{
    public FooMap()
    {
        AutoMap(CultureInfo.InvariantCulture);
        Map(m => m.Id).Name("ID");
        Map(m => m.Bars).Name("BAR");
    }
}
```
when writing records, the csv is coming like this

```csv
ID,BAR
1,fe,fi,fo
2,cn,ck,cl
```
Is there a way I can achieve like below?
```csv
ID,BAR,BAR,BAR,BAR
1,fe,fi,fo
2,cn,ck,cl,cz
```

**Comment by AltruCoder** [comment]
You can add the `indexEnd` of 3 and get `ID,BAR1,BAR2,BAR3` for the header.  Otherwise, I think you would need to manually write the header.
```csharp
public class FooMap : ClassMap<Foo>
{
    public FooMap()
    {
        AutoMap(CultureInfo.InvariantCulture);
        Map(m => m.Id).Name("ID").Index(0);
        Map(m => m.Bars).Name("BAR").Index(1,3);
	}
}
```

**Comment by FarshanAhamed** [comment]
@AltruCoder So if I length of the list is dynamic, I have to write the header manually inside a loop of maximum length, correct?

**Comment by AltruCoder** [comment]
You can pass `indexEnd` as an argument.
```csharp
public class FooMap : ClassMap<Foo>
{
	public FooMap(int indexEnd)
	{
		AutoMap(CultureInfo.InvariantCulture);
		Map(m => m.Id).Name("ID").Index(0);
		Map(m => m.Bars).Name("BAR").Index(1, indexEnd);
	}
}

void Main()
{
	var records = new List<Foo>
	{
		new Foo {Id = 1, Bars = new List<string> {"fe","fi","fo"}},
		new Foo {Id = 1, Bars = new List<string> {"cn","ck","cl"}}
	};
	
	using (var csv = new CsvWriter(Console.Out, CultureInfo.InvariantCulture))
	{
		csv.Context.RegisterClassMap(new FooMap(3));
		
		csv.WriteRecords(records);
	}
}
```

**Comment by FarshanAhamed** [comment]
@AltruCoder The output is having the index count with the header name.

```csv
ID,BAR1,BAR2,BAR3,BAR4
1,fe,fi,fo
2,cn,ck,cl,cz
```

Can we force not to include the number?

**Comment by AltruCoder** [comment]
@FarshanAhamed, Like I said before, I think you would need to use my second example and manually write the header to get `ID,BAR,BAR,BAR`.

**Comment by FarshanAhamed** [comment]
@AltruCoder Can I read these `BAR1, BAR2, BAR3` back into this `List<string> Bars` ? if that's possible, your first example is all I need.

**Comment by AltruCoder** [comment]
Yes, you can read them back in with `ID,BAR1,BAR2,BAR3,BAR4`, but your `ClassMap<Foo>` will need to be slightly different.
```csharp
public class FooReadingMap : ClassMap<Foo>
{
	public FooMap()
	{
		AutoMap(CultureInfo.InvariantCulture);
		Map(m => m.Id).Name("ID");
		Map(m => m.Bars).Index(1);
	}
}
```
