### ISSUE TITLE
XLSX?  

### ISSUE THREAD

**Issue by sereeth** [JoshClose/CsvHelper#841]
Does the new version of csvhelper support reading an xlsx file? I'm guessing no, but thought I'd ask.    I looked at https://github.com/christophano/CsvHelper.Excel, but it appears to not support .net core.

**Comment by JoshClose** [comment]
No it doesn't. That library is one that I would have pointed your towards. There is another too that someone mentioned in here, but I can't remember the name.

**Comment by JoshClose** [comment]
This is the other one I was thinking of. https://github.com/kendallb/ExcelHelper

**Comment by sereeth** [comment]
Probably this one: https://github.com/ExcelDataReader/ExcelDataReader  as it supports .net core.  CsvHelper doesnt yet due to ClosedXML needing to support .net standard.  Thanks
