### ISSUE TITLE
[Question] Appending a new column to existing CSV file

### ISSUE THREAD

**Issue by coke187** [JoshClose/CsvHelper#842]
Hello, I was wondering the best way to append a new column of data to an existing CSV file. So far, the new column will have a header, and it will contain the same amount of fields as existing data. Also, the CSV file is opened using a FileOpenPicker( ).PickSingleFileAsync( ), then StreamWriter(await file.OpenStreamForWriteAsync( ) ).

Existing CSV File:

YEAR   MO   DY    Forty-Five
1994      1       1     3.45
1994      1       2     3.48

New Column of Data:

Thirty-Two
4.2
3.1

Existing CSV File With New Data Appended:

YEAR   MO   DY    Forty-Five  Thirty-Two
1994      1       1     3.45           5.6
1994      1       2     3.48           6.4

Thank you :)

**Comment by JoshClose** [comment]
There is no editing feature in CsvHelper. What you could do though, is stream the changes into a new file. Open the old for reading, open a new file for writing, then read old file into objects and write it back into the new file. You could even just use the parser and deal with just string arrays if you want.

**Comment by coke187** [comment]
Perfect, thank you!

**Comment by adam-krug-wavin** [comment]
Here's my example:
1. It assumes you can have more columns than required by BasicType, but all headers must be unique
2. It assumes that you may need to change some values form the original records (BasicType)
3. It adds extra columns required by ExtendedType

`    class Program
    {
        static void Main(string[] args)
        {
            CsvConfiguration config = new CsvConfiguration(CultureInfo.CurrentCulture);
            config.HeaderValidated = null;
            config.MissingFieldFound = null;
            List<ExtendedType> outputData;

            using (TextReader tr = new StreamReader("input.csv", Encoding.UTF8))
            {
                CsvReader reader = new CsvReader(tr, config);
                reader.Read();
                reader.ReadHeader();

                var allUnique = AreHeadersAreUnique(reader.HeaderRecord);

                var inputData = reader.GetRecords<BasicType>();

                outputData = inputData.Select(row => new ExtendedType()
                {
                    A = row.A,
                    B = row.B + " abc", //change some initial value
                    C = row.C,
                    D = Guid.NewGuid().ToString() //add value for the additional column
                }).ToList();
            }

            List<dynamic> toWrite = new List<dynamic>();

            using (TextReader tr = new StreamReader("input.csv", Encoding.UTF8))
            {
                using (TextWriter tw = new StreamWriter("output.csv", false, Encoding.UTF8))
                {
                    CsvWriter writer = new CsvWriter(tw, config);

                    CsvReader reader = new CsvReader(tr, config);
                    reader.Read();
                    reader.ReadHeader();

                    int i = 0;
                    while (reader.Read())
                    {
                        var record = reader.GetRecord<dynamic>();
                        record.B = outputData[i].B;
                        record.D = outputData[i].D;
                        toWrite.Add(record);
                        i++;
                    }

                    writer.WriteRecords(toWrite);
                }
            }
            
        }

        static bool AreHeadersAreUnique(string[] headers)
        {
            var uniqueCount = new HashSet<string>(headers).Count;

            return headers.Length == uniqueCount;
        }
    }

    class BasicType
    {
        public int? A { get; set; }
        public string B { get; set; }
        public double? C { get; set; }
    }

    class ExtendedType : BasicType
    {
        public string D { get; set; }
    }`
