### ISSUE TITLE
Properties on dynamic objects are saved by index and not name

### ISSUE THREAD

**Issue by Mvrooman** [JoshClose/CsvHelper#843]
When writing dynamic objects the order that properties are created appears to be the only criteria used when determining the write order for properties. I slightly modified WriteDynamicExpandoObjectsTest to change the order of when properties are created for the second object which results in a row of 'two,2\r\n' instead of '2,two\r\n'.

```csharp
using (var stream = new MemoryStream())
            using (var reader = new StreamReader(stream))
            using (var writer = new StreamWriter(stream))
            using (var csv = new CsvWriter(writer))
            {
                var list = new List<dynamic>();
                dynamic obj = new ExpandoObject();
                obj.Id = 1;
                obj.Name = "one";
                list.Add(obj);

                obj = new ExpandoObject();
                obj.Name = "two";
                obj.Id = 2;
                list.Add(obj);

                csv.WriteRecords(list);
                writer.Flush();
                stream.Position = 0;

                var expected = "Id,Name\r\n";
                expected += "1,one\r\n";
                expected += "2,two\r\n";

                Assert.AreEqual(expected, reader.ReadToEnd());
```

**Comment by JoshClose** [comment]
What determines the order then; the first record that's written? Doesn't that kind of defeat the whole purpose of `dynamic`?

**Comment by Mvrooman** [comment]
The first record would determine the initial order yes.  How does that defeat the purpose of dynamic though?  I am not aware of scenarios where the order of properties on dynamic objects is important. When parsing the CSV the order would be different than the original object but I think it's more important that the right value be assigned to the right column.

**Comment by JoshClose** [comment]
What if the second dynamic record has more fields? Or another field in between?

When reading, ordering and number of fields doesn't matter. When writing it does. There is no way to do any mapping configuration on dynamic objects. Essentially every dynamic object is it's own type.

Out of curiosity, how are creating dynamic objects where the ordering of the properties is different?

**Comment by Mvrooman** [comment]
Each object doesn't have the same number of properties so the ordering doesn't match.   The idea is to be able to export to CSV a comparison grid.  For example you are comparing motherboards and one does not have an integrated network card so a row for Network Card Speed is not applicable for one of the items.  These properties aren't known at compile time and dynamic works well in this case.

It wouldn't be an efficient approach for a large dataset but in my particular case I know the dateset is always going to be small so I can add dummy properties to each object and then sort them all so they match and still use this library without any modifications.

The library would probably need to be updated to keep a mapping of encountered properties and when a row has a new property the mapping is updated.  For each row that is being written it would need to check the mapping to determine the correct order for each row.

**Comment by JoshClose** [comment]
Are the properties different types or all strings?

**Comment by Mvrooman** [comment]
Each object has a list of attributes. The attribute has a Value property which is an object and it can be a bool,int,string,float,DateTime.  There is also a Name property for the attribute which is what would be used for the column header.

**Comment by JoshClose** [comment]
It sounds like you want the first object you write to be the definition of the columns? If this is the case, what you could do is create a method that returns the object for you. Then you use that object and set the properties. That way you can always have the same order and list of properties because it will be created the same each time, and you can only fill in the properties that you're using for that row.

**Comment by Mvrooman** [comment]
No, the first object would not be the definition for the columns.  Another good visual example would be exporting the results from CarMax car search.   If I compare a 1990 Toyota Corolla vs an electric 2018 BMW  vs a 2018 Tesla each car has different features that are unique to that car.  Both the 2018 cars have an 'Automated Parking' boolean. On the BMW it's an optional feature so in the actual object representation of  it has a true/false value.  For the Corolla that attribute doesn't exist at all.  The Corolla however has a MPG int value but the electric cars don't have that value at all.  It's also not feasible to export every known attribute for all cars in the entire system.  When I'm comparing a 1990 Corolla vs a 1991 Corolla I don't  want 'Automated Parking' to show up or be exported.    The exported columns should just be the aggregate of all applicable attributes for the comparison.

**Comment by JoshClose** [comment]
If you don't know the columns that will show up, how are you adding them to an `ExpandoObject`?

**Comment by Mvrooman** [comment]
I can calculate what columns are needed ahead of time.  This allows me to correct the items so they all have the complete set of attributes being references for the list of items being included.  In my workaround I also make a complete copy of the objects since I need to keep the original objects without the additional attributes included in 
 their lists.  So another reason why my current solution is ok in my case but may not be a good solution for a very large dataset due to the memory required.


```CSharp
        public void ExportItemsToCSV<T>(List<T> items, string saveAsFileName) where T : ItemModel
        {
            try
            {
                items = PrepairItemsForExport(items);

                using (var textWriter = File.CreateText(saveAsFileName))
                {
                    var csvWriter = new CsvWriter(textWriter);
                    List<dynamic> dynamicItems = new List<dynamic>();
                    foreach (var item in items)
                    {
                        dynamic dynamicItemExpando = new ExpandoObject();
                        var dynamicItem = dynamicItemExpando as IDictionary<string, object>;
                        dynamicItem[item.PrimaryIDName] = item.BackendID;
			string enumerableSeperator = ";"
                        foreach (var itemAttribute in item.Attributes)
                        {
                            object attributeValue;
                            if (itemAttribute.Value is IEnumerable<object> enumerableValue)
                            {
                                attributeValue = string.Join(enumerableSeperator , enumerableValue);
                            }
                            else
                            {
                                attributeValue = itemAttribute.Value;
                            }
                            dynamicItem[itemAttribute.InternalName] = attributeValue;
                        }
                        dynamicitems.Add(dynamicItem);
                    }
                    csvWriter.WriteRecords(dynamicitems);
                    csvWriter.Flush();
                }
            }
            catch (Exception e)
            {
                throw new Exception("Error while exporting to CSV file", e);
            }
        }
        private List<T> PrepairItemsForExport<T>(List<T> items) where T : ItemModel
        {
            items = items.Clone();//Create a deep copy to prevent manipulation of the original items
            var distinctAttributeNames = items.SelectMany(e => e.Attributes).
                Select(a => a.InternalName).Distinct().ToList();
            foreach (var item in items)
            {
                NormalizeAttributes(distinctAttributeNames, item);
                SortAttributes(item);
            }
            return items;
        }

	/// <summary>
        /// CSV exports require all items have the same number of attributes
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="distinctAttributeNames"></param>
        /// <param name="item"></param>
        private static void NormalizeAttributes<T>(List<string> distinctAttributeNames, T item) 
                                     where T : ItemModel
        {
            var missingAttributes = distinctAttributeNames.
                  Except(item.Attributes.Select(a => a.InternalName));
            foreach (var missingAttributeName in missingAttributes)
            {
                var attribute = new Attribute { InternalName = missingAttributeName };
                item.Attributes.Add(attribute);
            }
        }

        /// <summary>
        /// CSV exporting requires attributes to be sorted the same for each item
        /// </summary>
        /// <param name="item"></param>
        private void SortAttributes(ItemModel item)
        {
            item.Attributes.Sort((a1, a2) => 
               String.Compare(a1.InternalName, a2.InternalName, StringComparison.Ordinal));
        }
```

**Comment by JoshClose** [comment]
I'm going to leave handling of the order of the properties to the user. As you do you your example, an `ExpandoObject` is just a dictionary, so the order is going to be whatever order you put them in. The idea with inserting an `ExpandoObject` is it will write whatever you give it. Each object is it's own type. I think you could do order caching of some sort before writing the object, but I don't feel that is the correct thing for this library to do.
