### ISSUE TITLE
Can CsvHelper store the CSV row number in the mapped object?

### ISSUE THREAD

**Issue by reloaded** [JoshClose/CsvHelper#845]
Hello!

I'm mapping my CSV records to a concrete object and I was wondering if there's a way to persist the row number in the concrete object?

I have a mapped object that looks like this:

```
public class CsvRowDto {
  public string FirstName {get; set;}
  public string LastName {get; set;}
}
```

And I'm trying to achieve something like this:

```
public class CsvRowDto {
  public int RowNumber {get; set;}
  public string FirstName {get; set;}
  public string LastName {get; set;}
}
```

The use case for this is to provide better error reporting. When my application detects a validation/business rule error I'd like to report the row number that had an error.

```
var records = csvReader.GetRecords<CsvRowDto>().ToList();

foreach(var person in records) {
  if(string.IsNullOrEmpty(person.FirstName)) {
    Console.WriteLine("First name is invalid: " + person.RowNumber);
  }
}
```

**Comment by JoshClose** [comment]
Text file row number or CSV row number? Meaning, a CSV field may have a `\r\n` in it.

**Comment by reloaded** [comment]
That's a quick response! :)

I think CSV row number?... I'm not certain on the differences between the two. The text file row number includes blank lines, right?

Let's say that you are a end user of my application and you upload a CSV. When my system detects an error it needs to tell you which row you should take a look at in the CSV file to find and fix the issue....

So... I think I need the CSV row number?

**Comment by JoshClose** [comment]
You'll want the file's line number then. A single CSV row may span many lines because a field could contain a '\r\n'.

```cs
void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Name");
        writer.WriteLine("1,one");
        writer.WriteLine("2,two");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.RegisterClassMap<TestMap>();
        csv.GetRecords<Test>().ToList().Dump();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int RowNumber { get; set; }
}

public sealed class TestMap : ClassMap<Test>
{
    public TestMap()
    {
        Map(m => m.Id);
        Map(m => m.Name);
        Map(m => m.RowNumber).ConvertUsing(row => row.Context.RawRow);
    }
}
```

**Comment by JoshClose** [comment]
Also, when an exception occurs, that information is available in the exception too.

**Comment by reloaded** [comment]
Wonderful! @JoshClose  That solved my question. Using `Map(m => m.RowNumber).ConvertUsing(row => row.Context.RawRow);` works like a charm.

**Comment by naveenkonda89** [comment]
Hi, 
If the content of records span across multiples rows, the actual row number in the document is returned instead of record number, how do we get record number in csv in such a case
Thank you!

**Comment by JoshClose** [comment]
Use `Row` instead of `RawRow`.

**Comment by capinredbeard** [comment]
Is this still an option? It looks like the API has changed, and ConvertUsing is no longer available.  I have also tried to use a TypeConverter, but haven't found a way to get the row number.

**Comment by JoshClose** [comment]
Yes, `ConvertUsing` was renamed to `Convert.

**Comment by jzabroski** [comment]
@JoshClose I think you should convert this to a Discussion and select the answer so that you can update the answer as you progress CsvHelper.

e.g.,

v12:
```c#
Map(m => m.LineNumber).ConvertUsing(row => row.Context.RawRow);
```
v13 - v20:
```c#
Map(m => m.LineNumber).ConvertUsing(row => row.Context.Row);
```
v21:
```c#
Map(m => m.LineNumber).Convert(row => row.Context.Row);
```
