### ISSUE TITLE
Small result set isn't written to MemoryStream unless StreamWriter is manually flushed

### ISSUE THREAD

**Issue by NuNn-DaDdY** [JoshClose/CsvHelper#846]
**Version**
   _CsvHelper
   Version=6.0.0.0
   Culture=neutral
   PublicKeyToken=8c4959082be5c823_
  
**Issue**
Smaller results sets (e.g. 3 records) are not being flushed to the underlying _MemoryStream_. Attempting to explicitly call _CsvWriter.FlushAsync()_  yielded the same result with no records being written.  The stream is written only after _StreamWriter.FlushAsync()_ is called

**Example Usage**

        [HttpGet]
        [Route("")]
        public async Task<IHttpActionResult> GetClaimsCsv()
        {
            try
            {
                // IQueryable initially returned and data is shaped/sorted into the desired format (anonymous type) for the CSV.
                var claims = await _getClaimsQuery.Handle(new GetClaimsQuery())
                                                  .Select(cl => new
                                                  {
                                                      ClaimNumber = cl.ClaimNumber,
                                                      Relationship = cl.Relationship,
                                                      Reason = cl.Reason,
                                                      Status = cl.Status,
                                                      PlannedBegin = cl.PlannedBegin,
                                                      PlannedEnd = cl.PlannedEnd
                                                  })
                                                  .OrderByDescending(cl => cl.PlannedEnd)
                                                  .ToListAsync();

                using (var memoryStream = new MemoryStream())                
                using (var streamWriter = new StreamWriter(memoryStream))                    
                using (var csvWriter = new CsvWriter(streamWriter))
                {
                    csvWriter.WriteRecords(claims);

                    // Does not work when no call to either FlushAsync methods are made. 
                    // MemoryStream has length of 0 when passed into the DocumentAttachmentResult.

                    //await csvWriter.FlushAsync();        // Will not work if this method is executed 
                    await streamWriter.FlushAsync();       // Only works when this is called.

                    return new DocumentAttachmentResult($"Claims_{DateTime.Now:yyyy-MM-dd_hhmmss}.csv",
                                                        MimeTypeCsv,
                                                        memoryStream.ToArray());
                }                                    
            }
            catch (Exception ex)
            {
                return CreateErrorResponse(ex);
            }
        }

**Comment by JoshClose** [comment]
`CsvWriter.Flush`'s intellisense/xml doc says

>  Serializes the row to the TextWriter.

So this does not flush the data to the stream.

The intended usage is to call `streamWriter.Flush` yourself. They will flush automatically when leaving the using block too. If you're returning before the end of the using, you'll need to call flush.

**Comment by NuNn-DaDdY** [comment]
Thank you for the clarification.  I appreciate it and will make sure to call _streamWriter.Flush_ moving forward.  Have a great day and keep up the good work!

**Comment by JoshClose** [comment]
Thanks!
