### ISSUE TITLE
6.0 release notes

### ISSUE THREAD

**Issue by niemyjski** [JoshClose/CsvHelper#848]
I saw the 6.0 release (congrats), and  was looking for a change log / upgrade guide on breaking changes but this was completely missing.

**Comment by JoshClose** [comment]
Sorry, got busy and forgot! I'll update the change log today.

**Comment by JoshClose** [comment]
Updated. Let me know if you have to hard refresh to see the data. I may need to version the files if this is a problem.

**Comment by niemyjski** [comment]
Thanks, I wasn't even looking on the website for them, I always just go
here: https://github.com/JoshClose/CsvHelper/releases

Thanks
-Blake Niemyjski

**Comment by JoshClose** [comment]
Just pushed the tags so 6.0.0 shows up there now. ;)
