### ISSUE TITLE
Follow Up to #837

### ISSUE THREAD

**Issue by MSWCRB** [JoshClose/CsvHelper#853]
https://github.com/JoshClose/CsvHelper/issues/837

Follow ups there have been ignored for a week - not sure how to get it back to the top of the list for comment...

**Comment by JoshClose** [comment]
I'll do things during the day if they'll only take a few minutes. If it's anything longer than that, I can't do them until my kids are in bed at night. This past week has been busy so I've been pushing this back. I spend about 1.5 hours looking into this. It's a very special case with a non-standard class structure, you want minimal configuration, and you want it to be generic and used across a bunch of classes. This is something that will take a while to figure out.

**Comment by MSWCRB** [comment]
No worries - I just thought the original request had gotten buried since I saw you responding to several others.  I'll wait until you can respond with a solution.
