### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by markwsanders** [JoshClose/CsvHelper#854]
I receive...

`The call is ambiguous between the following methods or properties: 'MemberMap<TClass, TMember>.ConvertUsing(Func<IReaderRow, TMember>)' and 'MemberMap<TClass, TMember>.ConvertUsing(Func<TClass, string>)'`

When I try to compile...
```
public class Client
{
	public string Name { get; set; }
	public string Language { get; set; }
	public string Email { get; set; }
}

public class ClientCsvMap : ClassMap<Client>
{
	Map(c => c.Name).Name("ClientName");
	Map(c => c.Language).ConvertUsing(row => "English"); //<-- Compile error
	Map(c => c.Email).Name("ClientEmail");
}
```
This was working fine until I upgraded to 6.0.0. I cannot figure out why this is happening. Any help would be appreciated.

**Comment by JoshClose** [comment]
It's because you're returning a string, so it has the same signature for reading and writing. If you quality the type of row, it should work.

```cs
.ConvertUsing((IReaderRow row) => "English");
```

**Comment by markwsanders** [comment]
That worked. Thanks!

**Comment by RenFontes** [comment]
> 
> 
> It's because you're returning a string, so it has the same signature for reading and writing. If you quality the type of row, it should work.
> 
> ```cs
> .ConvertUsing((IReaderRow row) => "English");
> ```

Thank you so much :)
For some reason we were using version 2.16.3 of CsvHelper, I updated to latest and found tons of errors. 😂
