### ISSUE TITLE
2.x documentation url is not working

### ISSUE THREAD

**Issue by jefhai** [JoshClose/CsvHelper#855]
I'm trying to access the 2.x version of the documentation because thats the only version that works with UWP .net standard 1.x. The url on the home page brings up a 404 error. Can you provide we with a new url please? Thank you.

http://joshclose.github.io/2.x

**Comment by JoshClose** [comment]
http://joshclose.github.io/CsvHelper/2.x/

Where did you get that url from? It needs updating.

**Comment by jefhai** [comment]
Bottom of the page 'here': https://joshclose.github.io/CsvHelper/

Thanks :)

**Comment by JoshClose** [comment]
Updated!

**Comment by smilin-desperado** [comment]
Where can I find the correct link to the 2.x docs? The link at the bottom of this page : http://joshclose.github.io/CsvHelper/ is 404ing. Thanks

**Comment by JoshClose** [comment]
Fixed. Should be there now.

**Comment by smilin-desperado** [comment]
Great! Thanks 😄
