### ISSUE TITLE
Docs not being indexed on Google

### ISSUE THREAD

**Issue by ExplodingCabbage** [JoshClose/CsvHelper#858]
I almost commented on https://github.com/JoshClose/CsvHelper/issues/456 to (wrongly) complain that the methods discussed there were still not documented, because I couldn't find them on Google. Try searching Google for any of the search terms below:

```
site:http://joshclose.github.io/ readheader
site:http://joshclose.github.io/ getfield
"Records aren't pulled until you actually start iterating the results."
```

The pages from the docs that ought to appear are, without exception, missing from the Google results. Additionally, viewing a cached version of a page other than the homepage (e.g. by entering `cache:joshclose.github.io/CsvHelper/reading` in the URL bar in Chrome) shows that, as far as Google is concerned, all pages of the docs just contain exactly the same content as the homepage.

**Comment by JoshClose** [comment]
Hmm... Google is supposed to be able to crawl single page apps.

I'll look into this.

Thanks!

**Comment by ExplodingCabbage** [comment]
Yeah, I don't know what the cause is - I'd be interested to see, once you figure it out.

**Comment by JoshClose** [comment]
Maybe it can only follow after an initial load or something. I'm dynamically loading all the content.

**Comment by JoshClose** [comment]
Look into using GatsbyJS

**Comment by JoshClose** [comment]
The docs have been updated using react-static. Every page has a static file behind it now.
