### ISSUE TITLE
raw csv Line

### ISSUE THREAD

**Issue by borgez** [JoshClose/CsvHelper#86]
How i may get this to model?

only data, not header

something like this?
public class importCSV
    {
        [CsvField(rawLine = true)]
        public string rawLine { get; set; }
    }

**Comment by ronnieoverby** [comment]
.... and `ICsvParser.RawRecord` is not there....

**Comment by kevinbrydon** [comment]
CsvReader version 27 has it in the `Parser` property. If it moved to `Context` ... it may have moved back

```
using (var streamReader = new StreamReader( csvFilePath ))
{
    var csvConfiguration = new CsvHelper.Configuration.CsvConfiguration( CultureInfo.InvariantCulture );

    using (var csvReader = new CsvHelper.CsvReader( streamReader, csvConfiguration ))
    {
        csvReader.Context.RegisterClassMap<MyClassMap>();

        while (csvReader.Read())
        {
            var rawRecord = csvReader.Parser.RawRecord;
        }
    }
}
```
