### ISSUE TITLE
Xamarin.Forms project not compiling for Android when using CsvHelper

### ISSUE THREAD

**Issue by afnan-ahmad** [JoshClose/CsvHelper#865]
Hi,

I recently added this library into my Xamarin.Forms project targeting .NET Standard 2.0. On compiling the project for Android, the following error occurred.

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'CsvHelper, Version=6.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'. Perhaps it doesn't exist in the Mono for Android profile?

Seems like the library is not configured to support .Net Standard 2.0 or Xamarin profiles. A workaround for this issue is highly appreciated.

**Comment by JoshClose** [comment]
Do you have any information what is required for the Android profile? CsvHelper has a netstandard2.0 build.

**Comment by afnan-ahmad** [comment]
.NET Standard libraries should work out of the box with Mono.Android profiles, I don't think any specific configuration is required. You may consult the Xamarin docs about .NET Standard here:

https://developer.xamarin.com/guides/cross-platform/application_fundamentals/net-standard/
https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/net-standard/

Thank you for your response.

**Comment by JoshClose** [comment]
Looks like `Xamarin.Android` version 8.0 or higher is required. What version are you using? https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by afnan-ahmad** [comment]
Yes, I am using Android version 8.0 (Oreo) as project target

**Comment by afnan-ahmad** [comment]
I can confirm it was working last time I used it with a Xamarin Forms project. So I guess we can close this now.

Thanks,
Afnan
