### ISSUE TITLE
Can't install NuGet Xamarin Forms

### ISSUE THREAD

**Issue by davidmclennan** [JoshClose/CsvHelper#866]
Trying to install the latest version from NuGet into a Xamarin Forms PCL project gives me this error:

> Could not install package 'CsvHelper 6.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I can't find anything from searching to say why this wouldn't work, or if a different profile would be compatible.

**Comment by JoshClose** [comment]
Looks like Xamarin.Android version 8.0 or higher is required. What version are you using? https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by davidmclennan** [comment]
I believe I'm > Xamarin.Android 8.0? These are my visual studio installed products:

> Microsoft Visual Studio Community 2017 
Version 15.4.5
VisualStudio.15.Release/15.4.5+27004.2010
Microsoft .NET Framework
Version 4.7.02046
Installed Version: Community
Visual Basic 2017   00369-60000-00001-AA806
Microsoft Visual Basic 2017
Visual C# 2017   00369-60000-00001-AA806
Microsoft Visual C# 2017
Visual F# 4.1   00369-60000-00001-AA806
Microsoft Visual F# 4.1
Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.
Mono Debugging for Visual Studio   4.7.4-pre (c2d89eb)
Support for debugging Mono processes with Visual Studio.
NuGet Package Manager   4.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
VisualStudio.IoT   1.0
Package with IoT components for Visual Studio
VisualStudio.Mac   1.0
Mac Extension for Visual Studio
Xamarin   4.7.10.38 (34c1b6c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
Xamarin.Android SDK   8.0.2.1 (HEAD/c2a33d8ea)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   11.3.0.47 (51128b8)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by JoshClose** [comment]
I'll have to install the Xamarin stuff and give it a try.

**Comment by rraallvv** [comment]
I'm seeing a similar error:

> Could not install package 'CsvHelper 6.1.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I tried to install the package for each target project instead of the shared one, and I was able to build the solution in that way, although the error is appearing again with a new project and that workaround is not working this time.

**Comment by rraallvv** [comment]
@JoshClose thanks for the info, since I wanted to stick to .Net Standard v1.3, as a workaround I used a dependency service that loads the entire table into a `List<List<string>>` through `CsvHelper` and added the CsvHelper package for each target platform.
