### ISSUE TITLE
POCO Properties not being recognized 

### ISSUE THREAD

**Issue by rufio620** [JoshClose/CsvHelper#867]
I am getting the following exception when attempting to use this library with an amazon mws report. The library is completely missing properties defined on my poco class.

amazon_order_id' is not a member of type 'UserQuery+_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_

```c#
void Main()
{
	var outputPath = $@"C:\Temp\azmwsreport.txt";
	using (var csv = new CsvReader(File.OpenText(outputPath)))
	{
		csv.Configuration.PrepareHeaderForMatch = header => header.Replace("-", "_");
		csv.Configuration.Delimiter = "\t";

		var rows = csv.GetRecords<_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_>();
		rows.Count().Dump();
		var count = 0;
		foreach (var row in rows)
		{
			count++.Dump();
			row.amazon_order_id.Dump();
		}
	}
}

// Define other methods and classes here
public class _GET_AMAZON_FULFILLED_SHIPMENTS_DATA_
{
	public string amazon_order_id { get; set; }

	public string merchant_order_id { get; set; }

	public string shipment_id { get; set; }
}
```

**Comment by rufio620** [comment]
Also the enumerator does not seem to work. The foreach loop body does not get executed in the code above.

**Comment by JoshClose** [comment]
There is some weird issue with LINQPad where you can't run it twice. The first time I get the row count just fine. The second time I get an error. I haven't dug into why that is. I have to open a new tab and copy/paste the code in there and run it again.

`GetRecords<T>()` return an `IEnumerable<T>`. What this means is it's forward only and you can only iterate over it once. That is why after doing a `Count`, there are no rows left when you do the `foreach`. If you were to do a `GetRecords<T>().ToList()` it will pull the whole set into memory and you could iterate over it multiple times. You will have the entire set in memory at once instead of a single record at a time though.

**Comment by rufio620** [comment]
Closing and reopening the linqpad queries seems to fix the issue as well. It only seems to manifest itself when you change the code after running it once. 

 Thanks for the info on the IEnumerable. I should have realized that count was forcing the enumerator to be executed and reading through the data causing the loop not to work.

**Comment by JoshClose** [comment]
No problem!

**Comment by rufio620** [comment]
I looked into the LinqPad issue and it appears to be an issue with the type existing in two different dynamically generated dll's (created by linqpad). Line 64 and 65 of ObjectRecordCreator.cs are the issue.  The call to the ReflectionHelper.CreateInstance uses ObjectResolver.Current.Resolve which I believe has a delegate which references the type in the older dll. If you check the type.Assembly.Module and recordType.Assembly.Module you will see they are in different dll's. The question I have is why is the call to ReflectionHelper.CreateInstance even required here. It seems like you are double creating the object just to get the type. Would it not make sense just to pass the recordType directly into the Expression.MemberInit? Below are snippets of the old and proposed fix. I did some preliminary testing and it appears to fix the issue. Let me know your thoughts.

Old
```c#
var type = ReflectionHelper.CreateInstance( recordType ).GetType();
body = Expression.MemberInit( Expression.New( recordType ), bindings );
```

Proposed New
```c#
// This is in case an IContractResolver is being used.
//var type = ReflectionHelper.CreateInstance( recordType ).GetType();
body = Expression.MemberInit( Expression.New( recordType ), bindings );
```

**Comment by JoshClose** [comment]
The comment there explains it, not very well ;)

```cs
// This is in case an IContractResolver is being used.
```

What that means is, you could have an `interface` like `IMyType` (or any type really) that resolves to something else, so you need to get an instance to see the actual type that is being used.

I'll look into caching the assembly along with the full type name. LINQPad is probably the only scenario where this will happen.

**Comment by JoshClose** [comment]
Also, your change causes 3 unit tests to break. :)

**Comment by JoshClose** [comment]
Just pushed 6.0.1 to NuGet which will fix this issue.

Thank you so much for figuring out the problem!

**Comment by JoshClose** [comment]
Actually, had to pull that. I accidently pushed some performance changes in there too which had breaking changes. I'll have to do some merging and get a new release out. I'll let you know when it's done.

**Comment by JoshClose** [comment]
Ok, 6.0.2 is on NuGet with just the NuGet fix.

**Comment by rufio620** [comment]
I figured you had a reason for doing it that way but, did not have the time to really dig into the rest of the code which explains why my change would have broken unit tests. Thanks for getting it fixed and released. Great project by the way. This really simplifies amazon feeds integration.

**Comment by JoshClose** [comment]
You're welcome and thanks!

**Comment by marcselman** [comment]
I'm sorry to say that with the latest version 6.1.0 this problem still occurs.

For anyone having this problem you can press Ctrl-Shift-F5 after every run to unload the query process.

**Comment by JoshClose** [comment]
Nice tip!

Do you have an example where this fails? I can look into it.

**Comment by marcselman** [comment]
Hm, I'm sorry. I think I'm mistaken. I can't reproduce it. I guess maybe there was an older version referenced in one of my scripts.
