### ISSUE TITLE
Anonymous type automapping does not work correctly

### ISSUE THREAD

**Issue by marcselman** [JoshClose/CsvHelper#870]
When I use ```csv.WriteRecords(records)``` I've noticed that sometimes I receive an  NullReferenceException.
After debugging your source I found the following code:

```
if ( context.WriterConfiguration.Maps[type] == null )
{
	context.WriterConfiguration.Maps.Add( context.WriterConfiguration.AutoMap( type ) );
}
var members = new MemberMapCollection();
members.AddMembers( c );
```

The ```context.WriterConfiguration.AutoMap( type )``` call does generate a valid ```ClassMap``` instance but when retrieving it with ```context.WriterConfiguration.AutoMap( type )``` it returns ```null```.
I was able to fix this but then another error occurred.

I guess the type retrieved by ```var type = GetGenericCsvClassMapType( map.GetType() ).GetGenericArguments().First();``` is different than the type passed to the AutoMap function for some reason.

For now I will try using reference mapping.

**Comment by marcselman** [comment]
After trying it with a Map class I found out something else.
I'm using LINQPad for testing and it looks like something breaks with:
```
at CsvHelper.ReflectionHelper.CreateInstance[T](Object[] args)
at CsvHelper.Configuration.Configuration.RegisterClassMap[TMap]()
```

I receive the following error (translated):
```
[A]CSVUserMap cannot be converted to [B]CSVUserMap. Type A comes from LINQPadQuery, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null in the context LoadNeither at location C:\Users\easyads laptop\AppData\Local\Temp\LINQPad5\_peanlztq\mddzqf\LINQPadQuery.dll. Type B is from LINQPadQuery, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null in the context LoadNeither at location C:\Users\easyads laptop\AppData\Local\Temp\LINQPad5\_peanlztq\ublhgw\LINQPadQuery.dll.
```

As you can see Type A and Type B have a different Temp folder generated by LINQPad.

**Comment by JoshClose** [comment]
There is an issue with linqpad and types being cached. https://github.com/JoshClose/CsvHelper/issues/867

**Comment by JoshClose** [comment]
I just published 6.0.2 to NuGet which has the LINQPad fix in it.

**Comment by JoshClose** [comment]
Were both of your issues caused by the linqpad problem?

**Comment by marcselman** [comment]
Yes, that must be it. Thanks for the quick fix!
And thanks for the great library.

**Comment by JoshClose** [comment]
You're welcome and thanks!

**Comment by marcselman** [comment]
I've been testing the new version but I still receive the NullReferenceException in LINQPad.
```
at CsvHelper.Configuration.MemberMapCollection.AddMembers(ClassMap mapping)
at CsvHelper.CsvWriter.WriteHeader(Type type)
at CsvHelper.CsvWriter.WriteRecords[T](IEnumerable`1 records)
```

**Comment by JoshClose** [comment]
Did you update your LINQPad NuGet assembly for CsvHelper to 6.0.2?

**Comment by JoshClose** [comment]
I found the same issue with caching in the writer. I'll get that fixed.

**Comment by JoshClose** [comment]
Just pushed 6.0.3 to NuGet that should fix this.
