### ISSUE TITLE
Validation Exception Message is too technical for user.

### ISSUE THREAD

**Issue by ndaonguyen** [JoshClose/CsvHelper#874]
Dear,

I'm trying to make the exception message more friendly for user to read and understand. 
Current the exception message is too technical for user:

Here is the message when ContactId is wrong format:
"Header matching ['ContactId'] names at index 0 was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue."

Can you please give me advice how can I know the ContactId is wrong format in validation exception? Or in the other words, where can I get the field that got wrong validation in the CsvHelper.ValidationException?

Thanks alot.

**Comment by JoshClose** [comment]
There should probably be a property on the `ValidationException` with the the field.

For now, I don't see a good way to get the data besides pulling it out of the exception message.

**Comment by ndaonguyen** [comment]
We have looked at every single information but couldn't find the property with the wrong validation fields. That's why need your advice. 

Because the message is too technical for user to understand, we looked for the error validation fields but couldnt find. And we stuck here.

Looking forward to receiving your response. Thanks.

**Comment by ndaonguyen** [comment]
So exactly where is the place we can find the wrong validation fields? Thanks

**Comment by JoshClose** [comment]
You need to pull it out of the `Exception.Message`. I need to add some properties on that exception with the extra information, so you don't have to do that.

**Comment by ndaonguyen** [comment]
Please let us know once you got any updates. Thanks

**Comment by mtissington** [comment]
I agree it seems very difficult to get a user friendly error message.

**Comment by AltairCA** [comment]
```csharp
Map(c => c.Agent).Name("AGENT").Validate(field => {
  if(field.Length > 1){
      throw new Exception($"ExceptionIdentifier:Field : {"AGENT"} is not valid at ");
  }
  return true;
});
```
then

```csharp
csv.Configuration.ReadingExceptionOccurred = (exception) => {
  if (exception.GetType() == typeof(ReaderException)) 
{
       string innterMessage = exception.InnerException?.Message;
       if (!string.IsNullOrWhiteSpace(innterMessage) && innterMessage.Contains("ExceptionIdentifier:"))
       {
             innterMessage = innterMessage.Replace("ExceptionIdentifier:", "");
              Log.Error($"{innterMessage} row {exception.ReadingContext.Row}");
        }
  
  } else {
   throw exception;
  }
 };
```

GG WP 🗡

**Comment by JoshClose** [comment]
You can set your own function and throw whatever you like with whatever message you like.
```cs
csv.Configuration.HeaderValidated = (bool isValid, string[] headerNames, int headerNameIndex, ReadingContext context) =>
{
    if (!isValid) throw new ValidationException("My custom message");
}
```
I will make the message more friendly and also put some properties on `ValidationException`.

**Comment by JoshClose** [comment]
Version 10.0.0 will have more friendly messages. Validation has been split up into `HeaderValidationException` and `FieldValidationException`. Each has some properties that pertain to the data it was given. Both inherit `ValidationException`.

**Comment by bmsalm** [comment]
Hey Josh - I don't see any useful information for `FieldValidationException`. Is there a way to write a custom exception, similar to what you're doing above for fields (opposed to headers)? Thank you in advance!

**Comment by jons-aura** [comment]
I have ````Map(m => m.Product_No).Validate(f => !string.IsNullOrWhiteSpace(f));```` in my ClassMap but the validation exception I'm getting has an empty string as the value for the field name when handled via ReadingExceptionOccurred. Is this expected? The exception message is just "Exception of type 'CsvHelper.FieldValidationException' was thrown." so I can't pull the name out of that either.

**Comment by zhangsquall** [comment]
> I have `Map(m => m.Product_No).Validate(f => !string.IsNullOrWhiteSpace(f));` in my ClassMap but the validation exception I'm getting has an empty string as the value for the field name when handled via ReadingExceptionOccurred. Is this expected? The exception message is just "Exception of type 'CsvHelper.FieldValidationException' was thrown." so I can't pull the name out of that either.

I have the same issue.  the Field is empty string in the exception.

**Comment by torndar** [comment]
I did a bit more digging and haven't verified it but I think the Field property is supposed to be the text value of the field itself. I wound up getting the name this way `string columnName = ex.ReadingContext.HeaderRecord[ex.ReadingContext.CurrentIndex];`
