### ISSUE TITLE
Auto-indexing doesn't work for sub properties

### ISSUE THREAD

**Issue by the-ress** [JoshClose/CsvHelper#876]
1. Create a mapping with subproperties:
```
Map(m => m.B.C.P3);
Map(m => m.P1);
Map(m => m.B.P2);
```
2. Write something using CsvWriter

Expected result: The fields should be written in order as defined: P3, P1, P2
Actual result: The fields are written in the following order: P3, P2, P1

**Comment by jamesbascle** [comment]
You have no control over the order unless you specify .Index() from my
understanding.

**Comment by JoshClose** [comment]
Yes, order is not guaranteed by .NET. https://blogs.msdn.microsoft.com/haibo_luo/2006/07/10/member-order-returned-by-getfields-getmethods/

If you want to control the order, you need to specify an index.
