### ISSUE TITLE
Handling exceptions thrown inside method "ConvertUsing"

### ISSUE THREAD

**Issue by OscarMolano** [JoshClose/CsvHelper#877]
Hello, thanks for the great library.

I created a class to map the rows to when reading a csv file and a class map extending from ClassMap in order to define the custom mapping i want for the class' properties using the columns in the row.

The mapping is working correctly but i have an issue, i'm doing some validation inside the ConvertUsing method for a property, and i want to throw an exception under certain conditions that can be caught in the block where i'm calling "csv.GetRecords<MyClass>()", but when i throw any exception inside the "ConvertUsing" function, i get an user-unhandled exception and end up catching that one instead of the original exception i threw.

Here's some example code, maybe someone can help.

Where i'm reading the file.
```
using (StreamReader file = File.OpenText(filePath))
{
        var csv = new CsvReader(file, csvConfiguration);
        try
        {
            rows = csv.GetRecords<MyClass>().ToList();
        }
        catch (CustomException ex)
        {
            // handle
        }
}
```

The map configuration of a property.
```
Map(m => m.Property)
.ConvertUsing(row =>
{
    throw new CustomException("Custom message");
});
```

**Comment by JoshClose** [comment]
All exceptions are wrapped with a `CsvHelperException` that adds extra information. 

Also, there is a validate method on a map.

```cs
Map( m => m.Property ).Validate( (string field) => field.Length > 0 );
```

**Comment by OscarMolano** [comment]
Thanks for answering Josh, the CsvHelperException did help me get the information i needed.
You mention the "Validate" method, in this case "Property" does not have an equivalent column in the csv file, it is generated by getting the values from several columns, something like the aggregate example in the documentation, and when i tried to pass a validate function to that map, it never seems to run that code.
I coded this and it went through with the mapping:
`Map( m => m.Property ).Validate((string field) => { return false; } ).ConvertUsing((row) => // code);`

**Comment by JoshClose** [comment]
Ah, I see. Glad you got it working!
