### ISSUE TITLE
Single line text values only setting

### ISSUE THREAD

**Issue by jababda** [JoshClose/CsvHelper#878]
Hi Josh,

I have a bit of an odd situation where some of the lines in the csv im parsing have an odd number of quote symbols \". 

When the reader hits the first \" it keeps reading from the file till it hits the next \" symbol, which for me is some 5000 rows away i.e.
line 1: a,b,c,d,"e
line 2: 1,2,3,4,5"
line 3: z,x,c,v,"b"

will return 2 rows with: 
a,b,c,d,"e\r\n1,2,3,4,5"
z,x,c,v,"b"

I think it would be a very useful to have a setting where if its true and any of the following characters during a quote sequence read is a line end it will throw a bad data exception. 

so instead 
line 1: a,b,c,d,"e -> Bad data exception
line 2: 1,2,3,4,5" -> Bad Data exception
line 3: z,x,c,v,"b" -> successful read

Apologies if this is an old/existing issue that I've missed.
Thanks

**Comment by JoshClose** [comment]
Field can contain a `\r\n` though, so I don't think there is a way to determine that.

**Comment by jababda** [comment]
Are there situations outside of quoted field that can contain end line characters?
And while a field can contain that it could also indicated a bad row like the situation I had. 

I got around it in the end by checking each row for an even number of " characters before attempting to parse it so its not tricky to get around, i just thought it might be a useful addition to allow the user to specify if the rows should allow multiline values :).

**Comment by JoshClose** [comment]
When you say `row`, you're referring to a text row. A CSV row (or field even) may contain an unlimited number of `\r\n`s. So if a field contains 10 `\r\n`s, that field will span 10 rows if you're looking at the file in a text editor.

**Comment by jababda** [comment]
I am aware. In my use case it would of been helpful to have a single line setting as at no point should the data i was dealing with have line breaks except at the termination of a csv row.

I would of thought this would be a fairly common characteristic csv data which is why i raised the issue.
But I've personally only worked with maybe a 100 odd csv files so that might just some bias on my part :).

**Comment by JoshClose** [comment]
Unfortunately this is very specific to your data. Line 1 and 2 are completely valid unless you hit the end of the file. Line 1 and 2 would actually just be line 1, which is the problem you're having. The only reason to have a field with `"`s around it is because the field contains a `"` or a `\r\n`.

What you want is to throw a `BadDataException` when a quoted field contains a `\r\n`. I will have to check into how much this will slow down the parser.

**Comment by b-maslennikov** [comment]
I also need this feature. It can be disabled by default.

**Comment by JoshClose** [comment]
This is complete and will be in version 10.0.0 on nuget.

There is a new config option `Configuration.LineBreakInQuotedFieldIsBadData` that defaults to `false`. If you set it to true, the `Configuration.BadDataFound` function is called, which defaults to throwing a `BadDataException`.
