### ISSUE TITLE
PrepareHeaderForMatch does not work (version 6.0.3)

### ISSUE THREAD

**Issue by developez** [JoshClose/CsvHelper#879]
```
using (TextReader fileReader = File.OpenText(@"test.csv"))
{
	var csv = new CsvReader(fileReader);
	csv.Configuration.PrepareHeaderForMatch = header =>
	{
		string n = header.Replace("Tipo de producto", "Tipo_de_producto");
		return n;
	};
	csv.Configuration.Delimiter = ";";
	csv.Configuration.HasHeaderRecord = true;
	data = csv.GetRecords<dynamic>().ToList();                
}
```

Content of test.csv

```
// Marca; Tipo de producto; Descripción; Referencia; EAN; Stock; Precio
// xxx; xxx; xxxx; xxxx; xxx; xxx; xxxx
// xxx; xxx; xxxx; xxxx; xxx; xxx; xxxx
```

The dynamic object still have got field "Tipo de producto", so I cannot access to the value, I debug the function when the replace is done, the value is returned properly (return n) but after "GetRecords()" the headers are not changed.

I mean that this does not work:

`data[0].Tipo_de_producto`

**Comment by JoshClose** [comment]
That's not used when reading dynamics... It probably should be though. I will have to rename it to `PrepareHeader` then I think, since it's not matching in this case.

**Comment by JoshClose** [comment]
This change has been pushed to NuGet in version 6.1.0.
