### ISSUE TITLE
Scientific values in csv cause Field with names ['Name'] at index '0' does not exist errors.

### ISSUE THREAD

**Issue by jsmug** [JoshClose/CsvHelper#881]
When you have data in a csv file containing scientific notation values, and you have headers in the csv file, the column with the scientific notation values cannot be found. I see in the debugger that the actual header is in the Context.HeaderRecord, but calling GetField<T>("ColumnName") fails with the aforementioned exception.

**Comment by JoshClose** [comment]
Can you give an example set of data?

**Comment by tiayi** [comment]
What about 'Name' and 'name'?
I think the indexer should provide ignore case option.

**Comment by JoshClose** [comment]
There is. You can just use `ToLower()`. http://joshclose.github.io/CsvHelper/configuration#prepareheaderformatch
