### ISSUE TITLE
Read Header and Validate

### ISSUE THREAD

**Issue by kechuwa** [JoshClose/CsvHelper#882]
I downloaded the current version 6.1 and trying to read a csv file with about 30 columns. I just need to read 5 columns and need to validate if the column name matches. I created a class and mapping to just read those 5 columns which is fine but I can't seem to validate headers and throw error. thank you.

**Comment by kechuwa** [comment]
I was able to do below
reader.Read();
reader.ReadHeader();
reader.ValidateHeader<MyClass>();

However, is there a way to detect the error  if headers do not match as I want to log it separately and present friendly message to user.

Also, is there a way to read header field names?

**Comment by JoshClose** [comment]
After doing `csv.Read()`, the row is accessible in `csv.Context.Record`. You could check that before proceeding.

**Comment by kechuwa** [comment]
if you don't mind, would you please provide example or point to the documentation, thank you for your time.

**Comment by JoshClose** [comment]
Actually, this method might work better for you. http://joshclose.github.io/CsvHelper/configuration#headervalidationcallback

**Comment by JoshClose** [comment]
It has been renamed to `HeaderValidated`.
