### ISSUE TITLE
Type Conversion examples.

### ISSUE THREAD

**Issue by Sahilshetye** [JoshClose/CsvHelper#883]
I know that type conversion wiki is in pipeline and will be soon come along with 3.0.0.
But I was hoping that you could at least provide a basic use case example for converting multiple columns to an array object using Array Converter.  

[Update] Am I missing something? The version that I have currently downloaded is  6.1.0(via NuGet) Is the versioning on nuget different than this repo?

**Comment by JoshClose** [comment]
I need to finish the docs. For now you can take a look at the unit tests here. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper.Tests/TypeConversion/ArrayConverterTests.cs

If you want to map by index, you specify the start and end index for the array. If you don't specify an end index, it will go to the end of the columns.

If you want to map by name, you specify the header name. This header name needs to be the same for every column though.
