### ISSUE TITLE
VB.net How do I actually use this?

### ISSUE THREAD

**Issue by Trones21** [JoshClose/CsvHelper#887]
I'm not very experienced with VB.net, but I am just super confused about 
`var csv = new CsvWriter( textWriter );`

I translated it to VB.net, different translators are giving me different results, but I keep getting an error with the textWriter part. 

Why can't I just write --
Dim csv As New CsvHelper.CsvWriter
 and then use the functions/methods with
csv.WriteField ,  csv.NextRecord , etc.

**Comment by JoshClose** [comment]
`TextWriter` is a base class https://msdn.microsoft.com/en-us/library/system.io.textwriter%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

You will usually have it attached to a file stream. Here is an example in C#. If you need me to translate to VB.NET I can try.

```cs
var stream = File.OpenWrite("path/to/file.csv");
var writer = new StreamWriter(stream);
var csv = new CsvWriter(writer);
```

**Comment by Trones21** [comment]
Thanks, I finally got it. I didn't understand the process. So we create a streamwriter object and then pass that as a parameter to the csvwriter object that we create. 
```
Dim sw As StreamWriter = My.Computer.FileSystem.OpenTextFileWriter(SaveAs, False)
Dim csv As New CsvHelper.CsvWriter(sw)
```

Would it be correct to say that your csvhelper makes use of the System.IO streamwriter class, but I have to first instantiate a streamwriter object so that csvhelper can use it?

**Comment by JoshClose** [comment]
It makes use of the `System.IO.TextWriter` class. `StreamWriter` is just one implementation of it.
