### ISSUE TITLE
Basic Read Example for VB.Net Needed

### ISSUE THREAD

**Issue by TimMakins** [JoshClose/CsvHelper#888]
I was wondering if anyone has a basic example of reading a CSV File in VB.NET? I created this example but can not get any output from it:
```vb
        Dim sr As StreamReader = New StreamReader("C:\client.csv")
        Dim csv = New CsvReader(sr)
        Dim CsvList As IEnumerable(Of Client) = csv.GetRecords(Of Client)()
        MessageBox.Show(CsvList.Count)
        For Each r As Client In CsvList
            Debug.WriteLine("record: " & r.CLIENT_NO & "  " & r.LICENCEE & "  " & r.POSTAL_STREET)
        Next

Public Class Client
    Private vCLIENT_NO As String
    Public Property CLIENT_NO As String
        Get
            Return vCLIENT_NO
        End Get
        Set(value As String)
            vCLIENT_NO = value
        End Set
    End Property
    Private vLICENCEE As String
    Public Property LICENCEE As String
        Get
            Return vLICENCEE
        End Get
        Set(value As String)
            vLICENCEE = value
        End Set
    End Property
    Private vPOSTAL_STREET As String
    Public Property POSTAL_STREET As String
        Get
            Return vPOSTAL_STREET
        End Get
        Set(value As String)
            vPOSTAL_STREET = value
        End Set
    End Property
End Class
```

Although the MessageBox shows the correct number of lines in the file, I get no output at all.
All I want to be able to do is to loop through the list, coping with lines such as:
```
57f7bg0,Joe Soap,"10 Main St, New Town"
```

**Comment by TimMakins** [comment]
As is normal with these things (!), shortly after posting, I found another post that showed I had omitted 'ToList()' as per:
Dim CsvList As IEnumerable(Of Client) = csv.GetRecords(Of Client)().ToList()

If anyone else has any helpful VB suggestions, it would be very nice to see them in the documentation, or below.

**Comment by JoshClose** [comment]
`GetRecords` returns an `IEnumerable` that `yields` results. That means only one row is in memory while it's iterating. Doing a `Count` will pull the entire CSV file into memory and do the count on it. You then can't do any more operations on the returned `IEnumerable` because the reading has completed. If you do a `ToList`, it will pull the entire file into memory and into a `List` that you can then do multiple LINQ operations on.

**Comment by TimMakins** [comment]
How interesting, Josh - thanks for sharing. I guess I am not so familiar with IEnumerables, and generally use List(Of Type). I must do more research. Please add these comments to a future 'VB' section of the Help notes - I am sure plenty of others will find them helpful too. HNY.

**Comment by JoshClose** [comment]
I'm planning on having the ability to switch between languages in the documentation.
