### ISSUE TITLE
HasFooterRecord Configuration Setting

### ISSUE THREAD

**Issue by RalfKoch** [JoshClose/CsvHelper#893]
We have a "Configuration.HasHeaderRecord" which works fine.
There should be a "Configuration.HasFooterRecord" as well since in some cases the file contains maybe summary information or else and the line should not be read.

**Comment by JoshClose** [comment]
There is no concept of a footer in CSV files. The first row may or may not be a header, and the rest is just data.

If you have a last row that is a footer, you can do a couple things. If the data is the same, just remove the last row from your list. If the data is different, you can test a field in the row before reading it.
