### ISSUE TITLE
   at CsvHelper.LinkedListExtensions.Drop[T](LinkedList`1 list Exception

### ISSUE THREAD

**Issue by M2xAy** [JoshClose/CsvHelper#895]
Hi 
firstly thank you for this Library.

I have some problem:

I am reading csv with this Code

```cs
try
{
    Assembly assembly = System.Reflection.Assembly.GetEntryAssembly();
    using (Stream stream = assembly.GetManifestResourceStream("asdf.DAL.Importdaten.xxx.csv"))
    {
        using (StreamReader reader = new StreamReader(stream, Encoding.GetEncoding("iso-8859-1")))
        {
            CsvReader csvReader = new CsvReader(reader);
            csvReader.Configuration.HeaderValidated = null;
            csvReader.Configuration.MissingFieldFound = null;
            csvReader.Configuration.Delimiter = ";";
            var xxx = csvReader.GetRecords<XXX>().ToList();
        }
    }
}
catch (Exception ex)
{
    return;
}
```

it works fine with other Models but with one Model I receive the following exception on Getrecords

Message = "Object reference not set to an instance of an object."

StackTrace = "   at CsvHelper.LinkedListExtensions.Drop[T](LinkedList`1 list, LinkedListNode`1 node)\r\n   at CsvHelper.Configuration.ClassMap.AutoMapMembers(ClassMap map, Configuration configuration, LinkedList`1 mapParents, Int32 indexStart)\r\n   at CsvHelper.Configu...

Do you have any idea ?

Thank you best regards

**Comment by JoshClose** [comment]
Are you able to give some sample data and class that causes this to fail?

**Comment by M2xAy** [comment]
Hi Josh,
Thank you for your answer.

I will create a sample solution for you.

Best regards

Von meinem iPhone gesendet

Am 12.01.2018 um 20:20 schrieb Josh Close <notifications@github.com<mailto:notifications@github.com>>:


Are you able to give some sample data and class that causes this to fail?

**Comment by M2xAy** [comment]
Hi Josh,
I created an Solution.

Can I send to your Mail adress ?

**Comment by JoshClose** [comment]
How big is it? I was thinking just a few rows you could paste here.

**Comment by M2xAy** [comment]
Hi Josh,
thank you for your answer.

Ok I will paste here
[csvimport.zip](https://github.com/JoshClose/CsvHelper/files/1641994/csvimport.zip)

**Comment by JoshClose** [comment]
The issue is because you have multiple circular references. Use a `ClassMap` and eliminate those.

This uncovered an issue in my code where the circular reference isn't detected because it's happening in multiple classes. I'll need to fix that.

**Comment by JoshClose** [comment]
This is fixed and in version 6.1.1 on NuGet.

**Comment by JoshClose** [comment]
I still suggest using a `ClassMap` though.

**Comment by M2xAy** [comment]
Hei Hi Josh, thank you very much for your nswer and Fixing the Problem.

I will try now and let you know.

Best regards

**Comment by M2xAy** [comment]
Hi Josh,

it works Thank you very much.

Best regards from switzerland
