### ISSUE TITLE
Error : {"Fields 'EntitySetName' do not exist in the CSV file."}

### ISSUE THREAD

**Issue by nolme** [JoshClose/CsvHelper#897]
I try to import a simple CSV file to database.
CSVHelper : 2.16.3 or 6.10.0
Data Model has been generated by DevArt Entity Developper 6.2.384
.NET Framework : 4.5

The short code is available here to reproduce the problem : 
[https://wetransfer.com/downloads/e085f9fa6c898b4fcdb4e1ecc12cf69a20180114224621/e64df35e87a7ff8a791b265eb345622020180114224621/7e4e59](https://wetransfer.com/downloads/e085f9fa6c898b4fcdb4e1ecc12cf69a20180114224621/e64df35e87a7ff8a791b265eb345622020180114224621/7e4e59)

**Comment by JoshClose** [comment]
Your `Country` class inherits `EntityObject`. You'll want to create a mapping and only map the properties you want written to the CSV file. http://joshclose.github.io/CsvHelper/mapping

**Comment by nolme** [comment]
Thanks for the answer :).

I've modified my sample code. Because AutoMap don't work, I've done it by myself : 
`public sealed class MyClassMap : ClassMap<Country>
        {
            public MyClassMap()
            {
                Map(m => m.Id);
                Map(m => m.Name);
                Map(m => m.TranslateTag);
                Map(m => m.ImageIndex);
                Map(m => m.CountryShortCode);
            }
        }

        static void Main(string[] args)
        {
            try
            {
                string csvFile = @"..\..\..\_CSV\Countries2.csv";                char separator = ';';
                //string csvFile = @"..\..\..\_CSV\Countries3.csv"; char separator = ',';
                using (TextReader reader = File.OpenText(csvFile))
                {
                    var csv = new CsvReader(reader);
                    csv.Configuration.RegisterClassMap<MyClassMap>();
                    csv.Configuration.Delimiter = separator.ToString();
                    csv.Configuration.Encoding = Encoding.Default;
                    var records = csv.GetRecords<Country>();

                    foreach (Country rec in records)
                    {
                        Console.WriteLine(rec.Name);                        
                    }
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }`

Now it nearly works. Only encoding seems to have no effect. I try with CsvReader alternative solution and Encoding.Default give me the good result with accented characters.
CSV files are available here if you want to make a try on a non french computer :
[https://we.tl/R82IhX4WUG](https://we.tl/R82IhX4WUG) .

Thanks again for help.

**Comment by JoshClose** [comment]
You're using `File.OpenText` which opens the file in `UTF-8` encoding. If you want to use a different encoding, do this instead.

```cs
using (var stream = File.OpenRead(@"path\to\file.csv"))
using (var reader = new StreamReader(stream, Encoding.Default))
using (var csv = new CsvReader(reader))
{
...
}
```
If you read the intellisense docs on `csv.Configuration.Encoding` it says

> Gets or sets the encoding used when counting bytes

You don't have `csv.Configuration.CountBytes` on, so you don't need to set the encoding in the config.

**Comment by nolme** [comment]
nice :)
thanks.

**Comment by JoshClose** [comment]
You're welcome!
