### ISSUE TITLE
Is there a way to selectively format fields when writing?

### ISSUE THREAD

**Issue by jkewley** [JoshClose/CsvHelper#898]
Let's say I have a date field in my input source that is optional and may not be present when reading the file. I might do something like this:
```
Map(m => m.DateOfDeath).ConvertUsing(row =>  {
    string field = row.GetField("DateOfDeparture");
    if (DateTime.TryParse(field, out DateTime parsedDate))
          return parsedDate;
    return DateTime.MinValue;
});
```

So now my POCO has either a valid date of death or DateTime.Min. 

I'd like to format the date for my CsvWriter if it's a valid date, or have it write an empty string if it's DateTime.Min. I may have other date fields on my POCO where my formatting options would differ. I guess what I'm looking for is something like this:
```
Map(m => m.DateOfDeath).ConvertUsing(row =>  {
    string field = row.GetField("DateOfDeparture");
    if (DateTime.TryParse(field, out DateTime parsedDate))
          return parsedDate;
    return DateTime.MinValue;
}.WriteUsing(field => 
    if(field==DateTime.Min) return string.Empty;
    return field.ToString("MM/dd/yyyy");
});
```
TypeConverters look close to me, but they would impact both reads and writes, correct? 

I see the Format attribute but it didn't seem to affect the output when I tried it like this:
```
public class ZipRecord
{
    public string Jurisdiction { get; set; }
    [Format("D")]
    public int ParticipantCount { get; set; }
}
```
Admittedly, this was a stab in the dark.

**Comment by JoshClose** [comment]
There is an overload for `ConvertUsing` that is for writing.

```cs
ConvertUsing( Func<TClass, string> convertExpression )
```
