### ISSUE TITLE
SQL Conversion

### ISSUE THREAD

**Issue by kevanhanson2814** [JoshClose/CsvHelper#900]
Hi Josh, CsvHelper is great, thanks, I have run into a problem.

I have a CSV file of Project data that I am trying to map to classes that eventually end up refreshing an SQL data base. Everything works fine until I come to a field that has been converted to a sub table. For instance one Column in the CSV file is Probability. In the CSV file it would appear as one of 100, 90, 75, 50, 20, 0. These values have their own Probability class and in my Project class that I am trying to populate I have a ProbabilityID and a navigation  Probability class with ProbabilityID and Probability value. I have four fields that need to be mapped this way. 

I expect it needs to be mapped line by line but could point me in the direction of the most efficient way of doing this? Thanks.

**Comment by JoshClose** [comment]
Can you give an example of the classes and a row of data?

**Comment by kevanhanson2814** [comment]
I replied to the email I received but I don't see it here. Did you get the files?

**Comment by JoshClose** [comment]
No. They go through github, so I'm guessing they just get removed.

**Comment by kevanhanson2814** [comment]
[report1516042874419.zip](https://github.com/JoshClose/CsvHelper/files/1640233/report1516042874419.zip)


[Models.zip](https://github.com/JoshClose/CsvHelper/files/1640223/Models.zip)

Here they are.

**Comment by kevanhanson2814** [comment]
Please delete them after you get a copy if you can.

**Comment by kevanhanson2814** [comment]
If that didn't work I can email them with an address

**Comment by kevanhanson2814** [comment]
Can you let me know whether you got the files? I'm not sure which time zone you are in, but if you could let me know I can delete the public link.

**Comment by kevanhanson2814** [comment]
Thanks, all classes involved and the csv file is attached.

Kevan R. Hanson

**Comment by kevanhanson2814** [comment]
How would I then add the map to the configuration? If I try to pass the lists to the map class constructor as so..>> csv.Configuration.RegisterClassMap<ProjectMap>( Probabilities, BusinessUnits, ProjectStatusItems, ProjectLocations);

The error is no overload for RegisterClassMap takes 4 arguments even though the constructor is 
public ProjectMap(List<Probability> Probabilities, List<BusinessUnit> BusinessUnits, List<ProjectStatus> ProjectStatusItems, List<ProjectLocation> ProjectLocations)
        {
}
Its probably just a syntax error on the RegisterClassMap line but it has me stumped.

**Comment by JoshClose** [comment]
It takes in an instance.
```cs
var map = new ProjectMap(List<Probability> Probabilities, List<BusinessUnit> BusinessUnits, List<ProjectStatus> ProjectStatusItems, List<ProjectLocation> ProjectLocations);
csv.Configuration.RegisterClassMap(map);
```

**Comment by kevanhanson2814** [comment]
OK, got it to work. That makes sense. Thanks.

**Comment by JoshClose** [comment]
You're welcome!
