### ISSUE TITLE
Import NULL

### ISSUE THREAD

**Issue by M2xAy** [JoshClose/CsvHelper#901]
Hi Josh,
I am again.

I have question, in my csv file I have field that I will Import as NULL, but in SQL Databse is this not NULL, how can I Import NULL? 

Best regards

**Comment by JoshClose** [comment]
If you want a field value to evaluate as `NULL`, you do this in the mapping.

```cs
Map(m => m.Id).TypeConverterOptions.NullValues("NULL");
```

You can put whatever text you want to evaluate to `NULL` in there. I don't understand how this relates to SQL.

**Comment by M2xAy** [comment]
Ahh Josh Thank you very much for your answer. I will try it.
in sql database was NULL as a string if you want I can make it a example but I am now in holiday, I can do this after 2 weeks.

Best regards

**Comment by JoshClose** [comment]
Let me know if it doesn't work.

**Comment by M2xAy** [comment]
Hi Josh,

What is ClassMap<Test> ? Where is this ClassMap ? 

Thank oyu very much for your answer.

Best regards

void Main()
{
    using (var stream = new MemoryStream())
    using (var writer = new StreamWriter(stream))
    using (var reader = new StreamReader(stream))
    using (var csv = new CsvReader(reader))
    {
        writer.WriteLine("Id,Name");
        writer.WriteLine("1,one");
        writer.WriteLine("2,two");
        writer.Flush();
        stream.Position = 0;
        
        csv.Configuration.RegisterClassMap<TestMap>();
        csv.GetRecords<Test>().ToList().Dump();
    }
}

public class Test
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int RowNumber { get; set; }
}

public sealed class TestMap : ClassMap<Test>
{
    public TestMap()
    {
        Map(m => m.Id);
        Map(m => m.Name);
        Map(m => m.RowNumber).ConvertUsing(row => row.Context.RawRow);
    }
}

**Comment by M2xAy** [comment]
I found It :)
