### ISSUE TITLE
Can CsvHelper parse custom EDI-style files?

### ISSUE THREAD

**Issue by quartilesoftware** [JoshClose/CsvHelper#904]
I have a custom format CSV file in which each record spans several rows, in the style of an EDI file. However, the file is not one of the recognised standard EDI formats (Tradacoms, or Edifact), but does have separate rows for each record in the file with each row containing, for example: a header row; specification rows; a variable number of detail rows; a footer row. 

Can CsvHelper be used to read and parse such a file into a corresponding EDI-style class?

**Comment by JoshClose** [comment]
Can you paste a small example here?

**Comment by quartilesoftware** [comment]
It's a very simple message structure - each row begins with a three-letter identifier to indicate: beginning of message; record header; record detail row(s); record trailer; end of message (MSG; HDR; DTL;TRL;END respectively). A typical file containing one message with two records with one and two detail rows might look like this:

MSG, MyTestCo,DateAndTimeString,LocationIdentifer,TypeOfMesage
HDR, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
TRL record rowcount,identifier
HDR, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
DTL, <alphabetic, integer, decimal and date values separated by commas>
TRL, record rowcount,identifier
END, message recordcount,identifier

**Comment by JoshClose** [comment]
You can loop the records and get the first field and check what type it is. Then you can constructor your object based on the next several rows and end it on the trail.

```cs
while (csv.Read())
{
	var rowType = csv.GetField(0);
}
```

You can register multiple mappings if you have several different object types you want to get. You can also just read fields individually.

**Comment by quartilesoftware** [comment]
Thanks,

That’s more or less what I’d already started implementing, so it’s good to hear your confirmation of the approach.
