### ISSUE TITLE
How to ignore a line full of blank values

### ISSUE THREAD

**Issue by scottpantall** [JoshClose/CsvHelper#907]
I get a CSV file from a client. It has headers and rows upon rows of useful data. CSVHelper works great!

But then I get to the end of the file where the last 2 lines look like this:

2nd to last row: `,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`
Last row: `(115943 row(s) affect,ed),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

I can ignore the last row with `csv.Configuration.ShouldSkipRecord = row => row[0].StartsWith("(");` but I'm having a hard time figuring out how to ignore the row full of empty values.

**Comment by JoshClose** [comment]
```cs
csv.Configuration.ShouldSkipRecord = row => row.All(string.IsNullOrEmpty);
```

**Comment by scottpantall** [comment]
Thanks! That allows me to skip the line full of blank fields!

But now I can only ignore the line full of blank fields and not the last row .

**Comment by scottpantall** [comment]
Never mind. Thanks the quick response. I got it working now.

`csv.Configuration.ShouldSkipRecord = row =>
            {
                return (row[0].StartsWith("(") || row.All(string.IsNullOrEmpty));
            };`
