### ISSUE TITLE
How to read an unquoted CSV file?

### ISSUE THREAD

**Issue by mlouwn** [JoshClose/CsvHelper#909]
Hi all,

I can't see how to configure the reader, for reading a file that isn't quoted.

Example:
Name;Hobby;FavColor
John;Fishing;Red

I tried something like this, and hoped to get "John". Instead I get an exception:

> Field with names ['Name'] at index '0' does not exist. You can ignore missing fields by setting MissingFieldFound to null

```cs
using (var csv = new CsvHelper.CsvReader(reader, new CsvHelper.Configuration.Configuration()
{
   HasHeaderRecord = true,
   Delimiter = ";"
}))
{
   while (csv.Read())
   {
      var name = csv.GetField<string>("Name");
   }
}
```
I get these files from a supplier, and can't make them change the format.

I hope someone can help me.

Best Regards,
Morten

**Comment by JoshClose** [comment]
If you call `Read()` manually, you'll need to call `ReadHeader()` also.

```cs
csv.Read();
csv.ReadHeader();
while (csv.Read())
{
...
}
```

**Comment by Tony-Pappas** [comment]
Hi Josh,

I'm still getting null when trying to read unquoted csv file. It works fine if all the fields are quoted. Here's the read code I'm using:
`               
using (var csv = new CsvReader(reader))
{
	csv.Configuration.MissingFieldFound = null;

	for (int i = 0; i < HeaderLineCount; i++)
		csv.Read();

	if (csv.ReadHeader() == false)
		throw new Exception("Can't read header");

	while (csv.Read())
		LoadRecord(csv);
}
`
Any idea what's going on?

**Comment by JoshClose** [comment]
`Configuration.IgnoreBlankLines` is `true` by default, so if the lines you're trying to skip at the beginning are blank, they're already being skipped.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("");
		writer.WriteLine("");
		writer.WriteLine("Name;Hobby;FavColor");
  		writer.WriteLine("John;Fishing;Red");
		writer.Flush();
		stream.Position = 0;

		csv.Configuration.Delimiter = ";";
		csv.Configuration.IgnoreBlankLines = false;
		
		for (var i = 0; i < 3; i++)
		{
			csv.Read();
		}
		
		csv.ReadHeader();
		
		while (csv.Read())
		{
			csv.GetRecord<Test>().Dump();
		}
	}
}

public class Test
{
	public string Name { get; set; }
	public string Hobby { get; set; }
	public string FavColor { get; set; }
}
```

**Comment by Tony-Pappas** [comment]
Wow, you're fast, thanks for the quick response! I just came back to delete my question, as it appears to be an encoding issue. The files are encoded as UCS-2 Little Endian. Could this be the problem?

**Comment by JoshClose** [comment]
The encoding shouldn't matter. As long as the line ending `\r\n`, the quote `"`, and the configured delimiter can be read, it should be fine.

I found out what was happening by outputting `csv.Context.Record` on each loop.

**Comment by Tony-Pappas** [comment]
Ahh yes, thanks for the tip. I'm getting what looks to be null chars before each char:
'''
\03\08\00\0d\0d\0f\02\04\0-\04\01\09\03\0-\04\0a\04\06\0-\08\01\02\0d\0-\00\07\02\08\0f\09\01\0e\0b\09\07\0e\0
'''

**Comment by JoshClose** [comment]
You need to set your encoding on the `TextReader`.

**Comment by Tony-Pappas** [comment]
Yep, I needed Unicode. Thanks for your help man! And thank you for CsvHelper!

**Comment by JoshClose** [comment]
No problem!
