### ISSUE TITLE
ShouldUseConstructorParameters = type => true fails on native types

### ISSUE THREAD

**Issue by magicmoux** [JoshClose/CsvHelper#911]
Found out that `ShouldUseConstructorParameters = type => true` recurses on the class constructor's parameters types so it finaly tries to find constructors for some intrinsic c# types (like Int32)  which have no constructors.

this results in making 
`type.GetConstructors().OrderByDescending(c => c.GetParameters().Length).First() ` 
at ReflectionExtensions.cs line 109 fail with an Empty Collection Exception.

Suggested Fix would be : 

- replace `.First()` by a `.FirstOrDefault() call `
- At least in ClassMap.cs line 402 (in méthod AutoMapConstructorParameters), check whether the parameter's type has a constructor to fall back to the last case if not.

Using this, all tests still succeed but there could be other side effects I'm not aware of

Could  you please check ?

**Comment by magicmoux** [comment]
Hi Josh, here's a simple test

        [TestMethod]
        public void ShouldUseConstructorParametersTrueTest()
        {
            var definition = new
            {
                Id = 0,
                Name = string.Empty,
            };

            using (var stream = new MemoryStream())
            using (var writer = new StreamWriter(stream))
            using (var reader = new StreamReader(stream))
            using (var csv = new CsvReader(reader))
            {
                writer.WriteLine("1,one");
                writer.Flush();
                stream.Position = 0;

                csv.Configuration.HasHeaderRecord = false;
                csv.Configuration.ShouldUseConstructorParameters = type => true;

                var records = csv.GetRecords(definition).ToList();
            }
        }

**Comment by JoshClose** [comment]
This kind of doesn't make sense to me... If `ShouldUseConstructorParameters` returns true, we shouldn't have to check again that it has a constructor. That was the purpose of having the `ShouldUseConstructorParameters` function. If that's what you want, why not just change

```cs
csv.Configuration.ShouldUseConstructorParameters = type => true;
```
to
```cs
csv.Configuration.ShouldUseConstructorParameters = type => type.HasConstructor();
```
