### ISSUE TITLE
Special symbols escaping

### ISSUE THREAD

**Issue by MakarovSoftware** [JoshClose/CsvHelper#917]
Hi!

I have a problem, I'm trying to use CsvSerializer to serialize strings, ";" is a delimiter, for example. And my strings include some special chars like delimiter char, like quote char and etc.

And Serializer just put it in CSV as is, without escaping this symbols, and of course csvhelper can't read this csv back. What am I doing wrong?

Thank you!

**Comment by JoshClose** [comment]
Use `CsvWriter` instead. All of that should work then.

**Comment by MakarovSoftware** [comment]
If I try to use CsvWriter.WriteRecord or WriteRecords for writing string values I get this exception:

"Additional information: Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?"

**Comment by JoshClose** [comment]
Those are for writing class objects. If you want to write individual fields, use `WriteField`. http://joshclose.github.io/CsvHelper/writing#writing-fields
