### ISSUE TITLE
Bug in WriteHeader<T>()

### ISSUE THREAD

**Issue by kabua** [JoshClose/CsvHelper#919]
Looking at the code to `writer.WriteHeader<MyClass>();` it appears that a call to `NextRecord()` is missing. Therefore the first record is appended to the header line.

**Expected**:
Ln#,StartDateTime,EndDateTime,mId,wId
1,8/22/2005 1:26:00 AM,8/22/2005 1:27:00 AM,506,48026
2,1/17/2005 2:10:00 PM,1/17/2005 2:11:00 PM,1270,4150

**Actual**:
Ln#,StartDateTime,EndDateTime,mId,wId,1,8/22/2005 1:26:00 AM,8/22/2005 1:27:00 AM,506,48026
2,1/17/2005 2:10:00 PM,1/17/2005 2:11:00 PM,1270,4150

**Note**: that the last property on MyClass is being Ignored. But I don't think this has anything do to with the problem.

**Comment by JoshClose** [comment]
That is intentional. It allows you to write a header based on a class, and still be able to write more on that line if you need. You're required to call `NextRecord` to get to the next line.

**Comment by kabua** [comment]
Thanks. I don't think the documentation didn't explain that very well then.

**Comment by JoshClose** [comment]
What part do you think should be more explicit?

http://joshclose.github.io/CsvHelper/writing#writing-a-single-record

> Sometimes you want to write individual records by themselves. When you are done writing the row, don't forget to call NextRecord to flush the data and write the line ending.

**Comment by kabua** [comment]
I didn't look under writing a single record. That wasn't my need.

**Comment by JoshClose** [comment]
A single record at a time, versus all records.
