### ISSUE TITLE
Deserialization, by definition, should support non-public default Constructors...

### ISSUE THREAD

**Issue by kabua** [JoshClose/CsvHelper#920]
Can't deserialize class with a private or protected default constructor.

For example:
```
public class Sample
{
  public Sample(string a, string b) {...}

  // Should be used by Deserializtion
 private Sample() {}

 public string A { get; private set; }
 public string B { get; private set; }
}
```
We get some bogus error regarding header verification.

In object lifetime, there is a difference between Instantiating a new object and rehydrating an existing object. During the instantiating stage, only the public ctors are valid. However, the rehydrating stage (i.e. Deserialization) doesn't (nor should they have) these restrictions. Therefore, frameworks like this one should (and I would say must) support private and protected default constructors. For example, Entity Framework and Json.NET support them.

P.S. I also tried `reader.Configuration.ShouldUseConstructorParameters = type => type == typeof (Sample);` but that didn't work either.

**Comment by JoshClose** [comment]
Does your bogus header error say something about not being able to find a header matching `a`? 

If I do this

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("A,B");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Sample
{
	public int Id { get; private set; }
	public string Name { get; private set; }
	
	private Sample() { }
	
	public Sample(int id, string name)
	{
		Id = id;
		Name = name;
	}
}
```

I get an error message

> Header matching ['a'] names at index 0 was not found. If you are expecting some headers to be missing and want to ignore this validation, set the configuration HeaderValidated to null. You can also change the functionality to do something else, like logging the issue.

If you notice, that is a lowercase `a`. If I change my constructor parameters to uppercase, then it works fine. You probably don't want to do that, so what you can do is change a config setting to allow matching against lowercase.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("A,B");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.PrepareHeaderForMatch = header => header.ToLower();
		csv.GetRecords<Sample>().ToList().Dump();
	}
}

public class Sample
{
	public int A { get; private set; }
	public string B { get; private set; }
	
	private Sample() { }
	
	public Sample(int a, string b)
	{
		this.A = a;
		this.B = b;
	}
}
```

**Comment by kabua** [comment]
Okay, interesting point about the non-default constructor. But my real question is how do I get the private or protected default ctor to be called? 

The problem with my example is that it wasn't showing the full structure. I have a base class (with two properties) and a derived class (with more properties). The derived class had a ctor that only takes 2 params but the base class takes none. The error was complaining about the first property on the base class. 

So it appears that your logic is tring to match all the properties to a single ctor, which in my case there isn't one. Can I put a CsvConstructor attribute on the ctor that I want used? Or can the framework just instantiate a raw class (from the private/protected default ctor) and then 'push' the values into the correct property?

**Comment by JoshClose** [comment]
You can use the `Configuration.GetConstructor` function to select which constructor you want. By default, it chooses the constructor with the most parameters.

The default is this.

```cs
csv.Configuration.GetConstructor = type => type
	.GetConstructors()
	.OrderByDescending( c => c.GetParameters().Length )
	.First();
```

You could do the reverse of that, or just check for no parameters.

```cs
csv.Configuration.GetConstructor = type => type
	.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance)
	.Where(c => c.GetParameters().Length == 0)
	.First();
```

**Comment by kabua** [comment]
Interesting, I'll look into it. Thanks.

**Comment by kabua** [comment]
Okay, I've tried calling my private Ctor, which looks similar to your example:

```
public class Sample
{
	public int A { get; private set; }
	public string B { get; private set; }
	
	private Sample() { }
	
	public Sample(int a, string b)
	{
		this.A = a;
		this.B = b;
	}
}
```
and I set the reader like so:
```
reader.Configuration.GetConstructor = type =>
    type.GetConstructors(BindingFlags.NonPublic | BindingFlags.Instance)
    .OrderBy(c => c.GetParameters().Length)
    .First();
```

But then I got this exception message:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=No public parameterless constructor found.
  Source=CsvHelper
  StackTrace:
   at CsvHelper.ReflectionHelper.CreateInstanceDelegate(Type type, Object[] args)
```

**Comment by JoshClose** [comment]
It looks like the problem lies in `ReflectionHelper`. When it goes to create the class it can't find the private constructor. I turned on private for all and there are no unit tests failing, so I think it should be ok to just do that to fix this problem.

**Comment by JoshClose** [comment]
This passes with that fix in place.

```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace CsvHelper.Tests
{
	[TestClass]
    public class Issue920
    {
		[TestMethod]
        public void Test1()
		{
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvReader( reader ) )
			{
				writer.WriteLine( "A,B" );
				writer.WriteLine( "1,one" );
				writer.WriteLine( "2,two" );
				writer.Flush();
				stream.Position = 0;

				csv.Configuration.GetConstructor = type =>
					type.GetConstructors( BindingFlags.NonPublic | BindingFlags.Instance )
					.OrderBy( c => c.GetParameters().Length )
					.First();
				csv.Configuration.IncludePrivateMembers = true;
				var records = csv.GetRecords<Sample>().ToList();
			}
		}

		private class Sample
		{
			public int A { get; private set; }
			public string B { get; private set; }

			private Sample() { }

			public Sample( int a, string b )
			{
				A = a;
				B = b;
			}
		}
	}
}
```

**Comment by JoshClose** [comment]
Version 7.0.1 is now on NuGet and has this fix in it.
