### ISSUE TITLE
Counting how many rows are in a CSV (excluding header)?

### ISSUE THREAD

**Issue by reloaded** [JoshClose/CsvHelper#922]
Is there a way to efficiently count how many rows are in a CSV file without calling GetRecords()?

I need to get the total number of CSV rows, save it to a database table and then start processing each record one by one. What's the best way to achieve this using CSVHelper?

**Comment by reloaded** [comment]
Turns out that `.Dump()` is not a method on `csv.Context.Row` because `Row` is an integer. Should there be some other API call into CSVReader that I need to call to reset the state?

**Comment by JoshClose** [comment]
`.Dump()` is a LINQPad method that will spit out any object. https://www.linqpad.net/

**Comment by reloaded** [comment]
aha, thanks @JoshClose
