### ISSUE TITLE
Quoted value with commas in first column

### ISSUE THREAD

**Issue by robhoward** [JoshClose/CsvHelper#923]
Version 6.1.1.

If the first column in the CSV is a quoted value with commas, subsequent quoted columns will cause a bad data exception.

Example:
"Aegon USA, Inc.",11857,https://www.aegon.com
"Allen-Bradley Company, Inc.",1341,http://ab.rockwellautomation.com/

A bad data exception is thrown for the second row.

Work around - change the column value order:
11857,"Aegon USA, Inc.",https://www.aegon.com
1341,"Allen-Bradley Company, Inc.",http://ab.rockwellautomation.com/

Cheers,
Rob

**Comment by JoshClose** [comment]
Can you give a failing example? This works for me

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Name,Id,Url");
		writer.WriteLine("\"Aegon USA, Inc.\",11857,https://www.aegon.com");
		writer.WriteLine("\"Allen-Bradley Company, Inc.\",1341,http://ab.rockwellautomation.com/");
		writer.Flush();
		stream.Position = 0;
		
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public string Name { get; set; }
	public int Id { get; set; }
	public string Url { get; set; }
}
```

**Comment by robhoward** [comment]
Hi Josh,

Here is an example that is failing. Your code works, so maybe it has
something to do with the file which I've also attached?

This generates a bad data exception on the 2nd call to WriteLine:

        static void Main(string[] args)
        {
            string path = AppDomain.CurrentDomain.BaseDirectory +
"test.csv";

            using (var stream = File.OpenRead(path))
            using (var reader = new StreamReader(stream))
            using (var csv = new CsvReader(reader))
            {
                stream.Position = 0;
                csv.Configuration.HasHeaderRecord = false;

                // Process rows
                while (csv.Read())
                {
                    Console.WriteLine(csv[0]);
                }
            }
        }

Thanks,
Rob

Founder, DailyStory

*DailyStory - know how you found your best customers.*dailystory.com
<http://info.dailystory.com/r/87yna> | 214-714-0059

**Comment by JoshClose** [comment]
Attachments don't make it into github. Can you post a link to the file?

**Comment by robhoward** [comment]
Sure, here you go:

https://www.dropbox.com/s/9arabkaa8fqdnb6/test.csv?dl=0

Founder, DailyStory

*DailyStory - know how you found your best customers.*dailystory.com
<http://info.dailystory.com/r/87yna> | 214-714-0059

**Comment by JoshClose** [comment]
This is due to bug #914. Follow that bug for a fix.
