### ISSUE TITLE
Is it possible to conditionally map fields?

### ISSUE THREAD

**Issue by saviourofdp** [JoshClose/CsvHelper#924]
I want to map properties to different csv fields columns depending on other property values in the same object, say
```cs
var data = new Foo () 
{
    value = (object) v,
    DataType = v.GetType()
};
```

stringValue|intValue|boolValue
-------------|---------|------------
example||
||1|
|||true

Is this possible? I couldn't find an obvious way of doing it

**Comment by JoshClose** [comment]
You'd probably be better off not using a map in that case. Your map would consist of all `ConvertUsing` calls, which would be the same as just manually getting the fields and assigning them to properties.
