### ISSUE TITLE
NUll values mapping 

### ISSUE THREAD

**Issue by M2xAy** [JoshClose/CsvHelper#927]
Ho Josh,
mapper doe snot working for me.

I created a class:
Code:
```    
public  class ProbenahmestelleCsvMapper : ClassMap<Probenahmestelle>
{
    public ProbenahmestelleCsvMapper()
    {
        Map(m => m.aa).TypeConverterOption.NullValues("NULL");
        Map(m => m.bb).TypeConverterOption.NullValues("NULL");
    }
}
```

I consume this 
```cs
csvReader.Configuration.TypeConverterCache.GetConverter(typeof( ProbenahmestelleCsvMapper));
//csvReader.Configuration.TypeConverterCache.GetConverter<ProbenahmestelleCsvMapper>();
```

Is this false?

**Comment by JoshClose** [comment]
What are you trying to do? Set `"NULL"` as a null value for every type? Only specific types? Only for specific properties of your class?

**Comment by M2xAy** [comment]
Hi Josh,
I use csvimport for seeding the database.


                using (Stream stream = assembly.GetManifestResourceStream("Delphi.DataImport.Importdaten.Probenahmestellen.csv"))
                {
                    using (StreamReader reader = new StreamReader(stream, Encoding.UTF8))
                    {
                        CsvReader csvReader = new CsvReader(reader);
                        csvReader.Configuration.HeaderValidated = null;
                        csvReader.Configuration.MissingFieldFound = null;
                        csvReader.Configuration.Delimiter = ";";
                        //csvReader.Configuration.TypeConverterOptionsCache.GetOptions<string>().NullValues.Add("NULL");
                        csvReader.Configuration.RegisterClassMap(new ProbenahmestelleCsvMapper());
                        var probenahmestellen = csvReader.GetRecords<Probenahmestelle>().ToArray();
                        foreach (var item in probenahmestellen)
                        {
                            context.TblProbenahmestellen.Add(item);
                            context.SaveChanges();
                        }
                    }
                }


 public sealed  class ProbenahmestelleCsvMapper : ClassMap<Probenahmestelle>
    {
        public  ProbenahmestelleCsvMapper()
        {
            AutoMap();
            Map(m => m.xxx).TypeConverterOption.NullValues("NULL");
            Map(m => m.Fkxxx).TypeConverterOption.NullValues("NULL");
        }
    }



this work now with automap, I wanna do this without automap for this I created Class Map

How can I do this without registerclass and automap and only configure my class map

Best regards

**Comment by JoshClose** [comment]
You don't want to use `AutoMap` inside your `ClassMap`? Just list all of the properties you want to map individually.
