### ISSUE TITLE
CsvHelperException in production server .NET Core 2.1.4

### ISSUE THREAD

**Issue by FarshanAhamed** [JoshClose/CsvHelper#928]
Production server having .NET Core version 2.1.4 and in local i'm having 2.1.2. The error below is happening on 2.1.4
 ```c#
try
{
       string importPath = _options.Value.ImportPath;
       using (var textReader = new StreamReader(importPath + importFileName))
       using (var csv = new CsvReader(textReader))
       {                    
        csv.Configuration.HeaderValidated = null;
        csv.Configuration.MissingFieldFound = null;
        var importFoos = (csv.GetRecords<FooModel>()).ToList(); // line 171
       }
}
catch(Exception ex)
{
return ex.Message;
}
```

This codes working fine in local and it giving an exception on production server with same data.

The stacktrace is as below:
`at CsvHelper.Configuration.Configuration.<>c.<.ctor>b__148_4(CsvHelperException exception)
  at CsvHelper.CsvReader.<GetRecords>d__63`1.MoveNext()
  at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
  at Foofoo.TestModule.Services.Import.fooImport.<Importfoo>d__5.MoveNext() in C:\inetpub\apps\Foofoo-api-net-core\site\repository\Foofoo.TestModule\Services\Import\fooImport.cs:line 171` 

The Csv file is below:

FooDate | Day | Month | Year | DayOfWeek | Day | Foo | Foo1 | Foo2 | Foo3 | Foo4 | Foo5 | Foo6 | Foo7 | Foo8 | Foo9 | Foo10 | Foo11 | Foo12 | Foo13 | Foo14 | Foo15 | Foo16 | Foo17 | Foo18 | Foo19 | Foo20 | Foo21 | Foo22 | Foo23 | Foo24
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01-03-2018 | 1 | 3 | 2018 | 4 | Thursday | 05:45:00 | 05:30:00 | 05:44:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:42:00 | 18:37:00 |   |   |   |   |   |   |   |  
02-03-2018 | 2 | 3 | 2018 | 5 | Friday | 05:45:00 | 05:30:00 | 05:43:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:41:00 | 18:37:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00
03-03-2018 | 3 | 3 | 2018 | 6 | Saturday | 05:45:00 | 05:30:00 | 05:43:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:41:00 | 18:37:00 |   |   |   |   |   |   |   |  
04-03-2018 | 4 | 3 | 2018 | 0 | Sunday | 05:45:00 | 05:30:00 | 05:42:00 | 12:20:00 | 12:10:00 | 12:38:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:40:00 | 18:37:00 |   |   |   |   |   |   |   |  
05-03-2018 | 5 | 3 | 2018 | 1 | Monday | 05:45:00 | 05:30:00 | 05:42:00 | 12:20:00 | 12:10:00 | 12:38:00 | 03:20:00 | 03:10:00 | 15:58:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:40:00 | 18:37:00 |   |   |   |   |   |   |   |

**Comment by FarshanAhamed** [comment]
@JoshClose  I found out the exception that 'String was not recognized as a valid DateTime.' at DateTimeConverter.cs line:33 . 
```
Stacktrace : at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
  at CsvHelper.TypeConversion.DateTimeConverter.ConvertFromString(String text, IReaderRow row, MemberMapData memberMapData) in C:\Users\User\Desktop\ConsoleApp1\CsvHelper\src\CsvHelper\TypeConversion\DateTimeConverter.cs:line 33
```

**Comment by FarshanAhamed** [comment]
Can you help with this?

**Comment by JoshClose** [comment]
What is the string that it's trying to convert into a `DateTime`?

**Comment by FarshanAhamed** [comment]
@JoshClose  Its the exact string for that date i mentioned in the table provided. But i found the Format of datetime by default is different in local and production as i'm not giving any formats while mapping.

**Comment by JoshClose** [comment]
From your data, it's trying to parse ` -- ` as a `DateTime` which isn't going to work. All of your fields have spaces before and after the value, which isn't a valid format for CSV, though there are workaround for that if you have t parse a file like that. You're using `|` as a delimiter but didn't set that as the delimiter.

I don't see any issues on parsing this data, so you'll need to give me more information. I don't know which property you're having the issue with.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		var content =
@"FooDate | Day | Month | Year | DayOfWeek | Day | Foo | Foo1 | Foo2 | Foo3 | Foo4 | Foo5 | Foo6 | Foo7 | Foo8 | Foo9 | Foo10 | Foo11 | Foo12 | Foo13 | Foo14 | Foo15 | Foo16 | Foo17 | Foo18 | Foo19 | Foo20 | Foo21 | Foo22 | Foo23 | Foo24
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
01-03-2018| 1 | 3 | 2018 | 4 | Thursday | 05:45:00 | 05:30:00 | 05:44:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:42:00 | 18:37:00 |   |   |   |   |   |   |   |  
02-03-2018| 2 | 3 | 2018 | 5 | Friday | 05:45:00 | 05:30:00 | 05:43:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:41:00 | 18:37:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00 | 12:50:00 | 12:40:00
03-03-2018| 3 | 3 | 2018 | 6 | Saturday | 05:45:00 | 05:30:00 | 05:43:00 | 12:20:00 | 12:10:00 | 12:39:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:41:00 | 18:37:00 |   |   |   |   |   |   |   |  
04-03-2018| 4 | 3 | 2018 | 0 | Sunday | 05:45:00 | 05:30:00 | 05:42:00 | 12:20:00 | 12:10:00 | 12:38:00 | 03:20:00 | 03:10:00 | 15:59:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:40:00 | 18:37:00 |   |   |   |   |   |   |   |  
05-03-2018| 5 | 3 | 2018 | 1 | Monday | 05:45:00 | 05:30:00 | 05:42:00 | 12:20:00 | 12:10:00 | 12:38:00 | 03:20:00 | 03:10:00 | 15:58:00 | 18:43:00 | 18:40:00 | 18:37:00 | 07:20:00 | 07:10:00 | 19:35:00 | 06:40:00 | 18:37:00 |   |   |   |   |   |   |   |  ";
		writer.Write(content);
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.Delimiter = "|";
		csv.Configuration.TrimOptions = TrimOptions.Trim;
		csv.Configuration.ShouldSkipRecord = record => record.Length == 0 || record[0].StartsWith("--");
		csv.GetRecords<FooModel>().ToList().Dump();
	}
}

public class FooModel
{
	public DateTime FooDate { get; set; }
	public int Day { get; set;}
	public int Month { get; set; }
	public int Year { get; set; }
	public int DayOfWeek { get; set; }
}
```

**Comment by FarshanAhamed** [comment]
Actually, the table provided is a copy-paste from excel and it worked in my local so i think there is nothing to do with delimiter.

The actual table in csv is same with `,` as delimiter

```
FooDate,Day,Month,Year,DayOfWeek
01-03-2018,13,6,1439,4
02-03-2018,14,6,1439,5
03-03-2018,15,6,1439,6
04-03-2018,16,6,1439,0
05-03-2018,17,6,1439,1
06-03-2018,18,6,1439,2
07-03-2018,19,6,1439,3
08-03-2018,20,6,1439,4
09-03-2018,21,6,1439,5
10-03-2018,22,6,1439,6
11-03-2018,23,6,1439,0
12-03-2018,24,6,1439,1
13-03-2018,25,6,1439,2
14-03-2018,26,6,1439,3
15-03-2018,27,6,1439,4
16-03-2018,28,6,1439,5
17-03-2018,29,6,1439,6
```

 The field which creating this error is FooDate and its strange that it is working fine on some environment. When i tried to give the Format as `dd-MM-yyyy` while Mapping it worked in production. I guess the problem is in the format. In production the format is `MM-dd-yyyy' . So the dates after 12 can't parse. 

it worked when i tried with this mapping.

```c#
public sealed class FooImportMap : ClassMap<FooModel>
    {

        public FooImportMap()
        {


            AutoMap();

            Map(m => m.FooDate).TypeConverterOption.Format("dd-MM-yyyy");
        }

    }
```

**Comment by JoshClose** [comment]
Yes, that is how you can change the format! Is everything working as expected then?

**Comment by FarshanAhamed** [comment]
@JoshClose  It is working fine right now. But i suggest it'll be more clear to provide the exact exception when this situation occurs. Right now the exception is `An unexpected error occurred.` and it is hard to identify unless we clone the project and test. Any way thanks for your help. 👍

**Comment by JoshClose** [comment]
There is more information in the `Exception.InnerException`.

**Comment by JoshClose** [comment]
Maybe when I wrap exceptions I should put a note. `An unexpected error occurred. Please check inner exception for more details.`

**Comment by JoshClose** [comment]
Added feature for this. #935

**Comment by FarshanAhamed** [comment]
@JoshClose  Is there a way that the `MM-dd-yyyy` date format can accept both 04-10-2018 and 04/10/2018?

```
public sealed class FooImportMap : ClassMap<FooModel>
    {

        public FooImportMap()
        {


            AutoMap();

            Map(m => m.FooDate).TypeConverterOption.Format("MM-dd-yyyy");
        }

    }
```

this is how i map my datetime property while reading and i'm getting `String is not a valid DateTime Exception`.

My csv is like this

FooDate,Day,Month,Year,DayOfWeek
04-01-2018,13,6,1439,4
04/02/2018,14,6,1439,5
04/03/2018,15,6,1439,6
04-04-2018,16,6,1439,0
04-05-2018,17,6,1439,1
04/06/2018,18,6,1439,2

**Comment by JoshClose** [comment]
`.Format` is `.Format( params string[] formats )` which means you can pass in as many arguments as you like.

**Comment by FarshanAhamed** [comment]
@JoshClose  Is there a general way for giving datetime formats or i need to pass the array of all possible `MM-dd-yyyy` formats ?

**Comment by JoshClose** [comment]
It doesn't have to be an array because it's a `params` type. You can pass them like `.Format("one", "two", "three")`. You can look at the source here. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/TypeConversion/DateTimeConverter.cs It uses `DateTime.ParseExact`, so you can use whatever is available for formatting with that method.

You could use `ShouldSkipRecord`.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("FooDate,Day,Month,Year,DayOfWeek");
		writer.WriteLine("04-01-2018,13,6,1439,4");
		writer.WriteLine("04-02-2018,14,6,1439,5");
		writer.WriteLine("04-03-2018,15,6,1439,6");
		writer.WriteLine("04-04-2018,16,6,1439,0");
		writer.WriteLine("04-05-2018,17,6,1439,1");
		writer.WriteLine(",,,,");
		writer.WriteLine(",,,,");
		writer.WriteLine(",,,,");
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.ShouldSkipRecord = record => record.All(r => string.IsNullOrEmpty(r));
		csv.GetRecords<Test>().ToList().Dump();
	}
}

public class Test
{
	public DateTime FooDate { get; set; }
	public int Day { get; set; }
	public int Month { get; set; }
	public int Year { get; set; }
	public int DayOfWeek { get; set; }
}
```
