### ISSUE TITLE
WriteHeader does not add CR/LF at end

### ISSUE THREAD

**Issue by gsteinbacher** [JoshClose/CsvHelper#929]
In the code below the `WriteHeader` does not add a carriage return/line feed after the header so the first data record is on the same line as the header...

First line of CSV file looks like this...

> "CustomerNumber","Name","CompanyName","Address1","Address2","City","State","Zip","Salutation","Email","12345", "John A. Smith","Company, Inc.","123 Main Street","","Anchorage","AK","99508-4053","Mr.","smith@mail.com"

```
using (var csv = new CsvWriter(writer))
{
	csv.Configuration.QuoteAllFields = true;
	csv.WriteHeader<GroupRecord>();

	foreach (var table in tables)
	{
		IList<GroupRecord> records = ReadData(table);
		csv.WriteRecords(records);
	}
}
				
```

**Comment by JoshClose** [comment]
You need to call `NextRecord()` when you're done writing the header. This is so you can write more fields manually before or after.

**Comment by outofthecave** [comment]
It would be nice if this was documented somewhere.  I'm following this documentation: https://joshclose.github.io/CsvHelper/getting-started#writing-a-csv-file and it doesn't even mention that I need to call `WriteHeader` to get correct round-tripping behaviour, let alone that I need to call `NextRecord` after it.

**Comment by JoshClose** [comment]
I'll update the documentation with some information on reading/writing records manually.

**Comment by JoshClose** [comment]
I added some info on the getting started page for both reader and writing.

**Comment by pajacz** [comment]
Would be nice to add parameter "leave line open", with default = false :)
