### ISSUE TITLE
Issues creating file when using WriteRecord instead of writeRecords

### ISSUE THREAD

**Issue by jeffkenn2000** [JoshClose/CsvHelper#930]
Im trying to only copy certain properties from my list. I have the following code. This issue is it never creates a file like WriteRecords does. 

What am I doing wrong? 
```cs
  var newCsvFile = Path.Combine(destPath, fileName);
            using (var writer = new StreamWriter(newCsvFile))
            {
                using (var csvWriter = new CsvWriter(writer))
                {
                    csvWriter.Configuration.QuoteAllFields = true;


                    foreach (var item in leads)
                    {
                        csvWriter.WriteField( "Code" );
                        csvWriter.WriteField( "First_Name");
                        csvWriter.WriteField( "Last_Name" );
                        csvWriter.WriteField( "Address" );
                        csvWriter.WriteField( "City" );
                        csvWriter.WriteField( "CountyName" );
                        csvWriter.WriteField( "State" );
                        csvWriter.WriteField( "Zip" );
                        csvWriter.WriteField( "Date" );
                        csvWriter.WriteField( "Age" );
                        csvWriter.WriteField( "Gender");
                        csvWriter.WriteField( "Phone" );
                        csvWriter.WriteField( "Email" );
                        csvWriter.WriteField( "DOB" );
                        csvWriter.NextRecord();

                        csvWriter.WriteRecord(item);
                    }
```

**Comment by JoshClose** [comment]
You need to call `NextRecord` to end the line, so do that after you call `WriteRecord`. `WriteRecords` does that for you since it's looping all the records.

After you're done writing, the writer will need to be flushed also. If that isn't happening, some of the data may be in the writer (`ITextWriter` that is) buffer still.

**Comment by jeffkenn2000** [comment]
so like this

                        csvWriter.NextRecord();
                        csvWriter.WriteRecord(item);

                        csvWriter.NextRecord();

**Comment by jeffkenn2000** [comment]
OK. It looks like it is writing the file, but I am doing it this way so I can omit two properties from the export. When do the following,   csvWriter.WriteRecord(item); , it writes all properties from the model, not just the ones I have defined. 

Any ideas?

**Comment by JoshClose** [comment]
Create a `ClassMap` and only map the properties you want included. http://joshclose.github.io/CsvHelper/mapping
