### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by paleolith** [JoshClose/CsvHelper#931]
OK, I know almost nothing about packages and not a great deal about Visual Studio (Community 2015 running under Win7). But I found Nuget Package Manager and pasted in Install-Package CsvHelper. The response was

Install-Package : Could not install package 'CsvHelper 7.0.0'. You are trying to install this package into a project that targets '.NETFramework,V
ersion=v4.0,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. Fo
r more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  CsvHelper
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Then I found Manage Nuget Packages, but the result was the same.

What do I need to do to make it compatible?

Thanks,

Edward

**Comment by jamesbascle** [comment]
It is distributed for .net4.5 and .net standard 2.0.  You may try using
VS2017, 2015 has issues with .net standard packages that target 2.0.
Otherwise, try some of the older versions until you can upgrade.  3.2.0
works fine using 2015 and .net 4.6.1 for us.

**Comment by paleolith** [comment]
Thanks. I was able to install CsvHelper 2.16.3. My current need is very simple, so presumably that will work find.

Edward

**Comment by dkezri** [comment]
Thanks, 
I was also able to install CsvHelper 2.16.3 on .net core.
