### ISSUE TITLE
ClassMap 

### ISSUE THREAD

**Issue by haesta1066** [JoshClose/CsvHelper#934]
Good afternoon

Attempting to use the ClassMap to map the headers in the following csv
```
Product,Origin Year,Development Year,Incremental Value
Comp, 1992, 1992, 100.0
Comp, 1992, 1993, 100.0
```
To:
```cs
class ProductPaymentLine
{
    public string ProductCode { get; set; }
    public string OriginYear { get; set; }
    public string DevelopmentYear { get; set; }
    public string IncrementalValue { get; set; }
}
```
Code:
.......
.......
```cs
            csvReader.Configuration.RegisterClassMap<TestCsvProductPaymentMap>();
            var productPaymentLineList = 
                        csvReader.GetRecords<TestCsvProductPaymentMap().ToList();

        }

        sealed class TestCsvProductPaymentMap : ClassMap<MyData>
        {
            public TestCsvProductPaymentMap()
            {
                Map(m => m.ProductCode).Name("Product", "Product Name", "Product_Name");
                Map(m => m.OriginYear).Name("Origin Year", "Origin_Year", "Origin");
                Map(m => m.DevelopmentYear).Name("Development Year", "Development_Year", 
                         "Development");
                Map(m => m.IncrementalValue).Name("Incremental Value", "Incremental_Value", 
                         "Incremental", "Value", "Loss");
            }
        }
```
Exception: CsvHelper.ReaderException: No members are mapped for type
Any pointers will be gratefully received. 

I will also need to write out results (after some manipulation) into a 'flatter' merged csv file.

Thx

**Comment by JoshClose** [comment]
Your `ClassMap` is referencing a class you don't have in your example. This seems to work fine.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		var content = 
@"Product,Origin Year,Development Year,Incremental Value
Comp, 1992, 1992, 100.0
Comp, 1992, 1993, 100.0
";
		writer.Write(content);
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestCsvProductPaymentMap>();
		csv.GetRecords<ProductPaymentLine>().ToList().Dump();
	}
}

class ProductPaymentLine
{
	public string ProductCode { get; set; }
	public string OriginYear { get; set; }
	public string DevelopmentYear { get; set; }
	public string IncrementalValue { get; set; }
}

sealed class TestCsvProductPaymentMap : ClassMap<ProductPaymentLine>
{
	public TestCsvProductPaymentMap()
	{
		Map(m => m.ProductCode).Name("Product", "Product Name", "Product_Name");
		Map(m => m.OriginYear).Name("Origin Year", "Origin_Year", "Origin");
		Map(m => m.DevelopmentYear).Name("Development Year", "Development_Year", "Development");
		Map(m => m.IncrementalValue).Name("Incremental Value", "Incremental_Value", "Incremental", "Value", "Loss");
	}
}
```

**Comment by haesta1066** [comment]
Thanks Josh

I'd given you a bumsteer!  I had the mapping class in a namespace but could not get the mapping to work. The data class was also in a separate namespace. So created another mapping class and data class in the same scope as the main program (with different class names). So between to two I left an incorrect data class name in the example code. Sorry!

Here's the proper code. I still get the mapping exception  - again any help is appreciated.

using CsvHelper;
using CsvHelper.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using xxxxx.Data;
using xxxxx.Mapping;

namespace WillisTowersWatson
{

    class Program
    {

        static void Main(string[] args)
        {
            string fileName = @"C:\Users\Developer\Documents\Visual Studio 2017\Projects\xxxxx\Files\AH_Sunny-Day_1-Product.csv";
            string path = Path.GetFullPath(fileName);

            TextReader reader = File.OpenText(fileName);
            CsvReader csvReader = new CsvReader(reader);
            csvReader.Configuration.HasHeaderRecord = true;
            //csvReader.Configuration.HeaderValidated = null;
            //csvReader.Configuration.MissingFieldFound = null;
            csvReader.Configuration.Delimiter = ",";

            #region csv mapper
            csvReader.Configuration.RegisterClassMap<CsvProductPaymentMap>();
            var productPaymentLineList = csvReader.GetRecords<ProductPaymentLine>();

            List<ProductPaymentLine> sortedProducts = new List<ProductPaymentLine>();
            sortedProducts = productPaymentLineList.OrderBy(s => s.ProductCode).ThenBy(s => s.OriginYear).ThenBy(s => s.DevelopmentYear).ToList();

            #endregion csv mapper
        }
    }

    }
}


From Mapping
    sealed class CsvProductPaymentMap : ClassMap<ProductPaymentLine>
    {
        public TestCsvProductPaymentMap()
        {
            Map(m => m.ProductCode).Name("Product", "Product Name", "Product_Name");
            Map(m => m.OriginYear).Name("Origin Year", "Origin_Year", "Origin");
            Map(m => m.DevelopmentYear).Name("Development Year", "Development_Year", "Development");
            Map(m => m.IncrementalValue).Name("Incremental Value", "Incremental_Value", "Incremental", "Value", "Loss");
        }

From Data
    class ProductPaymentLine
    {
        public string ProductCode { get; set; }
        public string OriginYear { get; set; }
        public string DevelopmentYear { get; set; }
        public string IncrementalValue { get; set; }
    }

**Comment by JoshClose** [comment]
You'll need to give me some failing sample data. This still works.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		var content = 
@"Product,Origin Year,Development Year,Incremental Value
Comp, 1992, 1992, 100.0
Comp, 1992, 1993, 100.0
";
		writer.Write(content);
		writer.Flush();
		stream.Position = 0;
		
		csv.Configuration.RegisterClassMap<TestCsvProductPaymentMap>();
		var productPaymentLineList = csv.GetRecords<ProductPaymentLine>();

		List<ProductPaymentLine> sortedProducts = new List<ProductPaymentLine>();
		sortedProducts = productPaymentLineList.OrderBy(s => s.ProductCode).ThenBy(s => s.OriginYear).ThenBy(s => s.DevelopmentYear).ToList();
		
		sortedProducts.Dump();
	}
}

class ProductPaymentLine
{
	public string ProductCode { get; set; }
	public string OriginYear { get; set; }
	public string DevelopmentYear { get; set; }
	public string IncrementalValue { get; set; }
}

sealed class TestCsvProductPaymentMap : ClassMap<ProductPaymentLine>
{
	public TestCsvProductPaymentMap()
	{
		Map(m => m.ProductCode).Name("Product", "Product Name", "Product_Name");
		Map(m => m.OriginYear).Name("Origin Year", "Origin_Year", "Origin");
		Map(m => m.DevelopmentYear).Name("Development Year", "Development_Year", "Development");
		Map(m => m.IncrementalValue).Name("Incremental Value", "Incremental_Value", "Incremental", "Value", "Loss");
	}
}
```

**Comment by haesta1066** [comment]
Ok. Data in csv file =

Product,Origin Year,Development Year,Incremental Value
Comp, 1992, 1992, 100.0
Comp, 1992, 1993, 100.0
Comp, 1992, 1994, 100.0
Comp, 1992, 1995, 100.0
Comp, 1993, 1993, 200.0
Comp, 1993, 1994, 200.0
Comp, 1993, 1995, 200.0

**Comment by JoshClose** [comment]
This also works fine.
```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		var content = 
@"Product,Origin Year,Development Year,Incremental Value
Comp, 1992, 1992, 100.0
Comp, 1992, 1993, 100.0
Comp, 1992, 1994, 100.0
Comp, 1992, 1995, 100.0
Comp, 1993, 1993, 200.0
Comp, 1993, 1994, 200.0
Comp, 1993, 1995, 200.0
";
		writer.Write(content);
		writer.Flush();
		stream.Position = 0;

		csv.Configuration.RegisterClassMap<TestCsvProductPaymentMap>();
		var productPaymentLineList = csv.GetRecords<ProductPaymentLine>();

		List<ProductPaymentLine> sortedProducts = new List<ProductPaymentLine>();
		sortedProducts = productPaymentLineList.OrderBy(s => s.ProductCode).ThenBy(s => s.OriginYear).ThenBy(s => s.DevelopmentYear).ToList();

		sortedProducts.Dump();
	}
}

class ProductPaymentLine
{
	public string ProductCode { get; set; }
	public string OriginYear { get; set; }
	public string DevelopmentYear { get; set; }
	public string IncrementalValue { get; set; }
}

sealed class TestCsvProductPaymentMap : ClassMap<ProductPaymentLine>
{
	public TestCsvProductPaymentMap()
	{
		Map(m => m.ProductCode).Name("Product", "Product Name", "Product_Name");
		Map(m => m.OriginYear).Name("Origin Year", "Origin_Year", "Origin");
		Map(m => m.DevelopmentYear).Name("Development Year", "Development_Year", "Development");
		Map(m => m.IncrementalValue).Name("Incremental Value", "Incremental_Value", "Incremental", "Value", "Loss");
	}
}
```
Can you create a failing unit test please?

**Comment by haesta1066** [comment]
Sorted, I picked up a csv test file without headers!

I'd like to convert some of the csv data to specific types
e.g. 
"1990" => integer or year
"100.50 => Money

I noticed some conversion related stuff in you framework, will csvHelper handle the above?

Thanks again for your time.

**Comment by haesta1066** [comment]
Sorry another question. Can I use the conversion helpers to also perform some basic validation... or would this be a bad idea?

**Comment by JoshClose** [comment]
Just change the type of your model property to `int`.
