### ISSUE TITLE
Rename Configuration.IgnoreQuotes

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#936]
This name is confusing and not intuitive. It makes it sound like the reader should not read the quotes as a part of the field, which is normal behavior, when what it does is ignores is as a special CSV escaping character.

Maybe: `DisableFieldEscape`

**Comment by SimonCropp** [comment]
still want this done? want a PR?

**Comment by jesuslpm** [comment]
Has `IgnoreQuotes` been renamed? I cannot find `IgnoreQuotes` anymore.

**Comment by JoshClose** [comment]
There are modes now. https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/CsvMode.cs

Hopefully this is more clear.
