### ISSUE TITLE
BadRecords

### ISSUE THREAD

**Issue by baoduy** [JoshClose/CsvHelper#937]
Currently, The CsvHelper consider the record with have double quote in the middle of field is invalid.
Ex: **123, 456 "A", 789**

Hope is one can be accepted by default.

**Comment by JoshClose** [comment]
No, because that is an invalid CSV file. https://tools.ietf.org/html/rfc4180

If you have a file that has bad data in it, there are still ways to parse. In your case you could turn `Configuration.IgnoreQuotes` on.

You shouldn't have spaces after the commas either.

**Comment by baoduy** [comment]
Hi JoshClose
Let me try, Thanks for your quick response. Much appreciate.
