### ISSUE TITLE
CsvHelper.ValidationException: Header matching ['currentProductId'] names at index 0 was not found

### ISSUE THREAD

**Issue by 900v3n** [JoshClose/CsvHelper#938]
Greetings,

I'm trying to read a CSV using CsvReader v7.0.1 but keep getting this error:
_'Header matching ['currentProductId'] names at index 0 was not found.'_

**The CSV file:**
```
ProductId
Email
```

**The model class:**
```
private string currentProductId;
private string[] hierarchy;

public ProductHierarchy(string currentProductId, params string[] parentProductIds)
{
	Contract.Requires<ArgumentException>(!string.IsNullOrWhiteSpace(currentProductId));

	this.currentProductId = currentProductId;

	if (parentProductIds == null)
	{
		parentProductIds = new string[0];
	}

	this.hierarchy = parentProductIds.Reverse().Concat(new string[] { currentProductId }).ToArray();
}

[DataMember(Name = "CurrentProductId", IsRequired = true)]
public string CurrentProductId
{
	get{return this.currentProductId;}
	private set{this.currentProductId = value;}
}

[DataMember(Name = "Hierarchy", IsRequired = true)]
public string[] Hierarchy
{
	get{return this.hierarchy;}
	private set{this.hierarchy = value;}
}

public bool IsStandalone
{
	get{return this.hierarchy.First().Equals(this.currentProductId, StringComparison.InvariantCultureIgnoreCase);}
}
```

**The C# code:**
```
using (TextReader reader = File.OpenText(filePath))
using (var csv = new CsvReader(reader))
{
	csv.Configuration.RegisterClassMap<ProductHierarchyMap>();

	csv.Configuration.PrepareHeaderForMatch = (header) => header.ToLower();

	var records = csv.GetRecords<ProductHierarchy>().ToList();
	return records;
}
```

**Map class:**
```
public sealed class ProductHierarchyMap : ClassMap<ProductHierarchy>
{
	public ProductHierarchyMap()
	{
		AutoMap();
		Map(m => m.CurrentProductId).Name("ProductId");
	}
}
```

I'd appreciate any suggestions/ ideas on this.

**Comment by JoshClose** [comment]
Do you need the `AutoMap` in there?

**Comment by 900v3n** [comment]
Without `Automap`, it's throwing the exception below:

_CsvHelper.ReaderException: 'No members are mapped for type 'Data.Model.ProductHierarchy'.'_

**Comment by JoshClose** [comment]
The reason that exception is thrown is because `CurrentProductId` has a `private` setter. If you add the configuration `csv.Configuration.IncludePrivateMembers = true;` it will work without the `AutoMap`.

```cs
using CsvHelper.Configuration;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace CsvHelper.Tests.Issues
{
	[TestClass]
	public class Issue938
	{
		[TestMethod]
		public void Test()
		{
			using( var stream = new MemoryStream() )
			using( var writer = new StreamWriter( stream ) )
			using( var reader = new StreamReader( stream ) )
			using( var csv = new CsvReader( reader ) )
			{
				writer.WriteLine( "ProductId" );
				writer.WriteLine( "Email" );
				writer.Flush();
				stream.Position = 0;

				csv.Configuration.PrepareHeaderForMatch = ( header ) => header.ToLower();
				//csv.Configuration.HeaderValidated = null;
				csv.Configuration.IncludePrivateMembers = true;
				csv.Configuration.RegisterClassMap<ProductHierarchyMap>();
				var records = csv.GetRecords<ProductHierarchy>().ToList();
			}
		}

		private class ProductHierarchy
		{
			private string currentProductId;
			private string[] hierarchy;

			public ProductHierarchy() { }

			public ProductHierarchy( string currentProductId, params string[] parentProductIds )
			{
				Contract.Requires<ArgumentException>( !string.IsNullOrWhiteSpace( currentProductId ) );

				this.currentProductId = currentProductId;

				if( parentProductIds == null )
				{
					parentProductIds = new string[0];
				}

				this.hierarchy = parentProductIds.Reverse().Concat( new string[] { currentProductId } ).ToArray();
			}

			[DataMember( Name = "CurrentProductId", IsRequired = true )]
			public string CurrentProductId
			{
				get { return this.currentProductId; }
				private set { this.currentProductId = value; }
			}

			[DataMember( Name = "Hierarchy", IsRequired = true )]
			public string[] Hierarchy
			{
				get { return this.hierarchy; }
				private set { this.hierarchy = value; }
			}

			public bool IsStandalone
			{
				get { return this.hierarchy.First().Equals( this.currentProductId, StringComparison.InvariantCultureIgnoreCase ); }
			}
		}

		private sealed class ProductHierarchyMap : ClassMap<ProductHierarchy>
		{
			public ProductHierarchyMap()
			{
				//AutoMap();
				Map( m => m.CurrentProductId ).Name( "ProductId" );
			}
		}
	}
}
```

**Comment by 900v3n** [comment]
I noticed you have added a parameterless public constructor for `ProductHierarchy` class. 
Would it possible to be done without it?

**Comment by JoshClose** [comment]
Yes, but then values would need to be passed into the constructor. Let me see if I can come up with an example of doing it that way instead.

**Comment by JoshClose** [comment]
The issue is, using a `ClassMap` creates a collection of `MemberMap`s. To have the constructor injected instead and use `ParameterMap`s, you have to auto map; meaning not use a `ClassMap` at all. The list of parameters for the constructor will need to match headers in the file. You can use `csv.Configuration.PrepareHeaderForMatch` to manipulate that some.

Another options is to use an `ObjectResolver`. This way you can create the object yourself passing in `null`s if you want, then use your mapping with the private properties. That doesn't seem like it would work for you though, because you have null checks in the constructor.

Honestly, my suggestion is to always create a simple class used only for reading and writing CSV files. Then once the data is out, you can copy it to another class where you do the validation and stuff. You could even use a tool like [AutoMapper](https://automapper.org/) to easily go between types then.

**Comment by JoshClose** [comment]
Currently the object creators require a parameterless constructor because they use `Expression.MemberInit`. I need to figure out a way to use `ReflectionHelper.CreateInstance` to create the object instead so the `ObjectResolver` can be used when creating the objects.

**Comment by JoshClose** [comment]
I think your best bet might be to do it by hand.

```cs
var list = new List<ProductHierarchy>();
while (csv.Read())
{			
	var productHierarchy = new ProductHierarchy(csv.GetField(0), null);
	list.Add(productHierarchy);
}
```

**Comment by JoshClose** [comment]
It might also be nice to use a mapping file to create constructor parameter maps.

**Comment by JoshClose** [comment]
Also, I got the creation of the objects to use the resolver and I'll be committing that today some time.

**Comment by 900v3n** [comment]
Thanks for the detailed explanation and suggestions! Appreciate it.

Looking on the current options in hand, I'd agree with your suggestion that simple class used only for reading and writing CSV files. Therefore, I'd stick with that as of now.
