### ISSUE TITLE
CsvHelper adding numbers (index) to the file headers

### ISSUE THREAD

**Issue by GeertvanHorrik** [JoshClose/CsvHelper#939]
After an upgrade, on *some* of our files we had breaking changes because file headers suddenly have a postfixed "1".

After writing unit tests and investigating a bit, we found out this is caused by `CsvWriter.WriteHeader`. If the index is -1 (which to me is a valid value, it means it doesn't matter), it uses this logic to determine the header name:

```cs
foreach( var member in members )
{
	if( CanWrite( member ) )
	{
		if( member.Data.IndexEnd >= member.Data.Index )
		{
			var count = member.Data.IndexEnd - member.Data.Index + 1;
			for( var i = 1; i <= count; i++ )
			{
				WriteField( member.Data.Names.FirstOrDefault() + i );
			}
		}
		else
		{
			WriteField( member.Data.Names.FirstOrDefault() );
		}
	}
}
```

Why would CsvHelper add a number, even when:

1. The name is unique
2. An explicit name has been given

**Comment by GeertvanHorrik** [comment]
To provide more info, this happens to records that have "custom attributes". This is just a dynamic dictionary that we use to put in extra info that is not yet known at compilation time. We construct the map like this:

```
public class OperationMap : ClassMap<Operation>
{
    public OperationMap()
    {
        Map(x => x.Id).Name("Id");
        Map(x => x.Name).Name("Name");
        Map(x => x.StartTime).Name("StartTime");
        Map(x => x.Duration).Name("Duration");
        Map(x => x.Quantity).Name("Quantity");
        Map(x => x.Enabled).Name("Enabled");
    }

    public void Initialize(IEnumerable<string> customAttributes)
    {
        var classType = typeof(Operation);

        var customAttributesPropertyInfo = classType.GetPropertyEx("Attributes");
        foreach (var customAttribute in customAttributes)
        {
            var csvPropertyMap = MemberMap.CreateGeneric(classType, customAttributesPropertyInfo);
            csvPropertyMap.Name(customAttribute).TypeConverter(new CustomAttributesTypeConverter(customAttribute));

            MemberMaps.Add(csvPropertyMap);
        }
    }
}
```

**Comment by GeertvanHorrik** [comment]
A fix is to manually add this:

```
csvPropertyMap.Data.Index = GetMaxIndex() + 1;
```

Just not sure why this manual index setting is required?

**Comment by JoshClose** [comment]
Looks like it will only add the index if `IndexEnd >= Index`. How is your `IndexEnd` getting set?

**Comment by GeertvanHorrik** [comment]
-1 (I didn't touched the index before). But not sure why adding a 1 to the header would solve an index problem, but that might be me not fully understanding the implications.

**Comment by JoshClose** [comment]
https://github.com/JoshClose/CsvHelper/blob/2b93585937c33b289c01c7a27ea73f60329f254e/src/CsvHelper/Configuration/ClassMap.cs#L83

Internally those indexes are getting set. In your initialize with custom attributes code, you're creating things manually, which won't set those values.

I think instead of calling creating the map the way you are, you could call `this.Map( Type classType, MemberInfo member, bool useExistingMap = true )` and pass the values in, and everything would be set up properly for you.

**Comment by GeertvanHorrik** [comment]
Correct, I already solved it by manually setting the index. However, I think it's weird that if no index is set, the lib won't just add it to the end, but maybe that's just a combo of my special use-case.

**Comment by JoshClose** [comment]
The system will set indexes for you if you don't have them set, so they're always there. It uses indexes for everything, and not names. It figures out at mapping time what position value should be read/write from/to.

You're not supposed to be using `MemberMaps.Add` like that, but I haven't hidden so people can hack if they want. I could completely close things down like that so this doesn't become an issue, but most people won't be doing complex things like you are.
