### ISSUE TITLE
Throw new exception inside Validate() method

### ISSUE THREAD

**Issue by phramos07** [JoshClose/CsvHelper#941]
Hi,

I've been trying to throw a new Exception inside the Validate() method during GetRecord(). The issue is that I want to be able to distinguish the kind of error I had during validation, instead of only getting a "ValidationException". I would like to get different exceptions depending on the validation, like "ParsingException" or "RequiredFieldException", because I'll need that level of detail saved in a report that will later be sent to the user who uploaded the csv file.

My code is something as follows:

```
 Map(m => m.MyField)
      .Name("My Field Name")
      .Validate(field => 
      {
           try { DateTime.ParseExact(field, "dd/mm/yyyy", null); }
           catch (Exception) { throw new 
                  MyException("My Field Name - Field should have the format dd/mm/yyyy"); }
           return true;
       });
```
I know that the MyException is not being caught inside the function GetRecord<MyClass>(), and that the latter only throws a ValidationException. But how do I specify the Validation Exception?

In the end, I want to be able to tell the user which Lines in the .csv file had "parse errors", which had "required field errors", which had "length errors" and so on. The only way I thought of doing that is, during the GetRecord<MyClass>(), catch different kinds of exceptions during validation each line and then store this information in different lists for different errors. List<int> linesWithErrorX , List<int> linesWithErrorY, etc.

I don't know if I'm being clear enough, and forgive my bad english. =)

Thanks in advance.

**Comment by JoshClose** [comment]
Did you check if your exception is the inner exception?

**Comment by phramos07** [comment]
Sorry, I'm kinda new to C# (only 8 days programming). How do I make MyException inner to ValidationException ?

**Comment by phramos07** [comment]
You mean something like that?

```
while (auxiliar.Read())
{
	try
	{
		MyClass myClass = auxiliar.GetRecord<MyClass>();
	}
	catch (Exception e)
	{
		if (e.InnerException is MyException)
			MyList.Add(line);
	}
	finally
	{
		line++;
	}
}
```

**Comment by JoshClose** [comment]
Yes, that's how you can test an inner exception. It's possible it could be further down the tree too, so you might want to test if it's anywhere in there.

Something like this.

```cs
public MyException FindMyException(Exception ex)
{
	if (ex == null)
	{
		return null;
	}
	
	if (ex is MyException)
	{
		return (MyException)ex;
	}
	
	return FindMyException(ex.InnerException);
}
```
