### ISSUE TITLE
 Could not load file or assembly 'CsvHelper' in iis in .net core

### ISSUE THREAD

**Issue by apis3445** [JoshClose/CsvHelper#944]
Hi! I have an asp .net core app that is hosted in iis server version 8.5 , in the developer pc works, but in the server, show the following error
System.IO.FileNotFoundException: Could not load file or assembly 'CsvHelper, Version=7.0.0.0, Culture=neutral, PublicKeyToken=8c4959082be5c823'. The system cannot find the file specified.
The csvhelper dll with the same version is in the same directory that is the app

**Comment by JoshClose** [comment]
It sounds like a deployment issue of some sort. Are you using any other 3rd party libs? How did you create the output that is going onto the server?

**Comment by s3raph** [comment]
I'm experiencing a similar issue to this currently - it appears to be complaing about the manifest not matching the assembly version. Still tracking it down though.

**Comment by JoshClose** [comment]
Let me know if you figure out if it's something I need to change. I don't have a way to reproduce this.

**Comment by apis3445** [comment]
I fix publishing again all the folders of the publish folder of visual studio

**Comment by JoshClose** [comment]
@s3raph If you're continuing to have this problem, start a new issue. Sounds like your issue might be different because of the manifest.

**Comment by s3raph** [comment]
Ah. Turns out another project in the same solution had installed v2.16.3.0 of CsvHelper, and that copy of the assembly was what was ending up in the WebDeploy package.

This resulted in unit tests succeeding, but E2E tests failing with "the located assembly's manifest definition does not match the assembly reference".

**Comment by JoshClose** [comment]
Glad you figured it out!
