### ISSUE TITLE
About "No public parameterless constructor found." for Android

### ISSUE THREAD

**Issue by Blasthal** [JoshClose/CsvHelper#947]
## Summary
When CsvReader constructor for Android, the following error occurs.
I hope you can teach if there is a workaround.
```
InvalidOperationException: No public parameterless constructor found.
```
I use it with Unity, but it works without problems on Windows.

Reproduce with the following code.
```
StringReader stringReader = new StringReader("");
CsvReader csvReader = new CsvReader(stringReader);
```

## Environment
* CsvHelper 7.0.1
* Windows 10
* Unity 2017.3.0f3

_Thank you for your consideration._

**Comment by JoshClose** [comment]
Just calling `new CsvReader` will throw that exception?

**Comment by Blasthal** [comment]
Thank you for your reply.

Yes, that exception is raised when calling `new CsvReader(stringReader);`.
It happens with Android, but it does not happen on Windows.

**Comment by JoshClose** [comment]
I have no clue how to figure out what's causing that. I haven't done Android dev before. Maybe you can see if the Android community has any suggestions. Once you figure out what's causing it, maybe I can help.

**Comment by Blasthal** [comment]
OK.
Thank you for your advice.

**Comment by JoshClose** [comment]
If you find out any more information, post it and I'll open this issue back up. I just have no way to help figure out the problem unfortunately.

**Comment by tipa** [comment]
Sounds like some classes are being linked away. Likely the problem goes away if you exclude the CsvHelper assembly from the Linker. Would be great if this library could be made linker-safe for Xamarin projects
