### ISSUE TITLE
Getting Count 

### ISSUE THREAD

**Issue by RifS** [JoshClose/CsvHelper#948]
I have similar issue on #92. But I'm not sure whether I should've bumped the issue that has been over 5 years old, so I'm creating a new one.

I'm aware that calling `Count()` on the enumerated records will cause the cursor goes to the end and further operation/`foreach` loop on the records will return nothing.

The outline of my code is like this

````C#
    var myCSV = new CsvReader(File.OpenText(txtBox_CSVFile.Text));
    myCSV.Configuration.RegisterClassMap<MyCSVClassMap>();
    
    var record = new MyRecordClass();
    var allRecords = myCSV.EnumerateRecords(record);
    int recordsLength = allRecords.Count<MyRecordClass>();

    foreach (var r in allRecords)
    {
        /* some read/write operation here
        */
        scannedCSVEntry++;
        progress.value = scannedCSVEntry/recordsLength;
    }
````

The `recordsLength` is important here as I need to update the progress bar while I'm processing the entry

But how do I get around this?

**Comment by JoshClose** [comment]
There are a few ways.
1. Pull the whole thing into memory by doing a `ToList`. You can then do several operations over the data, including `Count`.
1. Parser the whole file. You can use just the parser to go through the whole file and count the records. This should be pretty fast because it's not creating any class objects or doing any type conversions.
1. Just count the line endings in the file. You can then use the `Context.RawRow` property to do your progress.

**Comment by RifS** [comment]
Thanks, 
I finally picked method 2.

````C#
StreamReader sr = File.OpenText(txtBox_CSVFile.Text);
int recordsLength = 0;
while(sr.ReadLine() != null)
{
    ++recordsLength;
}
recordsLength--; // discount 1 line because there are column headers in first row.
Console.WriteLine("recordsLength : " + recordsLength);
sr.Close();
````

Does `EnumerateRecords()` automatically close the stream after hydrating all the entries? I'm wondering whether I should call `Close()` after calling the function.

**Comment by JoshClose** [comment]
My suggestion is to wrap in a `using` block.

```cs
using(StreamReader sr = File.OpenText(txtBox_CSVFile.Text))
{
    int recordsLength = 0;
    while(sr.ReadLine() != null)
    {
        ++recordsLength;
    }
    recordsLength--; // discount 1 line because there are column headers in first row.
    Console.WriteLine("recordsLength : " + recordsLength);
}
```

**Comment by Liero** [comment]
Using `stream.Position`  worked for me with large files without reading the entire file first:

```csharp
using(StreamReader sr = File.OpenText(txtBox_CSVFile.Text))
{
   var csvReader = new new CsvHelper.CsvReader(sr);
    while (csvReader.Read())
    {
         double progress = (double)sr.BaseStream.Position / sr.BaseStream.Length;
    }
}
```

it should work also with GetRecords, but I've not tested:
```csharp
foreach(var record in csvReader.GetRecords<MyRecordClass>())
{
    double progress = (double)sr.BaseStream.Position / sr.BaseStream.Length;
}
```

**Comment by svrooij** [comment]
I've checked your solution
```csharp
foreach(var record in csvReader.GetRecords<MyRecordClass>())
{
    double progress = (double)sr.BaseStream.Position / sr.BaseStream.Length;
}
```
which didn't work for me.
But you can do this `double progress = (double)csvReader.Context.CharPosition / csvReader.Context.CharsRead;` to get the desired result

**Comment by blueblur22** [comment]
Things have changes since 2019.

For anyone else looking to get the progress for a progress bar, I managed it with this:

```
double progress = csvReader.Parser.CharCount / sr.Length * 100
```

_Note: My stream is a FileStream_

**Comment by svrooij** [comment]
@blueblur22 nice a response on a 7 year old issue
