### ISSUE TITLE
Have you considered support for no delimiter?

### ISSUE THREAD

**Issue by jkewley** [JoshClose/CsvHelper#950]
Which would allow us to use CsvHelper to output fixed-field-length files? 

I have several projects where I use one map to read a csv and another to output a transformed csv. Some of my integrations call for field field length with no delimiter, but setting null or empty string for `Configuration.Delimiter` throws an object ref not set error.

**Comment by JoshClose** [comment]
Fixed width support is planned. It won't be for a while though.

**Comment by jkewley** [comment]
Was this implemented or pulled from consideration?

**Comment by JoshClose** [comment]
There is a feature for it in the contrib project. I may actually pull it into the main project though. https://github.com/CsvHelperContrib/CsvHelperContrib/issues/2

**Comment by janissimsons** [comment]
Why don't you allow empty delimiters? If fixed-width isn't going to be implemented any time soon, then simply allowing "" empty string to be set as a delimiter would help a lot for people like me who are using this library and adjusted it to work with fixed-width files.

Right now this library crashes when:
```csvWriter.Configuration.Delimiter = "";```

**Comment by JoshClose** [comment]
How can you look for a character/string that doesn't exist?

**Comment by jkewley** [comment]
Haven't worked with this in some time, but I think the idea is to allow the maps to be processed without requiring the split. This would allow the use of an ITypeConverter to do the splitting based on a fixed width spec and use of the IReaderRow. Obviously not the most performant approach, but not all situations call for that

**Comment by JoshClose** [comment]
CsvHelper doesn't do any splitting. It parses the file character by character. A fixed width parser could be created which should be much more simple. There would need to be a way to configure the widths though.
