### ISSUE TITLE
Question: how to string multiple typeconverter together

### ISSUE THREAD

**Issue by jasonduff** [JoshClose/CsvHelper#952]
I'd like to be able to string/chain multiple typeconverters together into something like this:
Map(m=>m.someField).Name("someTag").TypeConverter<TypeConverter1>().TypeConverter<TypeConverter2>()

This will compile but what gets passed to the second typeconverter is the original string.  This seems intentional which is ok.  Is there an alternative method you can suggest?

Thanks.

**Comment by JoshClose** [comment]
The first type converter won't get call either. The second call to `TypeConverter()` overwrites the first.

I think there are a few options.

1. You can create a custom type converter to do the conversion.
1. You can use `.ConvertUsing( row => ... )`.
1. Have your property setter do some work.
