### ISSUE TITLE
Calling Dispose on CsvReader multiple times throws NullReferenceException

### ISSUE THREAD

**Issue by seanterry42** [JoshClose/CsvHelper#954]
See PR #953 
Found when an update to my DI container unexpectedly began disposing items that were already taken care of by using statements.

Not exactly a bug, but [Dispose shouldn't result in an exception](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations)

**Comment by JoshClose** [comment]
Merged.
