### ISSUE TITLE
Use ClassMap to create constructor parameter mapping

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#955]
Look into what sort of work is required to do this.

Maybe everything can stay the same and there is a map type or something that can be changed.

```cs
Type = ClassMapTypes.ConstructorParameters;
Map( m => m.Id );
Map( m => m.Name );
```

https://github.com/JoshClose/CsvHelper/issues/1484

**Comment by gojanpaolo** [comment]
Would it be worthwhile to look at how EF Core does it? 

https://docs.microsoft.com/en-us/ef/core/modeling/constructors

**Comment by JoshClose** [comment]
I like that convention.

> When EF Core creates instances of these types, such as for the results of a query, it will first call the default parameterless constructor and then set each property to the value from the database. However, if EF Core finds a parameterized constructor with parameter names and types that match those of mapped properties, then it will instead call the parameterized constructor with values for those properties and will not set each property explicitly.

**Comment by philwindsor** [comment]
any update on this, really would be a handy feature?

**Comment by JoshClose** [comment]
It's still planned. There are a few things that have higher priority though and I don't have a lot of time at the moment.

**Comment by philwindsor** [comment]
I'm having massive issues with this at the moment. It may warrant a separate support ticket.

**Comment by JoshClose** [comment]
This was done as part of another feature several months ago.

**Comment by MurrayLong** [comment]
> This was done as part of another feature several months ago.

Which feature?  How is it used?

**Comment by JoshClose** [comment]
You use `Parameter` instead of `Map`.

```cs
void Main()
{
    var s = new StringBuilder();
    s.Append("Id,Name\r\n");
    s.Append("1,one\r\n");
    var config = new CsvConfiguration(CultureInfo.InvariantCulture)
    {
    };
    using (var reader = new StringReader(s.ToString()))
    using (var csv = new CsvReader(reader, config))
    {
        csv.Context.RegisterClassMap<FooMap>();
        csv.GetRecords<Foo>().ToList().Dump();
    }
}

private class Foo
{
    public int Id { get; private set; }
    public string Name { get; private set; }
    
    public Foo(int theId, string theName)
    {
        Id = theId;
        Name = theName;
    }
}

private class FooMap : ClassMap<Foo>
{
    public FooMap()    
    {
        Parameter("theId").Name("Id");
        Parameter("theName").Name("Name");
    }
}
```

**Comment by StijnOttenVMT** [comment]
Hey, I couldn't find this in your documentation under https://joshclose.github.io/CsvHelper/examples/configuration/class-maps/.

Might be handy to add because now I had to look through GitHub issues to find this
