### ISSUE TITLE
Log bad records in CsvReader

### ISSUE THREAD

**Issue by romiih** [JoshClose/CsvHelper#956]
Hi, I'm trying to replace my parser to your great library.
I want to log whole line of bad records but sometimes didn't get the results I expected.
What am I doing wrong?

Here my code:
```
public void Read()
{
    var sb = new StringBuilder();
    sb.AppendLine("\"A\",\"B\",\"C\"");
    sb.AppendLine("\"1111000\",\"100\",\"Good data\"");
    sb.AppendLine("\"1112000,\"200\",\"Bad data\"");

    var csv = new CsvReader(new StringReader(sb.ToString()));
    csv.Configuration.MissingFieldFound = null;
    csv.Configuration.BadDataFound = context =>
    {
        Console.WriteLine($"Row:{context.RawRow},{context.RawRecord}");
    };

    var result = csv.GetRecords<MyClass>();

    // read all
    result.Count();
}
```
expected: `Row:3,"1112000,"200","Bad data"`
result: `Row:3,"1112000,"200",`

Thanks,

**Comment by JoshClose** [comment]
That's because the exception is thrown at that character when the bad data is found. It hasn't finished reading the whole row.

**Comment by romiih** [comment]
Thank you very much for your answer.
