### ISSUE TITLE
Support for NET Standard 1.6?

### ISSUE THREAD

**Issue by brazilianldsjaguar** [JoshClose/CsvHelper#961]
Any particular reason why you're not able to also support NET Standard 1.6? I ask because we've got a project that, for reasons, can't be upgraded to .NET Core 2, and is stuck on 1.1 (which implements Standard 1.6). Thanks!

**Comment by JoshClose** [comment]
I don't want to maintain a bunch of versions. If upgrading isn't a possibility, you can use the last 2.x version. That implements netstandard1.3.

**Comment by brazilianldsjaguar** [comment]
Oh, didn't realize that! Thanks!

**Comment by JoshClose** [comment]
It's not advertised. You'd have to look back at the change log.
