### ISSUE TITLE
Read csv file with no quotes

### ISSUE THREAD

**Issue by reshmi-ravindran** [JoshClose/CsvHelper#962]
Hi Josh,

I am trying to read data from a csv file with no quotes in between data. My sample data looks like below:
1;TEST;NULL;TESTCODE;USCODE
When i read this data, it is not able to read the last column and it works when the last column is quoted like below:
1;TEST;NULL;TESTCODE;"USCODE"
Do you know why? Is there anything i need to do with configuration? My configuration right now is below:
var config = new CsvHelper.Configuration.Configuration
            {
                Delimiter = ";"                
            };

Thanks!
Reshmi.

**Comment by JoshClose** [comment]
If there is no header record, you'll need to turn that off.

```cs
csv.Configuration.HasHeaderRecord = false;
```
