### ISSUE TITLE
RegisterClassMap in a function with a generic type parameter

### ISSUE THREAD

**Issue by Code-Bear** [JoshClose/CsvHelper#963]
There is probably an obvious and easy way to do this but I can't find anything in the documentation. I am trying to work with a generic GetRecords method that accepts whatever class I give it. In the example below I am using a class I created to hold the records from a CSV but I can't figure out a way to register a map based on the available parameters sent to the method. I was hoping I could tell the CsvHelper to look for a map based on the class I am using. Any idea how I might go about this?

```C#
public virtual List<TEntity> GetRecords<TEntity>(string filePath)
            where TEntity : class
        {
            if (!File.Exists(filePath)) return null;
            Thread.Sleep(1000);
            using (var sr = new StreamReader(filePath))
            {
                using (var reader = new CsvReader(sr) { Configuration = { HasHeaderRecord = true, MissingFieldFound = null, HeaderValidated = null } })
                {
                    //reader.Configuration.RegisterClassMap<TestClassMap>();
                    return reader.GetRecords<TEntity>().ToList();
                }
            }
        }
```

**Comment by JoshClose** [comment]
A couple options:

You could add another generic parameter for the map type. 

You could register all maps. GetRecords<T> will use the registered map for type T.

**Comment by Code-Bear** [comment]
Both aren't exactly the answer I was hoping for. One request the dev to know/remember the map whenever they want to use the class and the other really takes away from the generic aspect of the function but I guess the first one is the only option I have at this point.

It would be great to either have a way to load/register any classes that inherit from the MapClass or maybe a way to find and register a map class based on the TCLass is was using. Almost like IOC or something.

**Comment by JoshClose** [comment]
So you want the user to not have to know what mapping file to use? They won't be creating or even know what these mapping files are?

**Comment by Code-Bear** [comment]
Sorry, I was tired when I wrote that. I guess my goal was to create a generic class that could be used by just feeding it the class as a param and have it figured out the associated map class with it. I just ended up making the generic class require both the class and map as params.

**Comment by Code-Bear** [comment]
Maybe something like Attributes instead of or as an alternative to a map class. Just an idea. Love the library either way. ^_^

**Comment by JoshClose** [comment]
There are attributes actually. https://github.com/JoshClose/CsvHelper/tree/master/src/CsvHelper/Configuration/Attributes

Maybe this will solve your problem.

**Comment by Code-Bear** [comment]
Oh nice, I didn't see anything about that in the documentation. Thank you!

**Comment by JoshClose** [comment]
Yeah... I need to finish the docs. They're not complete yet.
