### ISSUE TITLE
Parsing malformed data

### ISSUE THREAD

**Issue by mike1174** [JoshClose/CsvHelper#968]
The reader keeps failing on the following field.  Is there any way to process this field?  TextFieldParser can parse the field, but im unsure how to incorporate reading a bad data found line with TextFieldParser, also the bad data found raw context doesnt show the entire row of data, it gets cut off.

"15 CALLE "B" 13-11 ZONA 11 DE"

**Comment by mike1174** [comment]
is there a way to escape quotes in a string while reading?

if i choose the ignorequotes,  my file doesnt get processes, its a quote comma delimited file  with a lot of fields. 

using this example: 
[badrow.txt](https://github.com/JoshClose/CsvHelper/files/1876957/badrow.txt)

My solution was using the ReadingExceptionOccurred, then splitting the lines, and putting the quotes back on and then merging this bad line to the good lines after the entire file was read.

is there a better or more efficient way?  Without this, i can not read this row.

                        reader.Configuration.ReadingExceptionOccurred = exception =>
                        {
                            try
                            {
                                var malformedLine = exception.ReadingContext.RawRecord.Substring(1, exception.ReadingContext.RawRecord.Length - 2);
                                string[] fields = malformedLine.Split(new string[] { "\",\"" }, StringSplitOptions.None);

                                for (int index = 0; index < fields.Length; ++index)
                                {
                                    fields[index] = fields[index].Replace("\"", "");
                                }
                                var fieldLine = "\"" + string.Join("\",\"", fields) + "\"";

                                string[] header = exception.ReadingContext.HeaderRecord;
                                var headerLine = "\"" + string.Join("\",\"", header) + "\"";

                                using (var memoryStream = new MemoryStream())
                                using (var streamWriter = new StreamWriter(memoryStream))
                                using (var streamReader = new StreamReader(memoryStream))
                                using (var csvReader = new CsvReader(streamReader))
                                {
                                    csvReader.Configuration.RegisterClassMap<InvoiceViewModelCsvMap>();
                                    csvReader.Configuration.IgnoreBlankLines = true;
                                    csvReader.Configuration.HasHeaderRecord = true;
                                    csvReader.Configuration.HeaderValidated = null;
                                    csvReader.Configuration.MissingFieldFound = null;
                                    csvReader.Configuration.BadDataFound = null;
                                    csvReader.Configuration.ReadingExceptionOccurred = null;

                                    streamWriter.WriteLine(headerLine);
                                    streamWriter.WriteLine(fieldLine);
                                    streamWriter.Flush();
                                    memoryStream.Position = 0;

                                    var invoiceException = new InvoiceViewModel();

                                    while (csvReader.Read())
                                    {
                                        invoiceException = csvReader.GetRecord<InvoiceViewModel>();
                                        invoiceExceptions.Add(invoiceException);
                                    }
                                }
                            }
                            catch (Exception ex)
                            {
                                logger.Error(ex.Message, ex);
                            }
                        };

**Comment by mike1174** [comment]
No, its another company that we have no control over how they generate their files.

If you could add this feature in, that would be great, csvhelper is excellent.  I would say having this feature would be #1 on my wish list.

My logic processes 10's of thousands of rows a week, and time is important, so there is no time to manually correct these, i need a on the fly solution. 

Thanks

**Comment by JoshClose** [comment]
Added #989. Follow that for progress.
