### ISSUE TITLE
Slow Reading Speed. CsvReader

### ISSUE THREAD

**Issue by renszzzzzzz** [JoshClose/CsvHelper#969]
I am using the following code for reading and CSV file which is 160 MB. However it seems to be taking a long time. The file has 235344 rows and I am only interested in the "keyword" column. 

The file takes however 4 minutes to read and I thought the benchmark was a lot faster.

Does the code below seem alright, or am I missing something crucial? 

```
public void test()
        {
            using (var stream = File.OpenRead(@"C:\combine\Combination.csv"))
            //using (var writer = new StreamWriter(stream))
            using (var reader = new StreamReader(stream))
            using (var csvReader = new CsvReader(reader))
            using(var csvParser = new CsvParser(reader))
            //using (var csvWriter = new CsvWriter(writer))
            {
                csvReader.Read();
                csvReader.ReadHeader();
                csvReader.GetField<string>("Keyword");

                var records = csvReader.GetRecords<dynamic>();

                Console.WriteLine("records count: " + records.Count());

            }
        }
```

**Comment by JoshClose** [comment]
Can you create a class and try doing `GetRecords<MyClass>()` and see if that helps? I'm guessing `dynamic` is really slow. If so, I can look into speeding up dynamic creation.

**Comment by renszzzzzzz** [comment]
Yes, I will try. but the file columns are continuously changing. (only interested in one column however. the "Keyword" column). Would it be possible to read the headers and then select only the column through the class and ignore the rest of the columns?

Thank you for the quick reply!

**Comment by JoshClose** [comment]
Just loop and use `GetField`.

```cs
void Main()
{
	using (var stream = new MemoryStream())
	using (var writer = new StreamWriter(stream))
	using (var reader = new StreamReader(stream))
	using (var csv = new CsvReader(reader))
	{
		writer.WriteLine("Id,Name");
		writer.WriteLine("1,one");
		writer.WriteLine("2,two");
		writer.Flush();
		stream.Position = 0;
		
		csv.Read();
		csv.ReadHeader();
		while (csv.Read())
		{
			csv.GetField<int>("Id").Dump();
			csv.GetField<string>("Name").Dump();
		}
	}
}
```

**Comment by renszzzzzzz** [comment]
@JoshClose This is a lot faster. Reducing time from 4 minutes to 10 seconds. Are you planning to improve the `dynamic` in future versions.

**Comment by JoshClose** [comment]
I'll look into it. #972
