### ISSUE TITLE
dynamic reading speed

### ISSUE THREAD

**Issue by JoshClose** [JoshClose/CsvHelper#972]
Dynamic reading is really slow. Look into performance.

**Comment by shibayan** [comment]
`ExpandoObject` locks every time during an add operation. As a result, dynamic reading seems to be very slow.

To solve this problem will need an implementation that does not use `ExpandoObject`. (Like `SqlMapper.DapperRow` class in Dapper)

I think there are two implementation plans.

1. Implement inherit `Dictionary<string, object>` that implements `IDynamicMetaObjectProvider`.
  - It is easy to implement, but it is not memory efficient.
2. Create a class that implements `IDictionary<string, object>` and `IDynamicMetaObjectProvider` specialized for CSV
  - Improve memory efficiency by sharing CSV header information.

I write and test the code to improve this problem.
Thanks.

**Comment by superrnovae** [comment]
Itterating with foreach over IEnumerable<dynamic> is extremely slow and takes around 5 minutes for 50 thousand records.

**Comment by shibayan** [comment]
@superrnovae An auxiliary library has been created for fast handling. I believe it will help. https://github.com/shibayan/CsvHelper.FastDynamic

**Comment by JoshClose** [comment]
@shibayan  So this makes using `dynamic` faster than using types?

**Comment by shibayan** [comment]
@JoshClose No, it will not be faster than accessing with types because of the overhead present. However, performance should be significantly improved compared to `dynamic` using `ExpandoObject`.

**Comment by julian-gargicevich** [comment]
Any update on this?

**Comment by JoshClose** [comment]
This will be in the next release, 32.0.0.
