### ISSUE TITLE
Add skip to line feature to start reading from specified line number

### ISSUE THREAD

**Issue by aditya-kanekar** [JoshClose/CsvHelper#973]
I am trying to implement a CSV processor which will process a batch of rows depending on some condition and save the last line number as the position. When the batch process is complete I want to resume from the last line. I tried implementing this using Seek method but its error prone. This will be a nice feature to have.

**Comment by jamesbascle** [comment]
If you know how many lines you need to skip without reading the file, you
can use the option on the configuration object.

**Comment by JoshClose** [comment]
Text lines or CSV lines?

If CSV lines, you can just skip rows like this.

```cs
for (var i = 0; i < 20; i++)
{
	csv.Read();
}
```

**Comment by aditya-kanekar** [comment]
Hey Thanks Josh for the reply. I used csv.Read() function itself for the same.
