### ISSUE TITLE
CsvWriter ctor configuration and leaveopen

### ISSUE THREAD

**Issue by hangy** [JoshClose/CsvHelper#985]
In CsvHelper 7.0.0.0, there is no constructor for `CsvWriter` that accepts both `configuration` and `leaveOpen` (as `CsvReader` does). Simply stealing from the other constructors, that should be as simple as:

```
/// <summary>
/// Creates a new CSV writer using the given <see cref="TextWriter"/>.
/// </summary>
/// <param name="writer">The <see cref="StreamWriter"/> use to write the CSV file.</param>
/// <param name="configuration">The configuration.</param>
/// <param name="leaveOpen">true to leave the writer open after the CsvWriter object is disposed, otherwise false.</param>
public CsvWriter( TextWriter writer, Configuration.Configuration configuration, bool leaveOpen ) : this( new CsvSerializer( writer, configuration, leaveOpen ) ) { }
```

I realize that I can achieve the same by explicitly creating the `CsvSerializer` myself, but is there a specific reason for this constructor _not_ to exist? I could not find anything obvious in the existing issues.

**Comment by JoshClose** [comment]
Just oversight I believe.

**Comment by hangy** [comment]
Thanks for the quick reply!
