### ISSUE TITLE
[support needed] Problem reading CSV using dynamic instead of POCO 

### ISSUE THREAD

**Issue by hellboy81** [JoshClose/CsvHelper#990]
I am trying to convert code to read CSV with dynamic structure (some field can be added):

```csv
// More columns can be added

|somefield|somemorefiled|mydate|
|78787|898981|08.04.2018|
|1111|9829857|10.04.2018|
```

```csharp
var reader = File.OpenText(FileName);
			
var csv = new CsvReader(reader);
			
csv.Configuration.Delimiter = "|";

// This class map is only for POCO objects needed?

csv.Configuration.RegisterClassMap<TMyEntityCanBeChangedClassMap>();

// This code works properly  for POCO
var records = csv.GetRecords<TMyEntityCanBeChanged>().ToList(); // ToList() works fine

// Trying to replace with dynamic
var records = csv.GetRecords<dynamic>().ToList(); // ToList() throws exception both with or without  class map registration:

CsvHelper.ReaderException : An unexpected error occurred.
  ----> System.ArgumentException : An element with the same key '' already exists in the ExpandoObject.
```

I am not sure how to solve problem to read csv with dynamic structure:
the columns can be added/deleted but I dont want to change classmap/entity and recompile application

**Comment by JoshClose** [comment]
The exception looks like you have duplicate header names.

**Comment by Aashutosh3804** [comment]
> Ok, I'm dumb. `ICsvReader` exists on the context. Here is the default code. If you need help figuring out the first or last one, let me know.
> 
> ```cs
> public static string GetDynamicPropertyName(GetDynamicPropertyNameArgs args)
> {
> 	if (args.Context.Reader.HeaderRecord == null)
> 	{
> 		return $"Field{args.FieldIndex + 1}";
> 	}
> 
> 	var header = args.Context.Reader.HeaderRecord[args.FieldIndex];
> 	var prepareHeaderForMatchArgs = new PrepareHeaderForMatchArgs(header, args.FieldIndex);
> 	header = args.Context.Reader.Configuration.PrepareHeaderForMatch(prepareHeaderForMatchArgs);
> 
> 	return header;
> }
> ```

` var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
               
               
               
                GetDynamicPropertyName = (GetDynamicPropertyNameArgs context) => {
                    if (context.Context.Reader.HeaderRecord == null)
                    {
                        return $"Field{context.FieldIndex + 1}";
                    }
                    string header = context.Context.Reader.HeaderRecord[context.FieldIndex];
                    header = header.Substring(2);
                    var args2 = new PrepareHeaderForMatchArgs(header, context.FieldIndex);
                    return $"Field{context.FieldIndex + 1}";



                },
                 DynamicPropertySort = Comparer<string>.Create((x, y) => x.CompareTo(y)),
                HasHeaderRecord = true,


            };`
