### ISSUE TITLE
Is .net core 2.0 supported?

### ISSUE THREAD

**Issue by dougngo** [JoshClose/CsvHelper#991]
I have a .net core 2 console app, I installed csvhelper via  the package via .net cli with 

dotnet add package CsvHelper

However, when I add "using CsvHelper;" , I am still getting 

The type or namespace name 'CsvHelper' could not be found (are you missing a using directive or an assembly reference?)

**Comment by JoshClose** [comment]
It should. It's a netstandard2.0 assembly. What do your project file look like?

**Comment by dougngo** [comment]
Josh, thanks for the quick response.  It was a rookie mistake of mine. I am using your package with https://github.com/filipw/dotnet-script and I forgot the reference before accessing the package.
