### ISSUE TITLE
Possible to parse CSV, but retain quotes and escape characters?

### ISSUE THREAD

**Issue by theescapers** [JoshClose/CsvHelper#993]
Say I've got a CSV line like this:

1,""test quoted data"",2

If I parse that with CsvHelper, I'll get fields back of

```
1
test quoted data
2
```

But what I would like is

```
1
""test quoted data""
2
```

I'd be happy just to get indexes of the the commas which delimit the fields, in fact.

Can CsvHelper help me out here?

Thanks

Garry

**Comment by JoshClose** [comment]
`CsvReader.Configuration.IgnoreQuotes = true`

Your example is actually an invalid format.

**Comment by theescapers** [comment]
Sorry, yes it is, thanks for the help anyway.
