### ISSUE TITLE
misses a column

### ISSUE THREAD

**Issue by papiermache** [JoshClose/CsvHelper#996]
In following, the code returns "stemmy" instead of "2" for the before-last column of the single data row. This is causing our production implementation to crash.  Any help would be appreciated.

**Comment by JoshClose** [comment]
I will need a sample the reproduces the error, or at least the data that's causing this issue.

**Comment by papiermache** [comment]
Hi Josh, I had attached the csv file that causes the issue, did it not come across?
Regards, Rick.

Rick Piovesan

Enterprise Solutions Consultant
PMP, MCSD [Web.SQL,ALM], MCT
Xamarin Certified Mobile Developer

Detaya<http://blogs.objectsharp.com/> Corp
Cell: 905-717-7168
Off: 289-858-2658
rick.piovesan@detaya.com

**Comment by papiermache** [comment]
Hi Josh, thx in advance for looking into this, it’s a real issue here now with my govt client.  I’ve attached the file, it has just the header record and the single record having the issue.
Regards, Rick

**Comment by JoshClose** [comment]
If you're doing this via email, it won't show up in github. You'll have to do it on the website, I believe.

**Comment by papiermache** [comment]
Hi Josh,
I did it initially on the github website but you didn’t receive it, so I attached another copy to prior email – and I guess you didn’t receive it either. Do you have a non-github email that I could send to ? or a dropbox or equiv?  Otherwise I could put into my own dropbox (but would need your email in order to send you a link).  Cheers, Rick.

**Comment by JoshClose** [comment]
You can send it to narshe on the google email service.

**Comment by JoshClose** [comment]
Got your file.

The first row, the header, I'm getting 185 columns. The second row, I'm getting 184 columns. What are you expecting?

**Comment by papiermache** [comment]
great thx again for looking into this. and btw it does open correctly in Excel so I don’t think there’s a problem with the actual data.

**Comment by papiermache** [comment]
Hi Josh, sorry that’s not the issue.  Actually the file has about 100 records in it and it failed with reported issue on this record (which was the 4th one). And so I created this test file that I sent you , copying in only this ‘bad’ record.

But .. I just ran this single-record file through my program and it worked L bummer. And so t’ll need to create a better test file, I’ll try now with all the earlier records .

Back to you shortly with results
Rick.

**Comment by papiermache** [comment]
Hi Josh,
here’s the file again. This time I checked and it does fail. What I had to do was make the record in error be the 2nd record and not the first (or only).  And yes it looks correct in Excel (of course don’t save it since Excel does things with dbl-quotes).

I hope it fails also for you and you can figure this one out without too much hassle.
Regards, Rick

**Comment by JoshClose** [comment]
You'll have to send to my other email again.

**Comment by JoshClose** [comment]
Can you give me the code you're using to read with?

**Comment by papiermache** [comment]
not possible I’m afraid, it’s one module integrated with a whole bunch of other stuff, I would not be able to split it out.  Does your testing with this file not also fail?

**Comment by papiermache** [comment]
Hi Josh,

I figured out how to resolve the issue Though I have no idea why it solves anything, I turned off “IgnoreQuotes” and no more


        public string GetDataField(string headerFieldCaption)
        {
            //Reader.Configuration.IgnoreQuotes = true;
            Reader.Configuration.IgnoreQuotes = false;
            Reader.Configuration.MissingFieldFound = (string[] a, int b, CsvHelper.ReadingContext c) => stuffer(a, b, c);
            return Reader[headerFieldCaption];
        }

I don’t even know why I had that line in the first place, maybe from an example I stole read on the ‘net somewhere.

Anyhow, thanks again for your concern and prompt responses. Sorry to have troubled you on my mistake.
Regards,
Rick

**Comment by JoshClose** [comment]
`IgnoreQuotes` will treat the quote character like a normal character, and not like a special CSV character. Special characters in CSV files are `"`, `,`, and `\r\n`. Since it's treated as a normal character, it doesn't see the field as being "quoted" or "escaped", so the commas inside that field are seen as a new field, and not a part of a single field. In a normal case you should never use `IngoreQuotes = true`. It's there for people that have really badly malformed files, and need to handle that themselves.

**Comment by papiermache** [comment]
Hi Josh, thanks for the explanation, I guess the perils of cut n’paste programming.

final question tho (and if this is in the docs somewhere please just point me there) can your library handle TAB delimited instead of comma delimited?

Regards, Rick.

**Comment by JoshClose** [comment]
`cvs.Configuration.Delimeter = "\t";`

I tried to make the library be as simple as possible, where by default you should only have to do `var records = csv.GetRecords<MyType>();`, but you can do more to configure if you want.

**Comment by papiermache** [comment]
poifect !  Thx Josh.
