### ISSUE TITLE
Unable to write string from List<string> to the .csv file

### ISSUE THREAD

**Issue by TiredOfProgramming** [JoshClose/CsvHelper#997]
CsvHelper version - 7.1.0
.NET version - 4.7

I have a simple list:
`List<string> values = new List<string>();` 

Then I do:
```
values.Add("AA");
values.Add("AB");
values.Add("AC");
values.Add("BA");
values.Add("BB");
values.Add("BC");
```

Then I declare **CsvWriter** according to the **CsvHelper** documentation:

```
using (TextWriter writer = new StreamWriter(@"C:\TestFolder\test.csv"))
            {
                var csv = new CsvWriter(writer);
                csv.Configuration.HasHeaderRecord = true;
```

I created a file _test.csv_ and added _ticker,price_ as headers. My initial plan was to write tickers from the values List on each separate row into the .csv file, and then add corresponding prices from another List

Loop to write `values `to the .csv file:

```
foreach (var value in values)
                {
                    csv.WriteRecord(value);
                    csv.NextRecord();
                }
                writer.Flush();
}
```
However, on the line `csv.WriteRecord(value);` I'm getting this nice and beautiful error message: `CsvHelper.Configuration.ConfigurationException: 'Types that inherit IEnumerable cannot be auto mapped. Did you accidentally call GetRecord or WriteRecord which acts on a single record instead of calling GetRecords or WriteRecords which acts on a list of records?'`

Logically thinking I can answer the question in the error: yes, I'm writing single record and that's why I'm using **WriteRecord** method, not sure if there is any accident here. Is it possible with the help of **CsvHelper** library to write single string to the file? Or may be there is an issue? Please advise.

**Comment by JoshClose** [comment]
A record is a whole row. A field is a single column/cell in that row. You'll want to use `WriteField` instead.

**Comment by TiredOfProgramming** [comment]
Thanks @JoshClose for the clarification and fast response. I was confused with the naming convention believing **WriteRecord** method is an actual record of type string or int or byte or double......in singular form

**Comment by JoshClose** [comment]
Think of record like a row in a table. I believe that's where I pulled the terminology from.
